### ISSUE TITLE
Display project name in console's title

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#10018]
### Versions
```
Angular CLI: 1.7.0
Node: 8.9.4
OS: win32 x64
```

### Repro steps
* Run `ng serve`

### Observed behavior
```
Window title is `ng`
```

### Desired behavior
Window title should be the project's name

### Mention any other details that might be useful (optional)
When running several projects, it's impossible to identify which console window is responsible for the app you're currently working on. Displaying the app's (or project's) name will help identify the correct window.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
