### ISSUE TITLE
Options to disable or configure postcss/autoprefixer

### ISSUE THREAD

**Issue by sam-s4s** [angular/angular-cli#10076]
### Versions
1.7.3

### Repro steps
* Use a property like "display: flex;" in your css
* It will create multiple prefixed styles for browser backwards compatibility

### Observed behavior
Currently there is no way to disable the auto-profixes getting added into your css. This is annoying if you don't want them.

### Desired behavior
For my purposes, I just want to disable it - but I imagine some people would like to configure it.

Could provide config options in the .angular-cli.json file?

**Comment by coryrylan** [comment]
https://github.com/angular/angular-cli/wiki/stories-autoprefixer

**Comment by sam-s4s** [comment]
Sorry, I'm not sure how that helps with my problem? I read that before posting this issue, but I couldn't find anything about disabling or configuring the utility inside angular-cli.

At best it seems to have options of what browsers to target. I just want to disable it - I don't want it messing with my css (that I'm creating specifically to target Chromium).

Cheers
Sam

**Comment by sam-s4s** [comment]
My team is still having trouble with this issue...

All of the additional styles that are being automatically added in seem to be creating some unwanted side-effects in rare cases.

Would be great to disable this...

**Comment by DaSchTour** [comment]
I've similar issue. I would like to configure autoprefixer to not emit IE grid prefixes by setting the grid option to false.
https://github.com/postcss/autoprefixer#options

The inital "problem" is, that I get warning for using auto-fill and grid-auto-rows which are not supported in IE, although I excluded IE through browserlist.

https://github.com/postcss/autoprefixer/issues/1137

The suggestion is to disable grid (although it is by default) but I guess it might be enabled through angular-cli

**Comment by Dan503** [comment]
There are going to be many people that will want to disable grid translations.

The reason that it is disabled in Autoprefixer by default is because it places many restrictions on the users ability to use CSS Grid. People need to be aware of the limitations and intentionally buy into those limitations to use Autoprefixer's grid translations.

It's totally feasable that a user wants the site to generally work in IE (so allow IE prefixes) but wants IE to use a fallback layout rather than be restricted by IE's limited implementation of CSS Grid. At the moment that is not possible in angular-cli.

**Comment by mgechev** [comment]
@sam-s4s `ngx-build-plus` is the idea solution for customizing the Angular CLI's build. I'd recommend you to give it a shot. If somehow it doesn't let you configure postcss, please open a new issue with details. Thanks!
