### ISSUE TITLE
Unable to generate a scoped library with v6 rc0

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#10172]
### Versions
```sh
Angular CLI: 6.0.0-rc.0
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.0.10
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-ng-packagr: 0.0.4
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0
```

### Repro steps
* Create a new cli project with `ng new xxx`
* `cd` into the new project
* Try to generate a library with a scoped name: `ng g library @xxx/core`

### Observed behavior
It throws the following error in the shell:
```sh
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
```

### Desired behavior
It should generate a library named `@xxx/core` in the folder `projects/xxx-core` or maybe `projects/xxx/core` or even `projects/core` with the correct package name `@xxx/core` in the package.json file.

If it's not possible, then it should throw an error message that explains that it doesn't support scoped package names.

**Comment by about-code** [comment]
I suggest to generate a folder structure where the package name is a correct directory path structure - similar to how scoped packages are installed into the `node_modules` folder. 

So when generating a scoped package with `ng g library @xxx/core` where the package name in `package.json` will be `@xxx/core` CLI should generate a folder structure 

```
 |-@xxx
    |-core
       |-package.json
```

Not only would it be compatible with npm layout. It is likely to work better with VSCode's auto-import suggestions. For example consider a monorepo folder structure similar to the Angular repos. You would probably generate a library in the `packages` folder then.

```
${PROJECT_ROOT}
    |-node_modules
    |-packages
    |    |-@xxx
    |    |    |-core
    |    |       |-package.json
    |    |       |-index.ts
    |    |-@foo
    |    |    |-bar
    |    |       |-src
    |    |           |-Foo.ts
    |    |       |-package.json
    |    |       |-index.ts
    |    |-...
    |-tsconfig.json
```
Now if you attempt to use a class `Foo` exported by `index.ts` of package `@foo/bar` you ideally want 
VSCode to suggest an absolute import

`import {Foo} from "@foo/bar";` 

I've been successful to make this work in VSCode 1.19 but it temporarily stopped working in 1.20 or 1.21 after some refactorings. Absolute paths might be working again with latest VSCode versions and with TS 2.8. See https://github.com/Microsoft/TypeScript/issues/20619.

VSCode auto-import with absolute paths required some prerequisites in 1.19:
-  `@foo/bar` must be a valid path in the directory referenced via `baseUrl` in `tsconfig.json` 
- `@foo/bar` must be declared as a dependency in the importing package's `package.json` (that of `@xxx/core`)
- `baseUrl` and a generic path mapping must be set in `tsconfig.json`

*Example `tsconfig.json`*
```
"baseUrl": "./packages",
"paths": {
    'baseUrl'. */
       "*": ["./*", "../node_modules/*"]
    }
}
```

Generating the full package name as a directory structure would also makes it easier to compile an application from a monorepo structure. For example you could make webpack resolve `"@foo/bar"` from the `packages` folder by configuring

```
module: { 
     resolve: ["./packages", "./node_modules"]
}
```
in your webpack config. Then you can compile and bundle libs in the monorepo into an application without having to link them with `npm link` at all because TS and webpack can directly resolve them from `packages` rather than `node_modules`.

**Comment by about-code** [comment]
@gms1 Brocco has answered the reasoning in one of the commit discussions. They drop the `@` because it causes problems with path auto-completion on mac and windows console terminals, which they want to provide to users working a lot on the terminal (or from within VSCode e.g.). 

As far as I understood instead of a generic path mapping (which would be possible when sticking to package name convention) the CLI will generate a path mapping for each lib in `tsconfig.json` which maps a package `import` path including the `@`  onto a filesystem path without the `@`. So eventually, there will be no difference in how you would `import` a package in source code. Writing `import from "@foo/bar"` will work.

**Comment by about-code** [comment]
@gms1 See here https://github.com/angular/devkit/pull/646#issuecomment-380136599
