### ISSUE TITLE
Warning about i18n locale files

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular-cli#10203]
### Versions

```
Windows 10
Angular CLI: 6.0.0-rc.1
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/cli: 6.0.0-rc.1
@angular/flex-layout: 5.0.0-beta.14
@angular/material-moment-adapter: 6.0.0-rc.1
@angular/material: 6.0.0-rc.1
@angular-devkit/architect: 0.0.10
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.5.1
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.1
@schematics/update: 0.5.1
typescript: 2.7.2
webpack: 4.1.0
```
### Repro steps

* Step 1
  Setup internationalization:
```ts
import { registerLocaleData } from '@angular/common';

import localePTBR from '@angular/common/locales/pt';
registerLocaleData(localePTBR);
``` 
### Observed behavior
Emits a warning:

```
WARNING in ./node_modules/@angular/common/locales/XX.js
10:24-31 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

### Desired behavior

Not emit this warning

### Mention any other details that might be useful (optional)
I'm not really sure if this warning affects the app. It happens in dev mode. I couldn't manage to build a prod compilation yet (my first try after the upgrade was unsuccessful)

**Comment by aastrouski** [comment]
I have the same warning in RC.2

And one more issue:
For PROD mode If locale set in angular.json as "i18nLocale": "en-US" (not via registerLocaleData function), then an error occurs in @angular/common module in registerLocaleData function: "Cannot read property 'toLowerCase' of undefined", because localeId is undefined.

**Comment by about-code** [comment]
This is a webpack warning which is triggered when webpack can't statically analyse uses of e.g. `require.ensure` which can be caused by passing variables into `require()` or `require.ensure()` or dynamically constructing the URLs/module paths you pass into the functions.

Probably by dynamically loading things based on a given locale?

See https://github.com/webpack/webpack/issues/2675#issuecomment-269417932

**Comment by filipesilva** [comment]
This was an issue with Angular itself in https://github.com/angular/angular/issues/23217, and has since been fixed there.

**Comment by ocombe** [comment]
it should be fixed in rc4 once it's released
