### ISSUE TITLE
I can't make Bootstrap Popover work with angular-cli

### ISSUE THREAD

**Issue by gustav474** [angular/angular-cli#10223]
### Versions

Ubuntu 16.04 (x64)

-  typescript 2.5.3
-   angular-cli 1.7.3
-   bootstrap and `@types/bootstrap` 4.0.0.
-   jquery and `@types/jquery` 3.3.1

### Repro steps
Add in **angular-cli.json** external scripts:
`"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/popper.js/dist/popper.min.js",        
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "assets/js/main.js" 
      ],`
Add in **main.js** to initialize popover:
`$(document).ready(function(){
  $('[data-toggle="popover"]').popover(); 
});`
Add in **tsconfig.app.json**:
`"types": [
      "jquery"
    ]`
And in **app.components.html**: 
`<button type="button" class="btn btn-lg btn-danger" data-toggle="popover" title="Popover title" data-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>`

### Observed behavior
When i build and loaded project i can not see $ and Popper in window objecta and popover don't work.
What i do wrong?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Off the top of my head the reason it doesn't work is because you add `$(document).ready(function(){ $('[data-toggle="popover"]').popover(); });` to `main.ts`. 

You see, when the code in `main.ts` runs, the html does not yet contain your button. The button will be created dynamically by angular from the template. So Jquery cannot find it before then.

Try adding your code in the `afterInit` hook of your component. That should guarantee it runs after the template is there.
