### ISSUE TITLE
(rc4) ng test errors with 0 tests executed

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#10333]
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 8.9.4
OS: darwin x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, http, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.6
@angular/cdk                      6.0.0-rc.1
@angular/material                 6.0.0-rc.1
@angular/service-worker           1.0.0-beta.16
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-turbo-rc.4
typescript                        2.7.2
webpack                           4.5.0

```

### Repro steps

* clone https://github.com/angular/angular/pull/23234
* `cd angular/aio`
* `yarn install`
* `yarn ng test`

### Observed behavior
karma starts, but doesn't run any tests:
```
Chrome 65.0.3325 (Mac OS X 10.13.3): Executed 0 of 0 ERROR (0.021 secs / 0 secs)
```

as if no specs were loaded when karma started.

### Desired behavior
unit tests run :)

**Comment by IgorMinar** [comment]
I tried to scaffold a new cli project and copy the contents of the aio/src/ directory into it + install all missing dependencies and got the same result

**Comment by filipesilva** [comment]
I've been looking into this and it seems like something is preventing webpack from 'scooping' up all the spec files.

In `test.ts`, these are are the lines responsible for rounding up all specs:
```
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);/
```

In a brand new project you can add the line below after the ones above to see the list of tests ran:
```
console.log(context.keys());
```

You will see the following line in the karma output:
```
HeadlessChrome 65.0.3325 (Windows 10.0.0) LOG: ['./app/app.component.spec.ts']
```

In AIO with this PR, that doesn't happen. In fact, nothing at all is printed. Console logs after the `require.context` don't seem to run at all.

But if you go into `src/environments/environment.ts` and comment out the two following lines, tests run again:
```
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
```

The test will fail, but that doesn't surprise me since they are ran in JIT and thus need reflect.

But something weird is happening with reflect.

**Comment by filipesilva** [comment]
I think there an import somewhere that breaks things.

Trying to scoop up this single test works:
```
const context = require.context('./app/shared/', true, /registry\.spec\.ts$/);
```

**Comment by IgorMinar** [comment]
this was due to our unusual polyfill setup. See the commit above for solution.
