### ISSUE TITLE
New Angular-cli didn't generate webpack

### ISSUE THREAD

**Issue by hiepnguyen93** [angular/angular-cli#10354]
![image](https://user-images.githubusercontent.com/24579838/38805536-5a0a81f8-41a0-11e8-866e-e2887a520090.png)

- After upgrade to angular-cli 1.7.3 then i found missing webpack, Please help me check this issue

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
