### ISSUE TITLE
cli6rc4 allowOutsideOutDir not works

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular-cli#10350]
### Versions
```
Angular CLI: 6.0.0-rc.4
Angular*: 6.0.0-rc.5
```

### Repro steps
"allowOutsideOutDir":true still not works here (6rc4)?

in my architect.build.options i have:
```
"assets": [
{
  "glob": "favicon.ico",
  "input": "src",
  "output": "../",
  "allowOutsideOutDir":true
},
{
  "glob": "**/*",
  "input": "src/assets",
  "output": "../assets",
  "allowOutsideOutDir":true
}
]
```

> Data path ".assets[0]" should NOT have additional properties(allowOutsideOutDir).

### Mention any other details that might be useful (optional)
this issue https://github.com/angular/angular-cli/issues/10284 seems improve message error but not fix allowOutsideOutDir ?

**Comment by filipesilva** [comment]
We did remove the `allowOutsideOutDir` option, yes. It didn't make as much sense in the new multi-project setups, nor did it make sense with how we now handle paths for assets.

Can you tell me about your use case please? You seem to be outputing all assets outside the output dir for the project.

**Comment by istiti** [comment]
Yes correct i have multiple language. So /assets folder is same for all language and without output my assets outside each language make them exist everywhere

/fr
/de
/en
/it
Have their /assets which are exactly same i just want have it once and this option allowed it.

This option was discussed and was added by @hansl itselft as option to cover usecase (see closed issues) i don’t see how can I here have this behavior without it. Thanks

**Comment by istiti** [comment]
the problem:
- caching assets (styles, images, icons, fonts) once not for each language because they are exactly same
- if application is different their code is not different, because we must today build multiple app for different language, due to current "i18n poor" functionality.


I understand what you said but today I have 6mo `/assets` folder and it is in all my `/{language}` folder ! Big dammage, not you think so ?

**Comment by dcarabott** [comment]
@filipesilva My use case is a little bit different. The way we serve content to the client is always from the root folder on the server. Say I have 2 applications that share assets. So in `dist` I have `application1` and `application2`. In these applications I'm linking to some asset `box.jpg` so a typical link would be `assets/box.jpg`. The server would try to fetch this asset as `assets/box.jpg` not `application1/assets/box.jpg` or  `application2/assets/box.jpg` since it will always fetch from the root. The server is going to return a 404. Previously I built the assets outside the application folder which would solve my issue.

**Comment by hansl** [comment]
Marking this as required for the release, but only a decision needs to be made.

**Comment by alfaproject** [comment]
I have a multi-locale application as well, and my use case is this:
```
dist/
  app1/
    en/index.html
    fr/index.html
    sitemap.xml
  app2/
    en/index.html
    de/index.html
    sitemap.xml
```

`sitemap.xml` in that example needs to be 'outside' the destination path which is `dist/app/locale`.

@filipesilva @hansl am I doing things wrong with how CLI is supposed to work now?

**Comment by dcarabott** [comment]
Are there any updates?

**Comment by pbredenberg** [comment]
My use case FWIW: I maintain 4 (and more to come) Angular apps inside a large project with JSON assets that contain localization strings. These JSON assets are exported from a C# API server, and are consumed by my apps along with other legacy applications that need to read the same strings. It doesn't make sense then to store those assets inside my CLI project. Without the convenience of `allowOutsideOutDir` I'll have to script it elsewhere. Not terrible, it'll be an adventure.

**Comment by alan-agius4** [comment]
Closing this option was removed on purpose and writing outside might potentially causes problems when deploying such as when using `ng deploy`.
