### ISSUE TITLE
ng new : Renaming AppComponent --> RootComponent

### ISSUE THREAD

**Issue by nicolasploquin** [angular/angular-cli#10359]
### Versions
```
Angular CLI: 1.7.4
Node: 9.4.0
OS: win32 x64
Angular: 5.2.9
```

### Repro steps

* Create a new project with `ng new first-project` command
* Create a new component with `ng g c second` command

### Observed behavior
Ng-Cli produces a project with a first component named AppComponent with selector `app-root`
When we generate a second component using `ng g c second`, Ng-Cli produces a component `SecondComponent` with selector `app-second` in a folder named `second`.
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
}
```

### Desired behavior

It would be more consistent to name the root component `RootComponent` and keep `app` as a reference to application module only, just like other components are generated.
```
@Component({
  selector: "app-root",
  templateUrl: "./root.component.html",
  styleUrls: ["./root.component.css"]
})
export class RootComponent {
  title = 'app';
}
```

**Comment by sahilbabbar** [comment]
Don't know how the renaming of `AppComponent` to `RootComponent` will help, because it doesn't seem to break any convention or naming pattern. Consider changing the prefix of the app to `foo`, so perhaps now things seem nice and even; and justifies the present naming convention. Moreover, presently and also going forward, Angular may have some in-built classes which have the naming convention like `Root*`, so it will create a confusion among dev entities and in-build ones.

In case you are putting forward some better naming convention than the present one, please do justify it .

**Comment by alan-agius4** [comment]
@StephenFluin / @robwormald any thoughts about this?

**Comment by StephenFluin** [comment]
I can see some of the merit of the change from the perspective of a single app. From many perspectives the current name (AppComponent) is right, especially when there are multiple applications on the same page (multiple Apps, each with their own root).

Moreover, the global cost to change developer behavior / training / courses / guides is likely not worth this change.

**Comment by alan-agius4** [comment]
Closing as per above. 

Thanks.
