### ISSUE TITLE
`--configuration` option incorrectly treated as array

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#10398]
Since the `--configuration` option is not of type array, only the last occurrence should be taken into account.

E.g. given `ng build --configuration=foo --configuration=bar`:

- Expected to be treated as `--configuration=bar`.
- Actually treated as `--configuration=foo,bar`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
