### ISSUE TITLE
Update Webpack version

### ISSUE THREAD

**Issue by apiweb** [angular/angular-cli#10445]
### Versions
```
v6.0.0-rc.5
```

### Repro steps
Use the command:
```
ng -version
```

### Details
Please update the version of Webpack and Webpack Dev Server to the latest versions:
**[Webpack](https://github.com/webpack/webpack):** [4.6.0](https://github.com/webpack/webpack/releases/tag/v4.6.0) (4/17/2018)
**[Webpack-Dev-Server](https://github.com/webpack/webpack-dev-server):** [3.1.3](https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.3) (4/8/2018)

The new versions of both libraries bring several new improvements in performance, as well as greater speed in incremental builds

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
