### ISSUE TITLE
When i create a new project generated by angular cli not working?

### ISSUE THREAD

**Issue by vikasshetty07** [angular/angular-cli#10528]
### Versions

Angular CLI: 1.7.4
npm:5.6.0
Node: 8.11.1
OS:  Windows 7 win32 x64

### Repro steps

* install latest CLI (1.7.4) using npm install -g @angular/cli
* generate new project using ng new demoAng4
* then cd into demoAng4
* And launch the project using ng serve

### Observed behavior
The browser for localhost:4200 shows blank with the afore-mentioned errors

`vendor.bundle.js:523 Uncaught SyntaxError: Invalid or unexpected token
inline.bundle.js:55 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (inline.bundle.js:55)
    at Object.0 (main.bundle.js:66)
    at __webpack_require__ (inline.bundle.js:55)
    at webpackJsonpCallback (inline.bundle.js:26)
    at main.bundle.js:1`

### Desired behavior
App works normally

``
Please help me to find what is the problem?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
