### ISSUE TITLE
Subtitles not working after uglifying the code by Angular CLI

### ISSUE THREAD

**Issue by qstiegler** [angular/angular-cli#10533]
We are using the video.js Player in combination with an angular-cli project. By the `addRemoteTextTrack` method of the player, I add subtitles to the video.

```
this.vjsPlayer.addRemoteTextTrack({
    kind: '/path/to/file.vtt',
    label: 'Test',
    src
}, true);
```

This works great when I´m in the development mode of the project. But when I uglify the code by angular-cli by the command `ng build --prod`, the subtitles will not update anymore. What I mean is, that it stays on the subtitle text when you have activated the subtitles but the text does not get updated.

I´m pretty sure this occurs cause of uglifying, as the result of the following command is working: `ng build --environment prod --sourcemaps false --output-hashing all --named-chunks false --extract-css true --aot true --build-optimizer true`. If I understood the documentation correctly, then the only additional thing is uglifying the code.

Most of the time I use Chrome for development but this happens in every browser.

## Versions
- "video.js: "6.8.0"
- "videojs-contrib-dash": "2.9.3"
- "videojs-contrib-hls": "5.14.1"
- "@angular/cli": "1.7.4"
- "@angular/core": "5.2.10"

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
