### ISSUE TITLE
[Feature Request] Option for more aggressive code splitting

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#10550]
As a follow-up to #10525, I'll also add that the other thing we were using `ng eject` for was to configure aggressive code splitting for more effective caching. Losing this isn't necessarily a blocker for us, but would be nice to see something similar gain official support in lieu of `ng eject`.

For reference, this is what our implementation looked like:

```
const chunks	= getListOfAllThirdPartyDependencies().
	map(s => path.join('node_modules', s)).
	concat(getListOfSomewhatLargeFirstPartyModules()).
	map(s => ({
		name: 'commons__' + s.replace(/\//g, '_'),
		path: s
	}))
;

const entryPoints	= ['inline', 'polyfills', 'sw-register', 'styles'].
	concat(chunks.map(chunk => chunk.name)).
	concat(['vendor', 'main'])
;

const commonsChunkIndex	= config.plugins.indexOf(
	config.plugins.find(o => o instanceof CommonsChunkPlugin)
);

for (const chunk of chunks) {
	config.plugins.splice(
		commonsChunkIndex,
		undefined,
		new CommonsChunkPlugin({
			name: chunk.name,
			chunks: ['main'],
			minChunks: o => o.resource && o.resource.startsWith(
				path.join(process.cwd(), chunk.path)
			)
		})
	);
}

const htmlWebpackIndex	= config.plugins.indexOf(
	config.plugins.find(o => o instanceof HtmlWebpackPlugin)
);

if (htmlWebpackIndex > -1) {
	config.plugins.splice(
		htmlWebpackIndex,
		1,
		new HtmlWebpackPlugin({
			template: './src/index.html',
			filename: './index.html',
			hash: false,
			inject: true,
			compile: true,
			favicon: false,
			minify: false,
			cache: true,
			showErrors: true,
			chunks: 'all',
			xhtml: true,
			chunksSortMode: (left, right) => {
				let leftIndex	= entryPoints.indexOf(left.names[0]);
				let rightindex	= entryPoints.indexOf(right.names[0]);

				if (leftIndex > rightindex) {
					return 1;
				}
				else if (leftIndex < rightindex) {
					return -1;
				}
				else {
					return 0;
				}
			}
		})
	);
}
```

**Comment by dgp1130** [comment]
Hi @buu700, we're triaging existing issues and revisiting those that might have fallen through the cracks. Is this still a concern for you? Is current route-based code splitting sufficient for your use case, or do you need even more aggressive code splitting?

https://web.dev/route-level-code-splitting-in-angular/

**Comment by buu700** [comment]
Thanks for following up @dgp1130! This would still be a very nice to have for us, and lazy loading isn't an option for my use case.

Specifically, what we were doing prior to Angular 6 was splitting every single node_module as a separate chunk (as well as a few specific internal modules that were large and didn't change often).

**Comment by dgp1130** [comment]
Can you elaborate on why route splitting lazy loading doesn't work for your use case?

I'm not an expert on performance, but lazy loading every `node_module` individually sounds like it would perform far worse than traditional route splits. Can you share anything about the use case and how/why this performs better than more common lazy loading options?

**Comment by buu700** [comment]
Splitting based on node modules and large internal modules was a solution we came up with to optimize in favor of caching as much as possible at the cost of potentially missing out on some minification and/or tree shaking optimization, which made sense to us because our application is quite large (close to 20 MB uncompressed, which is primarily static assets and third-party modules).

We could consider route-based splitting as well, but as mentioned lazy loading isn't an option for us, so this would have to be implemented as webpack chunks rather than lazily loaded scripts.

Specifically, because of [WebSign](https://www.cyph.com/websign) we can't just use Angular's built-in lazy loading implementation; we'll have to build our own implementation into WebSign, which is on the roadmap but not an immediate priority.

**Comment by dgp1130** [comment]
Ok I see, thanks for the additional details. WebSign is a pretty specific use case so I don't think we have the bandwidth to support a special code splitting system for that.

While we don't have `ng eject` anymore, there are some community projects that allow you to directly edit the Webpack configuration of Angular builds (specifically [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders) and [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus)). These aren't officially supported as we don't consider Webpack to be part of our public API, but they provide some extra flexibility you can use to solve this particular problem.

**Comment by buu700** [comment]
Got it, that makes sense. That said, is this not a feature that would be useful in general? It seems generally like a pretty separate concern from lazy loading, more like `vendorChunk`++. I expect that many projects with dependencies that don't change too often would prefer this approach.

**Comment by clydin** [comment]
The vendor chunk option’s primary purpose is in development scenarios to support reduced rebuild time in watch mode.  It is not recommended for use outside this scenario.  Using the option in production scenarios will in the majority of cases lead to large increases in overall application size.  A variety of optimizations cannot take place with the option enabled.

It is also recommended to keep library versions as up-to-date as possible to avoid defects and security vulnerabilities.  Doing so will invalidate a large amount of the caching regardless of the splitting granularity.

Also when using lazy routing and without vendor chunking, libraries that are only used in one route will be contained within that particular route chunk.  If used in more than one, that library will be separated out into a chunk containing all common code for those specific routes.  This provides increased splitting granularity but along end user functionality boundaries instead of library boundaries.

However, if a library is preferred to be split, dynamic imports could also be used.  This also has the benefit in certain situations of allowing the library to be loaded only when actually needed within the owning code rather than on evaluation as with a static import.
