### ISSUE TITLE
CLI non existant environment (-e) usage error message

### ISSUE THREAD

**Issue by rzvjerkovic** [angular/angular-cli#10595]
### Versions
```
Angular CLI: 1.7.3
Node: 9.5.0
OS: win32 x64

```

### Repro steps
* Step 1 ng serve -e nonExistantEnvironment

### Observed behavior
```
ERROR in Cannot read property 'length' of undefined
```

### Desired behavior
CLI used to say (I don't remember the exact wording):
"Environment "nonExistantEnvironment" does not exist"

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by rzvjerkovic** [comment]
Works as expected now.

Thank you!
