### ISSUE TITLE
Creating a sub route add ... 

### ISSUE THREAD

**Issue by DNRN** [angular/angular-cli#1059]
My OS node and angular-cli version:
angular-cli: 1.0.0-beta.5
node: 4.4.2
os: win32 x64

When generating a sub route with:
`ng generate route parent/child `

There are added ... in the parent route which breaks the routing.

The fix is easy though, it's just remove the ... from the parrent.

**Comment by delasteve** [comment]
There was a PR (https://github.com/angular/angular-cli/pull/876) out that did fix this, it was closed by the author though because he thought it was fixed someplace else. 

I checked the commit history, but don't see a commit that fix it. I did see @Brocco's commit which removed the route generation temporarily, but the history of that file doesn't show it being fixed.

https://github.com/angular/angular-cli/commits/master/addon/ng2/blueprints/route/index.js

**Comment by filipesilva** [comment]
I'm closing this issue as obsolete, at the moment route generation is disabled and is being reworked for the new router.
