### ISSUE TITLE
6rc.10 installation flow

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10607]
### Versions
```
local and global cli 6 rc 9
```

### Repro steps
Inside my cli project I want update from rc9 to rc10 so: 
1. npm uninstall @angular/cli -g
2. npm i @angular/cli@next -g

### Observed behavior

```
=================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

ng update @angular/cli
==================================================================
```

I can read my config's changed so I run : `ng update @angular/cli`  then I get: 

```
Your global Angular CLI version (6.0.0-rc.10) is greater than your local
version (6.0.0-rc.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
            Found a modern configuration file. Nothing to be done.
```

### Desired behavior
Is this expected behavior ? Seems a little bit weird to me.

**Comment by alan-agius4** [comment]
`ng update` acts different than `npm i`, because `ng update` runs migration rules that will update your project to match the version that you are installing.

`ng update @angular/cli` itself though shouldn't not install pre-released versions, unless specified to do so with the `--next` flag, which seems to have been addressed.
