### ISSUE TITLE
Remove @angular/pwa from my list of dependencies

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10602]
### Versions
Latest master

### Repro steps
ng add @angular/pwa

### Observed behavior
@angular/pwa is now added as a dependency in my package.json.

### Desired behavior
I would like @angular/pwa to not be a dependency of my app.

**Comment by cyrilletuzi** [comment]
Why want to remove it? It's introduced by #10585 which I think is the good thing to do for most packages, as dependencies should be explicit.

For now, `@angular/pwa` is a special case, as it's just used to setup PWA and not used anymore thereafter. But it could be augmented in the future and become necessary to have it in the project.

**Comment by davinkevin** [comment]
Should it only be in `devDependencies` instead ?

/cc @Neonox31 @dabbid

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
