### ISSUE TITLE
Generation of library produces tslint error like "'Component' is not included in a module"

### ISSUE THREAD

**Issue by Nodarii** [angular/angular-cli#10638]
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.0-rc.2
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

### Repro steps
* `ng new projectX && cd projectX && ng generate library my-lib`
* Open project in Webstorm (I'm using v2018.1)

### Observed behavior
Project builds successfully but linter shows error like: 
Error:(3, 2) ng: Component 'MyLibComponent' is not included in a module and will not be available inside a template. Consider adding it to a NgModule declaration
![image](https://user-images.githubusercontent.com/1251685/39630855-4ae26138-4fb9-11e8-9649-0c08ca5ba242.png)
TypeScript config:
![image](https://user-images.githubusercontent.com/1251685/39632435-c05ce2f4-4fbd-11e8-85d6-39cafbe02551.png)

 
### Desired behavior
Cli should produce code that passes all tslint checks.

### Mention any other details that might be useful (optional)
Of course it it is not critical, but kind of annoying issue

**Comment by hansl** [comment]
Hi @Nodarii,

Tried to reproduce here and couldn't.

The `MyLibComponent` is properly added to the `MyLibModule`, everything passes the linting. This looks like an issue with either WebStorm or more likely the Language Service that might be confused.

**Comment by Nodarii** [comment]
Ooops, it's my bad. It is not 'tslint' error. Tooltip show prefix `ng:`. Also I run tslint from command line and it passed. It's definitely related to language service. Do you want me to create issue there?

**Comment by cyrilletuzi** [comment]
Feedback: this error comes from the Angular Language Service. There are similar problems in VS Code with the official ALS extension.

Problem is: as the check is quite complicated and relies on multiple files checks, the reaction of the Angular Language Service is often not in real time. You often have to change and save the file, and on computers with old hardware, the error can stay forever until relaunching the editor (having given a lot of Angular courses in many enterprises, I can say it happens quite often).

@chuckjaz  As this check is now already done by CLI compilation, in a more reliable way than in the Angular Language Service, I think this check should be deleted (or at least disabled by default) in Angular Language Service.

For info, it's very disturbing for new comers, because they stay stuck on this false error, not knowing what to do as there is really nothing to do.

**Comment by Nodarii** [comment]
@cyrilletuzi, this error doesn't disappear after WebStorm relouch. 
Did I understand you right? You recommend to disable angular language service?

**Comment by multimike77** [comment]
I believe I found a solution for the problem. More details can be found here:
https://youtrack.jetbrains.com/issue/WEB-28091#u=1527499821194
https://blog.jetbrains.com/webstorm/2018/02/webstorm-2018-1-eap-181-3741/

So adding tsconfig.lib.json to the patterns, seems to work for me.
