### ISSUE TITLE
Feature Request : ng build to include a --base-href <base>

### ISSUE THREAD

**Issue by timlevett** [angular/angular-cli#1064]
Much like what happens as part of [github deploy](https://github.com/angular/angular-cli/blob/f8f81796c6c4c8768780ab9b38562f33ac988cb7/addon/ng2/commands/github-pages-deploy.ts#L170), have a feature that you can supply a base-href that will be added to the `index.html` during the `ng build` command

Usage : `ng build --base-href <base>`
Example : `ng build --base-href home`
Replaces `<base href="/">` with `<base href="/home">` in `index.html`

**Comment by dzonatan** [comment]
I've started and actually did some work on this because I missed it in webpack version.. and I really need it. :|

To make sure I'm in the right way I need someone of angular members approval about how this argument should work. 
Is it good for you to have such case scenarios:
- if no `--base-href` tag provided then **do nothing** (keep the template index.html untouched). In such case the user is able to use `base` tag purely. This also ensures to don't have any breaking changes.
- if `--base-href x` provided and `base` tag **doesn't exists** then insert `<base href="x">` in header.
- if `--base-href x` provided and `base` tag **already exists** then replace only the "href" attribute of base tag. (In case developer uses additional attribute(s) like "target").

Also I'm thinking that instead of auto-prefixing url with slash whole url should be provided by developer for the case when I want to overwrite my `/xxx/` with just `/`.

**Comment by filipesilva** [comment]
I was gonna pick this one up, but if you're working on it I'm happy to help. I'm speaking as myself now, design for this feature hasn't been discussed within the team.

There's a couple of extra things you have to look into when developing this feature:
- needs to be tested
- the github deploy feature already does a regex base replacement, so it needs to be changed to use this feature
- needs to conform to router best practices found in https://angular.io/docs/ts/latest/guide/router.html

As far as behavior goes, I think your proposal makes sense. I also agree the developer should provide the whole URL.

**Comment by isleshocky77** [comment]
@dzonatan I'm not seeing it anywhere in the commit, but are you able to configure this option in the environment files instead?
