### ISSUE TITLE
Better Error message

### ISSUE THREAD

**Issue by JaanaTwt** [angular/angular-cli#10808]
I'm trying to create a routing file using cli and by mistake i missed the module name. But what i see in the response is:

```
$ ng g m --routing
Cannot read property 'lastIndexOf' of undefined
```

I think we should display proper error message like provide the module name etc.

**Comment by czeckd** [comment]
The problem also exists if a module name is give, but the arguments are placed in the wrong order, such as:

```
> ng g module --dry-run foobar
Cannot read property 'lastIndexOf' of undefined
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
