### ISSUE TITLE
Readme.md - prerequisites leads to nothing

### ISSUE THREAD

**Issue by fdonzello** [angular/angular-cli#10872]
Just go to the homepage of this repo and click on "prerequisites" anchor. It leads nowhere.

**Comment by Brocco** [comment]
"prerequisites" exists twice in the readme, once as the header for the Prerequisites section and the other below it in the "Installation" section. The link is within the page and scrolls to the Prerequisites section which may not scroll at all because it may already be in view.

Thanks for the issue, but I believe this is working as intended.

**Comment by fdonzello** [comment]
oh yes, my bad.
Since the prerequisites paragraph is very short it could be merged with installation though.

Anyway, sorry again :)
