### ISSUE TITLE
Please consider add "Typings" npm package to "Prerequisites"

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular-cli#1087]
OS - Mac OSX (El Capitan)

Version - 
angular-cli: 0.0.39
node: 5.0.0
os: darwin x64

Repro steps - 
Install angular-cli without Typings npm package.

The log given by the failure - 
"Typings" folder missing
"browser.d.ts" file missing.

Please consider add "Typings" npm package to "Prerequisites"

**Comment by kylecordes** [comment]
I have a request which might the sense be the opposite of this one:  Don't require or ask users to "npm install -g typings". That so easily leads to incorrect results because of version skew. Rather, the user should only need to do that if they explicitly want the convenience of running the tool themselves at the command line without "node_modules/.bin/typings". And even then it only works correctly if the tool (which I believe this one does) has code in it to ignore the global installation (making all those extra bits wasted anyway) and run the project local one.

When something like CLI needs to call something like typings, it should only always ever used the locally installed one, never use a globally installed one even if it is present. Therefore, if it has a dependency, it does not need to describe it as a prerequisite, rather it needs to simply declare it as a devDependency in the normal way.... Which it already does.

So if there is an actual bug here, then it is some case by which CLI, when it calls typings, erroneously relies on a global install.

**Comment by filipesilva** [comment]
That was old (and erroneous) behavior that has since been fixed, newer versions of the CLI have a local typings install.

There is a bug in beta.6 that requires a global typings install, but that is also unintended and were are looking to fix it: https://github.com/angular/angular-cli/issues/1092
