### ISSUE TITLE
[Improvement] Add 'outputPath' option in builder "@angular-devkit/build-angular:dev-server" schema

### ISSUE THREAD

**Issue by jmesa-sistel** [angular/angular-cli#10885]
### Versions
```
Angular CLI: 6.0.1
Node: 8.11.1
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@angular/pwa                      0.6.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Desired behavior

Add 'outputPath' option in builder "@angular-devkit/build-angular:dev-server" schema, so if this field is used the files will be written.
So we can debug with devserver and at the same time check it in a tomcat or another backend.

### Mention any other details that might be useful (optional)
I have been using 'write-file-webpack-plugin' ejecting the webpack configuration in previous versions.

**Comment by alan-agius4** [comment]
@jmesa-sistel thanks for open the issue. however we should be careful how we increase the scope of the CLI because each new feature means new code to maintain and fix issues in.

In this particular case, you can use https://github.com/manfredsteyer/ngx-build-plus to add addition plugins in the webpack pipeline.

Thanks

**Comment by rodries** [comment]
I already using that addition, also I [fix the bug](https://github.com/manfredsteyer/ngx-build-plus/pull/29) to be able to use write-file-webpack-plugin, but I think the only thing you have to do is set [writeToDisk](https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-) in devServer.
Anyway maybe writeToDisk will be removed in webpack 5 because of [this comments](https://github.com/webpack/webpack/pull/8642#issuecomment-455342804). 
I had to set:
```
output: {
        .....
        futureEmitAssets: false   
    },
```
to get it working ([check pull request](https://github.com/webpack/webpack/pull/8642/files#diff-7a14ca420cc4fa7cf55f788246117e7cR338))
