### ISSUE TITLE
Setting baseHref in angular.json might fix a build, but seems to break serve

### ISSUE THREAD

**Issue by rjcoupe** [angular/angular-cli#10914]
### Versions
```
Angular CLI: 6.0.3
Node: 8.11.2
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* In angular.json, set `projects.<project name>.architect.build.options.baseHref` to, for example, `https://me.github.io/myapp/`.
* `ng build` and observe the correctly functioning result.
* Run `ng serve`, observe that the root page's dependencies (`runtime.js`, `main.js`, etc.) do not load and trigger a 404.

### Observed behavior
```
Javascript dependencies do not load on an `ng serve`-hosted site.
```

### Desired behavior
The served site should load correctly.

**Comment by clydin** [comment]
This is expected behavior.  The base HREF set within the page is `https://me.github.io/myapp/` so the browser will try to access the scripts from that location.  If they are not at that location then a 404 will result.
Typically, a setting with a value such as this would only be set in the production configuration as it is generally only relevant for deployment and not for development.

**Comment by MattiJarvinen-BA** [comment]
There's still something fishy with this. While previously when running ng serve I could hit refresh to force reload the app (if for some reason I made a boo in the code and broke serve or hmr while doing so). Now when I hit refresh while not on localhost:4200/ maybe on localhost:4200/admin the app can't load at all.

Since angular.json is so darn complex and I cannot seem to find proper documentation anywhere detailing use of ng serve and related parameters in angular.json I'm starting to believe this is either a bug or a documentation bug.

ng serve when starting browser from another path than localhost:4200/ gives me 

404s on:
- runtime.js
- polyfills.js
- styles.js
- vendor.s
- main.js

**Comment by tobmaster** [comment]
@clydin I think its indeed needed in development too. Cause when you don't use the hash based routing and youre somewhere deep in the application like http://github.com/mymodule/subroute and I press reload I want it to behave correctly.
But it won't cause it will look for `http://github.com/mymodule/[runtime|polyfills|styles|vendor|main].js` instead. Not sure whats the right way to deal with this.
