### ISSUE TITLE
assets feature is slow

### ISSUE THREAD

**Issue by Wykks** [angular/angular-cli#10993]
### Versions
```
Angular CLI: 6.0.3
Node: 8.11.2
OS: linux x64
Angular: 6.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* Define a big folder in assets (node_modules for example)
* launch ng serve
* save any source file

### Observed behavior
Every rebuild take much more time (~4-5sec) with assets vs none (500ms).

### Desired behavior
Warn users that assets can slow down a lot the rebuild.

**Comment by filipesilva** [comment]
This sounds like a bug. We should be able to fix this so it doesn't take longer.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
