### ISSUE TITLE
Strip/Remove Debug Code in Angular 5+ With the Cli

### ISSUE THREAD

**Issue by vdiaz1130** [angular/angular-cli#10999]
I'm looking for a way to strip debug code when executing build with angular-cli. Something like webpack-strip-block or gulp-remove-code.

For instance, executing something like ng build --prod will do the following:

Original annotated code block:

    genForm(): FormGroup {
        const loginForm = this.fb.group({
            username: '',
            password: ''
        });
        
        /* develblock:start */
        if (environment.envName === 'dev') {
            loginForm.patchValue({
                username: 'fooUser',
                password: 'fooPassword'
            });
        }
        /* develblock:end */
     
        return loginForm;
    }

Resulting code after removing annotated block via build cmd:

    genForm(): FormGroup {
        const loginForm = this.fb.group({
            username: '',
            password: ''
        });
     
        return loginForm;
    }

Technically this code will not be executed in production but there may be a lot of forms that for the sake of time, we'd like to have the option of pre-filling.

Does the CLI support this or is this in the works?

**Comment by sebek64** [comment]
I'm migrating an existing project to Angular CLI and found a way to do this. We need to "flatten" environment file not to contain an object, but rather a bunch of constants - for example, environment.production.ts would look like this:

```ts
export const production = true;
```

Then, any condition based on this flag will be removed in production builds.

The reason it doesn't work with the object is that the object is mutable. The uglifier cannot know whether the value has not been changed since its initial definition.

I also did a few experiments with marking the fields readonly, but this information is stripped during typescript compilation, so uglifier doesn't know about immutability either.

I'd suggest changing default environment file structure to contain plain constants. Should I fill a separate feature request for it? Or are there any serious objections?

**Comment by sebek64** [comment]
Well, I was too optimistic. The workaround described in my previous comment works with rollup, but current angular-cli doesn't remove the unneeded code. At least, it should be able. Either rollup is just better in that compared to webpack, or configuration of uglify-js is different, or some other reason. I don't understand angular-cli so well yet, so I cannot investigate it any further.

**Comment by dgp1130** [comment]
Code gated by constants in if statements should be tree-shaken without the need for a preprocessor. Environments are specifically designed to fit this model, so this should just work out of the box. `ng new` even generates an `environment.production` value specifically for this purpose.

It seems that you're trying to use it as a string (`environment.envName === 'dev'`), which isn't a common use but I think it still works. My local test uses:

```typescript
// environment.ts

export const environment = {
  env: 'dev',
};
```

```typescript
// environment.prod.ts

export const environment = {
  env: 'prod',
};
```

```typescript
// main.ts

if (environment.env === 'prod') {
  console.log('Production!');
  enableProdMode();
} else if (environment.env === 'dev') {
  console.log('Development!');
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

Then running `ng serve --prod` and looking at the output:

```javascript
console.log("Production!"),
function() { // Inlined enableProdMode().
    if (Ln)
        throw new Error("Cannot enable prod mode after platform setup.");
    Mn = !1
}(),
nl().bootstrapModule($h).catch(t=>console.error(t)) // bootstrapModule()
```

The `"Development!"` log is not in the bundle and there is no if statement of the environment because it is known to be prod at compile time. If this isn't working for you then that is a separate bug.

Regarding the request to add a strippable comment, that is effectively asking for a preprocessor to run before the TypeScript compilation. Our opinion on this in the past is that we don't want to deviate too much from the blessed TypeScript path. And this would make more sense as a feature request to TypeScript than to Angular. I believe the TS has historically been against the idea of a preprocessor, but I'm not too familiar with the motivations or arguments behind that discussion.

I'm closing this issue for now as we don't want to add a preprocessor and your use case should be covered by existing tree shaking functionality. If tree shaking isn't working as you expect, then please open a separate bug about it and we can't investigate further to understand why.
