### ISSUE TITLE
Is there a way to compress all the css and all html template and load it in one shot in production mode, instead of making multiple calls

### ISSUE THREAD

**Issue by jagadeshpaladugula** [angular/angular-cli#1105]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment]
Is there a reason as to why you would want this? 

I mean technically you could make one big css file and paste in the code for all the other css files you are using into it but I don't see a reason as to why you would want to do that since you most likely won't be using all of the css initially a better alternative would be to implement lazy loading such that you would only load the css that is required for that particular set of components.

**Comment by filipesilva** [comment]
This will happen when we add in inlining of html and css, yes. It is being tracked in https://github.com/angular/angular-cli/issues/296
