### ISSUE TITLE
`ng generate service` should add `--module` back

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#11079]
### Versions
```
Angular CLI: 6.0.7
Node: 10.2.1
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* `ng new demo1`
* `cd demo1`
* `ng g m test`
* `ng g s data -m test`

### Observed behavior

The `ng g s` don't have a `--module` ( `-m` ) option anymore.  

### Desired behavior

I expected this option come back.  Even Tree-shakeable provider exists in Angular 6+, the traditional way to register service provider still works and commonly used when using lazy loading.

### Mention any other details that might be useful (optional)

N/A

**Comment by Brocco** [comment]
The idea of removing this option was to alleviate confusion and to prevent over-usage if the user was not totally sure that specifying a module was the actual intent.

For the cases when you understand that you really want to provide the service in a module it was decided that since that knowledge is there, so is the knowledge of being able to provide the service manually. This is why the option was removed in the current version(s).

I am marking this issue as a feature request to consider in the future.

**Comment by alan-agius4** [comment]
Closing this as since Angular version 6 the preferred way to create a services is to specify on the service that it should be provided in the application root. This is done by setting `providedIn` to `root` on the service's `@Injectable` decorator.

With this approach the module is redundant since the the service never gets registered in the `ngModule`.
