### ISSUE TITLE
Unable to install 1.0.0-beta.6 on OSX

### ISSUE THREAD

**Issue by JB-Tellez** [angular/angular-cli#1110]
On OSX El Capitan 10.11.4, Node 5.4.1, NPM 3.9.5, NVM 0.31.1 I ran

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

and hang about 25% of the way through on "loadRequestedDeps". The installation has been running about 30 minutes. I have a fast internet connection. 

Any thoughts? Thanks!

**Comment by filipesilva** [comment]
Odd thing really... `angular-cli` does take a while to install, but shouldn't take more than 2-3m tops.

On my machine I noticed I'm using node 5.11.1, can I ask you to install that version and retry? It might be a node issue.

**Comment by kylecordes** [comment]
I have been pointing people toward node 6 when they report any trouble with node 5. 5 is not "LTS" or anything like that, and there are relatively few projects that specifically need 5 instead of the current 6. Of course @JB-Tellez  could have such a project, there are some, because there are some modules out there that break on 6.

**Comment by diahron** [comment]
I am using Ubuntu Mate 16.04 with the latest node/npm updates. I am having the same ssues on my machine. I can load angular-cli using sudo, no big deal, but trying to run ng new ??? cause my system to loop endlessly until i cntrl-c.

**Comment by JB-Tellez** [comment]
Thanks everyone! Upgrading Node to latest makes it so the update installs. I'm going to close this issue. @diahron could you enter your problem as a separate issue?
