### ISSUE TITLE
[Feature request] Custom file naming scheme of modules and chunks

### ISSUE THREAD

**Issue by duki994** [angular/angular-cli#11113]
### Versions
```
@angular/cli - All versions
```

### Feature request
Currently there is no way to use custom file naming schema for modules and chunks.
For example, when building production application with CLI, the chunks start with number. And a production server of clients we are working for won't serve any files that start with number. 
In Webpack we can change the file naming convention easily in configuration like this ``` [name].[hash].bundle.js```.

It would be nice to have this, so auto-build systems can just run CLI and pack and publish Angular along with .NET Core and similar technologies. 

### Observed behavior
No file naming schema options

### Desired behavior
A variable in angular.json that will pass specified file naming schema to webpack config and/or command parameter with same role.

**Comment by JoseCMRocha** [comment]
Any update on this feature?

**Comment by alan-agius4** [comment]
You can use `namedChunks` to output the bundle with a name instead of a number.
See: https://angular.io/cli/build

I am closing this issue, as `namedChunks` is sufficient for this use case. If there is any other use case this is not covered by this. Kindly open a new issue explain the use case of having a different named chunk from the default provided.

Thanks.
