### ISSUE TITLE
Feature Request: cli command to automate installation of 3rd party libraries

### ISSUE THREAD

**Issue by jetlogs** [angular/angular-cli#1114]
Right now, it seems that adding 3rd party vendor libraries is very cumbersome based on the current documentation:
https://github.com/angular/angular-cli/wiki/3rd-party-libs

imagine adding 3 vendor libraries into your project, and you have to repeat all of these steps for each library you add. not to mention each step is a potential case for an error to happen

my current proposal is that we have a cli command like:
ng install lodash

which does the following:

1 does npm install lodash
2 install the typings for the library

it should also be able to figure out which typing command to use: 
- typings install lodash --save --ambient
- typings install dt~lodash --save --ambient
- typings install lodash --save --global

or if we use typescript's planned api: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/
- npm install --save @types/lodash

3 adds the library to the angular-cli-build.js file
4 adds the mapping for system-config.ts

**Comment by filipesilva** [comment]
Dupe (of sorts) of https://github.com/angular/angular-cli/issues/882.

Your post does add some more information but it is better if it's added on that issue, otherwise this discussion will become even more fragmented than it already is (there are some 5 different issues at least that talk about it).
