### ISSUE TITLE
No progress flag for ng xi18n

### ISSUE THREAD

**Issue by KlemensE** [angular/angular-cli#11167]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

`node --version`

v8.11.1

`npm --version`

6.0.1

` [System.Environment]::OSVersion.Version`

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17134  0
```

### Repro steps
Running `npm run ng xi18n -s --no-progress` in a angular project still writes the build progress to the output.

Running `npm run ng xi18n -s -- --no-progress` gives the error 

> Unknown option: '--progress'

### Desired functionality
Desired functionality would be to only receive Errors without the buildprogress.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
