### ISSUE TITLE
Complied lib files is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by william-lohan** [angular/angular-cli#11203]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.2.1
@angular/cli                       6.0.8
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3

### Repro steps
https://github.com/gatimus/lazy-lib
ng build shared
ng build lazy-lib

### The log given by the failure
ERROR in ./dist/shared/routing/error/shared-routing-error.d.ts
Module build failed: Error: C:\Users\User\source\lazy-lib\dist\shared\routing\error\shared-routing-error.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\User\source\lazy-lib\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\Users\User\source\lazy-lib\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
ERROR in ./dist/shared/routing/not-found/shared-routing-not-found.d.ts
Module build failed: Error: C:\Users\User\source\lazy-lib\dist\shared\routing\not-found\shared-routing-not-found.d.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\User\source\lazy-lib\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\Users\User\source\lazy-lib\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>

### Desired functionality
build with out error

**Comment by CharlesGrimont** [comment]
+1

**Comment by eastjie** [comment]
I have the same error, but after my test, this error happens when I try to make lazy loading for the library, when the name of the library contains "-" (minus character).
In my example, there is no problem by loading library "dynamic2". The error comes only after I have added another library "dynamic-simple".
https://github.com/eastjie/dynamic-module-imports-loading-with-the-angular-cli

In compiler,  the lazy loaded library has name consisting of "namespace-library name". I don't know if there is something wrong in getCompiledFile() from webpack by parsing path in the case.

>Date: 2018-08-03T13:11:58.563Z
Hash: 089fcb074e0789c02b3b
Time: 11867ms
chunk {dynamic-dynamic-module} dynamic-dynamic-module.js, dynamic-dynamic-module.js.map (dynamic-dynamic-module) 5.35 kB  [rendered]
chunk {0} 0.js, 0.js.map () 723 bytes  [rendered]
chunk {main} main.js, main.js.map (main) 25.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.1 kB [entry] [rendered]
chunk {sample-dynamic-simple} sample-dynamic-simple.js, sample-dynamic-simple.js.map (sample-dynamic-simple) 1.22 kB  [rendered]
chunk {sample-dynamic2} sample-dynamic2.js, sample-dynamic2.js.map (sample-dynamic2) 4.47 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.5 MB [initial] [rendered]
ERROR in ./projects/dynamic-simple/src/lib/dynamic-simple.module.ts
Module build failed: Error: C:\git_hub_fork\dynamic-module-imports-with-the-angular-cli\projects\dynamic-simple\src\lib\dynamic-simple.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\git_hub_fork\dynamic-module-imports-with-the-ngular-cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:714:15)
    at plugin.done.then (C:\git_hub_fork\dynamic-module-imports-with-the-angular-cli\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by eastjie** [comment]
I have the same problem. Can man add file to some setting in "tsconfig.json" as workround to solve this problem temporarily?
Thanks.

**Comment by frankpaap** [comment]
+1

**Comment by vkilaru** [comment]
+1

**Comment by akanagusku** [comment]
+1

**Comment by adipple** [comment]
+1

**Comment by pgh147** [comment]
+1

**Comment by saltman424** [comment]
+1

**Comment by LarsVonQualen** [comment]
I have a similar problem, I'm just not using the router, but lazy loading modules from web components using Angular Elements. I end up with modules containing only lazy loaded stuff, which apparently breaks the build, even though the modules are added to the `lazyModules` option in `angular.json`.

**Comment by ocampoesteban** [comment]
+1

**Comment by napstr** [comment]
Still broken on v8. Any hack or workaround very much welcome.

**Comment by napstr** [comment]
After updating to 9 this has gone away. I might have changed something in the configuration files as well but can't really point to anything specific. I'd generally recommend the update to 9, it solved a lot of problems I was having in a workspace with multiple libaries and lazy loading.
