### ISSUE TITLE
Allow to publish library in a isolated Github repo

### ISSUE THREAD

**Issue by brunolm** [angular/angular-cli#11283]
### Feature Request
```
- [x] feature request
```

### Area
```
- [x] other
```

### Versions
```
Windows 10
node v10.1.0
npm 6.1.0
Angular 6
```

### Repro steps
- `ng g library my-lib`

### The log given by the failure
> This command can only be run inside of a CLI project.

### Desired functionality
- create a standalone version I can publish on `github`/`npm` not coupled with a project/empty project.

### Mention any other details that might be useful
Followed steps from https://github.com/angular/angular-cli/wiki/stories-create-library

---

Example:

I created this package
https://www.npmjs.com/package/ngx-redux-state-props

And the source for it is here
https://github.com/brunolm/angular-libs

But I don't use anything other than what's in the projects folder, that feels weird.

**Comment by woodev01** [comment]
I've had similar feelings recently. It seems odd that module sharing seems like such a second class citizen in Angular. At my workplace, we have a have a shared component library, but if you are used to working on Angular projects, it looks like we have a weird example application (we use the src folder as our example app for our component library).

What would be nice of the CLI would be to include a secondary `ng new` mode.

`ng new --library` or `ng new --module`, although the former seems more semantically correct as module has a specific meaning to angular.

This version of the new command might make a project formatted something like:

- [my-project]
  - lib (or src) - containing the library module, or a group of library modules
  - examples - allows you to make an example angular app
  - node_mods
  - e2e
  - dist

When operating in this mode, build would default to the library, rather than the example app.

This way, the project is clearly a component library first, not primarily an application.

**Comment by alan-agius4** [comment]
@brunolm, I think what you want is to create an empty workspace without a default application.

```
ng new myworkspace --no-create-application
ng g library my-lib
ng g app example-app
```

**Comment by alan-agius4** [comment]
Closing as per above comment.

Feel free to open a new issue if the above is not what you meant.
