### ISSUE TITLE
Watching doesn't work for file paths remapped by the provided FS host

### ISSUE THREAD

**Issue by sis0k0** [angular/angular-cli#11339]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit - @ngtools/webpack
- [ ] schematics
```

### Versions
node v9.5.0
npm 5.7.1
Linux Fedora 25

### Repro steps
Create a new ng cli project. Build it in production mode. As specified by the `angular.json` file, the requests to the `environment.ts` file are remapped to `environment.prod.ts`. However, if you change the `environment.prod.ts` file, that webpack won't rebuild the project. Also, if you change the originally requested file - `environment.ts`, webpack will detect the change and trigger a build.

### Desired functionality
The app should be rebuild when a remapped file is changed.

### Mention any other details that might be useful
It looks like the original paths (and not the remapped ones) are added as dependencies for the webpack compilation in the `@ngtools/webpack` loader - [here](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/loader.ts#L77-L87). The same thing happens for the original component templates and styles (html, css, scss files).

**Comment by filipesilva** [comment]
I looked a bit into this today.

The current behaviour is due to us using Webpack's watcher to watch files in https://github.com/angular/angular-cli/blob/6449a753641340d8fc19a752e1a1ced75f974efa/packages/ngtools/webpack/src/virtual_file_system_decorator.ts#L107-L142

Instead, we should be using our own watcher implementation, that uses `host.watch(path)`. This way the host can properly resolve the alias when trying to watch a file.

I am unsure how much work this is since there might not be a one-to-one correspondence in functionality between the webpack watcher and the host watch functionality.
