### ISSUE TITLE
Electron + PDFJS + Angular 6 - DataCloneError: Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by MateEke** [angular/angular-cli#11368]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 6.0.6
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
Create electron app with pdfjs

### The log given by the failure
```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
```

### Desired functionality
PDFJS works fine in electron

### Mention any other details that might be useful
Everything is OK in Google Chrome

VadimDez/ng2-pdf-viewer#326
mozilla/pdf.js#9840

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

I would like to mention that Angular CLI does not support Electron platforms, so your problem might not have a solution right now.

**Comment by giridharkannan** [comment]
The issue is not what the error message says, it's actually something else. Since error handling faced another exception while reporting, things got messed up.

The reason for the issue is, Http module misses "require" method to be precise both Http and Https modules are empty.

When using pdf.js in Chrome browser, it uses PDFFetchStream to read data whereas when using pdf.js in Electron it uses PDFNodeStream. When in Electron, to resolve Http request PDFNodeStream uses Node's Http module ( require('http') ), somehow the http variable got overwritten.

Moving Http import inside PDFNodeStreamFullReader and PDFNodeStreamRangeReader solves the issue that we face.

I don't know why http variable got overwritten or who is responsible for this issue as am very new to frontend development but it would be helpful if someone helps us out to resolve this problem.
