### ISSUE TITLE
Enable watch for @angular-devkit/build-angular:server

### ISSUE THREAD

**Issue by jack-guy** [angular/angular-cli#11415]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions

node v10.1.0
npm v6.1.0

### Desired functionality
Currently developing application features for a server-side rendered app is a real pain. While I can `ng build --aot --watch` for the browser bundles, I have to manually rerun `ng run appname:server` to rebuild the server bundles every time I make a change. I suggest support for a `watch` flag that automatically rebuilds as necessary.

**Comment by hakobpogh** [comment]
I have tested the same also for `@angular/cli@6.1.0-rc.0` and the result is the same: it's impossible to enable watch mode for the server target. I have also tried with adding "watch": true to `angular.json` and I was getting the following error.
```Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(watch).
```
@Toxicable. you told that it was included in your PR. so I have tried it on RC too. And the result is the same. Also if there is another way to get it to work please tell me.

And I would like to make a note: if you're discussing adding that option to the angular json instead of having cli option then it's a terrible idea.

**Comment by jack-guy** [comment]
@hakobpogh I believe adding a flag in the CLI schema file of a schematic also adds support for angular.json and vice versa.

**Comment by Toxicable** [comment]
You need to use `"@angular-devkit/build-angular": "0.7.0-rc.0",`
beta.2 was where it was introduced but rc.0 is the latest

**Comment by clydin** [comment]
Closing as answered.  (Thanks @Toxicable )
