### ISSUE TITLE
Importing from the /projects directory should be prevented

### ISSUE THREAD

**Issue by j2L4e** [angular/angular-cli#11427]
Importing from a workspace project's source rather than from the built library leads to unexpected side-effects which can be hard to debug. A custom tslint rule would be able to effectively prevent this problem.

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
any

### Repro steps

```
import { MyClass as A } from '../projects/myProject';
import { MyClass as B } from 'myProject';

console.log(A === B) // false
```

### Desired functionality
tslint should enforce imports from the `/dist` folder and disallow importing from `/projects`.

### Mention any other details that might be useful
nrwl/nx implements a similar tslint rule ([repo](https://github.com/nrwl/nx/blob/master/packages/schematics/src/tslint/nxEnforceModuleBoundariesRule.ts)) to prevent imports from the 'wrong' place.

**Comment by alexeagle** [comment]
Long term, we expect to converge more with nrwl setup, so maybe this would become a default rule for Angular CLI.
Also we might make this a hard compiler error (via http://tsetse.info) rather than a lint check that you see only when running the linter.
For now you should add this lint check to your `tslint.json` if you want this check in your repo.
