### ISSUE TITLE
Allow "export to plnkr" feature

### ISSUE THREAD

**Issue by matsko** [angular/angular-cli#1147]
This would save me hours of time if this was built-in.

I am willing to take on developing this feature.

cc @hansl

**Comment by filipesilva** [comment]
On https://github.com/angular/angular.io we have a tool that converts runnable local examples to plunkers. Maybe something similar could be done here.

**Comment by nosachamos** [comment]
This is fantastic feature request!

**Comment by hansl** [comment]
@matsko if you have the time, we can talk next week when I'm back in MTV about how we should frame it. I think this should be a deploy command (like github-pages).

**Comment by matsko** [comment]
@hansl do we need to discuss it much? Having this feature sooner than later would make building animation demos much easier for me.

**Comment by hansl** [comment]
Alright. The command for it would probably be `deploy:plnkr`. Could you at least make a small design doc for it?

**Comment by matsko** [comment]
Yessir.

**Comment by filipesilva** [comment]
I should mention that this might be at odds with a webpack-based approach. Plunker generation as we have it in docs is heavily dependent on SystemJS configuration, and while it might be easy to have a generic one for base Angular 2 apps, I don't see how we could expand it to third party libs when using webpack.

**Comment by matsko** [comment]
Is the webpack-based approach mandatory? Is it super built into the generated CLI project?

**Comment by hansl** [comment]
It’s only for building CLI, which a Plnkr would not have to worry about.

We do not need the system-config anymore so we would kill it. You might
want to build it from scratch somehow.

-- 
Hans Larsen
Sent with Airmail

On June 20, 2016 at 6:56:29 PM, Matias Niemelä (notifications@github.com)
wrote:

Is the webpack-based approach mandatory? Is it super built into the
generated CLI project?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular-cli/issues/1147#issuecomment-227294462>,
or mute the thread
<https://github.com/notifications/unsubscribe/AApn8Qjj4ECcqiciTmIxz8VhU2p5zFyEks5qNxqbgaJpZM4I5_71>
.

**Comment by filipesilva** [comment]
What I mean is that now we could directly build the plunker SystemJS config from the existing project one, but if we move to webpack then it's gone so we can't do that.

What we could do is deploy to plunker and, if the user had 3rd party libs, the app would be broken until they fixed the SystemJS config.

**Comment by hansl** [comment]
Which is what I just said. He need to build one from scratch during deploy
:)

**Comment by filipesilva** [comment]
Well, if we're fine going down that approach, I might be able to wip something out pretty fast...

**Comment by hansl** [comment]
Closing this, we won't support this until we at least support different deploy options.
