### ISSUE TITLE
Configure source map path 

### ISSUE THREAD

**Issue by vanmxpx** [angular/angular-cli#11513]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
  NPM v5.5.1
Angular CLI: 6.0.8
Node: 9.3.0
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
  Windows (10)

### Repro steps
Create default angular application with "ng new [name]". Try to debug in Visual Studio 2017, VS Code, IDEA etc. Type script remote files will be not mapped to the sources, because of wrong webpack:// url. 

### The log given by the failure
There are no logs

### Desired functionality
Since angular-cli removed ng eject command i cannot configure webpack to override source map files location. I need to override devtoolModuleFilenameTemplate option to set normal path with root directory.

**Comment by clydin** [comment]
This is not configurable.  Most IDEs support debug configurations that allow debugging from within the IDE.  Please see this issue with sample configurations for vscode: https://github.com/angular/angular-cli/issues/2453

**Comment by adamdoyle** [comment]
> This is not configurable. Most IDEs support debug configurations that allow debugging from within the IDE. Please see this issue with sample configurations for vscode: #2453

It seems like you're saying that if you author libraries with webpack, those libraries can't be consumed in an Angular CLI project (if sourcemaps in Chrome are important), unless you're willing to switch from using `ng serve` to launching with vscode.  In my case, I'm using IDEA instead of vscode, which I don't think even has support for what you're suggesting.

So as I read this, it seems the instructions are:
- stop using `ng serve`
- switch IDEs from IDEA to vscode
- add a rewrite path so that `ng build` won't screw up the sourcemap path

That's a lot to ask considering it seems like Angular CLI is the one responsible for messing up the sourcemap paths to begin with.

I can include the webpack libraries in a vanilla HTML file via `<script></script>` tags and the paths look correct and Chrome successfully uses the sourcemaps.  But as soon as I funnel it through an Angular CLI project, the paths get rewritten from `file:///absolute/path/to/source/` to `webpack:///./relative/path/to/source/` and Chrome can no longer handle it.  I've read through #2453, but it only has a bunch of vscode-specific workarounds.
