### ISSUE TITLE
 ng serve --open  angular/node cli issue 

### ISSUE THREAD

**Issue by Glen-Dango** [angular/angular-cli#11528]
When opening my project i got this compile failure a few times...  

ERROR in src/app/hero-detail/hero-detail.component.ts(2,22): error TS2307: Cannot find module '../hero'.
src/app/hero-detail/hero-detail.component.ts(12,16): error TS2304: Cannot find name 'selectedHero'.
src/app/hero.service.ts(3,22): error TS2307: Cannot find module './hero'.
src/app/heroes/heroes.component.ts(2,22): error TS2307: Cannot find module '../hero'.
src/app/mock-heroes.ts(1,22): error TS2307: Cannot find module './hero'.

i ｢wdm｣: Failed to compile.

From bug fixing over my week trying to work through the heros tuts,....   i went into hero-detail.component   deleted a letter and replaced it with the same letter and saved the page again, and then it compiled... i didnt change anything just resaved the page !  

Any reason for this flaky, hit and miss compile issue or is it nothing to worry about?

**Comment by filipesilva** [comment]
I'm not sure what happened there but it maybe was related to some files changing quickly. File watchers are not very accurate and this sort of thing can happen. 

I wouldn't worry too much about it since as far as I know this isn't common. If you keep getting this, can you try using another editor just to test? Maybe your editor is changing some files.

Let me know if this is still a problem to you.
