### ISSUE TITLE
ng upgrade should upgrade ngsw-config.json

### ISSUE THREAD

**Issue by adamzr** [angular/angular-cli#11535]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Repro steps

Upgrade an older Angular app that uses a service worker to Angular 6 using the CLI upgrade tool.

### Desired functionality

The upgrade tool should update the file name patterns to cache to reflect the new Angular file naming scheme. The changes should be equivalent to this commit: https://github.com/angular/devkit/commit/fb78b20b5b5d46795f31b03ce3c02ed25432bee6#diff-dba244caa12fc352f91127ba5efc49e4

### Mention any other details that might be useful

This change can cause the angular JS files to not be cached. If the SW caches an old version of the index.html page, the site will fail to load as the old files are not cached and may no longer be available on the server.

**Comment by kwilliams-curago** [comment]
This issue causes major issues when deploying to environments like AWS cloudfront. 

The suggested deploy method for SPA applications in these environments is to map 404s to 200s and redirect to the index.html

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
