### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by daniele-zurico** [angular/angular-cli#116]
Hi all,
I've just tried this well done project.
The only problem that I see is that it use SystemJS. There's any chance to have webpack as well?

**Comment by sgentile** [comment]
+1 for webpack

**Comment by nileshmali** [comment]
+1 for webpack

**Comment by swestner** [comment]
+1 for webpack

**Comment by ansarizafar** [comment]
+100000 for Webpack

**Comment by mixomat** [comment]
+1 for webpack

**Comment by daniele-zurico** [comment]
no news about that? just to know if it planned or not :)

**Comment by filipesilva** [comment]
There aren't any plans for `webpack` right now, I believe. The build process is tightly tied into `broccoli` since that is what `ember-cli` uses.

Main priorities at the moment are getting the main user stories up and going, and only afterwards give some more thought to customizability.

That isn't to say you can't use `webpack` though! The scaffolding doesn't really care one way or another, neither do the tests. So basically you could very well use everything the cli has, minus `ng serve`. 

Just add in your own `webpack.config.js`, npm dependencies, fire up `webpack-dev-server` and you're ready to go!

**Comment by filipesilva** [comment]
(I'm closing this for now, but feel free to keep the discussion flowing.)

**Comment by mixomat** [comment]
I'm keen to to see the community acceptance of this project, without Webpack support ;)

**Comment by daniele-zurico** [comment]
@filipesilva thanks for the reply, but the point is why you/they decide to use SystemJs instead Webpack?

**Comment by filipesilva** [comment]
The CLI is mostly catering to the Typescript track at [angular.io](https://angular.io), which uses SystemJS. There is a section on the [quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#appendix-systemjs-configuration) that touches on webpack:

> There are alternatives that work just fine including the well-regarded webpack. SystemJS happens to be a good choice but we want to be clear that it was a choice and not a preference.

**Comment by nickroberts** [comment]
FYI: https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by iloveyo123u1** [comment]
+1

**Comment by sryzycki** [comment]
+1

**Comment by dennis-b** [comment]
+1

**Comment by systembugtj** [comment]
ember/ember-cli has its own philosophy and ecosystem. angular2 is totally different concept, angular-cli suppose to bring the smooth dev experience to angular2 not what ember-cli choose.

**Comment by zackarychapple** [comment]
Just going to drop this here. https://github.com/angular/angular-cli/tree/webpack @TheLarkInn and a bunch of others have been working on the #webpack branch.

**Comment by summerisgone** [comment]
Oh, I'm almost on time! +1 for webpack :)

**Comment by alexjoverm** [comment]
Cool to see webpack coming into play. Is it known when (or which version) angular-cli will release webpack support?

**Comment by kylecordes** [comment]
I haven't seen the CLI team officially state a version or date yet; but I think for most practical purposes you can think of it as already being the "current" version: it seems like most people talking about CLI and staying up to date with it are already at webpack, and numerous old issues in this issue tracker have already been resolved because they pertain to the pre-webpack versions.

**Comment by alexjoverm** [comment]
I've just realised about this https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

**Comment by Namek** [comment]
is webpack config somehow hidden from us? Why? How do I plug in autoprefixer for my styles or 3rd party dependencies?

**Comment by TheLarkInn** [comment]
@namek we wanted an opinionated and already managed base configuration. We realize there are other tools and features to be added so we will hopefully have an 'escape-hatch' or 'eject button' for the future.

**Comment by dbushman** [comment]
So, @TheLarkInn, in that case is it possible to add a proxy url to the current version?

**Comment by krishollenbeck** [comment]
@TheLarkInn. I regards to Namek's question. I too am also wondering about this. For example how would I go about importing jQuery or other thirdparty js libraries?[ I asked a question about this on stack overflow. ](http://stackoverflow.com/questions/38855891/angular-cli-webpack-how-to-add-or-bundle-external-js-files?noredirect=1#comment65076191_38855891)

**Comment by SethDavenport** [comment]
An escape hatch will be important I think - the power of webpack is its flexibility. Otherwise I'm afraid you'll be inundated with 'I can haz loader/plugin x?' requests.

Allow me to start :)

"I can haz cssnext?"

However I can't say enough how much of an improvement the webpack version is over the SystemJS one.

**Comment by SethDavenport** [comment]
Actually just saw postcss in there. Ignore me.

**Comment by nikolasleblanc** [comment]
To @SethDavenport's point, it would be ideal to be able to load a custom webpack config at the project root that the cli-webpack imports to extend its config. This would allow anyone to haz whatever they wanted, without mucking up the base config or having to fork off the original cli (hello "eject").

**Comment by TheLarkInn** [comment]
I would seriously encourage anyone involved on this thread to come up with a design proposal for this. We have a half created one with me and @brocco but currently we are focusing on MVP items at the moment. This is still IMO a great deliverable.

**Comment by nikolasleblanc** [comment]
Will take a look!

**Comment by nikolasleblanc** [comment]
Design proposal pending, but a quick sketch of the code would look like this:

https://github.com/nikolasleblanc/angular-cli/commit/1e081a6649728ca4cc6dae30830d805bfd36750f

**Comment by nikolasleblanc** [comment]
My design proposal. @TheLarkInn, not super familiar with the format of design proposals, open to suggestions if you have any.

https://github.com/angular/angular-cli/issues/1656

**Comment by migueldiganchi** [comment]
Does anybody know how to install angularfire2 after upgrade the angular-cli version to use the webpack bundler?

I am trying to follow the official repo steps to install angularfire2, but when I try to edit the 'angular-cli-build.js' file, I cannot find it. 

Regards!
