### ISSUE TITLE
Future of @schematics/package-update

### ISSUE THREAD

**Issue by sarunint** [angular/angular-cli#11674]
As far as I know, `@schematics/package-update` is no longer a dependency of Angular CLI. (Latest version of CLI that uses this package is 6.0.0-beta.7) But why there is still new releases of this package?

For reference: https://github.com/angular/angular-cli/commit/33a6823df121ea024afd5c0571eaee0d7eb34052

**Comment by hansl** [comment]
No future. That schematics was only updating the package.json and not doing anything else. The new `update` schematics also run migrations and validate peer dependencies properly.

It's still released because it's part of our monorepo and we publish all packages. I'll disable it at some point, so letting this issue open for tracking this.
