### ISSUE TITLE
Lint configuration to fail on tslint error

### ISSUE THREAD

**Issue by elwindly** [angular/angular-cli#11698]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X ] config

```
### Desired functionality
What would like to see implemented?   A configuration option to make the the compilation fail on tslint errror. 
What is the usecase? To enforce tslint rules.

**Comment by alexeagle** [comment]
I think this is misguided. If we block compilation, this forces you to make your code lint-clean before you even know whether the code works. Turning warnings into errors doesn't improve the developer experience in my opinion - there's a reason to distinguish between the two in your workflow.

The workflow our team prefers, and how we operate at Google, is that lint warnings are presented at code-review time. This is better because
- you are free to have messy code while you're iterating on it
- a linter is like a robot code reviewer
- code reviewer feels like some of the work is automated for them

I suggest checking out a service like Codacy.
