### ISSUE TITLE
Using externalSchematic breaks debug mode

### ISSUE THREAD

**Issue by mattezell** [angular/angular-cli#11726]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] devkit/Schematics
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node v8.11.3
NPM 5.6.0
Windows 7

### Repro steps

Create a new schematic, call an external schematic (such as @schematics/angular, ng-new), see 'could not find module "@schematics/angular"' error as initially disclosed in this devkit issue pre repo-migration: https://github.com/angular/devkit/issues/635

### Desired functionality

For Schematics to provide a way to test Schematics which seek to 'extend' Angular's default Schematics, as this seems to be one of the largest use cases for Schematics outside of Angular CLI (ex: we're building out developer tooling for an enterprise development environment).

### Mention any other details that might be useful

Originally opened issue for this problem: https://github.com/angular/devkit/issues/635

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
