### ISSUE TITLE
Is Node 4 in Readme correct?

### ISSUE THREAD

**Issue by frodefi** [angular/angular-cli#1173]
In issue #1146 user hacknaked says that one should probably use Node 5 or higher since Angular 2 requires it: https://angular.io/docs/ts/latest/quickstart.html#!#prereq.

Perhaps the Readme of this project needs to be updated from requiring Node 4?

**Comment by filipesilva** [comment]
Angular 2 itself doesn't require any specific version of Node per se, since it runs in the browser. Rather, the *setup* proposed in the quickstart requires it. 

I think Node 4 is still accurate for the CLI but if you find scenarios where it doesn't work, I'd be happy to accept a PR changing the readme.

**Comment by hacknaked** [comment]
> I think Node 4 is still accurate for the CLI but if you find scenarios where it doesn't work, I'd be happy to accept a PR changing the readme.

@filipesilva. Look your own comment in #1110. 

> Angular 2 itself doesn't require any specific version of Node per se, since it runs in the browser.

So, why no use Node 1.x? I also had problems with node 4.x and the solution was update to Node 6.x.
