### ISSUE TITLE
Feature Request: ng generate --sass Flag To Generate SCSS File

### ISSUE THREAD

**Issue by griffiti** [angular/angular-cli#1177]
It would be nice to have a `--sass` flag to use with `ng generate` to create a .scss file instead of a .css file for a given component.

`ng generate component user-list.component --sass`

**Comment by masaanli** [comment]
@griffiti You know there is a possibility to set the default style extension inside the 'angular-cli.json' file.

styleExt: 'scss' for example, if you do that it will generate a .scss file instead of a .css file with the generation of a component or route for example.

**Comment by gfrSE** [comment]
use `ng set defaults.styleExt scss`

**Comment by filipesilva** [comment]
I'm closing this issue because the answers given here seem to cover the usecase, and I don't see a big need to support it on the `ng generate component` command. 

It doesn't sound common enough that a user would have a default on `angular-cli.json` and then use a few different preprocessors elsewhere in the app.
