### ISSUE TITLE
Why angular inject scripts in my code because I want to inject manually!

### ISSUE THREAD

**Issue by alex2sorin** [angular/angular-cli#11816]
Angular 6 inject scripts in my code, and I don't want that!

![capture](https://user-images.githubusercontent.com/42208296/43835709-91edac7e-9b1b-11e8-817c-a17a6bf730f8.JPG)
![first](https://user-images.githubusercontent.com/42208296/43835726-9f6e65fa-9b1b-11e8-8d6d-5a817c50c669.JPG)

This happens after I run my .net core app which uses static files generated by angular cli with ng build command

**Comment by alexeagle** [comment]
What's the use case? Could you also help us understand why you don't want these scripts? Do you plan to add them manually in your HTML?

**Comment by alan-agius4** [comment]
Angular CLI, requires 3 tags to be present in the provided `index` file, `app-root`, `head` and `body`,  and not having the last 2 is causing your compilation error. As `@page` directives always need to be the first thing in the view.

I think what you might really want here is for Angular CLI not to process an `index` file. However, how to get around your issue, is based on how your `.NET` application is setup.

**Scenario 1.**
You are using a standard `.NET` and `Razer` configuration, without a custom view locator that processes the `view` that will be outputted to the `dist` folder. You wouldn't need fro Angular-CLI to process the `view` as it won't be able to be located and processed by `Razor`, as the view engine will only try too look for views in `src/Views`.

Now you can go around your error, simply by providing a dummy `index.html`, that won't be used by your view engine.

**Scenario 2.**
You are using a custom view locator to locate your views in the `dist` folder rather than `src/Views`. In this case you should be able to update your `index.cshtml`;

```cshtml
@page
@model RazorPagesContacts.Pages.HomeModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html>
<body>
   <app-root></app-root>
</body>
</html>
```

If you are using layouts you can also do something like the below;
```cshtml
<!DOCTYPE html>
<html>
<head>
</head>
<body>    
   
   <app-root></app-root>
   @RenderBody()
</body>
</html>
```

In think that scenario 2, is the best one, for various reasons, such as you can use the output-hashing without the need that one every build you need to change manually the paths of the `JS` & `CSS`. No room to error, as when doing the files manually it's easier to skip a file or miss something especially during upgraded. Or in your above case, a `css` file is placed in a `script` tag (Line 21). 

More info about view locators;
https://samueleresca.net/2016/07/net-core-1-0-customize-view-paths/
https://weblogs.asp.net/imranbaloch/view-location-expander-aspnet5-mvc6

I hope that this helps you.

**Comment by filipesilva** [comment]
Angular CLI injects these scripts because they are derived via internal logic from the Angular CLI configuration. We don't have an option to not add them because a user cannot easily determine which should be added or not.

**Comment by chintans** [comment]
I have a similar scenario. My workaround was to move away from angular cli and use custom webpack build. this way I can remove HtmlWebpackPlugin from my build process entirely. However, It would be great if a command line switch could be added which prevents angular cli from modifying index.html. something like 
`--preserve-index-html` or `--disable-script-injection`

**Comment by maxisam** [comment]
I wonder if we can use [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) to overcome this kinda issues. 

my case is I don't use index.html at all, but I still want to inject the scripts into 2 files, one for scripts and the other one for style.

I tried to use 

```
 plugins: [
    new HtmlWebpackPlugin({  
      filename: 'test.html',
      template: 'src/assets/test.html'
    })
  ]
```
but it doesn't work. It did generate a file but no scripts. 

The other way I have tried is using Gulp. This way does work. Just not pretty.

**Comment by BeniGemperle** [comment]
We often create Angular-Apps and host them inside a Content Management System, where index.html is included/embedded on the server side and the host-website already contains the html- and body-tags.

Angular cli 6.2.5 seem to add the script-tags before the closing `</body>` or at the very beginning of index.html (if there is no `</body>`-tag). There seems to be no convenient way to either:
1. disable script-injection entirely
2. or have the script-tags at the end of index.html, even if no `</body>` is present.

Today we use manual workarounds for this limitation but with downsides of not having automatic differences between development and production builds. We would very appreciate if such a feature is added.

**Comment by BDominik** [comment]
Any news about this?
I need to migrate ionic 3 application to ionic 4 which uses angular 6, and I also need to add those build files manually.

**Comment by tito-cr** [comment]
@alan-agius4  When you say:
> Angular CLI, requires 3 tags to be present in the provided `index` file, `app-root`, `head` and `body`....

Do you mean literally "app-root", or is it that it should have the selector from AppComponent which in our case is something like "my-root"? We're trying to track down a "Cannot read property startTag of null" error and this was one of the hits that came up.

**Comment by RobJacobs** [comment]
Would be nice if we could define in the config a query selector to determine which elements would get the css and scripts injected into.

**Comment by lk77** [comment]
so there is no way to disable this behaviour ?

i have this error :

```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: The selector "app-root" did not match any elements
```

in that particular html page, there is no angular app, just plain html page
