### ISSUE TITLE
Support glob options in assetPattern

### ISSUE THREAD

**Issue by dinony** [angular/angular-cli#11850]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

[Asset pattern](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L755-L785) supports glob patterns but does not support glob [options](https://github.com/isaacs/node-glob#options).

What about something like the following?

```
{ "glob": "**/*", "globOptions": {"ignore": "src/assets/fonts"}, "input": "src/assets/", "output": "/assets/" }
```
This would help with file duplication [issues](https://github.com/StudioProcess/rvp/issues/171).

**Comment by clydin** [comment]
One potential option is to try a glob with a negation.

However, the underlying issue is that non-assets are being placed within an asset directory.  Assets are files that are copied verbatim to the build output.  Files that are processed by the build system should not be placed there as they are not intended to be simply copied.
