### ISSUE TITLE
Tests Run When Swap Files (*.swp, *.swo, *.swn, ...) Change

### ISSUE THREAD

**Issue by benbotto** [angular/angular-cli#11880]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.11.3
npm: 5.6.0
Angular CLI: 6.0.8
Ubuntu Linux: 16.04.1

### Repro steps

Run tests: ng test
Open any file with vim and the tests run: vi src/app/heroes/heroes.component.ts
Change the file without saving and the tests run.  Anything that causes a change in the vim-generated swap file triggers a test re-run.

### Desired functionality

The tests should only run once.

### Mention any other details that might be useful

Seems like a similar issue has already been reported here: https://github.com/angular/angular-cli/issues/4593  Being a vim user I really appreciate the fix; however, the issue is also present when running unit tests.

**Comment by filipesilva** [comment]
There's two parts to this problem:
- Karma running the tests when nothing has changed
- Webpack compiling when no source file has changed

The second point is by design actually. It happens because of this bit of `src/test.ts`:
```
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
```

It means "find all the files under './' that end in '.spec.ts'", and part of that is watching the `./src/` dir. When anything under the `./src/` folder changes, Webpack recompiles to scoop up the source files again, because any new or changed files might actually included in the compilation.

The first point however, is something that we don't really do but makes sense. Even if webpack recompiled, we shouldn't rerun tests if nothing has changed. https://github.com/angular/angular-cli/pull/12402 should take care of that.

**Comment by filipesilva** [comment]
Indeed the regex only matches spec files. But the regex operates over the whole content of the folder. So the folder itself is a resource to be watched.

One could argue that webpack could do that better though. For me, since I am so used to the details of webpack, the question didn't really cross my mind. But it's a pertinent question.
