### ISSUE TITLE
Feature Request: Allow to generate libraries within a particular folder & allow to rename 'projects' folder name

### ISSUE THREAD

**Issue by micronyks** [angular/angular-cli#11927]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Latest

### Desired functionality
Currently It is not possible to generate a library within a specific folder with relative path.
When I run `ng generate library mylib --prefix=mylib` command, it generates a folder called **`projects`** under **`root directory`** and places **`mylib`** under **`projects`**

_Current Flow,_

```
|---MyFoodApplication
|                    |---projects
|                                |---mylib-1
|                                |---mylib-2
|                    |---src

```

_Sometimes use-case can be like:_

1) Create all libraries under **common** folder resides at (anywhere) angular project's root directory.  (common is just a folder and nothing else)

2) When I want to create any library, It should create **desire name of the folder (eg. companyname-libraries) which must contain all generated library**.

_So, the final output should be like below,_

```
|---MyFoodApplication
|                    |---common
|                              |---companyname-libraries
|                                                       |---mylib-1
|                                                       |---mylib-2
|                    |---src

```

**Comment by thefliik** [comment]
Obviously this isn't ideal, but I work around this issue by simply updating the `angular.json` `"newProjectRoot"` property to be whatever I want for the project I'm generating at that moment. 

In general, I keep it at the project root for my libraries (because I generate more of those) and I temporarily change it to the project root for my apps when I need to generate a new app (and then immediately change it back to my libraries' project root).

**Comment by micronyks** [comment]
@thefliik I have already done it but it **should not be** a manual process ! That's why I've added this as a feature request.

**Comment by emirhg** [comment]
It's been two years and this issue remains open. I'll like to work on it as I'll find it very useful on a current project. So far I've identified the involved line: https://github.com/angular/angular-cli/blob/9ee905d76bd6211e101d712f6782edfceb276114/packages/schematics/angular/library/index.ts#L153

I'm thinking on a CLI argument like `ng generate library my-lib --newProjectRoot=my-prefix-path` in order to be consistent with the JSON config file. Would love to read your comments about it
