### ISSUE TITLE
Support HTTP/2 Server Push

### ISSUE THREAD

**Issue by kimamula** [angular/angular-cli#11946]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

polymer-cli and preact-cli generate push-manifest.json which maps incoming request paths to the additional resources that should be pushed with it and is to be interpreted by a tool like [prpl-server-node](https://github.com/Polymer/prpl-server-node).

It would be great if angular-cli provide the similar functionality.

**Comment by kimamula** [comment]
It may not be easy to create `push-manifest.json` as Angular currently probably does not analyze which resources are required in each path in build time.

An alternative solution would be:

1. Create [a webpack plugin](https://github.com/kimamula/angular-cli/compare/master...kimamula:prpl?expand=1#diff-691046d02a2cd27f852b24aedbdcbbfd) that generates a file that maps module paths to resources
```json
// An example output of the webpack plugin
{
  // Resources which are always required are included in ""
  "": {
    "runtime.3e827d1a10b9047735bc.js": "script",
    "main.e8725b5004466c1664e1.js": "script",
    "polyfills.43f2535cedd6fe44b10e.js": "script",
    "styles.34c57ab7888ec1573f9c.css": "style"
  },
  "./lazy/lazy.module": {
    "0.8c6a7127511b5f2ffe40.js": "script"
  }
}
```

2. `require` the file created above and [pass it to `ngExpressEngine` function in an Angular Universal app](https://github.com/kimamula/universal-starter/compare/master...kimamula:prpl?expand=1#diff-5c092da67283b0b787b618509fa7b96f).
3. Provide [`LinkPreloadHeadersSetter`](https://github.com/kimamula/universal/compare/master...kimamula:prpl?expand=1#diff-b64bfe73b00101577ee1a764112e2e59), which creates link preload headers based on paths of required modules using the map, in Universal engines ([express-engine, for example](https://github.com/kimamula/universal/compare/master...kimamula:prpl?expand=1#diff-734fb3cbaaf4a84f10fb7ec6282a15da)), and [call its `onLoad` method in `ModuleMapNgFactoryLoader#load`](https://github.com/kimamula/universal/compare/master...kimamula:prpl?expand=1#diff-4e18c114224afda8375f904a7848a13a).

Demo: https://angular-prpl.appspot.com/ 
(Chrome users may have to disable `Experimental QUIC protocol` in `about:flags` to make HTTP/2 Server Push work)

Diffs:
- [angular-cli](https://github.com/kimamula/angular-cli/compare/master...kimamula:prpl?expand=1)
- [universal](https://github.com/kimamula/universal/compare/master...kimamula:prpl?expand=1)
- [universal-starter](https://github.com/kimamula/universal-starter/compare/master...kimamula:prpl?expand=1)

An apparent drawback of this approach is that you can use HTTP/2 Server Push only in Angular Universal apps.

**Comment by kimamula** [comment]
I have created a library based on the above idea, though I have not tested it thoroughly.

https://github.com/kimamula/ngx-server-push

**Comment by bogomips** [comment]
I was looking for the possibility of enabling push on an angular 9 / ionic app.
Any news?

**Comment by SchnWalter** [comment]
I would say that this is out of scope for the Angular CLI.

Because, for a proper configuration, besides the JavaScript and styles, each project also requires various static resources to properly bootstrap and render the application. If you really want to generate that file, you can use a 3rd party builder or write what that allows you to generates that file with the appropriate content.

And server push in Ionic applications isn't supported, they use a local web server. This would be useful if you are serving them on the web, which already requires you to tweak the application depending on the platform (you need to disable `preloadingStrategy: PreloadAllModules` on the web), so this calls for more custom configurations. And I think that these things shouldn't be maintained by the Angular CLI team, they should focus on maintaining other features.

**Comment by alan-agius4** [comment]
Thank you for raising this issue. However, due to the removal of HTTP/2 Server Push support from most modern browsers we will not be adding support for this feature.

Instead, we are exploring alternatives. This alternative is currently being tracked in https://github.com/angular/angular-cli/issues/26484
