### ISSUE TITLE
ng update @angular/cli sets incorrect ngswConfigPath

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12109]
_From @CDDelta on May 4, 2018 7:53_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

Angular: 6.0.0

### Repro steps

Migrate an angular-cli.json app with service worker to angular.json.

### The log given by the failure

Something about ngsw-config.json not found.

### Desired functionality

ngswConfigPath should be set to `src/ngsw-config.json` not `/src/ngsw-config.json`
https://github.com/angular/devkit/blob/9bbc4e62005c150ee1f24ee15ae8abcbba8e875d/packages/schematics/angular/migrations/update-6/index.ts#L310

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#845_

**Comment by alexeagle** [comment]
_From @chamikasandamal on May 15, 2018 12:19_

Changing `/src/ngsw-config.json` to `src/ngsw-config.json` fix the issue.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
