### ISSUE TITLE
build-optimizer "failing" with a 3rd dep with module.exports

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12111]
_From @Foxandxss on May 1, 2018 18:51_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

Node 8, npm 5.6, windows 10

### Repro steps

https://github.com/Foxandxss/devexpress-reporting-cli-issue

The repo has all details in how to reproduce it.

In short, with build-optimizer the 3rd party package fails in prod unless I monkey patch it.

@filipesilva thinks it is work investigating from the build-optimizer standpoint.

_Copied from original issue: angular/devkit#826_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
