### ISSUE TITLE
Fail to build/test blank schematic

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12126]
_From @andrewseguin on April 5, 2018 20:41_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

node: 8.9.4
npm: 5.7.1
devkit: 0.5.1

### Repro steps

1. Create blank schematic with `schematics blank --name=my-component`
2. Run `npm run test` or `npm run build`

### The log given by the failure

`src/testable-schematic/index.ts(6,35): error TS6133: 'options' is declared but its value is never read.`

### Desired functionality

Would like to have a buildable/testable skeleton to start my schematic. 

_Copied from original issue: angular/devkit#634_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
