### ISSUE TITLE
throw more descriptive errors when collection .json is invalid 

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12168]
_From @rkirov on June 14, 2017 18:14_

For example `https://github.com/angular/devkit/blob/master/packages/angular/schematics_tools/src/file-system-engine-host.ts#L60` just returns null, which means the error thrown eventually is the same as the file is missing and etc, other issues.

_Copied from original issue: angular/devkit#5_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
