### ISSUE TITLE
build-optimizer: enum wrapping pass is unsafe in atypical use cases

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12160]
_From @clydin on October 23, 2017 14:27_

### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Repro steps

An enum member can contain an initializer which may have side effects.  Currently all enums are wrapping in an IIFE and annotated with `PURE` which will prevent the side effects from occurring if the enum is unused.

```
function getValue() {
  console.log('hi');
  return 6;
}

enum Test {
  ValueA,
  ValueB = getValue()
}
```

### Desired functionality

As this will most likely be an extremely rare occurrence, a documentation note may suffice.  Additionally a warning or informational message may also be useful when an enum is encountered with a member containing a non-constant expression. 

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#234_

**Comment by OrangeDog** [comment]
@alexeagle looks like you typo'd the workaround label?

**Comment by dgp1130** [comment]
Just verified this locally and I'm still able to reproduce on v9.1.7. I didn't look into the pure comments for Terser, but running the following code:

```
function getBar(): number {
  console.log('Getting bar');
  return 2;
}

enum MyEnum {
  foo = 1,
  bar = getBar(),
}
```

Will print "Getting bar" with run with `ng serve` and will print nothing with `ng serve --prod`. Most likely the enum is getting tree shaken because it is unused and assumed to be pure via Terser comments when it actually isn't. I don't see any warning or compile-time error as a result of using a side-effectful function in an enum initializer.
