### ISSUE TITLE
Error if a command line flag is not a tool flag or a schematic property

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12166]
_From @dansanderson on June 14, 2017 18:16_

Currently if the user provides a command line flag to the CLI that is not a tool flag or a schematic property, the extraneous property is ignored. It should be reported as an error, especially to catch typos in property names that otherwise end up using defaults.

_Copied from original issue: angular/devkit#7_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
