### ISSUE TITLE
insertLeft/Right beyond boundary flips and binds to end?

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12164]
_From @dansanderson on June 14, 2017 18:23_

In the text update recorder, insertLeft(length + 1, ...) returns an index error. It would be helpful and intuitive for some algorithms for this specific case to be interpreted as insertRight(length, ...). For example, if I'm scanning a string for a position to do an insertLeft and do not find a matching position prior to the end, I want to append to the end. As is, I have to make a special case and call insertRight directly.

The symmetric operation would be insertRight(-1, ...) -> insertLeft(0, ...).

I don't know if it needs to allow all indexes past the ends or just one past the end. And there may be reasons I'm not thinking of to not do this at all.

_Copied from original issue: angular/devkit#9_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
