### ISSUE TITLE
[7.0.0-beta.2]: regression for short aliases like `-v`, `-m`...

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#12210]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node 8.11.3
Angular CLI: 7.0.0-beta.2
Node: 8.11.3
OS: darwin x64
Angular: 7.0.0-beta.5

### Repro steps
Commands like `ng -v` no longer works.

Or for example:

```
ng generate module shared
ng generate component button -m shared
```

is ginoring the module (adds it to AppModule), whereas:

```
ng generate module shared
ng generate component button --module shared
```
still works.

### The log given by the failure

It looks like some (all?) short aliases aren't working anymore.

### Desired functionality

We want our short aliases back :)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
