### ISSUE TITLE
Ng serve works in Windows but fails in Ubuntu

### ISSUE THREAD

**Issue by matinzd77** [angular/angular-cli#12283]
Hi I have tried and read all issues about this problem but I couldn't solve problem so I will post my issue here.
Do you know where the problem is? It successfully compiles in windows but there are errors serving in Ubuntu although `ng build --prob` neither works in Ubuntu nor Windows.

![screenshot_server_problem](https://user-images.githubusercontent.com/24797481/45586168-46e32100-b907-11e8-810e-ae02e8ac169e.JPG)

```
Ubuntu 16.04 and Windows 10
node version : 8.11.1 
npm version : 5.6.0
```

```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.6
node: 8.11.1
os: linux x64
@angular/animations: 4.4.7
@angular/common: 4.4.7
@angular/compiler: 4.4.7
@angular/core: 4.4.7
@angular/forms: 4.4.7
@angular/http: 4.4.7
@angular/platform-browser: 4.4.7
@angular/platform-browser-dynamic: 4.4.7
@angular/router: 4.4.7
@angular/cli: 1.2.6
@angular/compiler-cli: 4.4.7
@angular/language-service: 4.4.7
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
