### ISSUE TITLE
support loading dist/index.html from filesystem?

### ISSUE THREAD

**Issue by guidorice** [angular/angular-cli#1231]
I noticed that the dist/ project can be loaded by HTTP, e.g. if I do: python -m http.server, and then browsing to http://localhost:8000. However, if I just double click on dist/index.html in my browser, it fails with 404 not founds for the resources:

file:///vendor/es6-shim/es6-shim.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/reflect-metadata/Reflect.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/systemjs/dist/system.src.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///vendor/zone.js/dist/zone.js Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:21 Uncaught ReferenceError: System is not defined
file:///favicon.ico Failed to load resource: net::ERR_FILE_NOT_FOUND

Loading an app from the filesystem is a nice feature to have (also is what my boss prefers to do, to see demos, rather than messing about with http servers and installing stuff via npm, and so forth).

OSX 10.9.5

ng --version
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: darwin x64

I was just doing a bare-bones test of the tool like this:

ng new PROJECT_NAME
cd PROJECT_NAME
ng serve
ng dist -prod

**Comment by filipesilva** [comment]
For Angular 2 apps in general you really do need a server overall due to it running almost fully in html5 mode. 

The specific problem you're experiencing is due to relative paths in the vendor libs, which also doesn't work very well without a server.

**Comment by guidorice** [comment]
@filipesilva OK thanks very much for the info! Closing issue

**Comment by Wancieho** [comment]
So this is an issue with the vendors themselves? I'm trying to build to publish using Cordova and im getting a "System is not defined"?

**Comment by filipesilva** [comment]
@Wancieho I have a more detailed write-up on the whys and hows of this problem here: https://github.com/angular/angular-cli/issues/787#issuecomment-220064089. The intricacies of using different serving platforms is beyond the scope of the CLI at the moment though, since that really depends on what you choose..

I know the Ionic folks have this working on [Ionic2](http://ionicframework.com/docs/v2/getting-started/installation/), but personally I haven't dabbled in Cordova in a while so I can't give you tips as how to proceed besides comment linked in the first paragraph. I guess it mostly hinges on the base tag and systemjs config.

**Comment by jacodv** [comment]
Look at this thread [https://github.com/angular/angular/issues/13948](url)
