### ISSUE TITLE
Feature Request: File Replacements Should Accept File Name Templates

### ISSUE THREAD

**Issue by oberoivarun** [angular/angular-cli#12354]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular 6.1

### Mention any other details that might be useful

I want to use my existing code base to create a Web PWA with Angular Material Library and use Ionic Components to create a hybrid cordova application.

I'd like it if i could add a new environment configuration in angular json with file replacements option set like

```
              "fileReplacements": [
                {
                  "replace": "src/app/**.web.html",
                  "with": "src/app/**.ionic.html"
                }
              ]
```

Currently it throws an error that the file does not exist.

**Comment by fluoxa** [comment]
is there any progress on this feature request?

**Comment by rjlopezdev** [comment]
Hi @fluoxa, I'm so interested on this feature too.
My use case is `Load different providers depends on environment` & I think that fileReplacements is the option we should use in this case.

I posted [this article](https://medium.com/@rjlopezdev/angular-tips-environmental-providers-using-cli-builders-4b9f551982df) in which explain how I create different builds loading differente providers using a `--configuration` parametter (instead of adding each `service` to `fileReplacements` array).

I hope it be useful for you 😄

**Comment by alan-agius4** [comment]
Hi @oberoivarun,

Thanks for this feature request. At the moment, this feature doesn't fall in the Angular CLI roadmap.

Let's consider this in the future.

Thanks.
