### ISSUE TITLE
Unable to run unit test in Angular 5 - ng test

### ISSUE THREAD

**Issue by sivarajthava** [angular/angular-cli#12364]
While running ng test, I am getting error

"Uncaught TypeError: Zone.__load_patch is not a function".

I checked the source code in the debugger console in chrome, it is showing error ../zone.js/dist/async-test.js_global. It was worked earlier but now seems some of the dependencies got upgraded.

Dev Dependencies version:

@Angular/cli: 1.2.7,
@angular/compiler-cli:~5.2.0,
@types/jasmine:2.5.38,
@types/jasminenewd:~2.0.2,
@types/node:~6.0.60,
karma:~1.4.1,
karma-chrome-launcher:~2.1.1,
Karma-cli: ~1.0.1,
karma-jasmine: ~1.1.0,
ts-node: ^3.3.0,
talent: ~4.5.0

Dependencies:
zone. js: ^0.8.4

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by sivarajthava** [comment]
Thank you very much Alan. I upgraded my angular cli and it's worked for me. Great!!.
