### ISSUE TITLE
ng test logging

### ISSUE THREAD

**Issue by kamran-pervaiz** [angular/angular-cli#1246]
Hi Guys,

 Is it possible to output

> ng test --watch=false --build=false

to external file? so that I can parse the file in TeamCity and fail the build. I tried below

> ng test --watch=false --build=false > log.txt

but it only write True in it. It would be good to have full output in a file like

> ng test --watch=false --build=false --output=path\log.txt

**Comment by dzonatan** [comment]
If you need to correctly run tests on teamcity use [karma-teamcity-reporter](https://github.com/karma-runner/karma-teamcity-reporter) with [phantomjs](https://github.com/karma-runner/karma-phantomjs-launcher) browser (because I don't think that Chrome will work on teamcity, eventually it will timeout).

Just install these npm dependencies:
`npm i karma-phantomjs-launcher phantomjs-prebuilt karma-teamcity-reporter --save-dev`

Import them in `karma.conf.js` plugins:
```
config.set({
  ...
  plugins: [
    ...
    require('karma-phantomjs-launcher'),
    require('karma-teamcity-reporter')
  ],
  ...
});
```

And you're ready to run `ng test --watch=false --browsers=PhantomJS --reporters=teamcity`.
Using this method it will even show the details of successful/failed tests and of course fail your build if needed.

![test-ci](https://cloud.githubusercontent.com/assets/5166666/19642180/d17cd978-99ec-11e6-839c-372bf181adfe.png)

**Comment by catull** [comment]
@kamran-pervaiz Is this issue still on ?  Did you solve it ?
Otherwise, you can try this:  `ng test --watch=false --build=false 1>log.txt 2>&1`.

**Comment by filipesilva** [comment]
Closed as outdated.

**Comment by kamran-pervaiz** [comment]
@dzonatan @catull @filipesilva 
sorry i was away for other project and never tried it, I am back on the same project and will try tomorrow. will update you

**Comment by filipesilva** [comment]
@kamran-pervaiz the lines starting with `TypeError:` mean you have an error in your code that prevents TS compilation. Have a look at that, and also try using a browser other than PhantomJS (it's very outdated and has a lot of problems).

**Comment by kamran-pervaiz** [comment]
@filipesilva thanks filip I have managed to make it work for now. i uncommented polyfill.ts and it started working. as for upgrading phantomJs to other browser what is your recommendation? chrome headless? will it report to teamcity?
