### ISSUE TITLE
AngularCompilerPlugin is much slower compared to ts-loader

### ISSUE THREAD

**Issue by dhardtke** [angular/angular-cli#12669]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```
### Versions

node v10.12.0
npm 6.4.1
yarn 1.10.1
webpack 4.21.0
typescript 3.1.3
angular 7.0.0

### Repro steps

I have created a somewhat minimal reproduction: https://github.com/dhardtke/angular-vs-ts-loader with **1000 lazy-loaded components**.
AOT is *not* enabled in my repo, forkTypeChecker is enabled for both `ts-loader` and `AngularCompilerPlugin`.

### Desired functionality
Compared to `ts-loader`, the compilation is usually `2.5x` slower using the `AngularCompilerPlugin` in our project. In my reproduction repository (see https://github.com/dhardtke/angular-vs-ts-loader), the compilation takes **~13s** using `ts-loader` and it doesn't seem to finish in reasonable time using the `AngularCompilerPlugin`.

### Mention any other details that might be useful
I can see the compilation is stuck for a long time at ```72% after dependencies optimization```.
Also, I tested the plugin using the previous version of Angular and it didn't make a difference.

Might be related to https://github.com/webpack/webpack/pull/8238:

![grafik](https://user-images.githubusercontent.com/1360135/47258437-5cfe7700-d49b-11e8-9ea0-b738478f0ccf.png)

**Comment by clydin** [comment]
`transpileOnly` is always going to be faster as it doesn't compile the program as a whole.  While this will be faster, it has numerous downsides including a loss of various Typescript capabilities (e.g., const enums, namespaces, decorator metadata, etc.).

**Comment by no-more** [comment]
I would like to reopen this issue,

for me transpile only can't be the only reason.
Is it not possible to enable cache to improve build speed, at least for dev builds.

In my previous build process with webpack + tsloader + cacheloader + threadloader I could build my project in 1/10 to 1/4 of the time I need with angular-cli

Any small changes takes me hours due to build time around 3-6min. Even with watch mode it takes 10-45 seconds to rebuild (don't know why so much difference between two changes). Adding JIT compilation which add about 30-60 seconds to reload the page.

I love typescript + angular but this starts to be a huge issue.

Build time, at least in dev, should be a top priority.

**Comment by dhardtke** [comment]
@clydin 
> `transpileOnly` is always going to be faster as it doesn't compile the program as a whole.

Could you elaborate on that a little please?

> While this will be faster, it has numerous downsides including a loss of various Typescript capabilities (e.g., const enums, namespaces, decorator metadata, etc.).

But decorator metadata works flawlessly in my application. I don't really see the readme of `ts-loader` mentioning any semantical changes when using `transpileOnly` in conjunction with `fork-ts-checker-webpack-plugin` @johnnyreilly
