### ISSUE TITLE
I created a new project but there was a problem - Unhandled 'error' event

### ISSUE THREAD

**Issue by MangoWHL** [angular/angular-cli#12670]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ×] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -- v8.12.0;
npm --6.4.1;
ng --7.0.2;
 Windows (10)

### The log given by the failure

E:\>ng new kl
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
CREATE kl/angular.json (3823 bytes)
CREATE kl/package.json (1309 bytes)
CREATE kl/README.md (1019 bytes)
CREATE kl/tsconfig.json (408 bytes)
CREATE kl/tslint.json (2837 bytes)
CREATE kl/.editorconfig (245 bytes)
CREATE kl/.gitignore (503 bytes)
CREATE kl/src/favicon.ico (5430 bytes)
CREATE kl/src/index.html (289 bytes)
CREATE kl/src/main.ts (372 bytes)
CREATE kl/src/polyfills.ts (3234 bytes)
CREATE kl/src/test.ts (642 bytes)
CREATE kl/src/styles.scss (80 bytes)
CREATE kl/src/browserslist (388 bytes)
CREATE kl/src/karma.conf.js (964 bytes)
CREATE kl/src/tsconfig.app.json (166 bytes)
CREATE kl/src/tsconfig.spec.json (256 bytes)
CREATE kl/src/tslint.json (314 bytes)
CREATE kl/src/assets/.gitkeep (0 bytes)
CREATE kl/src/environments/environment.prod.ts (51 bytes)
CREATE kl/src/environments/environment.ts (662 bytes)
CREATE kl/src/app/app-routing.module.ts (245 bytes)
CREATE kl/src/app/app.module.ts (393 bytes)
CREATE kl/src/app/app.component.html (1173 bytes)
CREATE kl/src/app/app.component.spec.ts (1083 bytes)
CREATE kl/src/app/app.component.ts (207 bytes)
CREATE kl/src/app/app.component.scss (0 bytes)
CREATE kl/e2e/protractor.conf.js (752 bytes)
CREATE kl/e2e/tsconfig.e2e.json (213 bytes)
CREATE kl/e2e/src/app.e2e-spec.ts (298 bytes)
CREATE kl/e2e/src/app.po.ts (208 bytes)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by alan-agius4** [comment]
This usually means that the resolved `cwd` path is invalid.

If you do `pwd` in the terminal where you are trying to do `ng new` what is the output?

**Comment by Li-Mark** [comment]
@alan-agius4
As your tips, when I got your reply.
First, I restarted the PC and created a new project with powershell, there isn't any issue. 

Then I tried to create another project with cmd, it can be also created.

That's so weird. The issue is gone. I don't know why.
`? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
CREATE test-app/angular.json (3877 bytes)
CREATE test-app/package.json (1315 bytes)
CREATE test-app/README.md (1024 bytes)
CREATE test-app/tsconfig.json (408 bytes)
CREATE test-app/tslint.json (2837 bytes)
CREATE test-app/.editorconfig (245 bytes)
CREATE test-app/.gitignore (503 bytes)
CREATE test-app/src/favicon.ico (5430 bytes)
CREATE test-app/src/index.html (294 bytes)
CREATE test-app/src/main.ts (372 bytes)
CREATE test-app/src/polyfills.ts (3234 bytes)
CREATE test-app/src/test.ts (642 bytes)
CREATE test-app/src/styles.scss (80 bytes)
CREATE test-app/src/browserslist (388 bytes)
CREATE test-app/src/karma.conf.js (964 bytes)
CREATE test-app/src/tsconfig.app.json (166 bytes)
CREATE test-app/src/tsconfig.spec.json (256 bytes)
CREATE test-app/src/tslint.json (314 bytes)
CREATE test-app/src/assets/.gitkeep (0 bytes)
CREATE test-app/src/environments/environment.prod.ts (51 bytes)
CREATE test-app/src/environments/environment.ts (662 bytes)
CREATE test-app/src/app/app-routing.module.ts (245 bytes)
CREATE test-app/src/app/app.module.ts (393 bytes)
CREATE test-app/src/app/app.component.html (1173 bytes)
CREATE test-app/src/app/app.component.spec.ts (1101 bytes)
CREATE test-app/src/app/app.component.ts (213 bytes)
CREATE test-app/src/app/app.component.scss (0 bytes)
CREATE test-app/e2e/protractor.conf.js (752 bytes)
CREATE test-app/e2e/tsconfig.e2e.json (213 bytes)
CREATE test-app/e2e/src/app.e2e-spec.ts (304 bytes)
CREATE test-app/e2e/src/app.po.ts (208 bytes)

> node-sass@4.9.3 install C:\Users\...\test-app\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\...\AppData\Roaming\npm-cache\node-sass\4.9.3\win32-x64-64_binding.node

> circular-json@0.5.8 postinstall C:\Users\...\test-app\node_modules\circular-json
> echo ''; echo -e "\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor."; echo ''

''; echo -e "\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor."; echo ''

> node-sass@4.9.3 postinstall C:\Users\...\test-app\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\liyun\test-app\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1097 packages from 1292 contributors and audited 39125 packages in 79.669s
found 0 vulnerabilities

'git' is not recognized as an internal or external command,
operable program or batch file.`


> This usually means that the resolved `cwd` path is invalid, or the `cmd` path is incorrect.
> 
> If you do execute `pwd` and `where cmd` in the terminal where you are trying to do `ng new` what is the output?

**Comment by grebneglig** [comment]
Thanks @alan-agius4  i could resolve for me.
I tried to create an project in "D:\" and got the same error as @MangoWHL.
Then i created a project in "D:\Test\" and all was ok.
So i think the Problem was the Path.

**Comment by lranders** [comment]
I can reproduce the exact same behavior on Windows 10 if you try **ng new** in the root
of any of my drives. Make and enter a folder, and the error goes away.

**Comment by Exocomp** [comment]
I get the same issue when creating a project on root of a drive for example:

`R:\`

Create a project one level deep works:

`R:\test `

```
ng --version

Angular CLI: 7.0.3
Node: 8.9.4
OS: win32 x64
```

**Comment by amirzenoozi** [comment]
I get the same issue when creating a project on root of a drive for example:
```F:\```
Create a project one level deep works:
``` F:\TestDirectory```
But i want to create project on root of a driver 
how can i ?

**Comment by adamdport** [comment]
@amirzenoozi create the project one level deep and then move it?

**Comment by alan-agius4** [comment]
Hi, all we have identified the bug that is causing this error, as at the moment we are not handling root paths correctly in windows.

We landed a PR https://github.com/angular/angular-cli/pull/12951 to fix the issue

**Comment by TahirMehmood** [comment]
i am getting same issue but not in root drive
e:\code\FrontEnd\Angular-by-bradtraversy
still getting same error
