### ISSUE TITLE
Schematics: allow creation of custom tasks and executors

### ISSUE THREAD

**Issue by giggio** [angular/angular-cli#12678]
### Bug Report or Feature Request
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command
```
- [x] generate
```

### Versions
Node: `10.11.0`
Npm: `6.4.1`
Ng: `7.0.2`
Windows: 10, version `10.0.17134.345`

### Desired functionality

Right now there is no supported way to implement a new task, as we can't easily register an executor for the task. We are then limited to use only the ones created by the Angular team.

It should be possible to create custom tasks and easily register executors.

### Other details that might be useful

I have found that I can plug in a custom executor if I register it using the engine host from `context.engine._host` (`context` passed on to the `Rule` function). Like so:

````ts
const host = <NodeModulesEngineHost>(<any>context.engine)._host; // this line is not supported
host.registerTaskExecutor<YourFactoryOptions>({
  name: "your-executor-name",
  create: (opt) => import('../path/to/executor').then(mod => mod.default(opt))
});
````

The problem is that:

1. This is too hard;
2. This is being done for each schematic, it could be global for the collection (or not, I'd like to hear your opinion on this one);
3. It is clearly not supported, as `_host` is private.

Is this intentionally hard? If so, why is it? Do you plan to let we extend this somehow on the future? I'd like to understand the plans there.

**Comment by clydin** [comment]
This is intentional.  The tooling that hosts the schematic runtime controls the available set of tasks and their respective factories.  Schematics should not make any assumptions as to execution platform.  It could be node, it could be a web browser, or something else entirely.  Only the tooling knows which factory for a particular task needs to be registered to allow that task to function on the tooling's platform.  Schematics are also intended to be isolated from the system as a whole to protect the user of the schematic from potentially malicious behavior.  A schematic should never be accessing or manipulating anything beyond the bounds of the public API of the schematic framework.  And to that end, additional sandboxing is planned to make this a hard requirement in the future.

**Comment by giggio** [comment]
I understand the goal, but shouldn't the people who build their own schematics be able to extend it by adding tasks? Is there a way that you could enable us and still keep those goals?

**Comment by zbennett10** [comment]
This would be ridiculously awesome. I am writing a small book on schematics and was saddened to see that this feature is not supported!

**Comment by avergos29** [comment]
Thanks giggio for the workaround.
I want to apply prettier on the files generated by the schematics. In my context it consist in calling `yarn format`

What a pity there's no "official mean" to do it !

**Comment by william-lohan** [comment]
You could just use `RunSchematicTask` and then make a schematic that does what ever you want:

```ts
export function myCommandSchematic({ command, args }: { command: string; args: string[]; }): Rule {
  return (host: Tree, context: SchematicContext) => {
    return new Observable<Tree>(subscriber => {
      console.log(options.args);
      const child = spawn(command, args, { stdio: 'inherit' });
      child.on('error', error => {
        subscriber.error(error);
      });
      child.on('close', () => {
        subscriber.next(host);
        subscriber.complete();
      });
      return () => {
        child.kill();
      };
    });
  };
}
...
context.addTask(new RunSchematicTask('my-command', { comman: 'yarn', args: ['format'] }));
```

**Comment by sharikovvladislav** [comment]
Very desired feature.

@clydin Could you please suggest any legal way to register custom task?

I found this solution: https://stackoverflow.com/questions/52812085/how-can-i-create-a-task-for-schematics. Probably it is @giggio 's solution.

**Comment by bolasblack** [comment]
I think `TaskExecutor` can declare supported hosts when registering, for example:

```js
host.registerTaskExecutor<YourFactoryOptions>({
  name: "your-executor-name",
  hosts: ['node'],
  create: (opt) => import('../path/to/executor').then(mod => mod.default(opt))
});
```

Then when executing `Engine.executePostTasks`, `Engine` can check if all added tasks support execution under the current `EngineHost`, if not, throw an error.

**Comment by djencks** [comment]
I independently discovered the same solution as @giggio
However, it obviously violates the architecture.  Perhaps another approach would be to make the schematics cli tool and the node workflow easily extensible so that you can just implement your own cli extending the given one that passes the calls to     engineHost.registerTaskExecutor(MyTaskExecutor); into the cli > workflow.  By restricting the schematics collection to the one you're writing you could easily make a specific command line tool to run just your schematics.

**Comment by bmayen** [comment]
Came here to post a workaround but then saw https://github.com/angular/angular-cli/issues/12678#issuecomment-489175547. This is the same solution I landed on and it works well for most use-cases I can think of.

**Comment by wyntau** [comment]
Hi there, I recently have the same problem. And I found this issue, thanks to @william-lohan 's example, then I found `RunSchematicTask` can be a solution.

So I wrote a npm package `schematics-task`, and export a few handy methods to add task like schematics' builtin `NodePackageInstallTask`.

If anyone interest in it, please check the package [schematics-task](https://www.npmjs.com/package/schematics-task)

**Comment by dgp1130** [comment]
[@clydin already covered the general take of the Angular team](https://github.com/angular/angular-cli/issues/12678#issuecomment-431913763) around custom executors. Mainly that schematics are intended to be scoped to their particular directory and we're even hoping to provide better sandboxing in the future to enforce this more strongly. Executors inherently break out of that sandbox in an unsafe way, meaning we've been taking more direct ownership over exactly what these executors do (ie. `npm install` is a well known command with reasonable semantics for schematics use cases).

What would help us here is to understand what people actually want to *do* with custom executors. What actual use case are you are trying to meet? Understanding the actual desire here can help us identify what the best approach to support it is, which may be custom executors or may be something completely different. For example, if you want to format files after generating them, we have [a separate feature request](https://github.com/angular/angular-cli/issues/10777) for that which proposes [a more direct solution](https://github.com/angular/angular-cli/issues/10777#issuecomment-1058431142) than custom executors. Please let us know your actual use cases and we can try to identify the best path to supporting them.

**Comment by bmayen** [comment]
@dgp1130, I originally came across this issue while searching for a way to add Husky after creating a new project. Wound up creating a `post-create` collection that I call via `context.addTask(new RunSchematicTask('@my-lib/schematics', 'post-create', options));` at the end of the chain of my custom `ng-new`. From this schematic I can use child_process' `exec` to call things like `npx husky install`.

My first instinct was to use a custom executor since this seems like a similar use-case to `npm i`: after all of the schematics run and are finished creating the project files, run some additional terminal command against them. Still not confident my current solution isn't an anti-pattern, but it's working well enough for our needs for now. If there's a better solution though, I'm all ears.

**Comment by dgp1130** [comment]
@bmayen, if you want to create a new project with Husky setup, wouldn't you want to be put the `husky` execution in your project's `postinstall` script? Otherwise only the user creating the project would get Husky setup instead of everyone who downloads the repository later.

Beyond that, it doesn't seem like there are many other use cases which are running into this, so maybe we already have alternatives to them?

**Comment by bmayen** [comment]
That's a good point :) In our case we didn't run into that because these particular projects were created and maintained by one person. But you're correct that postinstall would be the preferred approach here.

**Comment by dgp1130** [comment]
In that case I think I'll close this issue for now. If anyone has a concrete use case which is pushing them to want a custom executor, please file a new issue and we can evaluate to figure out what the right approach is.
