### ISSUE TITLE
Consistent naming of options and arguments that do the same thing

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#12784]
At the moment, certain options and arguments that do the same thing should are not named the same across all schematics.

In `ng new` to skip the creation of spec files, one needs to use `--skip-test`, with an alias of `-S`, while in other schematics it is `--spec` and no alias.

In the component schematics `ng generate component`, to specify the style preprocessor you need to use  `--styleext`, while in `ng new` this is named `--style`

We should discuss this, choose the preferred namings and align all the same options to make it easier for the users.

**Comment by Gillespie59** [comment]
I prefer `--skip-test` and `--style`

**Comment by hansl** [comment]
Let's review it for v8. We have a design in place and a discussion.

**Comment by EatonZ** [comment]
When I create a new project using the just-released 6.2 CLI and `--skip-tests=true --style="scss"`, the new angular.json file uses the new `skipTests` field as expected, but instead of `"style": "scss"` under `@schematics/angular:component`, I still see `"styleext": "scss"`.

The PR clearly states "_styleext has been deprecated in favor of style since the latest is two words._", so this appears to be have been overlooked for new project creation.

**Comment by EatonZ** [comment]
@alan-agius4 @hansl @kyliau See above - behavior hasn't changed in the latest version so just checking if anyone saw this comment.

**Comment by alan-agius4** [comment]
@EatonZ, just saw your comment. Ideally, you open new issue when there is a bug.

That said, I will land a PR for this soon, since it's a minor thing.
