### ISSUE TITLE
NG Serve Doesn't Find All Dependancies. 

### ISSUE THREAD

**Issue by drumilpatel** [angular/angular-cli#12925]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### The log given by the failure
There are no errors in compilation and everything seems alright.

### Mention any other details that might be useful
When i run my project on the domain name with webserver backend as NGINX, it gets stuck on the loading page but if the same app is run without the domain name, that is on the IP Address:4200, it all loads fine. 

Please bear in mind that I am using a reverse proxy on NGINX which pushes port 127.0.0.1:4200 to IPADDR which then routes to the domain name. 

I tried replacing the localhost IP with my Public IP but no soap. It doesnt look like an issue with my NGINX Config as its syntax and configs pass the "nginx -t" and "nginx -T)

**Comment by alan-agius4** [comment]
Hi, I am sorry but there is not enough information here that we can use in order to find what’s going on. Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
