### ISSUE TITLE
typings (intellisense) not working in spec files

### ISSUE THREAD

**Issue by bluefalcon** [angular/angular-cli#1297]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
--Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: win32 x64

node--> v6.2.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Yes app was created using angular-cli.
--created new project (ng new PROJECT_NAME)
--npm install
--App builds and works fine.

--Go to e2e folder and the jasmine namespace works just fine
--Do ng g component foo
--go to spec file 'foo.component.spec.ts' and the jasmine namespace is not recognized.
--go to 'foo.component.ts' and the jasmine namespace is recognized

I also installed lodash and have the same exact results.  lodash works fine in foo.component.ts but not foo.component.spec.ts

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no log information available

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by bluefalcon** [comment]
I added a reference to main.d.ts at the top of the spec file and it now works.
---/// <reference path="../../../typings/main.d.ts" />

Just curious, why is the reference not needed for 'foo.component.ts', but required for 'foo.component.spec.ts'?

**Comment by delasteve** [comment]
@bluefalcon I'm curious, did you upgrade your project to `rc.4`? If yes, did you remove the imports for jasmine (`expect`, `describe`, etc) at the top of the `*.component.spec.ts` file because of the new release notes?

@Brocco - I've been noticing this since my PR https://github.com/angular/angular-cli/pull/741 (using the latest master CLI) from the other day. It will compile just fine, but just complain that it doesn't know what `beforeEach` (among all the others) is. I don't think the PR was wrong to get rid of them since they are now `@deprecated`, but rather that I forgot something and just unfamiliar enough to not know immediately what I missed. 

If you (or anyone else) know what I need to do, I'll make a PR asap to get this fixed. I do think the `/// <reference path="../typings/main.d.ts" />` at the top of the spec files is probably not the solution we want.

**Comment by bluefalcon** [comment]
@delasteve  No I have not upgraded to rc.4 yet and haven't removed any of the imports.

**Comment by bampakoa** [comment]
@delasteve I have upgraded to CLI beta 10 which contains Angular RC4, removed the deprecated imports for jasmine (expect, describe, etc..) from the top of my spec files and I have the same problem as @bluefalcon.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455, since we don't use the files property in tsconfig anymore.

There's another problem having a similar effect but on TS's side: https://github.com/Microsoft/vscode/issues/9232
