### ISSUE TITLE
ng e2e --grep issue

### ISSUE THREAD

**Issue by DmitrijK** [angular/angular-cli#13020]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
I would like to tag Protractor tests and run them using tags. Currently `ng e2e` is not supporting --grep option:
`Unknown option: '--grep'`

This feature would solve a problem of running tagged tests and with different tags.

**Comment by PoovinPR** [comment]
@DmitrijK @alan-agius4  Is there any workaround to run only tagged tests(Example: '@smoke' and '@regression') from a specific test suite? In case, if there is one please let me know.

**Comment by jdgarvey** [comment]
I am also running up against this issue.
The issue appears to be that the [Angular Protractor Builder](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular/src/protractor) does not support the `grep` argument (or `invertGrep` for that matter). See the [schema](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/protractor/schema.json).

@PoovinPR what we did to get around it is to use a base `protractor.conf` file, then create additional `protractor.conf` files that extend the base with the `jasmineNodeOpts.grep` property.

### protractor.conf.js
```
...
exports.config = {
    // All the normal config here
}
```

### protractor.\<tagName\>.conf.js
```
var globalConf = require('./protractor.conf.js').config;
globalConf.jasmineNodeOpts.grep = '<tagName>';
globalConf.jasmineNodeOpts.invertGrep = true; // exclude the above tag
exports.config = globalConf;
```

Then since `--protractorConfig` _is_ a recognized argument for the Protractor Builder, you can run `ng e2e <e2e-app> --protractorConfig protractor.<tagName>.conf.js`.

**Comment by dgp1130** [comment]
This sounds like a reasonable idea. It's flexible and useful enough. This isn't a major priority right now, but we would welcome any PRs implementing this.
