### ISSUE TITLE
ng build Library --aot --prod

### ISSUE THREAD

**Issue by zengwe** [angular/angular-cli#13040]
I create a library by command('ng generate library my-library').
use 'ng build my-library' and work successful.
but use 'ng build my-library --prod --aot',  not work.
please help me.

**Comment by alan-agius4** [comment]
Angular CLI no longer creates a production for libraries, as there is a single ng-packagr configuration. Since previously two different confiurations were dist folder was kept for none `--prod` builds.

Unless you create a production configuration you shouldn't be needing `--prod` for libraries.

Libraries get only build in AOT mode, thus `—aot` In not available.
