### ISSUE TITLE
Exclude other source.*.xlf files from locales during build (reducing bundle size)

### ISSUE THREAD

**Issue by gtsopour** [angular/angular-cli#13069]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently all source.*.xlf files are bundled in each build

## Expected behavior
Include only current source.{lang}.xlf file each build

## Minimal reproduction of the problem with instructions

I am using currently the following script but analysing after the bundle size, I can see my other xlf files too for other languages.
`ng build --prod --stats-json --configuration=production --output-path=dist --i18n-file=src/locales/source.de.xlf --i18n-format=xlf --i18n-locale=de`

## What is the motivation / use case for changing the behavior?

Reduce Application size

**Comment by martinvillysson** [comment]
I'm also experiencing this but I cannot remember that it was like this before. Has something changed in a recent update?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
