### ISSUE TITLE
Add flag for OnPush ChangeDetection

### ISSUE THREAD

**Issue by Mohendran** [angular/angular-cli#13327]
### Need to add flag for OnPush ChangeDetection and add it in angular.json

This is a Feature Request. My idea is to add a flag while creating a new angular project.
The flag should make OnPush changeDetection as the default.

ForExample:
ng new new-project --changeDetection=OnPush

**Comment by alan-agius4** [comment]
The ng new, creates a single component, and it would be trivial to change the change detection yourself for the root component. Since apart from `changeDetection` there are other things that you might want to change in the app component, such as `viewEncapsulation`.


That said, if you want all components of your application to be generated with `changeDetection` of `onPush` you can use set this via the config.

```cmd
ng config schematics.@schematics/angular.component.changeDetection OnPush
```

See: https://angular.io/cli/config
