### ISSUE TITLE
Wrong path creating a Lib in a existing project.

### ISSUE THREAD

**Issue by andmaltes** [angular/angular-cli#13341]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: v10.12.0
NPM: 6.4.1
CLI: 7.1.4

### Repro steps

1. I had an existing project with two apps on it.
2. ng generate library etpMenu
3. ng build etpMenu. 
Error thrown: 
BUILD ERROR
../etp-menu/src/projects/bookingtome.ts(5,15): error TS2307: Cannot find module './lib/etp-menu.service'.
../etp-menu/src/projects/bookingtome.ts(6,15): error TS2307: Cannot find module './lib/etp-menu.component'.
../etp-menu/src/projects/bookingtome.ts(7,15): error TS2307: Cannot find module './lib/etp-menu.module'.

4. Opened ts file: 
/*
 * Public API Surface of etp-menu
 */

export * from './lib/etp-menu.service';
export * from './lib/etp-menu.component';
export * from './lib/etp-menu.module';

5. Real path that works:

/*
 * Public API Surface of etp-menu
 */

export * from './../lib/etp-menu.service';
export * from './../lib/etp-menu.component';
export * from './../lib/etp-menu.module';

### Desired functionality

Path correctly created

### Mention any other details that might be useful

EDIT:

Now that I have changed the path, I am receiving the following error:

BUILD ERROR
error TS6059: File 'E:/RepositorioWebService/WebSites/Angular/projects/etp-menu/src/lib/etp-menu.component.ts' is not under 'rootDir' 'E:\RepositorioWebService\WebSites\Angular\projects\etp-menu\src\projects'. 'rootDir' is expected to contain all source files.
error TS6059: File 'E:/RepositorioWebService/WebSites/Angular/projects/etp-menu/src/lib/etp-menu.module.ts' is not under 'rootDir' 'E:\RepositorioWebService\WebSites\Angular\projects\etp-menu\src\projects'. 'rootDir' is expected to contain all source files.
error TS6059: File 'E:/RepositorioWebService/WebSites/Angular/projects/etp-menu/src/lib/etp-menu.service.ts' is not under 'rootDir' 'E:\RepositorioWebService\WebSites\Angular\projects\etp-menu\src\projects'. 'rootDir' is expected to contain all source files.

Thanks.
Andres

**Comment by alan-agius4** [comment]
Hi, 

Thanks for reporting this, however, I am not understanding the problem here with the reproduction steps you provided. 

In the step the error mentions some files which are not generated by the Angular-CLI example `../etp-menu/src/projects/bookingtome.ts`. There is no such folder structure in a newly generated library.

Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

Please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
