### ISSUE TITLE
Feature request: ng build: specify custom hash seperator

### ISSUE THREAD

**Issue by jochemmm** [angular/angular-cli#13460]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

ng version: `7.2.1.` of higher

### Desired functionality
Please extend ng build "hashing"-functionality with an option for specifying a hash char seperator.  
Desired `ng build` output example (please note the hyphen char):  
```
4_e0eea817028b65a58594.js
index.html
main_4823029cee2e28b426e2.js
polyfills_e6fbd82b34ccb0c8609f.js
runtime_c0ed55cd00207df1e4c1.js
styles_3ff695c00d717f2d2a11.css
```

### Mention any other details that might be useful
Root cause problem:  
Sitecore CMS system doesn't allow files to be upload with dot's in the file name.

**Comment by mgechev** [comment]
I'd prefer if we don't introduce an additional configuration option. Maybe it's worth it to switch from `.` to `_` for all users.

**Comment by alan-agius4** [comment]
I think we can change this to a `-`, to follow the current lazy loaded named file name.

**Comment by filipesilva** [comment]
Heya, we've just discussed this issue as a team and this isn't something that we're looking at doing right now.

We don't want to add an option specifically for this because we want to avoid very granular and situational options. If anything we want less options right now.

Switching the separator was also considered. It would just make your problem go away, but it would be a breaking change for us because now bundles would follow a different format. And being a breaking change means that it would require everyone that currently depends on the current file format to change their integrations.

We don't think that's worth doing because it would affect a fair number of people and at the end of the day filenames with dots are valid filenames. I agree that your CMS not supporting that is unfortunate but that really sounds like a bug at their end.

I think your best solutions are:
- use https://github.com/manfredsteyer/ngx-build-plus/tree/master/ngx-build-modern to change the separator yourself
- use a script that renames files after builds, and before the upload

**Comment by jochemmm** [comment]
Thanks for you consideration. I'm going to look for another solution in my case.
