### ISSUE TITLE
--base-url has no effect

### ISSUE THREAD

**Issue by Michel73** [angular/angular-cli#13611]
# 🐞 Bug report

The option `--base-url` has no effect. 

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.x.x

### Description

 
The option `--base-url` has no effect on the `e2e`-command. Also the `baseUrl`-entry in the `protractor.conf.js` has no effect.

## 🔬 Minimal Reproduction

Create new project via `ng new demo` and there modify the `e2e`-script or the `protractor.conf.js` as described. It has no affect. The app is always started at `http://localhost:4200` and the browser also opens this url. 
I have to run the tests in a no-serve scenario on a different url.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

macos
@angular/cli@7.3.0 
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@Michel73, most likely the root cause of this is that you have a `devServerTarget` specified. Hence it will always use the this.

Can you try `ng e2e --dev-server-target="" --base-url="https://localhost:8080"`?

I think we should emit an error when both `base-url` and `dev-server-target` are specified.
