### ISSUE TITLE
@angular/pwa does not work correctly when using custom builders

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular-cli#13679]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ x ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

``@angular/pwa`` needs to update the ``index.html`` to reference the web app manifest and it also needs to put the manifest into the assets array in the ``angular.json`` file.

To find the ``index.html`` files in question, it looks ups the targets that use specific builders (``@angular-devkit/build-angular:browser``, ``@angular-devkit/build-angular:karma``). To the same targets, it adds the manifest file as an asset.

Hence, ``@angular/pwa`` does not work, if one uses custom builders instead of the two mentioned ones.

To solve this, we could just directly update the targets with specific names, like ``build`` or ``test``.

## 🔬 Minimal Reproduction

- ng new myproject
- replace your builders in angular.json with custom ones (just edit the ``builder`` nodes; I don't think that the mentioned builders need to exist for this reproduction)
- ng add @angular/pwa
- Find out that the ``index.html`` has NOT been updated and that the manifest is not included into the ``assets`` array in your ``angular.json``

**Comment by clydin** [comment]
This is intentional for several reasons:
* The custom builder may not have the options
* The custom builder may have differently named but equivalent options
* The custom builder may have options with the same name but they provide different behavior or allowed values.

Using a set of known builders is currently the only viable option to ensure the schematic does not break an existing project.
Potential solutions are to elevate standard properties of a project to the project definition itself or provide a standardized facility to query a builder for its capabilities.

**Comment by manfredsteyer** [comment]
Could we just assume that there is a index property and a assets property? In most cases it should be there and if not, the result is the same as now: It does not work.

**Comment by manfredsteyer** [comment]
We could also just do this, when the caller provides a `--force` flag. I think, chances are high, that there will be an index and an assets property as most builders will extend existing ones. And if not, as mentioned, the result is the same (does not work).

**Comment by alan-agius4** [comment]
Hi @manfredsteyer,

Thanks for this feature request. However, there is very little interest in this feature and therefore I am going to close. Let's reconsider this in the future.

Thanks.
