### ISSUE TITLE
Make command to show default webpack config

### ISSUE THREAD

**Issue by glemiere** [angular/angular-cli#13737]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] eject
```

### Description
Problem: ng eject being disabled to reduce learning curve, it is now an absolute hell to find the default angular webpack config (I still did not find it).

### Describe the solution you'd like
Create a command to replace ng eject, but instead of ejecting the config, just print it out so that we can see the default behaviors and avoid breaking things when customizing webpack.

### Describe alternatives you've considered
Spent quite a bunch of time trying to find the default webpack config in my node_modules folder, still don't know where it is.

**Comment by alan-agius4** [comment]
This sounds like a useful feature for some, in the same time we should be careful how we increase the scope of the CLI because each new feature means new code to maintain and fix issues in.

In this particular case, I'd suggest to hold this off for now and revisit in future.

Let's reopen if more folks need such feature.

The webpack config files can be found here: https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs

**Comment by lightcoresystems** [comment]
I think its a good Idea ;) I also spent a lot of time on searching default webpack.config.. Sucha command would reduce this time

Regards

**Comment by chavlji** [comment]
Totally agree there should be a way to see config file.
It's very hard to override something you can't see.
