### ISSUE TITLE
Environment don't loaded

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular-cli#13997]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I have three environment whit this properties

```
environment.ts
HASVIDEOCALL: {
    VIDEOCALLURL: 'https://trial.herokuapp.com'
  },
environment.prod.ts
HASVIDEOCALL: {
    VIDEOCALLURL: 'https://trial.herokuapp.com'
  },
environment.costumer.ts
HASVIDEOCALL: false
```

in angular.json I have

            "costumer": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.hasis.ts"
                },

And use this variable in some service like opentok.service.ts with this:

```
  getSessionConfig(room) {
    if (environment.HASVIDEOCALL) {
      let url = environment.HASVIDEOCALL.VIDEOCALLURL + '/room/' + room;
      return this.http.get(url);
    }
  }
```

And now I try to start this enviroment with this:

`ng serve --configuration=costumer`

but the Terminal says:

> src/app/services/opentok.service.ts(21,42): error TS2339: Property 'VIDEOCALLURL' does not exist on type 'true'.
> 
> i ｢wdm｣: Failed to compile.

But as you can see, the type its not true.

An still more extrange it's if I modify any file, only with a console.log, when I save it, automatically rebuild the app and it's works without problems.

Do you know how it happens?

So sorry if this is not the forum to ask for it, but I thought this is a bug...

**Comment by alan-agius4** [comment]
This is expected as TypeScript won't allow that and type-checking will fail during compilation. The type of `HASVIDEOCALL`  is indeed `true` in this case. This is because when replacing the file the source code will look like;

As the replaced source will look like;
```ts
const environment = {
  HASVIDEOCALL: false
}

if (environment.HASVIDEOCALL) {
  let url = environment.HASVIDEOCALL.VIDEOCALLURL;
}
```

Closing as this is working as expected.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
