### ISSUE TITLE
Static analyzer: obvious side-effects in getters

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#14356]
Maybe we should warn/error when we find assignments in a getter method.

Related to #14316

Igor says we should keep pure_getters on

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
