### ISSUE TITLE
Proposal: Budgets for actual payload size after compression

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-cli#14536]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

Currently, `budgets` feature is validating generated JS bundle size. Usually, it is not delivered from server to browser directly. In most cases, it is compressed (gzip or brotli, etc) during deployment.

To improve page-loading performance, what developers should care about is the actual payload JS size. Even if the same 1MB, it may be 400KB or 300KB depending on the compression result. It is a big difference for users.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

I want a way to validate a compressed bundle size with `budgets` feature.

My current idea is adding budget types like `initial:gzip` and  `bundle:gzip`. Or adding a new field like `compressed: boolean` . 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
This is quite interesting however gzip and brotli compression levels varies from one server or CDN to another and there is no fixed equation to determine the final compressed size.

This is because gzip and brotli compression have various levels, the compression levels start at 1, and increase. The higher the compression level, the smaller the file (and the more computationally expensive the compression is).

Consider this, I don’t think it would be a good idea to determine the budget sizes based on compression.

That said, I don’t agree that developers shouldn’t care about the uncompressed JS, because JS needs to be evaluated, even with different compression levels the same Javascript will need to be evaluated which might still be a performance bottleneck. With compression you will improve one of the performance matrix which is reducing the data transfer over the wire but it won’t effect the scripting time.
