### ISSUE TITLE
ng build base-href issue (angular cli 8)

### ISSUE THREAD

**Issue by Mek89** [angular/angular-cli#14583]
Hi,

the base-href flag works differently in angular 8. I hope you can help.

In angular 7:
`ng build --prod app1 --base-href /app1/`

after the command all my relative path in the scss are changed to the proper one.
source:
`.example {
   background: url('/assets/img/picture.png') no-repeat center center;
}`
deployed:
`.example {
   background: url('/app1/assets/img/picture.png') no-repeat center center;
}`

With angular 8 nothing happen:
source:
`.example {
   background: url('/assets/img/picture.png') no-repeat center center;
}`
deployed:
`.example {
   background: url('/assets/img/picture.png') no-repeat center center;
}`

Thank you!

**Comment by alan-agius4** [comment]
Kindly follow the issue template. Thanks

**Comment by codler** [comment]
I have similar problem

**Comment by achieverprince** [comment]
I am also having the same issue.

**Comment by clydin** [comment]
This is expected behavior.  Previous versions of the CLI were errantly modifying root relative URLs.  One of the prime use cases of a root relative URL is to reference files from the root of a domain; modifying root relative URLs as was done previously prevent this from occurring.  Please also note that the HTML base HREF is a runtime browser value.  The browser also does not modify root relative URLs and the base HREF has no effect on such URLs.
