### ISSUE TITLE
@ngtools/webpack - enable sourceMap generates different build

### ISSUE THREAD

**Issue by sod** [angular/angular-cli#14617]
`@ngtools/webpack` produces different javascript output if you toggle the sourceMap setting. With source maps enabled, the compiler seems to include imports, that shouldn't be there.

Angular: 8.0.0 (but issue is present in 7.2.x as well)
Reproduction: https://github.com/sod/issue-ngtools-14617

Compare both dist-* folders. The only difference in the build is the `--source-map` flag. In one build the chunk `big-dependency` is missing and was inlined by webpack.

You can try to build it yourself with either one:

```bash
ng build --prod --aot --build-optimizer --source-map
ng build --prod --aot --build-optimizer
```

If you watch the output with `--source-map` of the ngtools/webpack loader in https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/loader.ts#L104, I see for the file https://github.com/sod/issue-ngtools-14617/blob/master/src/app/lorem/lorem.service.ts this output:

```typescript
import { BigDependencyOptions } from 'src/app/lorem/big-dependency';
import * as i0 from "@angular/core";
var bigDependencyLoader = function () { return import(/* webpackChunkName: "big-dependency" */ '../lorem/big-dependency'); };
var ɵ0 = bigDependencyLoader;
var LoremService = /** @class */ (function () {
    function LoremService() {
    }
    LoremService.prototype.load = function (options) {
        return bigDependencyLoader().then(function (m) { return new m.BigDependency().setOptions(options); });
    };
    LoremService.ngInjectableDef = i0.ɵɵdefineInjectable({ factory: function LoremService_Factory() { return new LoremService(); }, token: LoremService, providedIn: "root" });
    return LoremService;
}());
export { LoremService };
export { ɵ0 };
```

`BigDependencyOptions` is an Interface and only used as a type, that import should not be visible in javascript. If you throw the source into [typescriptlang](http://www.typescriptlang.org/play/index.html#src=import%20%7BBigDependency%2C%20BigDependencyOptions%7D%20from%20'src%2Fapp%2Florem%2Fbig-dependency'%3B%0Aimport%20%7BInjectable%7D%20from%20'%40angular%2Fcore'%3B%0A%0Aconst%20bigDependencyLoader%20%3D%20()%20%3D%3E%20import(%2F*%20webpackChunkName%3A%20%22big-dependency%22%20*%2F'..%2Florem%2Fbig-dependency')%3B%0A%0A%40Injectable(%7BprovidedIn%3A%20'root'%7D)%0Aexport%20class%20LoremService%20%7B%0A%20%20%20%20load(options%3A%20BigDependencyOptions)%3A%20Promise%3Cany%3E%20%7B%0A%20%20%20%20%20%20%20%20return%20bigDependencyLoader().then((m%3A%20%7BBigDependency%7D)%20%3D%3E%20new%20m.BigDependency().setOptions(options))%3B%0A%20%20%20%20%7D%0A%7D), you see that tsc wouldn't include that import as well.

We use an error reporting tool where we can upload the source maps to get better reports. But this behavior increases our build by ~100kb so we compile without source maps right now.

**Comment by sod** [comment]
Reproduction: https://github.com/sod/issue-ngtools-14617

Compare both dist-* folders. The only difference in the build is the `--source-map` flag. In one build the chunk `big-dependency` is missing and was inlined by webpack.

The reproduction doesn't reflect the issue we got, but it at least shows that just turning source map on/off alters the build output, whereas I'd assume that the builds should be identical, with either source maps on or off.

**Comment by filipesilva** [comment]
This seems unintended. I'm not sure why that would change... if you're interested in looking at this bug, I expect https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts is the right place.

**Comment by filipesilva** [comment]
I'm investigating this problem but I am a bit confused by your report and repro.

`lorem.service.ts` is part of a lazy chunk and looks like this:
```
import {BigDependency, BigDependencyOptions} from 'src/app/lorem/big-dependency';
import {Injectable} from '@angular/core';

const bigDependencyLoader = () => import(/* webpackChunkName: "big-dependency" */'../lorem/big-dependency');

@Injectable({providedIn: 'root'})
export class LoremService {
    load(options: BigDependencyOptions): Promise<any> {
        return bigDependencyLoader().then((m: {BigDependency}) => new m.BigDependency().setOptions(options));
    }
}
```

You have both a static import to `big-dependency`:
```
import {BigDependency, BigDependencyOptions} from 'src/app/lorem/big-dependency';
```
and a dynamic import:
```
const bigDependencyLoader = () => import(/* webpackChunkName: "big-dependency" */'../lorem/big-dependency');
```

You expect the direct import to be removed because `BigDependencyOptions` is an interface and also because `BigDependency` is unused.

In `dist-with-source-map-true` we can see the `big-dependency.b63b360e949b2fda8373.js` chunk. This means that the static import was removed, and only the dynamic import remained, otherwise there would be no lazy chunk.

In `dist-with-source-map-false` there is no `big-dependency.b63b360e949b2fda8373.js` chunk. Instead, it's contents are rolled into the other lazy chunk, `5.abbe2b336002b205b922.js`. You can verify that is true because `5.abbe2b336002b205b922.js` contains two results `setOptions`: one for the `BigDependency` class definition and one for it's invocation in `LoremService`. In `dist-with-source-map-true` those two results for `setOptions` are split among the two lazy chunks instead.

So at this point I can see that setting source-maps to false prevents a lazy chunk from being generated.

Yes this looks like a weird problem. But it doesn't impact total bundle size. You mention that this bug increases your build size by ~100kb but I am not seeing that here. What I see instead is that the contents of a lazy chunk were inlined in another chunk. So same total size, but different distribution.

What also confuses me is that you say that you have to disable sourcemaps. But disabling sourcemaps is what causes the inlining. According to this repo, I expected you to have to enable sourcemaps in order to actually have a lazy loaded chunk.

I'll continue looking into why there's a difference of behaviour regardless.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/16085 should fix this. 

What happened was this:
- we remove angular decorators as a transformation to speed up builds by removing unneeded symbols
- when a transform removes references, TS doesn't know it should remove their imports
- thus we manually add a pass to remove imports whenever we remove or modify nodes
- in this example our import removing pass identified both `BigDependency` and `import {Injectable} from '@angular/core;` for removal
- removing `BigDependency` altered the original `import {BigDependency, BigDependencyOptions} from 'src/app/lorem/big-dependency';` and caused TypeScript to not identify `BigDependencyOptions` for removal anymore.

Now we correctly identify type references as not being a usage for an import, for eliding purposes.

**Comment by sod** [comment]
nice, thank you :)
