### ISSUE TITLE
cli-builds repo `master` branch has outdated `package.json#version`

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular-cli#14692]
Looking at https://github.com/angular/cli-builds/blob/master/package.json#L3 you can see that the `master` branch builds have an outdated version:

```
  "version": "8.0.0-beta.18+168.6ec0991",
```

The same property on the `stable` branch (https://github.com/angular/cli-builds/blob/8.0.x/package.json#L3) has a more recent version:

```
  "version": "8.0.0+13.958d4cc",
```

This impacts the CLI docs on next.angular.io, since we use this `version` property to compute the tag that we should use when creating links from the docs pages to the source code in Github. See https://github.com/angular/angular/pull/30889

Can we fix this? Perhaps we need to deploy a new snapshot from `master`?

**Comment by alexeagle** [comment]
the publishing still happens, you can see we keep updating the SHA on that line like the last commit
https://github.com/angular/cli-builds/commit/4200ccb6e3f4e83104441b17ca9774c48dff7e64#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
I don't know where the beta.18 is coming from though. Can't find anything in a short tour of the snapshot publishing code. It happens to be stuck at the last beta tag, even though there are newer tags.

**Comment by gkalpak** [comment]
Maybe it is because the subsequent tags are created from commits that are not on master, but on the 8.0.x branch (i.e. they are not reachable from the latest master commit), so [git describe][1] can't find them.

[1]: https://github.com/angular/angular-cli/blob/e70b0e41bc13512c9cf56846ba0e39a8fab64e61/lib/packages.ts#L165

**Comment by alexeagle** [comment]
I see, it's because we haven't cut a next version 8.1.x of CLI yet, so there's no reasonable place to get docs for next.angular.io. I suppose it will sort itself as soon as we have an 8.1 release from master?
Is it urgent?

**Comment by filipesilva** [comment]
I know why this happens. It's because of our logic to get the version:
https://github.com/angular/angular-cli/blob/30345c34995e1d683f6b96395635ecaf749cfbb1/lib/packages.ts#L159-L175

We get it from git tags on the current branch. I don't think it's gotten tags in a while now.

**Comment by filipesilva** [comment]
It might be because the caretaker builds on master, or maybe because they didn't pull tags before.

```
kamik@RED-X1C6 MINGW64 /d/work/cli (decrypt-md)
$ git co 8.0.x
Switched to a new branch '8.0.x'
Branch '8.0.x' set up to track remote branch '8.0.x' from 'upstream'.

kamik@RED-X1C6 MINGW64 /d/work/cli (8.0.x)
$ git describe --match v[0-9].[0-9].[0-9]* --abbrev=7 --tags
v8.0.2-9-g3bfba54

kamik@RED-X1C6 MINGW64 /d/work/cli (8.0.x)
$ git co master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

kamik@RED-X1C6 MINGW64 /d/work/cli (master)
$ git describe --match v[0-9].[0-9].[0-9]* --abbrev=7 --tags
v8.0.0-beta.18-209-g30345c3
```

**Comment by gkalpak** [comment]
@filipesilva, yeah, that's what I meant in https://github.com/angular/angular-cli/issues/14692#issuecomment-499813221. It is expected, I guess as long as there is no release from the master branch after rc.

##
> Is it urgent?

@alexeagle: The problem we have is that the links to view the source for the cli commands on next.angular.io go to the old beta.18 version, which might be outdated (and also does not correspond to the content shown on next.angular.io). For an example of a bad link see the `View Source` link at the top right corner of https://next.angular.io/cli/add.

The `Edit Source` links are fine, because they always point to master (because we want PRs to be submitted against master most of the time). angular.io (stable) is also fine.

So, I would say it is not a huge deal (because I assume only a small number of people are affected), but confusing nonetheless.

**Comment by alan-agius4** [comment]
Closing as it appears to no longer be a problem.
