### ISSUE TITLE
Styling issue when creating a new project

### ISSUE THREAD

**Issue by psingl** [angular/angular-cli#14768]
Suppose we create a  new project using the command `ng new <project_name> --style=sass`
The new project when created successfully contains a file named `styles.scss` but in and the angular cli build configuration file `angular.json` the file points to `styles.sass` as we are selecting sass preprocessor while creating a new project.

So while serving the project on localhost or building it shows an error of Module not found.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
