### ISSUE TITLE
Add universal option to ng new

### ISSUE THREAD

**Issue by Fufuxx** [angular/angular-cli#14963]
# 🚀 Feature request

Add on universal option on ng new schematic to allow creation of new application with universal features.

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Allow generation of basic universal app through ng new schematic.

### Describe the solution you'd like

New ng new option 'universal' boolean default false that would run ng universal schematic if set to true on application creation.

### Describe alternatives you've considered

Alternative is to run it separately as it is now. Maybe there is a reason for it that I am not foreseeing.

### add-on

I would very much like to contribute and give a try of setting this up myself :)

**Comment by alan-agius4** [comment]
Hi @Fufuxx, thanks for your interest in this and the PR. 

Yesterday, we discussed this during our meeting and we think it's best not to add this feature because the universal schematic alone doesn't generate a working universal application, since it will not generate any server code that is needed to serve the SSR'd application. 

Typically users shouldn't use this schematic to generate a working Universal application but rather do it via `ng add @nguniversal/express-engine` or `ng add @nguniversal/hapi-engine`. 

Docs: https://angular.io/guide/universal

The universal schematic is used for other use cases, such as; App Shell, and the the above `ng add` packages uses this as part of their code generation.

Thanks for your understanding.
