### ISSUE TITLE
Angular 8 and CLI 8 do not build noticeable smaller bundles for es2015

### ISSUE THREAD

**Issue by zijianhuang** [angular/angular-cli#15004]
# 🐞 Bug report

### Command (mark with an `x`)

```

- [ x] build

```

### Description

According to https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27, the bundle size with NG8 CLI8 could be 7-20% smaller. However, in my big fat NG client, 
when with NG7 CLI7, the production bundle size for es2015 is 5.17 MB, excluding assets.
when with NG8.1 CLI8.1, the production bundle size for es2015 is 5.16 MB, excluding assets.

So less than 1% difference.

## 🔬 Minimal Reproduction
@filipesilva , this is loosely related to #13734 in which you had done the benchmark for memory consumption during build, with the repro of my big fat SPA. So I would presume that you can analyze this with the same repro.

**Comment by clydin** [comment]
The title is somewhat misleading as the bundles are indeed smaller just not as small as you expected.  Since your application is already ES2015 only and assuming that any unneeded polyfills are already removed, this particular application won't see the size reduction benefits as many applications would due to the application only supporting ES2015+ browsers.  IE11 is still a browser that many still need to target.

Note this paragraph from the linked blogpost in the differential loading section and the "for modern browsers" aspect:
>On angular.io we saved over 40kB of initial bundle size for modern browsers. From the community we’ve heard that applications generally save 7–20% of their bundle size, depending on the amount of modern JavaScript features they take advantage of.

**Comment by zijianhuang** [comment]
thank you for the clarification, which I had suspected such too. However, I was not sure if I had missed some "magic" switches in NG 8 and CLI 8 which may produce more optimization for smaller bundles of es2015.

**Comment by alan-agius4** [comment]
Closing as there is nothing to action. As explained by @clydin in the above comment.
