### ISSUE TITLE
Issue with module Aliasing in project lib 

### ISSUE THREAD

**Issue by parasharsh** [angular/angular-cli#15076]
I am creating a library project using Angular CLI. I plan to use aliasing for imports in the library project. So I defined the paths in the tsconfig.json of library project. The library project does compile fine after this. But the main application fails to compile with error can not find module for the library files under dist. This project shows the problem on running ng serve. https://github.com/parasharsh/angularprojects

Error is:
ERROR in dist/foo-lib/lib/foo-lib.component.d.ts(2,31): error TS2307: Cannot find module '#lib/foo-lib.service'.

Do i need to do any special steps to use aliasing in the library project. Why does ng serve or ng build again compiles the files under dist.
- [ X] build
- [ X] serve

**Comment by alan-agius4** [comment]
Hi, this is expected and this is by TypeScript design. Paths don’t get re-rewired when emitted. See: https://github.com/Microsoft/TypeScript/issues/10866

Hence, when building a library you should only use paths to change the location of an external module lookup. Not to make an import look clean. 

When using nice imports like `@app/foo` This works in an application because of tools such as webpack as running the javascript code directly won’t work as it’s not valid.

Ideally you should not output js code that doesn’t rely on tooling to work. Hence I would strongly discourage using `paths` to shorten the import and make them look clean.

`paths` Ideally should be used to change the resolutions and not to change the module import statement.
