### ISSUE TITLE
add text when building using ng build --prod

### ISSUE THREAD

**Issue by callmeblessed** [angular/angular-cli#15107]
request feature:

Adding text when compiling with ng build --prod.
first time using angular 8 from 7  I am confused because the ng build compile the project twice. Later I was informed that Angular 8 compiled twice for optimization / compatibility with old browser.

How about you add text like "building for ES5, to disable this build type xxxxx " when running ng build --prod

**Comment by alan-agius4** [comment]
This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
