### ISSUE TITLE
ctorParameters not stripped from BrowserPlatformLocation and TestabilityRegistry in prod builds

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#15194]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
yes

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

```
yarn global add @angular/cli@next
ng new test-app
cd test-app
ng build --prod
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

If I disable terser mangling, I'll see that ctorParams survived the build optimizer scrub pass on:

```
            /** @nocollapse */            return BrowserPlatformLocation.ctorParameters = () => [ {
                type: void 0,
                decorators: [ {
                    type: Inject,
                    args: [ DOCUMENT ]
                } ]
            } ], BrowserPlatformLocation;
```

and 

```
            TestabilityRegistry.ctorParameters = () => [], TestabilityRegistry;
```

This happens both with and without Ivy

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.2.0-rc.0
Node: 10.11.0
OS: darwin x64
Angular: 8.2.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-rc.0
@angular-devkit/build-angular     0.802.0-rc.0
@angular-devkit/build-optimizer   0.802.0-rc.0
@angular-devkit/build-webpack     0.802.0-rc.0
@angular-devkit/core              8.2.0-rc.0
@angular-devkit/schematics        8.2.0-rc.0
@ngtools/webpack                  8.2.0-rc.0
@schematics/angular               8.2.0-rc.0
@schematics/update                0.802.0-rc.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @IgorMinar, `BrowserPlatformLocation` and `TestabilityRegistry` are explicitly excluded from these optimisations. https://github.com/angular/angular-cli/blob/607e6f7cfd7b5f16231eae968fbf36e920c169e0/packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts#L26

This logic has been present since the introduction of Build Optimizer https://github.com/angular/devkit/commit/3097901b40dd6885cf0cc6c6bb48b5d492914a59#diff-98ef76947c50df9f53c7f56d716cb64cR5

I don't really have enough info to know why this was the case. Maybe @filipesilva since he authored the original commit. maybe he remembers the reason why that list was introduced

**Comment by filipesilva** [comment]
I don't actually remember either. The current whitelist

https://github.com/angular/angular-cli/blob/607e6f7cfd7b5f16231eae968fbf36e920c169e0/packages/angular_devkit/build_optimizer/src/transforms/scrub-file.ts#L25-L31

Is [retained](https://github.com/alxhub/ngo/blob/master/src/ngo.ts#L6-L11) from the precursor to Build Optimizer, which was [purify](https://github.com/igorminar/purify)+[ngo ](https://github.com/alxhub/ngo).

@alxhub according to git blame you were the one that added the whitelist. Do you know if it's still needed? @kara and @IgorMinar were involved in the creation of ngo and might know as well.

**Comment by IgorMinar** [comment]
unverified theory: all of these are defined as part of the platform injector which is the top most injector in an app and that injector used to have special requirements. We need to evaluate if that's still the case today.

**Comment by filipesilva** [comment]
Removing it doesn't seem to break AIO using VE or Ivy, and it doesn't change the bundle size either.

**Comment by filipesilva** [comment]
Asked @alxhub and he said
> I believe back in the day, at runtime reflect-metadata was still load bearing for types provided by the platform injector.
> I think we've done work since then to make that not the case.

So I think I'll remove the whitelist. I'll also remove the symbol based mechanism for identifying if the file is Angular Core. It only works for FESM and we've since added a flag that the caller can set that does the same. It's used on the webpack plugin, which has information about the package.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/15217 should implement the work needed on the CLI side.
