### ISSUE TITLE
output-hashing=all doesnot work for index.html

### ISSUE THREAD

**Issue by KrishnaAnanthi** [angular/angular-cli#15264]
Hi,

We are using angular-cli to build the project using below command
ng build --prod --build-optimizer --aot **--output-hashing=all** --extract-css=true --source-map=false --named-chunks=false --output-path=/home/app/build 

As per documentation all file names are appended with hashed value.  But what happens is, browser is using cached version of index.html. Its not taking latest index.html. How to handle this??   We are running angular using python server. 

Does angular cli takes care of hashing index.html also?

I tried to add below metatag also
<meta http-equiv="cache-control" content="no-cache, must-revalidate, post-check=0, pre-check=0" />

When i added this none of files are getting cached which leads to low performance. since all files are loaded from server everytime we refresh page.

**Comment by clydin** [comment]
The index should never be cached as it contains the references for the scripts and styles for the application.  It also must be named “index.html” otherwise a browser will be unable to find it.  Also please note that server configuration is outside the scope of the Angular CLI.

Here are several articles in no particular order found via a google search which explain server cache configuration for a SPA:
https://dev.to/jamesthomson/spas-have-your-cache-and-eat-it-too-iel
https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2
