### ISSUE TITLE
CI: linux build is taking too long to start

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#153]
it seems that the linux build is taking too long to start after including the OS X build

**Comment by filipesilva** [comment]
We should watch a CI build in off hours, I suspect this delay might have been due to this being a monday and early in US time.

**Comment by jkuri** [comment]
Looks like @filipesilva is right. I am testing now and watching builds and it seems that it always run parallel. Unfortunately the builds now takes much longer because of e2e first test which generates `ng new test-project` and correlated npm packages. I cannot skip installing npm packages in that case (like in unit tests) in order to run `ng test` in test-project then.

**Comment by filipesilva** [comment]
I suppose the real solution is to speed up the initial `npm install` in `ng new`, something that is already an issue.

**Comment by jkuri** [comment]
The other way would be to use cdns in testable htmls and npm linking angular-cli, then we could skip `npm install` in e2e test. Is that acceptable?

**Comment by filipesilva** [comment]
I don't quite understand your proposal. Could you explain it a bit more?

**Comment by jkuri** [comment]
I was playing with testem and noticed that mocha and other testing stuff is injected via CDNs, so I thought angular2, rxjs and system could also be injected via CDNs. If so, I believe we can do `ng new test-project --skip-npm` before running e2e tests. I don't know, maybe this is a bad idea.

**Comment by filipesilva** [comment]
Ok I understand now what you meant. I'm not sure we can do that because of the project has a build step compiling the TS into JS, and thus the dependencies would be required for it to run. 

It could be conceivable that we'd skip the build step, but that would prevent the unit and e2e tests in the generated project to run. I am not sure they are being ran now though, so maybe it's pointless to maintain that.

So that might be quite feasible after all - running `ng new` without doing the npm depedencies, and test only the code that the CLI is providing.

**Comment by filipesilva** [comment]
We now really do use the tests via `ng test` as part of the e2e testing of the cli tool. The initial problem seems to not be applicable anymore so I am closing this issue.

**Comment by cironunes** [comment]
:clap:
