### ISSUE TITLE
Get error "Module not found: Error: Can't resolve" after build when I import d.ts file

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#15411]
# 🐞 bug report
### Description
I created a component in which I use types from a d.ts file. Import to d.ts is not deleted in js file after build and I get the error "Module not found: Error: Can't resolve "

## 🔬 Minimal Reproduction
For reproduction, you can use this [project](https://github.com/ovchinnikov/ivy-missing-deps)
and the following steps:
1. npm i
2. ng build my-lib
3. ng build

After it, you get the error

## 🔥 Exception or Error
<pre><code>
ERROR in ./dist/my-lib/fesm2015/my-lib.js
Module not found: Error: Can't resolve 'devextreme/bundles/dx.all' in 'C:\Users\volkov.vladislav\Downloads\downloadnew\ivy-missing-deps-master\ivy-missing-deps-master\dist\my-lib\fesm2015'

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.2
@angular-devkit/build-angular      0.802.2
@angular-devkit/build-ng-packagr   0.802.2
@angular-devkit/build-optimizer    0.802.2
@angular-devkit/build-webpack      0.802.2
@angular-devkit/core               8.2.2
@angular-devkit/schematics         8.2.2
@angular/cli                       8.2.2
@ngtools/webpack                   8.2.2
@schematics/angular                8.2.2
@schematics/update                 0.802.2
ng-packagr                         5.5.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.38.0
</code></pre>

**Anything else relevant?**

Perhaps this is due to this [issue](https://github.com/angular/angular-cli/issues/4874). But I do not understand why this issue [was closed](https://github.com/angular/angular-cli/issues/4874#issuecomment-421092596). The problem is still reproducing.

**Comment by alan-agius4** [comment]
Hi, I just had a quick look and there is `devextreme/bundles/dx.all` JS bundle, there is only type definition for it, and hence the failure is correct.
![image](https://user-images.githubusercontent.com/17563226/63570803-9ea9f380-c57e-11e9-8be2-54ecaaaf01d7.png)

DevExtreme also seems to offer an Angular package https://js.devexpress.com/Documentation/Guide/Angular_Components/Getting_Started/Add_DevExtreme_to_an_Angular_CLI_Application/#Import_DevExtreme_Modules

More more thing which is unrelated to the issue is that import to your library in `app.component` https://github.com/ovchinnikov/ivy-missing-deps/blob/ae27b1ae00b02a957cbe7b47b0e0a42fa42443dc/src/app/app.module.ts#L5 is incorrect as it should point to the library module using it's name and not the relative path to dist.

From
```ts
import { MyLibModule } from '../../dist/my-lib';
```

To
```ts
import { MyLibModule } from 'my-lib';
```

That said, this seems to be a support request and not a bug in Angular CLI. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dxvladislavvolkov** [comment]
Why is the failure correct? I want to use types from d.ts in my lib. It can be another d.ts, not only dx.all. After build, I have unnecessary import in a js file and I get the error

**Comment by dxvladislavvolkov** [comment]
Perhaps this is due to this [issue](https://github.com/angular/angular-cli/issues/4874). But I do not understand why this issue [was closed](https://github.com/angular/angular-cli/issues/4874#issuecomment-421092596). The problem is still reproducing.

**Comment by alan-agius4** [comment]
You are right, for types only it should matter the import.
This issue is however being tracked here: https://github.com/angular/angular/issues/21280
