### ISSUE TITLE
deploy-url is not working with font urls 

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular-cli#15520]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7

### Description

 A clear and concise description of the problem...

Using `deploy-url` has no effect on font resources.

Take the following example:

```sccc
@mixin flags-font($theme) {
  @font-face {
    font-family: "BabelStone Flags";
    src: local("BabelStone Flags"),
        local("BabelStoneFlags"),
        url('/assets/fonts/BabelStoneFlags.ttf') format('truetype'),
        url('/assets/fonts/BabelStoneFlags.woff') format('woff'),
        url('/assets/fonts/BabelStoneFlags.woff2') format('woff2');
  }

  .flag {
    font-family: "BabelStone Flags" !important;
  }
}
```

If i'm running the build with `--deploy-url=my-url/`:

`/assets/fonts/BabelStoneFlags.ttf` I would expect that the CSS output will reference the 
path `my-url/assets/fonts/BabelStoneFlags.ttf`.

This was the case in version 7.

From version 8 it's not working, the URL is not prefixed with the deploy url.

## 🌍 Your Environment
<pre><code>

 shlomiassaf   …/sg/sg  ng version                                                                                                                                                   Development    

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.2
Node: 11.15.0
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.803.2
@angular-devkit/build-ng-packagr   0.801.3
@angular-devkit/build-optimizer    0.803.2
@angular-devkit/build-webpack      0.803.2
@angular-devkit/core               8.3.2
@angular-devkit/schematics         8.1.1
@angular/cdk                       8.1.3
@angular/cdk-experimental          8.1.3
@angular/cli                       8.3.2
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.1.3
@ngtools/webpack                   8.3.2
@schematics/angular                8.1.1
@schematics/update                 0.803.2
ng-packagr                         5.5.0
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by clydin** [comment]
This is intentional.  Root-relative URLs are a class of absolute URLs and should not be modified.  The purpose of a root-relative URL is to reference a file from the root of a host; modifying it would prevent that from occurring.  This behavior is common to CRA, Vue.js, and standalone Webpack configurations (css-loader).

**Comment by shlomiassaf** [comment]
@clydin 

So how would you reference the root URL while still maintaining deploy url behaviour?

The process is very complicated...

The URL is used for **build time file reference** and for **runtime url address reference**.

Because we're dealing with SCSS it might get imported from different places in which relative URLs are now useless...

**Comment by shlomiassaf** [comment]
I would also like to reference this issue to #6599 which looks solved but it's not.. .lots of comments from recently

**Comment by clydin** [comment]
Absolute URLs are left as-is (this includes root-relative URLs) and relative URLs are treated as module references.  This is the behavior of webpack itself.

For information regarding Sass' lack of import rebasing, please see: https://github.com/sass/sass/issues/2535

**Comment by shlomiassaf** [comment]
Bottom line, one can't relay on this process when used with mixins and other complex SCSS utilities.

Within the mixin, the relative root will be the one of the mixin caller, or worse the mixin's mixin, mixin, mixin caller... if complex one.

**Comment by clydin** [comment]
That is an existing problem with Sass itself that transcends the Angular CLI and can affect any Sass based setup; SPA or otherwise.  Breaking the standardized behavior and legitimate uses of absolute URLs has been considered a nonviable solution to overcoming deficiencies in a stylesheet preprocessor.

This is also one of the reason packages such as font-awesome use a variable to allow customization of the font file locations since importing the Sass files would break the URLs for the font files.

The team is considering additional methods to allow special variables within a stylesheet `url()` to allow referencing either the configured deploy URL or base HREF.  In the meantime, this compatibility option is currently available: `rebaseRootRelativeCssUrls`.
