### ISSUE TITLE
Can't find module when build (prod only)

### ISSUE THREAD

**Issue by rochapablo** [angular/angular-cli#15645]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know, I haven't tried old ones.

### Description

Running `ng build --prod` when include my module I get the following error:

```
ERROR in ./node_modules/my-dream-app/dist/pablo-pagination/pablo-pagination.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/node_modules/my-dream-app/dist/pablo-pagination'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/src/app'
ERROR in ./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/src/app'
```

## 🔬 Minimal Reproduction

```
$ ng new my-dream-app
$ ng generate library pablo-pagination

// to include the library as external module
$ ng new my-dream-app2

// need to do this so don't get error in browser
// my-dream-app2/tsconfig.json
"paths": {
      "@angular/*": [
        "node_modules/@angular/*"
      ],
    }

// and call the module as package
"my-dream-app": "file:../my-dream-app",

npm install

// import the package inside app.module
imports: [
    PabloPaginationModule
  ],

// this will be ok
npm start

// this will crash
// ng build --prod
```

[Here you can have the two projects](https://github.com/rochapablo/angular-module-error)

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/my-dream-app/dist/pablo-pagination/pablo-pagination.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/node_modules/my-dream-app/dist/pablo-pagination'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/src/app'
ERROR in ./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve 'pablo-pagination' in '/angular-module/my-dream-app2/src/app'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.5
Node: 10.15.0
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

https://stackoverflow.com/questions/58032141/angular-cant-find-module-when-build-prod-only

**Comment by alan-agius4** [comment]
Hi @rochapablo, 

There are a couple of issues with your setup. 

1) You need to import using the library module name and not the path with deep imports in https://github.com/rochapablo/angular-module-error/blob/3968695bd226740a43a9f269bf264140ea0449f9/my-dream-app2/src/app/app.module.ts#L7

instead of 
```ts
import { PabloPaginationModule } from 'my-dream-app/dist/pablo-pagination';
```

it should be 
```ts
import { PabloPaginationModule } from 'pablo-pagination';
```

2) You need to install the library in your secondary application and not the other workspace https://github.com/rochapablo/angular-module-error/blob/3968695bd226740a43a9f269bf264140ea0449f9/my-dream-app2/package.json#L22

```js
 "my-dream-app": "file:../my-dream-app",
```

should be changed to 
```js
 "pablo-pagination": "file:../my-dream-app/dist/pablo-pagination",
```

**Comment by rochapablo** [comment]
Hello!

Oh I see, you're right! But...

When I try to build from the repository, like:

```
"pablo-pagination": "git+https://.../pablo-pagination.git/dist/pablo-pagination",
// or
"pablo-pagination": "git+https://.../pablo-pagination.git",
```

I get the following error:

```
ERROR in src/app/app.imports.ts:31:48 - error TS2307: Cannot find module 'pablo-pagination'.
31 import { PremiumadsCorePaginationModule } from 'pablo-pagination';
```

I also tried to add the following path in the tsconfig.json, but it didn't work

```
"pablo-pagination/*": [
  "node_modules/pablo-pagination/dist/pablo-pagination/*"
],
```

Any idea of how to workaround this?

**Comment by rochapablo** [comment]
Look what I'm doing ```"postinstall": "cp -r ./dist/ng-premiumads-core/* ./"```, pretty ugly, but it's seems to be working.

**Comment by alan-agius4** [comment]
Building directly from a git repository is highly discouraged since libraries and applications don’t share the same build pipeline and you might end up with incorrect behaviour.

You most likely missed the below in your paths
```
"pablo-pagination”: [
  "node_modules/pablo-pagination/dist/pablo-pagination”
],
```

I am however going to close this issue as this doesn’t seem to be a bug but rather a support request. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
