### ISSUE TITLE
Feature request: ng serve should select another port if 4200 is already taken

### ISSUE THREAD

**Issue by amreladawy** [angular/angular-cli#1568]
> ## Feature request
- OS?  
  Windows 7
- Versions. 

```
angular-cli: 1.0.0-beta.11-webpack
node: 4.4.7
os: win32 x64
```
- Repro steps. 

a.   start an angular project with `ng serve`
b. start another angular project with `ng serve` 

The second one won't start as port 4200 is already taken 
`Port 4200 is already in use.`

Ionic cli is switching to another port automatically 
`The port 8100 was taken on the host localhost - using port 8101 instead`

**Comment by mwawrusch** [comment]
Random ports are a bad idea, especially if you use callbacks to login (like facebook). Just provide an easy option in the config (not the ember config) to specify the port.

**Comment by amreladawy** [comment]
I don't think random ports are a good idea as well. I wanted angular-cli to do like ionic-cli. increment the port number until the first available port is found and printed.

**Comment by bhelzer** [comment]
I'd rather have cli configured with my port, otherwise the port of my app would depend on in which order I start my two projects.

**Comment by amreladawy** [comment]
@bhelzer You already have the option to specify the port at your wish

`ng serve --host 0.0.0.0 --port 4201 --live-reload-port 49153`

We are proposing the facility of automatically switch to another port if the port is already taken.

**Comment by filipesilva** [comment]
There is currently a way to get an free port, by using `--port=0`:

```
$ ng serve --port=0
** NG Live Development Server is running on http://localhost:49152. **
# and on another console
$ ng serve --port=0
** NG Live Development Server is running on http://localhost:49153. **
```

**Comment by manoj30dec** [comment]
Thanks @amreladawy ng serve --host 0.0.0.0 --port 4201 --live-reload-port 49153
works for me.

**Comment by pain0486** [comment]
@filipesilva 
Could there be a way to opt into killing the task that is running automatically instead of getting the error? More and more I run into the issue that I closed the window running the app (VSCODE/Powershell/CommandPrompt) or it was closed for me. Then when I go to open it again and run npm start I get Port 4200 is already in use error. 

I used to go into task manager and try to find the correct nodejs.exe and end the process. Now I run this
netstat -ano | findstr :4200 | ConvertFrom-String | ForEach-Object {taskkill /PID $_.P6 /F}
But it would  be nice that if something is already running on that port to just kill it and then run as normal. 

Normally I would just switch to another port but we are using json webtokens and Identity Server for login so the local url has to match exactly.

**Comment by harmeshg5** [comment]
You can also try with this to run your application in visual studio code -:

`ng serve --open --port 4201`

you can give any port number.

**Comment by Ram569** [comment]
@filipesilva thanks for your suggestion (--port 0) server is starting on the opened port, but we are facing issue with e2e target with --port 0 application is running on opened port but base url is http://localhost:0.

**Comment by PawanAtCentennial** [comment]
@filipesilva I am new to angular and was facing the following problem:
I do ng serve in cmd prompt and then the angular application starts in browser at localhost 4200.
Now if i close the cmd prompt ,(i would hope that application should close) even then the application keep on running at localhost 4200.   If I have to run another angular application
 In order to run that other project ,what i would have to do is kill the process running on port 4200 by windows commands    which becomes pain when we are developing in angular and have to do that several times(considering one closed the cmd window after doing ng serve).

is there any solution to that apart from ng serve --port?

**Comment by pain0486** [comment]
Try Ctrl + C in the command prompt

**Comment by PawanAtCentennial** [comment]
pain0486 i mean if you close the command promt by mistake

**Comment by pain0486** [comment]
Ahhh, nope then you just stuck or use the --port=0 like mentioned above

**Comment by PawanAtCentennial** [comment]
@pain0486  oh ok  ........   I thought it would be similar to node .... like i we close the window then the server automatically stops  .................  ok  thanks   btw and what would you reccommend for getting expert in angular2+

**Comment by pain0486** [comment]
Read the [docs](https://angular.io/guide/quickstart) also if you have access to something like pluralsight would be good. but mainly just start a project and everytime you have a question or design question look at the docs and stackoverflow. That is where I did 95% of my learning. Pluralsight is easy to consume but I didnt have the time to really watch the videos.
