### ISSUE TITLE
Why default by using systemjs instead of webpack ?

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular-cli#1572]
i install angular-cli@systemjs and angular-cli@webpack

then

i run:

ng new PROJECT_NAME
cd PROJECT_NAME
ng build --prod

systemjs:
![systemjs](https://ooo.0o0.ooo/2016/08/05/57a56ecd8ae1e.jpg)

----------------------------------------------

webpack:
![webpack](https://ooo.0o0.ooo/2016/08/05/57a56ecd906ef.jpg)

Is there any meaning for systemjs ? 
Why not delete the systemjs version?

:)

**Comment by FraserKillip** [comment]
From what it seems, the web pack version will be the preferred version but has only just been merged to master in the last week or so. My guess is that they want to do a bit more work on it before committing it as there default.

**Comment by TheLarkInn** [comment]
The webpack version we didn't want to set as the `@latest` npm tag so that users who had existing projects wouldn't automatically see their apps error by doing an `npm update` or `npm install`. Eventually we will have the `webpack` build on master become latest after our Migration guide and other things fall in place.

**Comment by filipesilva** [comment]
We're still trying to get all the kinds out, and webpack will turn to the default at that time.

**Comment by samuel-kollat** [comment]
Will there be still @systemjs support after webpack becomes @latest ? Or will you be developing only @webpack version ?

**Comment by filipesilva** [comment]
@samuel-kollat only on webpack.
