### ISSUE TITLE
Add modules folder 

### ISSUE THREAD

**Issue by htmike** [angular/angular-cli#15778]
# 🚀 Feature request
To include folder for modules in the project initial structure at ng new assistant, for lazy loading.

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When I create a new project, I generate a principal module (home, explore, etc...) with a routing module, components, pipes, etc...

### Describe the solution you'd like
In the initial project, to include "/src/app/modules/name.module.ts". Routing optional, name optional if the the project require routing module

### Describe alternatives you've considered
This recommendation only apply for SPA.

**Comment by Splaktar** [comment]
You can find more information on the recommended structure of your app in the Angular Style Guide:
- https://angular.io/guide/styleguide#angular-ngmodule-names
- https://angular.io/guide/styleguide#application-structure-and-ngmodules
- https://angular.io/guide/styleguide#app-root-module
- https://angular.io/guide/styleguide#feature-modules

This request doesn't appear to align with that style guide. You are, of course, free to extend the existing schematics so that you can format and generate your project in the way that you or your company desires.

**Comment by alan-agius4** [comment]
As @Splaktar mentioned the folder structure you are suggested is not per Angular style guide.

Hence, I am closing this issue as the CLI file structure adheres to the Angular style guide.
