### ISSUE TITLE
Add param in config to exclude files to help to solve the "heap out of memory" issue

### ISSUE THREAD

**Issue by JoeyLi-1** [angular/angular-cli#15862]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] build

```

### Description
Hi There,

I had suffered a lot from the "heap out of memory" issue recently. That is caused by the source map for my case. (Angular 7 + Node 8 + window10)

I found this function in webpack config utility: (node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\utils.js)

```typescript
function getSourceMapDevTool() {
    // ...
    
    return new webpack_1.SourceMapDevToolPlugin({
        filename: inlineSourceMap ? undefined : '[file].map',
        include,
        exclude: ['vendor.js'],    //<----  Here, I excluded vendor.js and the issue gone. Build speed is much faster and it almost did not affect daily debugging!**
        append: hiddenSourceMap ? false : undefined,
    });
```

I noticed that there is a configuration in "angular.json" ["sourceMap"](https://angular.io/guide/workspace-config#optimization-and-source-map-configuration) under architect->build->option;
Could you guys please add an "exclude" param in that object? So that specified file could be excluded by us individually. If you can add that function, that might help a lot of people. Thank you! 

Thanks,
Joey

**Comment by flash-me** [comment]
Did you already try increasing allowed heap size for your node process?

You can create an environment variable for this:
name: NODE_OPTIONS
value: --max_old_space_size=4096

**Comment by JoeyLi-1** [comment]
@flash-me Yep. Some guys in our team use "cross-env NODE_OPTIONS=--max_old_space_size=4096" in package.json to fix this issue.

**Comment by flash-me** [comment]
Since nodejs v8 you can also set a user / system variable.
Enter in an elevated command prompt
`setx NODE_OPTIONS --max_old_space_size=4096`
Add **\m** for setting it as a system variable.

**Comment by JoeyLi-1** [comment]
@flash-me That is quite helpful. Thank you!

**Comment by chvarunkumar1994** [comment]
Isn't this only a temporary solution? What are we looking at in the long term?

**Comment by flash-me** [comment]
It's not like as if one could say "Let's turn this feature off" or "Let's optimize this particular part" to solve this. Every part of the toolchain affects the memory usage. From typescript itself to terser.

If the only requirement is low heap size, then go ahead and process everything sequentially. The drawback are gigantic build times.

Even the used OS has an impact on this. On *nix machines you will build faster then on Windows with same hardware. Thats because Microsoft has a different interpretation of a *process* than *nix.

To put it straight: There are ongoing efforts to reduce this, but you will have higher memory usage in general when developing with angular compared with default node.js.

**Comment by dgp1130** [comment]
I believe we've made a few improvements to memory usage in the last few versions. Node has also made a lot of headway in this area (in particular version 10 or 12 I believe?). Is this still an issue for you on the latest CLI and a more up-to-date version of Node?

We'd rather solve the underlying memory-usage issue out-of-the-box than introduce a new option for users to tweak.

**Comment by alan-agius4** [comment]
Closing a there was no further communication. If the problem persists feel free to open a new issue.
