### ISSUE TITLE
ng serve does not respect ng build --env

### ISSUE THREAD

**Issue by DavidRSchaller** [angular/angular-cli#1598]
To simply the details below:
Is it expected behavior where ng serve rebuilds the app and overwrites the prior ng build?

I am seeing an issue where a custom environment configuration file is initially generated as expected but then reverts when the app is served.

Here are the relevant details:

OS: Windows 10: 
ng --version: angular-cli: 1.0.0-beta.10, node: 4.4.7, os: win32 x64
App generated via CLI

A new environment file was created to establish a 'local' development environment.

environment.local.ts
`export const environment = {
  production: false,
  local :true
};
 `
Command executed for build:
`ng build --env=local`
The dist/app/environment.js file is properly built with the configuration set as expected.

Command executed for serve:
'ng serve'
It appears as if ng serve is actually rebuilding the app. Adding '--env=local' appears to respect the settings.

Prior to requesting the application via a browser, the dist/app/environment.js file is okay.
After connecting to the application via the browser, the environment.js reverts to the environment.dev.ts settings.

environment.dev.ts file:

`export const environment = {
  production: false,
  local :false
};`

Thanks in advance.

**Comment by dlizarra** [comment]
Yes this is the expected behaviour:
- `ng build`: Builds your app.
- `ng serve`: Builds your app and also starts a live reload server.

This means that when you were running `ng build --env=local` your bundle was built correctly but when after that you run `ng serve` the bundle was built again but this time with the default environment which is 'dev'.

So you just need to run `ng serve --env=local`.

**Comment by dlizarra** [comment]
@DavidRSchaller You can close the issue yourself if you think its solved. Thanks!!
