### ISSUE TITLE
CLI Migrations that make commits should do so as the CLI

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#16061]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] update
```

### Description
Similar to ng-new, the CLI should commit with itself as the author instead of the user, making it easier to differentiate user commits from automatic commits.

CC @vikerman

**Comment by alan-agius4** [comment]
@StephenFluin, the CLI will use which every git config you have.  If you have the a global git config with your use, When using `ng new` it will create the `initial commit` with your username.

I think the feature that you are talking about was in Angular CLI 1.6, where the author of the initial commit was `Angular CLI`.

I am not sure of all the reasons why this was changed. 

//cc @clydin & @filipesilva maybe they remember.

**Comment by filipesilva** [comment]
Can't say I remember either.

**Comment by clydin** [comment]
It was user requested.  I believe the argument was that the CLI user didn't actually exist so it could cause validation failures and also that the commit ultimately was created by the developer as the developer executed the ng command.

**Comment by IgorMinar** [comment]
now that the commits are authored only if the the user opts-in via `--createCommits` flag, I think it's not that surprising that the commits are authored by the current user.

in the past we used to author the initial git commit using a custom CLI author, and we rolled that back in CLI version ~1.4 because it was causing problems for teams that required all commits to be created by existing/real users.

@StephenFluin do you agree that the rationale for not using the current user to create the commits is no longer valid?

**Comment by StephenFluin** [comment]
SGTM
