### ISSUE TITLE
Generating Lite Build from Existing Code

### ISSUE THREAD

**Issue by shabbir-dhangot** [angular/angular-cli#16096]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ x ] build
- [ x ] serve
```

### Description
 As application builds day by day it become very heavy to load. Heavy in the sense it require good connection to load vendor.js, main.js which are huge in size. 

We can not deny that there are still low internet connection are available on the globe. When user having less speed he prefers to see lighter version of application. What I want to show user is there is lighter version of application is available(On different domain).

Is there any way we can create build from current code base with limited feature? If its not we should have this feature.

### Describe the solution you'd like
 Option for lite build.

### Describe alternatives you've considered
 Currently I am using file replace option in angula.json to replace it with lighter version of HTML TS. But its very difficult and also I didn't get success on that.

**Comment by EmmanuelDemey** [comment]
Do you use lazy loaded modules . I think it is a good first solution for minimizing the build size.

**Comment by shabbir-dhangot** [comment]
Yes @EmmanuelDemey I am already using lazy loaded component. I want to do further cut down by feature reduce on lite build.

**Comment by clydin** [comment]
A production build should not have a `vendor.js` file.  Are you building using the production configuration? (e.g., `ng build --prod`).

The file sizes for a new application using 9.0.0-rc.1 are as follows:
```
141032 Nov  6 20:08 main-es2015.ed01ec5f480fa886325f.js
163321 Nov  6 20:08 main-es5.ed01ec5f480fa886325f.js
 36808 Nov  6 20:08 polyfills-es2015.b6fe2b19564e29c5d554.js
127927 Nov  6 20:08 polyfills-es5.9cbeb6b4a192c8c548fe.js
  1485 Nov  6 20:08 runtime-es2015.52756d3ab8e6582f0541.js
  1485 Nov  6 20:08 runtime-es5.52756d3ab8e6582f0541.js
```

**Comment by shabbir-dhangot** [comment]
@clydin : I have set `"vendorChunk": true` in configuration that is why its generation separate vendor chunk while build. Default is false so its not generating for you.

**Comment by clydin** [comment]
That should not be used outside of development scenarios.  Its purpose is to improve rebuild performance during “ng serve”.  For builds, it causes a massive deoptimization of the final output and will result in significantly larger file sizes.

**Comment by filipesilva** [comment]
We already do our best with the defaults to have the smallest possible build. Whenever we find new ways of making user bundles smaller, we just do it automatically as bundle size is one of our biggest focus areas.

I'd like to reiterate that you really shouldn't have a vendor bundle in production for the reasons @clydin mentioned. Having a separate vendor chunk will always ensure it will be very large.

Additionally reducing the main bundle can be done by using lazy loaded components as much as possible. For the fastest initial load, you should structure your app such that the main bundle is as small as possible.

**Comment by shabbir-dhangot** [comment]
@filipesilva : I am already using lazy loaded component.

I am not getting why issue with different vendor. Because with vendor true my main.bundle size 900kb without vendor it increased to 2.6 MB.
My vendor.js file is 1.7 mb that I think appending in main.bundle.js file. Am I doing anything wrong?

My production build setup

    "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
              "serviceWorker": true,
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }]
            }

**Comment by shabbir-dhangot** [comment]
@filipesilva @clydin can you help me on this? I am curious to know.

**Comment by filipesilva** [comment]
No, you're not doing anything wrong I think. When disabling the vendor chunk it will be included in the main chunk. This allows for better optimizations when possible. In your case, maybe optimizations are not possible.

Having a bundle that large is probably due to many third party libraries. Some can be very large. You can see where the size comes from by doing a production build with sourcemaps (`ng build --prod --source-map`) and then using https://www.npmjs.com/package/source-map-explorer to see the size of each library in your bundle.

Using lazy routes helps, but if you want to reduce the size of your main bundle then you need to move as much code and third party imports the the lazy routes. If you have lazy routes but still a lot of code in the non-lazy routes, you will still have a large main bundle.

You can also get some more advice and help on how to reduce your application size by asking on Stack Overflow. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
