### ISSUE TITLE
Hook to prevent auto-update of CLI during `ng update`

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#16122]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

When running `ng update`, it automatically updates to the most recently released version. When doing local development, this is undesirable because devs want to use their locally built version.

### Describe the solution you'd like

Either a `--skip-self-update` flag or an environment variable to avoid this behavior.

### Describe alternatives you've considered

Only workaround is to manually change [this line](https://github.com/angular/angular-cli/blob/e1319e68e3fee7f1b73e7f02e60f2b99a37e0616/packages/angular/cli/commands/update-impl.ts#L203) to an `if (false) { /* ... */ }` before a local build.

**Comment by alan-agius4** [comment]
You can use the following env variable `NG_DISABLE_VERSION_CHECK`. Just be sure that you ran your local `ng` with either npx or yarn.

Example `yarn ng update ....`

**Comment by alan-agius4** [comment]
Oh nevermind, there is no check for that in that method.

**Comment by dgp1130** [comment]
Oh interesting, what does `NG_DISABLE_VERSION_CHECK` do if not preventing self-updating? Would it make sense to use the same environment variable to do so?

**Comment by alan-agius4** [comment]
When that env variable is set to true or 1. The CLI will bypass parts of the bootstrapping logic and will force the usage of the currently invoked process. Typically the CLI will always use the local version. But in some cases such as `ng update` self update we want to use the currently spawned process. 

https://github.com/angular/angular-cli/blob/862b28f844cddcc406defac6a32d6e266221d499/packages/angular/cli/lib/init.ts#L79

I think we can use this env variable for this use case too. As also, if we use this, we will be reducing an HTTP call. Since the cli will set this variable when using the self update version, but currently we don’t check it during `ng update` and thus when running in self update mode the spawned process will try to redundantly fetch the latest manifest of the cli again.
