### ISSUE TITLE
fonts of third party css in dist/ root

### ISSUE THREAD

**Issue by jcimoch** [angular/angular-cli#16239]
I'm reopening the issue because amazing bot closed another unresolved one...
https://github.com/angular/angular-cli/issues/3143

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

If the issue is that assets are moved to the root of the `dist` folder. Most likely, you are on Angular CLI pre 7 or you are not providing a `resourcesOutputPath` as an option.

Kindly see: https://v7.angular.io/cli/build

Thank you.
