### ISSUE TITLE
Remove legacy guessing logic from app-shell

### ISSUE THREAD

**Issue by wagnermaciel** [angular/angular-cli#16353]
Currently `_getServerModuleBundlePath` of `app-shell/index.ts` uses a regular expression to try to find the main bundle file.

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/app-shell/index.ts#L111

This is unnecessary since the main bundle will always be named main.js

@alan-agius4 I noticed this issue as a result of your comment that revealed this guessing logic is no longer needed

https://github.com/angular/universal/pull/1357#discussion_r353970284

**Comment by alan-agius4** [comment]
Just to be clear the appModuleBundle is redundant since the file name is always `main`. 

That said the regexp part is still needed for the time being since we do offer a way to hash the server bundle which will result in a file similar to the following `main.7d6a18ddde7a92ee9f58.js`. I personally don't see any reason why one would do this and never saw anyone using this feature.

I personally think that in the server builder `outputHashing` should be limited to `media`.
