### ISSUE TITLE
Angular complains about missing `index.ts` when it is there #16386

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16388]
This is in reference to:
https://github.com/angular/angular-cli/issues/16386

The error message:
> ERROR in ./node_modules/@fireflysemantics/slice/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/ole/Temp/sph/node_modules/@fireflysemantics/slice/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/ole/Temp/sph/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:900:23)
    at /home/ole/Temp/sph/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

Says to include `index.ts` in:
> Please make sure it is in your tsconfig via the 'files' or 'include' property.

This is confusing because IIUC it should not be included in the package at all.  After I removed it from the package, the application started compiling fine.  So  I assume that it just means that packages should not include `index.ts` in the root folder at all?

**Comment by filipesilva** [comment]
Heya, that error means that you're trying to use TypeScript sources that aren't included in the TypeScript compilation. You must include all sources you use in the TS compilation using the `files` or `include` properties in `tsconfig.json`, otherwise TS can't load them.

Files are usually included automatically through relative and dynamic imports, but they aren't included automatically when the import is to a third party library. I'm guessing you didn't actually want to include the TS sources in the package, but since I don't know how you are packaging it, it's really hard to tell what's going wrong. 

If it's an Angular library and you want to follow https://goo.gl/jB3GVv, then you can follow https://angular.io/guide/creating-libraries or use `ng-packagr` directly to ensure it's packaged correctly. If it's not an Angular library, I suggest you don't include TS sources in the packaged version at all.
