### ISSUE TITLE
Add option extractCss for builder @angular-devkit/build-angular:server

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#16411]
# 🚀 Feature request

`--extractCss` is supported for browser builds but when we specify extractCss in configurations of
`@angular-devkit/build-angular:server` it throws below error:

`Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(extractCss).`

Sometimes we want server to return just clean html without any styles embedded in html document, especially when we are already sending css file using HTTP/2 Server Push from the server along with the response. In this case the styles embedded in the html are redundant and increase page size (in my case ~24kb of css is added in html response).

### Command (mark with an `x`)

```
- [x ] build
```

### Describe the solution you'd like
`--extractCss` should work with `@angular-devkit/build-angular:server`

**Comment by alan-agius4** [comment]
Hi, thanks for opening this feature request. Note: `extractCss` doesn't effect components styles. So the feature you are requesting is a bit different.

**Comment by naveedahmed1** [comment]
Yes you're right, thanks for the clarification. Is it something that could be supported easily?

**Comment by alan-agius4** [comment]
> Especially when we are already sending css file using HTTP/2 Server Push from the server along with the response. In this case the styles embedded in the html are redundant and increase page size (in my case ~24kb of css is added in html response).

This is not correct, they are far from redundant. The styles in the `.css` file are the global styles while the once embedded in the HTML are the once in the component. 

Currently, it is not possible to disable CSS from being embedded in the HTML. So instead of having them embedded, your request is to have an addition `.css` file, that contains the component styles for that page.

This should be possible to be done by a server middleware though it will not be trivial. For now, let's close this issue and reconsider it if there is a bigger demand for this feature by the community as currently fall in scope of the Angular CLI/Universal project.
