### ISSUE TITLE
Outdir in tsconfig is ignored when using nx.dev

### ISSUE THREAD

**Issue by rienheuver** [angular/angular-cli#16482]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I'm building a monorepo using nrwl (nx.dev) and am using an outDir in my tsconfig.json, this seems however to be ignored. Someone reported a similar problem in #2267 where it occurred when multiple apps were declared in angular.json, which is the case for me since it's a monorepo.

## 🔬 Minimal Reproduction
Create a monorepo using Nrwl, make a tsconfig.json in, for example. your Node-app in the monorepo and specify an outDir-option so that the output should be separate files instead of one compiled js-file.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.20
Node: 12.13.1
OS: linux x64
Angular: 8.2.14
</code></pre>

**Comment by alan-agius4** [comment]
The `outDir` is indeed not used and is by design. To specify the output path of an application you should set it in the builder options in `angular.json`. Example: for `@angular-devkit/build-angular:browser` you can use the `outputPath` option.

That said the Angular CLI doesn’t have a builder that supports building Node applications.

This seem to be more of a Nrwl feature request to support unbundled applications.
