### ISSUE TITLE
deployUrl per i18n locale

### ISSUE THREAD

**Issue by mstawick** [angular/angular-cli#16558]
# 🚀 Feature request
Just as we can now configure `baseHref` per locale, can we also please get an option to configure `deployUrl` per locale?

**Comment by clydin** [comment]
Unlike the base HREF, the deploy URL is deeply embedded throughout the application code.  Changing the base HREF involves updating a single value in the index HTML.  However, changing the deploy URL requires fully rebuilding the entire application.  If the deploy URL is absolutely required for a project then individual builds per locale are necessary.
Where possible it is recommended to use the base HREF instead of the deploy URL option.  For an overview of the differences between the two, please see: https://github.com/angular/angular-cli/blob/master/docs/design/deployurl-basehref.md

**Comment by mstawick** [comment]
Thank you for the explanation, much appreciated.
