### ISSUE TITLE
Add documentation for --browser-target

### ISSUE THREAD

**Issue by NatoBoram** [angular/angular-cli#16572]
# 📚 Docs or angular.io bug report

### Description

There's no documentation for `ng serve --browser-target`.

### What's the affected URL?

* https://github.com/angular/angular-cli/wiki/serve
* https://angular.io/cli/serve

## 📷Screenshot

![Screen Shot 2020-01-07 at 09 47 16](https://user-images.githubusercontent.com/10495562/71903735-bac7bf00-3132-11ea-994a-3b0f745bdf3f.png)

**Comment by filipesilva** [comment]
Would you like to add more details to this doc?

**Comment by NatoBoram** [comment]
I'd love to, but I have no idea what it does nor how to use it. That's why I was referring to the docs.

**Comment by filipesilva** [comment]
The `browserTarget` property says what build target is going to be served. The serve command doesn't completely know how to build it, it just knows how to serve it.

Usually there's only one build, but since a target can have multiple configurations, you can specify that you want to serve that particular configuration of the build. There's some more information about it in [this AIO page](https://next.angular.io/guide/workspace-config#build-target).

In practical terms what this means is that `ng serve` will serve the development build and `ng serve --prod` will serve the production build. 

The way this is specified is through `browserTarget`. In a default `angular.json` you'll have this:
```
{
  "projects": {
    "next-app": {
      ...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": { ... }
          "configurations": {
            "production": { ... }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "next-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "next-app:build:production"
            }
          }
        },
```

Where `"browserTarget": "next-app:build"` means "I want to serve projects->next-app with the default options" and `"browserTarget": "next-app:build:production"` means "I want to serve projects->next-app with the default options merged with the production config".

Does this description help?

**Comment by domthewop** [comment]
@NatoBoram I have some spare cycles if you'd like to hand this off. Alternatively, I'd be happy to collaborate instead if you'd still like to be involved. I wrote some of the Python docs, and would be happy to mentor. And, of course, happy to let you do your thing -- but please update us either way.

**Comment by NatoBoram** [comment]
@domthewop You're free to work on it :)

**Comment by rrohak** [comment]
Is this still up for grabs?

**Comment by domthewop** [comment]
Go for it, @rrohak -- I left Google in the interim and didn't update the ticket, sorry!

**Comment by rrohak** [comment]
> Would you like to add more details to this doc? That string is extracted from json files in this repo, and should be the 3 results for "Target to serve" if you search across the code.

Here you said there are 3 results but IntelliJ only shows 2, are we including serve.md under docs/documentation or am I missing another file?
<img width="600" alt="image" src="https://user-images.githubusercontent.com/43389183/85097305-1fe50d80-b1c5-11ea-96d9-6da15f5671d4.png">
