### ISSUE TITLE
Code Coverage Report issue

### ISSUE THREAD

**Issue by Jamee77** [angular/angular-cli#16633]
I get the below issue while trying to run the command 
ng test (applicaitonname) --watch=false --code-coverage

Issue:
See http://localhost/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:

Please suggest what to do.

**Comment by ewolfe** [comment]
I just got the same error after updating a handful of dependencies (istanbul, istanbul-instrumenter-loader, and karma-coverage)

**Comment by Jamee77** [comment]
> I just got the same error after updating a handful of dependencies (istanbul, istanbul-instrumenter-loader, and karma-coverage)

Were you able to fix it?

**Comment by ewolfe** [comment]
Well... kind of? I'm going down a rabbit hole of updating all my dependencies:

![image](https://user-images.githubusercontent.com/32533397/72233508-9cbbed80-357c-11ea-9381-623f1249fc20.png)

I think one of my initial root causes was a mismatch of dependencies. But I couldn't tell you exactly what the culprit was. So I just started slowly hacking away it in as small as chunks as I could do.

(PS, don't read too much into the failed builds in my screenshot. It's unrelated to the code coverage report issue).

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jordivila** [comment]
I'm facing the same issue. It might be related to https://github.com/wycats/handlebars.js/issues/1636
