### ISSUE TITLE
Building process is replacing index.php file

### ISSUE THREAD

**Issue by Mangytai** [angular/angular-cli#1666]
> Issue info:
> ---------------------------------------------------------------

1. El Capitan

2. angular-cli: 1.0.0-beta.10, node: 5.3.0, os: darwin x64

3. nothing, just new application created by cli

The problem is in building process.  I am trying to build with `--output-path` flag. In result, cli replaces my **index.php** file in output folder by **index.html** existing in **src** folder.
I tried to delete index.html. Result: my index.php in output folder is also deleted.

In ideal, I want to hold index.php in output file and add to git and delete from my src folder index.html. Is there any way to make this happen?

I want to link angular 2 with Laravel framework.

Thank you

> ---------------------------------------------------------------

**Comment by hansl** [comment]
The output folder will always be entirely replaced. You can use the `public/` folder to have your `index.php` which will be copied to your output folder, or output the app to a separate folder and copy the files yourself.

This is by design and will not change. This is a build output folder, not a deploy folder. You should separate those two steps.
