### ISSUE TITLE
Impossible typescript Peer Dependencies

### ISSUE THREAD

**Issue by robodair** [angular/angular-cli#1681]
1. OS? 
   Mac OSX El Capitan 10.11.6
2. Versions. 
   angular-cli: 1.0.0-beta.11-webpack.2
   node: 6.3.1
   os: darwin x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Fresh installation of angular-cli@webpack
4. The log given by the failure. Normally this include a stack trace and some
   more information.
   <img width="652" alt="screen shot 2016-08-14 at 01 43 54" src="https://cloud.githubusercontent.com/assets/8318231/17644195/b4a6b21c-61c3-11e6-9016-f8278d2f96d2.png">
5. Mention any other details that might be useful.
   Currently is is impossible to install a version of typescript that pleases all dependencies of the cli. As you can see in the image above, tslint requires >=1.7.3 and @angular/tsc-wrapped requires ^1.9.0-dev (the -dev) preventing it from being a compatible version.

I'm assuming that this will be fixed when typescript 1.9.0 is released fully or updated to 2.0.0 but it's making for a very annoying reminder error. Is one peer dependency required more than another or not required at all?

**Comment by Jacob-Friesen** [comment]
Initially I got an error like that, but I upgraded from NPM 2 to NPM 3 and it worked (similar setup, but I am using Node.js 4.4.7). Additionally, I was doing an upgrade from the System JS Angular CLI for an already created app instead of a new app using [this document](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md). I still get messages when installing NPM packages like the above, but they are warnings not errors which does not prevent package installations.

So you may want to check if NPM has not been properly upgraded to 3 and upgrade. Not a fix, but at least it may stop the above from being errors.

**Comment by filipesilva** [comment]
In NPM 3 these are not errors but rather warnings. Unfortunately we didn't specify in the README that NPM 3 is needed, but this is fixed in https://github.com/angular/angular-cli/pull/1748.

**Comment by robodair** [comment]
I should note I'm on NPM 3.10.3

**Comment by filipesilva** [comment]
Odd, didn't think this would happen on npm 3. Will investigate more.

**Comment by Brocco** [comment]
This issue will be resolved via #3889 closing this issue in favor of that one.
