### ISSUE TITLE
i18n sourceLocale: en-US with @angular/localize does not go to root folder, neither baseHref

### ISSUE THREAD

**Issue by miki995** [angular/angular-cli#17014]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize

### Description
 When doing ng build --localize e.g. for 3 languages, for default one en-US, en-GB, and nl, the ng build creates 3 folders inside dist which means there is no default files under dist, thus application can be only accessed with http://localhost:3000/en-US if you set port to 3000.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Can we introduce default baseHref to be empty string "", and to add e.g. new property (`outputhPath`) to sourceLocale in angular.json to be root as default? 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

I've found a way to add rsync command to extract default folder to root like this e.g.
`rsync -a dist/en-US/* dist/ && rm -rf dist/en-US` and to set baseHref property inside angular.json file with this: 

`"i18n": {
        "sourceLocale": {
          "baseHref": ""
        },
}`

This way, my app loads at _http://localhost:3000_ as usual.

**Comment by clydin** [comment]
The behavior is indeed intentional.  There is no default build when localizing.  Each build is specialized using the provided locale (source locale included).  This specialization includes inlining the locale identifier, injecting locale data, and inlining all translations (removing runtime `$localize` calls).  The only difference with the source locale is that no translation file is loaded.  All other operations are still performed; making all builds unique to their respective locale.

The built output on the filesystem is also not in any way coupled to the deployment strategy or web server configuration.  The files can be moved, altered, or served in any way necessary to satisfy the needs of the project.  Some projects even use client language detection at the root level to automatically redirect to the appropriate locale variant.

**Comment by miki995** [comment]
@petebacondarwin @clydin Thanks for making it clear to me. I appreciate that. Cheers!
