### ISSUE TITLE
entryComponents required in tests

### ISSUE THREAD

**Issue by pburkindine** [angular/angular-cli#17110]
We are having to declare entryComponents in tests after upgrading to A9; the documentation indicates this should not be necessary
```

@NgModule({
  entryComponents: [
    xyz,
  ]
})
export class ImportModule {}
```

```
 beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [RouterTestingModule, ImportModule],
...
```

**Comment by alan-agius4** [comment]
Hi, the problem with Jest is that it doesn't use `@ngtools/webpack` to bundle and resolve the packages but rather rely on Node.Js resolutions.  These modules are not being transformed using NGCC and thus modules are resolved to their VE version.

You will need to run `ngcc` manually as a postinstall hook so that all modules are transformed to be Ivy compatible.

```js
"postinstall": "ngcc --properties main"
```

**Comment by archasek** [comment]
@alan-agius4 thanks so much, works well.
Thanks @AndrewKushnir !

**Comment by pburkindine** [comment]
@alan-agius4 
I was able to get things going by replacing the recommended postinstall (`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`) with `ngcc --properties main`.  In particular, I had to remove --create-ivy-entry-points to get this to work.  I am wondering what the implications of turning that flag off are.

**Comment by pburkindine** [comment]
@archasek thanks for the tip on the $localize setup issue which was also required to get things going

**Comment by pburkindine** [comment]
@alan-agius4 actually I spoke too soon, simple tests that e.g. a destroy$ subject is stopping some ngrx pipe fail when using the main/UMD target which weren't failing before
