### ISSUE TITLE
ng update should have removed     tslint setting no-use-before-declare

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#17117]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I ran `ng update`  to v9. Then I ran `npm run lint`. I received this error

```
▶npm run lint

> heroes-angular@0.0.0 lint /Users/papa/_git/heroes-angular
> ng lint

Linting "heroes-angular"...
no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
All files pass linting.
```

It seems I had a legacy setting in `tslint.json` for     `"no-use-before-declare": true,`

It would be great if the `ng update` removed any deprecated tslint settings.

**Comment by dgp1130** [comment]
@mgechev, what is the current status of ESLint? If we're hoping to move towards that in the future, we'll need to decide how much support we want to give TSLint for the time being.

**Comment by mgechev** [comment]
We're still in a process of evaluation. There are some performance concerns.

**Comment by dgp1130** [comment]
Since we'll still be support TSLint for the foreseeable future, we already need a migration to upgrade to TSLint 6.1. We can remove `no-use-before-declare` in that migration. This will need to be run manually in v9.x when it is ready, but will run automatically in v10 (assuming we don't migrate to ESLint by then).
