### ISSUE TITLE
Build fails on enum import

### ISSUE THREAD

**Issue by HarelM** [angular/angular-cli#17186]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
Build fails when importing an enum. strangely enough, there are other enum that are used and do not fail

## 🔬 Minimal Reproduction
Use the following repository:
https://github.com/IsraelHikingMap/Site/tree/be645e653d5e1b67fb6afe9cc1243c9a2939ea22
run `npm install` and `npm run build:watch`
Uncomment the commented out code here in this service:
https://github.com/IsraelHikingMap/Site/blob/be645e653d5e1b67fb6afe9cc1243c9a2939ea22/IsraelHiking.Web/sources/application/services/geo-location.service.ts#L125
(also in the import section).
--> compilation fails

## 🔥 Exception or Error
<pre><code>

export 'BackgroundGeolocationAccuracy' was not found 

</code></pre>

## 🌍 Your Environment
<pre><code>

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.22
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cdk                      8.2.3
@angular/cli                      8.3.22
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
```
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
This appears to be an issue with the package `@ionic-native/background-geolocation`.  The enum `BackgroundGeolocationAccuracy` is [declared](https://github.com/ionic-team/ionic-native/blob/8e9575b6aaba3a8ac3186cb40e6c397adb4621f6/src/%40ionic-native/plugins/background-geolocation/index.ts#L463) but never defined.  This is in contrast to the `BackgroundGeolocationLocationProvider` enum which has a [definition](https://github.com/ionic-team/ionic-native/blob/8e9575b6aaba3a8ac3186cb40e6c397adb4621f6/src/%40ionic-native/plugins/background-geolocation/index.ts#L18).
The type of the `desiredAccuracy` [property](https://github.com/ionic-team/ionic-native/blob/8e9575b6aaba3a8ac3186cb40e6c397adb4621f6/src/%40ionic-native/plugins/background-geolocation/index.ts#L189) also appears to have a number type and not the enum.  This aligns with the example provided at the documentation site for the plugin found [here](https://ionicframework.com/docs/native/background-geolocation) so this may be intentional.

**Comment by HarelM** [comment]
@clydin thanks a lot for the super quick response and investigation!!
I failed to notice that there was a difference between the declare enum and regular enum.
I have opened an issue for the ionic team as well here:
https://github.com/ionic-team/ionic-native/issues/3342
I think that this is not intentional but a bug in their code as I have used the plugin without their wrapper and the plugin offers enums and not numbers (which is better, I believe).
Thanks again!
