### ISSUE TITLE
Getting an Error 

### ISSUE THREAD

**Issue by DanielieWilliams** [angular/angular-cli#17226]
Getting a 404 error after coming back to my project:

"Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."

**Comment by alan-agius4** [comment]
Hi @DanielieWilliams, do you have a `baseHref` set by any chance?

**Comment by Karan36k** [comment]
@alan-agius4  I have the same issue
I am using hexo to deploy to github pages
I have tried to delete the favicon image also i have tried to rename still the same issue
I was running fine after i resize my favicon to a smaller one, the error came

**Comment by alan-agius4** [comment]
Kindly check https://stackoverflow.com/questions/56440876/refused-to-load-the-image-because-it-violates-the-following-content-security-pol for possible solutions.

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
