### ISSUE TITLE
No matching version found for @angular-devkit/build-optimizer@0.900.7

### ISSUE THREAD

**Issue by shabinpshams** [angular/angular-cli#17254]
When i am installing/creating a new angular app with version 9.0.5. getting the blow error.

No matching version found for @angular-devkit/build-optimizer@0.900.7

![image](https://user-images.githubusercontent.com/10242450/77050563-01f7e900-69db-11ea-8ee6-51c2264be5a9.png)

**Comment by alan-agius4** [comment]
Hi @shabinpshams, `@angular-devkit/build-optimizer` version `0.900.7` is available publicly on NPM repository. https://www.npmjs.com/package/@angular-devkit/build-optimizer/v/0.900.7

If you are using an NPM proxy please make sure that it's synced.

Closing as this is not a problem caused by Angular CLI.
