### ISSUE TITLE
Lossless Compression for static assets

### ISSUE THREAD

**Issue by artistry-intelligence-solutions** [angular/angular-cli#17298]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/....
"@angular/core": "~8.2.14"

### Description
 A clear and concise description of the problem or missing capability...
Lossless image compression for angular production builds.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Build managers like gulp offer great libraries for this alongside npm. Perhaps this might be a consideration for the future as a standard feature.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Yes, third party applications.

**Comment by alan-agius4** [comment]
Hi, @artistry-intelligence-solutions,

Thanks for your feature request. IMHO, I think images should be compressed outside of the build pipeline. Assets don't change that often, and a better approach would be to export/save the assets with the optimal compression. 

If you need to use a tool on top of your assets editing software to compress them even more. This doesn't need to be done in build pipeline either, as with this approach users can compress the assets using their desired compression method and tool. Also, with this approach an asset will be compressed once for every assets as opposed of having it as part of the build pipeline where each assets will be compressed each time a build is triggered.

Integrating compression in the build pipeline has the potential of becoming a foot-gun because builds will get slower because of the need to compress each assets.
