### ISSUE TITLE
improve testing capabilities

### ISSUE THREAD

**Issue by daniel-seitz** [angular/angular-cli#17368]
# 🚀 Feature request
I see that tremendous advancements were already made in the last years, dear Angular Team: Thank you for that!

There is something that I'd like to start a discussion on:

Faster and specific tests.

### Command (mark with an `x`)

- [ x] test

### Description
Looking at Jest and wallaby.js I really would like to have that/something similar by default in Angular when running ng test (in watch mode). 

As I like to keep my applications in standard, I think we all could benefit from improvements like these.

### Describe the solution you'd like
I think the main features are:
- if you change a test, just rerun that specific test
- if you change code, determine which tests are affected and rerun these tests
- if you change code in a spec file outside of a specific test, rerun the whole spec
- have a state of tests in memory and show interesting information about it in vs code

### Describe alternatives you've considered
Aquire wallaby.js and integrate it.

Input welcome.

**Comment by thesayyn** [comment]
Hello there.

I would recommend you to give a try to bazel which does exactly what you want to do. If you say that you don't want to get into a new whole world to get to know bazel, I can recommend you to give a try to NX workspaces.

Please don't mind me if I understood your problem incorrectly.

**Comment by daniel-seitz** [comment]
@thesayyn no sorry, that is not what i was looking for. have a look at the two projects if you're interested. I think there are some nice features which we could use.

**Comment by alan-agius4** [comment]
@daniel-seitz, for most of the above cases Bazel is the tool you are looking for. If you are looking for something which requires less buyin, Jest builder from NX is an alternative.

While, I agree that we should continue improving DX experiencing around testing. I don’t think that wallaby.js nor Integrate IT are viable options, because they are commercial products.

Also, I don’t see that we’ll replace Karma with another testing framework in the near future.
