### ISSUE TITLE
Constructor error with fuse.js 5.1.0

### ISSUE THREAD

**Issue by rulamon** [angular/angular-cli#17393]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, but not clear if it's a regression for Fuse or Angular CLI. 
Worked with fuse.js 3.6.1 

### Description

 fuse.js 5.1.0 gives a constructor error. When run locally I get 'fuse_js__WEBPACK_IMPORTED_MODULE_7__ is not a constructor', the deployed version gives 'Tl is not a constructor'. Posting this issue in the fuse.js github as well.

## 🔥 Exception or Error
<pre><code>

Local build: fuse_js__WEBPACK_IMPORTED_MODULE_7__ is not a constructor
In production: Tl is not a constructor
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.0
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/cdk-experimental          9.2.0
@angular/fire                      6.0.0
@angular/google-maps               9.2.0
@angular/material                  9.2.0
@angular/material-experimental     9.2.0
@angular/material-moment-adapter   9.2.0
@bazel/typescript                  1.4.1
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by rulamon** [comment]
Yes, you can find a minimal reproduction [here](https://github.com/rulamon/minimal_repro_fuse_5.1.0).
Thanks!

**Comment by alan-agius4** [comment]
Hi @rulamon, 

Thanks for the reproduction. I have looked and it and it seems that the problem is from fuse.js.

In the ESM bundle we can see that fuse class is exported via a default export: 
https://github.com/krisk/Fuse/blob/54a5a93344f54272ca57c91b3d6e69953abcea9d/dist/fuse.esm.js#L1438

But in the typings it's exported as a namespace:
https://github.com/krisk/Fuse/blob/54a5a93344f54272ca57c91b3d6e69953abcea9d/dist/fuse.d.ts#L4-L5

The above 2 are causes mismatches as during build time the import is expetced to be like:
```ts
 import * as fuse from 'fuse.js';
```

but for runtime a default import is expected:
```ts
 import fuse from 'fuse.js';
```

As a temporary workaround you add `"allowSyntheticDefaultImports": true` under `"compilerOptions"` in your application's tsconfig.json file.

Please file an issue on their issue tracker: https://github.com/krisk/Fuse/issues.

**Comment by krisk** [comment]
Should be fixed as of fuse.js@5.2.1: https://github.com/krisk/Fuse/issues/384

You can import normally: `import Fuse from 'fuse.js`.

(You **do not** need the `"allowSyntheticDefaultImports": true` option)
