### ISSUE TITLE
Need a way to selectively disable component size budgets

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#17390]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently the anyComponentStyle budget applies to all components.  However we have a couple of components that significantly exceed the budget.  We'd like to make an exception for those components, but still get warnings/errors if other components go over budget.

### Describe the solution you'd like
A way to either specify an exception list to the anyComponentStyle budget, or a way to set a per component budget that would override the anyComponentStyle budget for the specified component.

### Describe alternatives you've considered
We've upped our budget, but the components in question are considerably larger than our average, so the budget is now pretty much useless.

**Comment by luchsamapparat** [comment]
I agree. Our component styles are usually very small. However, we have one component that wraps a third-party component which comes along with its own CSS. I could of course include those styles in my `styles.css` oder via the `styles` property in my `angular.json`. However, with those solutions, the integration of the third-party component would spread across the project instead of being encapsulated by the one component.

**Comment by BruneXX** [comment]
I'm facing the same issue, and also I'm using this because angular universal because I can''t found a way to defer styles on load with preload, prefetch or preconnect...

**Comment by markuscodes1** [comment]
Is there already a discussion on how we can implement this feature? My idea is to add a property like `ignorePattern` in the budgets section of `angular.json`. This property accepts an array of regex patterns which components should be ignored. What do you think about this?

**Comment by stagefright5** [comment]
@markuscodes1 , I do not think the pattern is a suitable approach because, patterns are usually applicable for a _group_ of things and people usually want to name the component styles that should be excluded. These component styles are usually do not belong to a group. So, a property `ignoreComponents`  which takes an array of paths referring to the component that has to be excluded would make more sense.

**Comment by alan-agius4** [comment]
HI all,

Let's continue tracking this issue https://github.com/angular/angular-cli/issues/13393

Thanks.
