### ISSUE TITLE
ng build with --baseHref is not working in Angular 9

### ISSUE THREAD

**Issue by xtianus79** [angular/angular-cli#17486]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

yes

### Description

 A clear and concise description of the problem...
When you ng build --prod --baseHref 'any_other_path' >>> it only goes to dist/[output_folder]
there is no regard to an output path other than the output folder path

## 🔬 Minimal Reproduction

Angular 9.1.2

**Comment by alan-agius4** [comment]
Hi @xtianus79, 

I am not totally sure what is the regression/expected behaviour here, but the `baseHref` option doesn't effect the output path.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

Thanks.
