### ISSUE TITLE
v9.1.2 not published to npm yet

### ISSUE THREAD

**Issue by bmarcotte** [angular/angular-cli#17495]
Looks like the tag for v9.1.2 was created two days ago, but that version has not been published to npm yet, and it still shows 9.1.1 as the latest version.  So, at the moment, the latest version of @angular/cli is lagging behind the rest of the recently published @angular packages.

Is there a particular issue holding up publishing v9.1.2?  Or was this just an oversight?

**Comment by alan-agius4** [comment]
Hi @bmarcotte, we are of aware of that.

@dgp1130 is working on the release.

**Comment by dgp1130** [comment]
Yes I'm working on the release. CI is being difficult this time, hopefully I'll get it out today.

**Comment by dgp1130** [comment]
I was able to get a green CI. Though I'm not able to publish right now due to some issues with Wombat. At this point, it's too late on a Friday that I don't want to do the release anyways. I'd rather not risk problems over the weekend. I handed off caretaking to @kyliau who can follow up with this on Monday.

**Comment by EatonZ** [comment]
Hi, is this still planned for today?

**Comment by bmarcotte** [comment]
While we're waiting for any news on this release, perhaps the team can tell us what they suggest: When @angular/core and @angular/cli get out of sync like this, which of the following do you recommend?
1. Don't update @angular/core until there's a corresponding @angular/cli version to go with it.
2. Go ahead and update @angular/core, and don't worry about them being out of sync.

**Comment by alan-agius4** [comment]
Hi all, 

It's perfectly fine and safe to use different patch versions of CLI and Framework.

**Comment by kyliau** [comment]
version 9.1.2 has been published, as well as the next version 10.0.0-next.1
I apologize for the delay, we've been having some issues with this release because we transitioned from the default NPM registry to a Google proxy for security reasons and it hasn't worked as anticipated.

**Comment by EatonZ** [comment]
Hi all, looks like this is happening again with v9.1.5.

**Comment by dgp1130** [comment]
Yes, we're working on it. We're getting close to 10.0.0 RC so there were some delays on the framework (FW) side to get in some last minutes changes. Due to the way our release process works, CLI is dependent on FW and has to update some version numbers after FW has released. That then requires CI to run before we can release and if CI fails we have to fix the issue before we can release CLI.

For this particular release, there was a bug in FW related to case-sensitivity on Windows which broke CLI CI and some users. FW needed an emergency release of `9.1.6`, so CLI then has to update its own build to use FW `9.1.6` and re-run CI. CI takes at least an hour each time for CLI because we have end-to-end tests which are quite heavy weight. It also requires installing dependencies via Git tags, which is why you see Git tags set before NPM releases.

There was also an [unrelated CI issue](https://github.com/angular/angular-cli/pull/17675) on `master` which delayed release of `10.0.0-next.4`. Right now, we think both branches are in good states, we're just waiting for CI to confirm that before we release `9.1.6` and `10.0.0-next.4` for CLI.

Hopefully that gives a little more insight into the release process for CLI. As a result of this complexity, some release do get delayed by a day or two. We do our best to get them out in a timely manner.

**Comment by bbarry** [comment]
Thanks for the insight. The angular release processes and build architecture deserve some blog posts.

In general are we ok to update angular in our dev environments between versions like this or would it be better as a practice to wait until a new version comes from cli before updating (or is there another project which we should wait for in most user's pipelines)?

**Comment by dgp1130** [comment]
Version skew between FW and CLI is generally ok, since everything follows semantic versioning. In some instances we deliberately skew it such as right now where a bug in FW `9.1.5` and emergency release of FW `9.1.6` means that CLI `9.1.5` really maps to FW `9.1.6`.

As long as you don't cross major boundaries (CLI `10.0.0-next.4` with FW `9.1.6` or vice versa) you're probably fine.
