### ISSUE TITLE
Using vagrant vm and proxying with nginx getting error : [WDS] Disconnected!

### ISSUE THREAD

**Issue by sylar9232** [angular/angular-cli#1753]
On my mac i'm using vagrant (ubuntu) as virtual environment , and when running command `npm serve` i get two bugs.

First one is on browser. WebSocket URL is not correct, because its trying to send data to `localhost:4200`, even though i'm on `192.168.100.100/`

Second one, Webpack is not reloading after file change. I have created multiple new boxes and it wont work. I have installed webpack cli `sudo npm install -g angular-cli@webpack `

**Comment by sylar9232** [comment]
OK, i didn't know for flag --host 0.0.0.0, so there's no more errors for websockets.
Anyway after changing files, local access gets recompiled. But if i access from my mac, to vagrant ip, page does not get  recompiled. Websocket connection is established fine.

**Comment by filipesilva** [comment]
I can leave the issue open so other people can try and help out, but this sounds an awful lot like a Vagrant config issue and I just don't know a lot about that. If you uncover a solution that reveals a bug in the CLI I'm happy to look at a PR, but as is there isn't much I can do.

**Comment by LeviRosol** [comment]
@sylar9232 you just solved my issue! I had no idea the 0.0.0.0 host setting would ultimately allow livereload to work for me in a vagrant setup. Because of this I now have a fully functional angular-cli project running on vagrant.

With that, I can help you in your issue with vagrant not picking up your changes. 

Start by setting up vagrant-fsnotify: https://github.com/adrienkohlbecker/vagrant-fsnotify

FWIW, I would suggest using the following in your Vagrantfile:

```config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=1'], fsnotify: true, exclude: ["node_modules"]```

That exclude bit is one of the more important bits and makes a 10 fold decrease in the notification timing.

Also worth mentioning, if you only use 1024 mb of ram for your vm, the recompile is pretty slow. It appears using 2048mb is sufficient.

**Comment by filipesilva** [comment]
Now that I'm re-reading this issue, I'm reminded of this PR, made to address something similar: https://github.com/angular/angular-cli/pull/1814

This, and @LeviRosol's comment should address your file changes issue.
