### ISSUE TITLE
Migration to v9: Don’t set compilerOptions.module to "esnext" if it is set to "commonjs"

### ISSUE THREAD

**Issue by DerZyklop** [angular/angular-cli#17566]
# 🐞 Bug report

### Command
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

During the migration from 8 to 9 the `compilerOptions.module` in `tsconfig.app.json` gets set to `esnext` because of #16094 

As far as i understand #16094 should work with `esnext` but also with `commonjs`. I had `commonjs` before and it was unnecessarily overwritten. 

## 🔬 Minimal Reproduction
Set `compilerOptions.module` in `tsconfig.app.json` to `commonjs`. 

Then run `ng update @angular/cli @angular/core`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.3
Node: 10.16.0
OS: darwin x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@angular/fire                     5.2.3
@ngtools/webpack                  9.1.3
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
Not sure if this is relevant, but i have some circular dependency issues which i solved with a circular-entry-point.ts file and some deliberately chosen import statements at the end of some problematic files. This setup breaks with `esnext`. So i will try to keep `commonjs`.

**Comment by alan-agius4** [comment]
Hi @DerZyklop,
While we can do that check not to change `CommonJS` modules, this is not quite right because `CommonJS` is not intended to be used for browsers applications, but rather it's a module format which is used for server environments. We now also, do not suggest using `CommonJS` when building a server  bundle, to leverage the usage of lazy loading.

Some reasons are why CommonJS is not recommended for browsers builds;
- Webpack and Rollup works best with ES2015 modules 
- commonjs modules output is known to cause code optimizations bailouts and increase in bundle sizes.
- lazy loading chunks might not be generated

The recommend way forward here, is to fix the circular references, which are probably not being  picked when using commonjs as a module.
