### ISSUE TITLE
Uncompressed Index.html and Service Worker causes Hash Mismatch error when served through CDN

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#17700]
# 🐞 Bug report

### Command (mark with an `x`)
- [x ] build

### Is this a regression?
No

### Description

It seems that when creating a productions build, Angular CLI compresses all files except `Index.html` and `Service Worker`. Now when we deploy the files on server where static contents are served through CDN, CDN applies different optimizations on these files (minify/compress), 

As a result the `Hash` value for these files also changes, and hence service worker throws 
`Hash Mismatch`.

This issue is also reported here https://github.com/angular/angular/issues/23613

## 🔬 Minimal Reproduction
Deploy a project on server and serve static contents using CDN for example CloudFlare. And when testing website in browser you should be able to see the error.

## 🔥 Exception or Error
<pre><code>Hash Mismatch</code></pre>

## 🌍 Your Environment
<pre><code>
This applies to all versions and any browser that support Service Workers
</code></pre>

**Anything else relevant?**
In my case I was able to solve the issue as mentioned in comment https://github.com/angular/angular/issues/23613#issuecomment-626344959

It would be great if this could be fixed in Angular CLI so that we dont have to fix it manually.

**Comment by alan-agius4** [comment]
Also related to https://github.com/angular/angular-cli/issues/11538

**Comment by naveedahmed1** [comment]
One more thing, I also use Firebase for push notifications and for both workers (Angular and Firebase) to work together I concatenate  `concat dist/ngsw-worker.js src/messaging-sw.js -o dist/combined-sw.js` and then minify the output `terser dist/combined-sw.js -o dist/combined-sw.js -c --comments /^##/`. 

This approach is used by other developers as well that use Angular PWA with Push Notifications.

So, to avoid any issues with service workers I think we should just compress (remove whitespaces and comments including JSDoc-style comments) the service worker and not use mangle. So that the concatenation with other workers doesn't cause any issue.

**Comment by clydin** [comment]
When using client-side hashing/integrity checks (regardless of Angular usage), the final content should not be modified in-transit.  In this case the CDN's "Auto-minify" setting is the root cause.  Even if the CLI were to minify these files, there is still the possibility that the files will be modified with this option enabled.

Compression can be safely enabled and is not an issue in this context as it does not affect the final content; only the size during transit.  However, the already small size of the typical application index HTML will generally prevent any compression from occurring for that particular file.

**Comment by naveedahmed1** [comment]
@clydin thank you for your feedback. The CDN normally just removed the whitespaces and comments irrespective of the file size, unless other optimizations are also enabled. What if Angular CLI could remove the whitespaces and comments from these two files?

Its been few days since I deployed the files of my website https://www.mustakbil.com/ after compressing index.html and service worker file, and so far I haven't received any Hash Mismatch error.  I am using CloudFlare CDN.

**Comment by clydin** [comment]
The Angular service worker relies on file content to be transmitted to the client unmodified (this does not include transit-only file compression) to perform cache validation since the hashes are calculated at build time.  Using options such as Cloudflare's "Auto-Minify" option are fundamentally problematic in this situation.  Unfortunately, attempting to mimic and maintain the exact output of each CDNs content minification options would be both costly from a long-term sustainable perspective as well as error-prone.  Different CDNs could also have conflicting outputs resulting in some CDNs working and others failing.  The only guaranteed method to avoid this issue is to disable these type of options.  Either completely or, if possible, by adding the files referenced by the service worker to an exception list.

Changes in the design of the Angular service worker might provide support in this area.  However, the framework issue referenced above would probably be a better place to track such changes (https://github.com/angular/angular/issues/23613)

**Comment by naveedahmed1** [comment]
Thank you for your response @clydin . @gkalpak suggested to post the issue in this repo.
(please take a look at comment https://github.com/angular/angular/issues/23613#issuecomment-626354077 )

> Changes in the design of the Angular service worker might provide support in this area. However, the framework issue referenced above would probably be a better place to track such changes

I'm not suggesting to modify service worker, all I am saying is that cli should compress some other files as well.

If you search on Google for this issue, you would mostly find users complaining about hash mismatch of index.html or service worker file. 

When Angular CLI is compressing all javascript files and css, then why not index.html and service worker script file?

**Comment by naveedahmed1** [comment]
I think this issue should be reopened

**Comment by clydin** [comment]
Unfortunately, these type of CDN options can not be used safely when using the Angular service worker.  The minification instructions suggested are unfortunately only a workaround and could break at any time.  The instructions currently work because they happens to align with what Cloudflare is doing within that option.  However, Cloudflare's behavior could change at any time and it could also be different than other CDN's similar options.  In the later case, the Angular CLI would then need to choose which CDN providers should work and which will not.  Minifying these files beforehand, whether in the CLI or by some other means, still leaves the potential for failure due to these type of CDN options which allow the content to be modified at any time.

From a general optimization perspective, there are definite merits to minifying these files.  There are currently two open issues that are tracking optimization of the service worker files (https://github.com/angular/angular-cli/issues/11538)  and of the generated index (https://github.com/angular/angular-cli/issues/11360).  Both are being actively considered.  Please upvote and comment if these are features you would like to see included within Angular.

**Comment by gkalpak** [comment]
Some clarifications:

- The minification of the SW script should not affect the SW's behavior, since the hash of the SW script itself is not hashed and kept track of in the SW manifest. So, the minification or not of `ngsw-worker.js` should not cause hash mismatch errors.
  Minifying the SW script is also being tracked in angular/angular#27490 (it is not really a CLI issue).

- Minifying `index.html` _does_ cause hash mismatch errors (since its hash is kept track of in the SW manifest). So, I suggested to open an issue for adding support of minifying `index.html` (which _is_ a CLI issue/responsibility). It turns out this is already tracked in #11360.

- Minifying `index.html` should only be seen as an optimization, not as a solution to the problem of CDNs changing file contents by auto-minifying files (for the reasons mentioned by @clydin above).
