### ISSUE TITLE
ng xi18n isn't extracting localized messages when using $localize inside component ts files

### ISSUE THREAD

**Issue by blasco** [angular/angular-cli#17855]
Has this issue been solved?
https://github.com/angular/angular-cli/issues/16375

The issue was closed due to inactive, but I'm experiencing the same problem, the tool generates the translations for the html tags, but not for the strings marked with $localize in the typescript code.

**Comment by petebacondarwin** [comment]
No it has not been resolved yet. It will be fixed by https://github.com/angular/angular/pull/32912

**Comment by petebacondarwin** [comment]
Please follow that PR for updates. By the way `$localize` has not yet been published as a public API.

**Comment by blasco** [comment]
@petebacondarwin is there an alternative recommended way to translate code within typescript? I need this to translate the metatags, so the html template is not sufficient here as far as I know.

**Comment by petebacondarwin** [comment]
You can use `$localize` it is just not officially supported and you must work out the message IDs yourself because the current extractor will not extract them. One workaround for this is to use a custom id which you place at the beginning of the `$localize` tagged string:

```
$localize `:@@custom-id:my message text`;
```

In this case the id for this message will be `custom-id`.
