### ISSUE TITLE
ERROR in budgets, maximum exceeded for assets folder

### ISSUE THREAD

**Issue by ArunKumar-Annamalai** [angular/angular-cli#17909]
Hello, I'm getting error when do the ng build --prod in server. it works fine in my local system. Below error i'm getting

ERROR in budgets, maximum exceeded for assets/plugins/iCheck/line/_all.css. Budget 10 kB was exceeded by 11.2 kB.
ERROR in budgets, maximum exceeded for assets/plugins/iCheck/minimal/_all.css. Budget 10 kB was exceeded by 3.84 kB.
ERROR in budgets, maximum exceeded for assets/plugins/iCheck/square/_all.css. Budget 10 kB was exceeded by 5.23 kB.
ERROR in budgets, maximum exceeded for assets/plugins/seiyria-bootstrap-slider/css/bootstrap-slider.css. Budget 10 kB was exceeded by 128 bytes.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap/dist/css/bootstrap-theme.css. Budget 10 kB was exceeded by 15.1 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap/dist/css/bootstrap-theme.min.css. Budget 10 kB was exceeded by 12.9 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap/dist/css/bootstrap.css. Budget 10 kB was exceeded by 133 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap/dist/css/bootstrap.min.css. Budget 10 kB was exceeded by 109 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.css. Budget 10 kB was exceeded by 3.47 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css. Budget 10 kB was exceeded by 2.78 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.css. Budget 10 kB was exceeded by 6.79 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css. Budget 10 kB was exceeded by 5.36 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.standalone.css. Budget 10 kB was exceeded by 7.63 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.standalone.min.css. Budget 10 kB was exceeded by 6.07 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css. Budget 10 kB was exceeded by 12.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css. Budget 10 kB was exceeded by 10.6 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.standalone.css. Budget 10 kB was exceeded by 13 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker3.standalone.min.css. Budget 10 kB was exceeded by 11.2 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/samples/css/samples.css. Budget 10 kB was exceeded by 55.8 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/dialog_ie7.css. Budget 10 kB was exceeded by 409 bytes.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/dialog_iequirks.css. Budget 10 kB was exceeded by 759 bytes.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/editor.css. Budget 10 kB was exceeded by 29.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/editor_ie.css. Budget 10 kB was exceeded by 30.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/editor_ie7.css. Budget 10 kB was exceeded by 32.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/editor_ie8.css. Budget 10 kB was exceeded by 30.4 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/kama/editor_iequirks.css. Budget 10 kB was exceeded by 33 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/dialog.css. Budget 10 kB was exceeded by 3.27 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/dialog_ie.css. Budget 10 kB was exceeded by 4.27 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/dialog_ie7.css. Budget 10 kB was exceeded by 4.84 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/dialog_ie8.css. Budget 10 kB was exceeded by 4.44 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/dialog_iequirks.css. Budget 10 kB was exceeded by 4.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor.css. Budget 10 kB was exceeded by 35.8 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor_gecko.css. Budget 10 kB was exceeded by 35.9 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor_ie.css. Budget 10 kB was exceeded by 36.8 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor_ie7.css. Budget 10 kB was exceeded by 38.8 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor_ie8.css. Budget 10 kB was exceeded by 36.9 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono/editor_iequirks.css. Budget 10 kB was exceeded by 37.4 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/dialog.css. Budget 10 kB was exceeded by 3.39 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/dialog_ie.css. Budget 10 kB was exceeded by 4.39 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/dialog_ie8.css. Budget 10 kB was exceeded by 4.92 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/dialog_iequirks.css. Budget 10 kB was exceeded by 4.41 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/editor.css. Budget 10 kB was exceeded by 39.7 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/editor_gecko.css. Budget 10 kB was exceeded by 39.8 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/editor_ie.css. Budget 10 kB was exceeded by 40.7 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/editor_ie8.css. Budget 10 kB was exceeded by 41.5 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/ckeditor/skins/moono-lisa/editor_iequirks.css. Budget 10 kB was exceeded by 41.3 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/jquery-ui/themes/base/jquery-ui.css. Budget 10 kB was exceeded by 25.1 kB.
ERROR in budgets, maximum exceeded for assets/bower_components/jquery-ui/themes/base/jquery-ui.min.css. Budget 10 kB was exceeded by 20 kB.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by AndriiDidkivsky** [comment]
Same issue since yesterday. 
We've tried to deploy new version of application and on CI side got error. 
Question is why assets folder validating through the anyComponentStyle rule. 
we've fallen in the issue with
tinymce-angular: 3.4.0  here we have some  extra styles in the assets folder
@angular/cli: 9.1.8
`
budgets: {
    ....
    {
       type: "anyComponentStyle", 
       maximumWarning: '6kb', 
       maximumError: '10kb'
    }
`

All version of angular(s) packages are not fixed and allow minor version update "~9.1.0".
Also can't reproduce locally. 
So I think problem could be in update of something. 

@ArunKumar-Annamalai did you find a solution without increasing maximumError parameter ? 
@alan-agius4 do you need more details ?

**Comment by ArunKumar-Annamalai** [comment]
> Same issue since yesterday.
> We've tried to deploy new version of application and on CI side got error.
> Question is why assets folder validating through the anyComponentStyle rule.
> we've fallen in the issue with
> tinymce-angular: 3.4.0 here we have some extra styles in the assets folder
> @angular/cli: 9.1.8
> `budgets: { .... { type: "anyComponentStyle", maximumWarning: '6kb', maximumError: '10kb' }`
> 
> All version of angular(s) packages are not fixed and allow minor version update "~9.1.0".
> Also can't reproduce locally.
> So I think problem could be in update of something.
> 
> @ArunKumar-Annamalai did you find a solution without increasing maximumError parameter ?
> @alan-agius4 do you need more details ?

No @AndriiDidkivsky Still I'm getting same error.

**Comment by ArunKumar-Annamalai** [comment]
> Same issue since yesterday.
> We've tried to deploy new version of application and on CI side got error.
> Question is why assets folder validating through the anyComponentStyle rule.
> we've fallen in the issue with
> tinymce-angular: 3.4.0 here we have some extra styles in the assets folder
> @angular/cli: 9.1.8
> `budgets: { .... { type: "anyComponentStyle", maximumWarning: '6kb', maximumError: '10kb' }`
> 
> All version of angular(s) packages are not fixed and allow minor version update "~9.1.0".
> Also can't reproduce locally.
> So I think problem could be in update of something.
> 
> @ArunKumar-Annamalai did you find a solution without increasing maximumError parameter ?
> @alan-agius4 do you need more details ?

@AndriiDidkivsky I fixed this issue by removing "^" symbol from build-angular and angular-cli

"@angular-devkit/build-angular": "^0.803.26",
"@angular/cli": "^8.3.26",

changed as below

"@angular-devkit/build-angular": "0.803.26",
"@angular/cli": "8.3.26",

**Comment by Jabark** [comment]
It seems this issue was introduced in [this update](https://github.com/angular/angular-cli/releases/tag/v8.3.27). We have the same issue where we are importing external css files into our assets folder, and it is throwing this error on all the files. Works fine on version 8.3.26.

**Comment by Jabark** [comment]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.3.26

### Description

When we have external CSS files being put into the assets folder in angular.json like so:
```
"assets": [
   "src/favicon.ico",
   "src/assets",
   {
      "glob": "**/*",
      "input": "./node_modules/external-module",
      "output": "./assets/external-module"
   }
]
```
running `ng build --prod` no longer works:
```
[1m[31mERROR in budgets, maximum exceeded for assets/external-module/external-module.css. Budget 10 kB was exceeded by 357 kB.[39m[22m
```

## 🔬 Minimal Reproduction
- Have an external node module that contains CSS files such as ckeditor as the OP has in his list
- Update the build options to move those files into the assets directory
- Run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
[1m[31mERROR in ./src/styles/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) budgets, maximum exceeded for assets/eds-styles/eds-all.css. Budget 10 kB was exceeded by 357 kB.
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\NormalModule.js:310:13
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\loader-runner\lib\LoaderRunner.js:182:20
    at context.callback (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\mini-css-extract-plugin\dist\loader.js:135:14
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\Compiler.js:343:11
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\Compiler.js:671:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\Compiler.js:668:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\Compilation.js:1385:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\C21869A\git-repos\software-ui-case-management\node_modules\webpack\lib\Compilation.js:1376:32
 @ multi ./src/styles/styles.scss styles[0][39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-all.css. Budget 10 kB was exceeded by 357 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-all.min.css. Budget 10 kB was exceeded by 294 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-components.css. Budget 10 kB was exceeded by 63.8 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-components.min.css. Budget 10 kB was exceeded by 44.3 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-primitives.css. Budget 10 kB was exceeded by 279 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-primitives.min.css. Budget 10 kB was exceeded by 240 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-all.css. Budget 10 kB was exceeded by 357 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-all.min.css. Budget 10 kB was exceeded by 294 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-components.css. Budget 10 kB was exceeded by 63.8 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-components.min.css. Budget 10 kB was exceeded by 44.3 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-primitives.css. Budget 10 kB was exceeded by 279 kB.[39m[22m
[1m[31mERROR in budgets, maximum exceeded for assets/eds-styles/eds-primitives.min.css. Budget 10 kB was exceeded by 240 kB.[39m[22m[0m
</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.28
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.28
@angular-devkit/build-angular     0.803.28
@angular-devkit/build-optimizer   0.803.28
@angular-devkit/build-webpack     0.803.28
@angular-devkit/core              8.3.28
@angular-devkit/schematics        8.3.28
@angular/cli                      8.3.28
@ngtools/webpack                  8.3.28
@schematics/angular               8.3.28
@schematics/update                0.803.28
rxjs                              6.4.0
typescript                        3.5.3
</code></pre>

**Anything else relevant?**
Upgrading to Angular 9 with `ng update @angular/core@9 @angular/cli@9` avoids the issue

**Comment by Jabark** [comment]
@alan-agius4 Able to reopen this based upon the above?
