### ISSUE TITLE
Option in ng build to preserve build files until compilation is done

### ISSUE THREAD

**Issue by sethigoldy** [angular/angular-cli#17916]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] **build**
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Hey

Currently I have been using Nginx with my Angular build and its directly pointed towards Angular output path i.e. /dist folder and serving it from there itself.

But what happens is when I run `ng build --prod` on the server then it remove the old build first from the output folder and then compile the new build from the source code and till the time the process completed my Nginx throws `internal server error`.

I know the option `--deleteOutputPath=false` where you can specify ng build to not delete the output path files but it just keeps on adding files which I think is not a good option.

### Describe the solution you'd like
There should be an option in ng build like `--preserveOutputPath=true` where if given will not delete any content from the output path until the compilation is done and then replaces the new build files with the old build files.   

### Describe alternatives you've considered
As I am using Ansible to deploy and build angular app on server I have to specify different output path while building app and then replaces that one's files with the output path (/dist) files which is an additional task needed to perform.

**Comment by alan-agius4** [comment]
Hi @sethigoldy,

I don't think that building on the production servers is something that should be done nor promoted.  Using Ansible or similar deployment software is absolutely a better approach.

Here are some reasons why running `ng build` on a production server is not recommended.

- As mentioned in your issue, `ng build` will by default delete the contents of the `dist` folder, which results in either your application to be down during the entire build process or you'll manually need to clean up the old files.
- Having `node_modules` on your production environment increases the risk security vulnerabilities, most of these dependencies in your project are meant to be installed on development environments.
- When building on a production server, you might end up using a lot of it's resources which might result in slower response times of your production application.
- If you build your application in the production pointed directory, if an error occurs midway during the build process you might end in an invalid state, were you don't have the old version application or the application nor the new one.
- Some files will get overridden, example `index.html`, `runtime.js` etc.. Serving the application before the build has finished might result in errors in the browser.
- By "switching directories" you can easily rollback to the previous version of the application is something goes wrong with the new version.
- Not to mention that this will increase the complexity in CLI, because we'd need to keep track of which files to delete and which not.

If you want to reduce the burden of deployment, you can opt to use the automatic deployment provided in the CLI via `ng deploy`. Which allows you to deploy your application effortlessly to a number of cloud providers such as Firebase hosting, Azure, Amazon S3.

Visit https://angular.io/guide/deployment#automatic-deployment-with-the-cli for more information.

**Comment by sethigoldy** [comment]
@alan-agius4 Thanks for the detailed answer. 

If I lets say build angular app on my dev environment how do I then proceed working with different environments i.e. if I have to test my build on staging environment then I have to create a build specific using `ng build --configuration=staging` and push the output folder in git which is kind of automated with Ansible for me right now. 
And also, if by mistake the staging build goes to production is there a way to stop this.

**Comment by alan-agius4** [comment]
> ng build --configuration=staging and push the output folder in git which is kind of automated with Ansible for me right now. 

Not sure why you need Git for these especially considering you are using Ansible were you can easily move and sync files between different remote hosts. (https://docs.ansible.com/ansible/latest/modules/synchronize_module.html)

> And also, if by mistake the staging build goes to production is there a way to stop this.

I am not really sure what you mean by this. But with scripted deployment pipeline the room for mistake should be pretty small.
