### ISSUE TITLE
Script tag insertion logic

### ISSUE THREAD

**Issue by spencech-upbeat** [angular/angular-cli#17961]
Hi, I understand that we need these <script/> tags inserted on ng build; I'm wondering though if there is a way to inject them in a specified location in the index file (e.g., with a ${ng:script} token or html comment). 

The use case here is I'm building an angular.io web-app for a Craft Plugin, running within a twig partial file that does not have a traditional DOM structure (no html/head/body because those are in the base layout defined in the CraftCMS). So what's happening is that the five or so <script/> tags are injecting on the first line of the file, but because that's an illegal region for html content here, the twig rendering is breaking (it has to happen between {%content%} block tags in the doc). I'm sure I can write an auxiliary task or something to find and move that snippet or just import my angular "index" file as a partial into a parent template. But I'm wondering if there is a better way to achieve this? Thanks!

From earlier issue:
What's the use case? Could you also help us understand why you don't want these scripts? Do you plan to add them manually in your HTML?

_Originally posted by @alexeagle in https://github.com/angular/angular-cli/issues/11816#issuecomment-412136240_

**Comment by alan-agius4** [comment]
Hi @spencech-upbeat, currently the index file needs to be a valid HTML5 document, which at the very minimum should contain a `head` and `body` tag. The main reason for this is that we read the index document as AST and not plain text, for the reason to be able to inject scripts, base href, stylesheets, icons, etc.. in the right order if other tags are present.

In addition to that, some features also rely on the fact that the `index.html` is "static" such as the Service Worker and App Shell.

As per https://github.com/angular/angular-cli/issues/11816 we should allow the index file to be optional. However, in such case I think it should be up to the users to generate the script/style tag since we cannot really create tags for each templating engines since each engine might require different syntaxes.  For example .NET and Razor requires paths to be prefixed with a `~/`.

Currently it's not in scope of the CLI to officially support templating engines. Thus, auxiliary steps or 3rd party builders are required.

**Comment by spencech-upbeat** [comment]
Makes sense thanks, I've got a decent solution in place, so all's well that ends well. If it's relevant for any other CraftCMS devs, I just set routing to ignore the index file created by angular.io and used asset bundles to load the scripts that angular-cli injects.
