### ISSUE TITLE
[feat] run budgets check for dev configuration

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular-cli#18011]
# 🚀 feature request

### Relevant Package

 This feature request is for angular's build package

### Description

I think many developers will benefit if Angular checked for issues with the bundle size **during** the development. The *budgets* feature is great, but it only reports issues during "prod" build(*). There could be a lot of changes in the application by the time developer tries to run a prod build and it might be hard to identify the issue resulted in a bundle increase. On the other hand, if bundle size checks were performed during regular *ng serve* workflow, the silly mistakes resulting in increased bundles could be caught right away.

(*) It appears that the "budgets" feature works in any configuration as long as `"optimization": true` is set.

### Describe the solution you'd like
*Run budgets check even when the `optimization` flag is set to false.*
It's OK if the values in the budgets are set to some high numbers due to the nature of un-optimized bundles. The point here is to catch a drastic bundle *increase*.

### Describe alternatives you've considered
I've tried adding `dev` configuration to *angular.json*, which would look like this:
```ts
"dev": {
  "optimization": true,
  "vendorChunk": false,
  "budgets": [
    {
      "type": "bundle",
      "name": "main",
      "baseline": "390kb",
      "maximumWarning": "20kb",
      "maximumError": "40kb"
    }
  ]
},
```
This works, but the build process takes too long due to the `optimization` flag.

**Comment by DmitryEfimenko** [comment]
Andrew, you're right. Thanks for transferring it.

**Comment by alan-agius4** [comment]
@DmitryEfimenko, Thanks for this feature request.

I don't think this is that useful during development especially since the sizes can fluctuate quite a lot and don't necessary mean a whole lot.

I also think that for a number of reasons this might easily become a nightmare to maintain from a user perspective and might become a foot-gun.

 Here's some examples;
- A developer can import a 20Kb file and retain all or a 500Kb file and retain 1Kb during an optimised builds. As a developer you should be concerned about the former and not the latter.
- An update to any dependency can cause the budgets to fail even though there is no size difference for optimized builds.
- If the emitted code by either the TS or NG compiler changes slightly, lets say it's more 
"verbose" to enable better dead code elimination/tree-shaking, budgets will fail again for the wrong reason.
- If you are working in a team most likely you will reach and exceed the limit on a daily bases.

**Comment by DmitryEfimenko** [comment]
@alan-agius4 I'm glad you gave it a good amount of thought. Closing the issue!

**Comment by reda-alaoui** [comment]
Hi @alan-agius4 , 

Each commit is verified by the CI before it reaches master branch. The CI check the angular part by performing a production build. The CI build takes more than 10 minutes.

The developer adds a component. He checks everything via `ng serve`. When done, he pushes to the CI. Many minutes later, he discovers that the build failed because its component style exceeds the allowed budget.

The fact that `ng serve` does not run budgets check reduce our productivity and pleasure to develop.

Please reconsider the implementation of this feature.
