### ISSUE TITLE
Current README.md is not reflective of webpack version

### ISSUE THREAD

**Issue by RedFour** [angular/angular-cli#1808]
The current readme say that the instructions are for webpack:
> The current instructions on this file reflect usage for the webpack version.

But when I follow the upgrade instructions:
>Updating angular-cli
>
>To update angular-cli to a new version, you must update both the global package and your project's local package.
>
Global package:
>
>npm uninstall -g angular-cli
>npm cache clean
>npm install -g angular-cli@latest
>Local project package:
>
>rm -rf node_modules dist tmp
>npm install --save-dev angular-cli@latest
>ng init

It made my project use systemjs

when check the version of the cli:
>ng -v

I get angular-cli: 1.0.0-beta.10

I've been using angular-cli@webpack since RC5 was released, and I keep seeing people say that the main branch now uses webpack. And even the readme says it is using webpack. But checking the npm site shows the last published version is still beta.10:

https://www.npmjs.com/package/angular-cli

**Comment by rolandoldengarm** [comment]
Yeah that was confusing to me as well.

**Comment by filipesilva** [comment]
You're right that doing `npm install -g angular-cli@latest` will not give you the webpack release. It's not currently marked as `latest` since we're still ironing out a few kinks.

I understand it's confusing, and recognize that it's a bad thing, but we don't have a good way of having split documentation for beta.10, the webpack version, and the latest master at the same time so... this is what we have right now. The best I can do is to try and get the webpack release out and thus stabilize the readme, and until then explain the situation in issues as it comes up.
