### ISSUE TITLE
ivy and aot if using ngcc only, it returns some strange errors

### ISSUE THREAD

**Issue by GlauberF** [angular/angular-cli#18100]
# 🐞 bug report

### Affected Package
@angular/....

### Description

if I activate IVY and activate AOT, it returns some strange errors.
Since I want the final size to be small, I don't want to disable AOT.
After some tests, I found that to work with IVY and AOT, I need to change the postinstall.

generates error: `"postinstall": "ngcc"`
Does not generate error: `"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`

my fear is that using postinstall in this way is not the correct one and that the result is not what it should be, with the size of smaller packages.

But that's how far I got, because mistakes are confusing

## 🔥 Exception or Error
https://gist.github.com/GlauberF/376c265513ef70f51baf87d8530e0e3e

## 🔬 Minimal Reproduction
Large project and a client, I can't generate reproduction

## 🌍  Your Environment
<pre><code>
Angular CLI: 9.1.7
Node: 12.18.1
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.7
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                9.1.7
@schematics/update                 0.901.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by GlauberF** [comment]
ok, thanks!

**Comment by alan-agius4** [comment]
Hi,

Firstly, node-sass is not the sass processor of choice of the Angular CLI since v8. By default we use dart sass, which should perform better.

That said, most likely it’s taking more time due to the increase memory usage regression which should be fixed in the next patch of the CLI. You can test this theory by setting the `assets` to an empty array. Unfortunately, if that’s not the case, a reproduction would be required to investigate the cause of the slowness.

Since this issue is related to node-sass and we going off-topic from the original reported problem. I suggest that a new issue is created when having a reproduction, as it will also be easier for other users to find the issue if they encounter the same node-sass problem.

**Comment by GlauberF** [comment]
thanks, I will close this issue and test the empty assets and wait for the patch.
if the problem continues, I open a new issue
