### ISSUE TITLE
Question: Can we change target in tsconfig.base.json.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#18162]
Can we change target in `tsconfig.base.json` to `esnext` by users manually. And we can use babel and `.browserslistrc` to transform codes.

After all, the downstream users will convert the code by angular-cli. For ng-packager, setting it to esnext is reasonable.

**Comment by alan-agius4** [comment]
Hi @xiaoxiangmoe, this is currently not supported out-of-the-box and you might end up in a broken state when using ES2017.

- ZoneJS will does work with native async/await which was introduced in `ES2017` (angular/angular/issues/31730).
- In the CLI downlevelling only happens when targeting ES5 as an output.
- We don't recommend using `esnext` as currently is the same as and `ES2020`, however, in future version of TypeScript this can evolve in a backwards incompatible ways, resulting in build-time or run-time errors during a TypeScript update. So, if anything you should pin the target to a fixed version.

There have been some initial experiments into more intelligent transpilations and downlevelling see: #6170

**Comment by xiaoxiangmoe** [comment]
@alan-agius4  What do we need to do to target to es2020？

**Comment by alan-agius4** [comment]
You will need to extend the Angular CLI using a custom builder that at the very minimum downlevels async/await as per issue #16170.

It's important to point out, that while extending the Angular CLI builders is possible, the Angular tooling team doesn't officially support this.
