### ISSUE TITLE
Speed up angular library build

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#18246]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

`ng build some-lib --watch` will rebuild the whole program every time there is a modification. 
And our library is very large, every time you change a line of ts and save it, it will take a long time to recompile.

### Describe the solution you'd like

I think that when ng build --watch, it is not necessary to perform the operation of packing fesm and umd.
Every time we change a line of css or a line of js, it only updates a single js file of esm2015. Compiling a single file should not take a long time.

**Comment by alan-agius4** [comment]
@xiaoxiangmoe, thanks for opening the issue, however this is not caused by the CLI, please file an issue in [ng-packagr](https://github.com/ng-packagr/ng-packagr).

Also, it would be beneficial to know, how long is a long time?, where is this time spent?, and provide more details about the size of your library.
