### ISSUE TITLE
Build Optimizer marks unpure code as pure

### ISSUE THREAD

**Issue by xumepadismal** [angular/angular-cli#18297]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't think so as this is related to library update and not to Angular update

### Description
After updating Swiper library to 6.0.4 it becomes broken in Angular context. Building separately with Webpack in Production mode works as expected.

I investigated the problem a bit and now I'd say that it's because of "sideEffects: false" in their package.json. If I understand correctly side effects and "pure" modules are different things, or? Anyway, build optimizer's webpack loader marks some code as PURE when it isn't.

At first I've [created issue](https://github.com/nolimits4web/swiper/issues/3708) in Swiper's repo but maintainer says that Webpack's tree shaking works as expected. And that is true.
Here is why I decided to create issue here. Thanks!

## 🔬 Minimal Reproduction

Here is the repl. I used simplified contents of the file that caused the issue in my case but there are another files with similar issues as well.

https://repl.it/repls/UnwittingFrivolousSystemsanalysis#index.js

The problematic place in output:
```
/*@__PURE__*/ /*@__PURE__*/ Object.keys(Methods).forEach(function (methodName) {
    $.fn[methodName] = Methods[methodName];
});
```

**Comment by alan-agius4** [comment]
Hi @xumepadismal, 

A side effect is when code performs a special behaviour when imported other than exporting one or more symbols. In this case when you import a symbol from the mentioned file above, there is a top level side effect which effects the scope. https://github.com/nolimits4web/swiper/blob/1b08355540bdda8707debfc72721c8e0a12274c2/src/swiper.js#L10-L18

What is happening here is that the package is marked as being side effect free and so build optimizer will annotate all top level function calls with the pure marker so that terser can drop function call. However in this case it's breaking the library because the mentioned code does have side effects.

Our recommendation would be that the mentioned library marks the non-side-effect files as such.
