### ISSUE TITLE
Option to build without emiting files

### ISSUE THREAD

**Issue by ribbon-otter** [angular/angular-cli#18369]
# 🚀 Feature request

### Command (mark with an `x`)
- [x] build

### Description
To test to see if a project would build, I have to actually build it fully. This takes around a minute. Since I wish to automatically test that my schematic outputs valid code, I don't need code to be generated, merely know if the code compiles. Thus, I want to only execute the first stages of the angular compilation process.

### Describe the solution you'd like
Add a commandline flag to build which prevents it from outputting any code. For similarity with typescript, I would call it `--noEmit`, after the typescript flag which does the same thing.

Thus,
```
ng build --noEmit
```
would run all stages of compilation up to the point where it is clear that the code will successfully build. This would be the parsing and typechecking phases most likely, though I am not familiar enough with the angular compiler to know for sure

### Describe alternatives you've considered
I thought maybe `ng lint --type-check`  would do what I want. However, `ng lint --type-check` does not catch type errors. 

I could build a system which watches the output of the angular builder and then kills the process as soon as it enters the code generation phase. However, this seems a kludgy solution. 

Adding '"noEmit":true' to `tsconfig.base.json` suppresses the typescript generation, thereby saving ~30s of the ~60s build time, but angular cares on its marry way attempting to bundle anyway, leading to the console filling with erroneous warnings of unnecessary files included in the build. While the best alternatives  I have found, it seems that suppressing output on an angular level would still be superior as this would save even more time, and cause no erroneous warnings.

**Comment by alan-agius4** [comment]
Hi @ribbon-otter, 

Implementing an `noEmit` version of the browser builder is not really in scope of the Angular CLI. Also this would also have little to no impact on performance since the full build will still need to be performed but without emitting the files on disk.

From your explanation, however what you'd want to implement a new builder which invokes the Angular Compiler or TypeScript and performs solely type-checking diagnostics. Something similar to: https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#a-minimal-compiler

As a side note, we do have similar test cases and we do run a full build. Example:
https://github.com/angular/angular-cli/blob/master/tests/legacy-cli/e2e/tests/generate/guard/guard-implements.ts#L6
