### ISSUE TITLE
Support an option to build assets for only one locale

### ISSUE THREAD

**Issue by VasuMWS** [angular/angular-cli#18414]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
The `ng build --prod --localize` build assets in each locale that the application has. An option to build assets only for one locale and reusing them will be a great way to minimize the time of the building of server. 

### Describe the solution you'd like
`"assets": "reuse"` will be a good addition to the locale configuration.

### Describe alternatives you've considered
I have tried removing the assets directory from each locale after building but the server can't find them as each locale is loaded separately. I would also like to know other alternatives if any for now.

**Comment by alan-agius4** [comment]
Hi @VasuMWS, 

Thanks for this feature request.

We are not quite understanding by what you mean building assets for each locale.  Assets are directly copied without any processing to each locale variant. In most operating systems the copy-on-write technique is used which is very fast and takes no additional space.

Deployment is also a factor here too. As one could deploy the application variants and additional files in any file structure that fits their requirements. While the output of the Angular CLI can be deployed and/or served directly as is, it doesn’t need to be and for more complex applications one could modify the layout of such files as part of a post processing step.

As you mentioned for example you remove the assets folder from each locale, however you would need to configure your server to handle the assets for each locale.

**Comment by VasuMWS** [comment]
Hi @alan-agius4, 
Thank you for the reply.

By building assets for each locale I mean following. The situation is that I am using 3-4 locale for my website and each one of them is hosted at website.com/locale-code. But for each of them in the dist folder, there is the assets folder copied. I was wondering if we could have assets in only one of those folders and each locale use assets from that folder. It would be very helpful in decreasing the time needed for deployment.

**Comment by alan-agius4** [comment]
Having a single directory which all the assets for all locales is error prone from a build perspective especially when decelerating/using assets in templates, dynamic and not in CSS files. This would also slow down the build since we'll need to parse the HTML and CSS files and rebase all paths.

There are a number of options. If you still wish the have a single directory which contains all the assets on your production server.  I'll list the most straightforward two.

- The the most easier approach would be that you create a symlink to the assets directory from each locale.

```
ln -s dist/browser/assets dist/browser/fr/assets
ln -s dist/browser/assets dist/browser/pt/assets
```

- The other approach would be that you configure your server to serve all assets from a specific directory.
```
website.com/fr/asstets -> /dist/browser/assets
website.com/pt/asstets -> /dist/browser/assets
```
