### ISSUE TITLE
Increased build time causing timeouts

### ISSUE THREAD

**Issue by abhaychawla** [angular/angular-cli#18489]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
N/A

### Description
We have been facing recurring issues recently with our production build which is being created for the repository using Travis. The build gets stuck at some point leading to timeout and keeps on failing. 

## 🔬 Minimal Reproduction
Link for the repository: https://github.com/openMF/web-app

## 🔥 Exception or Error
Unable to determine the cause.

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.9
Node: 12.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
We have tried increasing the memory as well as disabling the build optimizer (as per earlier raised issues) but it still doesn't seem to work.

**Comment by alan-agius4** [comment]
Hi @abhaychawla,

Thanks for reporting the issue.

Angular version 7 is no longer under support. See the [Support policy and schedule](https://angular.io/guide/releases#support-policy-and-schedule) section.

A lot has changed since version 7 and issue you are experiencing might have been solved. Kindly update the to most recent Angular and Angular CLI version. More information on the update steps can be found in our update guide: [update.angular.io](https://update.angular.io)

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
