### ISSUE TITLE
Web worker syntax error in IE11

### ISSUE THREAD

**Issue by nitsuj102284** [angular/angular-cli#18519]
I have a web worker in **Angular 9** that is throwing a `Syntax error` in IE11. Looking at the debugger, it is on this line:
`const worker = new Worker('src/workers/attachment.worker', { type: 'module' });`

Removing `{ type: 'module' }` moves past the error, but of course returns 404.
`new Worker() will only be bundled if passed options that include { type: 'module' }.`

How do I make Angular web workers work in IE? Is this a bug, or am I doing it wrong?

(Note: my web workers are working in Chrome and Firefox)

**Comment by alan-agius4** [comment]
Hi @nitsuj102284, 

Unfortunately there are a number of reason why this can happen and without the full details of the issue template we are unable to determine the root cause.

Kindly open a new issue in [Angular CLI](https://github.com/angular/angular-cli) repo and provide all the requested information.

Thanks for your understanding,
Alan
