### ISSUE TITLE
Configurable image compression feature in CLI for commonly used file extensions

### ISSUE THREAD

**Issue by sahilpurav** [angular/angular-cli#18547]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 When we're working on any client side framework, along with main bundle size, the size of assets are equally critical. At this moment, auto image compression technique is not a part of this awesome CLI tool.

### Describe the solution you'd like
 Since the compression process would be heavy depending on the size of project, we cannot keep it *mandatory* default. My proposal is to incorporate as an optional configuration in `angular.json` and use [imagemin](https://github.com/imagemin) with options to configure the quality. It will add up new dependency in CLI project but looking at desire of this function in the [closed issues](https://github.com/angular/angular-cli/issues?q=compress+images), it is worth considering.

I'm open for contribution as major amount of work is already been done by me in various project. But I would like to initiate the discussion and get suggestions from CLI experts.

### Describe alternatives you've considered
 I've been working on Angular since long time and executed many projects, every time I setup a project, it has a requirement to auto compress the images. I That's why I extended the Angular Builder with `imagemin` library to compress "SVG", "JPEG", "PNG" files. Prior to that, I created a script to incorporate it after CLI build.

**Comment by alan-agius4** [comment]
IMHO, I think images should be compressed outside of the bundling pipeline. Assets don't change that often, and a better approach would be to export/save the assets with the optimal compression.

If you need to use a tool on top of your assets editing software to compress them even more. This doesn't need to be done in build pipeline either, as with this approach users can compress the assets using their desired compression method and tool. Also, with this approach an asset will be compressed once for every assets as opposed of having it as part of the build pipeline where each assets will be compressed each time a build is triggered (unless the result it’s cached).

That said, I am going to leave this open so we discuss this in our next team meeting.

**Comment by sahilpurav** [comment]
> IMHO, I think images should be compressed outside of the bundling pipeline

**It is what I used to do in all my previous project until this becomes a norm for all future projects.**

> and a better approach would be to export/save the assets with the optimal compression.

**This is always an "ideal" approach which hardly anyone follows. Humans tend to miss such things. Tools help overcome mistakes.**

Also, I don't think assets will be compressed on every build If we're using library like **imagemin**, as it detects the current quality of image and then take a decision to compress. This process can completely avoided by simply caching the results of previous build. 

_Moreover, this would be an optional feature, users can opt in to take a benefit out of it._

> That said, I am going to leave this open so we discuss this in our next team meeting.

**Sure, do inform me the outcome, I'm really happy to give back my contribution to community :+1:**

**Comment by dgp1130** [comment]
Hi @sahilpurav, we talked about this today and our general feelings are that compressing assets is something that should happen before the build pipeline. There are a few reasons for this:

* Image compression requires supporting a wide variety of image formats, compression codecs, and options for them. This particular problem scales out really quickly.
* We would need to limit ourselves to lossless compression, but users would get much better images if developers use lossy compression while taking image quality into account ([this video](https://www.youtube.com/watch?v=F1kYBnY6mwg) explains it pretty well). Lossy decisions need to be made by a human as "acceptable quality" is very subjective and even the codecs to use will vary from image to image based on its contents. When developers use lossy compression, our automated lossless compression would not really improve anything and just wastes time.
* This will also slow down builds significantly. Image compression is known to be a very intensive operation, and getting the smallest image often requires brute forcing many different algorithms. Caching would help here, but first time builds would still be impacted.
* Compressing the image at build time means the original needs to be stored in the repository. Raw image formats for quality cameras can be quite large (multiple MBs each), and blow up a repository's size very quickly.
* A reasonable follow up feature ask would be to generate multiple qualities for a given image of different sizes, which further increases complexity and means that specific images _shouldn't_ be over optimized because they should be for larger sizes.

Image editing tools like Photoshop already provide image compression and export functionality, so we feel it makes more sense to perform these optimizations as part of the image editing process. This also works well for evaluating different lossy codecs and identifying which algorithm has the most significant impact with the least amount of quality drop. [squoosh.app](https://squoosh.app/) is a great tool for comparing codecs as well.

We're hoping to add an `ng health` command at some point in the future, which could surface issues with an Angular project. It may make sense to surface large image sizes in this command to draw more attention to this particular issue and what devs can do about it. We're still in the early thoughts about `ng health`, so we have more thinking and design to do, but it could fit there, rather than as automatic compression run on build.

If you still really want a tool for this purpose, a [Webpack plugin](https://www.npmjs.com/package/imagemin-webpack-plugin) already exists. You would need to use [`custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) Angular builders to use it however. Alternatively, you could make your own Angular builder that provides this functionality without requiring `custom-webpack`.
