### ISSUE TITLE
[proposal] `i18n-extract` alias should be one letter long 

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#19109]
# 🤖  It is more like improvement

### Command 

- [x ] xi18n

### Description

[`i18n-extract` is an alias for `xi18n`](https://github.com/angular/angular-cli/blob/47490527ff8cfbd912225ae1ba1e7e3128547938/packages/angular/cli/commands/xi18n.json#L7) which looks a bit weird as all the rest available CLI commands aliases are like one letter long ref: https://angular.io/cli#command-overview  -and it is make sense.

### Proposal

So the proposal is to change `i18n-extract` alias to one letter alias, for example `x`

**Comment by alan-agius4** [comment]
Hi @kuncevic,

Thanks for this feature request. We have discussed this during yesterdays team meeting and we feel that adding an alias is not necessary and can cause confusion here.

Here's some points that were brought up:
- Not all commands have aliases
- `x` doesn't really represent a good alias for `ng i18n-extract`. 
- A single letter alias can be confusing at times and we'd like to move away from them in the future, in favor of more smarter aliases. Example `ng d` is not intuitive to which command it an alias of, as it can be of both `ng deploy` or `ng doc`.
- The alias for i18n extraction will be removed in the next major version.

**Comment by kuncevic** [comment]
Yeah i c, alias it is something that easier to type however it is a bit an exercise to type `xi18n` 
Based on [that](https://angular.io/cli#command-overview ) most of the aliases seems like just a first letter of the command and it is make sense. So `x` seems to me is a good candidate aliasing `xi18n` as `x` is the first letter of `xi18n` command and secondly it is the second letter of the word `eXtract`.

Speaking of other commands I think short commands like `new`, `doc`, etc does not need an aliases as it is very easy to type 3 letters, but if command has more than 3 letters it is a great candidate for aliasing. So based on that the `doc` commands may not need aliasing but it make more sense to alias `deploy` command as `d`

**Comment by alan-agius4** [comment]
> So based on that the doc commands may not need aliasing but it make more sense to alias deploy command as d

This is actually one of the reasons why deploy doesn't have an alias, this is because a single letter alias for a command is ambiguous and users were using `ng d` as a shortcut for `ng doc` instead of `ng deploy`. Hence, we decided to remove the alias from `ng deploy` as it was harmful as users might have unwilling causing their application to be deployed.

The `xi18n` is actually also ambiguous by itself for new users and in fact in version 11, we will be removed this command in favor of `extract-i18n`.

Another reason why certain commands have aliases is that they can are typically used more frequently such as `ng serve`, `ng build` and `ng generate`, while `deploy`, `xi18n`, `run`, `config`, `update` are used far less frequently.

We do agree that we should provide some form of aliases to commands, but we feel that a single letter aliases is not ideal at this point.
