### ISSUE TITLE
keep app state at hmr reload

### ISSUE THREAD

**Issue by fab313** [angular/angular-cli#19233]
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I am using HMR with the latest rc of the cli. 
Refresh and refill of forms works great, however the app state (saved as variables in services) is lost with each refresh.
It seems that all services are newly created with each reload.

### Describe the solution you'd like
The app doesn't loose the current state of the app at an HMR update

**Comment by alan-agius4** [comment]
Hi,

Thanks for trying our new feature 😄.

This issue is pretty similar and has the same root causes and resolutions of https://github.com/angular/angular/issues/39367

Currently for every change the application needs to be destroyed and re-bootstrapped and therefore any data which is stored in a service and not persisted in a browser storage (global object, localStorage, etc...) will be lost.

Ideally there would be a component/service unload/load mechanism, which HMR can leveraged in this case. 

Since both this and the previous mentioned requests are rather similar and likely need the same implementation and API changes. I suggest we continue tracking this in https://github.com/angular/angular/issues/39367. Feel free to chime in over there and give your input.
