### ISSUE TITLE
Errors when using mixed re-export

### ISSUE THREAD

**Issue by Seemspyo** [angular/angular-cli#19263]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Not tested yet.

### Description

 Webpack resolve error ocurs when project has a **mixed re-export files(.ts files and .d.ts files).**

## 🔬 Minimal Reproduction

I'd setup minimal repo [here](https://github.com/Seemspyo/ng-issue).

run `ng serve` or `ng build`

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/lib/index.ts
Module not found: Error: Can't resolve './lib' in 'D:\Projects\test\src\app\lib'
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.7
Node: 14.12.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@Seemspyo, I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the TypeScript project or file an issue on their issue tracker.

TypeScript is not eliding the import of the .d.ts file from the JS file.

**input TS**
```.ts
export * from './lib'; //<-- this is a .d.ts
export * from './test-module';
```

Running TSC directly

```bash
tsc -p tsconfig.app.json
```

Will output
**out-tsc/app/app/lib/index.js**
```js
export * from './lib';
export * from './test-module';
//# sourceMappingURL=index.js.map
```

`./lib` in this case doesn't exists which will cause webpack to fail to resolve the file and error.

As a workaround you can rename the `.d.ts` file to `.ts`, which will case TypeScript to emit an empty `lib.js`. Alternativle you can can the `export *` to use the export type `export type { Test } from './lib';`.
