### ISSUE TITLE
`ng lint --files` errors  in multi project workspace

### ISSUE THREAD

**Issue by piebe** [angular/angular-cli#19380]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 no

### Description

 
In a workspace with minimal 1 library and 1 project the command `ng lint`  or `ng lint thelibrary --file a/file/in/the/library.ts` both work as expected. However the command `ng lint --file a/file/in/the/library.ts` throws an exception:

``` 
An unhandled exception occurred: File "a/file/in/the/library.ts" is not part of a TypeScript project 'projects/client/tsconfig.app.json,projects/client/tsconfig.spec.json,projects/client/e2e/tsconfig.json'.
```

## 🔬 Minimal Reproduction

  1.  ng new lint-issue
   1. cd lint-issue/
 1.   ng g library sample
  1.  touch projects/sample/one.component.ts
  1.  echo "" > projects/sample/one.component.ts
  1.  ng lint sample
  1.  ng lint sample -files projects/sample/one.component.ts
  2. ng lint --files projects/sample/one.component.ts

step 7 succeeds, but step 8 throws exception

## 🔥 Exception or Error
<pre><code>

[error] Error: File "C:\\temp\\test\\lint-issue\\projects\\sample\\src\\lib\\sample.component.ts" is not part of a TypeScript project 'tsconfig.app.json,tsconfig.spec.json,e2e/tsconfig.json'.
    at _lint (C:\temp\test\lint-issue\node_modules\@angular-devkit\build-angular\src\tslint\index.js:121:23)
    at _run (C:\temp\test\lint-issue\node_modules\@angular-devkit\build-angular\src\tslint\index.js:51:35)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 13.7.0
OS: win32 x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
ng-packagr                      11.0.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

Similar (but different) issue: https://github.com/angular/angular-cli/issues/13399

**Comment by alan-agius4** [comment]
Hi @piebe, 

Thanks for opening this issue.

The root cause of this is that when no project is specified, the CLI will try to find the project from the CWD. The project which will be retrieved from the CWD in this case will be `lint-issue `, which doesn't contain the file you are trying to lint `projects/sample/one.component.ts`.

Since changing the behaviour here might be considered a breaking change because you are trying to lint a file which is not part of the current project, this is not a regression and considering that the TSLint builder is deprecated. I think it would be best to retain the current behaviour which users are accustomed too.

Thank you for your understanding.
