### ISSUE TITLE
Bring @angular-devkit/build-angular version in line with @angular/*

### ISSUE THREAD

**Issue by epelc** [angular/angular-cli#19402]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

When running ng update on a 10.x project after angular 11 was released it is hard to do a partial update ie to the latest 10.x with @angular-devkit/build-angular since it's version numbers do not match the rest of angular at all. ie it uses `0.1000.5`.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Bump @angular-devkit/build-angular versions up to 11.x so that they match the rest of the @angular/* repos or at least document this different versioning behavior on the `ng update` page.

You should be able to easily run `ng update @angular/core@^10 @angular-devkit/build-angular@10^` and get ie 10.2.x installed automatically when angular 11 was released.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Perhaps better docs about this difference in versioning? ie links/info on the ng update page https://angular.io/cli/update

Ideally it'd just match the rest of angular so it isn't a special case as it's required on many projects.

**Comment by alan-agius4** [comment]
Hi @epelc,

Thanks for opening the issue. 

I do agree that in future we should align the version of experimental packages with other Angular CLI versions. However, this will happen during a major release and when the mentioned packages are no longer experimental.

I think the main "confusion" here is caused by you are try to run `ng update @angular-devkit/build-angular` which is not needed as `ng update @angular/cli` will update the mentioned package. See the update guide on how to update a complete project: https://update.angular.io/?v=10.0-11.0

Side note: the formula for experimental packages version is; `"0." + (major * 100 + minor) + "." + patch`. So, for example, the 8.0.0 release becomes the 0.800.0 version for experimental packages.

**Comment by epelc** [comment]
@alan-agius4 ah I wasn't aware that updating the cli updated that package too. I think it was confusing because if you just run `ng update` to list which packages need updates then `@angular/devkit/build-angular` shows up in the list.

Maybe it should be removed from the list or perhaps the list could be upgraded to be tree view/show somehow that updating `@angular/cli` would also update this package? Hopefully people will find this issue instead in the mean time. As you said it's primarily a concern between major version updates. I don't think angular breaks things that often between the minor upgrades(I haven't required holding back to a specific minor yet).

**Comment by alan-agius4** [comment]
Oh, that shouldn’t be there. Let’s remove it.
