### ISSUE TITLE
Give me the option to update an existing xlf file

### ISSUE THREAD

**Issue by mafalarz** [angular/angular-cli#19418]
# 🚀 Feature request

- [X] extract-i18n

### Description
I'm a bilingual developer and always need to translate my apps.  Whenever I make any small change, I have to re-translate the whole xlf file. I do not use any translation services, I can speak both languages very well. I also do not see why I have to pay hundreds of dollars to use a translation app just so it can take an old xlf file and use the ID of it to update the fresh one produced each time by the angular cli.

### Describe the solution you'd like
Give me the option to update an existing xlf file. 

### Describe alternatives you've considered

- I've read on a close thread it would look weird to have translation in an xlf file produced by angular cli. This sounds more dogma than technical limitation. You can always give the option to do both.
- martinroob/ngx-i18nsupport

**Comment by petebacondarwin** [comment]
Hi @mafalarz - thanks for making this feature request. I appreciate that this is an important part of your workflow.
While it would be nice to include this as part of the Angular framework tooling, we have to consider the effort involved and the capacity of the team to support and maintain it. If it was trivial then I would expect there to be numerous tools out there that do this already, or one could just implement a script of their own. Also remember that the framework supports multiple formats not just XLIFF, so if the team were to implement this it would be necessary to support all these formats.

As you have linked in the description there is https://github.com/martinroob/ngx-i18nsupport, which includes a utility called XliffMerge, which is free and has worked well for people in the past. I understand that this has some current incompatibilities with the latest version of Angular. Apart from that, I believe this does exactly what you are requesting. I would imagine that our efforts would be better spent fixing up that project rather than rewriting the tooling internally here.

**Comment by alan-agius4** [comment]
Hi @mafalarz, thanks for this feature request. As @petebacondarwin mentioned I don't think such tool should be in scope of the Angular CLI.
