### ISSUE TITLE
i18n: after upgrade to v11 xi18n extracts locales from the imported libraries too

### ISSUE THREAD

**Issue by js-padavan** [angular/angular-cli#19447]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/localize

### Is this a regression?
Yes, the previous version in which this bug was not present was: 10.2.2

### Description
Having a custom library which has some locales and ships their translations. Running ng extract-i18n in app which consumes that library, locales from library are also extracted in messages.xlf. As a result, in messages.xlf appears such trans-units
```
      <trans-unit id="satusInterrupted" datatype="html">
        <source>interrupted</source>
        <context-group purpose="location">
          <context context-type="sourcefile">node_modules/<libname>/__ivy_ngcc__/fesm2015/libname.js</context>
          <context context-type="linenumber">906</context>
        </context-group>
      </trans-unit>
````
In previous version only app's locales are extracted.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.2
Node: 12.3.1
OS: win32 x64

Angular: 11.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.0
@angular/cli                    11.0.2
@angular/material               11.0.0
@nguniversal/builders           11.0.0
@nguniversal/express-engine     11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment]
From previous discussions that we had we mentioned that;
1) The extraction tool should not extract messages for libraries which provide their own translations files (This needs work on the extraction tool and also be included in the APF spec).
2) Possibly provide an option to exclude `node_module` from the extractions.
3) Possibly seperate vendor and local output example `local-messages.xlf` / `vendor-messages.xlf`.

Let's continue discussion this over https://github.com/angular/angular-cli/issues/18885 since it's related.
