### ISSUE TITLE
Watch mode broke when migrate from angular6 to angular9

### ISSUE THREAD

**Issue by proofyman** [angular/angular-cli#19549]
Hi. First of all, I have read your rules and **asked question on stackoverflow**, it was closed as `not suitable for this site`.

**Question started here:**
I have a custom webpack build (without ng-cli) because of perfomance considerations. (It works 5x slower than custom build and 1.5x slower with tweaks from custom-webpack builder in jit mode).

Webpack-dev-server watch doesnt work for lazy modules in aot mode (JIT fine). Btw when I setup ng-cli watch works just fine (ts configs all the same). When I change Application.module watch and recompile works ok.

Could you advise me, where to search problem ?

Problem appeared when I migrate from angular6 to 9, I use loadChildren as function in my project.

Some of aot related config:
![image](https://user-images.githubusercontent.com/2207686/101157752-b1452080-363b-11eb-8983-309599e5d34b.png)
![image](https://user-images.githubusercontent.com/2207686/101157770-b86c2e80-363b-11eb-8319-190e7f88de35.png)
![image](https://user-images.githubusercontent.com/2207686/101157791-bc984c00-363b-11eb-9d83-7b97a8ad1db3.png)
tsconfigs:
![image](https://user-images.githubusercontent.com/2207686/101157816-c5891d80-363b-11eb-91df-82470fb2b1cd.png)
![image](https://user-images.githubusercontent.com/2207686/101157825-c91ca480-363b-11eb-9df7-e67ede64d55a.png)

**Comment by alan-agius4** [comment]
Hi @proofyman,

Without a reproduction it would be hard to determine what is the root cause.

With just the screenshots above, it's rather un-clear how your application lazy loading is configured, how Webpack is configured, what's your environment etc.. I am afraid that the reason why your issue was closed on stackoverflow is that vital information that is needed to reproduce and understanding the problem, such as a full webpack configuration, lazy-loading module info was not provided. (I am only speculating here cause the SO issue is not linked here).

All in all, we, the Angular tooling team don't provide support for custom Webpack configurations.
