### ISSUE TITLE
faild to gengerate metadata.json useing @ngtools/webpack with custom webpack

### ISSUE THREAD

**Issue by joebnb** [angular/angular-cli#19545]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Did this behavior use to work in the previous version? yes

### Description

i use '@ngtools/webpack' want it generate metadata.json while webpack build, but it wasn't out put [name].metadata.json that i expected.

## 🔬 Minimal Reproduction
this is aot plugin

```js
new AngularCompilerPlugin({
        tsConfigPath: path.join(PAGE_PATH, 'tsconfig-aot.json'),
        entryModule: path.join(PAGE_PATH, 'src', 'index.ts'),
        emitClassMetadata: true,
        emitNgModuleScope: true,
        sourceMap: true,
        compilerOptions: {
            "genDir": path.join(PAGE_PATH, "lib/"),
            "enableIvy": false,
            "skipTemplateCodegen": true,
            "strictMetadataEmit": true
        }
        // mainPath: PAGE_PATH
    })
```
this is the tsConfigpath
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./lib",
    "sourceMap": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "module": "es2020",
    "target": "es2015",
    "emitDecoratorMetadata": true,
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ],
    "paths": {
      "my-lib": [
        "src/"
      ]
    }
  },
  "angularCompilerOptions": {
    "genDir": "aot/",
    "enableIvy": false,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true
  },
  "include": [
    "./src"
  ]
}
```

this is loader
```
export const aot = {
    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
    loader: '@ngtools/webpack'
}
```
i want after webpack bundle out put with index.metadata.json

**Comment by alan-agius4** [comment]
Hi @joebnb,

This is expected because this plugin is not designed to be used to compile libraries.  

Using ng-packagr ensures that your library will always be bundled following latest APF spec https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/mobilebasic

Also most likely there are several broken paths when using Webpack to bundle a library.
- Type Definition files will not be emitted.
- Using Webpack to bundle your library might break NGCC, because Webpack will replace the ES6 module `import` and replace them with `__webpack_require__` which NGCC doesn't know how to handle.

Why not use ng-packagr directly without using Webpack?,
