### ISSUE TITLE
fileReplacements no longer works with css files

### ISSUE THREAD

**Issue by OrangeDog** [angular/angular-cli#19717]
https://github.com/angular/angular-cli/issues/11451 got locked.

It used to work at one point (Angular 8), then was broken again by #19310

**Comment by alan-agius4** [comment]
Hi @OrangeDog,

This is working as expected.

`fileReplacements` is only intended to work with TypeScript source files. Unfortunately, in earlier versions there was a bug which causes the file replacements to work for other files outside of the TypeScript compilation. 

 In version 11, we introduced an error when invalid file extensions are provided as previously unsupported file replacements were simply ignored silently.

**Comment by OrangeDog** [comment]
But many people seem to want this feature. Why can't it be reinstated?

**Comment by KBroichhausen** [comment]
@alan-agius4 First of all, thank you for all the work. I still don't get the point here. Even if this was a bug and was intended to never work this way, it worked that way! What is the reason of fixing a bug, which just extended the feature set?
To me it looks like you unnecessary broke peoples' build / angular.json. I have four different builds and now need a workaround to replace HTML-files after upgrading from v 10 to v 11.

For me, it gets pretty messy now. The builds use different assets via assets option, different index.html via "index" option but all other html file needs to be replaced via custom script now.

**Comment by alan-agius4** [comment]
Unfortunately, this was one of those implementations that the fact that it worked was a bug, replacing anything which is not part of the TypeScript compilation was never a supported use-case.



In version 10, we introduced a new build pipeline which makes it non trivial to support these previously use-cases, in version 11.1 we are also introducing a version of the compiler plugin which handles fileReplacement strictly at a TypeScript compilation level where it replaces modules during module resolution.







The reason why we want to be stricter with fileReplacements is that it's better to have earlier feedback as build errors rather than failing silently. One of these use-cases is when trying to replace the `index.html` or replacing a global `.css` file which previously failed silently.

**Comment by alan-agius4** [comment]
> For me, it gets pretty messy now. The builds use different assets via assets option, different index.html via "index" option but all other html file needs to be replaced via custom script now.

Are you using configuration merging? 
https://angular.io/guide/workspace-config#alternate-build-configurations

**Comment by KBroichhausen** [comment]
> 
> 
> > For me, it gets pretty messy now. The builds use different assets via assets option, different index.html via "index" option but all other html file needs to be replaced via custom script now.
> 
> Are you using configuration merging?
> https://angular.io/guide/workspace-config#alternate-build-configurations

No. I probably should do it for my tests and production builds. Why is this important?

I just realised that even a pre-build script will not work as before. E.g. I test two builds at the same time by using `ng build --watch` with two different configurations simultaneously. Replacing html files on file level will lead to the fact that they both must use the same files.

So, I need to stick at version 10 for now.
