### ISSUE TITLE
Angular devkit schematics move issue

### ISSUE THREAD

**Issue by sahithiKondapalli** [angular/angular-cli#19806]
# 🐞 Bug report

### Command (mark with an `x`)

- [X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.6.7

### Description
we have a angular schematics project for generation of customized files which we linked to node server using npm link and the command for generating the files will be invoked from node server.

@angular-devkit/schematics: ^0.6.7 

Recently we upgraded angular from 6 to 7 and from then  i am getting the below exception on triggering the command for the file generation.

Path "/__path__/__name__.ts" does not exist. 

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

</code>const templateSource = apply(url('./files'), [
  applyTemplates({
    classify: strings.classify,
    dasherize: strings.dasherize,
    name: options.name
  }),
  **move(normalize(options.path as string))**
]);</pre>

**Anything else relevant?**

**Comment by sahithiKondapalli** [comment]
> # 🐞 Bug report
> ### Command (mark with an `x`)
> * [X ] new
> * [ ]  build
> * [ ]  serve
> * [ ]  test
> * [ ]  e2e
> * [ ]  generate
> * [ ]  add
> * [ ]  update
> * [ ]  lint
> * [ ]  extract-i18n
> * [ ]  run
> * [ ]  config
> * [ ]  help
> * [ ]  version
> * [ ]  doc
> 
> ### Is this a regression?
> Yes, the previous version in which this bug was not present was: 0.6.7
> ### Description
> we have a angular schematics project for generation of customized files which we linked to node server using npm link and the command for generating the files will be invoked from node server.
> 
> @angular-devkit/schematics: ^0.6.7
> 
> Recently we upgraded angular from 6 to 7 and from then i am getting the below exception on triggering the command for the file generation.
> 
> Path "/**path**/**name**.ts" does not exist.
> 
> A clear and concise description of the problem...
> ## 🔬 Minimal Reproduction
> const templateSource = apply(url('./files'), [
> applyTemplates({
> classify: strings.classify,
> dasherize: strings.dasherize,
> name: options.name
> }),
> **move(normalize(options.path as string))**
> ]);
> 
> **Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @sahithiKondapalli, 

I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
A lot has changed since Angular CLI version 7 which no longer under support. The currently LTS version is 9 see https://angular.io/guide/releases#support-policy-and-schedule

**Comment by alan-agius4** [comment]
Hi @sahithiKondapalli, 

I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.

That said, a lot has changed since Angular CLI version 7 which no longer under support. The currently LTS version is 9 see https://angular.io/guide/releases#support-policy-and-schedule

 Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
