### ISSUE TITLE
ng build generating vendor source maps even if set to false

### ISSUE THREAD

**Issue by dwilches** [angular/angular-cli#19879]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know, first detected in ng-cli's version 11.0.7

### Description

In angular.json I added a configuration like follows:

```
"configurations": {
    "dev": {
        "optimization": true,
        "outputHashing": "all",
        "sourceMap": {
            "scripts": true,
            "styles": true,
            "hidden": false,
            "vendor": false
        },
        "namedChunks": true,
        "extractLicenses": false,
        "vendorChunk": true,
        "buildOptimizer": true
    },
    "production": {
      ...
```

Then I build with `ng build --configuration=dev` and, taking a look at the `dist` folder, I see the `vendor.*.js` files are getting source maps generated:

```
~/my-project/ $ ll dist/vendor*
-rw-r--r-- 1 dwilches 1.3M Jan 26 15:52 dist/vendor-es2015.d5ada0d379d2aba7da41.js
-rw-r--r-- 1 dwilches 7.5M Jan 26 15:52 dist/vendor-es2015.d5ada0d379d2aba7da41.js.map
-rw-r--r-- 1 dwilches 1.4M Jan 26 15:52 dist/vendor-es5.d5ada0d379d2aba7da41.js
-rw-r--r-- 1 dwilches 7.6M Jan 26 15:52 dist/vendor-es5.d5ada0d379d2aba7da41.js.map
```

But notice in my source map config I set `"vendor": false`.

## 🔬 Minimal Reproduction

1. `ng new hello`: accept all defaults
2. Add this configuration to `angular.json`:
```
"dev": {
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": {
        "scripts": true,
        "styles": true,
        "hidden": false,
        "vendor": false
    },
    "namedChunks": true,
    "extractLicenses": false,
    "vendorChunk": true,
    "buildOptimizer": true
},
```
3. `ng build --configuration=dev`
4. `ls -l dist/hello/vendor*`

## 🔥 Exception or Error

There will be a source map for `vendor` inside of `dist/hello`. But there shouldn't be as it was configured as disabled.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.7
Node: 10.23.1
OS: linux x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @dwilches, 

Thanks for opening this request, however this is the working as intended. 

When vendor sourcemaps is disabled, the vendor sourcemap file is still generated. Although this doesn't the contains of the resolved 3rd party libraries.

There are two main reasons for this:
1) `//# sourceMappingURL` comments will not be removed from the source file of the libraries and a warning will be issued in the console because the sourcemap cannot be loaded. (#19236)
2) Having the vendor sourcemap file still improves debugging experience, even when the sourcemaps are not fully resolved. 

### `vendor.js.map` generated with `vendor: false`
![image](https://user-images.githubusercontent.com/17563226/105965584-e726e400-6083-11eb-8ecc-e16b538711d9.png)
![image](https://user-images.githubusercontent.com/17563226/105965659-fd34a480-6083-11eb-9023-f9ce0e68928e.png)

### `vendor.js.map` not generated
![image](https://user-images.githubusercontent.com/17563226/105965784-20f7ea80-6084-11eb-8760-910df2a87cd4.png)


![image](https://user-images.githubusercontent.com/17563226/105965671-002f9500-6084-11eb-9e66-26f1565c4c06.png)

**Comment by gorshkov-leonid** [comment]
@alan-agius4  In my case I have 29MB of vendor.js.map and source map generation takes 22min (because of the usage of fat corporate libraries). Without `sourceMap` the build takes 4min.
I also expected vendor.js to be disabled with any option. 
But for now, as I understand the only way to make build faster is to disable `sourceMap` completely.

**Comment by gorshkov-leonid** [comment]
Or maybe I am wrong and the fact of fat vendor.js.map that includes all 3rd-party libs is a problem (checked it via source-map-explorer). Do you know why all libs are included?

**Comment by alan-agius4** [comment]
Possibly one of the reasons why the generation is slow is due to `optimization` and `buildOptimizer` being used in combination with `sourceMaps`. 

The mentioned 2 options are not meant to be during development.

if you can provide a reproduction I’ll happily take a look.

**Comment by gorshkov-leonid** [comment]
@alan-agius4 Thank you in advance. I've prepared an example with `monaco-editor`: https://github.com/gorshkov-leonid/test-source-map . There `buildOptimizer` is disabled but `optimization` is enabled to have source maps on the preproduction server. 

Don't pay attention to code where web workers for monaco-editor are bundled. Just call `npm install && npm run build`. And look into `build/dist/test-source-map/vendor.js.map`

**Comment by alan-agius4** [comment]
Thanks for the reproduction.

The monaco-editor source is huge, this causes the sourcemap to grow quite a lot because the source content is included in vendor sourcemap. 

This is working as expected and as documented in here https://angular.io/guide/workspace-config#source-map-configuration because when `vendor` is set to `false` vendor source-maps are not resolved to actually source-map as this process is considerably slow.

It is also important to point out that `vendorChunk` is only meant to be used for development purposes and shouldn't be used when using the `optimization` option. Using vendor chunking can cause several optimization bailouts.

At the point I see two options here; 
1) Extend the CLI using 3rd party builds such as https://github.com/manfredsteyer/ngx-build-plus and https://www.npmjs.com/package/@angular-builders/custom-webpack
2) Provide a way to truly disable vendor sourcemaps, this would however has some cavets, such as the issue with stacktraces explained above. 


I think for the time being, option 1 is the best way option to achieve this. We can re-evaluate option 2, if we see more community members requiring this.
