### ISSUE TITLE
LoggerApi.error should accept messages of type Error

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular-cli#19951]
### Description
`LoggerApi.error` only accept string messages:
https://github.com/angular/angular-cli/blob/efb97c87f023497dc59a2f4fa3825a2ca78606da/packages/angular_devkit/core/src/logger/logger.ts#L91
 
When implementing a custom builder, we have to convert errors to strings before logging them with some logic like:
```ts
context.logger.error(error.stack ?? error.toString());
```

### Describe the solution you'd like
Would that make sense to move this logic inside the logger and change the signature to:
```ts
error(error: string | Error, ...)
```

**Comment by Jefiozie** [comment]
Hi @alan-agius4, would this be something that the community can pick-up? If so, would we need to know any specific things we should be aware of? Or any pointers on how we can implement it. 

Thanks

**Comment by edbzn** [comment]
@alan-agius4 We had a problem with the following common scenario : 

```ts
catchError((error) => {
  context.logger.error(error) // <- fail silently and log anything
})
```
The typing of the logger argument (type `string`) is ignored by the compiler because errors are of type `any`. I understand the idea of having more actionable error message but in this case it leads to the opposite.

**Comment by alan-agius4** [comment]
In this case, the problem is more that `Error` is of type `any`.

When using `any`, there is always a chance of having undefined or broken behaviour. In this case what `any` means is that the `error` can be anything, it can be a string, number, instance of class, array etc... 

IMHO, a good practice is that when having an `any` type you verify the type similar to how you'd do if the type was `unknown`.

We can see the problem with using unguarded `any` types in a trivial example:

```ts
const foo = (val1: number, val2: number) => val1 + val2;

const val1: any = "1";
const val2: any = 2;

console.log(foo(val1, val2));
```

The output will be 12, instead of 3.

**Comment by alan-agius4** [comment]
An `error` can really be anything you can also check this with a simple try/catch/block.

```ts
try {
  throw [1,2];
} catch (e) {
  console.log(e); //  Array [1,  2]
}
```

I think it’s a good practice that when using any type you verify the type before using.

**Comment by edbzn** [comment]
That's right, it would be easier if errors would be of type unknown... no way to forget to check the type. In any case, thank you!
