### ISSUE TITLE
Building shaders (.glsl)

### ISSUE THREAD

**Issue by RCnowak** [angular/angular-cli#19963]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
It is not possible to build shaders for webGL. I tried to use @angular-builders/custom-webpack to add rule for importing .glsl files to ts files but it doesnt work because of .

### Describe the solution you'd like
I would be great to add ability to import shaders (import vertex from './my-vertex-shader.glsl'). It's a plain text actualy so it wont be a problem I think. 

### Describe alternatives you've considered
A lot of angular developers have to put shaders to assets and download them via http-client. But what if I dont want to make a request. It can be bad for users and it's not comfortable for developers. It's much easier to import it.

**Comment by alan-agius4** [comment]
Hi @RCnowak,

Thanks for this request.

Angular CLI doesn't support Webpack specific features, importing a non JS module (ie: `import vertex from './my-vertex-shader.glsl'`) is non standard JavaScript behavior and only works because of tools like Webpack.

Hence, using a 3rd party solutions that extends the Angular CLI is the recommended approach if you don't wish to fetch the assets via HTTP.  I suggest you file an issue with the author of `@angular-builders/custom-webpack` for support.
