### ISSUE TITLE
Angular 12: Don't include deprecated TSLint by default

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#20105]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Not applicable

### Description
- [TSLint](https://www.npmjs.com/package/tslint) has been deprecated since January 1st, 2020 
<img width="1195" alt="tslint_deprecated" src="https://user-images.githubusercontent.com/13006107/108644843-a8b3f780-747e-11eb-8dad-d53ae52886d9.png">
- As such, TSLint should not be included by default in Angular projects

## 🔬 Minimal Reproduction
- (Optional) Create global angular config file to use `yarn` package manager if not present. `cat ~/.angular-config.json`
   ```json
  {
    "version": 1,
    "cli": {
      "packageManager": "yarn"
    }
  }
  ```
- `npx @angular/cli@12.0.0-next.1 new web-apps --create-application false`
- Open `package.json`
	```json
	{
	  "devDependencies": {
	    "tslint": "~6.1.0"
	  }
	}
	```

## 🌍 Your Environment
<pre><code>
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0-next.1
Node: 15.9.0
OS: darwin x64 (11.2.1)
Yarn: cd web-apps` && `yarn outdated

Angular: 12.0.0-next.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0-next.1
@angular-devkit/core         12.0.0-next.1
@angular-devkit/schematics   12.0.0-next.1
@schematics/angular          12.0.0-next.1
@schematics/update           0.1200.0-next.1
rxjs                         6.6.3
typescript                   4.1.5
</code></pre>

**Anything else relevant?**

**Not relevant to this issue**
- Thank you to the team for making [`strict` option the default](https://github.com/angular/angular-cli/pull/20029) when creating applications (starting Angular 12)

**Comment by rgant** [comment]
Not having a linter included with angular cli by default would make my life trying to help people work with Angular much more difficult.

**Comment by MuhAssar** [comment]
why not just replacing it with eslint

**Comment by kyliau** [comment]
We will stop generating new projects with TSLint starting version 12. 
The TSLint builder will also be deprecated in version 12, but actual removal will be in v13.
When running `ng test` in version 12, CLI will print out commands to inform users third party alternatives that they can install on their own, much like the behavior of `ng deploy`.
As for replacing TSLint with something else **by default**, we'll let users make the call because existing solutions are all community owned, and our team does not have the resources to maintain and provide support for third party builders.
One of our major concerns is that adding third party builders to CLI could potentially increase the number of transitive dependencies by **a lot**, and hence massively increase the download size of Angular CLI.
For these reasons, we think it's best to leave the decision to users.

**Comment by prabh-62** [comment]
Is [codelyzer](https://www.npmjs.com/package/codelyzer) package also not included by default?

**Comment by alan-agius4** [comment]
Yeah, closely we is only used with tslint, hence when removing tslint we will also remove codelyzer..
