### ISSUE TITLE
incorrect update commands shown after "ng update"

### ISSUE THREAD

**Issue by sanket-bhalerao** [angular/angular-cli#20219]
ng update command returns 
![image](https://user-images.githubusercontent.com/9264813/110427762-3d993080-80ce-11eb-94e2-89c4a8beaf1f.png)
the highlighted should be @angular/http

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by alan-agius4** [comment]
Please be aware that `@angular/http` is no longer supported. Please use `@angular/common/http` instead https://angular.io/guide/http
