### ISSUE TITLE
CVE-2021-28092 in is-svg by cssnano

### ISSUE THREAD

**Issue by SymbioticKilla** [angular/angular-cli#20317]
Hi,

I have got no positive answer in cssnano repo. Perhaps it is important to mention it here.

https://github.com/cssnano/cssnano/issues/1018
https://github.com/cssnano/cssnano/issues/1019

```
`-- @angular-devkit/build-angular@0.1102.2
  `-- cssnano@4.1.10
    `-- cssnano-preset-default@4.0.7
      `-- postcss-svgo@4.0.2
        `-- is-svg@3.0.0 
```

**Comment by alan-agius4** [comment]
In Angular CLI `postcss-svgo` is disabled and hence this vulnerability cannot be exploited. Also, the mentioned exploit reference is for server environments which generally don't expect Angular CLI to run in.

In many cases these advisories should be taken with a pinch of salt.

That said, once a new version of CSSNano is released we will update, other than that these is not much we can do here.

**Comment by stanislavgeorgiev** [comment]
@alan-agius4 please note that there's an [open defect in CSSNano](https://github.com/cssnano/cssnano/issues/1030) regarding the same CVE. The issue was just closed so adopting that new version should resolve the following complaint from GitHub:
![image](https://user-images.githubusercontent.com/1253469/113761741-cf07bc80-96e5-11eb-9261-598011ef9e70.png)

I think an issue marked with `High severity` should be taken into consideration and addressed by the Angular team. We're already using Angular 11.2.7

**Comment by alan-agius4** [comment]
Addressed via https://github.com/angular/angular-cli/pull/20458
