### ISSUE TITLE
Docs: provide info on how to determine if a PR is released

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular-cli#20325]
Please provide some info in the README.md letting people know how to determine if a PR is released, and if so, what version of Angular has it.

For example, I'm trying to determine if a [PR 20172](https://github.com/angular/angular-cli/pull/20172) that closed issue #18398 is released. It's unclear to me if I can use any of the labels attached to the PR to determine this.

This could probably be applied to all angular/ packages.

**Comment by alan-agius4** [comment]
You can either use the changelog, or from GitHub UI you can view which releases the commit is included in, by open the commit itself. example open https://github.com/angular/angular-cli/commit/e1b3ee6f58fa50d63da38042020740a52e5a71cd and check the tags.

A better way instead of documented the above mentioned GitHub functionality, would be to post a notification in the issues. This request is currently being tracked here: https://github.com/angular/angular/issues/39864

**Comment by DmitryEfimenko** [comment]
Thanks for the info! I didn't know about the tags. The automatic notification in the issues would definitely be best! I'm glad this is tracked.

**Comment by clydin** [comment]
That particular PR is in 11.2.3 and 12.0.0-next.3.

**Comment by DmitryEfimenko** [comment]
@clydin the tags on the commit are `v12.0.0-next.5` `v12.0.0-next.4` `v12.0.0-next.3`

I don't doubt that what you're saying is true, but is there a reliable way for me to find out this information?
