### ISSUE TITLE
'Unexpected value 'undefined' exported by the module' * ... in generated typings file. When importing custom library. #10967

### ISSUE THREAD

**Issue by kerolos-sss** [angular/angular-cli#20320]
the same issue as this one 
https://github.com/angular/angular-cli/issues/10967
facing it now 
consider reopening the original or handling it here

**Comment by clydin** [comment]
The referenced issue was opened against a much older version of Angular than the current version (`6.0` vs `11.2`) and there have been significant changes since version 6.0.
If encountering a similar issue, please provide the information present in the issue template including the output of `ng version` and a minimal reproduction if possible.
