### ISSUE TITLE
Document NG_BUILD_PROFILING

### ISSUE THREAD

**Issue by pauldraper** [angular/angular-cli#20336]
I feel like I've discovered some great secret, and I'd like other to know about it.

Environment var NG_BUILD_PROFILING=1 tells you where the precious seconds of your life are going.

**Comment by alan-agius4** [comment]
The main reason why this is not documented AIO because it’s not part of the API and It’s functionality can be changed and/or removed without warning.

In v12 this will only create CPU profiles.

Maybe we should add this somewhere in https://github.com/angular/angular-cli/blob/master/docs/design/build-system.md

**Comment by pauldraper** [comment]
Well, if not build profiling a feature offered by Angular CLI, I suppose I have a feature request :)

**Comment by alan-agius4** [comment]
Actually I was wrong in v12, it doesn’t generate CPU profiles but rather Chrome profile file which includes timings of plugins execution.

**Comment by intellix** [comment]
We're having compilation time issues (100sec rebuilds when serving) and figured we'd try NG_BUILD_PROFILING=1 after seeing it mentioned in another ticket. On my 16gb 2019 MBP it never seems to complete (been running for 1hr so far) with nothing inside the chrome-profiler file:

```
$ NG_BUILD_PROFILING=1 node --max_old_space_size=8192 ./node_modules/.bin/ng build
```

Not sure if there's a middle solution or a way to hook into it to see what it's doing?
