### ISSUE TITLE
Make environment.ts the default file for production

### ISSUE THREAD

**Issue by mdarefull** [angular/angular-cli#20445]
# 🚀 feature request

### Description
By default, environment.ts is used as part of normal (non production) builds and serves and the recommendation is to use environment.prod.ts to replace the base file with prod-specific settings.

On CI/CD environments, the most popular pattern is to place "tokens" in environment.prod.ts that are replaced at build/release time with the environment-specific values and secrets.

This presents several issues:

- Local development configuration code (environment.ts) is checked into the repository by default. Depending on the project size, this could lead to one team member breaking others configurations or mistakenly committing settings that only make sense for the local machine.
- Secrets get checked into the repository by default. Sometimes we use staging/production secrets to connect to external dependencies during development/testing. If we don't remember to revert the changes, secrets could be leaked into the repository.
- Because the build performs a replacement, basic settings that are set during development have to be duplicated in environment.prod.ts and could be missing.
- environment.ts and environment.prod have to be checked into the repository, otherwise, the project won't compile.

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
We should deprecate environment.prod.ts in favor of environment.development.ts and use the latest as a default file replacement while not performing any replacement for prod builds.

Also, a property could be added to support optional file replacements. That way if at build time the file to replace environment.ts doesn't exist, it won't fail (probably a warning).

It would also be good to "strong type" the variable, that way we have a build-time check that all the environments have the required properties set with the expected type.

Additionally, it would be great to consider a "merge" process, where instead of replacing environment.ts by environment.*.ts, the properties would be merged.

I based my suggestions on the way .NET Core app settings are implemented.

### Describe alternatives you've considered
To achieve the above, I had to do this:
![image](https://user-images.githubusercontent.com/22510674/113490593-7f38b380-94a1-11eb-88c3-c384b2268d9d.png)

Which doesn't look nice but works... Also I changed environment.prod.ts to environment.development.ts and added it to git ignore.

**Comment by alan-agius4** [comment]
Hi @mdarefull, 

Thanks for opening this feature request. 

> Local development configuration code (environment.ts) is checked into the repository by default. Depending on the project size, this could lead to one team member breaking others configurations or mistakenly committing settings that only make sense for the local machine.

I am not sure what sort of setting you are referring to here that are different per local machine.

> Secrets get checked into the repository by default. Sometimes we use staging/production secrets to connect to external dependencies during development/testing. If we don't remember to revert the changes, secrets could be leaked into the repository.

File replacements shouldn't be used to store secret tokens as these will be leaked in the final production application bundle and hence it will cause a potential security vulnerability.

> Because the build performs a replacement, basic settings that are set during development have to be duplicated in environment.prod.ts and could be missing environment.ts and environment.prod have to be checked into the repository, otherwise, the project won't compile.

True, but I don't see how a renaming of file will solve this. You can still have a missing key in one of the other configurations. 

> We should deprecate environment.prod.ts in favor of environment.development.ts and use the latest as a default file replacement while not performing any replacement for prod builds.

At this point, changing the names of these files is difficult because by doing so we will invalidate a lot of material such as courses, blogs and books.

> Also, a property could be added to support optional file replacements. That way if at build time the file to replace environment.ts doesn't exist, it won't fail (probably a warning).

The goal is that in the future we move away from file replacements toward tokenization. I don't think that we should add any more features around file replacements.

> Additionally, it would be great to consider a "merge" process, where instead of replacing environment.ts by environment.*.ts, the properties would be merged.

The contents in the file replacement is not restricted to an object literal, it can contain a class, a component or anything really, hence a merge operation cannot be performed.

**Comment by mdarefull** [comment]
> > Local development configuration code (environment.ts) is checked into the repository by default. Depending on the project size, this could lead to one team member breaking others configurations or mistakenly committing settings that only make sense for the local machine.
> 
> I am not sure what sort of setting you are referring to here that are different per local machine.

The easiest example is an API URL. You might have multiple environments, at least 2, you would specify the correct one here. 
A popular pattern is to have 3 environments: your local machine, a staging/test environment, and production. 
During development, your API URL could point to your local machine API or it also could point to staging/test... sometimes... it could even point to production to spot a bug.

> File replacements shouldn't be used to store secret tokens as these will be leaked in the final production application bundle and hence it will cause a potential security vulnerability.

I agree but sometimes we don't have any other options do we? Ultimately, an angular application gets sent entirely in plain text to our users. Where would you include the OpenId settings, analytics instrumentation keys, etc..?

> True, but I don't see how a renaming of file will solve this. You can still have a missing key in one of the other configurations.
It is not a mere file renaming... it is an inversion of the process... Is instead of making environment.ts as the default file for development settings, to make it the default for production... that way local development settings could be kept **local**.

Imagine a bunch of developers, a bunch of environments, and a bunch of APIs. Because environment.ts is the one used for development by default, that's where I would point to the API I'm working with... but the other developers might use different settings... and because environment.ts has to be checked into git it usually leads to one developer committing settings that other developer don't use and might break their setup...

I've worked with angular for several years on small and big teams and they all complain about how difficult, inflexible, and brittle managing settings in angular is. This is merely a simple solution that could help to solve a headache we've been having.

**Comment by clydin** [comment]
Something additional to consider is that the environment files are a build-time configuration method where as something like the .Net `appsettings` files are a runtime configuration method.  It is, however, possible to use runtime configuration methods with an Angular application by leveraging the [APP_INITIALIZER token](https://angular.io/api/core/APP_INITIALIZER) combined with [HttpClient](https://angular.io/api/common/http/HttpClient).  A configuration service could also be created that wraps both the static build-time environment values and any run-time configuration fetching into a common interface that can be injected into the rest of the application.  This later part also has advantages when unit-testing as the configuration service can be mocked to simulate different behavior during tests.

**Comment by mdarefull** [comment]
@clydin thanks for bringing that up. That's where things get tricky... my team initially created an app initialization flow leveraging the APP_INITIALIZER and pulling settings from the server just as you mentioned. We even implemented a merge process similar to .net app settings. Sadly, we faced several issues that led us to move back to the environment.ts approach:
* Not every 3rd party library plays well with delayed initialization. Back then, the root providers were instantiated before APP_INITIALIZER completed and their dependencies weren't resolved until the HTTP response... which required several workarounds that weren't nice.
* Complexity of the app increased, leading to some race conditions, etc.
* The user had to perform an additional HTTP request for the application to be loaded, impacting the UX. Also, this wasn't trivial to cache like how the JS and CSS are.

As for the current environment.ts approach, you mentioned it is a build-time configuration and I think you nailed it there... The most popular pattern I've found to integrate it with CI/CD is to use a token replacement task during release. You set an environment.ts property to like: api: ___MyApi___ and then you replace it during release. 
The problem is that it invalidates the checksum, most noticeably breaking the angular service worker.
The solution? One build CI per-environment :( which not only makes everything harder but kind of breaks the idea that artifacts should be identical across environments.

Can we agree that currently we don't have a nice solution to manage settings in angular?

**Comment by alan-agius4** [comment]
Hi @mdarefull, 

I do agree with you, but what are describing seems to be a seperate features request which should be directed to the Framework to provide an a runtime configure service although it could be argued that the community can take this effort as a seperate project.

That said, I've seen a couple of companies using different runtime configurations solutions successfully, I'll try to explain what I've seen, some of which might be complex or unorthodox. But, want to share what I've seen working in the past. Also typically larger companies tend to avoid built time configuration.

- "Promotion" is typically preferred. The generated application "dist" is promoted from one environment to another without rebuilding `test->staging->production`, this typically works particular well when having a white-label solution where you don't want to build the application X amounts of time to change configuration.

- The above mentioned approach with `APP_INITIALIZER` (https://juristr.com/blog/2018/01/ng-app-runtime-config/) is probably the most widely used. Also  in large application sometimes this can cause performance bottleneck, but typically at this point the application itself starts showing performance issues due to the size of the application. Hence many users opt for SSR and use TransferHttpCacheModule which installs an HTTP interceptor, so that when the application is bootstrapped on the client HTTP requests are retrieved from the transferred state. IE, re-use the calls that have been performed on the server.

-  Another approach that will unorthodox does work is to have a dynamic `script.js`, which can be a coming from an API, that returns a global configuration object. (In this case, typically a service would consume the global configuration object, so not to have any direct interaction).

```html
<script src="/api/script.js"></script>
```
Response
```js
var configuration = { ... };
```

That being said, back to the "original" request here, I do see how renaming a file does address your concerns or issues your are experiencing.

**Comment by clydin** [comment]
Some addition points on the runtime configuration concerns:
* HTTP/2 greatly reduces the overhead of repeat requests to the same origin (HTTP/3 takes this even further but support is limited currently)
* As mentioned, the configuration files should not typically be cached (`Cache-Control: no-cache`) but ETags should be enabled since they will greatly reduce request overhead when a configuration file hasn't changed.
* Using `preload` hints for the configuration file in the index will allow the browser to fetch the the configuration file before the application starts bootstrapping.  This should make the `HttpClient` request almost immediate during the Angular bootstrap phase. (Example: `<link rel="preload" href="configuration.json" as="fetch" crossorigin="anonymous">`)
* Further optimization is possible if HTTP/2 Server Push is available server-side.  Server Push allows the configuration file to be sent at the same time the index HTML is sent to the client; making the configuration file immediately available.

**Comment by alan-agius4** [comment]
Hi @mdarefull, 

Thanks for the feedback. However, mentioned earlier, back to the original request, I don't see how changing the name of the file solve any issue. If you feel otherwise please let me know.
