### ISSUE TITLE
ng build produced module of MIME type application/octet-stream

### ISSUE THREAD

**Issue by mikgross** [angular/angular-cli#20448]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, on version 9.0.7 this worked well.

### Description
When building my project and deploying on App Engine, I receive the following error message:
````
The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
````
While before the MIME type was set correctly, I cloned my project, went back to CLI 9.0.1 and the deployment went fine.

## 🔬 Minimal Reproduction
For me:
1) In the project directory root:
`ng build`

2) in the dist folder (with the relevant app.yaml)
`gcloud app deploy`

## 🔥 Exception or Error
<pre><code>
The server responded with a non-JavaScript MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.6
Node: 15.4.0
OS: linux x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cdk                    11.2.6
@angular/cli                    11.2.6
@angular/fire                   6.1.4
@angular/material               11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.5.5
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by mikgross** [comment]
I believe the ng CLI is working as expected by your team's design, however, how come the MIME type changes and is not "servable" anymore...

**Comment by mikgross** [comment]
Probably linked to https://github.com/angular/angular/issues/30835

**Comment by clydin** [comment]
The MIME types are configured and sent by the server.  Based on the error, most likely what is happening is that the server has been sending incorrect MIME types but the difference is that with the upgrade of the Angular CLI, `module` type scripts are now used to provide newer JavaScript features. When using module scripts, the [HTML specification](https://html.spec.whatwg.org/#fetch-a-single-module-script) mandates that the MIME/content type header for the received data be valid.  The content type that should be sent by the server for JavaScript files (`.js`) is `text/javascript` (or one of the equivalents found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#JavaScript_types)).  Most servers and hosting services will do this automatically as JavaScript files are a common file type.  If using object storage services for hosting, commonly used first-party tools for those services will also set the appropriate type when uploading.  There is no guarantee that a browser will execute a script (module or otherwise) with an invalid content type.  This is especially true when using security-related headers such as `X-Content-Type-Options=nosniff` ([details](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options)).  Even if module scripts are not in use, the correct content type header should still be sent by the server.

Improper or missing content type headers can have a wide range of negative impacts on a site; some of which are security related.  For more information on this please see: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types

**Comment by mikgross** [comment]
Thanks Charles.
I am struggling with something. Why my generated build works on the exact same server with Angular CLI 9 and fails with Angular CLI 11. I run in both cases `ng build` and supposedly the server configuration does not change. Isn't that a regression?

**Comment by clydin** [comment]
The output files generated by the Angular CLI have no control over the MIME types sent by the web server.  The browser in this case is performing required validation of the server's response as per the HTML specification and the web server appears (from the information provided) to be sending incorrect responses.  While this may work today in a browser with classic scripts, there is no guarantee it will work in the future especially if additional security related headers are introduced.

**Comment by mikgross** [comment]
Alright, I guess I will just force the server to specify MIME type of text/javascript for.js files.
