### ISSUE TITLE
Updating to Angular 12.0.0-next.9 causes 100% reproducible WebWorker failure

### ISSUE THREAD

**Issue by lincolnthree** [angular/angular-cli#20553]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Not yet. I updated using `ng update`

### Is this a regression?
Yes

 Yes, the previous version in which this bug was not present was: `12.0.0-next.8`

### Description

 A clear and concise description of the problem...

Run the sample repository. After doing nothing but updating package.json dependencies and re-building, web-workers stop working.

Project was created using:

```ng new
ng generate web-worker app
 ```

The application was then updated to the latest version of Angular pre-release build.

```
git clone https://github.com/lincolnthree/example-webworker-broken-angular
cd example-webworker-broken-angular
npm i
ng serve
```

Then open the console and observe the error message. See https://github.com/lincolnthree/example-webworker-broken-angular/blob/main/src/app/app.component.ts#L18

## 🔬 Minimal Reproduction
https://github.com/lincolnthree/example-webworker-broken-angular

## 🔥 Exception or Error

<pre><code>

ERROR: undefined
</code></pre>
(descriptive, right?)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

sharktop:example-web-worker lincoln$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0-next.9
Node: 14.15.0
OS: darwin x64

Angular: 12.0.0-next.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-next.9
@angular-devkit/build-angular   12.0.0-next.9
@angular-devkit/core            12.0.0-next.9
@angular-devkit/schematics      12.0.0-next.9
@angular/cdk                    12.0.0-next.7
@schematics/angular             12.0.0-next.9
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

Not that I know of. Fails on both latest Chrome and Safari.

**Comment by clydin** [comment]
Version 12 now contains a breaking change related to Web workers due to the upgrade to use Webpack 5 internally.  For details on the breaking change, please see the release notes for the latest prerelease here: https://github.com/angular/angular-cli/releases/tag/v12.0.0-next.9

Essentially, Webpack 5 requires the structure of the parameters for the `Worker` constructor to change as follows:
`new Worker('./app.worker', ...)` --> `new Worker(new URL('./app.worker', import.meta.url), ...)`.

A migration will automatically execute for users upgrading from version 11 or earlier.
The migration can also be manually execute via `ng update @angular/cli --migrate-only update-web-workers-webpack-5`

**Comment by lincolnthree** [comment]
@clydin Interesting, thank you for the pointer/solution/missing info! This helps a TON. It looks like this was omitted from the primary release notes *BREAKING CHANGES* section:

https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes

Seems like something the Angular folks might want to add there! Shout out! Thanks again :)

**Comment by alan-agius4** [comment]
@lincolnthree, it’s listed in the e breaking changes here: https://github.com/angular/angular-cli/releases/tag/v12.0.0-next.9

**Comment by lincolnthree** [comment]
@alan-agius4 Yeah I found it there, just not in the primary release notes that are supposed to aggregate the release notes from all the projects afaik.

**Comment by alan-agius4** [comment]
https://github.com/angular/angular/blob/master/CHANGELOG.md only contains the framework changes.

**Comment by lincolnthree** [comment]
@alan-agius4 Oh, interesting, then am I misunderstanding the package naming for `compiler-cli` `build` and `language-service`?

![Screen Shot 2021-04-18 at 1 18 18 PM](https://user-images.githubusercontent.com/362329/115154409-b209ac80-a048-11eb-9dd4-9d15b6aa76df.png)

**Comment by lincolnthree** [comment]
@clydin  Thanks again for the reply. The issue I've encountered appears to be an incompatibility between Webpack 5/the new Angular build, and the `observable-webworker` library: https://github.com/cloudnc/observable-webworker/issues/67 (Issue I opened on that project with details of the failures, and another code repro branch if you want to see what's happening.)

Simply updating the syntax does not fix the issue, rather exposes a different error, and depending on the _flavor_ of syntax used, actually causes a silent failure where nothing happens whatsoever.

I'm not sure if you feel like this needs to be addressed or even investigated by the Angular team, but I figured you'd want to know that this is indeed causing library-level incompatibilities. 

I don't know enough about Webpack to understand where the fix needs to happen -- so just trying to provide helpful information.

**Comment by lincolnthree** [comment]
@clydin Seems the new minification process is stripping workers of their content when they are executed using @Annotation/decorator hooks rather than directly via a function call in the source js.

The annotation is not enough to keep the minifier from consuming them. See related issue in `observable-webworker` above.

**Comment by clydin** [comment]
In the case of this issue, the decorator from the library is attempting to internally cause a global side effect at runtime.  However, since the class is not referenced within the code, the class appears unused and is removed.  This situation may have unintentionally worked previously inside worker code.  However, now that Webpack 5 Web worker support is used, the full compilation pipeline is leveraged for worker code.  The important aspect of this is that worker code is now optimized equivalently to the main application code wherein a decorator such as used here would also not function. Adding the following to the worker file instead of the decorator will cause the code function:
```
ObservableWorker()(ExampleWorker);
```
Since the class is now referenced within the call expression, it will be retained in the optimized output.

**Comment by lincolnthree** [comment]
@clydin Thanks for the update. This indeed was the issue, makes sense now that you've laid it all out. Again, I really appreciate the attention/followup on this one. It was strange and I am by no means an expert in all this!

Your workaround works, but for anyone else finding this issue, just omit the annotation entirely and use the `runWorker(ExampleWorker)` method provided by `observable-webworker`. 

(WARNING: If you use both the `@ObservableWebworker()` annotation AND the `runWorker(...)` method, your workers will be executed twice per message, which is likely not a good thing.
