### ISSUE TITLE
npm install fails with NPM 7 (Reference issue #19957)

### ISSUE THREAD

**Issue by bipalam** [angular/angular-cli#20590]
Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@11.1.4',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v15.10.0', npm: '7.8.0' }
npm WARN EBADENGINE }

The above errors appears when I try to install ngx-datatable in my ionic project. Install command: "npm install @swimlane/ngx-datatable"

Reference: [https://github.com/angular/angular-cli/issues/19957](https://github.com/angular/angular-cli/issues/19957)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
