### ISSUE TITLE
UnhandledRejection: Cannot read property 'range' of undefined #3588

### ISSUE THREAD

**Issue by mrsants** [angular/angular-cli#20625]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x] serve
- [ x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
run the tests with jasmine / karma on angular version 8 on the current nodejs the following error is shown to me

```
6 04 2021 09:48:56.461:ERROR [karma-server]: TypeError: Cannot read property 'range' of undefined
    at handleRangeHeaders

```
I went to the karma runner but nothing to find a solution, if I run with nodejs 10 there is no problem

 Your Environment
angular 8.2.14
nodejs v15.7.0
karma: 4.1.0
karma-jasmine: 2.0.1

**Comment by clydin** [comment]
Unfortunately, Angular 8.x is no longer supported.  Please consider updating to a newer, supported version.  If the issue is still present after updating, please open a new issue detailing the problem and versions used.
For additional information regarding supported versions, please see https://angular.io/guide/releases#support-policy-and-schedule
