### ISSUE TITLE
angular.json gets auto updated in angular 10

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#20697]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

yes

### Description

![image](https://user-images.githubusercontent.com/36756050/117117592-5ad83b80-adad-11eb-8f15-a85ea9563596.png)

## 🔬 Minimal Reproduction

1.	Create a new Angular application using Angular CLI command – “ng new my-app”.
2.	Install Angular EJ2 packages using schematic command- “ng add @syncfusion/ej2-angular-grids” in cli app.
3.	Now you can see the style reference link is added in styles.css & angular.json file.

## versions

"@angular-devkit/build-angular": "~0.1000.5",
    "@angular/cli": "~10.0.5",
    "@angular/compiler-cli": "~10.0.6",

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , any suggestons

**Comment by alan-agius4** [comment]
@kumaresan-subramani, this looks like it being done by `@syncfusion/ej2-angular-grids`.

**Comment by kumaresan-subramani** [comment]
Yes @alan-agius4 

Using below schematics scripts

https://unpkg.com/browse/@syncfusion/ej2-angular-grids@19.1.59/schematics/ng-add/schema.json 

https://unpkg.com/browse/@syncfusion/ej2-angular-base@19.1.58/schematics/ng-add/theme.js


I questoin is why it is not workign for angular-cli latest

**Comment by alan-agius4** [comment]
@kumaresan-subramani, what is the error that you receiving? Can you please update the description and providing all the important information.

Thanks.

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , 

we haven't face any error on latest. But schema updation not working in latest cli so i got confused.

 is there anything done from angular end to prevent this schema updatoin

**Comment by alan-agius4** [comment]
> But schema updation not working in latest cli so i got confused.

I am not following what you are reporting. Please clarify the issue and provide the appropriate details. 

- What schema are you referring to? Are you referring to the `angular.json` workspace configuration file?
- In the issue template the `ng version` output indicated that you are using version 10, however in your comments, many times you are stating you are using the latest. (currently 11).

I gave this a try locally using version 12 and I can see the below errors, this is a caused because this schematic is used private APIs which have been removed. Anything under `@schematics/angular/utility` is considered as private and can be removed in any version without warnings.

```
ng add @syncfusion/ej2-angular-grids
ℹ Using package manager: npm
✔ Found compatible package version: @syncfusion/ej2-angular-grids@19.1.59.
✔ Package information loaded.
✔ Package successfully installed.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
```

**Comment by kumaresan-subramani** [comment]
Thanks @alan-agius4 , 

my confusion gets cleared 

>this is a caused because this schematic is used private APIs which have been removed. Anything under @schematics/angular/utility is considered as private and can be removed in any version without warnings.
