### ISSUE TITLE
Angular 12 *.mjs files webpack 5 problem

### ISSUE THREAD

**Issue by rudyhadoux** [angular/angular-cli#20785]
Hi

There is a big problem with webpack 5 because *.mjs files are rejected for the compilation.

The error message is :
**Did you mean 'index.mjs' ?
BREAKING CHANGE: The request './utilities' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').**

**Comment by alan-agius4** [comment]
In `.mjs` files or `.js` files with a package.json with `"type": "module"` imports need to be specified with an extension. 

In Webpack 4, this was not enforced since this was still an experimental feature in Node.JS, however since now this is a standard it is being enforced and error out when encountered incorrect packages.

**Comment by rudyhadoux** [comment]
Closed but without workaround.
