### ISSUE TITLE
Unnecessary warning message <DON'T USE IT FOR PRODUCTION!>

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular-cli#20799]
# 🚀 Feature request

- [x] serve

### Description
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************

### Describe the solution you'd like

Showing the above warning message was discussed in some previous CLI versions, and it was agreed that it's a useless thing. It is back in V12. Why? We're not in a kindergarten.

If you think that it's necessary for newcomers, introduce a flag to allow us to disable it, please.

**Comment by clydin** [comment]
That warning has been in continuous existence since version 1.0 (~5 years ago).  It is only shown when the development server is executed with production-like options (e.g., script or style optimizations). Using such options are generally not  recommended during local development as they will greatly increase rebuild times. As a result, users typically will rarely see the warning.

Can you provide links to the previous discussions? An initial search of old issues was unsuccessful.

**Comment by mlc-mlapis** [comment]
@clydin Ops, then there is something strange with my case because that warning appears on `ng serve` (`nx serve`) and not `ng build`. Before the V12 update, everything has been working correctly, so I need to discover what is different and what happened.

It looks like that even with `ng serve` > the whole build with a complete optimization is done.

**Comment by mlc-mlapis** [comment]
@clydin The problem was probably in using `ng update` instead of `nx migrate latest` that led to a wrong `angular.json` configuration.
