### ISSUE TITLE
add --ignore-space to ng init d (diff) command

### ISSUE THREAD

**Issue by bougnat12** [angular/angular-cli#2083]
This is not an issue but a feature request.

The aim is to avoid to lost a lot of time when migrating from angular-cli version to a new one only because there is a lot of diffs due to spacing (indentation of 2 or 4 spaces for example).

I suggest to add an `--ignore-space` option (or `--ignore-diff-space`) to the **ng init** command to resolve this issue.

**Comment by Kiougar** [comment]
@bougnat12 @filipesilva 
I have made a [pull request](/kpdecker/jsdiff/pull/153) to the `jsdiff` module, which is used to generate the diff. When that pull request is accepted I would gladly create a pull request to this repo to add the `--ignore-space` option.

Another option I would also suggest is `--ignore-line-endings`. That way the diff is more accurate and does not display every line as changed.

Maybe the functionality of these two options should be merged into one?

What do you think?

**Comment by Kiougar** [comment]
@filipesilva 
`jsdiff v3.2.0` has been released that includes my previously mentioned pull request.

Should I proceed with a pull request in this repo that adds the --ignore-space option?

**Comment by filipesilva** [comment]
Heya @Kiougar, thanks for the work getting those features into jsdiff! I would appreciate a PR here to use it, yes. 

Unless there are strong opinions otherwise, my instinct says to just default to `--ignore-space` and `--ignore-line-endings`, without presenting the options even. It's also easier to implement this way.

**Comment by Kiougar** [comment]
Hey @filipesilva.

I'm not sure if we should default to `ignore-space` since the `ignoreWhitespace` option of the `diff` module removes the formatting of the code when it is outputted to the console (see below for sample output).
I personally do not care about the formatting, since it is only a visual issue; but it might be misleading to some people, that when accepting the differences the new file would lose the formatting.

Also, the `ignore-line-endings` _(which AFAIK the `diff` module does not support - correct me if I'm wrong)_ has to be solved with the following "trick":

* Use `.replace(/\r\n/g, "\n")` on both strings that need to be compared so that they have the same line endings.

The `ignore-line-endings` can be implemented by default since I don't see any scenarios that it might not work properly.



---
**Here is an example of the output with `ignore-line-endings` and `ignore-space`:**

### Old file contents:
```javascript
import { AppModule } from './app/';

if (environment.production) {
  enableProdMode();
}
if (a) {
  if (b) {
    func();
  } else {
    func2();
  }
} else {
  func3();
}
```
### New file contents:
```javascript
import {AppModule} from './app/';

if (environment.production) {
    enableProdMode();
}
if (a) {
    if (b) {
        func1();
    } else {
        func2();
        func21();
    }
} else {
    func3();
}
```
### createPatch output:
```
Index: filename
===================================================================
--- filename
+++ filename
@@ -1,14 +1,15 @@
-import { AppModule } from './app/';
+import {AppModule} from './app/';
 
 if (environment.production) {
 enableProdMode();
 }
 if (a) {
 if (b) {
-func();
+func1();
 } else {
 func2();
+func21();
 }
 } else {
 func3();
 }
```
[source](https://runkit.com/kiougar/58638db6f764a30014e02ec0)

**Comment by hansl** [comment]
We're getting rid of `update` and `init` because they won't be needed after the release. They were temporary tools that were useful during the rough transition from beta, and going forward the only things needed for upgrading from 1.0.0 to 1.0.1 will be to `npm install`.
