### ISSUE TITLE
Angular 12.0.1 dropped support for node < 12.17

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular-cli#20863]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.0.0

### Description

[SassWorkerImplementation](https://github.com/angular/angular-cli/commit/b89fdc36123e401a2df11b59b477d842fc8cec15) dropped support for node < 12.17

It passes `transferList` into `Worker` constructor ( https://github.com/angular/angular-cli/commit/b89fdc36123e401a2df11b59b477d842fc8cec15#diff-6f1d85ee071c6e16d742bed5b1c832894a14dc4c9452f0bd6b95e3b61e5d1b17R108-R111 ). 

Support for that was added in node 12.17 ➡️  https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2020-05-26-version-12170-erbium-lts-targos

Upgrading to node 12.20.0 solves the issue, but it wasn't mentioned in the CHANGELOG.

## 🔥 Exception or Error

<pre><code>TypeError: MessagePort was found in message but not listed in transferList
    at new Worker (internal/worker.js:167:17)
    at SassWorkerImplementation.createWorker (/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:96:24)
    at SassWorkerImplementation.render (/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:62:40)
    at Object.loader (/node_modules/sass-loader/dist/index.js:46:3) {
  code: 'ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST'</code></pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 12.0.1
Node: 12.16.1
Package Manager: npm 6.13.4
OS: darwin x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1200.1
@angular-devkit/build-angular              12.0.1
@angular-devkit/core                       12.0.1
@angular-devkit/schematics                 12.0.1
@nguniversal/express-engine                11.2.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        12.0.1
rxjs                                       6.6.7
typescript                                 4.2.4</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
We’re sorry for any inconvenience this may have caused. After reviewing the issue, we considered adjusting the implementation. But unfortunately another Node.js version issue complicates the matter. Transitive dependencies (potentially several levels deep) are starting to use the package.json exports field with features only available in 12.20.  Since these dependencies cannot be pinned and their presence can cause failed builds, the CLI will need to set the minimum to 12.20 to ensure working builds.  This recently (yesterday) happened with the “colord” package which thankfully updated their package.json to remove the newer feature usage even though the result is significantly more verbose and harder to maintain.  However, usage of the exports field and all its features will only accelerate moving forward.

**Comment by kamilchlebek** [comment]
@clydin Thank you for comprehensive explanation. 

btw. You may want to update node version in the [README.md](https://github.com/angular/angular-cli/blob/master/README.md) as well:
> 3. Make sure that you have Node 12.14 or 14.0 installed. See instructions here.
