### ISSUE TITLE
SassError: expected ";" (before !important when using Tailwindcss)

### ISSUE THREAD

**Issue by martinsotirov** [angular/angular-cli#20922]
# Bug Report

### Affected Package
``` "@angular/core": "^12.0.1",```

### Is this a regression?

Yes. Tailwind used to work perfectly fine in Angular 11 with the `node-sass` based `sass-loader` and `postcss-loader` in a custom `webpack.config.js`.

### Description
I'm trying to migrate my app from Angular `11.2.3` to `12.0.1` and along with it Tailwind from `1.4.5` to `2.1.2`. It's nice that with Angular 12 I don't need a custom `webpack.config.js` to load `Tailwind` but the switch to dart-sass (I assume) is messing with the loading of my scss files. It doesn't understand `@apply bg-green-500 !important;` while `@apply bg-green-500;` and `background: green !important;` work fine.

## Minimal Reproduction

[https://angular12-tailwindcss-bug.stackblitz.](https://angular12-tailwindcss-bug.stackblitz.io)

## Exception or Error
<pre><code>
./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: SassError: expected ";".
  ╷
9 │   @apply bg-green-500 !important;
  │                      ^
  ╵
  src/styles.scss 9:23  root stylesheet
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by clydin** [comment]
`@apply` is a defunct (https://caniuse.com/css-apply-rule) CSS standard proposal.  From the [abandoned proposal](https://tabatkins.github.io/specs/css-apply-rule/), it appears that the rule was intended to only accept the name of a CSS custom property.

For the related Sass functional, Sass provides the `@mixin` and `@include` At-rules (https://sass-lang.com/documentation/at-rules/mixin).

**Comment by clydin** [comment]
If this is something that you believe Sass should be handling differently, please consider opening an issue with the Sass project: https://github.com/sass/dart-sass

An additional option would be to use CSS for this stylesheet instead of Sass which would remove the Sass compiler from processing the stylesheet and generating the build failure.

**Comment by martinsotirov** [comment]
Like I said in my issu edescriprion, `@apply` by itself works perfectly fine. It's the combination of `@apply` and `!important` that seems to be messing with the compilation of my css. Angular with Sass and Tailwindcss via PostCSS is a pretty popular combination which used to work up until Angular 12. By that definition it's a regression.

**Comment by alan-agius4** [comment]
@martinsotirov, @clydin pointed out this syntax is not recognised by the dart-sass pre-processor. You can test this here https://www.sassmeister.com/ and choose dart-sass as your pre-processor.

Therefore, If you feel like this should be handled differently please file an issue in their project: https://github.com/sass/dart-sass. 

That said, the `@apply` proposal has been abandoned, due to being generally a bad idea. See http://tabatkins.github.io/specs/css-apply-rule & https://www.xanthir.com/blog/

**Comment by martinsotirov** [comment]
@alan-agius4, @clydin, thanks for the suggestions. I guess I'll have to remove Sass entirely from my build chain for Tailwind to work properly in Angular 12. Should be doable without a major refactoring if I use a combination of PostCSS plugins that emulate most of the Sass syntax I use.

On the topic of `@apply`, I don't think it's going to disappear any time soon with or without W3C support. Tailwind is just getting too big.

**Comment by clydin** [comment]
From looking through the Tailwind documentation, it appears this is an expected interaction between Tailwind and Sass.  The Tailwind documentation has a specific section on this exact issue: https://tailwindcss.com/docs/using-with-preprocessors#sass

Essentially instead of `@apply bg-red-500 !important;`, use `@apply bg-red-500 #{!important};`;

**Comment by martinsotirov** [comment]
No idea how I missed that interpolation trick but thanks for digging it up, @clydin!
