### ISSUE TITLE
SassError: SassError: Undefined mixin. sass variable or mixins not getting identified in Angular 12 scss application.

### ISSUE THREAD

**Issue by digish777** [angular/angular-cli#20924]
SassError: SassError: Undefined mixin. sass variable or mixins not getting identified in Angular 12 scss application.

My _mixins.scss file content:

@mixin horizontal-box {
  display: flex;
  flex-direction: row;
}

@import url("../app/_mixins.scss");

.result-box {
  @include horizontal-box;
}

this is a freshly created angular 12 application with commmand: ng new angular12app

it straight away gave the error on command: ng serve

./src/app/app.component.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: SassError: Undefined mixin.
  ╷
4 │   @include horizontal-box;
  │   ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\app\app.component.scss 4:3  root stylesheet

I lost 3 hours on this issue. Did not expect this from Angular.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by clydin** [comment]
@spock123 The issue you are describing is a defect within the CSS optimizer (`cssnano`) and has been fixed in its latest version (5.0.4).  You should force an update of the package by removing node_modules and the lock file and then reinstalling.

@digish777 Based on the Sass documentation for `@import` (https://sass-lang.com/documentation/at-rules/import#plain-css-imports), the above code is expected to fail.  Sass treats a `url()` based `@import` as a standard CSS import.  Changing the import to `@import "../app/_mixins.scss";` will cause Sass to process the import.

**Comment by spock123** [comment]
@clydin  thanks for the info! I'll definitely try that! cheers

**Comment by digish777** [comment]
@alan-agius4 . I have seen You closing issues with out resolving. Hopefully Google is aware of what You are doing here.

**Comment by digish777** [comment]
@clydin the solution does not work.

**Comment by digish777** [comment]
@alan-agius4 It is not right to close an issue without checking, If the issue is resolved.

**Comment by alan-agius4** [comment]
@digish777, it’s not right, to open an issue and completely ignoring the issue template.

Please your time and fill in all the required information.
