### ISSUE TITLE
Forced version of the webpack

### ISSUE THREAD

**Issue by janousek** [angular/angular-cli#20977]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  <12.0.0

### Description

In angular 12.x.x version of the webpack is forced by the package.json in @angular-devkit\build-angular
https://github.com/angular/angular-cli/blob/638344afe1774ea5573b26def4b2a41cc14f6b8b/packages/angular_devkit/build_angular/package.json#L71
https://github.com/angular/angular-cli/blob/2f295963d7f23f0cbf204bba18af521df73e3ef0/packages/angular_devkit/build_angular/package.json#L71

Is there any reason not to use minor release? Like this:
```
"webpack": "^5.36.2",
```

If we install different version of the webpack in our project it is installed twice. And it causes version mishmash and produces errors like this: "TypeError: The 'compilation' argument must be an instance of Compilation..."

There is already reported several bugs caused by this:
https://github.com/angular/angular-cli/issues/20768
https://github.com/angular/angular-cli/issues/20773
https://github.com/angular/angular-cli/issues/20786

## 🔥 Exception or Error

<pre>TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks ....................<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @janousek,

We pin all of our versions to ensure that the Angular CLI doesn't break when a 3rd party direct dependency cut a release and therefore provide a more stable tool.

Over the years, a number of packages had breaking changes / serious regressions including in patch versions which otherwise would have broke a lot of users. Webpack is one of these packages, which even recently in version 3.37.1 had a regression which would have cause all Angular CLI projects stop work if consumed.

Regarding the mentioned issues, those errors seems to be caused by NPM 7 and a defect in its module hoisting logic. We did notice NPM about this issue and are waiting for a resolution.
