### ISSUE TITLE
Initializing string properties with Observables ...

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#21024]
So I have a string property like this:

```
  @Input()
  backgroundImageURL!: string | null 
```

It's initialized with an `Observable` in the template ... So the type has to be declared `string | null` ....  Since the `Observable` could emit null ... but I'm also using the non null assertion operator to say that it will not be null .... Otherwise Angular complains ...

So the whole thing is a bit "Strange ...".  I think I liked the way this worked before a lot better ... I never had any issues and now there's all this "Strict" type checking that feels like a double bind in many cases ...

**Comment by alan-agius4** [comment]
@fireflysemantics, next time please follow the issue template, issues which don’t follow the template will be closed.

Also, kindly provide some code that illustrates the problem. Thanks.

**Comment by clydin** [comment]
This is not Angular specific and rather is standard TypeScript behavior.
If `backgroundImageURL` does not have an initializer and is not set in the constructor, then the field will initially be `undefined`.  If it can also be set to `null` then the correct type for the field would be `backgroundImageURL: string | null | undefined` or `backgroundImageURL?: string | null`.  Removing the `null` emit case would reduce this to only `backgroundImageURL?: string` (assuming `null` does not have a differing contextual meaning in this case).
The important aspect here is that the strict typing helps prevent errors within the logic of the component since the value can also be `undefined` which may not be accounted for within the component. Failure to set the input in a template or incorrectly set the input could trigger these cases.

**Comment by clydin** [comment]
Also, if preferred (but not recommended), the strict settings can be disabled or otherwise adjusted within a specific project.

**Comment by alan-agius4** [comment]
This is strandard TypeScript behaviour, and by initializing a variable in the template it doesn't guarantee that the variable has a value in the all parts of the class life-cycle such when accessed in the `constructor`. Also, technically all inputs are optional, and therefore their value be can `undefined`.
