### ISSUE TITLE
Add flag to create new component / directive / pipe as module (SCAM)

### ISSUE THREAD

**Issue by mxxlrfu** [angular/angular-cli#21053]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] generate

### Description

I see more and more people adopting the Single-Component-As-Module approach. What do you all think about maybe adding some `--as-module` flag when generating new component, directive or pipe? It's a hot topic, it dramatically decrease bundle size, resolve the shared/core-shared module struggle on large projects and help avoiding to break SOLID principles.

### Describe the solution you'd like

Extend current `ng generate` behaviour with a flag to generate new component / directive / pipe wrapped into a single module. It wouldn't introduce any breaking changes and would be profitable if you care about architecture & of course, performance.

### Describe alternatives you've considered

It's ok to do it manually though it would be a valuable shortcut.

### If I can PR that?
- [x] YES!

**Comment by alan-agius4** [comment]
Thanks for offering to create a PR for this @mruffieux. Let's wait to see what's the feedback on this request from the community first though.

**Comment by tayambamwanza** [comment]
@mruffieux 100%, doing, it manually isn't tough but generating it would save a lot of time.

I would suggest instead of --as-module, maybe the flag option would be --inlineModule

Also then it would automatically --skipImport

e.g.

ng g c example --inlineModule

```ts
import { CommonModule } from '@angular/common';
import { Component, NgModule, OnInit } from '@angular/core';

@Component({
  selector: 'app-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.css']
})
export class ExampleComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}



@NgModule({
  declarations: [ExampleComponent],
  imports: [CommonModule],
  exports: [ExampleComponent]
})
export class ExampleComponentModule {}

```
If you need a routed component or modal component it would be as easy as writing

ng g c example --inlineModule --export=false --skip-selector

**Comment by LayZeeDK** [comment]
ng generate component --scam

SCAM is shorthand for Single-Component Angular Module 😃 They are also okay to export a single directive or a single pipe despite their name.

**Comment by wizardnet972** [comment]
> ng generate component --scam
> 
> SCAM is shorthand for Single-Component Angular Module 😃 They are also okay to export a single directive or a single pipe despite their name.

@LayZeeDK, I agree it should be `scam` flag. Because you called it first in your talk. I also suggest calling it `scam` as you do :)

https://github.com/angular/angular-cli/issues/21574

I hope the team implements it soon. I think it is the right way for now to make components tree shakeable.

**Comment by tayambamwanza** [comment]
> ng generate component --scam
> 
> SCAM is shorthand for Single-Component Angular Module  They are also okay to export a single directive or a single pipe despite their name.

--scam is good too since it most popular.

**Comment by tayambamwanza** [comment]
@artaommahe curious about the reason for thumbs down?

**Comment by e-oz** [comment]
It also could be “ng generate component-module”, and with shortcuts, it would be just “ng g cm”.

Doesn't matter how exactly, but would be great to generate a scam-component with OnPush strategy using one line.

**Comment by NetanelBasal** [comment]
You can use this schematics for now:
https://github.com/ngneat/scam

**Comment by mruffieux** [comment]
I agree `--scam` is definitely the most popular @LayZeeDK but it may be a misleading term since we may generate directives and pipes as well.

@alan-agius4 let me know if we're good to go and what flag seems to be the best fit.

Regarding the change detection strategy, it's already there https://angular.io/cli/generate#component. We're not gonna alter the normal behaviour of the `ng -g component` command, we'll just trigger an extra schematic that will wrap the new component.

**Comment by alan-agius4** [comment]
We did discuss this during our last meeting.

Before committing in increasing the public API which would need to be supported and in the CLI for several major version. We'd like to understand a bit better the impact of [Optional NgModules](https://angular.io/guide/roadmap#simplified-angular-mental-model-with-optional-ngmodules) on this. The ideal behind optional NgModule is that "SCAM" will happen automatically.

**Comment by e-oz** [comment]
but optional ngModules will be here in a very far future, while many of us are using single-component modules right now :)

**Comment by tayambamwanza** [comment]
@alan-agius4 I think it's worth considering just for dev experience,  having a flag for those of use who do put the module and component in the same file, we have inline templates, inline styles and now inline modules would be great too.

As @e-oz it is also something that can be done at a lower cost (my assumption of course) then adding the optional modules feature, we are using it already, would be appreciated to make life easier for use instead installing third party or typing out ng module repeatedly.

**Comment by alan-agius4** [comment]
As stated, before we commit to this, we'd like to understanding the impact of optional NgModules a bit better. Work on optional NgModules is already in progress, that said there is no definite date for when this will be rolled out.

Adding a new option is trivial, but such option will need to be supported for at least 2 major versions, potentially such option will be included in training materials and other tutorials and therefore before committing in adding a new option we need to make sure that this will stay there for the long run as otherwise if we remove it, we'll invalid education materials. 

The schematic from @NetanelBasal, https://github.com/ngneat/scam provides a good enough alternative for the time being. until we decide how to proceed.

**Comment by mruffieux** [comment]
@alan-agius4 I have to second you on this. Discussions around Optional NgModules has been a up for a while now.

The scam approach will become irrelevant as soon as they will be released. As we already know days are counted, I don't think we should keep this discussion active.

There are alternatives to this as @NetanelBasal pointed out and that's fine.

At last, `ng generate module myModule` will generate a scam by default. Then apply the appropriate changes to have working for you.

**Comment by tayambamwanza** [comment]
@mruffieux Concerning the last liine, are you saying that's what **ng g m** will do by default when optional ng modules feature is released, or that it already does that?

I would love this feature but if optional ng modules isn't that far off I guess the wait will be bearable, otherwise it will be harder to swallow that this was closed down lol, either way trust the teams judgement.

**Comment by dgp1130** [comment]
We think this use case is better handled by standalone components, which fills the same need with less tooling requirements. It's in developer preview right now, and we think it's the right solution to this particular problem: https://angular.io/guide/standalone-components
