### ISSUE TITLE
Allow --nospec flag for services

### ISSUE THREAD

**Issue by cburgdorf** [angular/angular-cli#2108]
With https://github.com/angular/angular-cli/commit/a85a507a82c07f6f4d67343601469ad283316f7c a `--nospec` option was introduced to generate components without tests.

In case there isn't a specific reason why this option shouldn't be valid for services as well, I propose to implement it for consistency.

//cc @PascalPrecht

**Comment by Brocco** [comment]
I agree with this as well, but would also expand it to not just services, but also directives, pipes, classes.

**Comment by filipesilva** [comment]
All for it myself.

**Comment by niklas-dahl** [comment]
When adding the `--nospec` flag to all generate commands, wouldnt it make sense to add it to `ng new` aswell, just like it works with `ng new sassy-project --style=sass`?

`ng new notests --nospec` would then omit the generation of the `e2e` folder, `karma.conf.js`, `protactor.conf.js`, `src/test.ts` and `src/app/app.component.spec.ts`.

Additionally it could set a flag in the `angular-cli.json` so that all `generate`commands know to not generate a spec file.

Could look like this:

`
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "generateSpecs": false
  }
`

I know I am a terrible person for asking for this, but sometimes the test stuff just gets in the way.
