### ISSUE TITLE
using esbuild-loader within the angular cli webpack configuration

### ISSUE THREAD

**Issue by aelkoussy** [angular/angular-cli#21205]
# 🚀 Using esbuild-loader within the angular cli webpack configuration

### Command (mark with an `x`)
I think this will be relevant for all the commands

### Description

Angular run and build can be really slow for large projects with many libs and dependencies
Esbuild provides very high speed but in another issue, it was rejected as angular-cli still relies heavily on webpack:

The related issue is this: https://github.com/angular/angular-cli/issues/18395

### Describe the solution you'd like

We can just adjust the webpack configuration under the hood to use the esbuild-loader plugin and this will probably provide a speedup that might be 5x to 10x without major changes

https://github.com/privatenumber/esbuild-loader

### Describe alternatives you've considered

I tried to override the webpack configuration that is used by Angular cli but that didn't work out, however I tried this for one part of the project and the speedup was 10x for using this in webpack configuration (without any other change)

**Comment by artaommahe** [comment]
> esbuild only supports a subset of tsconfig options (see TransformOptions interface) and does not do type-checks

so you're completely missing code and templates typechecking. You can achieve almost same performance boost just by disabling ts typechecking.

**Comment by alan-agius4** [comment]
Thanks for showing interest in this, in version 12.2 we did introduce a JavaScript optimization pipeline using esbuild and is definitly promising. You can read more about this here https://github.com/angular/angular-cli/pull/21163

That being said one of the reasons why esbuild is faster to transpile TypeScript is indeed because it doesn't do any type-checking.

We will continue evaluating esbuild and other tools periodically.

**Comment by aelkoussy** [comment]
@alan-agius4 great, thanks for the quick response and good luck with the PR, looks promising :)
