### ISSUE TITLE
Make angular workspaces the default in v13

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21218]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently, there are multiple ways to setup angular source code.
```shell
# Preferred default
❯ npx @angular/cli new web-apps --create-application false
❯ cd web-apps && yarn ng generate application command-center 
```

```shell
# Current Default
❯ npx @angular/cli new command-center
```

### Describe the solution you'd like

Ideally, there should be one approach for generating both application and library. 
- I recently opened an issue against https://github.com/angular-eslint/angular-eslint/issues/462 repo. Having multiple approaches requires library maintainers to do additional work. 
- What if a developer initially used this command `npx @angular/cli new command-center` and now has to develop another application. Usually, the common infrastructural code(error handling, auth session, interceptors) should be extracted to some library (say, `@company/core`) and be re-used by both the applications. This becomes non-trivial if initially angular workspace was not created. 
<img width="597" alt="ui_monorepo_v13" src="https://user-images.githubusercontent.com/13006107/123527127-02396680-d6ab-11eb-8f58-d81f10b688e0.png">

### Describe alternatives you've considered
N/A

### Migration
- I understand, this could be a significant undertaking by the CLI team. Therefore, the team could continue supporting current approach. With v13, the CLI can by default generate workspace file and then application/library. This would mean, library maintainers(libraries which support `ng add library`) supporting Angular v13 have to code against one approach, thus lessening their workload.

**Comment by alan-agius4** [comment]
I think there are a number of things to also consider here.

- The majority of new users typically won’t need need a monorepo style workspace.
- Changing this behaviour will be a significant breaking change as it will invalidate a lot of educational material.
- Schematic author typically don’t have to worry about whether the structure of the workspace is a multi repo or monorepo style.   The issue referenced with eslint is quite an edge case, due to the root level base configuration file.

**Comment by prabh-62** [comment]
> I think there are a number of things to also consider here.
> 
> * The majority of new users typically won’t need need a monorepo style workspace.
> * Changing this behaviour will be a significant breaking change as it will invalidate a lot of educational material.
> * Schematic author typically don’t have to worry about whether the structure of the workspace is a multi repo or monorepo style.   The issue referenced with eslint is quite an edge case, due to the root level base configuration file.


* Agreed the majority of new users won't need monorepo, but an angular workspace with just one application under `projects` cannot be called a monorepo. It would be a monorepo once new user creates another library/application in same workspace
* Agreed, but there also have been similar broad changes in the past (`.angular-cli.json` to `angular.json`)
* Schematic author: Do you think if there is only one way to create application(workspace style), James Henry would have enocuntered that issue?


By the way, why do we recommend workspace style approach for libraries? 
https://angular.io/guide/creating-libraries#getting-started
<img width="863" alt="ng_lib_workspace" src="https://user-images.githubusercontent.com/13006107/123545514-60575f80-d726-11eb-9842-9b1f1b9e22a3.png">
and perhaps, we can do the same thing for applications.


Another question:
```shell
❯ npx @angular/cli@12 new command-center
❯ cd command-center && yarn ng g app admin-console
```
Will the angular CLI team continue supporting this alternative approach? This becomes confusing for library authors and vscode extension authors, since there is `.browserslistrc` at root and `projects/admin-console/.browserslistrc` inside project and extension authors are not able to figure out if its a workspace or single app. There could be similar instances where some files are at the root which get picked up by vscode extension and applied for all workspaces apps/libs.
<img width="369" alt="ng-app-workspace" src="https://user-images.githubusercontent.com/13006107/123545674-37839a00-d727-11eb-9cc4-0448649330fa.png">

**Comment by alan-agius4** [comment]
Hi @prabh-62,

Thanks for this request, that said following a convo with our devrel we feel that we shouldn't move forward with this proposal. None-the-less, I will answer your questions below;

- Agreed the majority of new users won't need monorepo, but an angular workspace with just one application under projects cannot be called a monorepo. It would be a monorepo once new user creates another library/application in same workspace
> That is true, although having an application down in 2 sub directories when you don't want a mono-repo isn't the most intuitive thing. 
- Agreed, but there also have been similar broad changes in the past (.angular-cli.json to angular.json)
> Indeed and from those changes we did learn that we should be more cautious when doing breaking changes especially when they effect the `ng new` experience. The mentioned changed was also required to introduce multi-project type workspace which in this case the pros outweighed by far the cons.
- Schematic author: Do you think if there is only one way to create application(workspace style), James Henry would have enocuntered that issue?
 > Probably yes, because removing the single project workspace concept will not solve this, since that structure will still need to be supported. That said, users are free to move applications/libraries around example https://github.com/Angular-RU/angular-ru-sdk/tree/master/packages/stream has a library at the root level. While the CLI doesn't generate this out-of-box, this is a perfectly valid supported structure. So a golden rule would be to not assume any particular structure, if you really need to know how is the workspace is structured read the configuration in `angular.json`.
- By the way, why do we recommend workspace style approach for libraries?
> In many cases, when creating a library you'd always want to create an application to run integration and E2E tests.
- Will the angular CLI team continue supporting this alternative approach? This becomes confusing for library authors and vscode extension authors, since there is .browserslistrc at root and projects/admin-console/.browserslistrc inside project and extension authors are not able to figure out if its a workspace or single app. There could be similar instances where some files are at the root which get picked up by vscode extension and applied for all workspaces apps/libs.
> I think the main problem here, is that the mentioned workspace is a mixture of a single and multi project workspace. TypIcally, if you want to create a multi-project repo workspace you start by using `--no-create-application`.
