### ISSUE TITLE
Angular should error when there is no projects key in the angular.json

### ISSUE THREAD

**Issue by EvanCarroll** [angular/angular-cli#21314]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not afaik.

### Description

Projects created with `ng g app qux` return _"Project "qux" does not exist."_ which is obvious.. that's why I'm wanting to create it.

```text
❯ ng g app qux
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
Project "qux" does not exist.
```

## 🔬 Minimal Reproduction

Create a new project with

```sh
ng new foobar --create-application=false
```

`cd` into `foobar` and change `angular.json` to

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
}
```

Now try to run `ng g app qux`

## 🔥 Exception or Error

A warning that your angular.json needs a `project: {}`... or just create it

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: linux x64

Angular: undefined
... 

Package                      Version
--------------------
----------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@angular/cli                 12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
