### ISSUE TITLE
Cannot build with modules only

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#21507]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I guess

### Description

I am trying to build our app for modern browsers only (only type=module) but cannot get it working. Using a fresh ng new does not even work. I have created a browserslist in the root containing only "last 2 chrome versions" and left the target at "es2017" (ng g application did that). Even using "es2015" does not work.

## 🔬 Minimal Reproduction

1. ng new test --defaults --no-create-application
2. cd test
3. ng g application test --defaults
4. echo "last 1 Chrome version" > .browserslistrc
5. ng build
6. cat dist/test/browser/index.html
7. No es6 modules generated

## 🔥 Exception or Error

<pre><code>
None
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.0
Node: 12.22.2
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This has been added in version 13, See: https://github.com/angular/angular-cli/pull/21484

Note: this doesn't mean that the bundle will contain ES6 module syntax to load chunks instead of the the Webpack module loading syntax. ES6 module syntax is still experimental in Webpack https://webpack.js.org/configuration/experiments/#experimentsoutputmodule.

**Comment by alan-agius4** [comment]
This has been added in version 13, See: https://github.com/angular/angular-cli/pull/21484

Note: this doesn't mean that the bundle will contain ES6 module syntax to load chunks instead of the the Webpack module loading syntax. ES6 module syntax is still experimental in Webpack https://webpack.js.org/configuration/experiments/#experimentsoutputmodule.

Just to clarify the request, are you expecting to see ES 6 imports/exports in the bundles?

**Comment by muuvmuuv** [comment]
@alan-agius4 yes I am expecting `<script type=module>` in my index.html but getting `<script defer>` instead.

**Comment by alan-agius4** [comment]
In that case, this has been addressed in version 13 which is currently in prerelease stage via the linked PR above.

**Comment by muuvmuuv** [comment]
Okay, that are good news. Thanks. I will opt-in into the beta once its out and try it. We are using Ionic so backwards comp. is not our focus ^^.
