### ISSUE TITLE
Angular 12: ng build --configuration staging does not generate a production build

### ISSUE THREAD

**Issue by vignesh87ad** [angular/angular-cli#21572]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 
We have setup different environment files with different configurations for each environment and we have been using the angular cli command **ng build --prod -c=<<environment>>** to generate packages for different environments like staging, development, production etc. After updating to angular version 12 and enabling production builds by default, we are unable to generate production builds with the command **ng build --configuration staging**. This command generates a development build using environment.staging.ts file instead of a production build using environment.staging.ts file. Running the command **ng build** correctly generates a production build so we can confirm that production builds are enabled by default. 

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Production by default builds will run the build using the production configuration, or the configuration which is set as the `defaultConfiguration` in `angular.json`.

`—-prod` which is deprecated is just an alias for `—configuration=production`. 

Therefore, in your case since you want to merge two configurations to have the same behaviour as `—prod —configuration=staging` you will need to run the command with the following `—configuration=production,stage`. Where the configurations will be merged from left to right.
