### ISSUE TITLE
NG_BUILD_DEBUG_OPTIMIZE breaks treeshaking

### ISSUE THREAD

**Issue by kkoo95** [angular/angular-cli#21597]
# 🐞 Bug report

### Description

Running an "production optimized" application build (optimizations & build-optimizer turned ON) but with the additional flag NG_BUILD_DEBUG_OPTIMIZE produces a bundles that is not totally tree-shaken. 

Use case consists of an application depending on a simple angular library, and only uses parts of it through routing. If we look at the produced bundles, we can see the unused library exports still being here.

## 🔬 Minimal Reproduction

[https://github.com/kkoo95/ng-issue-repro1.git]()
```
$ npm ci && npm run build-lib
```
And then,
either `npm run build` or  `npm run build-debug` to produce either the standard production bundle or the one using the debug flag turned ON. 

There is also `npm run analyse` for visualizing webpack stats

## 🌍 Your Environment

v12.1.2

**Comment by alan-agius4** [comment]
This is expected since when `NG_BUILD_DEBUG_OPTIMIZE` is used to debug tree-shaking / DCE issues. 

When used minification is not enabled by default and hence unused code is not dropped. If you'd like to minify the code you can use `NG_BUILD_DEBUG_OPTIMIZE=minify ng build`

Note: this API is for internal purposes and it's usage is not supported.

**Comment by kkoo95** [comment]
Thanks, I stepped upon this micro syntax trick just now and was coming back here to close the issue.

> Note: this API is for internal purposes and it's usage is not supported.

no doubt about that. Thanks again
