### ISSUE TITLE
Use existing package.json if it exists in ng new execution directory

### ISSUE THREAD

**Issue by Furry** [angular/angular-cli#21688]
# 🚀 Feature request

### Command (mark with an `x`)

- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I ran into an occurrence where I was using both Tauri Webview for Rust, & Angular for the front-end portion.
To keep my libraries in one place and to avoid file bloat, I tried `ng new src-angular .` hoping it would utilize the package.json & node_modules in the directory I ran the command from, but unfortunately it made a new node_modules and package.json entirely in the generated angular folder.

### Describe the solution you'd like

A good solution in my opinion, would for `ng new projectname .` to use the existing package.json & node_modules folder within the directory the command was executed in (if they exist), if not, carry out normal functionality.

### Describe alternatives you've considered

I am not sure about any viable alternatives to this, as it's pretty specific of a feature.

### Note:
If this feature request is acceptable, I'd be happy to code up the implementation and link a PR for it in this issue!

**Comment by alan-agius4** [comment]
Hi @Furry, 

Thanks for this feature request and offering in implementing this.

I believe that this is quite an edge case and merging the `package.json` is not trivial. Ex: what happens when a package version conflicts, Example `rxjs` exists in the current `package.json` with version `5.0.0`, but the `ng-new` schematic wants to add version `6.0.0` how should such conflicts be handled?

Overall, seeing that this is an edge case and it is non trivial to implement and support it. I don't feel that this warrants to be included in the default Angular `ng-new` schematic. On the other hand this can candidate for a custom schematic.
