### ISSUE TITLE
Re-compilation failed on external import changes

### ISSUE THREAD

**Issue by roman-rr** [angular/angular-cli#21727]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] serve

### Is this a regression?
✍️ Yes, the previous version in which this bug was not present was: **11.0.5**

### Description
✍️ Since i up to 12.x.x version, i got error on re-compile application. 
In angular application I use external import out of project environment and folder. 
```js
import { CupertinoPane } from '../../../cupertino-pane';
```
I serve angular app with `ng serve` and there is no error on this moment. 
Then, i make changes in `cupertino-pane` package and build it again with 
```js
$ cd cupertino-pane
$ gulp build
```
In this time, angular cli successfully see changes and trying to re-compile app. 
Then i got error below.
If i re-run `ng serve` error will disappear. 
What i want is real-time compilation to have ability make changes in external packages. 
I use this in previous versions. 

![ezgif-2-f08d32dd89d3](https://user-images.githubusercontent.com/10646478/132555947-f130c36d-4f2e-4e24-b5d0-9c1f9e53cfe0.gif)

## 🔥 Exception or Error

<pre><code>
Cannot find module '../../../cupertino-pane' or its corresponding type declarations.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.4
Node: 14.17.4
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 12.2.4
... cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.4
@angular-devkit/build-angular   12.2.4
@angular-devkit/core            12.2.4
@angular-devkit/schematics      12.2.4
@schematics/angular             12.2.4
rxjs                            6.6.7
typescript                      4.2.3
</code></pre>

### Prepare workspace
```bash
$ mkdir bug-workspace
$ cd bug-workspace
$ git clone https://github.com/roman-rr/cupertino-pane.git
$ ng new ng-project
```
You must have this folder structure:
```
- bug-workspace
   - cupertino-pane
   - ng-project
```

### Code
Add import to angular project here `/bug-workspace/ng-project/src/app/app.component.ts`

```js
import { CupertinoPane } from '../../../cupertino-pane';
```

### Serve
```bash
$ cd /bug-workspace/ng-project/
$ ng serve
```
On this step you will have success compilation without errors with external package. 

### Catch error
Open new terminal tab and execute
```bash
$ cd /bug-workspace/cupertino-pane/
$ npm i
$ gulp build
```
Now look at first terminal where `ng serve` executed and you will have error. 
Re-execute `ng serve` and error will dissapears.

**Comment by alan-agius4** [comment]
Unfortunately without a reproduction it’s hard to tell what is happening.

Can you please setup a minimal reproduction? Thanks

**Comment by roman-rr** [comment]
@alan-agius4 updated with reproduction steps.

**Comment by alan-agius4** [comment]
The main problem here, is that during the rebuild, in your gulp tasks you are deleting and re-creating files. Typically you'd want to avoid doing that and only emit the changed files when the build is in watch mode as this also helps to reduce the incremental build time of application.

Changes are aggregated to every 200ms https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout, in your case this causes race conditions due to missing files on disk. 

While with your setup it is non trivial to emit only changed files, you can easily update the code to not delete the entire package. (**NB**: for non watch mode, I support you have a seperate task that does clean the dist). 
 
**cupertino-pane/gulp/build-js.js**
```diff
    plugins: [
-      typescript({clean:true})
+      typescript()
    ],
```

**cupertino-pane/gulp/gulpfile.js**
```diff
- gulp.task('build', gulp.series(['clean', 'js', 'prod-source-sourcemap-fix-paths']));
+ gulp.task('build', gulp.series(['js', 'prod-source-sourcemap-fix-paths']));
```

I also noticed that you are building your library using custom gulp tasks, I strongly suggest to use the Angular CLI to build your libraries. You can read more about this here https://angular.io/guide/creating-libraries, otherwise you'd need to keep syncing the changes in the [APF](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) in your custom build. Using the Angular CLI also ensures that you are using the best practices when it comes to building and packaging your library.
