### ISSUE TITLE
Allow forcing colors

### ISSUE THREAD

**Issue by GerkinDev** [angular/angular-cli#21732]
Hi,

I run angular CLI tasks in my own scripts that internally use `concurrently`. This setup disables colors in the angular CLI issue.

It would be great to be able to force color support via an env var, like `FORCE_COLOR`.

Related to:
* https://github.com/angular/angular-cli/issues/6478
* https://github.com/open-cli-tools/concurrently/issues/238

**Comment by alan-agius4** [comment]
`FORCE_COLOR` is supported by Node.js natively without the need to implement addition logic. See: https://nodejs.org/dist/latest-v12.x/docs/api/tty.html#tty_writestream_getcolordepth_env

The problem here, is that `concurrently`, `stdout` doesn't implement Node.js `WriteStream`, instead it is using RxJs Subject https://github.com/open-cli-tools/concurrently/blob/10ff00cbfbd4dbf1a41a716556b4592a20022fa9/src/command.js#L21 which of course doesn't support the `getColorDepth` nor `FORCE_COLOR` APIs.
