### ISSUE TITLE
OWASP Vulnerable Dependencies:  Child dependency ansi-html@0.0.7 of @angular-devkit/build-angular causing security issue

### ISSUE THREAD

**Issue by rashidaslam75** [angular/angular-cli#21843]
Vulnerable Dependencies Description: This affects all versions of package ansi-html. If an attacker provides a malicious string, it will get stuck processing the input for an extremely long time.

**Comment by alan-agius4** [comment]
This vulnerability doesn’t really effect the Angular CLI since we don’t expect the CLI to be executed on production environments were arbitrary maliciously crafted strings are provided.

`webpack-dev-server` has been updated to version 4 in Angular CLi version 13 which is currently in prerelease. Unfortunately this update cannot be back-ported to earlier versions due to breaking changes.
