### ISSUE TITLE
Lit web component decorators is removed by build-optimizer

### ISSUE THREAD

**Issue by johnste** [angular/angular-cli#21864]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Not sure

### Description

Lit.dev uses decorators to register custom elements when using typescript, e.g. 

```ts
@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  render() {
    return html`<p>Hello world</p>`;
  }
}
```

The angular build optimizer assumes all decorators are side effect free [similar issue here](https://github.com/angular/angular-cli/issues/20714#issuecomment-841255528) and marks the component as being side effect free, which leads to it being removed from the build.

Lit is not alone in using decorators this way, Stencil also uses a similar method that (though I haven't tested it myself)  

## 🔬 Minimal Reproduction

Example reproduction repo: https://github.com/johnste/lit-component-angular-repro (uses angular 11)

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
