### ISSUE TITLE
how do i get cli to copy random files to dist folder?

### ISSUE THREAD

**Issue by nmorado** [angular/angular-cli#2202]
versions: angular-cli: 1.0.0-beta.14
node: 5.10.1

i needed to copy random files into the dist folder. it's not clean from the the documentations how to accomplish the same.

appreciate any help.

thanks in advance.

**Comment by kylecordes** [comment]
This capability was lost a few weeks ago - you and I and others are eagerly hoping for its return. I feel like there is an inevitable opening for such a mechanism to be misused, so it would be great to do without it - but without it, too many projects will be driven away from CLI. Therefore, I hope it returns.)

(For some use cases you can work around it by copying extra files to "dist" after running ```ng build```; for other that won't work, because that doesn't make the files available at top level URLs during development with ```ng serve```.)

**Comment by Lightw3ight** [comment]
Im writing a chrome extension in Angular 2 with the cli and chrome extensions need a manifest.json file in the root of the app, so I would really like this feature back as manually copying files sucks! :(

**Comment by pauldubois777** [comment]
I am on 1.0.0-beta.14

Look in your angular-cli.json file for "assets" under "apps".  The default value is "assets", which represents the name of the folder you need to create under your "src" folder.  This folder, and its contents, will be copied to the "dist" folder during "ng build".  

Of course you can change the name of this folder to whatever you want, as long as it matches what is in your angular-cli.json file.  IE:
    "assets": "myAssets"

src -> myAssets

**Comment by nmorado** [comment]
This works

**Comment by Lightw3ight** [comment]
How do you get it to copy a file that exists in the root /src/manifest.json

**Comment by zompad** [comment]
I'm trying to build a PWA and need to move the manifest.json to the root.  Currently I am moving this with a shell copy script but would be nice to incorporate this into the ng build process.
@Lightw3ight - did you find a solution?

**Comment by filipesilva** [comment]
On the next release, this should be available: https://github.com/angular/angular-cli/pull/2570

**Comment by wooltar** [comment]
write manifest.son  in assets, file anuglar-cli.json

`"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "manifest.json"
      ],`
