### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by iDhruv22** [angular/angular-cli#2211]
As soon as i include any js file in index.html, the browser console show the error **"webpackJsonp is not defined"**

**Version information:**
- angular-cli: 1.0.0-beta.14
- node: 6.4.0
- os: linux x64

**Comment by filipesilva** [comment]
You shouldn't try to add files directly to `index.html` because that way the bundling breaks. 

I know it's a bit intuitive but different build systems do impose some restrictions on how to import stuff.

Can you tell me what you're trying to do? Maybe I can help you do it the right way for CLI projects.

**Comment by KingRauk** [comment]
Hi. I use the same version of CLI and Node and trying to add MDL selectfield.
https://github.com/MEYVN-digital/mdl-selectfield
Adding the .js in index.html but it breaks bundle, do anyone have an idea how I should add .js file without breaking bundle?

**Comment by filipesilva** [comment]
@KingRauk see https://github.com/angular/angular-cli#3rd-party-library-installation

Closing issue as inactive.

**Comment by MarkEMedlin** [comment]
I just ran across a similar issue.  I am using angular with ASP.Net.  I have to include the script libraries in my main page.  The included script library statements have worked fine since CLI release beta.14.  However, the location of WebpackJsonp changed since release beta.14.  It was moved from inline.js to inline.bundle.js.  

I had to copy the script statements from the dist\index.html file and place the statement in my ASP.Net Views\Shared\_Layout.cshtml file.  I also had to update the path for each .js file to reflect the location in my ASP.Net solution.  

Hope this helps someone.
