### ISSUE TITLE
Caniuse-lite uses CC-by-4.0 licensing

### ISSUE THREAD

**Issue by uahic** [angular/angular-cli#22123]
# 🐞 Bug report

### Description

Caniuse-lite is licenced under CC-by-4.0 which seems to require everyone to include special credits using this dependency and I'm still not sure if its also including a copyleft part (which would be deadly). The fact alone that each company's lawyers have to check this and spend time/money makes it on my opinion a no-go for commercial software. 

One could argue its only included in building stages (not sure about that?) and is already used by very large companies but I cant know if they have checked it or just ignored checking licenses.

Does the Angular team has been confronted with this issue before? If so, it would be helpful to have an official info page to explain why its not an issue to for commercial applications. Thank you!

**Comment by alan-agius4** [comment]
Hi @uahic, 

AFAIK, this is the first time that this came up.

 `caniuse-lite` is only used during the building phase and many tools use this package. Since this package is used for building and in no shape or form is redistributed as part of your application from my understanding of `CC-by ` an attribution is not needed since you are not redistributing licensed material.
 
From https://spdx.org/licenses/CC-BY-4.0.html

> Section 3 – License Conditions.
> 
> Your exercise of the Licensed Rights is expressly made subject to the following conditions.
> 
> a. Attribution.
> 1. If You Share the Licensed Material (including in modified form), You must:
> A. retain the following if it is supplied by the Licensor with the Licensed Material:
>      i. identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);
>      ii. a copyright notice;
>      iii. a notice that refers to this Public License;
>      iv. a notice that refers to the disclaimer of warranties;
>      v. a URI or hyperlink to the Licensed Material to the extent reasonably practicable;
> B. indicate if You modified the Licensed Material and retain an indication of any previous modifications; and
> C. indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.
> 2. You may satisfy the conditions in Section 3(a)(1) in any reasonable manner based on the medium, means, and context in which You Share the Licensed Material. For example, it may be reasonable to satisfy the conditions by providing a URI or hyperlink to a resource that includes the required information.
> 3. If requested by the Licensor, You must remove any of the information required by Section 3(a)(1)(A) to the extent reasonably practicable.
>  4.If You Share Adapted Material You produce, the Adapter's License You apply must not prevent recipients of the Adapted Material from complying with this Public License.

**Comment by alan-agius4** [comment]
We removed the direct dependency on this package as this is no longer necessary in version 13, via https://github.com/angular/angular-cli/pull/22124.

That being said, this is still a transitive dependency of a number of packages what we use.

**Comment by uahic** [comment]
I assume it will take some moments for your team to decide how to classify this issue, for me its definitely not (at least) crystal clear how licenses of dependencies of a build/cli chain influence transpiled code which has been generated by that chain and shipped to a customer. I also found that react-app starter-kit includes this dependency. But let me add that I'm glad you're having a look into that matter and did not just ignore it. Thanks alot

**Comment by dgp1130** [comment]
@uahic, Angular is built on top of a lot of open source technology with varying license requirements. It is up to users to stay complaint with any legal requirements of the technology they use, whether those dependencies are pulled in by Angular or by any other means. Due to the wide variety of technologies, licenses, and use cases, we can't provide comprehensive legal advice.

FWIW, my personal understanding of Creative Commons is that it mostly just requires attribution to the source, which is a pretty common requirement in the OSS ecosystem, and often allowed by most enterprises. Of course, IANAL and this is not legal advice, just my understanding of the requirement.

We do take license requirements into account when evaluating third party dependencies. If a particular legal requirement is a major barrier for using Angular, we would like to hear about that to inform or own strategy. Our previous discussions with enterprises have not shown OSS license attribution to be a significant barrier to use.
