### ISSUE TITLE
[Angular 13] `noEmitHelpers` broken

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#22137]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. It behaved as expected as recently as Angular 12.2.7.

### Description

We use `noEmitHelpers` in our tsconfig. The intent of this is that our code is emitted with no TypeScript helpers embedded (e.g. for spreading arrays), and we're able to load tslib separately beforehand.

With Angular 12, our code is emitted with lines like `__spreadArray([], balls)`. Loading `node_modules/tslib/tslib.js` sets that and other helper functions in the global scope, thus working as intended.

With Angular 13, the output looks like this:

```
/* harmony import */ var _cyph_cyph_app_node_modules_babel_runtime_helpers_esm_toConsumableArray__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./node_modules/@babel/runtime/helpers/esm/toConsumableArray */ 62384);

[...]

[].concat((0,_cyph_cyph_app_node_modules_babel_runtime_helpers_esm_toConsumableArray__WEBPACK_IMPORTED_MODULE_1__["default"])(balls));
```

The use case here is that we have sections of code that are converted to strings and executed within a Worker context. You see the problem. Rewriting all of our code to work around this issue would be a significant amount of work, realistically enough to block us from upgrading to Angular 13 for the foreseeable future.

## 🔬 Minimal Reproduction

Can provide one if needed.

## 🔥 Exception or Error

<pre><code>
Uncaught ReferenceError: _cyph_cyph_app_node_modules_babel_runtime_helpers_esm_toConsumableArray__WEBPACK_IMPORTED_MODULE_1__ is not defined
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.0.1
Node: 16.13.0
Package Manager: npm 8.1.3
OS: linux arm64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
</code></pre>

**Anything else relevant?**

Until a fix is released, can you suggest a workaround? I'd be happy just to be pointed in the direction of a file under `node_modules/@angular` that we can (hopefully temporarily) patch on our end to restore the previous behavior.

**Comment by alan-agius4** [comment]
The helpers mentioned are actually not inject by TypeScript but rather `@babel/plugin-transform-runtime` which is equivalent to TypeScript's `importHelpers` option, Babel also offers a similar option to `noEmitHelpers`, which is [`externalHelpers`](http://hzoo.github.io/babel.github.io/docs/advanced/external-helpers/).

That being said, this behaviour has been the same for a number of major versions when using either ES5 or ES2017+.

I am going to mark this issue for discussion with the rest of the team, to see if we should configure Babel to use these TypeScript options. My main concern is that that changing this behaviour can be considered as a breaking change at this point. Since if anyone is using `noEmitHelpers`, passing these options to Babel will cause their application to break during runtime due to the missing helpers. Although, I doubt many users are using `noEmitHelpers`.

**Comment by buu700** [comment]
Thanks for the quick reply!

As far as being a breaking change, if that were the case, it seems like this is already an undocumented breaking change? I would think that there would be more projects still on Angular 12 (possibly relying on the same behavior as us) preparing to upgrade to 13 than new projects on Angular 13 that just happen to rely on the current behavior of this option.

As far as what's actually changed and why, I guess I'm a little confused. Was it intentional to change the behavior of this option, or just incidental / a bug as I'd initially assumed? Does the generated code still need/use tslib at all, or is the Babel library a complete replacement that's now preferred for whatever reason?

**Comment by alan-agius4** [comment]
There are 2 types of helpers, TypeScript's (tslib) and Babel's which are both needed as they are used for different code transformations. Now, `noEmitHelpers` and `importHelpers` options control the TypeScript's helpers and this still works as expected. 

However, at the moment, there is no option exposed by the CLI to control Babel's helpers and this has been the case since Babel was introduced in the CLI in version 10. Likely, you didn't encounter this problem because previously you didn't have code that required Babel helpers. However, passing  the mentioned TypeScript options to Babel might cause applications to break as they will require to include additional  if anyone is using noEmitHelpers, passing these options to Babel will cause applications that require Babel helpers to break because these [helpers](http://hzoo.github.io/babel.github.io/docs/advanced/external-helpers/) would need to be included by hand.

**Comment by buu700** [comment]
Ah, got it, thanks for clarifying all that. If that's the case, since our code is the same (only Angular has changed), do you know why it's now using Babel helpers in cases where tslib helpers exist? I see in the latest tslib release notes that `__spreadArray` still exists, for example, so it's unclear why Angular now prefers Babel's `toConsumableArray`. Is that potentially a bug, or the current expected behavior?

Either way, I agree that setting `externalHelpers` based 
on `noEmitHelpers` at this point doesn't make sense (at least in a minor or patch release). Would it be possible to add a new option under `angularCompilerOptions` or to the `ng build` config? I wouldn't mind submitting a PR for that.

**Comment by alan-agius4** [comment]
@buu700, those are expected if you target ES5.

@clydin, mentioned a possible workaround, is to set the `target` in your tsconfig to `es2015`. Than you shouldn’t need the Babel helpers.

The fact that the CLI uses Babel is an implementation detail and I don’t think it would be wise to to expose new options to control this behaviour.

**Comment by buu700** [comment]
Well, we're currently targeting ES5 in both cases, so it's still unclear to me what changed to drop the dependency on `__spreadArray` (I suppose that could just be internal to `@babel/plugin-transform-runtime` if it isn't an intentional change on Angular's part).

We're ready to drop ES5 just yet (at least not for this reason; it'll be based on internal analytics), but out of curiosity does that workaround still apply if we're using async/await?

> The fact that the CLI uses Babel is an implementation detail and I don’t think it would be wise to to expose new options to control this behaviour.

Would it be possible then to set `externalHelpers` based on `noEmitHelpers` in version 13.1.0 or 14.0.0? I was about to test the following patch, which we could temporarily maintain on our end until then:

```
diff --git a/package.json b/package.json
index a01964b2b..6117bfd3c 100644
--- a/package.json
+++ b/package.json
@@ -82,6 +82,7 @@
     "@babel/core": "7.16.0",
     "@babel/generator": "7.16.0",
     "@babel/helper-annotate-as-pure": "7.16.0",
+    "@babel/plugin-external-helpers": "7.16.0",
     "@babel/plugin-proposal-async-generator-functions": "7.16.0",
     "@babel/plugin-transform-async-to-generator": "7.16.0",
     "@babel/plugin-transform-runtime": "7.16.0",
diff --git a/packages/angular_devkit/build_angular/src/babel/presets/application.ts b/packages/angular_devkit/build_angular/src/babel/presets/application.ts
index 8b849f07d..dae6061cf 100644
--- a/packages/angular_devkit/build_angular/src/babel/presets/application.ts
+++ b/packages/angular_devkit/build_angular/src/babel/presets/application.ts
@@ -259,14 +259,17 @@ export default function (api: unknown, options: ApplicationPresetOptions) {
 
   if (needRuntimeTransform) {
     // Babel equivalent to TypeScript's `importHelpers` option
-    plugins.push([
-      require('@babel/plugin-transform-runtime').default,
-      {
-        useESModules: true,
-        version: require('@babel/runtime/package.json').version,
-        absoluteRuntime: path.dirname(require.resolve('@babel/runtime/package.json')),
-      },
-    ]);
+    plugins.push(
+      require('@babel/plugin-external-helpers').default,
+      [
+        require('@babel/plugin-transform-runtime').default,
+        {
+          useESModules: true,
+          version: require('@babel/runtime/package.json').version,
+          absoluteRuntime: path.dirname(require.resolve('@babel/runtime/package.json')),
+        },
+      ]
+    );
   }
 
   return { presets, plugins };
```

**Comment by dgp1130** [comment]
@buu700 can you elaborate on your use case here? IIUC, it seems like you're somehow taking the build output of the CLI, splitting up the modules, and then loading some of them into a `Worker`. We have [direct support for Web Workers](https://angular.io/guide/web-worker), is there some reason that isn't sufficient for you?

Also, how exactly are you putting this code into a worker? Are you taking the CLI build output and transforming it somehow for a worker? This feels like an unsupported use case, but I don't think I fully understand what you're trying to do here.

**Comment by buu700** [comment]
Sure. What we're doing specifically looks more or less like this:

```
const thread = this.workerService.createThread(() => {
	[...]

	Comlink.expose(
		{
			doStuff: () => {
				[...]
			}
		},
		self
	);
});

await thread.doStuff();
```

The implementation under the hood converts the function into a string, converts that into a blob URL, and then passes it in to the Worker constructor.

There are various reasons that this makes more sense for our use case (developer-friendliness aside), but the general pattern also predates our usage of Angular in the first place.

**Comment by dgp1130** [comment]
Ah I understand, this [came up once before](https://github.com/angular/angular-cli/issues/15059#issuecomment-584593180) and [our take on it then](https://github.com/angular/angular-cli/issues/15059#issuecomment-635550420) was that this is a bit of an anti-pattern due to the issues you encountered. Imports don't work cleanly, global state is not shared (polyfills, helpers, etc.), and it's a potential XSS vulnerability. I think what you really want is a [module block](https://github.com/tc39/proposal-js-module-blocks#worklets), though this isn't standardized yet and I don't think any browser implements it.

There's no clean way to support this pattern and we don't think it is the right way of approaching this problem. We recommend using our built-in Web Worker support, even if it is a bit less convenient, it is much easier to reason about and doesn't suffer from the mentioned issues. Is there any reason Web Workers aren't viable for you, or is it just a migration issue from your current state?

**Comment by buu700** [comment]
I agree that those are all issues (with the exception of the XSS concern; we aren't evaluating user input), but they're really more inherent to Workers than anything to do with the way we're initializing them. I'm more concerned about the rapid pace of build tooling changes causing issues like this than I am about the run-time stability of the solution.

As far as dropping this for Angular's implementation, unfortunately that isn't an option for us. It's a requirement of [our stack](https://www.cyph.com/websign) that the Worker be initialized without using an external subresource. I'm also not seeing how the linked module block proposal applies here. Any alternative would require browser-level support for SRI with Worker scripts, but even then we would need to fall back on our current pattern as a polyfill for an extended period of time. Either way, I don't see why it's necessary to break something that has continued to work from Angular.js through Angular 12.

**Comment by dgp1130** [comment]
> It's a requirement of our stack that the Worker be initialized without using an external subresource.

I think the challenge here is that "your stack" doesn't support what you want to do. I'm not very familiar with SRI, but it sounds to me like web workers just don't support SRI in the way you want. The blob URL trick is a hack to work around that incompatibility. That's a completely independent issue from Angular.

> Either way, I don't see why it's necessary to break something that has continued to work from Angular.js through Angular 12.

"Works" != "Supported", there are plenty of implementation details of Angular today which can be abused to create interesting behavior (such as altering the Webpack config or deep importing private APIs). That doesn't mean they won't change, especially across a major version boundary. We have [a web worker solution](https://angular.io/guide/web-worker) currently, and while that might not work for SRI, that seems like more of a web platform problem than an Angular problem.

The feature request for Angular here is supporting blob URLs in workers as a workaround, which we don't think is a good idea for the above reasons.

**Comment by buu700** [comment]
Is there a reason that it wouldn't be desired for `noEmitHelpers` to behave consistently? I didn't bring up my specific use case initially because I don't think it's relevant. I'm not asking for "blob URLs in Workers" to be supported, as that's a detail of our code that has nothing to do with Angular. I'm suggesting that it's only logically consistent for `noEmitHelpers` to treat TypeScript and Babel helpers the same way.

**Comment by dgp1130** [comment]
The use case helps inform the motivation for such changes and any gaps in our own support, which is why I focused on that and tried to dig through the [XY problem](https://xyproblem.info/) here. I appreciate you sharing those details.

`noEmitHelpers` in `tsconfig.json` is a TypeScript concept. While Babel has a very similar flag for similar reasons, the semantics of these two flag may not always align. Mirroring `noEmitHelpers` in Babel automatically can lead to its own issues for discrepancies between the flags and their meaning and what applications actually want (maybe someone wants Babel helpers but not TS helpers). Even if the relevant semantics align now, we can't guarantee that they won't change in the future, and it could become a migration challenge. When the next tool comes along that emits helpers, users would also ask to tie that tool into the same flag, which again pulls on the incompatible semantics problem. IMHO, it's also fairly unintuitive that a change in `tsconfig.json` would affect a completely different part of the CLI build (Babel in this case).

If we were to do this, it would probably be in our own `angular.json` flag which gets reflected in both TypeScript and Babel (and any future tools). That way we would own the precise semantics of the flag and how our internal infrastructure respects it. Expanding the public API like this is a significant decision and we want to make sure we have a concrete understanding of the motivating use cases to ensure we are addressing them properly. Working around SRI in web workers is one requirement, which on its own isn't compelling enough for this kind of feature. If we find a large amount of users suffering from this particular issue or other motivating use cases for `noEmitHelpers` in Babel, we can re-evaluate, but for now there isn't much interest in expanding the public API to support such a feature.

**Comment by buu700** [comment]
Got it, thanks for clarifying all of that @dgp1130. That makes sense, and I can see why neither of those options would be ideal.

For now, we have the issue mitigated on our end with a patch based on @alan-agius4's earlier guidance. However, I'm not really excited about taking on this kind of technical debt without a clear long-term solution on the horizon.

As a compromise, would you guys be open to expanding the API surface of `@angular-devkit/build-angular` and/or `@ngtools/webpack`? That would allow us to solve our problem using a custom builder like `@angular-builders/custom-webpack`, without polluting the stable high-level APIs of the main framework. If so, I can go ahead and submit a new ticket for that.

**Comment by dgp1130** [comment]
We could add something like this to `@angular-devkit/build-angular`, however this is an experimental package with no public API. This feature also wouldn't be used by the CLI itself, meaning it could very easily be accidentally deleted in the future because it isn't used and break you in the same fashion. We would need to mark such an API with a comment basically saying, "Don't remove this because of #22137", at which point it has effectively become public API, even if the package itself is experimental. This makes it harder to evolve over time and future updates to Babel and our integration continue to run the risk of breakage. We don't think this is much better than an official API.

If there is more community interest in more explicit Babel configuration, then we can re-evaluate.

**Comment by buu700** [comment]
What if it were explicitly marked as experimental in the property name, with a note in the jsdoc that it may be removed without warning in a future release, particularly in the event that the CLI discontinues its use of Babel? For example, `AngularWebpackPlugin` could take an `experimentalBabelOptions.externalHelpers` or `experimental.babelOptions.externalHelpers` boolean.

On that note, it's not directly related, but the other parts of my requested API expansion would be `esbuildOptions` and `terserOptions`. Specifically, right now we have to patch `@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js` to modify the mangle and compress configurations for our needs, but would much prefer using a custom builder for this as well.
