### ISSUE TITLE
Feature: Allow switch from single quotes to double quotes

### ISSUE THREAD

**Issue by Mattes83** [angular/angular-cli#2213]
I think it would be useful to be able to configure if single quotes or double quotes are used in files generated by the cli.
This could e.g. be configured in  angular-cli.json.

**Comment by xtreemrage** [comment]
This would be really nice, in my work environment, double quotes are the way to go.

**Comment by Springrbua** [comment]
I usually work with java, so I am used to use double quotes.
Also I usually use tabs instead of spaces, but most IDEs support a Tab-to-Space conversion, so thats not a big problem.
However I haven't seen a Single-to-Double-Quote conversion until now and I guess it is pretty complex to implement one...
So having an option to use double quotes instead of single quotes in all CLI-generated files would be really great.

**Comment by delasteve** [comment]
With https://github.com/angular/angular-cli/pull/4248 you should be able to change the `tslint.json` `quotemark` rule from

```json
"quotemark": [
  true,
  "single"
],
```

to

```json
"quotemark": [
  true,
  "double"
],
```

and then do `ng lint --fix`.

I don't think this feature is necessary, as it will be more effort than it's worth, especially now that there will be (hopefully) a quick fix. Granted, all new files will also give you lint errors since they will use single quotes, but doing a quick `ng lint --fix` I don't think is too unreasonable.

**Comment by Springrbua** [comment]
@delasteve Thanks for this suggestion, I did not know about that tslint feature.  
But is it able to handle literals inside strings like:
`alert("Say 'Hello'");`

Thanks

**Comment by delasteve** [comment]
@Springrbua, the linter will change single quotes to double quotes. It will keep the inside quotes the same.

- Example 1: Double quotes inside single quotes
  ```ts
  const foo = '""';
  ``` 
  `ng lint --fix` (`tslint` ran with `--fix` under the hood)

  ```ts
  const foo = "\"\"";
  ```

- Example 2: Single quotes inside double quotes
  ```ts
  const foo = "''";
  ```
  `ng lint --fix` (`tslint` ran with `--fix` under the hood)

  ```ts
  const foo = "''";
  ```

**Comment by Springrbua** [comment]
@delasteve ah thats nice! Thanks a lot. Do you know when this feature will be available in angular-cli?

**Comment by delasteve** [comment]
It will be available next release. It got merged in yesterday.

**Comment by Springrbua** [comment]
@delasteve Thanks a lot for the information, can't wait for this feature :)

**Comment by filipesilva** [comment]
Closing as answered (and made possible) by @delasteve. Cheers!

**Comment by filipesilva** [comment]
This should be available soon-ish via automatically running TS Lint fixers on generators. This is being tracked in #6272.
