### ISSUE TITLE
Deprecate use of universal-analytics package

### ISSUE THREAD

**Issue by IanMoroney** [angular/angular-cli#22183]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

The `universal-analytics` package is not currently being maintained for security patches, and is vulnerable to JSON prototype pollution.
Google's `universal analytics` has been deprecated in favour of using [Google Analytics 4](https://support.google.com/analytics/answer/10089681) so I was wondering if it were possible to remove that dependency from the angular cli.
Would the [@google-analytics/data](https://www.npmjs.com/package/@google-analytics/data) package be a suitable replacement?

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
