### ISSUE TITLE
generate - customize location

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular-cli#222]
Right now, it appears to be hard-coded to an `app` directory to contain all src. I would like to use `angular-cli`'s `generate` ability but not necessarily use the build. For this to be useful, it would be beneficial to be able to specify the root src directory or even a path to a location to generate the file, etc.

If this sounds reasonable, I can look into a PR.

**Comment by NathanWalker** [comment]
For instance `app` here does not need to be hard-coded and could become a cli argument:
https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/component/files/src/app/components/__name__/__name__.ts#L6

**Comment by hansl** [comment]
Due to the complexity of the problem, we will not allow you to specify a structure. At least in the foreseeable future. We want the tool to generate an app with a structure that is considered the best practice by angular. And having a stable structure will make it easy for tools to parse as well. 

Note that the app structure generated by the tool right now is likely to change before the beta milestone. I would not use this for serious production websites, or be ready for some refactoring.

**Comment by NathanWalker** [comment]
Thanks @hansl understandable.
