### ISSUE TITLE
TSLintFixTask replacement for ESLint

### ISSUE THREAD

**Issue by MaxKless** [angular/angular-cli#22232]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Before the ESLint migration, the file changes resulting from a custom schematic could easily be linted by using a `TSLintFixTask` rule. This functionality was deprecated without providing an alternative for ESLint. 

### Describe the solution you'd like

It would be great if there was a native, performant rule to lint schematic results using ESLint.

### Describe alternatives you've considered

Alternatively, it would be possible to execute ESLint manually after executing a schematic or somehow writing a custom builder that modifies `ng generate`. I haven't been able to figure out how to do that, though. Any help is appreciated.

**Comment by alan-agius4** [comment]
Hi @MaxKless, 

Indeed the `TSLintFixTask` has been removed without replacement. An `EsLintFixTask` isn't something that we envision to be part of our API. The Angular CLI shouldn't be opinionated about which tools a user chooses to use to lint, or format the code. Instead we'd like to create a more generic API for users to create custom tasks and executors instead of providing an EsLint task. 

Let's keep tracking this as part of https://github.com/angular/angular-cli/issues/12678.
