### ISSUE TITLE
Add new option to exclude some packages from vendor.js

### ISSUE THREAD

**Issue by robmv** [angular/angular-cli#22325]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Add an option that tells CLI that some packages should not be treated as vendor packages. When code is reused between multiple applications and the code is developed by the same team, with the same update schedule of the applications using them, having these packages installed in `node_modules` but distributed in `vendor.js`, break many of the advantages of having a vendor file, like not needing to update it with every application minor update. Lets look at an example:

- Application for the Healthcare market
    - Uses @company/accounting package
    - Uses @company/inventory package
    - ...
    - Functionally exclusive for Healthcare not on a separate package
- Application for the Hospitality market
    - Uses @company/accounting package
    - Uses @company/inventory package
    - ...
    - Functionally exclusive for Hospitality not on a separate package

These two applications share code as separate packages, the problem with how Angular packages this by default, is that everything in `node_modules` is dumped on the `vendor.js` file, but it is better if they could be moved to `main.js`, this could reduce the need for clients to update `vendor.js` with every minor applications updates that don't change external dependencies versions.

### Describe the solution you'd like

Currently Angular CLI force everything on `node_modules` to `vendor.js`, check [the relevant code](https://github.com/angular/angular-cli/blob/b04cdc3a233c739063abd9b32bd8a3984a6ef1d5/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L44). Enhancing this code and exporting that to an option on `angular.json` could be great.

### Describe alternatives you've considered

This probably could be done with git submodules to share code with multiple Angular workspaces, but I am trying not to do this since using the npm modules dependencies functionality sounds more manageable.

**Comment by alan-agius4** [comment]
HI @robmv, 

Thanks for this feature request. 

None-the-less this doesn't align with the scope of the vendor chunking option. As per the [docs]( https://angular.io/cli/build 
) this option is intended to be used for development. This is because it will speed up the feedback loop when performing changes in your application. 

However, during production builds, we don't encourage this option to be used. as in many cases this can cause optimization bailouts, sub-optimal code splitting and increases the bundle size, especially if lazy loading is used. All the mentioned will also have a negative impact on the [core web vitals](https://web.dev/vitals/).
