### ISSUE TITLE
module not found when the npm package is packed in a certain way

### ISSUE THREAD

**Issue by jcompagner** [angular/angular-cli#22324]
This is more of a discussion, i am also not sure if this belongs here, if it is a typescript issue or if they just really need to fix there package in npm

i already reported my issue here: https://github.com/transloadit/uppy/issues/3354 
because i have a problem with @uppy/angular package that they ship

the problem is that the angular package (the one with the FESM dirs) is in a "dist/angular" folder inside the package
and the the main package.json (in the root)

  "name": "@uppy/angular",
  "version": "0.2.6",
  "module": "dist/angular/esm2015/public-api.js",
  "types": "dist/angular/uppy-angular.d.ts",

does that.

But when i use that package in my own component, which is also a package
And then use my component in a project i get:

/node_modules/@servoy/servoyextracomponents/fesm2020/servoy-servoyextracomponents.mjs:26:0-38 - Error: Module not found: Error: Can't resolve '@uppy/angular' in '/node_modules/@servoy/servoyextracomponents/fesm2020'

i guess they should just package it better and not having that indirection, i just wonder should this work?

**Comment by alan-agius4** [comment]
Hi @jcompagner, 

The problem here is that the mentioned library `@uppy/angular`, the `module` key is referencing a file that does not exist and therefore the module resolution is failing.

```json
 "module": "dist/angular/esm2015/public-api.js",
```

https://unpkg.com/browse/@uppy/angular@0.2.6/dist/angular/

That being said, the package also seems to be published from an incorrect location for some reason as it should be published from `/dist/angular/` as otherwise the package doesn't conform with the [APF spec](https://angular.io/guide/angular-package-format). 

Closing as the failure is legit.

**Comment by jcompagner** [comment]
ah i didn't notice that, is that the case why 0.2.5 should maybe work because that file reference was pointing to an existing one..

Problem is a bit that they did a release and because of that some released component of mine (that worked on top of that) started to fail, but those releases did almost happen at the same time.

So now i wonder if also the build of my component (that just uses @uppy/angular) wouldn't also just fail, but it could be that i build that against 0.2.5 and then when that was installed in another project hat project did get 0.2.6 and because of that it fails now (because of the wrong reference)

but as you said and i already mentioned in on the issue for them, that they should deploy that more correctly anyway.

thx for looking into it.
