### ISSUE TITLE
ng build --preserve-symlinks caches the first seen version of linked library

### ISSUE THREAD

**Issue by greenpau** [angular/angular-cli#22380]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Idk.

### Description

The `ng build --preserve-symlinks` works only once for linked libraries.

## 🔬 Minimal Reproduction

Step 1: Modify code, build, and link `ngx-avatar-persona`:

```
cd ~/dev/go/src/github.com/greenpau/ngx-avatar-persona
ng build
cd dist/ngx-avatar-persona
npm link
```

That would create a symlink:

```
/home/greenpau/.npm-global/lib/node_modules/ngx-avatar-persona -> /home/greenpau/dev/go/src/github.com/greenpau/ngx-avatar-persona/dist/ngx-avatar-persona
```

Step 2: Browse to AuthDB app and reference the newly created link:

```
cd ~/dev/go/src/github.com/greenpau/authdb-ui
npm link ngx-avatar-persona
```

That would create another link:

```
/home/greenpau/dev/go/src/github.com/greenpau/authdb-ui/node_modules/ngx-avatar-persona -> /home/greenpau/.npm-global/lib/node_modules/ngx-avatar-persona -> /home/greenpau/dev/go/src/github.com/greenpau/ngx-avatar-persona/dist/ngx-avatar-persona
```

Then, build `authdb-ui` app:

```
ng build --preserve-symlinks
```

**Note**: At this point the changes in `ngx-avatar-persona` propagated to `authdb-ui` app.

Step 3 (new changes): make changes to `ngx-avatar-persona` and repeat Step 1 and 2.

The changes to the `ngx-avatar-persona` would not be reflected in `authdb-ui` app.

## 🔥 Exception or Error

No error. The changes are not being picked up.

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.1
Node: 14.17.6
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.1
@angular-devkit/build-angular   13.1.1
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@angular/cli                    13.1.1
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.5.3
</code></pre>

**Anything else relevant?**

No.

**Comment by alan-agius4** [comment]
Hi, 

This is expected, because `node_modules` are treated as immutable unless the `version` in the `package.json` of the library changes.

See:
https://webpack.js.org/configuration/other-options/#cachemanagedpaths
https://webpack.js.org/configuration/other-options/#immutablepaths

That are a couple of things you can do however;

1) Build the library in watch mode, which would change the version in the package.json with every rebuild. 
2) You can [disable caching](https://angular.io/cli/cache#enabling-and-disabling-the-cache).
3) Consume the library using path mappings instead of links. 

**tsconfig.json**
```js
"compilerOptions": {
    "paths": {
        "ngx-avatar-persona": ["../ngx-avatar-persona/dist/]
    }
 }
```

Closing since this is working as expected, however feel free to continue the discussion below.

**Comment by greenpau** [comment]
@alan-agius4 , thank you very much! 👍
