### ISSUE TITLE
Stylus support: why removed?

### ISSUE THREAD

**Issue by lynxeyedua** [angular/angular-cli#22432]
Hello. In the most recent versions on Angular CLI we start seeing warning _"Stylus usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour, please migrate to another stylesheet language."_

The problem is that we heavily rely on it, and can't easily move to other stylesheet language. This will very likely block us from using latest versions of Angular in the near future.

Also, the reasons behind this decision are also not clear. Even if only 0.3% users use stylus, this is thousands of developers, which will have one more pain to solve. And repository is not so dead anymore https://github.com/stylus/stylus/commits/dev

Please, check this, review the decision and keep Stylus support in the future versions. 

If this is not possible, how about postponing Stylus removal to a far future versions (e.g. do this in Angular 16)?

Thanks in advance!

Serhii

**Comment by dgp1130** [comment]
Hi @lynxeyedua, thanks for bringing this up. We're glad to hear that Stylus is getting some love.

Dropping Stylus support was a tough decision that involved a lot of different factors. Low usage (0.3% as you mentioned) was probably the most significant data point, as we have finite time and resources to deliver value to users and need to make trade-offs. All CLI users "pay" for Stylus, since it is directly depended upon by the CLI, even if you don't use it (which is 99.7% of users).

Stylus support in Angular is already weaker compared to other CSS preprocessors like Sass (for example, you can't use Stylus in a single-file component). Continued investment in Stylus support didn't feel like it would provide as much value to the community as the countless other projects we could be spending time on instead. Stylus is also still considered "experimental" (the NPM package hasn't reached `1.0.0` yet), so long term sustainability and cost is hard to estimate.

Googling around shows a few existing tools which provide some automated means to migrate off of Stylus (disclaimer: I haven't tried them). Hopefully these can provide a starting point and some guidance for projects in your position to help ease the migration process.

> If this is not possible, how about postponing Stylus removal to a far future versions (e.g. do this in Angular 16)?

We do hear you, and understand that changing CSS preprocessor is a pretty high-friction change that involves a significant amount of churn. I believe Stylus support was deprecated in Angular v12, and we usually give a 1-2 major version grace period before dropping a deprecated feature. We can't defer this forever, but since this is a bigger breaking change than most, I imagine we'll give some extra time for projects to migrate. We're going through v14 scoping right now and are *not* planning to drop Stylus just yet. I can't promise any specific version where it will/won't be removed, but we do listen to the community and want to make sure teams have the appropriate amount of time to handle this migration.

**Comment by jamie-pate** [comment]
Tooling to auto-convert stylus to sas/scss would go a long way (even if it just gets us 90% of the way there)

This is the kind of tooling that angular devs have promised for such major changes like this. 

This example would get almost the whole way there since sass is close to stylus.. but a stylus ast -> sass/scss ast -> sass/scss text would probably be a small amount of work compared to the volume of stylus code that needs to be converted by hand by the .3% (even if it came with large disclaimers about impedence mismatch stylus/scss feature sets and some manual cleanup after...)

https://github.com/ManuelSch/sass-scss-converter/blob/master/src/util/convertSassToScss.ts
