### ISSUE TITLE
Fingerprint assets

### ISSUE THREAD

**Issue by acalvo** [angular/angular-cli#22510]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Angular CLI fingerprints the generated JS output (for example `main.d64e98daf9464b95.js`) which works great with aggressive cache strategies in a CDN.

In the other hand for assets such as images, [the recommended way of dealing with them](https://angular.io/guide/workspace-config#assets-configuration) is to put them in a special folder which Angular CLI copies as-is when building the app. This means that there is no fingerprint and thus causes problems with CDNs cache, as can't know if the requested file changed since last request.

### Describe the solution you'd like

A way of fingerprinting assets such as images that works with Angular CLI.

### Describe alternatives you've considered

We used to use some webpack tricks but none of them work by Angular CLI 13.1.

We also use a Service Worker but doesn't solve the problem: it does keep track of the changes and knows if a non-figerprinted resource changed (as it stores its hash in `ngsw.json`) BUT when it has changed and it's requested to the CDN, the CDN doesn't know about this and can't decide whether it can serve the cached version, or should request a fresh version of it. If it was fingerprinted, as they'd be different filenames, there would be no problems with the cache.

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/22351 and https://github.com/angular/angular-cli/issues/3415

**Comment by dgp1130** [comment]
This feature isn't really feasible since there are so many ways to reference assets in an application with no easy way to get the hash for that asset.

* `fetch('/some-asset.txt')`
* `@import '/some-font.ttf'`
* `<img src="{{ 'some-asset.jpg' | relativeUrl }}" *someDirectiveWhichModifiesSrc />`

For app-specific JS and CSS files which get chunked, we can automatically supply the hash at all usage sites. But assets, by definition, are used in places we don't control and can't inject the hash for you, making this fairly unusable.

**Comment by acalvo** [comment]
@dgp1130 sorry, I might have not explained myself well. The feature request is not necessarily to add a way to make Angular automatically generate and handle fingerprints/hashes. It's just to support (i.e., document so that it's officially supported) *any* either manual or automatic way of achieving it. It's already doable as stated in https://github.com/angular/angular-cli/issues/23144 . But the way described there is a webpack trick that is not officially supported by Angular.

Hence this feature request: to support *any* way of doing it. That could be the one already works (just document it), or define a similar one - anything that officially supports what unofficially has always been doable.

Can you reopen the issue @dgp1130 ? Or should I open a new feature request making this clear? Although that be a pity because this issue already has 42 upvotes...

**Comment by dgp1130** [comment]
If you're hoping for something like an officially supported file loader syntax, then I don't think that's viable either since Webpack is an implementation detail which could change in the future as mentioned in that issue. Even if we consider this a public API of Angular which happens to be implemented via Webpack, such a syntax isn't compatible with actual web standards. This means any new future bundlers we use might not support that functionality, which could limit our options going forward and cause breakages for users if the feature needs to be removed.

From a slightly higher level, I understand the desire for hashes in filenames and I get how that can often make the caching story simpler. Ultimately the Angular CLI is responsible for building your web client (HTML, JS, CSS). We have some basic support for assets, because that's a very common problem users encounter. But that support is deliberately limited, as Angular is not a comprehensive build system. Where users write source code, we try to make that code align with web standards as much as possible so users don't make their code implicitly require the exact Angular CLI toolchain.

If there is a future proposal for "import file contents from a URL", then we could possible revisit this and support some means of loading and hashing that URL automatically. Import assertions might be the right area for this (I think you can already do this with JSON files at least), but I'm not aware of any "load a generic asset" spec right now.

For possible workarounds:
* You can always check-in assets with hashes already in the file names, and just include that hash wherever it's used. That will put a bunch of ugly hashes into your source files which most people probably don't want.
* You can also explore https://www.npmjs.com/package/@angular-builders/custom-webpack to manually add in a file loader, though we don't really support that use case either for the same reasons mentioned above.
