### ISSUE TITLE
Shell hijacked

### ISSUE THREAD

**Issue by LaKing** [angular/angular-cli#2258]
Minor issue.

> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Fedora 14

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15
node: 5.9.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

install the CLI
add a new project
cd to the dir
ng test

4. The log given by the failure. Normally this include a stack trace and some
   more information.

running ng-test on a VE without browsers ..

21 09 2016 01:32:28.076:ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.

.. and then it seems to be impossible to exit from here.

5. Mention any other details that might be useful.

It's ok that I can't test without a browser, but Ctrl-C should exit back to the shell.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This seems to be a karma issue rather than a CLI issue. Please submit it in https://github.com/karma-runner/karma instead. The CLI just runs Karma when you do `ng test`.

As a note, `ng test` runs in watch mode by default... you can do `ng test --no-watch` to do a single run.

If you are looking for a Travis/headless browser config, I can direct you to the quickstart travis file: https://github.com/angular/quickstart/blob/master/.travis.yml
