### ISSUE TITLE
The Registration Pattern

### ISSUE THREAD

**Issue by joeedh** [angular/angular-cli#22592]
There's a common pattern I do a lot in my code:

`
export const Classes = [];

class BaseClass {
  static register(childClass) {
    Classes.push(childClass);
  }
}

class Child extends BaseClass {
}
BaseClass.register(Child);
`

Angular's webpack setup (at least Angular 10) prunes child classes that use this pattern.
I don't understand why; shouldn't `BaseClass.register(Child)` be enough to keep them around?

**Comment by joeedh** [comment]
Okay I think I figured it out.  Angular uses webpack's "sideEffects" code optimization mode, which prunes files based solely on import/export statements.  I make a custom webpack config with sideEffects:false and usedExports:true and it seems to work, while producing almost the same level of compression.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
