### ISSUE TITLE
ng build SHOULD NOT use prod environment by default. It possibly corrupts the production database

### ISSUE THREAD

**Issue by Davidnh8** [angular/angular-cli#22618]
# 🚀 Feature request

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Right now running `ng build` builds production by default. I am suggesting that we definitely don't do that as we risk contaminating production database. Here is a scenario:
1. I have 2 servers: staging and production. Each with unique CI and firebase database configured
2. I use ng build and ng build --prod on each CI respectively. Thinking that each will build development and production respectively..
3. I deploy both apps, without knowing that both servers are configured to use the same PRODUCTION firebase database
4. App is live. I onboard a QA.
5. QA creates or DELETES random data during testing, hence contaminating the production database

As you can see it opens up the possibility of connecting production database to staging environments because the developer trusts that ng build will not blindly build production, especially since it has always been the case that you needed --prod.

I get that many users forgot to use --prod, hence this solution was implemented, but it can be dangerous to production apps. I strongly recommend we revert this change and resort to printing out glaringly obvious console messages if user forgets to use --prod.

### Describe the solution you'd like

Don't build production by default on ng build.

**Comment by alan-agius4** [comment]
Hi @Davidnh8, 

We appreciated your feedback. 

We did a lot of research prior to switching the defaults of `ng build` to be production by default.

Some of the reasons why of this change are:
1) This aligns with other frameworks CLIs example both React (CRA) and Vue CLIO build is production by default. 
2) A number of hosting providers will run `npm run build` to build a production ready application. This caused users to deploy non optimized applications to production.
3) From feedback we gather, users did expect that `ng build` generated a production ready bundle.
4) At enterprise level it is also common that users choose to promote the generated bundle from one environment to another without rebuilding. This is mainly possible by shifting towards using runtime instead of build time configurations. 

That being said, while we don't recommand switching the default especially since it can cause confusion for new developers going your team. You can opt-out from the production by default builds by altering the builder configuration in your `angular.json`.

```diff
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
      ...
  },
  "configurations": {
    "production": {
      ...
    },
    "development": {
      ...
    }
  },
+ "defaultConfiguration": "development"
- "defaultConfiguration": "production"
},
```
