### ISSUE TITLE
Angular DevTools install suggestion pop-up

### ISSUE THREAD

**Issue by sumitarora** [angular/angular-cli#22619]
# 🚀 Feature request

Angular CLI should show `install devtools` suggestion pop-up when running `ng serve`

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When a user executes `ng serve` on their application running in development mode, the CLI should inject a script which checks if Angular DevTools is available. If it’s not available, the script should show a pop up asking if the user wants to install the extension or never see the pop up again.

Clicking on “Install” should redirect the user to the Chrome Web Store page of Angular DevTools.

New configuration option `disableDevtoolsPopup` should be added to disable the functionality.

### Describe the solution you'd like

Document describing the proposed solution.
https://docs.google.com/document/d/e/2PACX-1vQiWzu6eqD_Ep4-Yt0yGjfY8o7n3jmYz0pC6lwceO6SR3Jz7EDLxjGkrSbCinav7ceWyk13qguGRA9Z/pub

**Comment by sorin-davidoi** [comment]
Browser sniffing will be needed to not spam Firefox and Safari users that can't install the extension:
 - https://github.com/rangle/angular-devtools/issues/785
 - https://github.com/rangle/angular-devtools/issues/895

**Comment by mgechev** [comment]
@sorin-davidoi good point! We should have Firefox support soon.

**Comment by alan-agius4** [comment]
Some points to consider: 

- As mentioned above this should only be done for Chrome desktop, therefore there needs to be some browser detection logic.
- When the `Close` button is clicked, likely a state needs to be persisted in local storage to avoid the pop-up to re-appear when the page is refresh when there are code changes due to live-reloading.
- For browser to node communication we'd can probably add a dev-server middleware to modify the `angular.json`. (This is actually quite involved).
- From the builder there is no easy way to access the global configuration, therefore a builder level option would be a better alternative.

**Comment by alan-agius4** [comment]
@mgechev is this something that we want to do and keep tracking on Github?

**Comment by alan-agius4** [comment]
Closing as this is tracked internally.
