### ISSUE TITLE
13.2.1 breaks constructor names with disabled mangler in production builds

### ISSUE THREAD

**Issue by amoscatelli** [angular/angular-cli#22622]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 13.1.2

### Description

 
After being forced to upgrade to 13.2.1 (caused by https://github.com/angular/angular-cli/issues/22606) disabling mangler (NG_BUILD_MANGLE="false") does not mantain correct constructor names, since "numbers" are appended to the name when compiling for production.

For example AppComponent constructor name becomes "AppComponent1" or "AppComponent2" or "AppComponent3" (etc etc).
This applies to every constructor, even ones from ivy libraries.

Reverting back to 13.1.2 makes NG_BUILD_MANGLE="false" working properly again and constructor name is back to "AppComponent" 

## 🔬 Minimal Reproduction

Set NG_BUILD_MANGLE to false.
put something like console.log(AppComponent.name); inside app.component.ts constructor
ng serve  --configuration=production

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.2.1
Node: 16.13.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.1
@angular-devkit/build-angular   13.2.1
@angular-devkit/core            13.2.1
@angular-devkit/schematics      13.2.1
@angular/cli                    13.2.1
@angular/compiler               13.2.0
@angular/compiler-cli           13.2.0
@angular/language-service       13.1.0
@angular/service-worker         13.1.2
@schematics/angular             13.2.1
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @amoscatelli, 

This is working as intended due to the changes in https://github.com/angular/angular-cli/pull/22379.

The `NG_BUILD_MANGLE` is a private API that is only intended to be used for debugging purposes and it's implementation can change in any version without a warning.

It is recommended to use other alternatives to the `name` property, such as `instanceof` or a custom `static` property.

**Comment by alan-agius4** [comment]
In the past we did have decisions around this and were we decided that we should not provide such option as in general it is a bad practice to rely on `.name` property and it also causes increases in bundle.

Similar issues:
https://github.com/angular/angular-cli/issues/12887
https://github.com/angular/angular-cli/issues/11910
https://github.com/angular/angular-cli/issues/3861

If your application does require the name property, you can extend the Angular CLI by using a 3rd party solution such as [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) vs [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack).

**Comment by amoscatelli** [comment]
If you read carefully those issues you'll see there are many (and I stress out 'many') who asked for the freedom of doing what I also did, and they kindly and politely gave reasons for they doing such thing. They have been ignored because somebody thought his point of view was the only right one in an opensource framework.

The more you find issues about this, the more I am proved right.

I have been using Angular for 5 years and there were _always_ ways to disable name mangling. NG_BUILD_MANGLE is like the third different way of disabling name mangling till now.

I ventured in unsopported territory you say ? Source code is my documentation. I don't think undocumented means automatically private in the opensource world.

From my point of view, I should have the possibility to make a pull request and extend myself functionalities offered in angular.json to let users override terser/mangling options.

But I doubt such pull request would be accepted, looking at those issues and noting how many plugins exist about this.

**Comment by amoscatelli** [comment]
One more funny thing :

I was _forced_ out of lts into 13.x because of https://github.com/angular/angular-cli/issues/22280#issuecomment-984631710

**Comment by alan-agius4** [comment]
@amoscatelli, I understand that you are frustrated that your application is broken. But this is not a regression as in terms of functionality the Angular CLI never supported access to the name property during optimized builds, as per the various issues listed above. 

Keeping the name of the classes or functions is not something that we allow nor want, as it defeats one of the principal goals of the Angular CLI which is to provided the smallest possible bundles, since turning on this option will significantly increase the bundle size. In addition to this, while accessing the name of a class or function is pretty common in other languages this is not so for JavaScript for this reason.

In general it should be assumed that anything un-documented or not exported as part of the public API (iE: accessed via deep imports) is to be considered private, this typically is true for most popular OSS packages.

Regarding to why you were forced on to v13, that is all in conformance with our [support policy](https://angular.io/guide/releases#support-policy-and-schedule.).
