### ISSUE TITLE
Adding linter to ng serve

### ISSUE THREAD

**Issue by Pirozek** [angular/angular-cli#22648]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 Hey guys, I am well aware of issues https://github.com/angular/angular-cli/issues/3269 and https://github.com/angular/angular-cli/issues/3269 but those are over a few years old and I think this feature is still kinda missing.

Purpose of feature is to add `ng lint` functionality to watch cycle of `ng serve` and `ng build --watch` commands. Right now, I can set up linter in IDE, but it only lints file I am currently working on.

### Describe the solution you'd like

  It would be great to have lint functionality, that is already there, enabled in watch commands of angular CLI. I can, of course, set up another watcher, but purpose of CLI should be to provide pleasant developer experience :)

**Comment by alan-agius4** [comment]
This is quite a desirable feature because having build and lint feedback at the same time via a single command sounds link a great feature on paper.  But in reality, it is so and in many case it will causes more harm than good, especially as the project starts growing.

Very few people remember, but we did have linting on `ng test --watch`. This was removed quite some time ago. We also have a circular dependency checker on `ng build` and `ng serve` which is currently in deprecation phase and will be remove in version 14. The main reason why these have been removed is because they slow down compilations and at times quite drastically. This clearly is a problem during a build but more so when running in watch mode, because the purpose in watch is to get very fast feedback on your changes and anything that slows it down is a problem. Also, typically when testing out changes or writing code you don't care as much about styling issues. 

Angular CLI, is also not opinionated which linter is used and therefore different linting setups can require different results/presentation/options. 

One of the goals of the CLI is to continuously improve and reduce the build times, and adding a linter during the build would definitly hinder that. 

I know I will get a number of dislikes for this, but IMO, linting doesn't belong in an incremental build step, where you want to do the least necessary work as possible.
