### ISSUE TITLE
Turn off sourcesContent in .map files

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#22708]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I found the .map files generated by angular will contain sourcesContent property. Is it possible to delete it? I tried to use custom webpack, but I can't get the original webpack.config.js angular uses. So I don't know what to do.

I also find angular will modify my exiting angular libraries .map files to add sourcesContent property, which will disable vscode's Go to Implementation function.

I asked in gitter, but no body replies. I guess I'll have better chance here.

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.18
Node: 16.13.1
OS: win32 x64

Angular: undefined
... 
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.18 (cli-only)     
@angular-devkit/core         11.2.18 (cli-only)       
@angular-devkit/schematics   11.2.18 (cli-only)       
@schematics/angular          11.2.18 (cli-only)       
@schematics/update           0.1102.18 (cli-only)     
typescript                   4.5.5
</code></pre>

**Comment by UchihaYuki** [comment]
A relevent question:
https://github.com/angular/angular-cli/issues/22703

**Comment by alan-agius4** [comment]
This is caused by NGCC and It is not possible to turn this off. It is recommended to build and ship your Angular libraries using v13+ which would not require processing by NGCC.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by UchihaYuki** [comment]
It is a bug, please look at this issue.
https://github.com/microsoft/vscode/issues/142980
sourcesContent property does prevent vscode code work properly. But I do understant that, it's not possible to delete it in angular. Maybe I just need to wait for the bug to be fixed by vscode.

**Comment by UchihaYuki** [comment]
You can close it, after viewing my comment. Thank you.
