### ISSUE TITLE
ng init asks: Overwrite some files (Yn...)  no information to base answer on.

### ISSUE THREAD

**Issue by lebsral** [angular/angular-cli#2271]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
10.11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng init

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

When doing an ng init on an existing project it asks if I want to overwrite a series of files.  But since I haven't seen what it is gong to overwrite it with, I have no information to base that decision on.

I can just say yes to everything then use git to determine which things I want to revert.  But then why ask in the first place?

**Comment by tomwanzek** [comment]
I encountered the same experience when migrating projects over the past few releases (from beta.11.webpack.8 to now beta.15).

All the files encountered were subject to git version control in the repo. So a reasonable approach can be:
1) Ensure there are no uncommitted changes in the repo
2) Do all the clean-up pre-work before running `ng init` (i.e. remove node_modules, dist etc.)
3) Run `ng init`. When asked whether to overwrite, you should be alright to answer Y, since you will be able to see the isolated uncommitted changes in your IDE (in my case VS Code)
4) Review the tracked changes by file and simply "undo" the ones you do not need

Mostly, I noticed that I could readily revert back all changes to files like `index.html`, `app.component.ts` and the like. (Although, this may not be the case if you come from earlier angular-cli/angular releases.)

The biggest issue was mostly related to `package.json`. The tender-loving care was:
* re-installing project specific packages, like `bootstrap` or `d3-ng2-service`
* Adding back properties like "author", which were wiped in the ng  init process. (Tends to be a quick copy/paste job in the IDEs delta view

Also, `angular-cli.json` may need similar attention to e.g. "styles". In any case due to the delta view it's relatively straightforward.

Based on the delta's I saw in the initial projects I migrated, I then chose not to overwrite certain app source code files (`index.hmtl`, `app.component.ts`, `*.css` etc.) for other projects with a comparable angular-cli version starting point.

Hope this helps.

**Comment by kylecordes** [comment]
Over here we have been following and recommending the same process as @tomwanzek; although it would be possible for CLI itself to offer a diff and merge feature for each of these files during an upgrade, in a real project your source control tool is going to do a much better job presenting the overall set of changes for review/merge/edit anyway.

It seems likely to me that a future CLI version will do a better job merging the needed changes for upgrade instead of just overwriting all the files, in the meantime though this process typically takes only a short while.

**Comment by gelliott181** [comment]
The CLI already offers a diff option to see what changes will be made. When you run ng init it will ask `Overwrite file.ext? (Yndh)`. You can decide whether to overwrite (Y, default), skip (n), diff (d), or get help (h).

The diff (d) option will then print a comparison of the two files. It's no git diff, but I haven't had to scroll a diff yet, even on an 80 line height console window.

**Comment by lebsral** [comment]
@gelliott181 
Thanks for the tip.
Maybe we could change it from
Yndh
to
ynDh
to make that more obvious.  Seems like the diff should be the first default.

**Comment by gelliott181** [comment]
I'd agree that diffing the files by default is a much better option. I've already had to do some hard resets after wrecking my project's configs by hitting enter repetitively.

**Comment by kylecordes** [comment]
It would also be wonderful, perhaps in a few months after some more pressing needs are addressed, to make the upgrade process more "semantic", where it would not overwrite the files and all, rather it would understand its current needs and try to make them specifically. For example it could no what dependencies are currently needed, what dependencies used to be needed but no longer are, and make those updates to the package.json instead of overwriting it. And so on. But this is quite a lot more complex, of course.

**Comment by filipesilva** [comment]
As mentioned, the option to diff is presented. We have an upgrade functionality planned that would largely mitigate the need for this process, but don't have specifics to share at the moment.
