### ISSUE TITLE
Adding german special characters to *.ts-files breaks source maps with workspaces

### ISSUE THREAD

**Issue by markuspalme** [angular/angular-cli#22795]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Not sure

### Description

1. Create a new project with `ng new` and default options (no routing, CSS)
2. Run with `ng serve`, open in Chrome or Firefox
3. In the developer tools, add the directory as a workspace. The local `*.ts` files are recognized as indicated by the little green dots:
    
   <img width="702" alt="image" src="https://user-images.githubusercontent.com/1481801/156445910-825dd165-a3ee-49cc-a086-57a48140ff51.png">

4. Now go to `app.component.ts` and change the title so that it contains an umlaut such as `ü`:
   
   <img width="279" alt="image" src="https://user-images.githubusercontent.com/1481801/156446246-81b7205a-59d7-463a-897a-04e0bd2c32c3.png">

5. The browser refreshes and looses the link to `app.component.ts`:

   <img width="262" alt="image" src="https://user-images.githubusercontent.com/1481801/156446183-a19b46d3-3d7d-44a4-b766-bbd052e3bbe5.png">

As a consequence, breakpoints in this file are no longer hit.

Expected results: Adding special characters in the utf-8 encoded file does not impact source maps.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin arm64

Angular: 13.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by alan-agius4** [comment]
Hi @markuspalme,

I did try to look into this and it doesn't seem an issue with the sourcemaps generation when using UTF-8 characters as they are being generated correctly.

You can take a look here: https://justin.ridgewell.name/source-map-visualization-evanw/#NjQyACJ1c2Ugc3RyaWN0IjsKKHNlbGZbIndlYnBhY2tDaHVua3NtX3VuaWNvZGVfdGVzdCJdID0gc2VsZlsid2VicGFja0NodW5rc21fdW5pY29kZV90ZXN0Il0gfHwgW10pLnB1c2goW1sibWFpbiJdLHsKCi8qKiovIDEzOToKLyohKioqKioqKioqKioqKioqKioqKioqISpcCiAgISoqKiAuL3NyYy9tYWluLnRzICoqKiEKICBcKioqKioqKioqKioqKioqKioqKioqLwovKioqLyAoKCkgPT4gewoKCmNvbnN0IHggPSAnYWFhw7xhJzsKY29uc29sZS5sb2coeCk7CgoKLyoqKi8gfSkKCn0sCi8qKioqKiovIF9fd2VicGFja19yZXF1aXJlX18gPT4geyAvLyB3ZWJwYWNrUnVudGltZU1vZHVsZXMKLyoqKioqKi8gdmFyIF9fd2VicGFja19leGVjX18gPSAobW9kdWxlSWQpID0+IChfX3dlYnBhY2tfcmVxdWlyZV9fKF9fd2VicGFja19yZXF1aXJlX18ucyA9IG1vZHVsZUlkKSkKLyoqKioqKi8gX193ZWJwYWNrX3JlcXVpcmVfXy5PKDAsIFsidmVuZG9yIl0sICgpID0+IChfX3dlYnBhY2tfZXhlY19fKDIwMiksIF9fd2VicGFja19leGVjX18oMTM5KSkpOwovKioqKioqLyB2YXIgX193ZWJwYWNrX2V4cG9ydHNfXyA9IF9fd2VicGFja19yZXF1aXJlX18uTygpOwovKioqKioqLyB9Cl0pOwovLyMgc291cmNlTWFwcGluZ1VSTD1tYWluLmpzLm1hcDMwNgB7CiAgInZlcnNpb24iOiAzLAogICJmaWxlIjogIm1haW4uanMiLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7QUFBQSxNQUFNLENBQUMsR0FBVyxPQUFPLENBQUM7QUFFMUIsT0FBTyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsQ0FBQyIsCiAgInNvdXJjZXMiOiBbCiAgICAiLi9zcmMvbWFpbi50cyIKICBdLAogICJzb3VyY2VzQ29udGVudCI6IFsKICAgICJjb25zdCB4OiBzdHJpbmcgPSAnYWFhw7xhJztcblxuY29uc29sZS5sb2coeCk7XG4iCiAgXSwKICAibmFtZXMiOiBbXSwKICAic291cmNlUm9vdCI6ICJ3ZWJwYWNrOi8vLyIKfQo=

It also appears that breakpoints stops working when using the Filesystem feature as otherwise they are kept bound which confirms that the source-maps are being generated correctly. Therefore, this seems to be more of bug in the browser.

**Comment by markuspalme** [comment]
@alan-agius4 Thanks, that sounds reasonable. The same behavior can be observed in Chromium based browsers as well as Firefox. That makes it rather unlikely to be a browser issue though.

**Comment by alan-agius4** [comment]
@markuspalme, how to do you replicate the issue in Firefox?

**Comment by alan-agius4** [comment]
In that case I am closing this issue. I suggest you file an issue with Chrome.
