### ISSUE TITLE
feature(generate module and routes with --lazy)

### ISSUE THREAD

**Issue by JanStureNielsen** [angular/angular-cli#2279]
**Proposal**

`ng generate component --lazy home` should generate:
```
    home.component.css
    home.component.html
    home.component.spec.ts
    home.component.ts

// and new scaffolds:

    home.module.ts
    home.routes.ts
````

**Comment by aszechlicki** [comment]
there is already a ``ng generate module`` scaffold

**Comment by filipesilva** [comment]
We are currently working on this.

**Comment by Brocco** [comment]
`lazy` is not a product of a component, instead it is associated to an `NgModule`. Furthermore lazy loading of modules is configured with the routes that reference a module and because the CLI currently does not generate routes (for many reasons) this is not something that will be implemented. At least not until route generation makes sense.
