### ISSUE TITLE
Bootstrap carousel transitions are broken on production build with Angular 13.0.0

### ISSUE THREAD

**Issue by SingleEntity** [angular/angular-cli#22999]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I do not know, I have never attempted to use Bootstrap with Angular before.

### Description

I am using Windows 10, Chrome/Edge browsers behave the same.

When creating a new angular 13.0.0 project with Bootstrap 5 included, I am finding some of the bootstrap animations are failing to work on the built version when using ng build, but working correctly when using the development server via ng serve. 

In particular the carousel transitions are broken, rendering the carousel feature useless when built with Angular, and collapse animations are also non-functional.

I believe this may be related to:

https://github.com/angular/angular-cli/issues/22635

However, I didn't find the answer satisfactory, and I believe the problem may be larger than presented here as it may also include the carousel feature as mentioned.

## 🔬 Minimal Reproduction

The code is here in my SO post -> https://stackoverflow.com/questions/71903388/angular-13-0-0-possible-build-issue-with-bootstrap-5-1-3-carousel-transition-a

- Create new empty project using Angular 13.0.0
- Add Bootstrap 5 and popperjs/core to the angular.json file
- Add bootstrap carousel HTML to a component from the Bootstrap 5 carousel examples web page
- ng serve to show that bootstrap carousel is functioning as expected within the project and changing images smoothly
- ng build and host static files via nginx to show that carousel transitions are broken

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.4
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by farengeyt451** [comment]
I also have problem related to css animation, but with another lib. 
When I use `tippy.js` animation doesn't work when the first time triggering tooltip:

![tippy](https://user-images.githubusercontent.com/47389399/147224654-8d5e2b34-58b3-41d6-aae6-0694f8475127.gif)

Transition issue reprodocing in `production build`. Also I can fix it only if disable `buildOptimizer` for prod build.

**Comment by dgp1130** [comment]
This has come up before as mentioned in the original post, Bootstrap relies on side-effectful getters while build optimizer assumes they are pure and tree shakes them. Build optimizer doesn't really make optimization more strict than when `optimization` is set, the only major additional constraint applied to user code is pure getters (the assumption that all getters are pure).

If something works with `optimizations: true` and `buildOptimizer: false` but fails with `buildOptimizer: true`, then it's almost certainly a pure getters issue.

Some options you have here:

1. Use [`ng-bootstrap`](https://github.com/ng-bootstrap/ng-bootstrap) - This is a community implementation of many of the Bootstrap APIs design for Angular and pure getters compliant (AIUI). This could be a great alternative, but I don't know how hard it would be to switch to.
2. Disable build optimizer - This would turn off pure getters but also disable some code transforms and reduce the number of optimization passes, so your code will be bigger as a result. If that regression is worth it to you, then that's one thing to consider.
3. Update the code to not rely on pure getters. This is the most desirable, but may not always be possible when working with libraries not owned by you. Bootstrap for example is using impure APIs on the DOM nodes to force relayout, so finding another approach for this would probably be fairly involved.

Some longer term approaches we can consider in the Angular CLI:

1. We're thinking about moving some build optimizer functionality into `optimizations` or just enabling them all the time. This would mean that turning off build optimizer would have fewer negative impacts on your bundle size since the option would be changing less. Arguably pure getters should also just be an option directly under `optimizations`, but I don't know that we want to get that specific.
2. We could consider turning off pure getters, however when we experimented with that last it had significant bundle size regressions, so I think this is unlikely to have a viable path forward.

Given that it should be possible to work around the issue I don't think there's anything immediately actionable here. We'll investigate simplifying `buildOptimizer` as a separate task which should hopefully mitigate some of the challenges here.

**Comment by hassan0423** [comment]
Using bootstrap.bundle.min.js in index.html worked fine for me, angular build effects bootstrap.min.js in angular.json.
