### ISSUE TITLE
ng serve results in "Error"

### ISSUE THREAD

**Issue by bernhardwaidacher** [angular/angular-cli#2325]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
macOS Sierra

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I've created the project with WebStorm and then added "angular2-materialize" as described here: https://github.com/InfomediaLtd/angular2-materialize at point "Installing & configuring angular2-materialize in projects created with angular-cli@webpack (1.0.0-beta.11-webpack.8)"

4. The log given by the failure. Normally this include a stack trace and some
   more information.
This is all of the output I get: 
```
Bernhards-MacBook-Pro:fittrainerAngular Bernhard1$ ng serve
Error
```

**Comment by sinjinn** [comment]
Hello, I ran into the same issue tonight.  All files passed ng lint without issue and the red 'Error' seemed to come out of nowhere. I poked around a bit and it turned out to be a missing comma in my angular-cli.json. (in my styles array).  Since you recently included materialize, check your angular-cli.json and see. Copy/paste error for me.  Hope that can help.

**Comment by filipesilva** [comment]
You're really going to ask the maintainers at `angular2-materialize` about this error, they are the ones that made the guide.
