### ISSUE TITLE
Avoid serving legacy JavaScript to modern browsers

### ISSUE THREAD

**Issue by midzer** [angular/angular-cli#23287]
### Description

Using latest Angular 14, polyfills are injected in the DOM at the end of `</body>` with

```
<script src="polyfills.js" type="module">
```

next to all other JS.

We could improve performance by not loading those polyfills to modern browser at all. Lighthouse show this info in the report as well.

### Proposed solution

With `nomodule` in `<script>` we indicate ES2015+ browser to not load the polyfills at first. Legacy browsers on the contrary don't know this tag and load the `<script>` as usual.

More info: https://midzer.de/how-to-skip-loading-polyfills-in-modern-browsers

### Alternatives considered

Hmm, right now, I can't think of other options on how to to do it in a non-JS way.

**Comment by alan-agius4** [comment]
Indeed the `polyfills.js` contains mandatory "polyfills" that are required for the application to run, irrespective of the browser.

**Comment by clydin** [comment]
As of Angular v13 and with the remove of IE11 support, Angular no longer officially supports any browsers that would use a `nomodule` script.  Prior to v13, Angular contained a system called "Differential Loading" which not only bifurcated the polyfills but also provided the automatic building and conditional loading of ES5 and ES2015+ scripts for the application itself.  However, with the removal of IE11 support this functionality was no longer needed and has since been removed.
For additional information on how differential loading worked in previous Angular versions, please see https://v12.angular.io/guide/deployment#differential-loading
