### ISSUE TITLE
Better chunk names

### ISSUE THREAD

**Issue by ritz078** [angular/angular-cli#2351]
Angular latest release beta 15.

Currently chunk names are `0.chunk.js, 1.chunk.js` etc. This makes it difficult to figure out which bundle is for which route. It will be better if the chunk names are based on module names.

**Comment by filipesilva** [comment]
These names are auto generated and really not very relevant. Closing.

**Comment by mvareeth** [comment]
Our project was creating 5 chunk instead of 6 chunks (there are 6 modules configured in routing.module file). By commenting one by one module in the routing.module, I could find that it is generating only one chunk for two modules. It took time for me to identify which module is making this issue.  If we have a provision to provide the chunk names or create the chunk name based on the module name, that will help us while debugging.

**Comment by intellix** [comment]
I think it would also help. I'm looking at the chunks generated and trying to improve how chunks are generated and which things to include. Right now we have 0.chunk.js and 1.chunk.js and I was under the impression that a chunk was created for every Module we have. After inspecting them with source-map-explorer I found that this is actually not the case. Only a chunk is created per lazy-route rather than module. If we had better names I would have known this up-front

**Comment by born2net** [comment]
personally I don't get any chunks created, not sure if anyone has any ideas
info: https://github.com/angular/angular-cli/issues/4121

**Comment by rudzikdawid** [comment]
webpack 2.4.0 has nice Features

> import() now allows to configure a chunk name
```
import(/* webpackChunkName: "my-chunk-name" */ "module")
```

https://github.com/webpack/webpack/releases/tag/v2.4.0
