### ISSUE TITLE
npm WARN deprecated source-map-resolve@0.6.0 for @angular-devkit/build-angular package

### ISSUE THREAD

**Issue by spraju92** [angular/angular-cli#23664]
Good day, Team. In one of my Angular applications, we use @angular-devkit/build-angular, and we recently discovered a deprecated vulnerability issue with the'source-map-resolve' npm package. This'source-map-resolve' package is required by the @angular-devkit/build-angular package. As a result, we need some guidance in dealing with this situation.

**Comment by clydin** [comment]
The `source-map-resolve` is a transitive dependency of the `@angular-devkit/build-angular` package which is present due to the inclusion of the `stylus` package.
```
└─┬ @angular-devkit/build-angular@14.1.0
  └─┬ stylus@0.58.1
    └─┬ css@3.0.0
      └── source-map-resolve@0.6.0
```
The usage and/or version of the `source-map-resolve` package would need to be addressed at the `stylus`, or further, package level.  The stylus project has an issue tracking this which can be found here: https://github.com/stylus/stylus/issues/2665

**Comment by alan-agius4** [comment]
Closing as this is not actionable from our end.  It's also worth mentioning that a depreciation is not a vulnerability.
