### ISSUE TITLE
Third party lib works unless I use --prod

### ISSUE THREAD

**Issue by tomhackettishida** [angular/angular-cli#2393]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.7

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Error: Uncaught (in promise): No value accessor for form control with name: 'startDate'

5. Mention any other details that might be useful.
I'm using a third party lib (ng2-datepicker) which works when I use ng-serve, and also works when i use ng build. But as soon as I build with --prod it stops working and I get this error. Pulling my hair out trying to solve the issue, any ideas?

Thanks.

**Comment by alexsorokoletov** [comment]
@tomhackettishida we use ng2-typeahead, works just fine with prod

**Comment by tomwanzek** [comment]
I had a similar experience, possibly with the same root cause?

I published a service to inject D3 as a service (d3-ng2-service) into Angular 2, while its written in TS to published package built exports two version of the transpiled JS (ES5 target/ES 6 module) and (ES6 target/ES6 module).

When importing the service into an angular-cli (beta 15) project, there is no issue, including with the `--prod` flag.

I locally experimented with using Rollup to provide a UMD bundle as on of the builts, for other module loaders.

The experience I had was essentially the same, when linking the 'experimental' local package version. While the error message differed in detail, it only created a runtime error with `--prod`, no problem occurred in dev mode.

**Comment by filipesilva** [comment]
This was a bug we had in `webpack.2` but was fixed for `webpack.3`: https://github.com/angular/angular-cli/pull/1662
