### ISSUE TITLE
Useless installation of temporary CLI

### ISSUE THREAD

**Issue by egonknapen** [angular/angular-cli#24024]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm not sure if this should be a bug or a feature, it's more of an annoyance.

Every week when I check with 'ng update' it first complains that the CLI is outdated and starts installing a temporary CLI version, which takes a while. Then it tells me there is a new CLI version and I have to install it again with 'ng update @angular/cli', this time for real. Next time I do a 'ng update' it quickly shows me, without the delay.

Is it really necessary to install a new temporary cli version every week ?

Or maybe if there is a new one, can't we have question or a parameter to install the new CLI version (automatically), instead of installing it temporarily (and thus twice)? Just like when you type 'ng new' you also get a question.

### Minimal Reproduction

> ng update

The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.2.5 to perform the update.
√ Packages successfully installed.

### Your Environment

```text
Angular CLI: 14.2.5
Node: 16.16.0
Package Manager: npm 8.3.0
OS: win32 x64
```

**Comment by alan-agius4** [comment]
Primarily `ng update` is needed to update a to a new major version as this is typically when code migrations are added. For minor and patch updates, updating the dependencies in the package.json or refreshing the lock file will suffice. 

The temporary CLI is installed when your are using an outdated version to perform the update. The latest version is always used as the update runner. This is extremely important when there are fixes and features that affect the update process, as otherwise during the update the old version with potential bugs is used which might cause updates to fail. As such downloading the temporary version is definitely the better DX.

**Comment by egonknapen** [comment]
Which means that a batch file doing:

ng update @angular/cli
ng update

Would be the faster way to weekly check for updates of your system...

That CLI system is outdated every week.

**Comment by alan-agius4** [comment]
I strongly belief that developers should not perform dependency updates themselves (At least for non major versions).

There are a number of excellent tools that automate this, like [RenovateBot] (https://github.com/renovatebot/renovate) which can also be self hosted and thus ideal for corp environments and [DependaBot](https://github.com/dependabot).

**Comment by alan-agius4** [comment]
Following a convo with @clydin we decided that we will disable downloading a temporary version of the Angular CLI when running `ng update` without any package name. Since in this cases an update to date update executer is not neccessary.
