### ISSUE TITLE
unable to install angular-cli

### ISSUE THREAD

**Issue by eanastacio20** [angular/angular-cli#2416]
3918 verbose stack Error: not found: git
3918 verbose stack     at getNotFoundError (C:\JStudio\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
3918 verbose stack     at F (C:\JStudio\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
3918 verbose stack     at E (C:\JStudio\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
3918 verbose stack     at C:\JStudio\nodejs\node_modules\npm\node_modules\which\which.js:90:16
3918 verbose stack     at C:\JStudio\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
3918 verbose stack     at C:\JStudio\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
3918 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
3919 verbose cwd C:\Users\Eric
3920 error Windows_NT 10.0.10586
3921 error argv "C:\\JStudio\\nodejs\\node.exe" "C:\\JStudio\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@latest"
3922 error node v6.7.0
3923 error npm  v3.10.3
3924 error code ENOGIT
3925 error not found: git
3926 error Failed using git.
3926 error This is most likely not a problem with npm itself.
3926 error Please check if you have git installed and in your PATH.
3927 verbose exit [ 1, true ]

**Comment by gelliott181** [comment]
`3925 error not found: git`
You don't have Git for Windows installed. This is a requirement to properly use NPM, Angular 2, and the Angular 2 CLI.

**Comment by adam-beck** [comment]
@gelliott181 this wasn't always the case and it looks like there is only 1 dependency that is being resolved with github (`compression-webpack-plugin`). I'm assuming this version has a bug fix that was needed. So once that package is updated on npm this issue will likely be resolved. Until then this breaks for those that don't have the benefit of using git/github

**Comment by filipesilva** [comment]
There's some NPM functionality that definitely needs git, and NPM3 is a hard requirement to be able to resolve Angular 2 dependencies properly. 

It's true that only that only `compression-webpack-plugin` needs it, and that we have a temporary git dependency until a release gets cut.

**Comment by adam-beck** [comment]
> There's some [npm] functionality that definitely needs git

I don't think this is true. npm has no dependencies on a VCS to use *except* for when trying to resolve dependencies with the `git://` protocol. 

I'm not sure but since npm understands git urls (as seen below) would using `git+http://{url}` fix this issue without the need for users to have git installed? Not all companies have git available for their users (mine :-1: )

```
git://github.com/user/project.git#commit-ish
git+ssh://user@hostname:project.git#commit-ish
git+http://user@hostname/project/blah.git#commit-ish
git+https://user@hostname/project/blah.git#commit-ish
```

**Comment by filipesilva** [comment]
I *think* it wouldn't help because the repo still needs to be cloned and whatnot. Having that dependency use a git url is a temporary solution, mind you... 

We did it to avoid https://github.com/angular/angular-cli/issues/1560, and are just waiting for https://github.com/webpack/compression-webpack-plugin to officially release `0.3.2` so we can remove the git url. @TheLarkInn is on it, but until then, I don't have a good workaround for you.
