### ISSUE TITLE
SCSS Debugging issue - Could not load content for webpack

### ISSUE THREAD

**Issue by jrdutton** [angular/angular-cli#24394]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.X

### Description

When debugging the CSS in Chrome, clicking on SCSS file links results in an error (similar to the below):

Could not load content for webpack:///node_modules/bootstrap/scss/_grid.scss (Fetch through target failed: Unsupported URL scheme; Fallback: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)

This was working with version 14, not version 15.

### Minimal Reproduction

**Working** GitHub repo:
https://github.com/jrdutton/a14

**Non-Working** GitHub repo:
https://github.com/jrdutton/a15

Reproduction:
1. Run in Chrome with ng serve -o
2. Right-click on HELLO WORLD and Inspect.
3. View styles Tab and click on _grid.scss URL.
4. Error appears.

### Your Environment

**Non-Working**
```text
Angular CLI: 15.0.2
Node: 16.16.0
Package Manager: npm 8.12.2
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.7
typescript                      4.8.4
```

**Working**
```text
Angular CLI: 14.2.10
Node: 16.16.0
Package Manager: npm 8.12.2
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by jdwholmes** [comment]
We are also experiencing this problem since the upgrade. 

See screenshots below showing the issue.

![after-upgrade](https://user-images.githubusercontent.com/25403223/206469477-f885a2c0-0bc0-473a-adad-f1494ef8dd64.png)
![after-upgrade](https://user-images.githubusercontent.com/25403223/206469477-f885a2c0-0bc0-473a-adad-f1494ef8dd64.png)
![after-upgrade2](https://user-images.githubusercontent.com/25403223/206469487-d8e59748-f480-483c-b826-f500d16a409e.png)
![after-upgrade2](https://user-images.githubusercontent.com/25403223/206469487-d8e59748-f480-483c-b826-f500d16a409e.png)
![before-upgrade](https://user-images.githubusercontent.com/25403223/206469488-6f4eb1d5-2bda-4088-8a7d-c3cd78b29b7b.png)
![before-upgrade](https://user-images.githubusercontent.com/25403223/206469488-6f4eb1d5-2bda-4088-8a7d-c3cd78b29b7b.png)
![before-upgrade2](https://user-images.githubusercontent.com/25403223/206469490-438b3b9a-a472-4fde-814d-9def47e25ab5.png)
![before-upgrade2](https://user-images.githubusercontent.com/25403223/206469490-438b3b9a-a472-4fde-814d-9def47e25ab5.png)
