### ISSUE TITLE
Imported module is seen differently

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#24415]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

I'm importing `dayjs` library in my own library.
I'm importing it with 
```typescript
import * as dayjs from 'dayjs';
import * as localeData from 'dayjs/plugin/localeData';
import * as objectSupport from 'dayjs/plugin/objectSupport';
import 'dayjs/locale/pl.js';
import {Dayjs} from 'dayjs';

console.log('--dayjs--', dayjs, dayjs.extend, localeData);
dayjs.extend(localeData);
dayjs.extend(objectSupport);

``` 
It works well in that monorepository as You can see in console log

<img width="669" alt="2022-12-09_13-22-10" src="https://user-images.githubusercontent.com/420691/207027093-78fc6f14-27a4-4b11-ad64-501e755354f6.png">

After that I publish it on npm as library using:
```
    "datetime:build": "ng build datetime  --configuration production",
    "datetime:publish": "cd dist/datetime && npm publish --access public",
```

After that I import that library in my other project in which I receive errors as You can see on other screenshot. Why is it interpreted differently? Both projects are in angular@15 (I'm making upgrade from angular@13 in which everything worked great).

<img width="745" alt="2022-12-09_13-22-24" src="https://user-images.githubusercontent.com/420691/207027126-7e896738-5d9c-4da4-87bb-709ebc0c245d.png">

### Minimal Reproduction

It is complicated ;)

### Your Environment

```text
Angular CLI: 15.0.3
Node: 16.14.0
Package Manager: npm 8.5.3
OS: win32 x64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.3
@angular-devkit/build-angular   15.0.3
@angular-devkit/core            15.0.3
@angular-devkit/schematics      15.0.3
@angular/cdk                    15.0.2
@schematics/angular             15.0.3
ng-packagr                      15.0.1
rxjs                            7.6.0
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
I am able to replicate the same issue when the library is consumed in the same monorepo. 

Likely you are unable to replicate this because you are using path mappings to compile the library as part of the application. It is expected that in this case the behaviour is inconsistent due to different nature of the builds.  (See: https://angular.io/guide/creating-libraries#using-your-own-library-in-applications)

To consume this library in your librarary enable `allowSyntheticDefaultImports`, you can read more about this option here: https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports

Than you can update your code to 

```ts

import dayjs from 'dayjs';
import localeData from 'dayjs/plugin/localeData';
import objectSupport from 'dayjs/plugin/objectSupport';
import 'dayjs/locale/pl.js';

console.log('--dayjs--');
console.log({
  dayjs,
  extend: dayjs.extend,
  localeData,
});
dayjs.extend(localeData);
dayjs.extend(objectSupport);
```

I also recommend to reach out to the library author for dayjs. While this library ships an ESM version but to consume it you need to use deep imports. Using CJS/AMD/UMD bundles will cause optmization bailouts that will increase the bundle size. 

You could also consider other alternatives that can be optimized like [date-fns.](https://date-fns.org/
)

**Comment by alan-agius4** [comment]
closing as per above.

**Comment by piernik** [comment]
@alan-agius4 thanks - that worked for me!
