### ISSUE TITLE
esbuild support exports/imports resolution in package.json for type: module

### ISSUE THREAD

**Issue by wesselvdv** [angular/angular-cli#24425]
### Command

build

### Description

Would it be possible to support the resolution of exports/imports (sub)paths for type: module (https://nodejs.org/api/packages.html)

The only supported "custom" paths are currently through tsconfig. I am aware of the builtin support in esbuild for exports defined in package.json, but I reckon something isn't passed along to esbuild because it doesn't work for the builder.

**Comment by clydin** [comment]
Can you provide an example and/or a minimal reproduction demonstrating the problem you are encountering?

The Angular framework packages extensively use the package `exports` field and are also marked as module type packages.  However, package exports in general do not require the presence of the `type` field nor its value being set to `module`.

**Comment by wesselvdv** [comment]
I am trying to use the self reference capabilities of exports (`moduleResolution: Node16`) in combination with esbuild.

**Comment by clydin** [comment]
Can you provide a code example of what is being attempted to assist in replicating and troubleshooting the issue?

If you are attempting to import the root `package.json` that contains added `exports` entries then this won't work unless the TypeScript files in the entries are manually added to the compilation within the tsconfig `include`/`files` settings.
This is due to TypeScript behavior which considers those files external to the application and will not be emitted by the TypeScript compiler.  The source file is, however, correctly and fully resolved.  This situation also applies to `imports` entries as well.
The esbuild-based builder should be providing an error in these cases with a note to add the file to the TypeScript compilation.

**Comment by wesselvdv** [comment]
Looks like I was running into this issue: https://github.com/webpack/enhanced-resolve/issues/355

Now that i've applied my own fix, it works. (both webpack and esbuild)
