### ISSUE TITLE
Esbuild builder - support TypeScript path mappings

### ISSUE THREAD

**Issue by JanST123** [angular/angular-cli#24654]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As the experimental esbuild does not yet support features like [respecting the `paths` from tsconfig.json](https://github.com/evanw/esbuild/issues/394) that lack of features can be workarounded by custom esbuild plugins ([esbuild-ts-paths](https://www.npmjs.com/package/esbuild-ts-paths) in the case of the missing `paths` transforming).

But plugins can't be passed to the `esbuild.build` function yet.

### Describe the solution you'd like
Pass another option `plugins` to `esbuild.build` like it was done for the `external` option in #23322

### Minimal Reproduction

* Have paths defined in tsconfig.json
```json
  "compilerOptions": {
    "paths": {
      "@shared/*": [
        "src/app/@shared/*"
      ]
    }
  }
```

* Notice that the compiler can't find the modules imported from that paths
```javascript
import { MySharedModuled } from '@shared/shared.module';
```

* Find a plugin that can fix it: https://www.npmjs.com/package/esbuild-ts-paths
* Search a way to pass this plugin to esbuild

### Your Environment

```text
Angular CLI: 15.1.4
Node: 14.21.2
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 15.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
ng-packagr                      15.1.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
There are two parts in this issue: 
- **Support for extensibility**
 This is already been tracked in #24163
- **Support for TypeScript path mappings**
- This should likely be provided out of the box and is indeed not yet implemented.

**Comment by thaoula** [comment]
Hi @alan-agius4,

I recently tried to build our app using 15.2.0-next.4 because it included the .less support. 

I was able to build without any errors but did was not able to run due to errors in code at run time (the inherited class was undefined).

I was going to raise a bug and saw this issue. We have a similar setup where we use typescript paths so our imports @brand/xxxx ... We also have a model folder in with the @brand path that is symlinked to allow sharing with the API.

Would not having path support result in build errors or no errors at build time just runtime errors?

Regards,
Tarek
