### ISSUE TITLE
Don't duplicate assets referenced in CSS/SCSS files

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#24882]
### Command

build, serve

### Description

When referencing files in CSS/SCSS they get duplicated and placed in the root folder:

```background: url('../assets/icons/menu.svg');```

Now the file gets deployed twice:

- assets/icons/menu.svg
- menu.svg

Using an absolute path `/assets/icons/menu.svg` doesnt duplicate the files BUT it doesnt work when deployed to a sub-folder using `base-href`.

Personally I don't see any reason for that and I dont want to have all my assets deployed twice.

This was already a feature request from 2017 which had a lot of people upvoting / commenting but has been closed: 
https://github.com/angular/angular-cli/issues/6692

### Describe the solution you'd like

- Don't duplicate linked assets
- Deploying to a sub-folder using `base-root` it should still work

**Comment by alan-agius4** [comment]
Working as intended.

Please see explanation in https://github.com/angular/angular-cli/issues/19664#issuecomment-753843382


TLTR;
Don’t place your CSS resources under the assets folder.

**Comment by MickL** [comment]
@alan-agius4 Please consider this a feature request then and please reopen.

Why shouldn't I put them in the assets folder? 

- I dont want my assets to end up in the root, e.g. I have 100 icons which should end up in `assets/icons`
- I dont want my assets to be fingerprinted, this prevents them from being cached by the browser each time a new deployment runs

**Comment by alan-agius4** [comment]
> @alan-agius4 Please consider this a feature request then and please reopen.
> 
> Why shouldn't I put them in the assets folder?

Because otherwise CSS recourses will be emitted twice, once as a resource and another one as an asset configured via the `assets` option in angular.json
> 
> * I dont want my assets to end up in the root, e.g. I have 100 icons which should end up in `assets/icons`

You can use the `resourcesOutputPath` option to configure the output path of css resources.

> * I dont want my assets to be fingerprinted, this prevents them from being cached by the browser each time a new deployment runs

Unless the resource changes the hash should be the same, thus having hashes actually simplify caching and it’s invalidation. That said, if you want to disable hashing for resources, you can set `outputHashing` to `bundles` or `none`.


See https://angular.io/cli/build for more if information about build options.

**Comment by MickL** [comment]
Thanks for you explainations. Anyway I would like to see this as a feature request.
