### ISSUE TITLE
ng build --watch broken

### ISSUE THREAD

**Issue by jonnysamps** [angular/angular-cli#2511]
### OS?
> Mac OSX (El Capitan)

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.7.0 (I also tried it on 5.12.0 and 4.6.0)
os: darwin x64

### Repro steps.
1. `npm install -g angular-cli@latest`
1. `ng new build-watch`
1. `cd build-watch`
1. `ng build -w`

### The log given by the failure.
```
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Class.run (/Users/jonathansamples/projects/build-watch/node_modules/angular-cli/tasks/build-webpack-watch.js:14:26)
    at Class.run (/Users/jonathansamples/projects/build-watch/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/jonathansamples/projects/build-watch/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/jonathansamples/projects/build-watch/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/jonathansamples/projects/build-watch/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/jonathansamples/projects/build-watch/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/jonathansamples/projects/build-watch/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by denkomanceski** [comment]
same happens on Windows. There is one main reason why we would use ng build -watch over ng serve.. we need the generated map files on the disk instead of inmemory in webpack dev server so we will be able to debug from webstorm..

**Comment by splintercode** [comment]
@denkomanceski @jonnysamps to get around this run the following: 
`ng build --watch -o dist/` Adding the out param seems to fix it. We use it as well because we proxy the site and need physical files on disk.

**Comment by jonnysamps** [comment]
Good tip @splintercode. Works like a charm.

**Comment by AnthoniG** [comment]
Unfortunately it does not seem to work for me.

I have a directory called test. Inside this directory are two other directories. One for my electron program and the other an angular app built using ng new.

Now I've set my angular-cli.json to output to `"outDir": "../electron/src/gui"`

When I do a normal ng build, it creates the files as it should. However if I use ng build --watch with that directory and change anything, it does not update anything.


Btw: I am using windows7 64bit

**Comment by krabovm** [comment]
```
@angular/cli: 1.1.3
node: 8.2.1
os: linux x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.1.3
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

```
`-o` does not help.
OS: elementary
ng build -w or --watch or --watch=true compiles ones and crashes
btw with `-o` I get `The option '--o' is not registered with the build command. Run ng build --help for a list of supported options.
`
What's seems to me strange, is that It worked, I did no updates of node, cli or anything related, nothing changed, it just stopped to work. May it be due to some OS updates?

**Comment by krabovm** [comment]
```
@angular/cli: 1.1.3
node: 8.2.1
os: linux x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.1.3
@angular/compiler-cli: 4.3.1
@angular/language-service: 4.3.1

```
`-o` does not help.
OS: elementary
ng build -w or --watch or --watch=true compiles ones and crashes
btw with `-o` I get `The option '--o' is not registered with the build command. Run ng build --help for a list of supported options.
`
What's seems to me strange, is that It worked, I did no updates of node, cli or anything related, nothing changed, it just stopped to work. May it be due to some OS updates?
Sometimes it compiles twice, first time when I run the command, and then after 600ms-700ms it compiles second time with the same hash, and then stops.
