### ISSUE TITLE
Angular 16: webpack dev server show error "ResizeObserver loop limit exceeded"

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#25151]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

After upgrade from angular 15 in dev mode, webpack show error "ResizeObserver loop limit exceeded"

![immagine](https://user-images.githubusercontent.com/6096678/236483822-af6026b5-b9a8-4a3c-b505-895029efcee6.png)

This div appare in overlay.

Side note: no error into the console

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0
Node: 18.12.1
Package Manager: pnpm 8.2.0
OS: win32 x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0 (cli-only)
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0 (cli-only)
@angular-devkit/schematics      16.0.0 (cli-only)
@schematics/angular             16.0.0 (cli-only)
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by renanrider** [comment]
After some tests, I realized that the problem is apparently not with angular but with external libraries, which use ResizeObserver. As per https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors

Minimal Reproduction
Create a new app in Angular 16 using ng new proxy-test --standalone
Change the builder option in angular.json to @angular-devkit/build-angular:browser-esbuild
Add a proxyConfig to the serve configuration
Run the proxy and the application
Endpoints using the defined proxy path are not received in the proxy.
https://github.com/renanrider/repro-issue-25151

**Comment by JeanMeche** [comment]
@renanrider In your case calling `book.destroy()` in `ngOnDestroy()` fixes your issue.

**Comment by JeanMeche** [comment]
Thank you Daniel for your contribution to the issue. 

Stangely enough, the issue does not occur when I import your repo into stackblitz but it does when I run it locally.

**Comment by JeanMeche** [comment]
@json-derulo I don't think your example is a correct repro. It's actually a buggy code that is supposed to trigger this error. 

See in plain js: https://stackblitz.com/edit/js-xduijx?file=index.js

**Comment by json-derulo** [comment]
@JeanMeche I agree that my code is buggy, I was just trying to provoke the error. However according to [this SO thread](https://stackoverflow.com/q/49384120/5470544) there seem to be cases where this error is benign and isn't caused by buggy code. There is also an [ongoing discussion](https://github.com/w3c/csswg-drafts/issues/5023) whether to treat this as a warning instead.

**Comment by cesco69** [comment]
@JeanMeche on stackblitz isn't replicable because the error appears only when the webpack dev server is used
