### ISSUE TITLE
esbuild: noscript rule in head

### ISSUE THREAD

**Issue by dylanvdmerwe** [angular/angular-cli#25211]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

Testing out the new esbuild option in Angular 16. The project builds, but when trying to `ng serve` it I receive an issue with the Facebook pixel code. 

This code is copied and pasted as provided from Facebook. I see that noscript should not go in head rule, but I feel this is what people will do as instructed by the Facebook install instructions.

### Please provide the exception or error you saw

```true
7:28:55 PM [vite] Internal server error: Unable to parse HTML; parse5 error code disallowed-content-in-noscript-in-head
 at C:/Projects/Productify/WebsiteProjects/Website.Portal/productify-portal/index.html:63:5
61 |    </script>
62 |    <noscript>
63 |      <img height="1" width="1" src="https://www.facebook.com/tr?id=210205235066312&ev=PageView
   |                                                                    ^
64 |    &noscript=1" />
65 |    </noscript>
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.1
Node: 14.21.3
Package Manager: npm 6.14.18
OS: win32 x64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by clydin** [comment]
An `img` element within `head` is invalid HTML based on the specification.  Most browsers will attempt to make it work but it can have unintended effects in doing so which are silently performed.  Also, since it is not valid HTML, there is no guarantee that browsers will actually render the page.  Most HTML validation/linting tools will also flag this as a problem.
For additional information please see: https://developers.google.com/search/docs/crawling-indexing/valid-page-metadata
Performing a search for `disallowed-content-in-noscript-in-head` may also provide additional guidance on the topic.

This error is originating within Vite which is used internally as the development server.  As a result, users of Vite outside of Angular also will encounter this behavior. Please consider opening an issue with Vite if you would prefer this behavior to be changed.
