### ISSUE TITLE
[Unit Testing]  Why not use vitest instead of jest

### ISSUE THREAD

**Issue by ampmonteiro** [angular/angular-cli#25217]
### Which @angular/* package(s) are relevant/related to the feature request?

upgrade

### Description

i read in blog post about two tings:

- Better unit testing with Jest and Web Test Runner
- Developer preview of the esbuild-based build system, with vite

so my question is: why not use a tool which has better integration with vite as well as better performance ?

### Proposed solution

Replace jest by using **vitest**, which is: 
-  compatible with jest API
- better performance
- the best fit when using **vite** 

### Alternatives considered

allow the devs choose which want to by make available Jest and vitest.

Where those which:
-  dont use vite build base, it is recommend use Jest

- Otherwise vite + vitest, would be the best bet.

**Comment by pumano** [comment]
would be good to have both options

**Comment by michaelfaith** [comment]
Really appreciate the thorough response.  I had the same question myself about vitest since the bit that I've used has been a rewarding experience, and the synergy with vite seemed like a slam dunk.  But knowing, now, that Vite is used in a more limited capacity helps clarify that.  And, to your point, we've been using Jest in a significant portion of our Angular applications for years, and it's been a solid option for us (in no small part to the great work that @ahnpnl's done with `jest-preset-angular`).   So it's definitely proven to be a good at scale.
