### ISSUE TITLE
Implement vendor chunk support for esbuild builder

### ISSUE THREAD

**Issue by pumano** [angular/angular-cli#25283]
### Command

build, serve

### Description

When using esbuild builder, we got many chunks: 

![IMG_20230527_000313_004](https://github.com/angular/angular-cli/assets/17675259/9be85a3e-dd78-423e-b7ed-0161a972aae4)

but that amount (we have around 50-65) not suitable for production use cases, because of performance application degradation due to poor web vitals. That happens due to absence of vendor chunk support. Yes we got that message, when we 'serve' app:

```
The esbuild-based browser application builder ('browser-esbuild') is currently in developer preview and is not yet recommended for production use. For additional information, please see https://angular.io/guide/esbuild
The 'namedChunks' option is not used by this builder and will be ignored.
The 'vendorChunk' option is not used by this builder and will be ignored.
```

### Describe the solution you'd like

Would be good to have support of vendor chunk when all node modules libs concatenated like webpack builder do.

That dramatically changed core web vitals due to small amount of initial chunks

**Comment by alan-agius4** [comment]
For context esbuild does not support this https://github.com/evanw/esbuild/issues/207

**Comment by pumano** [comment]
@alan-agius4 yes, I see before that issue, but, in that case, `esbuild` is not suitable for production. I really test it for our large production application and see dramatic web vitals degradation. `esbuild` in that case only provide some speed of building, but ruin real web vitals totally.  Would be good if @alan-agius4 and your team can propose changes to `esbuild` for vendor chunk support.

**Comment by alan-agius4** [comment]
Hi @pumano, 

I did discuss this with @clydin, from initial testing we saw that with esbuild the lighthouse score were slightly better. 

Overall, vendor chunking should have only been used for development purposes. This only existed in the Webpack builder to workaround rebuild time issues that Webpack has. While indeed Esbuild does generate more chunks, this does not necessary mean they are all initial, and in the majority of cases this is done to return initial size which should improve CWV as Webpack's module concatenation causes a lot of unneeded code to be put in the initial chunk. 

Are you testing the lighthouse scores on a production or the Angular CLI dev-server? Testing with a dev-server can result in an incorrect scores since server config is a big part of this, such as response processing which differs greatly between vite and webpack-dev-server, compression, caching etc... It would be helpful to share your lighthouse reports.

**Comment by pumano** [comment]
@alan-agius4 I prepare lighthouse comparison for our app with webpack and with esbuild:

before:
<img width="569" alt="Screenshot 2023-05-31 at 15 32 14" src="https://github.com/angular/angular-cli/assets/17675259/714fba75-f7c9-4a03-9290-c52d6bd81f4a"><img width="680" alt="Screenshot 2023-05-31 at 15 34 04" src="https://github.com/angular/angular-cli/assets/17675259/41ac120e-0ba3-47d2-8259-9d99bd27e7c7">
<img width="694" alt="Screenshot 2023-05-31 at 15 28 08" src="https://github.com/angular/angular-cli/assets/17675259/76bc7813-b8f8-4ae0-b5ea-58cec8a10353">

after:
<img width="582" alt="Screenshot 2023-05-31 at 15 32 09" src="https://github.com/angular/angular-cli/assets/17675259/69f9c3e8-fd63-46dc-8a03-899db4d46cd4">

<img width="684" alt="Screenshot 2023-05-31 at 15 33 22" src="https://github.com/angular/angular-cli/assets/17675259/246299c4-7faa-4284-be72-fdb5928ec35f">
<img width="719" alt="Screenshot 2023-05-31 at 15 28 16" src="https://github.com/angular/angular-cli/assets/17675259/51d3a3ee-3af9-4e8a-8b83-d47b9e81281b">

**Comment by pumano** [comment]
> Any reason why you don't use HTTP 2? From the screenshots above I can see that the initial requests more than doubled, from 54 to 110 requests.

We have some limitations now, but after this issue we also trying to looking for HTTP/2

> It would we great if you could send them via discord. You can find me in [discord.gg/angular](https://t.co/98zbtEvZHJ)
I already sent you DM message

**Comment by alan-agius4** [comment]
Hi @pumano, 

We discussed the issue that you are facing and the root cause does appear to be because of using HTTP 1. 

With the new modern toolchain we recommend users using modern HTTP protocols such like HTTP/2 or HTTP/3 which nowadays are provided out of the box by the majority of hosting providers and CDNs.

In the unlikely event that you still experience poor web vitals after using HTTP/2 or 3 please open a new issue.

**Comment by pumano** [comment]
@alan-agius4 OK thank you, for detailed feedback. We will try to upgrade our infrastructure for using HTTP/2.
