### ISSUE TITLE
Add support for mercurial

### ISSUE THREAD

**Issue by Miuler** [angular/angular-cli#2529]
Hi friends, when the ng make a project for default add versioning with git, but would good the have option for indicate the system control version, for example mercurial, and to change the default svc (~/.ngrc < svc = hg or git).

### OS?
Linux (archlinux)

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64

**Comment by gelliott181** [comment]
I'm not really big on this. Git is a prerequisite for proper NPM functionality, and while everyone has a preference in version control software, Git is the only one that is guaranteed* to be available in a fresh environment. In addition, the Git repo initially set up can always be nuked and replaced with a Mercurial repo at your discretion. Nothing about automatically initializing a Git repo at install means you're required to use Git from that moment on.

*I say guaranteed because if you don't have it, there's a high probability you'll encounter errors pulling dependencies on some projects.

**Comment by Meligy** [comment]
I agree with @gelliott181.

There's already a flag for `ng new` that reads `--skip-git`. You can use that, and then add the project to your preferred source control system. This should be enough I think.

**Comment by splintercode** [comment]
As someone who does use mercurial with the CLI I would say this is unnecessary and adds unneeded complexity to the CLI. The `--skip-git` seems sufficient enough.

**Comment by filipesilva** [comment]
I understand there are other good VCS around, but we're mostly offering the git initialization as convenience, with `--skip-git` as an escape hatch. 

We're not looking to add support for other VCS because it's quite trivial to initialize the repository manually as well.

The exception is the `github-pages:deploy` command which makes heavy use of git commands, but on the other hand it also requires github.
