### ISSUE TITLE
node_path not working with angular cli

### ISSUE THREAD

**Issue by hjackows** [angular/angular-cli#25302]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We can't check in our node modules in our build gitlab based on company policy they are much too large.
When node_modules are in the project folder ng build works 
When node modules are in a parent directory ng build works 
When we move node_modules to a different folder and set set NODE_PATH=D:\henryNodeModules\node_modules
We get error node_modules cannot be found for example 
 Cannot find module '@angular/core' or its corresponding type declarations.
Noticed previous similar issue :
https://github.com/angular/angular-cli/issues/3864

Any workarounds fixes 
Using v18.16.0

### Minimal Reproduction

Do any ngbuild and move node_modules 

### Your Environment

```text
Angular CLI: 15.2.7
Node: 18.16.0
Package Manager: npm 9.5.1
```

**Comment by clydin** [comment]
`NODE_PATH` is not supported with ESM code (https://nodejs.org/api/esm.html#no-node_path). As more and more of the ecosystem shifts to ESM, `NODE_PATH` will no longer be a viable option for most projects.
Node.js also strongly recommends using a local `node_modules` directory (https://nodejs.org/api/modules.html#loading-from-the-global-folders).

The `node_modules` directory is also very rarely checked into a repository.  Typically, the package lock file is checked in to ensure consistent package layout and versions but otherwise an install is performed after a clone/checkout of the repository to create/populate the `node_modules` directory.

**Comment by wartab** [comment]
One possible solution is to use a symlink/shortcut to the node_modules folder you want.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
