### ISSUE TITLE
Watcher doesn't recover from `function foo(): {[foo: number] {}`

### ISSUE THREAD

**Issue by sod** [angular/angular-cli#25581]
### Command

serve

### Description

paste `function foo(): {[foo: number] {}` anywhere in a typescript file and the watcher crashes and won't recover with an error like:
<img width="1649" alt="CleanShot 2023-07-25 at 13 33 07@2x" src="https://github.com/sod/ng16-issue-throwing-syntax/assets/905328/73276ba9-edb8-421b-b48f-1ffc05e1bf4d">

You have to fix the code and restart the watcher.

### Minimal Reproduction

https://github.com/sod/ng16-issue-throwing-syntax

### Expected behavior

Don't have to restart `ng serve`. Fixing the code should rebuild.

### Your Environment

```text
Angular CLI: 16.0.6
Node: 18.16.1
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.0.6
@angular/cli                    16.0.6
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by clydin** [comment]
NOTE: Rebuilds work as expected with this scenario when using the esbuild-based build system currently in developer preview.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
