### ISSUE TITLE
MacOS terminal stuck due to ng completion script

### ISSUE THREAD

**Issue by nouraellm** [angular/angular-cli#25608]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I just tried creating an app with `npm init` and started it then, I could not use a new window of the terminal ... a workaround is to kill the process in the activity monitor.

<img width="776" alt="Screenshot 2023-07-30 at 14 13 38" src="https://github.com/angular/angular/assets/26191219/526f2b55-d653-46da-8674-37e3ced80e3d">

But such a thing shouldn't happen.
I am using MacOS Venture 13.3.1 M1 

### Please provide the exception or error you saw

```true
no error, just the terminal being stuck
```

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 14.2.6

### Anything else?

Node: 19.4.0

**Comment by dgp1130** [comment]
I think all we do for `ng completion script` is [delegate to Yargs](https://github.com/angular/angular-cli/blob/bcdd0a73c4e43dd3750ea866f8c71dadd188865e/packages/angular/cli/src/commands/completion/cli.ts#L72C18-L72C18). Unfortunately I don't have a Mac on hand to try to reproduce this issue.

Are you able to get a stack trace of the hanging code? Ctrl+C might print that. Otherwise you could just run the command directly and attach a debugger:

```shell
NODE_OPTIONS="--inspect-brk" ng completion script
```

When the debugger is attached and the program is hanging you should be able to pause it to see the stack it's stuck at.

**Comment by alan-agius4** [comment]
Also it could be great if you can try this using Angulae CLI version 16+.

**Comment by nouraellm** [comment]
Unfortunately, I couldn't reproduce the issue again...
Thanks for your input!
