### ISSUE TITLE
[Feature] Reduce dependencies on nodejs for the CommonEngine

### ISSUE THREAD

**Issue by cromefire** [angular/angular-cli#25718]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] builders
- [x] common
- [ ] express-engine

### Description

I'd like to use Angular server side outside of nodejs, because it's intended to be delivered via web frameworks or gateways (like Spring or ASP.NET Core), but those are often not in nodejs.

In my case I'd like to be able run Angular on something like GraalJS (GraalVM can run both JVM and JS) or maybe with some WASM-based JS engine to directly integrate with the backend applications.

The current state with something like GraalJS actually doesn't look too bad, but it's pretty hard to build drop-in replacements for all the things and debug all of that.

### Describe the solution you'd like

I don't have the overview, whether this is even possible, but what I'd imagine ideally would be some sort of `RuntimeAdapter` interface that specifies all the host features required by the `CommonEngine` and then a `NodeJsAdapter` that is passed by default and implements everything using all the functions currently implemented using nodejs built-in modules and then one can optionally specify a custom adapter that works for their environment, whatever that may be.

### Describe alternatives you've considered

Patching all the nodejs built-in modules with custom implementations is kinda maybe possible, but it's quite the project and kinda fragile and messy and definitely not safe from breaking changes.

### Scope

This issue is about the core engine not depending on node.js. It is not about alternative platforms this engine could be used in **nor is the goal** for Angular **to provide any Integrations with specific platforms**. It is merely **the option** to have the **APIs** so that either **all developers** or the Angular team itself can even entertain to build those kinds of platform support.

**Comment by alan-agius4** [comment]
I do agree that we need to reduce dependencies on Node.js APIs, although most of these come from critters.

That being said, you can do server side rendering with cloudflare workers https://developers.cloudflare.com/pages/framework-guides/deploy-an-angular-site/

**Comment by MickL** [comment]
That doc is for a normal Angular site, not a Angular Universal SSR app

**Comment by alan-agius4** [comment]
`npm create cloudflare@latest my-angular-app -- --framework=angular` will create and configure an Angular SSR application with all the necessary things to be deployed on a cloudflare worker.

**Comment by cromefire** [comment]
They seem to shim the NodeJS API, maybe a good workaround for now: https://github.com/cloudflare/workers-sdk/blob/36d497829972667852bbcaacebcb22124d73d765/packages/create-cloudflare/src/frameworks/angular/templates/tools/bundle.mjs#L19

**Comment by cromefire** [comment]
I think you might have to add SSR yourself, because I see references to it in the source code of the CLI, but the documentation is really confusing...

**Comment by MickL** [comment]
Maybe they tried to make it work without success but in the docs there is no word to Angular Universal or SSR and the command that @alan-agius4 stated creates just a regular Angular app like `@angular/cli new` does.

**Comment by alan-agius4** [comment]
@MickL, in the above screenshot, I am not even seeing any chances done by CloudFlare such as the creation of the `tools` directory.

Here's what I am seeing
```
tree -L 2
.
`-- my-angular-app
    |-- angular.json
    |-- node_modules
    |-- package.json
    |-- package-lock.json
    |-- README.md
    |-- src
    |-- tools
    |-- tsconfig.app.json
    |-- tsconfig.json
    |-- tsconfig.server.json
    |-- tsconfig.spec.json
    `-- yarn.lock
```

**Comment by MickL** [comment]
Another thing that is not working is Vercel Edge Functions:

> Error: The Edge Function "api/index" is referencing unsupported modules:
>        - dist/server/main.js: crypto, fs, http, https, net, os, path, querystring, stream, string_decoder, timers, tty, url, zlib, node:fs, node:path

**Comment by jdgamble555** [comment]
This is definitely a huge problem.  If Angular Universal (not Angular) does not support Edge Function deployment, which is a Deno deployment, it will never truly be able to compete and adopted by people coming from other frameworks.

J

**Comment by oriollpz** [comment]
Any news on how to deploy an Angular +16 SSR app into Vercel/Denodeploy/Cloudfare?

**Comment by piyushpranjal03** [comment]
I recently deployed angular ssr 16 on EC2 with Github Actions and previously deployed on vercel using this [guide](https://dev.to/jdgamble555/how-to-deploy-angular-universal-to-vercel-31d0). It was working find on vercel but the **Initial sever response time** was around 2 -3 second. So I migrated from there after 1 day

**Comment by MickL** [comment]
Angular Universal runs on Vercel but not on Serverless Edge Workers like Vercel Edge Functions, Deno Deploy or Cloudflare Workers.

**Comment by jdgamble555** [comment]
@piyushpranjal03 - Hi Pi, I wrote that guide :)

The reason it takes 2-3 seconds, is because Vercel itself is Serverless using AWS Lambdas under the hood.  It only takes 2-3 second on the first load of the bucket, which is the cold start time.  AWS Lambdas are way faster than Cloud Functions (although paying more for faster servers could change that).

Vercel Edge, on the other hand, does not use serverless functions, but the Edge Network, which would load extremely fast.  However, Angular Universal will not load on the edge due to the Express dependencies (the point of this post).

Fix this problem, and Angular Universal can run on the Edge (no cold starts or serverless), and it would be extremely fast on a CDN... just like you can do with literally every other SSR framework.  (technically the edge is considered serverless without cold starts, but completely different infrastructure)

J

**Comment by piyushpranjal03** [comment]
Thanks for the guide @jdgamble555 .
Yeah now I'll move my app to cloudflare directly will wait until the proper SSR deployment is not available there.

**Comment by joseph-simpson** [comment]
npm create cloudflare@latest my-angular-app does work now (it didn't work for me the last time I tried some weeks ago).  

main.server.ts looks like this:

```
import "zone.js/dist/zone-node";
import "@angular/platform-server/init";

import { bootstrapApplication } from "@angular/platform-browser";
import { renderApplication } from "@angular/platform-server";

import { AppComponent } from "./app/app.component";
import { config } from "./app/app.config.server";

interface Env {
	ASSETS: { fetch: typeof fetch };
}

// We attach the Cloudflare `fetch()` handler to the global scope
// so that we can export it when we process the Angular output.
// See tools/bundle.mjs
(globalThis as any).__workerFetchHandler = async function fetch(
	request: Request,
	env: Env
) {
	const url = new URL(request.url);
	console.log("render SSR", url.href);

	// Get the root `index.html` content.
	const indexUrl = new URL("/", url);
	const indexResponse = await env.ASSETS.fetch(new Request(indexUrl));
	const document = await indexResponse.text();

	const content = await renderApplication(
		() => bootstrapApplication(AppComponent, config),
		{ document, url: url.pathname }
	);
	// console.log("rendered SSR", content);
	return new Response(content, indexResponse);
};
```

and the tools folder contains the Cloudflare shims/magic to make it work.

Watching the [Angular 17 announcement video](https://www.youtube.com/watch?v=Wq6GpTZ7AX0) I was excited to see just how committed the Angular team are to SSR (and SSG), including non-node environments on the edge.  Especially with Angular Universal being rolled into core and a better DX.

**Comment by cromefire** [comment]
> the tools folder contains the Cloudflare shims/magic to make it work

Yeah well, that's the big honey, that that isn't needed anymore, as it doesn't sound too stable of a foundation...

**Comment by MickL** [comment]
> I was excited to see just how committed the Angular team are to SSR (and SSG)

They NEED to be. Angular is already left behind and I dont see them catching up to Next and Nuxt anymore. After 7 years of being an Angular developer I just tried out Vue and Nuxt for the first time and I am simply amazed by how easy it is (no classes, no DI, auto imports, runs everywhere, file based routing, build a server rest API directly in Nuxt, etc. etc.) and also by the eco system around it.

**Comment by cromefire** [comment]
> no classes, no DI

Well but that's why there are different frameworks to choose from. I find both of them to be very important to me for big enterprise applications. But yes SSR on the edge is a must.

**Comment by piyushpranjal03** [comment]
Hi @alan-agius4 any updates on this? ETA or anything?

**Comment by alan-agius4** [comment]
The `@angular/ssr` at the moment common engine indeed has a strict requirement for Node.js due to Critical CSS inlining. However, this does not mean that Angular SSR does not work on Edge workers. Edge workers are supported and in fact we did recently work with both Netlify and CloudFlare to support Angular version 17.

We will continue to improve Edge worker compatibility and integrations with providers in the coming versions.

**Comment by jdgamble555** [comment]
@alan-agius4 - I think a lot of people use Vercel for their projects, which is why this is a problem for me specifically. Perhaps there could be a `deno`, `bun`, and `node` build version respectively. I think [vite handles this](https://vitejs.dev/guide/features#import-inlining-and-rebasing) automatically, so this is really a `esbuild` problem and should be fixed there I believe. That way it could be removed all together in angular/ssr, and just added to the build process.

J

**Comment by alan-agius4** [comment]
@jdgamble555, we actually did reach out to Vercel, to work with them to support SSR. Unfortunately in the near term they do not have a priority to add support for Angular SSR/SSG.

I think you might have sent an incorrect vite link above, as it links to CSS processing.

**Comment by cromefire** [comment]
> Perhaps there could be a deno, bun, and node build version respectively.

Would be good if it's modular enough though to support other stuff as well. I'd want to use it from GraalVM, which works differently again. Or maybe you'd want to use it as a portable WASM/WASI module or something like that. It needs to be flexible.

**Comment by jdgamble555** [comment]
@alan-agius4 - The CSS preprocessing will inline the CSS in the page. It is actually [automatic](https://vitejs.dev/guide/features#disabling-css-injection-into-the-page), but yes uses `postcss`.
> Vite is pre-configured to support CSS @import inlining via postcss-import.

Yeah, I think `esbuild` somehow should be more versatile and support any build environment, but I think `ssr` should be separate from the build process like vite... probably (definitely not my specialty). As long as the environment problem gets solved, how it is solved is irrelevant to me.

As far as **Vercel**:

When writing my article on [deploying to Vercel](https://dev.to/jdgamble555/how-to-deploy-angular-universal-to-vercel-31d0), and actually wanting to deploy to Vercel for my blog back then, I actually reached out to them.

They told me they don't support any 3rd party integrations, as it is up to the Framework creator and the community to create adapters that work with Vercel deployments. However, they had a specific problem with Node.js server, quoting them from December 28, 2021:
> Unfortunately, there are no plans to add this since this is using a Serverless Function to start your server on Vercel, instead of a Node.js server, making this not ideal.

I proved them wrong by [making it work](https://dev.to/jdgamble555/how-to-deploy-angular-universal-to-vercel-31d0), as I honestly think there was an ignorance on Vercel's behalf. They literally told me that since I did not have an adapter like [nuxt vercel-build](https://github.com/nuxt/vercel-builder), they would not add it to the list. I did not want to take the time to build one, and frankly just switched away from Angular at that time due to the long build times for Angular Universal. 

I think you guys could build one now easily, but it would not work for Edge functions until the Node.js dependencies are removed, which would solve all problems at hand.

J

**Comment by naveedahmed1** [comment]
I am receiving below error when trying my app on cloudflare:

```
http
X [ERROR] ERROR Error: Dynamic require of "http" is not supported
```

**Comment by jdgamble555** [comment]
@alan-agius4 - Are you guys going to be able to work on Vercel? As I mentioned above, you would need to build a Vercel adapter like the [nuxt-adapter](https://github.com/nuxt/vercel-builder). Again, getting rid of these dependencies all together and opening up the code to run on any JS environment would be ideal and would probably make Vercel more excited to support Angular SSR.

J

**Comment by jdgamble555** [comment]
@alan-agius4 - Is this still on the radar so we can at least deploy to Vercel Edge?

J

**Comment by ProximaB** [comment]
Is there anywhere listed what edge functions providers are supported with ssr? Right now it is Cloudflare and Netlify?

**Comment by Pii2** [comment]
> Is there anywhere listed what edge functions providers are supported with ssr? Right now it is Cloudflare and Netlify?

Cloudflare works, but only without critical css inlining

**Comment by jdgamble555** [comment]
@alan-agius4 - Are you guys still working on this for Vercel / other node-less environments?

**Comment by jer-tx** [comment]
> we did recently work with both Netlify and CloudFlare to support Angular version 17.

@alan-agius4  Can you expand on this? There's zero documentation anywhere of how to make Pages work with SSR. It isn't clear within Pages how to make this work.

**Comment by alan-agius4** [comment]
@jer-tx, please check out cloudflare docs. https://developers.cloudflare.com/pages/framework-guides/deploy-an-angular-site/

**Comment by nunoarruda** [comment]
Been trying to deploy an Angular SSR app for several days now but encountering several issues, even with the Cloudflare version of Angular SSR.

After addressing the node-dependent critters, I would also suggest the Angular team to try replacing the Express server with a more cross-platform/cross-runtime framework, if possible. This way Angular SSR could be deployed on Cloudflare, Fastly, Deno, Bun, AWS, Node.js, etc

I have 2 suggestions: [Hono](https://hono.dev/) or [Nitro](https://nitro.unjs.io/).

**Comment by cromefire** [comment]
> After addressing the node dependencies, I would also suggest the Angular team to try replacing the Express server with a more cross-platform/cross-runtime framework

That's not even necessary, in the common engine there's basically just a function to which you provide one URL and it'll return a rendered string. No need to "integrate" any other web server, it's all just configuration. And if you wanna simply that, no one stops you from publishing an NPM package building on you favorite web server and the common engine, it's super easy.

**Comment by jdgamble555** [comment]
@cromefire - This is unhelpful here. This needs to be part of the Angular/SSR package itself. As @nunoarruda said, there are many servers that don't support Angular out-of-the-box without changing to Vite etc (which no guide to do so btw). None of this is easy to do. Angular is the only mainstream Framework that doesn't work for basic deployment (NextJS, Remix, Nuxt, Astro, Solidstart, QwikCity, SvelteKit, Preact, Gatsby, etc) options. It's not just Edge Deployment that is the problem but all other options due to this issue request.

This should be built into the main code.

J

**Comment by cromefire** [comment]
> @cromefire - This is unhelpful here. This needs to be part of the Angular/SSR package itself. As @nunoarruda said, there are many servers that don't support Angular out-of-the-box without changing to Vite etc (which no guide to do so btw). None of this is easy to do. Angular is the only mainstream Framework that doesn't work for basic deployment (NextJS, Remix, Nuxt, Astro, Solidstart, QwikCity, SvelteKit, Preact, Gatsby, etc) options. It's not just Edge Deployment that is the problem but all other options due to this issue request.
> 
> This should be built into the main code.
> 
> J

So what you are telling me is that something like
```javascript
app.map("**", async ctx => {
    return await commonEngine.render(ctx.path);
});
```
is too hard? Please... I hope you see how silly that is...

If you're not able to make one function call in your framework of choice, you probably shouldn't use that framework.

**Comment by jdgamble555** [comment]
Yes, I have no idea what any of that does. I can easily guess, but I shouldn't have to configure all that. It certainly isn't in the docs. You're missing the point of this thread.

J

**Comment by cromefire** [comment]
> Yes, I have no idea what any of that does.

Then you should read the docs for the common engine & SSR. If there's any problem at all it's documentation, which is completely out of scope for this issue.

> You're missing the point of this thread. 

You're missing the point of the issue. It has a very narrow, specified goal and that doesn't include any frameworks, but the **CommonEngine** specifically and is not supposed to devolve into a fight over how and which Integrations for SSR should be done. If you want to have that discussion, open a discussion or another issue.

> but I shouldn't have to configure all that

Well if 3 loc (which like describing 3 loc as "all that" is really quite the stretch, try to configure an ASP.NET project with a DB or so, that could be described as "configure all that") is too much for you, I guess find another framework... Low code has very little code I heard...

**Comment by naveedahmed1** [comment]
To deploy your Angular application with Server-Side Rendering (SSR) on Cloudflare Pages, follow these steps:

1. Begin by initiating the Cloudflare project setup using the command  `npm create cloudflare@latest`.

2. Choose the desired directory or path where you wish to create your project.
 
3. Select `Website or Web App` when prompted.
 
4. Specify `Angular` as your preferred development framework during the setup process.
 
5. Select the appropriate Angular CSS configuration for your project. 

This will install all necessary dependencies.

6. You'll be asked if you want to deploy the project to Cloudflare. Choosing `Yes` will initiate the creation of a Cloudflare project, deploy your application, and provide a deployment URL for testing purposes.

Alternatively, if you opt for `No`, you can deploy your project at a later stage using the `npm run deploy` command within your project directory.

To locally test your project, execute the command `npm run start` on your machine.


**Familiarize yourself with few things:**

**server.ts File**:
This file is responsible for executing your Angular application. It contains a `workerFetchHandler` function, which leverages Angular's `renderApplication` function to launch your Angular app on the server. This process generates HTML markup corresponding to the current URL.

**Tools Folder**:
Within this folder, you'll find a collection of scripts. These scripts are executed upon completion of the Angular build process. They handle tasks such as preparation and copying of files to the Cloudflare directory. Take a look at the scripts section in the `packages.json` file for further details.

**`_routes.json` File in `src` Folder:**
This file serves to inform Cloudflare about routes requiring Server-Side Rendering (SSR) and those to be excluded from SSR. Routes designated for SSR are processed by Cloudflare Workers, while excluded routes are served directly by Cloudflare Pages.

**Custom HTTP Status Code or Headers:**
Should the need arise to set custom HTTP status codes or headers, you'll need to update the server.ts file. Pass ResponseInit as platform providers to configure these settings. Follow these steps:

Update the renderApplication function as illustrated below:

```
const responseInitOptions: ResponseInit = { status: 200, headers: headers };

const content = await renderApplication(bootstrap, {
  document,
  url: url.pathname + queryString,
  platformProviders: [
    { provide: RESPONSE_INIT_OPTIONS, useValue: responseInitOptions }
  ]
});
```

Define the injection token `RESPONSE_INIT_OPTIONS` in a TypeScript file:
```

import { InjectionToken } from '@angular/core';
export const RESPONSE_INIT_OPTIONS = new InjectionToken<ResponseInit>('RESPONSE_INIT_OPTIONS');

```

Inject `RESPONSE_INIT_OPTIONS` into your Angular app:

```
private readonly responseInitOptions = inject(RESPONSE_INIT_OPTIONS, {
  optional: true,
});
```

**Set the HTTP status code:**

`this.responseInitOptions.status = statusCode;`

Configure custom headers:

```
let newHeaders = {
  'X-Robots-Tag': 'noindex',
  'Content-Type': 'text/html; charset=utf-8'
};

this.responseInitOptions.headers = newHeaders;

```

Thus far, the sole obstacle I've encountered pertains to https://github.com/cloudflare/workers-sdk/issues/5262; notwithstanding, the overall procedure appears remarkably straightforward. My commendations to both the Angular and Cloudflare teams especially @alan-agius4 @petebacondarwin for facilitating such a seamless process. 
 
Should you require any assistance, please do not hesitate to reach out.

**Comment by nunoarruda** [comment]
@naveedahmed1 for your information or for your curiosity I've also found this obstacle: https://github.com/cloudflare/workers-sdk/issues/5263

**Comment by naveedahmed1** [comment]
@nunoarruda have you updated `provideHttpClient` and using `withFetch`:

```
 provideHttpClient(
  withFetch()
),
```

https requests are working fine with `"prerender": false`

**Comment by nunoarruda** [comment]
@naveedahmed1 it's an Angular app generated with `create cloudflare`, it already comes with `withFetch` configured:

`providers: [provideHttpClient(withFetch()), provideRouter(routes), provideClientHydration()]`

**Comment by naveedahmed1** [comment]
Yes you are right, and this config seem to be working fine in my case with `"prerender": false`

**Comment by jdgamble555** [comment]
Hey guys,

Thank you for the help. You can definitely keep stripping Angular to its core to get it to work in any scenario (it is just JS after all), but there are no docs for this (I have asked for docs many times btw), it is not easy (or you would see at least one article on how to deploy to Vercel Edge outside of Analog), and it is the only Framework that requires crazy custom configurations for basic deployment options (anything outside of NodeJS). Why do you think the Cloudflare deployment option is so custom. So yes, this is a problem when things like `os`, `path`, `crypto`, etc. being in the way by default.

I wrote an article about all this when it comes to deployment problems: [The State of Angular SSR Deployment](https://dev.to/jdgamble555/the-state-of-angular-ssr-deployment-in-2024-17jb). You can deploy to Cloudflare, but the Inline Critical CSS does not work.

- [Cloudflare Edge Example](https://angular-cloudflare-cjz.pages.dev/)
- [Analog Vercel Edge Example](https://analog-test-mu.vercel.app/)

If you compare the examples, you can see a Cumulative Layout Shift (CLS) problem on the Cloudflare version because the Critical CSS is not loaded inline (from my understanding this is why). If Cloudflare now works let me know.

In a perfect would, you would just say:
- `ng add @angular/deploy-cloudflare`
- `ng add @angular/deploy-vercel`
- `ng add @angular/deploy-netlify`
- `ng add @angular/deploy-cloudrun`

But maybe we just need this:
- `ng add @angular/deploy-wasm`
- `ng add @angular/deploy-deno`
- `ng add @angular/deploy-bun`
- `ng add @angular/deploy-nodejs`

etc, etc...

There would be options for `serverless` or `edge`. `serverless` would automatically code split into functions like NextJS does, or it would load immediately etc. There could be a mixture of options.

If you open a similar issue, it will probably get closed and point back to this issue FWI. This is the core of the deployment problem. This post is about SSR, not regular Angular problems.

**Comment by cromefire** [comment]
@jdgamble555 That's nice and all and you can try to plead with the Angular team to implement that **after** this has been fixed (I mean you can open an issue now and if you don't want it closed, just reference this issue and explain that it expands this issue and how and that it depends on it). But right now this is cluttering the issue and I feel like y'all are trying to expand the scope of this issue with you specific grievances, which only leads to one result: It'll never get done.

So please just keep this out of here and be patient as you can do anything without this being solved anyway. All this talk about Cloudflare and other integrations has just cluttered this issue and yet there has been no substantial progress. This leads to nothing. If you focus on which platforms work and which don't or "I want this to be integrated or that" you'll end up with something like the Cloudflare solution, which works now, great, but only for Cloudflare and it's hacky and didn't address the root cause at all... There's a reason I didn't open an issue for "Running Angular SSR on GraalJS", because there a more common problem here which is exactly why I want a general solution for this and resolve the root cause, instead of trying to aka for specific platforms. The platforms are easy in the end the Angular team can decide to provide more integrations or not, there'll be other people who take care of that, but all hinges on this very issue first.

I've clarified the scope of this issue in the description, so please keep it in scope and for everything else just open another issue or a discussion with a different scope...

**Comment by pxPP** [comment]
A colleague and I tried to identify and eliminate the dependencies to node in order to make the inline CSS executable in Cloudflare Workers.

We came across the following packages:

[https://www.npmjs.com/package/critters](https://www.npmjs.com/package/critters)
[https://www.npmjs.com/package/picocolors](https://www.npmjs.com/package/picocolors)
[https://www.npmjs.com/package/postcss](https://www.npmjs.com/package/postcss)

The customisation for critter was relatively simple, we were able to replace the native node fs method with a callback and use Cloudflare ASSETS.fetch.

With Picolor, the dependency on tty was a particular problem, which we were able to solve in the first step by using string replace in the bundle 🙈

However, the dependencies on node within PostCSS, especially for the source maps, were then embedded too deeply.

Presumably a dedicated CriticalCSS implementation is needed for non-node environments.

So unfortunately the experiment has failed for the time being :(

**Comment by cromefire** [comment]
> The customisation for critter was relatively simple, we were able to replace the native node fs method with a callback and use Cloudflare ASSETS.fetch.\n\nWith Picolor, the dependency on tty was a particular problem, which we were able to solve in the first step by using string replace in the bundle 🙈

That sounds pretty cool maybe one could already get this into Angular (Using callbacks of course instead of the specific Cloudflare stuff)? Or did you only replace it after the fact in the finished bundle?

**Comment by pxPP** [comment]
We have changed critter so that it uses a callback instead of calling node fs directly. We then pass the Cloudflare methods in our server ts file. This works great. But it also seems to be only a small piece of the puzzle.

I think that postCSS is the very critical dependency.

**Comment by cromefire** [comment]
> We have changed critter so that it uses a callback instead of calling node fs directly. We then pass the Cloudflare methods in our server ts file. This works great. But it also seems to be only a small piece of the puzzle.

Most definitely, but a small part of the puzzle would already be one part at least and one is better than none.

**Comment by naveedahmed1** [comment]
Thank you @alan-agius4 for the amazing work! Can you please also share if this change requires any updates to existing Angular Cloudflare Worker hosted app?

**Comment by alan-agius4** [comment]
To use the new API, there will be some minor changes needed. More information to follow at a later stage.

**Comment by naveedahmed1** [comment]
And just to confirm, its a non breaking change, I mean if we just update the angular version to the newer version in our app it will still work, correct?

**Comment by alan-agius4** [comment]
Yes
