### ISSUE TITLE
src/styles.scss compression

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#2578]
Hi, I put all my components styles in `src/styles.scss` where I import other styles in it

``` css
@import 'style/vendors/_base';
@import 'style/core/_base';
@import 'style/modules/_base';
```

I do this to gain access to variables and mixins, but it appears that the CLI doesn't compress it before adding it to the head, is this intended or will it be fixed in the future?

**Comment by filipesilva** [comment]
Hm, can you elaborate on what you mean by this bit?
> the CLI doesn't compress it before adding it to the head

**Comment by MurhafSousli** [comment]
@filipesilva  I mean the file `src/style.scss` doesn't get minified

**Comment by filipesilva** [comment]
Got it. Will investigate.

**Comment by dannyk08** [comment]
having the same issue on v1.0.0-beta.17
styles.scss is not being processed into css

**Comment by filipesilva** [comment]
Partially solved by https://github.com/angular/angular-cli/pull/2593

**Comment by grizzm0** [comment]
The CSS is minified. See the output style.js in your build dir.

What you're seeing in the head is the CSS from the JS file appended to head by the webpack plugin style-loader. This will be changed in #2646 as "outside of app" styles will compiled to a .css file instead of .js.

@filipesilva Can be closed.
