### ISSUE TITLE
Angular CLI can be easily broken when external dependencies update

### ISSUE THREAD

**Issue by The-MAZZTer** [angular/angular-cli#25844]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Unknown, probably none.

### Description

I observed this issue blocking creation of new Angular projects today:

https://github.com/babel/babel/issues/15967

It has since been fixed, but the babel team should not be able to break basic Angular CLI functionality. It is a bad look if someone goes through the basic project creation steps on the Angular site and they don't work. Doesn't matter who is the blame, the user will blame Angular. Angular team should take steps to ensure this does not happen, such as by locking down versions of dependencies until new ones are tested and verified working, or some other solution.

### Minimal Reproduction

Run ng new command while a dependency has been broken by a third party.

### Exception or Error

```text
https://github.com/babel/babel/issues/15967

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/types@^7.22.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in blah blah blah blah
x Package install failed, see above.
The Schematic workflow failed. See above.
```

### Your Environment

```text
Angular CLI: 16.2.2
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular:
...

@angular-devkit/architect 0.1602.2 (cli-only)
@angular-devkit/core 16.2.2 (cli-only)
@angular-devkit/schematics 16.2.2 (cli-only)
@schematics/angular 16.2.2 (cli-only)
```

### Anything else relevant?

Given the nature of how the error is presented it is impossible for the user to know where the problem is coming from (@babel/types is not directly referenced in the generated package.json; I assume it's coming from @babel/core but I can't tell since npm doesn't tell you!) or what steps they can take to work around it (probably none?)

**Comment by nicolo-ribaudo** [comment]
Unfortunately due to the nature of the npm ecosystem this is incredibly difficult. There are two possible solutions:
- include a committed lockfile as part of `ng new`
- bundle all the dependencies

The first one is better, as it still allows users to independently update their (transitive) dependencies while providing a known-working initial setup. However, it requires much more maintenance form the angular team since they have to release a new version of the lockfile whenever a transitive dependency has an update (which probably means, to setup a cronjob running every 12 hours and automatically publish it if tests pass).

**Comment by alan-agius4** [comment]
As @nicolo-ribaudo mentioned, the NPM eco system is rather complex and it’s hard to control transitive dependency versions. While a shinkwrap file can be an option, AFAIK it is not supported by all package managers.

Bundling of dependencies is something our radar and we want to look into it more sometime in the future for various reasons.

Ultimately however, this issue is not really actionable from our end at this stage as the problem was also swiftly fixed upstream by the Babel team (Kudos to them), and such breakages are extremely rare.

**Comment by The-MAZZTer** [comment]
Fair enough. At the very least I wanted to be sure the angular team was aware of this blip and how it affected basic functionality of the angular cli.

One approach I thought of is to simply monitor which packages tend to have stability issues like this, and how often, to take corrective action on an as-need basis if it seems warranted. Such action could be to lock down versions for these specific packages (or those that depend on them, if that would help) or to transition away from those packages or packages which depend on those packages to alternatives.

**Comment by alan-agius4** [comment]
@The-MAZZTer, we already follow a pinned version policy as you can see for yourself https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/package.json unfortunately this only effects direct dependencies.
