### ISSUE TITLE
esbuild-builders: broken websocket proxy

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#26151]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16

### Description

Hi.
Websocket proxying on esbuild-based builders is simply not working.
To see that WS connection can be established, change builder to `@angular-devkit/build-angular:browser`

### Minimal Reproduction

https://github.com/zip-fa/ng17-ws-proxy-bug

### Your Environment

```text
Angular CLI: 17.0.0-rc.1
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.1
@angular-devkit/build-angular   17.0.0-rc.1
@angular-devkit/core            17.0.0-rc.1
@angular-devkit/schematics      17.0.0-rc.1
@schematics/angular             17.0.0-rc.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.1
```

**Comment by alan-agius4** [comment]
I have looked into this and it looks like in this case webpack-dev-server was doing the wrong thing as the request should not have been proxied in the first place.

Your proxy config url is configuration to `/v3/channel_123/*`, however from the application the request is made to `ws://localhost:4200/v3/channel_123`. The glob doesn't match the request URL as it doesn't have a slash nor any other character after it.

If the slash and characters after are optional you can update the glob to the following `/v3/channel_123?(/*)` otherwise if the request will never have a slash, you can simplify it by removing the glob entirely, `/v3/channel_123`
