### ISSUE TITLE
Custom configurations for Vite/Esbuild

### ISSUE THREAD

**Issue by drtobal** [angular/angular-cli#26329]
### Description

In webpack projects we can use custom configurations adding the builder of https://www.npmjs.com/package/@angular-builders/custom-webpack such as:

- Remove unused CSS with PurgeCSS (very useful when using external css libraries like bootstrap)
- Move the JS files to a external CDN and modify the urls of index.html and runtime.js to this external CDN
- More modifications to styles, javascript files and index.html files

### Proposed solution

Add the hability to customize builds of EsBuild and Vite and external plugins

### Alternatives considered

Add more properties to angular.json to add keys of customization of esbuild and vite

**Comment by dlq84** [comment]
I'd like this too, I'm using `@svgr/webpack` today and would need to use `esbuild-plugin-svgr` with esbuild.

**Comment by clydin** [comment]
The package referenced above (`@angular-builders/custom-webpack`) is a third-party package.  The Angular team does not maintain or otherwise support the package.  If you are interested in that project creating a similar package for the new application builder, please consider opening a feature request with that project.  Programmatic APIs within the Angular CLI are available to allow for the creation of such a package with similar functionality.
