### ISSUE TITLE
application builder: error at runtime with angular-highcharts

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#26342]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

WHen using the application builder, an application using `angular-highcharts` works well with `ng serve` but has a runtime error when built with `ng build`.

### Minimal Reproduction

The following repo https://github.com/cexbrayat/ng-highcharts is a minimal reproduction built with:

```
npx @angular/cli new ng-highcharts --defaults --no-standalone --no-routing --skip-tests
npm i --save --save-exact highcharts@11.2.0 angular-highcharts@16.0.0
# add hello world described in angular-highcharts readme
# https://github.com/cebor/angular-highcharts/tree/master#using-highcharts-modules
```

`ng serve` and `ng serve --configuration=production` work fine and display the chart.
`ng build && http-server dist/ng-highcharts/browser` throws at runtime (no build error) because the loading of the Highcharts module no longer works.
`ng build --configuration=development && http-server dist/ng-highcharts/browser` doesn't work as well (stack trace below)

Using the `browser` builder fixes the issue.

### Exception or Error

```text
TypeError: object is not a function
    at Array.forEach (<anonymous>)
    at angular-highcharts.mjs:286:57
    at Array.forEach (<anonymous>)
    at _ChartService.initModules (angular-highcharts.mjs:285:25)
    at new _ChartModule (angular-highcharts.mjs:319:15)
    at Object.ChartModule_Factory [as useFactory] (angular-highcharts.mjs:323:16)
    at Object.factory (core.mjs:6119:32)
    at core.mjs:6026:33
    at runInInjectorProfilerContext (core.mjs:871:5)
    at R3Injector.hydrate (core.mjs:6025:9)
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: npm 9.7.1
OS: darwin arm64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

The `browser` builder does not have this issue

**Comment by JoostK** [comment]
After some digging I found that esbuilds `__toESM` helper copies the loaded CJS module into a newly created ESM object, with the same prototype as the original CJS module. The resulting value is _not_ callable though, which is why this throws.

Although the specifics are not entirely clear to me (CJS/ESM interop seems to require a PhD), a namespace import in ESM is required to represent an object, _not_ a function AFAICS. The [`esModuleInterop` flag that was introduced in TypeScript 2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) would typically report an error when such namespace object is called, but in this case that call is indirected through the `HIGHCHARTS_MODULES` provider and hence it goes unnoticed. Interestingly, toggling this flag does not appear to make a difference.

This appears to work using the development server where esbuild does not perform bundling, in which case the `highlights-more` bundle is amended with `export default require_highcharts_more_src();` and crucially the namespace import has been rewritten to a default import. I suspect the latter behavior is Vite's, although that is really just a guess.

The problem is entirely avoided by using a default import, which seems like to correct thing to do here anyway. Why this does work in Vite is surprising to me, but I haven't looked further into it than mentioned above (which was just an observation of the emitted code, not a deep-dive into the build pipeline itself)

**Comment by clydin** [comment]
As mentioned above, namespace exports are not callable as per the ECMAScript specification. This usage would typically be an error but the use of the dependency injection hides the usage.  Combine this with the loose typing of providers, both in the package's injection token (`any[]`) and the providers array itself (`useFactory` is `Function`), and it allows the build to pass without notice.  However, if you attempt to call either the `more` or `exporting` namespace imports directly in `src/app.module.ts`, it will cause an error (`This expression is not callable.`).

Also as mentioned by @JoostK, default imports as follows will allow both the build to succeed and the application to work at runtime. Default imports are callable and are the spec-compliant usage in this case. For more information, the conversion guide provides more details here: https://angular.dev/tools/cli/esbuild#esm-default-imports-vs-namespace-imports
```
import more from 'highcharts/highcharts-more.src';
import exporting from 'highcharts/modules/exporting.src';
```

**Comment by cexbrayat** [comment]
It does fix the issue, thanks for the investigation and detailed answer @JoostK @clydin

**Comment by cexbrayat** [comment]
@JoostK @clydin We stumbled on another case which, based on my understanding of your explanations, I would have expected to work.

We use [dompurify](https://github.com/cure53/DOMPurify) in one application. The lib is meant to be used as:
```
import * as DOMPurify from 'dompurify';
clean = DOMPurify.sanitize('<b>hello there</b>');
```

As this is not a namespace call as in the previous example with Highcharts, I thought this would work with the application builder, but it throws at runtime:
```
TypeError: DOMPurify.sanitize is not a function
```

It works with the browser builder and the same workaround can be applied for the application builder: `import DOMPurify from 'dompurify';` works.

I just want to make sure this is expected and not an issue that went unnoticed.
If this is expected, is there any way we can catch this when switching to the application builder other than by trial and error?

**Comment by cexbrayat** [comment]
I forgot to mention I updated the repro with a new commit showcasing the issue https://github.com/cexbrayat/ng-highcharts/commit/e6a25398f26283e3f6ccd2c915d892335b24a3fa

**Comment by JoostK** [comment]
The `dompurify.es.js` file contains:

```js
export { purify as default };
```

Since it is ESM itself, importing the namespace results in a namespace object with a `default` property, _not_ the `DOMPurify` instance.

This is fine for TypeScript since the `@types/dompurify` declarations contain:

```ts
export as namespace DOMPurify;
export = DOMPurify;
```

but that isn't accurate for the ESM bundle that actually ships with `dompurify`.

**Comment by cexbrayat** [comment]
Ok thanks @JoostK for the explanation.

Do you know how we could detect such things? Even if it is not automated via the CLI, do you know a tool that would help catch this?

**Comment by JoostK** [comment]
Not that I know of. It's typically detected by TypeScript but that only works if the declarations accurately reflect the situation.
