### ISSUE TITLE
application builder: JSON import regression with dashed root keys

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#26461]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

When importing a json file using `import('file.json')` in an CLi application, the JSON returned does not include the root keys that have a dash in their name.

Consider the following JSON:
```json
{
  "withoutdash": "Without dash, OK",
  "with-dash": "With dash, OK",
  "nested": {
    "withoutdash": "Nested without dash, OK",
    "with-dash": "Nested with dash, OK"
  }
}
```

loaded in a component dynamically:
```ts
  jsonContent: any;

  async show() {
    const fileName = 'test';
    this.jsonContent = await import(`./${fileName}.json`);
  }
```

and then displayed:
```html
<button (click)="show()">Load and show JSON content</button>

@if (jsonContent) {
<h1>Whole object</h1>
<pre>{{ jsonContent | json }}</pre>

<h1>Default property</h1>
<pre>{{ jsonContent.default | json }}</pre>
}
```

The whole object displays (no `with-dash` root key):
```json
{
  "default": {
    "withoutdash": "Without dash, OK",
    "with-dash": "With dash, OK",
    "nested": {
      "withoutdash": "Nested without dash, OK",
      "with-dash": "Nested with dash, OK"
    }
  },
  "nested": {
    "withoutdash": "Nested without dash, OK",
    "with-dash": "Nested with dash, OK"
  },
  "withoutdash": "Without dash, OK"
}
```

whereas the default content is correct:
```json
{
  "withoutdash": "Without dash, OK",
  "with-dash": "With dash, OK",
  "nested": {
    "withoutdash": "Nested without dash, OK",
    "with-dash": "Nested with dash, OK"
  }
}
```

### Minimal Reproduction

See https://stackblitz.com/edit/stackblitz-starters-dg68rk?file=json-loading-bug%2Fsrc%2Fapp%2Fapp.component.html

Run:
```
cd json-loading-bug/
npm i
npm run start
```

### Your Environment

```text
Angular CLI: 17.0.3
Node: 18.18.0
Package Manager: npm 9.4.2
OS: linux x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

A workaround is to use the default property:

```ts
this.jsonContent = await import(`./${fileName}.json`).then(m => m.default);
```

**Comment by cexbrayat** [comment]
I forgot to mention that this quite breaking for applications using libraries like `ngx-translate`

**Comment by alan-agius4** [comment]
This is unfortunately expected, as not all default browsers support an arbitrary module namespace which is required to support direct dashed exports in ESM.

IE: 
```
export {
  with_dash as "with-dash",
};

```

**Comment by clydin** [comment]
Also of note here is that the `default` export is the only export that can be guaranteed to be present. The JSON module specification directly calls out this behavior.  So from an ESM and spec perspective, the default is probably the better long-term option especially for the dynamic import usage.
The new build system does support named imports (assuming you don't use the json type attribute with the import) which does have some nice tree-shaking capabilities.  But as mentioned, this would only be viable to use for non-identifier JSON top-level properties due to target browsers support of arbitrary module namespace identifiers.

Webpack will actually generate an error if you attempt to use a static import statement for JSON with a named import:
`import { x } from './a.json';`
Results in:
`./src/app/app.component.ts:343:12-13 - Error: Should not import the named export 'x' (imported as 'x') from default-exporting module (only default export is available soon)`
