### ISSUE TITLE
browser-esbuild/application builds should not show summary stats when the build fails from budget errors

### ISSUE THREAD

**Issue by NateRadebaugh** [angular/angular-cli#26514]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

When running "build" command with budget errors, eg `anyComponentStyle`, we expect to be informed in a clear way.

We do see the output of "Application bundle generation failed" in a normal console log color, but the stats table still shows.

### Minimal Reproduction

1. Have any budget that is not met, for instance setting to 1kb with a large style.
2. Run "ng build"
3. Are quietly notified about the build failure, but have to scroll up past all the site chunks in order to see what went wrong.

### Your Environment

```text
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.3
Node: 20.10.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cdk                    17.0.1
@angular/cli                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by dgp1130** [comment]
Had some discussion about this in the team today. Our general feeling is that the budget table is actually quite useful to have when a budget is exceeded. This provides a nicely formatted UI to help users understand how a budget was exceeded.

```
$ ng build

⠙ Building...

▲ [WARNING] bundle initial exceeded maximum budget. Budget 1.00 kB was not met by 202.32 kB with a total of 203.32 kB.


✘ [ERROR] bundle initial exceeded maximum budget. Budget 1.00 kB was not met by 202.32 kB with a total of 203.32 kB.

Initial Chunk Files   | Names         |  Raw Size | Estimated Transfer Size
main-45SV4OB3.js      | main          | 170.63 kB |                46.82 kB
polyfills-LZBJRJJE.js | polyfills     |  32.69 kB |                10.59 kB
styles-5INURTSO.css   | styles        |   0 bytes |                 0 bytes

                      | Initial Total | 203.32 kB |                57.41 kB

Application bundle generation failed. [4.568 seconds]
```

In this case we can see that "Initial Total" includes both `main` and `polyfills`, which might not be obvious to users. We could probably do a better job with the general error message, but including the table seems useful in general.

One observation is that it might be better for errors to come *after* the table. Because of the nature of terminal UI autoscroll, most users will read the bottom of the content before the top. The table can also be quite large, so putting errors at the bottom can help avoid users needing to scroll up past the large table before seeing their errors.

@clydin, I think you wanted to look at moving the error messages?

**Comment by NateRadebaugh** [comment]
My concern here is that your example with just a few chunks is not realistic. On a normal application with rich code splitting, we end up with so many chunks that the fact that there are any yellow/red warnings/errors is hidden by a big chunk of green that tells me everything is good, making it difficult to discern when something goes wrong.

My read of it is that the error itself should include enough context for debugging what specific items are errored.

I agree that moving the error messages to show at the end may solve my problem. Alternatively, including the error color/message directly in the chunk table would be the best DX.
