### ISSUE TITLE
Recommended VS Code configuration

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#2672]
### OS?

> Windows 10, Ubuntu, Mac

I think lots of developers out there use VS Code for ng2 projects. It would be very cool to have some kind of recommended configuration on the following VS Code settings for an optimal user experience. 
- Recommended extensions for ng2 developers (i.e. tslint extention to enable style ng2 guide linting)
- Build Task Configuration to use integrated build runner (ctrl+shift+b)
- How to configure the debugger to be usable

Could be written for other ide's like webstorm to.

**Comment by dancancro** [comment]
I'm not sure if this helps but here's my basic vscode configuration file in an Angular-CLI project. It lets you debug server-side node code
https://github.com/dancancro/great-big-angular2-example/blob/master/.vscode/launch.json

**Comment by lacolaco** [comment]
I'll try to create a first draft for that, but I'm not familiar with integration to VS Code. I'll need help from folks! 🙏

**Comment by lacolaco** [comment]
@mbeckenbach @benjamincharity @dancancro Could you help me to fill TODO parts? I want your reviews and comments!
https://github.com/angular/angular-cli/pull/7846

**Comment by filipesilva** [comment]
VS Code recipes actually has an official doc for Angular CLI already: https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI

**Comment by filipesilva** [comment]
I don't have a specific opinion about this but @hansl probably has, because he has been working on moving the CLI docs over to angular.io.

**Comment by dgp1130** [comment]
Discussed this amongst the CLI team today, and we definitely agree that we can do better in this space. Rather than just writing docs about it however, it would be better to have `ng new` just generate the relevant VSCode configuration out-of-the-box. That way users don't need to read docs, understand how it all works, and set things up themselves. The debugger configuration breaks the abstraction of the build somewhat as it has to map back to source code directories. If we are able to support this in `ng update`, we might be able to migrate user code to avoid breakages from internal changes and keep projects more consistent.

Regarding extension recommendations, it begs the difficult question of "What extensions get recommended?" which is very difficult to address. We want to avoid even the appearance of favoritism, whether for extensions written by core team members, written by frequent contributors, lobbied heavily, or based on any other aspects than the extension's individual merit. Unfortunately, it is very difficult to avoid such an appearance, even if all the decision-makers have the best intentions. After some discussion, the team has decided that the safest option is to simply not recommend _any_ community extensions, because introducing "officially" recommend extensions only causes confusion and the possibility of misinterpretation. As an alternative, there are many community-curated lists of useful tools and extensions which developers can use.

There are still a lot of questions here we need to figure out before we can make the change:
1. What is the ideal VSCode configuration that users typically expect?
1. Can we migrate existing projects to include the same configuration, and if so, how?
1. Should the changes be flag protected (`--editorConfigs vscode`) and what should be the default?
    * My personal opinion is to just generate the config by default, users can always delete it later with minimal effort if they don't want it.

**Comment by samuelfernandez** [comment]
Proposal:

* Add a default configuration just when creating new projects. Migrating existing projects to a custom setup can be breaking
* I'd expect to have at least:
  * Launch task with debugging enabled
  * Attach task to existing instance
  * Debug unit test
  * Minimal suggested extensions according to the tools being used: eslint, editorconfig

Additionally, I'd consider super useful:
* Suggested extensions: Prettier, Angular 11 snippets, Angular Schematics

I'd volunteer to submit a PR with a basic agreed configuration. It can be a foundation to be extended later according to community feedback.
