### ISSUE TITLE
You did not install all folders

### ISSUE THREAD

**Issue by juanfeorar** [angular/angular-cli#2682]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux (Ubuntu 15.10 --- 4.2.0-42-generic). 

### Versions.
> Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.17
node: 6.3.1
os: linux x64

### Repro steps.
> npm install -g angular-cli
> ng new mi-nuevo-proyecto-angular2

### The log given by the failure.
> Attached file log of install of AngularCLI(I tried with sudo without sudo)
[npm-debug.pdf](https://github.com/angular/angular-cli/files/527185/npm-debug.pdf)

### Mention any other details that might be useful.
> when I give in ng new, do not believe me complete files and folders(only 3 folder of 6)
![angular](https://cloud.githubusercontent.com/assets/1591202/19351993/a696185e-9123-11e6-8eca-8f85ee63a2ad.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by uitgewis** [comment]
This may seem like a silly question, but does it work when you run `ng serve`? 
It looks like you already have everything you need (there are only those two folders, plus `node_modules` 😃 ).

**Comment by juanfeorar** [comment]
Thanks for you response, 
I am studying a book of angular2, and according to the book this is the folder structure (see picture): 
![angular1](https://cloud.githubusercontent.com/assets/1591202/19357433/49aa720c-9137-11e6-8326-f5f7798694ef.png)

when run `ng serve` gives this result(bundle is now VALID)
![angular2](https://cloud.githubusercontent.com/assets/1591202/19357745/8989cd2c-9138-11e6-86d5-62010a4cd276.png)

**Comment by cheposki** [comment]
+1

**Comment by clydin** [comment]
Your book is outdated.  That is the old folder structure.

**Comment by Meligy** [comment]
Yes, the book is outdated.

There have been some special config files merely for the use of SystemJS. Since the CLI now uses Webpack, those were gone, and so went the `config` folder. The few remaining configuration files live in the root (`angular-cli.json`, `karma.conf.js`, `protractor.conf.js`).

The `public` folder is now an `assets` property in `angular-cli.json`. It's an array of strings. Each string can match files that will copied to the output folder (`dist` by default) as-is (for example `*.config` files get copied to `dist/{filename}.config`). If the string matches a folder name (`assets` for example), the folder itself will be copied with the same name (for example to `dist/assets`).

The `typings` folder was for a tool that has the same name that loads TypeScript definition files for JavaScript libraries (the files that provide autocomplete for non-TypeScript libraries). Now in TypeScript 2, there's a new way to load those definitions, which is loading them as NPM packages under the name `@types` (similar to how Angular 2 packages are under `@angular`), which TypeScript understands and loads by itself without other tools.

The green output ending with no errors means it's working fine (warnings are OK, you might see them in production build output, another long story). For example, if you get that after `ng serve`, your site should be ready for you at `http://localhost:4200`.

**Comment by juanfeorar** [comment]
OK, thanks.
