### ISSUE TITLE
[Severe] V17: ng-build removes part of library author code

### ISSUE THREAD

**Issue by GreenFlag31** [angular/angular-cli#26825]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi,

I'm currently making an carousel library. When running the command 'ng build' parts of my code get removed.

In my development library environnement (BUG): 

To reproduce the error:
1. Git clone https://github.com/GreenFlag31/carousel-library and npm i
2.  (optional) Run 'ng serve -o'. Everything works as expected in development (nothing has been removed).
3. Run 'ng build'
![find folder dist](https://github.com/angular/angular/assets/84795623/69f145b0-9849-45f8-8cad-4bc782789e39)
Find the corresponding file in the compiled code in the dist folder and search for the method 'resetViewLeftDirection'. 'this.slidesContainer.offsetHeight;', which is necessary for forcing element reflow, has been removed.

In a existing project (BUG):
1. Git clone https://github.com/GreenFlag31/Portfolio and npm i. The library is contained in the tarball file .tgz (winrar) at root .
2. Have a look at the ngx-carousel-ease in the node_modules/fesm2022/ngx-carousel-ease.mjs.map. 'this.slidesContainer.offsetHeight;' is present.
![inside node_modules](https://github.com/angular/angular/assets/84795623/2606ab3b-67b9-426b-abcc-3138681e8e0f)
3. Now run 'ng build' and find the corresponding file in the dist folder: 
![last line gone](https://github.com/angular/angular/assets/84795623/faeee759-e62a-4f73-9f4e-c8e5ff11f1a4)
'this.slidesContainer.offsetHeight;' has been removed in the compiled code.

In a new project (WORKING):
1. Git clone https://github.com/GreenFlag31/lib-carousel and npm i. The library is contained in the tarball file .tgz at root .
2. Run ng build
3. Have a look at the corresponding compiled file in the dist folder. The 'this.slidesContainer.offsetHeight;' is present.

I have no idea why this is working in a new project, and not in my developement environnement nor in an existing project. I don't know if it's a regression bug. I expect it to be a configuration problem. I've tried to get the same tsconfig from the working project in not working ones, but was unable to find the problem. 

When shipped to npm, the code includes the missing lines. When running 'ng build'  this line got removed. Is this some aggressive optimisation from ng build ? If this line got removed, it is totally possible that other part of the application get removed by ng build as well.

**Comment by JoostK** [comment]
Webpack builds use `terser` with `pure_getters` enabled, so the statement which just reads a property is optimised away under the assumption that is value isn't used.

There is more discussion in #11439.

With the new application builder (using esbuild instead of terser) doesn't have this behavior I suspect.

**Comment by JoostK** [comment]
Also see #17494, which refers to terser/terser#464 which is still open.

This is unlikely actionable given the above tickets. The new builders using esbuild don't show this behavior.

**Comment by dgp1130** [comment]
> With the new application builder (using esbuild instead of terser) doesn't have this behavior I suspect.

I'm pretty sure we still run Terser on the output so I think this would still reproduce there. Regardless I think the ideal solution here is to avoid a side-effectful getter. 

It's unfortunate that it's occasionally necessary to trigger reflows. https://github.com/angular/angular-cli/issues/17494#issuecomment-635592036 seems to indicate that `getClientBoundingRect()` might have the same effect of reflowing without requiring a side-effectful getter.

**Comment by GreenFlag31** [comment]
Thanks you for your replies. I will try another approach (getClientBoundingRect), I hope another one do the job. 

The problem now is that it causes mistrust in one of the most basic command of Angular. ng build should in no cases delete author code.

**Comment by dgp1130** [comment]
This is just the nature of tree shaking in a language as dynamic as JavaScript. There are ways to observe most dead code elimination with the right JS pattern (side-effectful getters, import elision, top-level side effects, dynamic property access, `eval`, etc.). In particular, if all property accesses are assumed to be side-effectful, you really can't tree shake almost anything. Pretty much all modern frameworks / bundling tooling do this kind of thing. If we kept things perfectly safe it would be a massive bundle size regression for applications, and this is what we think makes the best trade offs with that in mind.

**Comment by GreenFlag31** [comment]
I got your point and understand that a tradeoff has to be made. However, I believe that it would be almost impossible or very hard for a novice Angular developer to find and understand the issue. Moreover, this issue only happens in production environnment and at runtime, which is really really bad. At least, in development mode, a warning should be raised about side-effectful getters.

getClientBoundingRect does the job and is not getting removed by webpack.

**Comment by dgp1130** [comment]
A warning would be nice, but I don't think it's possible to generally identify side-effectful getters and their usage, particularly for code invoking a property from a library. I doubt we could identify `offsetHeight` as a side effectful getter without a long and brittle blocklist of CSS properties. Even then, it would warn for all `offsetHeight` properties, whether or not the developer is actually using an `HTMLElement` property (types are invisible to Terser). If you wrote `(someUnrelatedObject as SomeClass).offsetHeight` that would get the same warning and be completely unactionable. Maybe some other tooling can provide this which developers could optionally include, but I suspect it would be surprisingly complex and quite noisy for typical usage.

The one potential improvement I can think of is to exempt empty getter statements:

```typescript
// `doSomething` could be pure and removed. Also should drop `obj.offsetHeight` for the previously specified reasons.
doSomething(obj.offsetHeight);

// Clearly a no-op, this only makes sense as a useful statement if `offsetHeight` is side-effectful.
obj.offsetHeight;

// Also definitely a no-op, but less clear on the developer's intention here?
'test' + obj.offsetHeight;
```

I suspect this might be infeasible because optimization typically involves many intermediate steps. I'm not super familiar with how Terser works but I think it is entirely reasonable that it might use a plain expression as a part of the optimization pass:

```typescript
// If `doSomething` is pure, we can remove it. But parameters might have side-effects.
doSomething(obj.offsetHeight, 'test', somethingElse());

// Optimize to:

obj.offsetHeight;
'test';
somethingElse();

// Then do another pass, anything else we can drop?

// obj.offsetHeight; // Removed due to `pure_getters`
// 'test'; // Removed as useless.
somethingElse(); // Retained, could be side-effectful.

// Outputs

somethingElse();
```

If so, implementing a `pure_getters` exception for standalone property access expressions might be infeasible architecturally. That's probably a question for Terser, I don't think they implement anything like this today. You can file a feature request to Terser and we could consider adding it to Angular (still not convinced this is a usable solution or that Angular would definitely want to incorporate such an option, it's just one potential proposal).

It's definitely an unfortunate rough edge, but this is the nature of the JavaScript language we work within.
