### ISSUE TITLE
executing an arbitrary code synchronously before kicking off angular 2

### ISSUE THREAD

**Issue by nmorado** [angular/angular-cli#2683]
we need to do something else before starting angular.

using sysmjs - we accomplish this by calling System.import right after our function ran.

i am trying to look for a way in the current CLI/setup - how we can do the same.

thoughts?

**Comment by Meligy** [comment]
You can call your code in `src/main.ts` before the `platformBrowserDynamic().bootstrapModule(AppModule);`  call.

The file itself has an example of this, which is loading polyfills (which, just like the thing you want to run, need to be loaded before Angular).

(It also sets Angular's production mode when the environment is set to production  before bootstrapping the application, which needs to be set before bootstrap so that the bootstrapping process uses it).

This is what the file looks like: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/__path__/main.ts

(This is the template, the actual file lives in `src/main.ts` in your project).

**Comment by nmorado** [comment]
this was what i did initially, but it did not seem to work.

i was asynchronously loading my templates and setting it to some global variables to be used by a component's template.

after making the async call i did call the platformBrowserDynamic().bootstrapModule(AppModule);

but the component's is not picking up the templates as i am expecting.

**Comment by nmorado** [comment]
looking at the main-bundle.js, it looks like the Component is decorated too soon and i suspect it happened before the async calls to fetch the templates complete

**Comment by Meligy** [comment]
Yes, decoration is *like* a build step in Angular. You wouldn't be able to hook into that unless you are loading every single file separately in the browser via systemJS, which isn't too efficient for production of course.

**Comment by filipesilva** [comment]
The CLI doesn't have any special facility to allow for code to run before the rest. You can simply run whatever you need, return a promise, and bootstrap the app in the `.then` block.
