### ISSUE TITLE
Angular 2 CLI build ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by MatthiasSkopek** [angular/angular-cli#2701]
I'm learning angular 2 now and i fail to build the Project. I create a new project ( no changes ) and then ng build and open the index.html file in the dist folder and get the ERR_FILE_NOT_FOUND but the path is right. 
I'm working on OSX El Capitan and Node v6.8.0. 

Hope you can help me.

**Comment by gelliott181** [comment]
Does `ng serve` properly serve the app to `localhost:4200`?

**Comment by MatthiasSkopek** [comment]
It should run on an server. So it's the file build dist folder with the inline.js. So i  don't need ng serve.

**Comment by splintercode** [comment]
When you open the index file after running `ng build` are you using a web server of some kind? You would need a local host running to properly view your project.

**Comment by gelliott181** [comment]
@MatthiasSkopek Yes, it should run on a server, which is why I ask if it runs with `ng serve`. If you're running `ng build` then opening index.html with a file browser, or as a file, then you're not running into a bug, you're just not serving the app at all. Angular 2 must be accessed through an HTTP server, such as the nodeJS http-server, express, HapiJS, etc.

**Comment by tonydearaujo** [comment]
I'm not sure if this helps. I just want to make a note about this issue: The path for the JS and CSS files on the index.html in the dist folder are set to root of the system. This is the root of your computer, not the root of your app. In order to view it from your app you need to change the PATH in relation to your system root. This also applies if you upload it to a real server.

**Comment by filipesilva** [comment]
@gelliott181 has it right. You really must serve your app instead of just double clicking it. If you don't want to use `ng serve`, the simplest server that fully supports all features that Angular 2 needs from a server is https://github.com/johnpapa/lite-server.

**Comment by delsner** [comment]
@MatthiasSkopek alternatively, if you want to use it directly from the file system (double-clicking index.html), you could just remove `<base href="/">` from your index.html and you should be able to run the app without running a web server.

**Comment by MatthiasSkopek** [comment]
Thank you all. When i throw it in MAMP it's works perfectly. The HTTP Server was the problem
