### ISSUE TITLE
ng serve doesn't work in Bun

### ISSUE THREAD

**Issue by mgechev** [angular/angular-cli#27111]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

It'll be wonderful to get `ng build` and `ng serve` work with Bun.

As of right now, `ng serve` throws an error:

![image](https://github.com/angular/angular-cli/assets/455023/0ab5e9f0-f0cd-4176-a5d5-acf46c985333)

([source](https://twitter.com/thfsilvab/status/1758259445182964215/photo/1))

### Minimal Reproduction

`bun run --bun start`

### Your Environment

```text
Angular CLI v17.2 on macOS
```

**Comment by thfsilvab** [comment]
Just adding some more details as this was ported from a discussion on X.

- I needed Node installed to run `ng new` as it doesn't recognize that the package `@angular/cli` was installed through Bun
- I uninstalled Node after that and tried to develop the application only with Bun
- Running `ng serve` or `bun run dev` also doesn't work because it tries to use Node instead of Bun (setting an alias might solve this and the first problem as well)
- Only by adding `--bun` to the run command I was able to force it to run with bun, which resulted in the error reported above

It'd be really nice to have Angular running with Bun, I expect some improvements in compilation time as Bun by now is the fastest runtime available, and that's very exciting!

**Comment by alan-agius4** [comment]
This is working as expected.

The Node.js runtime is still necessary, and `bun` support was added solely as a package manager.
