### ISSUE TITLE
Router outlet broken

### ISSUE THREAD

**Issue by mrynthom** [angular/angular-cli#272]
By running the default install
ng new project
cd project
ng serve

The webpage is populated with project Works! but doesn't fill in the router outlet. This is the same as 
https://github.com/angular/angular-cli/issues/166 but the ordering doesn't seem to solve it, and is following the latest from the quick start. 

System
Darwin 14.5
Node v5.7.0
Npm v 3.6.0

**Comment by filipesilva** [comment]
You're absolutely right - but it is actually intended in the base app. 

This is because the generated app is *ready* to render routeable components in the outlet, but starts with none whatsoever. 

If you follow the instructions [here](https://github.com/angular/angular-cli#generating-a-route) (generating a route and adding it to `@RouteConfig`), you should see the outlet being populated when at that route.

If this does not happen though, then there is definitely something wrong.

**Comment by wollio** [comment]
Hello @filipesilva 

I ran exactly in the same error, when I installed angular-cli via npm and tried do generate some routes.
I fixed it by adding:

```
import {Router} from '@angular/router';

...

constructor(private router: Router) {
}
```

to my main-component in the app folder.
