### ISSUE TITLE
[SSR, Application Builder] Option to Generate Common JS Modules for Server

### ISSUE THREAD

**Issue by TheNightmareX** [angular/angular-cli#27279]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler, platform-server

### Description

I'm faced with a need to bundle the SSR application into an executable. However, all the Node.js executable bundling solutions support only CommonJS modules, while our new SSR feature seems to generate only ECMA modules.

I have tried to change the `module` option in `tsconfig.json` to `CommonJS`, but it turned out that this option is not respected by the builder.

### Proposed solution

Respect the `module` option in `tsconfig.json` to allow CJS module building.

### Alternatives considered

Alternatively, add a new option for the Application Builder to generate CJS instead.

**Comment by JoostK** [comment]
Angular has fully transitioned to ESM and has since stopped supporting CJS output. If you need CJS, your best course of action is to transform the output JS modules to CJS using a separate build step.

Note that CJS restricts various ESM features from being usable, which would impact the available feature set of Angular libraries. So having this as a supported option in the CLI itself would impose limitations on the ecosystem.
