### ISSUE TITLE
const enum is broken

### ISSUE THREAD

**Issue by KhodeN** [angular/angular-cli#2741]
### OS?

> Mac OSX Sierra
### Versions.

> 1.0.0-beta.17
### Repro steps.

> `ng new --prefix=t check-enum`
> `cd check-enum/`
> `ng serve`

then add to `main.ts` (no matter, may be any *.ts)

```
declare namespace Sts {
  export const enum A{
    a, b, c
  }
}
console.log(Sts.A.a, Sts.A.b);
```
### The log given by the failure.

> `main.bundle.js:65131 Uncaught ReferenceError: Sts is not defined`
### Actual in `main.bundle.js`

`console.log(Sts.A.a, Sts.A.b);` (see at Source panel of Chrome Developer Tools)
### Expected in `main.bundle.js`

`console.log(0 /* a */, 1 /* b */);`

If I run `tsc` from `src` directory, this code will be in `dist/out-tsc`, as expected. TypeScript is OK!
### Mention any other details that might be useful.

> I donn't know, where is  a mistake, in angular-cli or its configuration or deps. Generated code is same, as without `const` keyword. This is very strange.

**Comment by zhengbli** [comment]
This is blocking me as well. version 1.0.0-beta.25.5

**Comment by imiuka** [comment]
this is a huge problem for me as well. i'd love to see a fix.

**Comment by Gustorn** [comment]
We also ran into this while upgrading to a Webpack-based/AOT-enabled build system. We have some tooling set up that automatically generates `d.ts` files for all of our web-facing model classes. This maps native enums - very correctly - to const enums.

The automatically generated `.d.ts` file:
```ts
declare module server {
    const enum Status {
        OK
    }
}
```

The problem arose when we tried to use these enum values directly:

```ts
export function processStatus(status: server.Status) {
    switch (status) {
        server.Status.OK:
            // Custom code here
            break;
    }
}
```

Luckily code like this was few and far-between so I solved the issue by replacing the generated enums with their constant values. This solution is of course very far from ideal: we lose type safety and the code becomes harder to read. Non-ambient `const enums` are properly transpiled. 

Since this issue is 6 months old and is a pretty severe codegen bug some official word would be really appreciated.

**Comment by KhodeN** [comment]
It still be very annoying bug. 
Did anybody try to fix or "investigate" this?

**Comment by KhodeN** [comment]
I found explanation: [Const enums are preserved when using transpileModule](https://github.com/Microsoft/TypeScript/issues/5243)

In short: `transpileModule` compiles in `single-file` mode, so it don't know about enums in other files.

I think there is a way to concatenate sources before compile to workaround this. 
Your thoughts?

**Comment by imiuka** [comment]
@KhodeN on your second question, these are your current options (until this issue is fixed):

- don't use const enums.
- use const enums, but add `preserveConstEnums = true` into `tsconfig.json`

either of these two options will mean typescript generates the standard enum bits, and that enum accesses go through runtime property lookups.

```
(function (Enum) {
    Enum[Enum["A"] = 0] = "A";
    Enum[Enum["B"] = 1] = "B";
})(Enum || (Enum = {}));
```

when that's unacceptable, there's a third workaround that i'm using for now. i've forked `@angular/cli` and added an extra webpack plugin that runs after typescript compilation. it walks through all const enum imports and rewrites them into their literal values.

that's a little more painful to write, though.

**Comment by KhodeN** [comment]
Now I don't use const enums( 

`preserveConstEnums = true` not works in ambient declaration files (`*.d.ts`)

Third way is too complex and take much time. It is very expensive in support.

**Comment by taras-demyanets** [comment]
Dear CLI team! Please give some feedback on the issue. 
I have similar setting as Gustorn (post from 10 Apr.) and feel very uncomfortable modifing generated code just to satisfy the CLI tooling pipeline.
"awesome-typescript-loader" still does not have any solution for the problem, so may be you can replace the loader?
Thanks!

**Comment by sumitarora** [comment]
@taras-demyanets @KhodeN You can compare enums using `valueOf` function of enums.
```
namespace Validation {
  export const enum A {
    a, b, c
  }
}

const x: Validation.A = Validation.A.c;
console.log(x.valueOf() === Validation.A.b); // return false

switch (x.valueOf()) {
  case Validation.A.a:
    console.log('a');
  break;
  case Validation.A.b:
    console.log('b');
  break;
  case Validation.A.c:
    console.log('c');
  break;
  default:
    console.log('none');
  break;
}
```

**Comment by Gustorn** [comment]
@sumitarora The problem isn't that we can't compare const enums, it's that the values we're comparing against don't get transpiled (and result in runtime errors). If we take your example (a little shortened):

```ts
// Ambient declaration in another .d.ts file
namespace Validation {
  export const enum A {
    a, b, c
  }
}

// Actual code
const x: Validation.A = Validation.A.c;
switch (x.valueOf()) {
  case Validation.A.a:
    console.log('a');
    break;
}
```

Should transpile to:
```ts
var x = 2;
switch (x.valueOf()) {
    case 0:
        console.log('a');
        break;
}
```

But instead transpiles to: 
```ts
var x = Validation.A.c;
switch (x.valueOf()) {
    case Validation.A.a:
        console.log('a');
        break;
}
```

And naturally it cannot find `Validation.A.c` and `Validation.A.a` at runtime.

**Comment by squadwuschel** [comment]
I've many enums in my project and that I can't use them is a really show stopper for me to use the cli. Currently I am using pure webpack and there everything is workingfine with the Enums

**Comment by wsquire** [comment]
This is still a blocking issue for me. 
Repro steps:
- create a new project (ng new)
- add a new ts file (enums.ts for example)
- make the contents of this file 
`module enums {
	export const enum myEnum {
		value0 = 0
	}
}`
- add this file to the tsconfig.app (using "files" or "include" for example)
- reference your enum in app.component.ts
`let x = enums.myEnum.value0;`
- ng serve (or test or e2e)

Expected:
The app builds and runs without error
Actual:
The app builds without error. However, the module containing your enum will not be defined at runtime. Error message: `Uncaught ReferenceError: enums is not defined`.

The module not being defined at runtime is actually expected. The compiler _should have_ replaced the enum reference with the value because this enum is defined as a constant. This is unexpected and undesirable behavior.

This issue prevents me from using angular-cli in projects where I have split out enumerations into their own files for reuse. What is worse is that I can not use tools like typelite to automatically translate my enumerations from .Net to typescript.

>

**Comment by Gustorn** [comment]
The worst thing is that this is a solved problem in `ts-loader`. I understand the desire for higher performance (`transpileModule` _is_ faster) but at least add an option for us to use the slower but correct version.

As a temporary workaround you can actually import const enums explicitly and it will work as expected. The problem is that most tools generate definition and not regular TS files.

**Comment by wsquire** [comment]
Indeed.

As for the workaround, I agree that explicit importing should work for cases where I we modify the source file. AFAIK we would have to modify that enums file to start with **`export`**` module enums ...`. Is there a way to explicitly import a file which does not export?

This is the crux of the issue with Typelite. The enum file generated by Typelite has a structure just like in my steps. I believe I can not explicitly import a Typelite enum since it is generated and, as far as I can tell, there is no way to alter how the module is declared when it is being generated.

**Comment by lordzero83** [comment]
We want to use CLI in out current project for better updateability, but could not switch due to the enum problem.
We also use Typlite to generate our enums.

Is there anybody investigating this problem and can say when the problem will be solved?

**Comment by KhodeN** [comment]
@lordzero83 I found the reason: https://github.com/angular/angular-cli/issues/2741#issuecomment-294696150

It's need for performance. Each ts file compiles separately, without information from other files. While `transpileModule` is used, the trouble stays.

**Comment by Gustorn** [comment]
The thing is, `ts-loader` with its [fork-checker-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) beats `awesome-typescript-loader` in some of our projects *and* it actually generates correct code.

**Comment by squadwuschel** [comment]
@KhodeN it would be great if the cli could provide a configuration parameter, where it ignores the performance improvements so that you can use the cli also with const enums and a slower performance would be ok for me.

**Comment by MikeMatusz** [comment]
This is a major issue for us, as well.  The fact that it's a runtime error makes it even worse because it's really easy to miss.  @hinaria , what webpack plugin are you using to do the replacement?

**Comment by omouse** [comment]
This seems to still be an issue but in a different way, and it's causing issues in other module repos: https://github.com/swimlane/ngx-datatable/issues/927

**Comment by clydin** [comment]
With CLI 1.5+ and Angular 5, the use of `transpileModule` has been eliminated.  Note that Angular 4 uses the previous compiler pipeline so if const enum support is required please update to Angular 5+.

**Comment by josephliccini** [comment]
Tested this out and it works! Thanks for fixing it 👍
