### ISSUE TITLE
Outdated webpack version for @angular-devkit/build-angular 16.2.14

### ISSUE THREAD

**Issue by conrezo** [angular/angular-cli#28043]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Superclass- is replaced with null in production build for the current used version of webpack (5.88.2)
Please see the issue in webpack repo - https://github.com/webpack/webpack/issues/17711

### Minimal Reproduction

In my case I tried to use 3d model from Spline using @splinetool/runtime. It looks like the bug affects the runtime script.

### Your Environment

```text
Angular CLI: 16.2.14
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1602.14
@angular-devkit/build-angular   16.2.14
@angular-devkit/core            16.2.14
@angular-devkit/schematics      16.2.14
@angular/cli                    16.2.14
@schematics/angular             16.2.14
rxjs                            7.8.1
typescript                      5.0.4
zone.js                         0.13.3
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by conrezo** [comment]
@alan-agius4 the fix is not present on the latest version of Angular 16 LTS (16.2.14)

**Comment by alan-agius4** [comment]
Version 16 is in LTS phase and only received security fixes.

For all other fixes please update to the latest version.

Please see: https://angular.dev/reference/releases#actively-supported-versions
