### ISSUE TITLE
How to allow .html in URL in angular 18 like 'product/:slug.html' 

### ISSUE THREAD

**Issue by sumitpypy** [angular/angular-cli#28125]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

How do we allow .html in URL in angular 18 like 'product/:slug.html'  it is not working on refresh but it is working with the router. it shows like Cannot GET /product/abc.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 20.14.0
Package Manager: npm 10.7.0
OS: darwin arm64

Angular: 18.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
```

**Comment by sumitpypy** [comment]
@JeanMeche Although I appreciate your response, the information in https://github.com/angular/angular-cli/issues/27905 is unclear. way we are able to consent.HTML using a dynamic path. Could you give me a thorough explanation of it? We need to create a new URL since we had ones with.html in an earlier edition, so old SEO won't work.

**Comment by sumitpypy** [comment]
@JeanMeche Is there any way we can allow .html in the URL so we can retain our old crowled pages.

**Comment by alan-agius4** [comment]
This issue is separate from the server configuration. With the Vite-based builder, `ng serve` will return 404 errors for file-like requests if the files don't actually exist.

As explained in https://github.com/angular/angular-cli/issues/27905, it's generally recommended to avoid including file extensions in URLs. This simplifies server-level routing.

Possible solutions:
- Make no changes, but be aware that refreshing the page will not work when using `ng serve`.
- Remove `.html` extensions from URLs. To avoid affecting SEO, you can create a server rule that redirects `.html` URLs to the corresponding pages without extensions using a 301 redirect. This is the recommended long-term approach.
