### ISSUE TITLE
Build watch EPERM operation not permitted, copyfile on second emit

### ISSUE THREAD

**Issue by zrsio4** [angular/angular-cli#28182]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Updated my project form 17.x to 18, along with a switch to the application builder. I'm not sure if it's the update from 17 to 18, or the switch to application builder, but now my project's build watch will fail on second emit; builds fine initially, continues the watch, and the next change causes a rebuild and the watch fails with:

An unhandled exception occurred: EPERM: operation not permitted, copyfile '..\client-apps\projects\myapp\src\assets\ANY FILE IN HERE' -> '..\client-apps\dist\myapp\browser\assets\ANY FILE IN HERE'
See "user\AppData\Local\Temp\ng-A7WWmr\angular-errors.log" for further details.

The files copied in 17 are not readonly, while the files copied in 18 are, hence the above exception, I assume.

### Please provide the exception or error you saw

```true
An unhandled exception occurred: EPERM: operation not permitted, copyfile '~\client-apps\projects\myapp\src\assets\ANY FILE IN HERE' -> '~\client-apps\dist\myapp\browser\assets\ANY FILE IN HERE'
See "user\AppData\Local\Temp\ng-A7WWmr\angular-errors.log" for further details.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.4
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.4
@angular-devkit/build-angular   18.1.4
@angular-devkit/core            18.1.4
@angular-devkit/schematics      18.1.4
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             18.1.4
ng-packagr                      18.1.0
rxjs                            7.8.1
typescript                      5.5.4
```

### Anything else?

IDE is Visual Studio 2022 using TFS for source control. The assets are under source control but are not checked out prior to building

**Comment by alan-agius4** [comment]
The issue you're encountering is related to the input file is read-only. In the application builder, the build process behaves differently compared to browser builder which uses Webpack. Previously, when using Webpack, the files were copied in memory before being written to the output directory, which allowed the process to work smoothly even if the input files were read-only. However, with the new build process, the files are being copied directly, and since they are read-only, it results in the `EPERM: operation not permitted` error during the rebuild phase.

To resolve this issue, you should update the permissions of the input source files so that they are writable.
