### ISSUE TITLE
Native support to pass additional options to angular-compiler plugin

### ISSUE THREAD

**Issue by KeM1aL** [angular/angular-cli#28458]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

I would like to enable a specific option to let me build a dependency.  I need to pass deprecatedAssertSyntax = true and everything should be okay ... but I can't find a way to pass that option to the esbuild angular-compiler.

### Proposed solution

Allow generic section to pass options to esbuild plugins

### Alternatives considered

None

**Comment by clydin** [comment]
Can you provide additional information regarding the dependency you are trying to use? Without further information regarding the usage, enabling the ability to parse the syntax in third party libraries may not actually result in a working output.
Import assertions were never standardized and were only support in v8 based browser but support has since been removed. No browser officially supported by Angular can be used with an import assertion.
https://caniuse.com/mdn-javascript_statements_import_import_assertions

Would it be possible to raise an issue with the dependency to remove obsolete syntax that is not recommended for use?

**Comment by KeM1aL** [comment]
I've created an issue in the dependency repository : https://github.com/reown-com/appkit/issues/2880

But I try to find a way to use it before they release a new version including this change.

**Comment by alan-agius4** [comment]
Closing as @clydin's suggested. The best course of action is to raise an issue with the library author and address the problem upstream.
