### ISSUE TITLE
Allow to configure sass `fatalDeprecations` and `silenceDeprecations` options

### ISSUE THREAD

**Issue by sod** [angular/angular-cli#28587]
### Command

serve, build

### Description

Please allow to configure [fatalDeprecations](https://sass-lang.com/documentation/js-api/interfaces/options/#fatalDeprecations) and [silenceDeprecations](https://sass-lang.com/documentation/js-api/interfaces/options/#silenceDeprecations).

* `fatalDeprecations` can be used to prevent already deprecated features or syntax be added to the code - by failing the build - in a code base where a lot of people are working on.
* `silenceDeprecations` can be used, so you don't have to [downgrade sass](https://github.com/angular/angular-cli/pull/28234) anymore.

### Describe the solution you'd like

perhaps in the angular.json:

```
"stylePreprocessorOptions": {
    "fatalDeprecations": ["color-functions", "1.70.0"],
    "silenceDeprecations": ["1.77.0"],
}
```

**Comment by dgp1130** [comment]
Agreed this would be useful for Sass users. We normally try to abstract over and encapsulate options like this, but it doesn't seem like we can provide a meaningful abstraction on top of these options and there's not much risk of misuse by users, since they can't really break your application outside of failing from deprecations as they are intended to.

We should probably also add [`futureDeprecations`](https://sass-lang.com/documentation/js-api/interfaces/options/#futureDeprecations) which is in the same boat as the two options discussed above.

We likely don't want to put these directly in `stylePreprocessorOptions` since that applies to all preprocessors (including Less) where these options don't do anything. The better design is likely to create a `sass` sub-object which contains these three deprecation options.
