### ISSUE TITLE
Angular v18 SSR - Prerendering routesFile routes.txt when route starts with "id". Ex: "/:userId/home"

### ISSUE THREAD

**Issue by sonnyk22** [angular/angular-cli#28591]
### Command

build

### Description

Based on the feedback in this link [#28346](https://github.com/angular/angular-cli/pull/28346), `Angular v19` will provide a much better and easier way to handle the prerendering when it comes to the routes that starts with `"id"`.  But this version will not be released until Nov 19th or so.

Using the below section in the `angular.json` file:
```
"prerender": {
    "routesFile": "routes.txt",
    "discoverRoutes": false
},
"ssr": {
    "entry": "server.ts"
}
```

In `Angular v18.x`, it is is really easy to get prerendered for such basic routes as below:
```
   /auth
   /contact  
   /info/:id
```

However, is there a way to prerender when the "id" is right at the beginning of the route? For example:
```
   /:userId/profile
   /:userId/home
   /:userId/account
```

This is a unique request to prerender that I have not found any solution to on search engines.  

### Describe the solution you'd like

While waiting for `Angular v19` to be released, it would be nice to be able to prerender in `v18.x` via the `routesFile` `routes.txt` for the example routes below:

```
   /:userId/profile
   /:userId/home
   /:userId/account
```

**Comment by alan-agius4** [comment]
The placement of the dynamic part of the URL is irrelevant because the full routes are specified in the routes.txt file.  If the problem persist can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sonnyk22** [comment]
Here is the `Angular v18` repo you've requested.   The `README` file explains my question.  Hopefully, there is an easy way to handle this prerender question.   [Repo:](https://github.com/sonnyk22/angular-ssr-prerender)

**Comment by alan-agius4** [comment]
This is working as intended. The parameterized route values in `routes.txt` need to be replaced with actual values.

Example:
```diff
- /:user/profile
+ /john/profile
+ /jane/profile
- /:user/photos
+ /john/photos
+ /jane/photos
```

See: https://angular.dev/guide/prerendering#prerendering-parameterized-routes
