### ISSUE TITLE
SSR Schematics uses by default API being in developer preview state

### ISSUE THREAD

**Issue by pawelfras** [angular/angular-cli#28662]
### Command

new

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19.0.0-next.9

### Description

 Schematics for SSR generates new application with the following API that is in dev preview:
- `AngularNodeAppEngine` with `writeResponseToNodeResponse` and `createNodeRequestHandler` in `server.ts` file
- server routes in `app.config.server.ts`

Compared to previous functionalities introduced as dev preview, e.g. `provideClientHydration`, the API mentioned above is not optional but used by default.

### Minimal Reproduction

- generate new app by running `npx @angular/cli@19.0.0-next.11 new my-app` (with SSR)
- verify shape of `server.ts`

### Your Environment

Angular CLI: 19.0.0-next.11
Node: 22.8.0
Package Manager: yarn 1.22.22
OS: darwin arm64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0-next.11 (cli-only)
@angular-devkit/core         19.0.0-next.11 (cli-only)
@angular-devkit/schematics   19.0.0-next.11 (cli-only)
@schematics/angular          19.0.0-next.11 (cli-only)

**Comment by Platonn** [comment]
Hi @alan-agius4 . Thanks for taking this issue under discussion in the Angular Team.
Let me share our usecase, to help provide more context for an informed debate:

**Our Angular library**
We're maintaining an Angular library for creating ecommerce sites ([SAP Spartacus](https://github.com/SAP/spartacus/)), where we depend on SSR APIs a lot. And as an enterprise product, we care adapt new APIs of Angular only when they are declared Stable API. Otherwise we would risk too many/frequent breaking changes for our users, which we want to avoid for our users.

**Our library is installed via schematics**
Our storefront app is scaffolded in 2 steps:
1. `ng new ...` (create new angular app)
2. `ng add @spartacus/schematics ...` (install our library and scaffold a storefront app).

**Why `ng new` using Developer Preview APIs is cumbersome for us**
And if the app created in the step 1 uses Angular APIs being in Developer Preview, then we have to write our own funky schematics steps that revert usage of Developer Preview APIs, and replace with the Stable APIs - which is cumbersome.

So ideally, I'd love if `ng new` could **by default** create apps using only stable APIs, but Developer Preview APIs would be used only when an *optional CLI arg* is provided to `ng new`.

**Many thanks for your effort. Respect to your choices**
All that said, I want to thank you for all your hard work on improving Angular SSR Developer Experience. And I respect your software design choices, acknowledging they are often very hard to make.
