### ISSUE TITLE
Wrong hashing for `scripts` production bundle

### ISSUE THREAD

**Issue by ShadowManu** [angular/angular-cli#2868]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux x64 (Ubuntu 16.04)
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 6.5.0
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Using the CLI for dev/prod for more than a month. Updating to latest version continously.
### The log given by the failure.

> Normally this include a stack trace and some more information.

No errors related. (Only webpack production warnings)
### Mention any other details that might be useful.

The hashed name generated for `scripts.**.bundle.js` generated for different versions of the same app (like adding a service) is the same while the bundle content has differences (seems like chunk numbers generated by webpack).

Example flow to replicate:
create an app
add a script to `angular-cli.json`
generate a production bundle <-- generates a `scripts` bundle with a hash X.
add some TS module to the app (like a new component)
generate a production bundle <-- generates a `scripts` bundle with the same hash X but the content is different (in particular, webpack-related chunk numbers).

This affects production caching since the bundle cannot be invalidated by name since the hash works 'fake' (same hash, different content, enough to make the app fail to load).

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Thanks for the report. This looks like a bug somewhere.

**Comment by rcomblen** [comment]
Issue still there with beta 25.

Struggled half a day to understand why my app wasn't loading anymore when served thru Cloudfront.

Stumbled across this issue, updated to beta 25 to have your fix. Doesn't work for me.

I build with `ng build --prod --aot`

To test your fix, I did:
 - build once
 - change the content of one of my service file
 - build again

the inline.XXX.js has the same hash be a different content.
The difference is the following:

    c.src=r.p+""+e+"."+{0:"c66703c4cd276dc1f7c0"

    c.src=r.p+""+e+"."+{0:"9745f38a9de532556cb0"

The id there is the corresponds to the hash of my main.XXX.js: dist/main.9745f38a9de532556cb0.bundle.js

So obviously the problem is not solved ...

**Comment by rcomblen** [comment]
Further, these file names are only referred to in the index.html and the source maps. The hash should have a value that is easy to check, it should be the md5sum or sha1sum of the file.
