### ISSUE TITLE
Resolve deprecated npm critters package

### ISSUE THREAD

**Issue by Tymo66** [angular/angular-cli#28857]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

Install packages with npm install for latest version of Angular-devkit/build-angular (18.2.11) pulls in a deprecated critters package that emits an npm warn message.

### Minimal Reproduction

- ng new tour-of-heroes
- manual delete node_modules and package-lock.json (just to recreate blank situation)
- npm install:

_npm warn deprecated critters@0.0.24: Ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. If you'd like to keep using Critters, please switch to the actively-maintained fork at https://github.com/danielroe/beasties_
 

### Exception or Error

```text
no warn message on deprecated packages, just clean message
```

### Your Environment

```text
Angular CLI: 18.2.11
Node: 20.16.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.11
@angular-devkit/build-angular   18.2.11
@angular-devkit/core            18.2.11
@angular-devkit/schematics      18.2.11
@schematics/angular             18.2.11
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else relevant?

it's not really a bug, I just want to keep a clean build output, free of warnings and errors

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by itslenny** [comment]
This is not fixed in the latest published v18 version of `@angular-devkit/build-angular` which is `18.2.12`

![Image](https://github.com/user-attachments/assets/7545ab7b-f2ff-44ab-a203-a86b4a779760)

Looking at the deprecation message it just needs to be switched from `critters` to `beasties` and it should "just work" and resolve the NPM warning.

```
npm warn deprecated critters@0.0.24: Ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. If you'd like to keep using Critters, please switch to the actively-maintained fork at https://github.com/danielroe/beasties
```

**Comment by alan-agius4** [comment]
This has been addressed in version 19. Version 18 is currently in LTS and only security fixes are merged.
