### ISSUE TITLE
add `sass` to `stylePreprocessorOptions` in  `browser-eslint` for V19

### ISSUE THREAD

**Issue by lukimil** [angular/angular-cli#29014]
### Command

build

### Description

Related changes for `application` builder is added, but missing for other builders that allow to configure `sass`  

https://github.com/angular/angular-cli/pull/28627

**Comment by alan-agius4** [comment]
The `browser-esbuild` serves as a compatibility layer, providing the same options as the browser builder.  

This builder is designed to allow seamless switching between the Webpack and Esbuild builders.  

To take advantage of the latest features and functionality, consider migrating to the application builder.

**Comment by TokenR1ng** [comment]
@alan-agius4 Then how about adding this to the browser builder which is still (according to documentation) fully supported. Our project cannot migrate to the application builder at this point due to other bugs and problems, and at the same time, we cannot get rid of the deprecation warnings in our SASS files because of Bootstrap not updating their project (and so on...).

So having stylePreprocessorOptions to suppress the deprecation warnings in the browser (webpack) builder would be really helpful for us. thx
