### ISSUE TITLE
Angular doesn't use ESM modules if package is multi module format

### ISSUE THREAD

**Issue by rsmogura** [angular/angular-cli#29087]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, I use angular 18 with Sweetalert2 library. During build I got information that this library is CommonJS and it's hard to optimise size (tree shaking). In fact size of project grown up around 0.5MB

After inspecting library, it was found that library exports few types of modules through `package.json`:
```
  "main": "dist/sweetalert2.all.js",
  "browser": "dist/sweetalert2.all.js",
  "module": "dist/sweetalert2.esm.all.js",
```
and `module` is in fact an ESM module.

However Angular doesn't pick up ESM version of sources instead focuses on on CommonJS version. I would like Angular to pickup ESM versions either by default, or by using additional switches.

### Minimal Reproduction

1. Create Angular project.
2. Add SweetAlert2 library `npm install sweetalert2 @sweetalert2/ngx-sweetalert2`
3. Reference Swal alert in source code, so that alert will get displayed.
4. Build project and check output and warnings.

### Exception or Error

```text

```

### Your Environment

```text
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1802.12
@angular-devkit/build-angular     18.2.12
@angular-devkit/core              18.2.12
@angular-devkit/schematics        18.2.12
@angular/cdk                      18.2.13
@angular/material                 18.2.13
@angular/material-luxon-adapter   18.2.13
@schematics/angular               18.2.12
rxjs                              7.8.1
typescript                        5.5.4
```

**Comment by alan-agius4** [comment]
This occurs because, for browser builds, the `browser` field takes precedence over the `module` field. This behavior aligns with the default bundler behavior as outlined in [esbuild's documentation](https://esbuild.github.io/api/#platform) and [Webpack's configuration guidelines](https://webpack.js.org/configuration/resolve/#resolvemainfields)

Changing the order of resolution can break other libraries. For this reason, providing such an option in the Angular CLI is not ideal. If you need to modify this behavior, consider using a custom builder.
