### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#298]
I am not sure if this is the right project asking for it but is something like [react's hot reloading](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.jphvnz146) possible with Angular 2 + Webpack? I don't think is possible by Angular`s design?

Edit: the mentioned project is replaced by [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform).
More Information [here](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.xehif2axw)

**Comment by filipesilva** [comment]
Hm.... I know [webpack has hot reload](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack), but I get the feeling the functionality described in your links is more advanced than this.

A better place to ask is https://github.com/angular/angular, I think.

**Comment by zackarychapple** [comment]
I agree with @filipesilva that this is better asked on Core, however depending on what happens there we might need to make adjustments as well.

**Comment by doczoidberg** [comment]
seems that this is a webpack configuration issue?

https://webpack.github.io/docs/hot-module-replacement-with-webpack.html

so this is the right place for my question

**Comment by filipesilva** [comment]
Hot module replacement as provided by webpack allows an app to reload a module/file on the fly. That bit is definitely a configuration feature.

However, the way by which the application responds to having modules being reloaded is an app/framework issue. 

In the case of react, the hot reload behaviour seems to have been achieved via [heavy instrumentation](https://github.com/gaearon/babel-plugin-react-transform#babel-plugin-react-transform) of components. This makes sense, because their state needs to somehow be persisted and re-introduced on the newly reloaded components.

I am not aware of such an angular feature, but there might be something to it if you ask on the angular repo. The CLI could perhaps have webpack's hot reload, but it wouldn't do much on it's own.

**Comment by doczoidberg** [comment]
[Here](https://github.com/AngularClass/awesome-angular2) is a boilerplate with HMR enabled. It does not save the state when hot reloading.

This is a store specific thing?  Can this be solved by using RxJs?

**Comment by doczoidberg** [comment]
nice article: http://blog.mgechev.com/2015/10/26/angular2-hot-loader-hot-loading-tooling

to sum up: it works with architecture considerations or it needs additional tools which patches the components without reinitiializing them.

Are there any angular tooling repositories? I think it's time to get the right tools for angular 2 now.

**Comment by filipesilva** [comment]
I am not aware of any, but have not really looked at it. Would love to hear about it if you find them!

**Comment by johnchristopherjones** [comment]
There's a [recent article demonstrating the use of hot reloading](http://teropa.info/blog/2016/08/08/angular-2-hot-loading-with-ngrx-store-and-webpack.html) using Webpack.  Now that angular-cli is moving to Webpack, this is probably a really good thing to integrate.

**Comment by VladWulf** [comment]
You can find the angular2-cli friendly seed with redux and hot reloading here.
https://github.com/VladWulf/angular2-redux-hmr-boilerplate
