### ISSUE TITLE
ng destroy does not unlink the dir

### ISSUE THREAD

**Issue by jkuri** [angular/angular-cli#304]
When performing `ng destroy` all related files are unlinked but directory is left in the tree. This is obviously `ember-cli` issue and we should override that command and unlink the whole related directory.

**Comment by Brocco** [comment]
When implementing this fix to prevent execution of ember cli commands that are not relevant to the angular cli  please ensure that all commands are accounted for. A graceful message stating that the requested command is not valid would be appropriate.

**Comment by cwramsey** [comment]
Is there a list of commands `ng` will include (unless we're just using all current ones that are listed in the readme) that I can compare to `ember-cli`?

**Comment by filipesilva** [comment]
I think we should try to include the `ng destroy` command for our blueprints overall. `ng g route` has to take it into account because removing a route causes side effect (like updating the config).

The reason `ember-cli` doesn't automatically destroy the dirs is because they put multiple components/services/etc in each dir.

With nested routes, we might also have a situation where deleting a route shouldn't delete all files in those directories.

This feature requires a bit of effort in planning imho.

**Comment by hansl** [comment]
Destroy is no longer supported.
