### ISSUE TITLE
For Discussion: Release Frequency

### ISSUE THREAD

**Issue by Meligy** [angular/angular-cli#3127]
How often should the CLI release?

I'd argue daily, as in, whenever there's a day the team merges a handful PRs (which is obviously not every calendar day or even week day), they can just bump the version.

This is based on the fact that the CLI is still in beta, and assuming that releasing is cheap, which might be uninformed false assumption.

Working from git isn't ideal for all sort of reasons, and quite often one list of merges in a day would have something I've been looking forwards to for so long.

If the current release schedule is intentional (what is the release schedule by the way?), then can we have some `-builds` repository and packages similar to how the @angular/angular repository have?

Just starting the discussion...

**Comment by gelliott181** [comment]
Before I put in my opinion, I always suggest checking https://github.com/angular/angular-cli/milestones for more detailed release info, specifically what features and bugs are being focused on by the guys at Google to reach API and feature stability.

As you said, working from git is a little difficult, but until the CLI is at Release Candidate stages I don't think a rapid release schedule fits. The team is working hard on core features which means the functionality day to day may not be stable, increasing overhead as a build has to be checked and stripped of said partial functionality.

I'd rather have a somewhat irregular release cycle during beta if it means the CLI itself will continue to be built with long term maintainability and a good ear for the community's input. That said, if the community pushes to release on the daily, they'd likely discuss it. In support of whatever schedule they make though, I hope they choose to aim for solid releases rather than rapid until the CLI is ready for RC and Final releases.

**Comment by Meligy** [comment]
I don't think the CLI stability is an issue.

Almost all code is done via PRs. PRs first are discussed, and then if needed gone into `pr_action: review` status, then several days later (even for the tiniest PRs), they get approved, marked `pr_action: merge` (marking status and action is done via labels). Several more days, the team picks only some of these supposedly all ready to merge PRs and adds some of them in one day, possibly leaving a few others.

The merge activity doesn't happen every day as I mentioned above (possibly daily is a bad word to express it), although the team has been pretty active this month, possibly as it gets closer to RC.

I hope you do realise that what this issue is, is simply a community discussion, to gather community input, like the `+1`s on the issue, and like your comment, etc.

**Comment by clydin** [comment]
I think a release schedule and/or roadmap would be incredibly useful.  However and in general, releases are rarely cheap for a large project.  The CLI is also somewhat more complicated as the user's generated projects may need to be _upgraded_ as well.  Too frequent updates can lead to upgrade fatigue and/or user confusion.

I would also caution against the assumption that the PR process acts as a panacea for stability issues.  While it does greatly mitigate stability concerns it does not remove them.  Formal release processes exist for a reason.

As an RC appears to be close at hand, I would prefer the team focus on feature improvements and bugfixing rather than pushing releases.

**Comment by filipesilva** [comment]
We do manual releases, and while I wouldn't say a release is expensive I wouldn't say it's cheap either. Currently time is (by far) the most scarce resource the team has and making a release does mean that other stuff isn't being worked on.

We are looking at setting up a regular release cadence, possibly mirroring that of Angular 2 itself. We also talked once about doing nightlies.

We also want to use the "Projects" feature of github to organize stuff better, which should give more visibility. There's some stuff there now but it's not a comprehensive list. Organization will get better in the coming months.

**Comment by fxck** [comment]
So seeing my issue was closed, what's the current status on this? While I understand it takes a while to setup the `*-builds` repo, many other repos of this org has already gone thru it and I'm sure would be willing to help it set up. @DevVersion did it very recently on @angular/material2.

**Comment by filipesilva** [comment]
Nowadays, in post-1.0, our release cadence is as follows:
- weekly patch releases
- minor releases when there is a good amount of features in, and beta/rc weekly meanwhile.
