### ISSUE TITLE
github pages deploy create wrong base href for repos with camelcase names

### ISSUE THREAD

**Issue by krabolov** [angular/angular-cli#3146]
Ubuntu 16.04
angular-cli: 1.0.0-beta.19-3

1. Create repo with name like this: `someRepo`
2. `ng github-pages:deploy`
3. Base href will be `/some-repo`, not `/someRepo` as was expected.

**Comment by taylorjb** [comment]
The `ng github-pages:deploy` command derives `baseHref` from `packageName`, which is pulled from `package.json`.

`package.json` is created through `ember-cli/lib/models/blueprint.js` which uses the `normalizeEntityName` function to `dasherize` as they call it.

There must be a way to override the `normalizeEntityName` function to support camelCase.

**Comment by WebDesignerKits** [comment]
This also creates a problem for github pages that use custom domains.

In which case the base href needs to default back to just "/" and no longer the name of the repo, or "/some-repo".

Because unlike the github page, which serves content from some-account.github.io/some-repo
A custom domain no longer has the extra file path ie, not this myWebsite.com/some-repo

Instead it servers from myWebsite.com, and so it needs a "/" base href.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
