### ISSUE TITLE
Page reload extremely slow

### ISSUE THREAD

**Issue by stefanmeschke** [angular/angular-cli#3315]
### OS
Mac OSX 10.12.1 (16B2555)

### Versions
```
angular-cli: 1.0.0-beta.21
node: 6.5.0
os: darwin x64
```

### Repro steps.
- Project was created with `ng new`
- After putting all dependencies in the AppModule, we decided to create some `NgModule` to import and export Components/Pipes/... in separate modules
- After this step the page reload increased extremely. At this point we do not know whats happening inside.

Does anyone has/had the same issue?

Many thanks in advance!

**Comment by borislemke** [comment]
@stefanmeschke how slow is slow to you? On my dev machine average reload is around 10 ~ 20 seconds and just under minute with `--aot`.

**Comment by filipesilva** [comment]
I wonder if this is the same as https://github.com/angular/angular-cli/issues/1980 or a separate problem the contributes to it.

@stefanmeschke can I ask you to give me a very precise repro with rebuild times? Something like
- do `ng new`
- do `ng serve`, change files a couple of times and had this rebuild time (this is important because the first few rebuilds are always slower)
- changed code in exactly this way
- repeated step 2, rebuild times are now this.

**Comment by hccampos** [comment]
@stefanmeschke mentions importing and exporting several modules, maybe using index.ts. This is in line with a theory of mine that one of the causes could be index.ts files or modules exporting a bunch of stuff and causing webpack to have to traverse a lot of stuff for each rebuild. I haven't been able to test this theory to confirm or reject it, but will hopefully do that soon.

In any case, since build performance is so abysmal with TS and webpack, it will be really nice to start finding the best ways to code and structure apps in order to keep build times short.

**Comment by filipesilva** [comment]
Closed as inactive.
