### ISSUE TITLE
How can I debug this in webstorm to make changes in it to custom for my requirement

### ISSUE THREAD

**Issue by kushwahashiv** [angular/angular-cli#335]

**Comment by zackarychapple** [comment]
What portion of the CLI are you trying to debug?  Also what type of changes are you looking to make?  There may be command line flags that will get you there.

**Comment by kushwahashiv** [comment]
Hi Zackarychapple,
I find difficulty in creating services folder inside the module folder. Very similar to the components we can create using generator.

Below is the directory structure i want to create  for my proejct.
Client
   - src
         -app
                -layout
                         -components
                         -services       <- this I want in individual modules i.e. layout
                         -pipes
                        -directives   
               -abc
              -.....


I was trying to debug angular-cli code in webstorm to understand the code flow so that I can make changes to achieve above structure.
[Angular-cli-services](https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/service/index.js)
I put break points in service.and when I was doing 'ng g service my-new-service' it was basically add service in the  below structure:
      Client
   - src
         -app
               -services  <- here generators was adding which didn't want to 
                -layout
                         -components
                        -directives   
               -abc
              -.....


Hope this help you understand what my was trying to achieve  and also why I was not able to break on breakpoints in webstorm while running the service command

**Comment by zackarychapple** [comment]
I am not aware of any easy ways to debug the CLI in the way you are trying to.  I spent some time trying to look into it and since the CLI is independent of the npm flow it makes it even more challenging.  However in terms of changing the structure, My understanding is that this is something that would be unsupported since the CLI is using that structure for multiple processes and is setting that structure in accordance to the Angular2 Styleguide.

**Comment by filipesilva** [comment]
I believe dynamics paths are in at the moment, and that allows you to choose your own paths when generating a command.

For instance, `ng generate service src/app/layout/service-name` should give you a service in the directory you want.

As far as debugging in webstorm, I am unfortunately not able to tell you much as I do not use webstorm... But since your breakpoints are not being reached, I suspect they might be on the wrong file - when you run the cli there are both a global and a local package. 

If you do not have these symlinked to be the same thing, you might not be using the file you think you are using. Check https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli and note the `npm link angular-cli` line, this is the one that links both codebases.

**Comment by zackarychapple** [comment]
Thanks for the correction @filipesilva

**Comment by kushwahashiv** [comment]
Thanks a lot zackarychapple and filipesilva for your effort to help me out to resolve the issue.
Here are my findings:
- if I use command 
````bash
ng generate service src/app/layout/service-name
````
when I run below commands:
<img width="848" alt="screen shot 2016-03-26 at 12 22 04 am" src="https://cloud.githubusercontent.com/assets/4386810/14051437/db1b42b8-f2e8-11e5-8222-634fffa49cff.png">

When I run 1st command shown in above I got below folder structure created:
as shown below:   
<img width="373" alt="screen shot 2016-03-26 at 12 19 34 am" src="https://cloud.githubusercontent.com/assets/4386810/14051449/f872cc1e-f2e8-11e5-9f61-81a536186583.png">

But when I run the 2nd one (as shown above in  snippet) it basically created the exactly I was looking for:
<img width="373" alt="screen shot 2016-03-26 at 12 19 34 am" src="https://cloud.githubusercontent.com/assets/4386810/14051443/e6e7de6c-f2e8-11e5-8a5f-3d0baf24eea2.png">

I was not passing the correct path while generating services so it was generating as my previous post. I also feel it has a bit confusing generating structure. 

Thanks again for the help

**Comment by filipesilva** [comment]
Glad to be of help!
