### ISSUE TITLE
Remove extraneous barrel at the app root

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#3369]
### OS?
Mac OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: darwin x64

### Repro steps
`ng new foo`

### Details
`src/app/foo/index.ts` is created and represents a barrel for `app.module.ts` and `app.component.ts`

This is referenced from `src/app/main.ts`

Removing the `index.ts` file would only require one change in the app:

Before
```
// main.ts
import { AppModule } from './app/';
```

After
```
// main.ts
import { AppModule } from './app/app.module';
```

Reason:
1. One less file is easier to read.
2. One less concept to learn for the user (barrels)
3. It only used in one place, so it is easy to code without the barrel

**Comment by digimax** [comment]
yeh you are just going to confuse the daylights out of some N00bz using typescript barrels with reckless abandon, like u decided to do here.

**Comment by bhaskerchari** [comment]
@johnpapa,

I am totally confused whether to use barrels or not with angular2 ?

I am trying to use barrels the imports does seem to reference properly but when I run the application it doesn't seem to work as intended unless I import them without using any barrels.

Can you please confirm going forward we shouldn't be using any barrels concept? Since even in angular docs I don't see any references to barrels in examples.

Thanks,
Bhasker

**Comment by wulfsberg** [comment]
Barrels have essentially been superseded by `NgModule`s, which provide the same "one-stop import" for the using code, but also handle Angular-specific things like setting up the needed providers.

**Comment by johnpapa** [comment]
@bhaskerchari  Hi. Barrels help reduce the number of import statements, and can reduce the length of your imports. They do this by consolidating imports into a file (often called a barrel) and then re-exporting them. Thus our code can just import from the barrel, which repoints to the others. Angular does this itself with things like `@angular/core`.

With the advent of `NgModule`s we have less need for these barrels. Why? Because the ngmodules let us break the app up into functional areas and thus we have fewer need to import across them. It doesn't eliminate the value of barrels, but I feel it does dramatically reduce their value in most Angular 2 apps.

An example of this can be found in my event-view repo on github https://github.com/johnpapa/event-view

I hope this helps clarify a little

**Comment by wulfsberg** [comment]
Just to add: There shouldn't be any functional difference between importing directly or through a barrel. It is purely a stylistic matter where you want to stack your imports. There is nothing wrong in using them, and they should work.

**Comment by bhaskerchari** [comment]
Hi @johnpapa ,

Thanks for clarifying that up and it does really makes sense now with the advent of NgModules we have less need for these barrels.

While I do see the advantages with the barrels but there seems to be design problems too with usage of it in a way it creates cyclic dependencies between the different exports in a barrel where one has a dependency on another and makes the exports order non trivial otherwise there is more likely chance of breaking the app with an unintended behaviour.

Maintaining the correct order in barrels can be tricky sometimes especially when you do have lot of exports and can become a painpoint.

@wulfsberg Please refer to the below link which I am referring to:
[http://stackoverflow.com/questions/37398829/barrel-import-appears-to-break-load-order](url)

Having said all that I am getting rid of barrels from the project that I am going to work on.

Thanks,
Bhasker
