### ISSUE TITLE
mobile support ?

### ISSUE THREAD

**Issue by johnqiuwan** [angular/angular-cli#3380]
Hi All, 

  When does the mobile flag will be supported ? I really want to make the app PWA (progressive web app) way : )

**Comment by jvitor83** [comment]
Hi, i have created a seed that has some PWA features with this CLI at https://github.com/jvitor83/angular-seed-cli-admin

To achieve the PWA i use 
- the https://github.com/GoogleChrome/sw-precache for offline
  > _using the config file at https://github.com/jvitor83/angular-seed-cli-admin/blob/master/sw-precache-config.js and the command at https://github.com/jvitor83/angular-seed-cli-admin/blob/master/package.json#L12
- and have created the manifest.json to achieve splashscreen
  > _https://github.com/jvitor83/angular-seed-cli-admin/blob/master/src/scripts/manifest.json_

**Comment by Taco-Gestapo** [comment]
Hi John,
I don't think the mobile flag is supported anymore. it ay be a point of contention, not sure. it's most like deprecated. I would think that this decision was fairly easy to arrive at, since if you are doing Angular2 right, and use the material2, your work will work in all modern browsers, and not so modern browser, regardless of your client's OS or platform or whatever the correct buzz word is currently.

**Comment by hansl** [comment]
IT's not. We're working on an example of a working mobile app using the CLI, but it won't be as simple as passing a flag anymore. That functionality will come back when we support addons and custom templates.

**Comment by kuncevic** [comment]
@hansl any updates on example yet?
