### ISSUE TITLE
20%

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#3446]
Windows 10

I use cli v22-1

So I don't know why I don't have message error LIKE WHEN RUNNING ng build command !

I spend so much time to understand why ng serve is blocking at 20% without any kind of errors...

But when running ng build I have a great error that help me to see where is the problem : 
```
Template parse errors:
There is no directive with "exportAs" set to "ngForm" ("<h1>Template Driven</h1>
<form (ngSubmit)="onSubmit(f)" [ERROR ->]#f="ngForm">...............
```

So I just remove my FormsModule ! after specify my ng serve works !

**Comment by fsx999** [comment]
same for me

**Comment by drew-moore** [comment]
This (ng serve hanging at 20%) started happening for me when I tried running with TypeScript 2.1. Reverting to ~2.0.3 resolves it.

**Comment by istiti** [comment]
The problem here is not what is the solution to resolve, the problem is I expect from ng serve get me same error like ng build to tell me what is wrong otherwise impossible to find !

**Comment by drew-moore** [comment]
I meant it resolves the problem, not the issue you've raised. 

Your issue is valid, but cli doesn't explicitly support TS 2.1 yet and it seemed worthwhile to note that this looks like a 2.1-specific problem.

**Comment by morninng** [comment]
This problem happened TS 2.0.10, too.

**Comment by jwuliger** [comment]
I am not sure what to do anymore. Yesterday my CLI app was working without issue using TypeScript 2.0.10, Angular 2.2.4. So today I saw the release of Angular 2.3.0. I updated my dependencies and that is when `can't resolve module` at 20% showed up. I have since reverted all the changes I made today back to the way my app was when it was working Yesterday, and now I am still having the same problem. Even when I use TypeScript 2.0.3. I am on a Windows machine with node 7. No idea what to do...

**Comment by hansl** [comment]
`serve` blocks because webpack-dev-server does not support async plugins; when an error happens in an async plugin webpack-dev-server just stops working, instead of reporting the error and waiting for a change.

`ng build` should give you the proper error to fix here. Once that error is fixed, `ng serve` will be working fine.

**Comment by istiti** [comment]
It's not reason to close issue or add documentation to teach to users that they need run ng build if serve is blockin! Thanks 
I think issue and bug is always here issue need to be open to show people what they can do, thanks

**Comment by hansl** [comment]
Just to add to what I said above: https://github.com/webpack/webpack-dev-middleware/issues/156.
