### ISSUE TITLE
Stable | Final Version of CLI | When would it be ready?

### ISSUE THREAD

**Issue by anupamarachuri** [angular/angular-cli#3471]
Hi Team,

We started with CLI 17 and it is now 20. The npm install of 17 does not work when there is another latest version available. We are looking for a consistent version of CLI so that developers can checkin the package.json and can install the older versions too. 

1) Is it possible to install a specific version of CLI and are all the versions available somewhere. Please provide the command?
2) By when would the CLI be final and ready without further changes/versions?

Thank you in advance!

With Regards
Anupama Rachuri

**Comment by gelliott181** [comment]
You may want to re-approach how you handle the CLI. The global install references each project's local installation of the CLI at `node_modules/.bin/ng`, and you can peg the project's dependency to a specific beta. By changing out the package.json `scripts` to reference the local installation you never have to worry about the global install being different from the local, but you will have to use `npm` to start your app rather than `ng` as `ng` references whatever global CLI you have, and the local installation must match the global in that case.

I re-wrote all my CLI package.json files to use a local install so that my Jenkins server can just `npm install` and then `npm test` immediately without requiring globals to be maintained. It works very well, and though I've brought my projects all to beta.22 so far, I used to run four different versions due to various bugs.

**Comment by hansl** [comment]
1. You can fix the version of the CLI in your project, so what you use globally won't matter.

2. We're hoping for an early 2017 release.
