### ISSUE TITLE
setting node_debug 

### ISSUE THREAD

**Issue by tag42git** [angular/angular-cli#3559]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Sorry, noob question.  I just want to set the NODE_DEBUG environment variable for node so that I can see where a possible require() circular dependency might be.  I'm getting an empty object back from require() in javascript on (I think?) browser side.  Using angular-cli: 1.0.0-beta.19-3, node: 6.5.0, linux x64

**Comment by hansl** [comment]
NODE_DEBUG would not help you with circular dependencies in the browser, because webpack itself does not take it into account when building the bundle that's served to your browser. It's only useful for server side debugging.

Please note that CommonJS allows circular dependencies. But it does not allow for good tree shaking. I suggest you change your requires to imports instead, and the circular dependency might show up at that point.

**Comment by tag42git** [comment]
Thanks hansl, I will try that but since then I think my problems are with Webpack and I need to read up on that...
