### ISSUE TITLE
Webstorm (intellij) coverage integration with the angular cli

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#3560]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
n/a

### The log given by the failure.
> Normally this include a stack trace and some more information.
n/a

### Mention any other details that might be useful.
> Is there a way to display code-coverage inside of intellij/webstorm? The cli uses the test.ts file which does some aggregating of the spec files. The problem is, karma uses that and only that file to test. Is there a guide? Perhaps I'm just doing in incorrect? 
Thank you!

**Comment by zackarychapple** [comment]
Right now the Karma plugin for IntelliJ / WebStorm only supports karma-coverage for the coverage reporter. This keeps the stats from showing up in the IDE when you run coverage.

**Comment by filipesilva** [comment]
No idea how to do it in WebStorm. I don't use it myself. Will tag issue for community help.

**Comment by marklagendijk** [comment]
I did some research into this.

- The existing Karma coverage feature in Webstorm works specifically for the [karma-coverage plugin](https://github.com/karma-runner/karma-coverage). 
- There is an (old an ignored) [issue on Youtrack](https://youtrack.jetbrains.com/issue/WEB-10303) to support coverage in a generic way.
- The 'communicating an lcov file to Intelij'-part seems to be trivial:  
``` js
// start
intellijUtil.sendIntellijEvent('coverageStartupStatus', {
    coveragePreprocessorSpecifiedInConfig : coveragePreprocessorSpecifiedInConfig,
    coverageReporterFound : coverageReporterFound
});

// end
intellijUtil.sendIntellijEvent('coverageFinished', lcovFilePath);
```

I think the ideal solution would be to have a plugin (preferably made by the Webstorm team itself), which:
- Allows watching paths for changes to lcov files.
- Triggers the 'coverageFinished' event whenever a lcov file changes.

This would solve the coverage issue for basically all use cases (not just Angular 2), because lcov reporters exist for basically everything.

**Comment by mgechev** [comment]
@marklagendijk thanks for sharing your vision! I agree that the CLI might not be the right place for this feature request. I'll close the issue, please open a new one in case I'm missing something.
