### ISSUE TITLE
Upgrade to typescript@2.1 and rxjs@5.0

### ISSUE THREAD

**Issue by neolwc** [angular/angular-cli#3579]
Is there a plan to upgrade these dependencies?

**Comment by kunl** [comment]
and 4.0.0-beta?

**Comment by vfedoriv** [comment]
As I see, migration to TS 2.1 not finished: 
https://github.com/angular/angular/pull/13294

**Comment by the-destro** [comment]
YMMV but you can manually update to them in your package.json. I have not hit any issues thus far.

**Comment by jammerware** [comment]
I'm unable to use Typescript 2.1.1 (and up) with beta-24. When I `ng serve` with this combination, I get the below error:

```
ERROR in AppModule is not an NgModule
```

(AppModule is the module I bootstrap in `main.ts`)

Let me know if I can provide any additional information.

**Comment by hikalkan** [comment]
I have the same issue "ERROR in AppModule is not an NgModule".
But my application is properly running.

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/3426#issuecomment-269669853:
>>>
I just want to say that `@angular/compiler-cli` is NOT compatible with TS 2.1. The CLI itself is compatible and will work fine with TS 2.1, but since we use `@angular/compiler-cli` it won't work.

Refer to https://github.com/angular/angular/pull/13294 for more information. Closing this as nothing needs to be done by Angular CLI.
