### ISSUE TITLE
Visual Studio 2015 update 3, files are hidden

### ISSUE THREAD

**Issue by ehsaanwelcome** [angular/angular-cli#3614]
OS = Windows 10
Version = 22

I have asp.net core project in visual studio 2015, if i add any new file in file explorer on system then visual studio detect that file immediately and show in solution explorer but when i generate component through ng g c -name then visual studio dot not detect them until i manually add them or restart IDE.

**Comment by mattdistefano** [comment]
Been a while since I used VS but you may need to set 'show all files' on your solution explorer to see the generated files, then right click and 'include in project' on the generated directory to pull it into the project. Would be nice if this happened automatically but AFAIK that would require a VS extension.

**Comment by ehsaanwelcome** [comment]
Yes, i know about show files but ng generated files does not even show up with show hidden files. 

One more thing, if i add any folder and file in file system then aspnet core project (asp.net projects) show them immediately without even show hidden files and include in project

**Comment by rosdi** [comment]
I am using Visual Studio 2015 here, you need to click the refresh/reload button in order to see the newly generated files (show all files also must be enabled).

**Comment by filipesilva** [comment]
That's a VS2015 problem it seems. There's nothing we can do on the CLI's end.
