### ISSUE TITLE
Combining multiple css preprocessors in an angular-cli project

### ISSUE THREAD

**Issue by madoar** [angular/angular-cli#3616]
I'm asking myself if it's possible to use multiple css preprocessors in one angular 2 project that is managed by angular-cli.
Let's say I have two components component1 and component2, where component1 has a stylesheet written in less and component2 has a stylesheet written in scss.
Is it possible to do that? If yes, does it works out of the box or do I need to do some modifications to make it work?

**Comment by filipesilva** [comment]
Yeah it's fine really. It works out of the box.

**Comment by jj707** [comment]
@filipesilva could you provide a simple example?

Maybe a short description to clarification:
I have a project with a root module (everthing in "LESS").
Now I wanted to create an abstraction of a third party library grid and encapsulate that into an seperate module. But this third party library grid requires "SASS/SCSS". 

Switching the preprocessor is no option because we decided to use "LESS".

Best regards
