### ISSUE TITLE
Requiring a npm module that has ES2016+ .js dist files

### ISSUE THREAD

**Issue by Laoujin** [angular/angular-cli#3634]
## Environment
OS: Windows 8
Versions: angular-cli: 1.0.0-beta.22-1
node: 6.4.0
os: win32 x64

### Repro steps

```
npm install -S fold-to-ascii
```

In app.component.ts:

```
const ASCIIFolder = require("fold-to-ascii");
console.log(ASCIIFolder.fold("sometêxt"));
```

### Problem

The fold-to-ascii is a JavaScript file that uses ES2015 features: `class ASCIIFolder`. (https://github.com/mplatt/fold-to-ascii/blob/master/lib/ascii-folder.js)   
The tsconfig.json does say `"target": "es5"` but because it is JavaScript, it is not transpiled to ES5.  

So, an `ng build` creates a `/dist/vendor.bundle.js` that still contains the "class" keyword and Internet Exploder is not happy.

This is not a problem with "fold-to-ascii" specifically but an issue for any npm package that has .js dist files that have not yet been transpiled to ES5.

This seems like a common use case but I was unable to find any info on how to tackle the issue within Angular-CLI.

**Comment by Laoujin** [comment]
We fixed this specific issue by downgrading to `fold-to-ascii@2.0.2` as mentioned in their readme.

It would still be interesting to know how to do this though?

**Comment by filipesilva** [comment]
"Internet Exploder" made me laugh :D

Yeah I don't think we have an ES2015 transpiler for modules exported like that. I guess we would but it would make all builds super slow, since all JS would be processed like that.

I think but am not sure that it's mostly a question of library publishing best practices. When libs are published they should have as ES5 code as `main` in `package.json`, and if they want ES6 in `jsnext:main`.

You can read it up on https://github.com/jsforum/jsforum/issues/5.

That library specifically seems geared towards node usage so the author is fine with it being used only on node6 and above. But you need to use it in a browser environment and in there ES5 is kind.
