### ISSUE TITLE
Install specific version

### ISSUE THREAD

**Issue by LucasReSilva** [angular/angular-cli#3635]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Mint 18 64bits

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Node v6.9.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
sudo npm uninstall -g angular-cli && sudo npm cache clean && sudo npm install -g angular-cli@1.0.0-beta.20-4
then ng -v, and i got angular-cli v1.0.0-beta.22(latest)

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.
I'm need to back to 1.0.0-beta.20-4, but i can't

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filoxo** [comment]
Are you inside a directory that has `node_modules/`? If so, `ng -v` would report that version, not the globally installed one. For updating your global CLI, move to a directory that doesn't have node_modules installed (something like your `~` dir). You'll also want to update and save your project's version so that there isn't a version mismatch.

**Comment by filipesilva** [comment]
@filoxo summed it up pretty well, cheers!
