### ISSUE TITLE
92%

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#3657]
I use cli v.22-1

I will have big project. actually I have lazyloading for 20 or 30 modules... when I do ng serve or ng build with --aot option ... the cli take a long until finish, it wait at 92% 
I think chunks generating (it takes 5mn) ... 
My project will be more bigger 100-200lazyloading modules and I'm scared if this will take 1 hours to generate project....

when cli finish generating with AOT, my project works without error... and I wonder if this is normal or how can I know if something in my code is blocking this  step ?

**Comment by hansl** [comment]
Unfortunately this is the feedback that `webpack` provides. Chunk optimization is slow for even smaller apps than yours, and it is up to the webpack project to make it faster, since the CLI itself does not have control over that step.

In general, as a word of advice, I would not use AOT locally but only when you're ready to ship to production.

We have various tracking issues for build and install times. We're always trying to improve on those fronts, so there is some hope. But I'm going to close this particular issue as WAI.
