### ISSUE TITLE
Why cant I ng init in a directory with a period in it's name?

### ISSUE THREAD

**Issue by Martin-Andersen** [angular/angular-cli#3718]
Name of folder: Goo.WebApp
running ng init --prefix=goo --style=scss

getting error: We currently do not support a name of "Goo.WebApp" - Why!!!

What part of the cli are using the root folder name?

**Comment by filipesilva** [comment]
The main component is using the project/folder name, which is why it's limited to html5 custom component format (dash separated, two or more words).

**Comment by MarkTiedemann** [comment]
I think many other repos, especially those containing web-apps, are `.`-separated. How about, if a `.` is encountered in the name, simply changing it to a `-`? I don't think anyone would be too surprised about that behavior.

Otherwise, if you don't like this suggestion, the CLI should at least print a more descriptive error message, letting you know which chars in the name cause issues. If that would happen, users could fix it straight away, instead of having to manually try which chars are causing the issue and/or searching for / opening an issue here.

**Comment by Martin-Andersen** [comment]
As a work around I renamed my goo.web to gooweb before running ng new.
and then renamed it back to goo.web
