### ISSUE TITLE
Make skip-npm as default and provide enable-npm as an option 

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular-cli#3741]
I am using angular-cli with the skip npm option and do npm install manually. It takes few milliseconds to generate the code and then npm install command installs all the package dependencies, the time taken for it to complete depends on the environment.  in Mac OS, install takes minimum of 5 minutes for me. 

Why can't angular-cli ask the end user to do the npm install manually?   This is make Cli to take few milliseconds and npm install becomes another step which angular-cli has no control of.

**Comment by clydin** [comment]
The npm install is a required step.  The project won't work without it so the end result would be an extra required step with no overall time savings.  And most likely an increase in issue reports due to npm install not being run.

There's also ongoing work to reduce the initial install time.  Which while annoying is realistically only a one time event for a project.

**Comment by hansl** [comment]
As @clydin said.
