### ISSUE TITLE
[Feature] Generate components/directive with 'attribute' selector

### ISSUE THREAD

**Issue by mp3por** [angular/angular-cli#3833]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.22-1
node: 6.9.1
os: win32 x64

I would like to be able to specify during component ( and not only ) generation what kind of selector I would like the component to use - attribute or tag. Currently it defaults to 'tag' and thus I have to always remember to change it.

**Comment by baruchvlz** [comment]
Doing this:
```typescript
import { Component, OnInit } from '@angular/core'

@Component({
  selector: '[my-selector]',
  template: '<h1>My Selector'
})
export class MySelectorComponent implements OnInit {
  constructor() { }
  ngOnInit() { }
}
```

Then calling the component like so: `<div my-selector></div>` doesn't follow the (Style Guide - 05-03)[https://angular.io/styleguide#!#05-03].

**Comment by mp3por** [comment]
I understand this however this is just a style guide. Your project is about making interaction with Angular2 easier, to convey good practices and improve Angular2 experience which I highly appreciate since I would have not been able to do my job so easily without offloading things to you ( like webpack ) in the beginning. Yet I see no reason why you should not support features available in Angular2. And attribute selectors is a supported feature. 

On the side: I also do not think this particular point in the style guide is correct. I feel like the benefit of quickly distinguishing between component and directive by using attributes for directives and elements for components yields a much more serious problem - I found out that most browsers just skip elements they do not understand natively yet. This breaks CSS. One can easily overcome this by using a naming scheme for directives and components like d-directive-name and c-component-name and gain the full support and predictability of CSS.

**Comment by baruchvlz** [comment]
The reason for the style guide is so all Angular 2 projects' structures are similar so developers don't have to spend too much time having to figure out what does what, is very useful and everyone should do it. From my limited experience with Angular 1.x I can safely say that working on projects that some-what followed John Papa's Style Guide were a lot easier to work with than those that didn't.

Now, your other point, that's is something I feel you should take up over at  the framework's [repo](https://github.com/angular/angular) but, in my opinion, having `components` being called as elements and `directives` as attributes is more than just being able to identify them quicker, it makes logical sense. `Components` are basically custom HTML Elements that hold and display data and `directives` is where that data gets manipulated. For example, a `mouseenter` event that will change an icon into a checkbox (sort of like Google's Inbox) or a scroll event that will set a navbar component into a fixed position when scrolled pass X. I also feel that thinking of `components` and `directives` this way makes it easier to learn how to use the framework.

**Comment by mp3por** [comment]
Yeah man I totally agree with your point about similar projects' structures.

My point is that I see no harm in adding this functionality for projects that for one reason or another do not follow the style guide to the point. You can still use element selectors as default but have a switch for the other supported types of selectors since ... well they are supported even if their use is not 100% encouraged all the time. You could even make it generate a warning during component generation which will explain that this is against the style guide. But just as the name implies - it is a style **guide**

**Comment by filipesilva** [comment]
I don't think this is something we want to add for two reasons:
- it's in direct opposition to the style guide, even though it's admittedly just a recommendation
- feature creep, it's one more flag that needs to be tested and maintained
- trivial to do yourself, you're always going to edit that component afterwards

I'm reception to reopening the issue if there are a lot of people asking for it, though.

**Comment by jakehockey10** [comment]
@filipesilva , I don't necessarily think this should be re-opened, but I just wanted to ask a clarifying question.  If I have a sidenav with a plethora of links and `<sections>` and I'm using a UI tool like VMWare's Clarity or Bootstrap, for example, certain rules on the structure of these elements are required to be adhered to for the CSS styling to work.  For example:

``` html
<clr-main-container>

  ... lots-o-html up in here ...

  <div class="content-container">
    <nav class="sidenav" [clr-nav-level]="2">
      <section class="sidenav-content">

        ... section 1 stuff ...

      </section>
      <section class="sidenav-content">

        ... section 2 stuff ...

      </section>
    </nav>
    <main class="content-area">
      <router-outlet></router-outlet>
    </main>
  </div>
</clr-main-container>
```

As my project continues to progress, I start to have really large template files.  I base this "measurement" on how much I have to scroll, which may not be reason enough to do what I sometimes do: start taking sections of these larger component templates that have dynamic behavior and extracting that portion of the template and the logic in the component class to its own component to keep that concern isolated.

But as soon as I do this, the structure of my navigation has changed if I follow the style guide strictly.  Instead of two `<section>...</section>` elements as siblings inside the `<nav>...</nav>`, if I extract the second section into a component in and of itself, I now have a `<section>...</section>` that is a sibling to a `<my-section-component></my-section-component>`.  VMWare's Clarity has no idea what a `my-section-component` selector is, so this section I extracted does not show up well, if at all.

Clarifying question(s) time: Is this enough reason to break from the style guide and use a attribute selector for this component?  Is there an alternative suggestion for these types of scenarios that still follow the style guide?

Maybe the answer is: don't worry about how large your template is getting.  But I would say to that, "maybe it is not so much about how large the template is getting but more so about how much logic ends up being in my root component because the navigation was intended to have very dynamic content and the logic behind that would have to also belong in the root component's class.  Keeping a class small may be more important than keeping its template small."

What do you think?

**Comment by filipesilva** [comment]
@jakehockey10 I think that's a pretty good reason to break away from the style guide for those components.

When there's CSS and other libraries that add behaviour/styling to them depending on their html position, they are moving away from being simple dumb HTML tags and can now be considered custom components.

So now you want to add some extra behaviour to them, and following this mindset you don't want to wrap another component around them. Instead you use an attribute selector to add more behaviour.

There might be other lessons to gather from this topic, and for that I'd recommend talks by the https://github.com/angular/material2 team. There's usually a few in-depth ones on each big conference that go over why they changed X and Z, and it's usually for the sort of concern that you're exploring.

**Comment by jakehockey10** [comment]
@filipesilva Thank you for the feedback!  I'm trying to stay on track while learning all this and wanted to make sure I wasn't straying off the main track too much.

Also, thanks for the suggestion on finding some talks by the material2 team.  Would the best place for looking for these talks be YouTube?  Or is there a site dedicated to posting these talks?

**Comment by filipesilva** [comment]
You can find all the ng-conf talks here: https://www.youtube.com/user/ngconfvideos

This is one of the material talks, from this years' ng-conf: https://www.youtube.com/watch?v=0BikjL858OQ
