### ISSUE TITLE
Tracking: Warnings on console from `npm install`

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#3889]
We should not have warnings on the command line when people create a new project and `npm install`.

**Comment by Brocco** [comment]
Current status of dependencies (as of version 1.0.0-beta.26)

>npm WARN deprecated minimatch (2 causes)
 - karma-remap-istanbul causes a warning of a deprecated version of minimatch
This is caused by an older version of karma-remap-istanbul and by remap-istanbul (a sub-dependency) using an older version of istanbul as well. Updating the CLI project's version of karma-remap-istanbul to v0.4.0 fixes the first dependency issue. To fix the other an update of istanbul within remap-istanbul would be needed.

 - protractor causes a warning of a deprecated version of minimatch
This is caused by jamine's reference to an older version of glob. This has been corrected in jasmine in version 2.5.1 (current version is 2.5.3).
To make this correction the version of jasmine will need bumped in both [protractor](https://github.com/angular/protractor/blob/e68dcf1bfd7f32c59ebd23fa16ca53e1a53f8ddf/package.json#L21) and [jasminewd](https://github.com/angular/jasminewd/blob/96824d4a3801a28501e1286d83dfafa227f0350f/package.json#L18)

>npm WARN prefer global node-gyp
node-sass has node-gyp as a dependency

**Comment by hansl** [comment]
@brocco If we update protractor to 5, would that work?

**Comment by Brocco** [comment]
@hansl unfortunately not, both protractor and jasminewd have their versions of jasmine pinned to v2.4.1, even in release v5.0.0

The good news is that there are no documented breaking changes in jasmine between v2.4.1 and v2.5.3 so the upgrades should be seemless

**Comment by Brocco** [comment]
There is a remaining warning about a package that prefers to be installed globally (node-gyp)

```bash
npm WARN prefer global node-gyp@3.5.0 should be installed with -g
```

This is a dependency of of node-sass.

**Comment by osnoser1** [comment]
#4575 [beta.31] npm WARN at installation in global

**Comment by Brocco** [comment]
At this point the only warning on installation (global or local) is when installing within a project there is a warning that `node-gyp` prefers to be installed globally, this is a dependency of `node-sass`.
