### ISSUE TITLE
Angular-cli witch es6

### ISSUE THREAD

**Issue by andrzejpakula** [angular/angular-cli#3895]
Hi. At the beginning I want to apologize for my bad English. I have a question. Builds advanced applications rest. I use your great angular-cli and I wanted to use the new features of ECMAScript6, for example http://es6-features.org/#GeneratorFunctionDirectUse . My WebStorm showed errors js version. So I set versions of java script on ECMAScript 6. Then also there were errors in the compilation of typescript. So  I set file tsconfig target to ES6, and now everything works as it should, the new function ES6 are supported, and so far I do not have any errors. But I doubt whether it's certainly good to use ES6 and why at this moment is set by default ES5? Can you explain this to me? 

Best Regards

Andrew

**Comment by Meligy** [comment]
Hi @andrzejpakula
I'm afraid proper support for generators needs to come to TypeScript first. There's nothing CLI specific to be expected other than testing the newer version when it comes out, and officially use it by default.

We are talking several months here most likely.

Allow me to explain why, and feel free to ask if there's anything not obvious:

## TypeScript

Angular CLI supports TypeScript only.

TypeScript supports most features of ES6, but not in every target output. It does support generators but only when targeting ES6, not ES5. The support for generators when targetting ES5 is planned but not yet implemented. Ref: https://github.com/Microsoft/TypeScript/issues/3975#issuecomment-266509574

## ES6

You cannot change the output of TypeScript to ES6 unless you only target a browser that fully supports ES6 (latest Chrome maybe?) Because Angular CLI does not apply any further compilation to the output of TypeScript.

## What To Expect

So, most likely you'll need to wait until:

- TypeScript releases a new version that supports generators when targeting ES5
- Angular CLI supports that new TypeScript version
  (At the moment TypeScript latest version is 2.1.x, but Angular itself has an issue with that, which is why Angular CLI only supports TypeScript 2.0.x)

As mentioned above, I'm afraid we are probably talking several months here, and nothing specific for the issue from the CLI side.

Sorry.
