### ISSUE TITLE
linked angular-cli throws an error when running serve. help please

### ISSUE THREAD

**Issue by mkoczorowski** [angular/angular-cli#3947]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OS Serra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

latest

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

cloned cli, linked, trying to use ng serve. Compilation stops at 70% and ContextElementDependency error is thrown. this works fine if I just install cli folrm npm. The problem is when I link it

### The log given by the failure.
> Normally this include a stack trace and some more information.

64% building modules 460/503 modules 43 active ..._modules/inherits/inherits_browser.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (/[....]/node_modules/webpack/lib/Compilation.js:188:20)
    at Compilation.processModuleDependencies (/[....]/node_modules/webpack/lib/Compilation.js:177:7)
    at /[....]/node_modules/webpack/lib/Compilation.js:317:12
    at /[....]/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/[....]/node_modules/webpack/lib/Compilation.js:123:12)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Does that also happen on a project created via `ng new` with the linked master? My bet is that it's something related to your project.

**Comment by mkoczorowski** [comment]
I will try to recreate it using linked cli, thanks for the tip. I'm not sure it will do anything different, since the project was already created using cli, just the npm version, so if I create a new one and copy everything over will end up with the same. Are there any required steps when linking ?
- I have cloned the repo
- ran npm install in there
- ran npm run build

anything missing ?

Thanks for all the help! Great work

**Comment by tristancaron** [comment]
I have the same error, with the same config.

My code was working with the version 21 of angular-cli

**Comment by Equinox** [comment]
@mkoczorowski You may want to ensure you followed this part [here](https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli) correctly.

**Comment by mkoczorowski** [comment]
of course. I forgot last step npm link angular-cli. Thank you @Equinox :D @tristancaron FYI

**Comment by zephyrprime** [comment]
Ok, I had the same problem but the suggested fix didn't work for me.  However, I was able to fix the problem after some random bumbling around.  I'm not sure what the problem was.  However, I don't see why running "npm link @angular/cli" is useful anyway unless you want to development work on angular/cli itself which I am not doing.

I first tried to run 
"npm link @angular/cli".  
Then I tried building again.  
I got the error:
'The "@angular/compiler-cli" package was not properly installed'
I then installed @angular/compiler-cli globally but that installed the 4.0 version.  I downgraded to the 2.4.10 version by running
npm install -g @angular/compiler-cli@2.4.10
I tried to build again but I still got the 'The "@angular/compiler-cli" package was not properly installed' error.
I then deleted the @angular/cli symbolic link in the npm_modules directory and I reinstalled angular.cli locally by running:
npm install --save-dev @angular/cli@1.0.0
For some reason, this fixed my original problem.
