### ISSUE TITLE
`ng help` shows `No help entry for 'serve.run'` and others.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#3994]
While using `1.0.0-beta.25.5`, running `ng help` shows `No help entry for 'serve.run'` and a couple of others in red. These entries should not be listed.

**Comment by CarreraPHP** [comment]
@filipesilva , #4001  & #3982 are 2 different PR for the same issue. in #4001 the issue is resolved using the ignore list and in #3982 the issue is resolved by excluding the '*.run.ts' files in the filter map. 

Is there a way to know whether someone is working on a PR for an issue? I am searching for issues that can be reproduced in macOS Sierra for which i can make a PR but mostly end up find an already submitted one. At last, I comment in the issue referencing the PR that resolves the issue and again go back searching for an new issue. Can u suggest some easy to medium effort issues that can be resolved by new contributors like me.

**Comment by CarreraPHP** [comment]
@hansl merged #3982

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/3982

**Comment by filipesilva** [comment]
Heya @CarreraPHP, I don't have a better way myself than to look at the PR list. A lot of the fixes are driven by users needing something fixed or wanting to help, and it's not coordinated.
