### ISSUE TITLE
Feature: ServiceWorker support in CLI

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#4006]
Requested by @alxhub.

This is non 1.0 blocking but will be tracked in the 1.0.

**Comment by splintercode** [comment]
For reference for anyone who wants to use service workers with the CLI now its not to much work using the sw-precache library. I have a blog post and working demo here. https://coryrylan.com/blog/fast-offline-angular-apps-with-service-workers

**Comment by justingrayston** [comment]
@hansl I notice that this is marked Done in Tracking and I see @alxhub branch here https://github.com/alxhub/angular-cli/tree/sw-support do you have an idea of when this might get a PR? I know you guys are really busy and you are doing a great job, I only ask because I was thinking  of trying to figure out some plugin to help server a service worker. So before I get my hands too dirty, I thought I'd be cheeky and see if we are looking weeks or months here?

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/commit/cb2e418d58149493fd4978909daf87ad8e432cd5

**Comment by justingrayston** [comment]
Awesome, sorry I didn't see it.

**Comment by alexjlockwood** [comment]
I'm having trouble getting this to work... and I feel like it has something to do with the fact that I'm setting `--base-href=/SubDirectory/` when I build. Any reason why the service worker wouldn't work when this argument is set?

**Comment by osnoser1** [comment]
Maybe this will help: [Feature: Route redirection to index.html](https://github.com/angular/mobile-toolkit/tree/master/service-worker/worker#feature-route-redirection-to-indexhtml).
@alexjlockwood

**Comment by alexjlockwood** [comment]
@osnoser1 Thanks for the tip! Are you suggesting I manually update the `ngsw-manifest.json` file after I build?

**Comment by osnoser1** [comment]
For now yes. 😃

**Comment by alxhub** [comment]
@alexjlockwood, create a `ngsw-manifest.json` file with only the routing config specified in your project root. The generated manifest with file hashes will be merged into it at build time.

**Comment by alexjlockwood** [comment]
@alxhub Sorry for being a complete noob here, but do you mean like this?

```
{
  "routing": {
    "index": "/index.html",
    "routes": {
      "/": {
        "prefix": false
      },
      "/ShapeShifter": {
        "prefix": true
      }
    }
  }
}
```

My web app is [here](https://github.com/alexjlockwood/ShapeShifter)... I'm building it using `ng build --prod --base-href=/ShapeShifter/` so that it serves at `https://alexjlockwood.github.io/ShapeShifter`. Not exactly sure what the desired `ngsw-manifest.json` end result is supposed to look like though.

**Comment by alexjlockwood** [comment]
@alxhub Friendly ping. :)

**Comment by alexjlockwood** [comment]
The problem I seem to be having is that the browser is still trying to retrieve the `ngsw-manifest.json` file from `https://alexjlockwood.github.io/ngsw-manifest.json` when it is actually located at `https://alexjlockwood.github.io/ShapeShifter/ngsw-manifest.json`. Is this something that can be changed via the routing config above?

**Comment by jvitor83** [comment]
@alxhub

I think that `--base-href=/SubDirectory/` should be concated to the `ngsw-manifest.json` at routing.index.

Resulting in `/SubDirectory/index.html` to the sw.

**Comment by alexjlockwood** [comment]
Just a quick follow up... I ended up filing #5186 and once that got fixed everything seemed to work fine for me.
