### ISSUE TITLE
Feature Request: Import component information to routing module when --routing flag is passed

### ISSUE THREAD

**Issue by baruchvlz** [angular/angular-cli#4023]
When using `--routing` while generating a module the routing module is missing the component information. 

Another thought is to automatically set a default empty route in the `__name__-routing.module.ts` file.

**Example**
Running `ng g m --routing foo` will generate this routing file:

```typescript

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { FooComponent } from './foo.component';
const routes: Routes = [
  {
    path: '',
    component: FooComponent
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: []
})
export class FooRoutingModule { }

```

**Comment by Brocco** [comment]
There was a discussion a while ago whether using the `--routing` flag would create a component at all. Initially I was against this idea, but it has definitely grown on me and I am leaning that way of removing the component generation from module generation, even though it's now only when you add a routing module.

The reason is control, there are no options to control how the component is generated... name, inline template/style, flat are all unavailable and in my opinion should be a separate command run by the user.

A new issue was created to monitor that discussion #4209

**Comment by Brocco** [comment]
Module generation with `--routing` no longer generates a component.
