### ISSUE TITLE
ng e2e does not start a webserver

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular-cli#4042]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OS X El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.25.5
node: 6.7.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/material: 2.0.0-beta.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Running `ng e2e` fails because the webserver is never started.

### The log given by the failure.
> Normally this include a stack trace and some more information.

```text
[13:20:23] E/protractor - Could not find Angular on page http://localhost:4200/ : retries looking for angular exceeded
```

### Mention any other details that might be useful.

If this is expected behaviour, there should be a way to start a dev server and attach a callback to it so that we manually trigger the integration tests once the dev server is started.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This is intended behaviour, `ng e2e` does not start a server. 

This was chosen because there are multiple ways in which you might want to test your project. For instance, you might need to test the latest build, that was done via `ng build --multiple --flags --and-configs`. You might also want to test the current running `ng e2e`, or even your live site.

My recommendation for running e2e on a CI environment is to add this npm script:
```
"e2e": "ng build --no-progress && concurrently \"lite-server dist/\" \"ng e2e\" --kill-others --success first"
```

This script relies on https://github.com/kimmobrunfeldt/concurrently to coordinate processes and the fact that starting a lightweight webserver is always faster than starting protractor.

You might want to omit `ng build` if you already have a build available in `dist/`.

**Comment by rolandjitsu** [comment]
Thanks for the suggestion :)
