### ISSUE TITLE
new project with scss is failing when using yarn instead of npm

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [angular/angular-cli#4197]
### OS?
> Mac OSX (El Capitan)

### Versions.
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: darwin x64

### Repro steps.
I've set up a new project with the following comments:
```
ng new scssyarn --skip-npm --style=scss
cd scssyarn
yarn
ng serve
```
This results in an error when I start the project. No errors have been given during the creation of the project.

### The log given by the failure.
```
** NG Live Development Server is running on http://localhost:4200. **
Hash: a32b1d809b1a70ef89e7                                                               
Time: 5861ms
chunk    {0} main.bundle.js, main.bundle.map (main) 8.89 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 12.7 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 2.84 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '[local path]/scssyarn/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.getInstalledBinaries ([local path]/scssyarn/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList ([local path]/scssyarn/node_modules/node-sass/lib/errors.js:20:15)
```

### Mention any other details that might be useful.
I've had very similar issues with beta 24. It worked after some tweaks, see https://github.com/angular/angular-cli/issues/3610. The suggestion to link to the latest version did also not help.

**Comment by Meligy** [comment]
I just tested it and it worked for me. I suggest you have yarn 0.19 at least if you don't have it.

But it's probably not yarn. I'm guessing it's node. I don't remember the details on the top of my head, but a few people seem to be having issues with Node 7.

Since odd version numbers of Node are more of experimental versions, that end up as LTS (Long Term Support) versions in the next even number version, I suggest you get the latest Node LTS version (6.x) and see if the problem continues (you'll need to clean up the NPM and yarn files from your user folder manually).

**Comment by tobi-or-not-tobi** [comment]
Thanks for your feedback @Meligy. I was on yarn 0.17. moving to 0.19 did the trick!

**Comment by filipesilva** [comment]
Closing as answered. Thanks @Meligy!
