### ISSUE TITLE
CSS imports do not work for component CSS

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#4285]
In `beta.26`, the following results in a runtime error:
```
// src/app/app.component.css
@import '~bootstrap/scss/bootstrap'
```
```
http://localhost:4200/~bootstrap/scss/bootstrap Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.bundle.js:6292 Unhandled Promise rejection: Failed to load ~bootstrap/scss/bootstrap ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ~bootstrap/scss/bootstrap 
```

For global styles, `css-loader` is what resolves imports currently. Component styles had `css-loader` added in an incorrect way, which resulted in broken CSS (fixed by @clydin in https://github.com/angular/angular-cli/pull/3511).

Using `'exports-loader?module.exports.toString()'` together with `css-loader` fixes this bug, but I know @clydin is currently working in `css-loader` replacement functionality via PostCSS plugins for imports, which also solves the problem so it's better to wait for that solution.

**Comment by rainstormza** [comment]
change file extension to scss it works well

styleUrls: ['./test.scss'],

in my test.scss file I use
@import '../../../assets/admin/css/ionicons.min.css';

**Comment by adam-beck** [comment]
So, if I understand this issue correctly it is so that users can import a style in the `component.ts` file and the styles listed there would be moved to the global scope. The user could still use `styles` and `styleUrls` in `@Component`.

Is that the gist of this? I'm trying to understand myself why `exports-loader` is used. I noticed it after I had run `ng eject`.
