### ISSUE TITLE
ng options / blueprints: factor them out

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#4324]
It would be great if `availableOptions` and blueprints are extracted from the commands.
These constants are then imported in the resp. commands, but are also available for different purposes.

**Comment by catull** [comment]
Accidentally clicked on the "Close and comment" button instead of just moving the mouse away.

**Comment by catull** [comment]
Implemented in https://github.com/angular/angular-cli/pull/4390.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
