### ISSUE TITLE
Discussion: Too many config files in the root folder

### ISSUE THREAD

**Issue by shairez** [angular/angular-cli#443]
@johnpapa raised a concern he got from people who saw how many files the CLI is generating.

So he offered to move the CLI files into an `.angular-cli` folder so at least we'll have a little less noise.

Points raised:

**The good parts**

- The root folder will be a little less messy
- We can set an example for other projects to clean up our dirty dirty root folder :)

**The bad parts**

- People are used to stuff being in the root folder
- Unless we can convince all of the other projects to keep their file in a `config` folder this isn't gonna change soon

We'll love to hear more feedback from the community, so feel free to add your input and vote in favor or not.

**Comment by filipesilva** [comment]
Ah, I had actually misunderstood John's point: if it is just the cli specific files then the only two what would be moved are `angular-cli.json` and `angular-cli-build.js`. This wouldn't present any kind of extra config issue.

All the others are related to external tools.

**Comment by shairez** [comment]
I'll edit the post

**Comment by johnpapa** [comment]
Yes, to be clear I meant just the angular cli specific files go in the `.cli` folder (or whatever it is called)

BTW ... idea came from @spboyer "Beardy"

**Comment by spboyer** [comment]
@filipesilva I would also like to see if `.clang-format` could move as well

**Comment by hansl** [comment]
@johnpapa: There might be a problem with moving `angular-cli-build.js` into a separate folder; people are expected to change it in their project to suit their need. Until we have a compelling story where the build files isn't needed for installing and building third party libraries, pushing it inside a dot-folder might hide it from people who need it.

However, `angular-cli.json` does not need to be visible and hand edited as it's expected people will use `get`/`set` commands to change it (but is still manually editable).

**Comment by hansl** [comment]
So basically my point is that a `.cli` would be relative very empty. Just moving `angular-cli.json` to `.angular-cli.json` (or even `.cli.json`) would probably be fine.

**Comment by d3viant0ne** [comment]
@hansl Couldn't we just go with the best of both worlds. Stick everything in the folder selected and then if the user wants / needs to override you could stick that in the root directory.

Bit more work but imo it's a viable compromise.

**Comment by hansl** [comment]
The user might not see the directory at all on POSIX systems, depending on their editor. So they wouldn't know they're there.

**Comment by d3viant0ne** [comment]
I would think the vast majority of us are well accustomed to dotfiles

**Comment by hansl** [comment]
I know some people will file issues with it, and it's avoidable in a really simple way.

Personally I'd rather see the following:
* `.clang-format` go away until you run your first `ng format`.
* all the karma+protractor configuration go into a `test/` folder.
* `angular-cli-build.js` could go into `config/`.
* `tslint.json` could go into `config/`.

That leaves the following files at the root:
* `.gitignore`
* `.angular-cli.json`
* `typings.json`

Of all of these, the only one that _has_ to live at the root is `.gitignore`. `typings` may go away with TS Next (ultimately will). Angular CLI makes sense in the root because it's what we're going to use to find the project you're in (we find the closest `.angular-cli.json` file).

So really, there's so much to do without even touching the JSON file, I don't know why we're bikeshedding on it.

**Comment by hansl** [comment]
Also, please note that one of my goal with the `ng install` story is to kill the `angular-build-cli.js` file altogether. The content will be split between `angular-cli.json` and addons.

**Comment by d3viant0ne** [comment]
@hansl That sounds intriguing :)

**Comment by filipesilva** [comment]
@hansl don't think it makes much sense to make a `test` folder just to contain two config files. If it's absolutely necessary to do away with them, might as well go into the `config/` folder as well.

Adding `.clang-format` only on the first run of `ng format` also means that until then, the project has the `clang-format` dependency but no configuration. Might as well put it in the config folder and have  all configs on the same place, otherwise users will have to look into several folders (`./`, `./config` and `./test` so far) for config files.

@spboyer I don't think `clang-format` should be moved into a `cli` dir, mostly because it's not a cli thing. Like `tslint`, it's a third party tool. It also represents a point of configuration: if a user wants to auto format his code with some other tool, all he has to do is change the `format` scripts in `package.json` and `ng format` will run that.

**Comment by hansl** [comment]
There's also the `karma-shim.js`, which really we need a way to customize but will not be changed by most people.

3 files in total.  :shrug:

**Comment by filipesilva** [comment]
True, forgot about that one.

**Comment by nfantone** [comment]
I was redirected here from #896.

I cannot agree more with the point of this thread. Have you consider using [custom metadata](http://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid/27232456#27232456) in `package.json`? Particularly, everything in `angular-cli.json` could be moved there.

**Comment by nfantone** [comment]
Also, I gotta say I'm not a big fan of the `ng install` approach. I am of the opinion that tools should be re-used whenever possible and sticking to standard, popular ones should be the way to go. `npm i` should be _all_ that's needed to install a dependency in an Angular 2 project (just like it is in any other javascript project). Couldn't this be solved with a `"postinstall"` npm script?

**Comment by kylecordes** [comment]
I would like to request that a file name starting with "." not be used unless we can be 100% sure there is no reason to look at this file, either to diagnose problems, to fix problems, to understand the mechanism, etc. These hidden files cause undue difficulty particularly when first introducing a new product to developers who operate mostly on a Mac - because they do not see the files in Finder, some of them know to always look in their editor instead while others struggle. There are already enough hurdles to get past to adopt this stack, I think it is good to avoid adding any more than absolutely necessary.

**Comment by nfantone** [comment]
> These hidden files cause undue difficulty particularly when first introducing a new product to developers who operate mostly on a Mac - because they do not see the files in Finder.

I'm going to take a wild guess and say that the vast majority of us here work on a Mac. I'd like to know other experiences, but from my point of view, files starting with `'.'` have _never_ been a issue. Almost all IDEs (or IDEs wannabes) show those files by default. Some even recognize them and add a pretty icon next to the name. 

By now, we are all very well accostumed to files such as:

-`.npmignore`
-`.bashrc`
-`.eslintrc`
-`.gitignore`
-`.gitattributes`
-`.editorconfig`
-`.jshintrc`
-`.jshintignore`
-`.csslintrc`
-`.bowerrc`
-`.travis.yml`
-`.gitlab-ci.yml`

... so I really don't see a problem in adding more one more of those.

**Comment by kylecordes** [comment]
Ah, .bowerrc. This is a great example of an irritating file, when introducing this whole tool stack the people who is not used it before. I never did find a compelling reason to hand out about why someone could put most of their power settings in bower.json, except for just one really important setting (where in the project they keep their web files) had to go in this separate file with a special ("hidden") name. I certainly agree with the sentiment above that most sane IDEs will show these files by default, but is that really a compelling reason to create a new generation of the bower question? To make each new person ponder why some of the settings they want to set are in an ordinary file and some are in a special pseudo-hidden file? Or is the idea here to try to move every configuration file that angular-cli needs to a .name ?

**Comment by nfantone** [comment]
> To make each new person ponder why some of the settings they want to set are in an ordinary file and some are in a special pseudo-hidden file?

Isn't things like that what _define_ a person being _new_ to any given subject in the world? To ponder?

All in all, this is a banal discussion. Personally, I'd vote in favor of dotted filed. This issue is about reducing the number of auto-generated config files, regardless of their name.

**Comment by kylecordes** [comment]
Actually I think there wasn't one important bit I left out before. Regardless of the merits of the dot (actually don't care either way, for most of the reasons you describe), I do feel strongly about the following:

If there is a mix of some settings that must be made in plainly named files, and other settings that must be made in .named files, then there should be a crisp, clearly elucidated reason as to why some settings merit one kind of file and some the other. If there is not a reason to have a difference between two things, then there should not be a difference between the two things - having some comprehensible reason for similarities and differences is at the heart of making a system approachable and learnable.  In the bower example I gave, no one I worked with ever did find any real reason other than "legacy". Let's not make any fresh new "legacy", let's do things for reasons.

**Comment by filipesilva** [comment]
I don't believe this is an issue anymore. With `beta.15`, a typical newly generated project has a fairly spartan set of files:

![image](https://cloud.githubusercontent.com/assets/4172079/18736723/c2390dd0-8081-11e6-8eda-df272fb55c00.png)
