### ISSUE TITLE
Suppress warnings on ng build "Cannot find SourceMap"

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#4460]
I included two external JavaScript files within `angular-cli.json`. Now when running ng build it is showing two warnings `Cannot find SourceMap 'name.js.map': Error: Can't resolve './name.js.map' in  [...]`.

Is it possible to suppress this warnings?

Im already doing `ng build -prod --sourcemap false`

**Comment by spwoodall** [comment]
Sounds similar to this angular2-highcharts [#99](https://github.com/gevgeny/angular2-highcharts/issues/99) issue. Hopefully this helps you with suppressing those pesky warnings.

**Comment by rameshcharykotha** [comment]
same issue is happening and we have lots of third party js files, any update on this?
**ng -v** results

@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3

**Comment by ChrisProlls** [comment]
Same here ! Any idea ?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
