### ISSUE TITLE
br tag is not working data comming from json with br tag

### ISSUE THREAD

**Issue by uyadav0001** [angular/angular-cli#4479]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment]
Hi @uyadav0001 , This issue is not related and would best be suited for: https://github.com/angular/angular 

The issue you have is because you are most likely trying to load your data like:

```
var json = 'Hello </br>World';

Template:
<p>{{ json }}<p>
```

The correct way to do it would be:

```
<p [innerHTML]="json"></p>
```

This is frowned upon though due to the evident security flaws, you can read more about it here:
https://angular.io/docs/ts/latest/guide/security.html#!#xss

An alternative would be to bypass it with bypassSecurityTrustHtml

**Comment by filipesilva** [comment]
Closed as answered.
