### ISSUE TITLE
console has printed "webpack: Compiled successfully." but browser only update css,html, not update js

### ISSUE THREAD

**Issue by xingguangsixian** [angular/angular-cli#4683]
OS 
> windows10

Versions
>ng --version

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 6.9.2
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/compiler-cli: 2.4.6

### Repro steps.
>console has printed "webpack: Compiled successfully." but browser only update css,html, not update js
That's why?

**Comment by Meligy** [comment]
There was a reported issue in beta 28. This was fixed in later beta.

The current version is beta 31. Please note that the package name changed from `angular-cli` to `@angular/cli`. You can find instructions for upgrade [in the README](https://github.com/angular/angular-cli#updating-angular-cli) of this repository, or [in this post](https://www.gurustop.net/blog/2017/02/03/how-to-upgrade-from-angular-cli-beta-28-3-and-lower-to-angularcli/).

**Comment by filipesilva** [comment]
Closing as answered, thanks @Meligy!

**Comment by cooldeepcoding** [comment]
npm version 5.5.1
node version - v8.9.3

I did following steps:

1. Installed node.exe on my windows 7
2. went to a particular folder 
3. ran cmd prompt on that folder 
4. ran npm install 
5. ran npm install angular 
6. ran npm start 

Getting the message on console - webpack compiled successfuly but web page is not launching on browser

![image](https://user-images.githubusercontent.com/19520328/36637394-19203d4c-1a2f-11e8-8421-e939f6761377.png)

**Comment by karthibala** [comment]
Hi 

Try with below commends in your cmd:

Creating new project and starting testserver:
ng new my-app
cd my-app
ng serve --open
