### ISSUE TITLE
reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by Narasimha969** [angular/angular-cli#4684]
I am working on Angular 2.. I have recently ran `npm install`. 

the project is running on angular-cli.
 when I run the command `ng build`. I am getting the below error.

`reflect-metadata shim is required when using class decorators`

Please help.

Here I am attaching my package.json and screenshot.
![image](https://cloud.githubusercontent.com/assets/20059343/22916686/e66b25a8-f2a5-11e6-8355-77f103d7ffe1.png).

[package.txt](https://github.com/angular/angular-cli/files/773241/package.txt)

![image](https://cloud.githubusercontent.com/assets/20059343/22916813/f4fc97fe-f2a6-11e6-88d1-304a1f7ec39c.png)

`{
  "name": "Sample Project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "awesome-typescript-loader": "2.2.1",
    "bootstrap": "4.0.0-alpha.4",
    "core-js": "^2.4.0",
    "rxjs": "^5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "typescript": "2.0.0",
    "webpack": "2.1.0-beta.21",
    "zone.js": "0.6.12",
    "loader-utils": "^0.2.16"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.17",
    "awesome-typescript-loader": "^2.2.1",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.0",
    "webpack": "2.1.0-beta.21"
  }
}
`

![image](https://cloud.githubusercontent.com/assets/20059343/22916797/dbff594e-f2a6-11e6-8797-20b42eedd508.png)

**Comment by clydin** [comment]
You appear to be using a fairly old version of the CLI. Please try upgrading to the latest version which at this time is 1.0.0-beta.31.  Please also note that the name of the package has changed to `@angular/cli`.

**Comment by Narasimha969** [comment]
@clydin  I have tried with latest version of `@angular/cli`. 

Its not supporting the `@angular/core` which I have provided in package json.  

After installing the `@angular/core@latest` there are many more errors such as `directives` `pipes` issues..

**Comment by Meligy** [comment]
There are quite a few very old dependencies in that file. All Angular packages are from RC, the router is a version that has been rewritten 2 times since, RXJS is still beta etc.

The CLI will not support those versions or troubleshoot them I'm afraid.

My advice to you is to create a new project using the latest version of the CLI then create a new project with it, and start migrating your files to the new project. I expect it wont be an easy job because Angular must have changed a fair bit since that ancient version. but I'm afraid this is the only way to get Angular support, as RCs are not supported after Angular final was released, and the CLI itself is now using Angular 2.3 by default.

I know you said you upgraded the CLI, but I suggest you double check your installation (quite a few people thought it went well when it didn't). The current version is beta 31. Please note that the package name changed from `angular-cli` to `@angular/cli`. You can find instructions for upgrade [in the README](https://github.com/angular/angular-cli#updating-angular-cli) of this repository, or [in this post](https://www.gurustop.net/blog/2017/02/03/how-to-upgrade-from-angular-cli-beta-28-3-and-lower-to-angularcli/). Re-do the upgrade just to be safe.

Good luck.

**Comment by Narasimha969** [comment]
It was working till yesterday. 

I would like know the reason for the issue. 

Thanks in advance

**Comment by Luftzig** [comment]
@Narasimha969 , Have you tried using a later version of the CLI? Does the problem still happens? If not, did you have trouble updating to the latest version of angular-cli?
#goodnessSquad

**Comment by Narasimha969** [comment]
@Meligy Thanks, Updated all node modules. Working as usual.
