### ISSUE TITLE
Angular 2 application errors when run on IE-9

### ISSUE THREAD

**Issue by nvrnagasai** [angular/angular-cli#4772]
> Unable to get the data from HTTP service, throwing timeout error

### OS?
> Windows 10

### Versions.
>angular-cli: 1.0.0-beta.24
node: 6.9.4
os: win32 x64
@angular/common: 2.4.2
@angular/compiler: 2.4.2
@angular/core: 2.4.2
@angular/forms: 2.4.2
@angular/http: 2.4.2
@angular/platform-browser: 2.4.2
@angular/platform-browser-dynamic: 2.4.2
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2

Used jQuery and Semantic-UI

These are the console errors

![ie9_issue](https://cloud.githubusercontent.com/assets/13963219/23060966/f167815e-f525-11e6-88dc-af4c507deb3c.png)

vendor.bundle.js (86613,25) error line is below code screenshot
![vendor_bundle_issue_1](https://cloud.githubusercontent.com/assets/13963219/23060965/f1651b94-f525-11e6-91b4-01ac26bf3771.png)

vendor.bundle.js (31130,13) error line is below code screenshot
![vendor_bundle_issue_2](https://cloud.githubusercontent.com/assets/13963219/23060964/f164d0bc-f525-11e6-983d-6d4d81e9e30d.png)

> ---------------------------------------------------------------

**Comment by filipesilva** [comment]
Are you sure you're using the necessary polyfills listed in https://angular.io/docs/ts/latest/guide/browser-support.html for IE9? There's a few specifically for `Http`.

**Comment by nvrnagasai** [comment]
I have included these apart from jQuery & semantic

![image](https://cloud.githubusercontent.com/assets/13963219/23063719/f4567e22-f531-11e6-84c0-62c39ff2640b.png)

**Comment by zingzinco** [comment]
Try changing the core.js from default to the library: https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/library.min.js

Worked for me.

**Comment by mattdistefano** [comment]
Is this happening just when running off the webpack dev server, or off a real HTTP server?

I had this issue as well but am pretty sure it was actually in one of the webpack dev server's deps (the websocket library, I believe).

**Comment by nvrnagasai** [comment]
Yes, Thanks a lot, actually it was happening when running through webpack dev server, I have used xampp and tested, it was working fine without any errors, 
is there any working fix for dev server too?

**Comment by mattdistefano** [comment]
No, I ended up just using another http server for the little IE9-specific work I needed to do. If I get a chance, I'll try to log an issue with webpack, though. Also would be nice if the CLI maintainers would take a look into this since nominally the CLI should support IE9.

Also - you may be aware of this already, but if not - I don't believe Angular 2.x supports IE9s quirky handling of backspace/deletes, so if you have text inputs in your app, you'll want to polyfill/work around that. See https://github.com/angular/angular/issues/7557

**Comment by nvrnagasai** [comment]
roger that.. 
Thank you

**Comment by Meligy** [comment]
If the problem is with web sockets as suggested above, I expect turning off live reload to workaround it, just a random guess.

**Comment by Meligy** [comment]
So, maybe try `ng serve --live-reload=false`

**Comment by nvrnagasai** [comment]
tried, no luck.
In other HTTP servers like tomcat, xampp its working, no issues with IE9+
webpack dev server have some issues when app is launched on IE9 even after polyfills inclusion.

is there any way to launch angular-cli generated app through other server without build and using dist folder files.

**Comment by mattdistefano** [comment]
You can run the build in watch mode (I think `ng build -w` but `ng help` should say) and have your HTTP server serve from the dist folder. With browsersync or lite-server I think you should still get live reload.

**Comment by filipesilva** [comment]
So this seems like a webpack-dev-server problem, and not the app itself.

I tried looking for what browsers webpack-dev-server supports but it seems like there's isn't a list. https://github.com/webpack/webpack-dev-server/issues/767 kinda seems like it's saying ie8/ie9 aren't supported.

@mattdistefano's advise is solid though: `ng build --watch` will rebuild your app on every change and output the generated bundle onto `dist/`.

**Comment by filipesilva** [comment]
I can verify that the following polyfills are enough to run a brand new **built** application on a server other than `ng server`:

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
```

I can also verify that using `ng serve` a new error appears:
![image](https://cloud.githubusercontent.com/assets/4172079/24074849/8a7899a2-0c08-11e7-9843-e5b631596db0.png)

This must be related to the webpack dev server itself. It seems live reloading still works though, and the app still runs.

I tried adding `<script src="https://unpkg.com/core-js/client/shim.min.js"></script>` to have every conceivable polyfill but it didn't make any difference.

So atm I think that error is inconvenient when testing on IE9 but it's not problematic.

If your app just does not run in IE9 it's probably not because of the `SCRIPT445` error since it runs the app fine on a brand new app. You're probably missing some other polyfills related to your application.

Meanwhile for users that need to test applications in IE9 and are worried about the dev server related errors, please follow these steps:

- run `npm install --save-dev concurrently lite-server`
- add this npm script: 
```
"scripts": {
 // ...
 "serve-ie9": "concurrently \"ng build --watch --no-progress\" \"lite-server --baseDir=dist\""
```
- run `npm run serve-ie9`


I'll leave the issue open for now, maybe someone has more insight into this. Users shouldn't add a polyfill just for the dev server though.

**Comment by sandeepperkariappdev** [comment]
I see  "ERROR TypeError: Object doesn't support this action" error when working on IE with Ionic 3.5.0, Angular Core 4.1.3 versions. I tried to debug to find out the IE is not supporting the URL class from typescript. I think we a need to compile the typescript code to work in IE.

**Comment by sandeepperkariappdev** [comment]
after replacing the URL class with string, my app is working fine in the IE edge browser, I think compiling the typescript to es3(lower version of javascript to support lower versions of browsers) version may work.

```![image](https://user-images.githubusercontent.com/15526203/28441248-d83818fe-6d77-11e7-98aa-1bd7358c4dac.png)```

**Comment by clydin** [comment]
CLI 1.0 prerelease versions are no longer supported.  If this error still occurs on the latest version (6.1.4 currently).  Please open a new issue describing the problem.
