### ISSUE TITLE
ng e2e -s or -w doesn't make any difference

### ISSUE THREAD

**Issue by ctrl-brk** [angular/angular-cli#4855]
What's the purpose of these flags? For me they don't do anything.
`ng e2e` always runs tests once and exits. Next time you have to rebuild everything again which takes forever. How can I make it to behave like `ng serve`, so it sits there and watches for changes?

**Comment by ctrl-brk** [comment]
Still don't see a purpose for them in rc.1
How do I use it?

**Comment by filipesilva** [comment]
The `--serve` flag controls wether or not `ng e2e` will also serve your project. The default is true.

You can do `ng e2e --no-serve` to not serve. That's useful if you want use e2e on an already running server.

The `--watch` flag is passed on to the server with `--serve` is true. It defaults to false on `ng e2e` because it would be bad for live reload to kick in and reset your test while you're running `ng e2e`.

**Comment by ctrl-brk** [comment]
That's not a behavior I see. For me ng e2e runs just one and exits no matter what parameters I use.

**Comment by jculverwell** [comment]
`ng e2e --no-serve` is working fine for me

**Comment by filipesilva** [comment]
@ctrl-brk the server (same as `ng serve`) is what makes use of the `--watch` flag, the e2e test itself does not. An example of this behaviour would be that the browser auto reloads in the middle of an e2e test because you made a code change. This would break the e2e test.

I think the functionality you are expecting is the one requested in https://github.com/angular/angular-cli/issues/2861.
