### ISSUE TITLE
loaderUtils.parseQuery() : if there is a # in dir name > webpack : failed to compile (macos)

### ISSUE THREAD

**Issue by s-f-a-g** [angular/angular-cli#4872]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (El Capitan)

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.4.0
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/flex-layout: 2.0.0-beta.5
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.7

### Repro steps.
You can do it with angular-cli.
cd #FOLDER 
ng new project-with-diese
cd project-with-diese
ng serve

### The log given by the failure.
> [...] script-loader/addScript.js(node:95633) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
[...] ERROR in Could not resolve "/Users/me/" from "/Users/me/". 
Last line : "webpack: Failed to compile."

### Mention any other details that might be useful.
related to #4869

**Comment by s-f-a-g** [comment]
Just to mention that the folder with # is my root folder for sources for years now... 
#PROJECTS/project-1
#PROJECTS/project-2
etc, etc...
and the error is very new.

**Comment by filipesilva** [comment]
Hm. Well this sucks. We'll see what we can do.

**Comment by Nandan108** [comment]
Similar error... or rather warning, in my case.
### OS:
Ubuntu
### Version:
@angular/cli: 1.0.2
node: 7.7.3
os: linux x64
@angular/animations: 4.1.1
@angular/cli: 1.0.2
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/compiler-cli: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/platform-server: 4.1.1
@angular/router: 4.1.1

I have no # in my path, yet a very similar warning is emitted upon build (in any mode, including -aot and/or -prod):
```
10% building modules 3/4 modules 1 active
.../modules/catalogue/src/style/app.scss(node:26741) DeprecationWarning:
loaderUtils.parseQuery() received a non-string value which can be problematic,
see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```
Could this be caused by the fact that my node_modules/ is behind a symlink?
The build finishes correctly regardless.

**Comment by mgechev** [comment]
Can you still reproduce this issue?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
