### ISSUE TITLE
@ngtools/webpack: Cannot use custom NgModuleFactoryLoader with dynamic require

### ISSUE THREAD

**Issue by sis0k0** [angular/angular-cli#4884]
Currently, the `@ngtools/webpack` plugin adds lazy routes to the context module only if you are using the built-in `SystemJsModuleFactoryLoader`. If you provide a custom factory loader, the require statement will be resolved with `webpackEmptyContext`, which leads to the following error when trying to require the module:
```
Cannot find module `RandomModuleName`.
```

 This happens when using `@ngtools/webpack` version 1.2.5 and above. The problem's caused by this [check](https://github.com/angular/angular-cli/blob/master/packages/@ngtools/webpack/src/plugin.ts#L272-L275), which respects code only from `@angular/../linker`.

Here's a simple [repo](https://github.com/sis0k0/ngtools-custom-module-loader) with reproduction of the problem.

**Comment by clydin** [comment]
The plugin was designed to work in concert with the built-in loader.  As such, a fully custom loader would need to take full responsibility for loading the lazy routes.  This would most likely be the case anyway if the need for a custom loader arose.

Could you describe your use case further?

**Comment by sis0k0** [comment]
It's not a loader in the terms of webpack. It's a `NgModuleFactoryLoader` with custom logic for lazy loading modules. The provided repo should clarify that.

We are using such a [loader](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-module-factory-loader.ts) in `nativescript-angular`. However, since the `@ngtools/webpack` plugin only accepts calls from the built-in module loader, applications using `NSModuleFactoryLoader` can't be webpacked.

**Comment by clydin** [comment]
Looking at the loader, it appears that the JIT load and compile path is the only area with modifications.  If that is the case, I would suggest delegating to the built in loader instead of replicating the existing logic for the AOT case.  This should have the dual advantages of reducing the maintenance burden on your custom loader as well as aligning the loader with future AOT module loading changes.

In regards to the AotPlugin, supporting additional use cases and adding greater extensibility is currently in the planning stages; however, the current development focus is on the 1.0 release of the CLI.

**Comment by sis0k0** [comment]
Makes much more sense to reuse the built-in loader logic. Thank you!
