### ISSUE TITLE
Build: ng prod build bundle size is larger than ng build  

### ISSUE THREAD

**Issue by ashwin-sureshkumar** [angular/angular-cli#4896]
### OS

Mac OSX - Sierra

### Versions.
```
@angular/cli: 1.0.0-beta.32.3
node: 6.9.4
```

### Repro steps.
This is the repo for the code : https://github.com/ashwin-sureshkumar/gmail-clone-for-blog
It is a very simple gmail clone for purpose of explaining angular concepts. 

### ng build
```
gmail-clone$ ng build
Hash: bf6abf3b965e06908e7d
Time: 10887ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 153 kB {4} [initial] [rendered]
chunk    {1} **main.bundle.js, main.bundle.js.map (main) 133 kB** {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 31.3 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.52 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
```

### ng build --prod --aot
```
gmail-clone r$ ng build --prod --aot
Hash: b2cd2a202a280466e874
Time: 24812ms
chunk    {0} **main.005c2ffc467f19c9340f.bundle.js (main) 700 kB** {3} [initial] [rendered]
chunk    {1} polyfills.836e3aece0e7149ec524.bundle.js (polyfills) 153 kB {4} [initial] [rendered]
chunk    {2} styles.37c59cb6f5e610c45cfc.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.3e14e30aaca91e4984d3.bundle.js (vendor) 2.31 MB [initial] [rendered]
chunk    {4} inline.08d5e9d4a1623033a7ec.bundle.js (inline) 0 bytes [entry] [rendered]

```

**Comment by delasteve** [comment]
AoT compilation will create the necessary `ngfactory`s and compiled templates, amongst other things. These can be larger than your original file due to complexity moving away from the Angular Compiler, `ngc`, and into your component and new `*.ngfactory.ts` file. 

The CLI bundles all of the artifacts generated from the compilation and places that in the `main` bundle. AoT also removes the need for the `ngc` which is why you notice the over 1MB drop in the `vendor` bundle.

More info on AoT can be found here:
http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/

**Comment by filipesilva** [comment]
@delasteve's answer is spot on 👍 

The only thing I'd add is that your app will *always* run faster since templates are not being compiled in the browser as well.

**Comment by ashwin-sureshkumar** [comment]
Thanks for the explanation @delasteve and @filipesilva. Appreciate it!
