### ISSUE TITLE
Names must contain a dash either include a dash or multiCase name

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#507]
I am using the latest angular-cli. The route generation apparently have changed recently. But the new method does not appear to be a good convention. I just wanted to check if this is a bug or intentionally done.
Is there a way I can generate the older structure of list and detail components?

Also the route parameter now expects something with a dash in it? but the documentation is updated about this.

`$ ng generate route user
installing route
installing component
Names must contain a dash either include a dash or multiCase name. (i.e. multiCase -> multi-case)
`

**Comment by Brocco** [comment]
This was intentionally done.

In order to register and use custom tag names they must contain a dash. The first step to supporting this is to disallow creation of such components (routes are just components with more to them). We are considering other alternatives to allow simpler names that would get prefixed or suffixed with a specified abbreviation. But for now in order to be in compliance with the HTML 5 spec, we are disallowing the creation.

I hope this clears this up for you, let me/us know if you have any questions.

**Comment by mmrath** [comment]
Thanks @Brocco 

I think even the previous one did not create components with dash. As per the documentation the following should work

`ng generate route hero`
 
In fact that is what I would like to have, with in the +hero folder hero-detail and hero-list components.

**Comment by mmrath** [comment]
Looks like this is fixed in the latest master.

**Comment by gravity-addiction** [comment]
Whenever I create a simple component name, it gives me this error. I read that it requires multicase to be HTML5 compliant.

I create a component named hero
```
ng g component heroMaster
```
The component is named HeroMasterComponent .. to me you are suffixing every component name with Multicase, so ng g component hero should really be HeroComponent, therefore being compliant?

Thanks.

**Comment by Brocco** [comment]
@gravity-addiction that is the name of the component class the kabeb-case issue is in regards to the `selector` property of the `@Component` annotation.

As @mmrath mentioned this has been addressed in the master branch and will be part of the next release of the CLI...

The fix is that that each app/project will have a determined prefix associated with each selector (default value of `app` but overridable). This prefix will be applied to every generated component so if you were to do `ng generate component hero` the selector will be `app-hero`.

**Comment by gravity-addiction** [comment]
@Brocco Ok. At this point i'm done using the CLI.. it's become overly complicated. nothing makes sense anymore.

**Comment by Brocco** [comment]
@gravity-addiction I'm sorry to hear that, things are starting to settle down after a lot of ups and downs. The documentation and guides are coming soon... hopefully you reconsider. Either way, thank you for your feedback.

**Comment by gravity-addiction** [comment]
I'm good with the error message, i understand the reason. The issue I have is that you are adding in stuff that i did not specify. I really don't want every component prefixed with app- (or any other univerisal string) .. Let me prefix or suffix however I want to, individually per component.
