### ISSUE TITLE
Lazy loading modules

### ISSUE THREAD

**Issue by zwolej** [angular/angular-cli#5141]
What is approach for implementing lazy loaded modules in fresh angular cli 

```
"@angular/cli": "1.0.0-beta.32.3",
"@angular/*******": "^2.4.0",// all angular modules version
```

I found out some tutorials to use in routings some specific syntax:

` { path: "product", loadChildren: "app/product/product.module#ProductModule"  }`

But before that  I wanted to compare it with some statistics. So I started from opening dev tools(npm run start) on my one of main pages and it loads with

`46 requests ~7.6mb  ~4seconds. //vendor.bundle.js over 5.9mb`

It's a bit bad result. I'am trying to fix it with those lazy modules, but what is wird i removed like 70% of my code from project. From that:

```
{
    path: '',
    component: AppTemplateComponent,
    resolve: {
      cms: AppResolver
    },
    children: [
      ...PensionRoutes,
      ...ContactRoutes,
      ...InboxRoutes,
      ...CouponsRoutes,
      ...InformationRoutes,
      ...ErrorRoutes
    ]
  },
```

To

```
  {
    path: '',
    component: AppTemplateComponent,
    resolve: {
      cms: AppResolver
    },
    children: [
      ...PensionRoutes
    ]
  },
```

I removed also corresponding folders - each routing was module in custom folder. So after deleting those folders I lost like 70% of application but it still loads in almost same time...

`46 requests ~7mb  ~4seconds.  //vendor.bundle.js over 5,6mb  overall less only 0,6mb`

So I supose lazy modules won't help. Maybe npm run start are not proper command? Only prod flag should be tested or so ? I load all external libs in shared module that is part of every module, maybe thats the problem of big vendor.bundle.js?

**Comment by Meligy** [comment]
You might want to change the routes to something like:

```
  {
    path: '',
    component: AppTemplateComponent,
    resolve: {
      cms: AppResolver
    },
    children: [
      {
        path: 'pensions',
        // You can use `./` or `app/`
        loadChildren: './pensions/pentions.module#PensionsModule'
      }
    ]
  },
```

Which is to take advantage of lazy loading.

While your routes get imported in the `PensionsModule` itself.

**Comment by mattdistefano** [comment]
Your vendor bundle is angular and assorted other dependencies, so lazy-loading won't shrink it much (if at all). If you do a prod build, how big are your JS bundles?

**Comment by delasteve** [comment]
@zwolej, as @mattdistefano mentions, the `vendor.sha-hash.bundle.js` file is all your library code. Lazy loading will create separate bundles in the form `0.sha-hash.bundle.js`, where `0` is the first lazy loaded bundle created and increasing for each bundle created.

You will notice fluctuation in AoT compiled `vendor.bundle.js` and JIT compiled `vendor.bundle.js` if your code is able to be compiled with AoT. AoT allows the compiler not to be loaded in the vendor bundle. In a base CLI project, the difference between `ng build` and `ng build --prod` (which has `--aot` enabled by default) is around 1mb.

Another caveat you will notice with AoT is that your `main.bundle.js` and lazy loaded bundles will increase in size vs the JIT bundle sizes. This is due to the AoT compiler loading more code (`NgFactory`s) in the bundles. The total size of all your AoT code should be smaller than your JIT code.

Hope this helps.
