### ISSUE TITLE
barrel is not exporting shared folder

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#515]
*BUG* When I created  `… app/+dashboard/shared` folder and then ran `ng g component foo`, the barrel in `… app/+dashboard/index.ts` does not import from `shared` and I think it should be (or else it wont find it)

HANS -  It'd basically be `export * from 'shared'` inside the dashboard/index.ts

PAPA - yes, exactly Hans

cc @Brocco @hansl

**Comment by Brocco** [comment]
@johnpapa I tried implementing this but it will not work up front because there is nothing exported by default from `shared/index.ts` so this will throw an exception ([see here in the CI log](https://travis-ci.org/angular/angular-cli/jobs/125675978#L1481))

This will need to be looked at later as a way to add this re-export once something has been added to the `shared/index.ts` barrel

**Comment by johnpapa** [comment]
i think this will be important if we want to get to the point where we can generate a working app out of the box.

this can wait, but please lets keep it open

**Comment by Brocco** [comment]
Managing barrels is no longer part of the CLI, closing.
