### ISSUE TITLE
[Feature Request] Assets should be copied before compilation starts

### ISSUE THREAD

**Issue by FabienDehopre** [angular/angular-cli#5242]
Assets defined in .angular-cli.json should be copied before the compilation starts.

Example of assets defined in .angular-cli.json:
```json
"assets": [
        { "glob": "**/*", "input": "./assets/", "output": "./assets/" },
        { "glob": "favicon.ico", "input": "./", "output": "./" },
        { "glob": "**/*", "input": "../node_modules/font-awesome/fonts/", "output": "./assets/fonts/" },
        { "glob": "**/*", "input": "../node_modules/simple-line-icons/fonts/", "output": "./assets/fonts/" },
        { "glob": "**/*", "input": "../node_modules/flag-icon-css/flags/", "output": "./assets/images/flags/" }
      ]
```

Example of styles defined in scss:
```scss
$fa-font-path: "./assets/fonts";
$simple-line-font-path: "./assets/fonts";
$flag-icon-css-path: "./assets/images/flags";

@import "~bootstrap-sass/assets/stylesheets/bootstrap-sprockets";
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
@import "~font-awesome/scss/font-awesome";
@import "~simple-line-icons/scss/simple-line-icons";
@import "~flag-icon-css/sass/flag-icon";
```

Running `ng serve` or `ng build` will both produce compilation error indicating that assets are not found.
On the other hand, if I set the assets paths (in styles.scss) to point to the `node_modules` of their respective package, no error is produced but all fonts, images, etc. are copied to the root of the website (which is not really clean).

I hope to have been clear enough in my description of the feature request.

**Comment by filipesilva** [comment]
The 'right' way to do this with the CLI actually is adding the paths to node_modules.

This is because we resolve all urls and imports in css/sass/etc, so those need to be pointing to a real destination at build time, whereas assets are build artifacts. They can't really be there before the compilation starts and even if they were, you'd still get the loads of files at the dist root.

The reason we get that massive amount of files is because the build system scoops them up, fingersprints them and outputs them at dist. I agree that this is unsightly, but don't really have an alternative. They could maybe go in a folder or something, but it's more of a cosmetic thing overall.

When you do a prod build all the files that were included via urls will also receive an hash for caching.
