### ISSUE TITLE
ng g route throws multicase error

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular-cli#539]
Hi there,

So running 0.0.34. When I run `ng g route subject` to create a new route I get the following error:

```
installing route
installing component
Names must contain a dash either include a dash or multiCase name. (i.e. multiCase -> multi-case)
```

Previous versions didn't do this.

Versions:
OSX El Capitan
angular-cli: 0.0.34
node: 4.2.6
os: darwin x64

**Comment by Brocco** [comment]
This was new and is a temporary implementation... the HTML 5 spec states that custom DOM elements must contain a dash to be valid and since `subject` would not kebab-case to have a dash it is considered invalid.

There is a fix to this to allow specification of a default prefix for selectors which would satisfy the dash requirement. That will be part of the next release of the CLI.
