### ISSUE TITLE
Current and long term problem with extending tsconfig.json

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#5447]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report

### Versions.
`@angular/cli` 1.0.0-rc.2

### Repro steps.

- install a project with the cli
- add `"plugins": [{ "name": "@angular/language-service" }]` in `/tsconfig.json`
- run `ng e2e`

### The log given by the failure.
`TSError: ⨯ Unable to compile TypeScript Unknown compiler option 'plugins'. (5023)`

### Desired functionality.
Currently, the CLI uses different tsconfig for dev (`/tsconfig.json`), build (`/src/tsconfig.app.json` or internal ?), tests (`/src/tsconfig.spec.json`)... And for factoring, it extends the others from the dev one.

Problem : Angular is still in TS 2.1 but VS Code has moved to TS 2.2, which allow direct use of Angular language service via `"plugins": [{ "name": "@angular/language-service" }]` in tsconfig `compilerOptions`. But as it's a new option, it breaks tests or build or other which use TS 2.1.

It is a problem that will come again in the future, with each new TypeScript option.

I see 2 possible solutions : 
- do NOT extend tsconfigs ;
- create a new tsconfig in root (`/tsconfig.root.json` for example), mentioned as untouchable in docs, and extend all other tsconfigs from it, including the dev one (which must remains `/tsconfig.json`, as it is what is used by editors).

I can take care of the PR, but I want to know first what's the best solution, and for solution 2, what exact name to use for the new tsconfig.

**Comment by clydin** [comment]
It is recommended to configure vscode to use the project's typescript package rather than the built-in one.
You should also be able to use 2.2 within the project if desired.

**Comment by cyrilletuzi** [comment]
I use the VS Code version of TypeScript. The problem is not TypeScript itself, it's the `tsconfig.json`, as explained in details.

**Comment by filipesilva** [comment]
I'm with @clydin on this one, but think it warrants some discussion.

@cyrilletuzi essentially you are saying that you want your *editor* to use a different TS version than your *app*. You want to do it because newer typescript versions have editor functionality that is not available on older ones.

I think the right solution here is to update your project wholesale to the right typescript version.

Angular version 2.0 is stuck on TS2.0, but version 4.0 works on TS2.2. It is true that new 4.0 projects point directly at 2.1 though. It's not a hard restriction though. Maybe we should update that.

As far as long term implications, I still believe it is better to have a consistent TS version used by project and editor. Local plugins will conceivably have dependencies that you need to satisfy via your node modules so it doesn't make a lot of sense to have packages there that need a different TS than installed in the project.

**Comment by filipesilva** [comment]
Related: https://github.com/angular/angular-cli/issues/5497

**Comment by filipesilva** [comment]
Closing as there hasn't been any more discussion on this topic.
