### ISSUE TITLE
Where to set the global variable

### ISSUE THREAD

**Issue by 392475992** [angular/angular-cli#5462]
I want to configure a global variable, because I want to 'ng build - env/prod use different global variables to point to my server

**Comment by deebloo** [comment]
I am not sure I totally understand your queation. Your environment files should have different configs. How you co figure globals is up to you

**Comment by 392475992** [comment]
I want to 'dev' and 'prod' set an environment variables, and then I can access the global variables

**Comment by Meligy** [comment]
It's still not obvious what you want.

If you just want to set a global variable. You can set `window.anythingYouWant` from any file. You might do it in `main.ts` for example.

You shouldn't need this in most cases, because you can use the `environments` feature instead, and just import that in other files that need values in there.

If you want OS or process environment variables from Node, etc., this is currently not supported, the environment files are purely client side like the rest of the app files. You might want to have some build step that rewrites the `environment.ts` or `environment.prod.ts` file with what you want on your build server.

**Comment by faresayyad** [comment]
@Meligy  Could you please give an example of how to define window.anythingYouWant  to be global?
