### ISSUE TITLE
Question:  use Bootstrap 4, navbar toggle does not work following directions in Wiki

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#5463]
### Bug Report or Feature Request (mark with an `x`)
- [ X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

@angular/cli: 1.0.0-rc.2
node: 7.7.3
os: win32 x64
@angular/common: 4.0.0-rc.3
@angular/compiler: 4.0.0-rc.3
@angular/core: 4.0.0-rc.3
@angular/forms: 4.0.0-rc.3
@angular/http: 4.0.0-rc.3
@angular/platform-browser: 4.0.0-rc.3
@angular/platform-browser-dynamic: 4.0.0-rc.3
@angular/router: 4.0.0-rc.3
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 4.0.0-rc.3

### Repro steps.

I am using bootstrap 4 alpha 6, with Sass

I tried to follow the directions from this https://github.com/angular/angular-cli/wiki/stories-include-bootstrap, but when I follow the http://v4-alpha.getbootstrap.com/components/navbar/ first example, the toggle button does not work.  

My understanding is using jQuery with angualr is not recommended.  

Is there a way to get this to work ? 

### Desired functionality.

Like to use Bootstrap 4 with Sass directly in angular 2 and get it's toggle functionality to work.

**Comment by delasteve** [comment]
Your understanding is mostly correct. Mixing Angular and jQuery are generally frowned upon, only because Angular can do most things you need to do in jQuery. This doesn't mean you can't include it in your project. Bootstrap's JS file depends both jQuery and Tether. In this case, including jQuery is fine.

There is currently a PR out there (https://github.com/angular/angular-cli/pull/5248) that will update the doc as soon as a few things are sorted out with the PR author.

This should get you going:
https://github.com/GoNode5/angular-cli/blob/9c264178d2c9a8dc3373648ccd84d5944ca589fc/docs/documentation/stories/include-bootstrap.md#adding-full-bootstrap-component-js-support

**Comment by clydin** [comment]
There are two angular options:
https://ng-bootstrap.github.io
https://github.com/valor-software/ng2-bootstrap

**Comment by daBishMan** [comment]
@delasteve thank you so much for your prompt reply.  This got me going. Again many thanks.

**Comment by Malikhaseebtahir** [comment]
@delasteve thanks a lot.
