### ISSUE TITLE
Investigate Ultimate Angular Aot

### ISSUE THREAD

**Issue by hccampos** [angular/angular-cli#5551]
Have you guys looked into https://github.com/UltimateAngular/aot-loader ? It looks pretty interesting and seems to be very fast. There might be some ideas to take from it. Or even integrate it in the CLI, although I am not sure about the differences between it and the CLI's webpack tool.

**Comment by filipesilva** [comment]
There was a conversation about it a few days ago, but I haven't looked into it myself.

**Comment by hansl** [comment]
We looked into it. Todd is using the same kind of integration with the Compiler we were doing at first, but it turns out that it's not a good long-term solution. We had a problem with the Compiler in 2.3 where the private APIs changed, so we decided to go for a different approach.

There are also concerns about dependencies between components of the same modules that are not reflected in the require/import dependency graph, so there could be errors when rebuilding where some files who should be rebuilt aren't.

All in all, we decided to go the route we are right now, and since we're part of the core Angular team we will work towards making a watch mode for the Compiler that is better and faster, rather than try to solve the problem from the webpack side.

Cheers!
