### ISSUE TITLE
Need to get out of beta, stop changing this version, nail it down

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular-cli#5559]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: darwin x64

### Repro steps.

Us ng build and one day it will mysteriously fail, putting your development and all of your developers out of business: unable to run a simple build. 

### Mention any other details that might be useful.

You really need to release this as-is, nail it down and stop changing it (the released version).  This way you are free to break the build tool, and we are free to roll-back to a working build tool and continue.

**Comment by delasteve** [comment]
The CLI is currently are out of beta. `rc.4` was just released last night. In each of the `rc` releases, there has been a complete feature freeze and only bug fixes are being let through. You should be able to upgrade to the `rc` and nothing should change going forward until after `1.0` is released.

To upgrade to the latest CLI, do the following (since there was a name change from `28.3` to `rc.0`)

```
npm uninstall -g angular-cli
npm uninstall --save-dev angular-cli
npm install -g @angular/cli
npm install --save-dev @angular/cli
```

There may be some other configuration you will need to do as far as your `angular-cli.json` file and `tsconfig.json` file is concerned. For example, the CLI recently broke up the `tsconfig.json` into 4 files, a main `tsconfig.json` at the root of the project, `tsconfig.app.json`, `tsconfig.spec.json`, and `tsconfig.e2e.json`.

I hope this helps!

**Comment by montella1507** [comment]
Well yeah.. We had the same problems..

https://github.com/angular/angular-cli/issues/5554
But i will try what @delasteve  suggests and i will hope it wont be broken after several days again. I am sure guys are doing good work and it may be stable after rc.0. 

I am going to migrate our porjects to RC.0 because atm we have .map is not a function in production builds.  (only with -prod) so maybe something with treeshaking idk.

**Comment by filipesilva** [comment]
We're pretty close to 1.0 final actually. Sorry it took a while, but trust me when I say that we don't do releases for fun. I think pretty much every release has had a big bug fix that was affecting a lot of people.
