### ISSUE TITLE
Bump npm package named @angular/cli from Version v1.0.0 to v4.0.0

### ISSUE THREAD

**Issue by brookhutchinson** [angular/angular-cli#5629]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.7.4
os: win32 x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0
Windows 10

### Suggestion.
Change the version of the npm package named @angular/cli from version 1.0.0 to version 4.0.0 so that all Angular things are version 4.0.0

**Comment by filipesilva** [comment]
We aim to roughly keep pace with Angular release cadence, but not necessarily version number.

**Comment by brookhutchinson** [comment]
I was of the understanding that one of the goals behind the move from Angular 2.0.0 to version 4.0.0 was to standardize the version numbers of the different Angular packages starting with version 4.0.0

**Why would the @angular/cli package be any different?**  Might not be a big deal to some, but it sure seems like a good opportunity to keep the Angular CLI Package version in line with other Angular Packages.

**@angular/cli: 1.0.0**
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

**Comment by filipesilva** [comment]
That's a fair point tbh... the CLI does not 'live' on the same repo as the rest of the `@angular/*` packages, and isn't released at the same time so that's why version numbers differ.

But a user looking at their `package.json` just sees a bunch of `@angular/*` packages and no information that they 'live' in different places. And the CLI is the odd one out.

**Comment by filipesilva** [comment]
This issue is open for discussion, but we're not going to do anything now really. The CLI is at 1.x and will be for the foreseeable future.

**Comment by hansl** [comment]
Hi @brookhutchinson,

We had a lot of discussions regarding this internally at Google. Basically it comes down to a few points:

1. You shouldn't think about version numbers. Angular 4 is just Angular.
2. Angular CLI is compatible with every version of Angular right now, so the numbering scheme doesn't really work.
3. We're following semantic versioning, so your package.json should be saying `angular-cli: ^1.0.0` and you won't have to change it before version 2 is out.
4. It's managed in a different repository than Angular, so it will always be different minor and patches, and on a different schedule.
5. That last point is worth re-mentioning. We don't want to commit to the same schedule as Angular _just yet_, and so even our majors might not be synchronized. So in 6 months when Angular is releasing version 5, the CLI might be at 1.2 or 1.6, but not ready for version 2. So this versioning would be meaningless.

We may rethink about this but not for a long time, and definitely not before the next major version of the CLI. But because of these reasons, I'm going to close this issue, sorry.

Cheers!
