### ISSUE TITLE
Automatically amend template referenced variables so they have public visibility (AoT)

### ISSUE THREAD

**Issue by SaltyDH** [angular/angular-cli#5747]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

There has been a number of discussions around the AoT requirement whereby variables referenced by Angular templates must have public visibility in order to successfully support the AoT template compilation.

My request to help solve this issue is to provide an optional setting as part of the ngtools webpack process. The compilation process can analyse variables which are referenced from templates, detect the variables current visibility using static analysis and correctly amend the source code stream (setting private and protected variables to public) as it compiles the Typescript code.

If the transformation step is performed late enough in the compilation pipeline (just before templates are compiled/generated), we should get normal typescript errors where visibility constraints are actually broken by source code but avoid the confusion where internal state variables have to be made public.

Disclaimer: I don't begin to think I actually understand the compilation pipeline that takes place here. If nothing else I'm hoping to learn why this sort of approach isn't possible. :)

**Comment by robwormald** [comment]
Short answer is no, because this is the *correct* behavior:
This Component:
```ts
@Component({
  template: `Hello {{name}}`
})
export class MyComponent {
  name = 'world'
}
```
compiles to a HostComponent, which *hosts an instance of the component* and represents the template. This is easier to understand with v2 generated code than v4, so i'll show that, but conceptually its exactly the same (this is entirely psuedocode).

```ts
//this is produced by AoT compilation.
export class MyGeneratedHostComponent<MyComponent> {
  host:HTMLDivElement;
  h1_0: HTMLHeadingElement;
  context: MyComponent; //this is the instance of your component
  constructor(host:HTMLElement){
     this.host = host;
     this.context = new MyComponent(); //we create an instance of the component
  }
  //create the internal DOM
  createViewInternal(){
    this.h1_0 = document.createElement('h1');
    this.host.appendChild(this.h1_0);
  }
  //simplified change detection
  detectChangesInternal(){
     const text = `Hello ${this.context.name}`; //note we are accessing the name property here from *outside the class*
     this.h1_0.innerText = text;
  }
}
```
So your issue is effectively asking us to do a huge amount of engineering work to basically trick Typescript into ignoring something that is fundamentally incorrect.

**Comment by SaltyDH** [comment]
From who's perspective is this fundamentally incorrect though? As developers we've become very accustom to variable visibility and scope and here's a framework that asks us to change that fundamental concept due to a technical implementation.

As a consumer/developer using the Angular framework - I **don't** think about the fact that my component gets turned into a generated host component during compilation and to expect my development team to constantly think that way is not working. We work daily at the source code level, not the compiled outputs.

I really implore you to reconsider this line of thinking - it seems closed minded and technically/implementation driven rather than providing a fantastic and predictable developer experience, this only confuses and alienates developers.

**Comment by robwormald** [comment]
important things to mention about the above:
- we never modify your code (other than the usual TS transpilation)
- we generate *new* code 
- we then typecheck (usual TS semantics) the new program, which is why you see compilation errors. 

Also important to note that `private`, in TS, has no runtime meaning, which is why it "works" - private is for humans, working on teams :) Forcing a property to be public (or, not private) to a template means that we can typecheck your *templates* against your components - so things don't silently fail when you change one or the other.

**Comment by robwormald** [comment]
> From who's perspective is this fundamentally incorrect though?
The Typescript language specification. Forgetting Angular:
```ts

class Foo {
  private bar:boolean
}

class Baz {
  constructor(foo:Foo){
     foo.bar //ERROR: this is private
  }
}

```
You'd find the exact same constraint if you wanted build a baby Angular:
```ts

class MyComponent {
  private name:string = 'world'
}

const myComponentTemplate = context => `Hello ${context.name}`

const html = myComponentTemplate(new MyComponent()) //ERROR!
```

**Comment by SaltyDH** [comment]
Agreed, but is the existence of Foo and Baz driven by implementation detail in terms of how the component compilation process works or do you see that as the specific mental model that should be applied when thinking about components.

Until we introduce AoT into a project, component can be thought of a solitary encapsulated thing. I.E a component is the combination of its behaviour and its presentation (These might be dynamically resolved in some situations, sure).

When you enable AoT, you suddenly have this situation where you now actually have to think about Angular in the same way as the code you've written above. It becomes different. Why did this work yesterday? I hear AoT is good why is it causing me pain now?

Before this turns into a novel:-

* I can no longer guarantee components only communicate through public inputs and outputs when using AoT. Any internal state variable (used in a template) can now be referenced from any other component.

* Just as the AoT process generates new code specific to the Angular compilation process, I'm trying to move an implementation detail out of my source code and into the compilation process where it lives. In doing so, remove a fairly significant difference between a developer's interaction when writing a component for Dynamic vs AoT compilation.

**Comment by SaltyDH** [comment]
From the docs: https://angular.io/docs/ts/latest/quickstart.html

"Angular applications are made up of components. A component is the combination of an HTML template and a component class that controls a portion of the screen. Here is an example of a component that displays a simple string"

To reword this based on the above typescript source code:

Angular applications are made up components and templates. A component is implemented in a typescript class and a template is implemented as a typescript class which is dynamically generated at runtime. 

The implementation detail has bled through the abstraction. I cannot think about a component as a single thing. Its always two things.

**Comment by robwormald** [comment]
> Until we introduce AoT into a project, components can be thought of as a solitary, encapsulated thing.

The only reason AoT is not the default, even in dev mode, is that we cannot yet provide the same level of build/rebuild performance to the open-source community as we do to internal teams at Google (where we do not use JIT mode at all, other than in testing). There's a number of reasons for this, mainly that we have significantly more constrained environment, but also that basically, this stuff is *really* hard. 

The issue here is that developers should not be "introducing" AoT into a project - it should be the default behavior. If this restriction is clear from your first component, its never an issue. You're suffering from migrating, and I apologize for that, but our policy is generally to optimize for the future. This model enables a number of benefits for large teams and codebases and it's unlikely to change.

If you have suggestions on improving the documentation around this at all, a PR would be welcome in the appropriate repository.

**Comment by hccampos** [comment]
I have to agree with SaltyDH on this one.

Most people see the template as part of the component itself and, therefore, private variables/props are visible in it. In fact, it is assumed that everything in the template has a hidden `this.` behind it. This is also how it works in React, for instance, where you can access everything in your render method.

However, the way that AoT is currently implemented in Angular, the template is completely separated from the component itself, and just uses an instance of the component to get its context. It would be much more intuitive to then declare a component separately from the component class...

```
@Component({
  template: "./template.html",
  context: MyComponentClass,
})
```

**Comment by robwormald** [comment]
> However, the way that AoT is currently implemented in Angular, the template is completely separated from the component itself
This is the way *compilation* is currently implemented in Angular, irrespective of if its ahead of time or at runtime. The only distinction is that we cannot *enforce* this behavior because compilation happens at runtime, after type information has been stripped out. 

Because our eventual aim is to make AOT the standard, we'd rather devote engineering hours to making that a reality for everyone. 

At this point, the actionable issue here is that we should make you more aware of this up front, so that you're not confused in the meantime. This is being addressed by our documentation team.
