### ISSUE TITLE
'ng test' command to generate a json covered file

### ISSUE THREAD

**Issue by mmisumi-ciandt** [angular/angular-cli#5856]
Is there any command or way to generate a json file for coverage? I cannot find it in coverage directory.

I need to get the percentage of coverage to use in sonar.

Thanks.

**Comment by cexbrayat** [comment]
You can by using the plugin `karma-coverage-istanbul-reporter`.

```diff
   coverageIstanbulReporter: {
-     reports: [ 'html'],
+     reports: [ 'html', 'json-summary'],
      fixWebpackSourcePaths: true
    },
```

Check the complete documentation over there https://github.com/mattlewis92/karma-coverage-istanbul-reporter

This is not really an issue though, you should ask your questions on Stack Overflow instead of opening Github issues for this kind of thing.

**Comment by marciomsm** [comment]
@cexbrayat thank you. I will ask on Stack Overflow.
