### ISSUE TITLE
ng serve/e2e -no-pr doesn't work

### ISSUE THREAD

**Issue by ishitatsuyuki** [angular/angular-cli#5916]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
node: 7.8.0
os: linux x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Brief

`ng serve/e2e -no-pr` doesn't yield desired behavior.

### Actual results.

Works:
`ng build -no-pr`
`ng test -no-pr`

Doesn't work:
`ng serve -no-pr`
`ng e2e -no-pr`

```
The option '--pr' is not registered with the serve command. Run `ng serve --help` for a list of supported
 options.
```

### Desired functionality.

It should have the same behavior as `ng test/build -no-pr`.

**Comment by filipesilva** [comment]
Sounds like a bug to me. Thanks for reporting it!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
