### ISSUE TITLE
No source map for global less file

### ISSUE THREAD

**Issue by cenkentimist** [angular/angular-cli#6001]
Not sure if this is a bug, or feature doesn't exist. Any additional insight would be welcome. This is similar to some closed problems, but the solutions used for those seem to require accessing the webpack config which to my knowledge is not currently possible. 
My I replaced my styles.css file generated by the angular cli project template with a styles.less and changed the entry in the .angular-cli.json so it worked. The file imports three other css files. This results in 4 style tags when I run the project. When I'm debugging a style for the source all the information I get is &lt;style>...&lt;/style> in chrome dev tools. I can click that and It will take me to the style tag, but then I lose my spot. I also don't get line numbers or anything.

### Versions.
@angular/cli: 1.0.0
node: 7.5.0
os: darwin x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
create a new project.
replace styles.css file with styles.less
replace styles.css in .angular-clit.json with styles.less
add some imports to styles.less and styles
create put some html in app.component.html that uses the styles.
observe that you can't effectively debug it in chrome.

### Desired functionality.
source map for the styles.less or work around.

**Comment by clydin** [comment]
Source maps for stylesheets can only be enabled if the CSS is extracted.  This is due to an issue with an underlying dependency.  For development builds this is disabled by default but the `--extract-css` option can be used to enable extraction.  Note that this may have negative effects on rebuild performance and required special handling if using HMR.

Also (and unrelated), from looking at your repro steps, imports in your `styles.less` file should not need to added to the styles array in your angular-cli config.

**Comment by cenkentimist** [comment]
Oh I get it. Don't think I would of figured this out on my own, but I still should of thought to consult the command line flags before asking. @clydin thanks a bunch.
