### ISSUE TITLE
Cannot find name '__moduleName'

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#607]
Bug in 0.0.34
Created a new component (with ng g component)
Then, after building, I get this error:

Cannot find name '__moduleName'

Which is in the newly generated component.

**Comment by hansl** [comment]
You'll need to do a few things because that's a breaking change to your app:

1. Update your CLI to the latest.
2. Change `__moduleName` to `module.id` everywhere.
3. Change your tsconfig to build with commonjs instead of system.
4. There's a line in the `system-config` that says something like `format: "system"` or something like that. Remove that line entirely.
5. That should work and I'll close this issue, but assuming it doesn't, please update this issue instead of creating a new one.

Cheers!
