### ISSUE TITLE
Infinite loop on ng build --watch, does not detect change anymore

### ISSUE THREAD

**Issue by stevehouel** [angular/angular-cli#6092]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

When I am running the command to build my applicaiton with **watch** option enabled, the build is doing an infinite loop. Files are built every 5seconds instead of detecting those who have changed (or not)

### Versions.

Version used : 1.0.1

### Repro steps.

`ng build -w`

### Desired functionality.
Detect files content change instead of build every 5seconds all files.

### Mention any other details that might be useful.
I am trying to use the build watch function with Browsersync and those infinite build reload the server every time which is unuseable.

**Comment by filipesilva** [comment]
This isn't something I can reproduce myself. It kinda sounds like you have some process in your machine that does something to your files every 5 seconds.

**Comment by stevehouel** [comment]
For information I am on MacOS X
Le ven. 5 mai 2017 à 19:23, Filipe Silva <notifications@github.com> a
écrit :

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
