### ISSUE TITLE
Babili support

### ISSUE THREAD

**Issue by aldo-roman** [angular/angular-cli#6097]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 7.4.0
os: win32 x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3
@angular/language-service: 4.0.3

### Desired functionality.
I would like to have opt-in babili support when building from AngularCLI.
This would allow to compile and minify ES2015 code.
Currently, only Uglify is supported, which only supports ES5

Check https://github.com/babel/babili

### Mention any other details that might be useful.
#2907 is related

**Comment by filipesilva** [comment]
There's a https://github.com/webpack-contrib/babili-webpack-plugin but as far as I can tell it's not a drop-in replacement for Uglify really.

**Comment by filipesilva** [comment]
Consolidating this with #2907, discussion will continue there.

**Comment by alan-agius4** [comment]
#
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
