### ISSUE TITLE
Angular2 Firebase installation Error

### ISSUE THREAD

**Issue by saimzishan** [angular/angular-cli#6222]
This error is come when i m getting install the ( npm install angularfire2 --save ), Any One  have solution?
![capture](https://cloud.githubusercontent.com/assets/26278266/25808361/afe8a1f4-33be-11e7-9703-8f23d22f61a5.PNG)

**Comment by Shyam-Chen** [comment]
You have to update your `@angular/cli` version.

**Comment by filipesilva** [comment]
@saimzishan the errors you are getting are peer dependency errors. This means that some of the packages you are using expect certain other packages (and versions).

In this case, you are using `angularfire2@4.0.0-rc.0`, and you are getting a few warnings about how it requires other package/version combos (like `@angular/common@^4.0.0`).

Just go through all of those and install them (`npm install @angular/common@^4.0.0 --save` and so forth).

Installing some new peer dependencies may show more peer dependency warnings because the new package can have it's own requirements as well. As you go through all of them they'll start to go away.

**Comment by saimzishan** [comment]
@filipesilva thanks for comment, i have solve this problem my own, my npm is in old version, i replace with a new one version, and error is gone. 
Thanks
