### ISSUE TITLE
Configurable options for ng e2e

### ISSUE THREAD

**Issue by anthonynd** [angular/angular-cli#6241]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [x] feature request
```

### Desired functionality.

I'd like the ability to configure the default behaviour of `ng e2e` similar to how you can configure `ng serve`. That is passing default properties in .angular-cli.json. And I'd also like to be able to configure how `ng e2e` serves as well. For example, by default it serves on a random port, but I'd like to specify a default port for the server to be run on.

Here's an example of how it could look within the .angular-cli.json file.
```
...
"defaults": {
  "e2e": {
    "config": "some-other.config.js",
    "specs": [
      "test1.spec.js",
      "test2.spec.js"
    ],
    "port": 80
  }
}
...
```

**Comment by filipesilva** [comment]
`ng serve` has some defaults in `.angular-cli.json` because it can't really be configured another way. `ng e2e` however, can be mostly configured by `protractor.json`. 

For this reason I don't think this would be a very worthwhile addition to the config file, especially since we're ware of configuration bloat. There's already a lot of options there.
