### ISSUE TITLE
index.html build not in the outDir

### ISSUE THREAD

**Issue by pguichon** [angular/angular-cli#6253]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
@angular/cli: 1.0.2
node: 6.9.5
os: darwin x64

### Desired functionality.
I have many app in my .angular-cli.json and each app have one main.ts, index.html, style.css like appIndex.html, appMain.ts, appStyle.css with outDir=dist_app
when i build apps, i have a dist_app with appIndex.html not index.html
A option for indicate the name of the index.html for the outDir will be a good idea ?
sry for my bad english

thx

**Comment by filipesilva** [comment]
We actually just use the name you provide the CLI config, as some users requested us not to rename. That gives users better control. 

It's not yet published but you can find docs for multiple app support here as well: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/multiple-apps.md

**Comment by dmayerdesign** [comment]
Can this be reopened?

I'm running into the same issue -- the behavior one would expect is that `index.html` be placed at the path specified in `outDir`, but if `outDir` is outside of `--source-dir`, `index.html` gets placed at a path relative to `--source-dir`.

I have an app set up using `ng new my-app --source-dir src/client`, so my `node_modules`, `e2e`, etc live in `~/my-app` and the source files live in `~/my-app/src/client`. I've set `outDir` to `"./dist/public"`.
My issue is that `index.html`, instead of being placed in `~/my-app/dist/public`, is being placed in `~/my-app/src/client/dist/public`.

Snippet of my angular-cli.json:

```
...
"apps": [
    {
      "root": "./source/client",
      "outDir": "./dist/public",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
...
```
