### ISSUE TITLE
 ng completion -b >> ~/.bashrc fails if local cli version is different from global cli version

### ISSUE THREAD

**Issue by carlobonamico** [angular/angular-cli#6343]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Your global Angular CLI version (1.0.1) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.10.3
os: linux x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```
### Repro steps.
1) create project with @angular/cli 1.0.0
2) install @angular/cli 1.0.1 globally ( npm install -g @angular/cli)
3) cd in the project folder
4) run as suggested 
ng completion -b >> ~/.bashrc 

At this point .bashrc includes the warning message
``Your global Angular CLI version (1.0.1) is greater than your local``

### The log given by the failure.
Opening a new bash shell prints out
```
bash: /home/bonamico/.bashrc: line 115: syntax error near unexpected token `('
bash: /home/bonamico/.bashrc: line 115: `Your global Angular CLI version (1.0.1) is greater than your local'
`'`


### Desired functionality.
clarify help for ng completion so that the warning do not come up in the .bashrc file


### Mention any other details that might be useful.

**Comment by catull** [comment]
This is not a bug, and here's why.

Typically, running `ng completion -b >> ~/.bashrc` / `ng completion -z >> ~/.zshrc` should NOT be performed _inside_ an ng project folder.

If you use oh-my-zsh or bash-it, and enable ng tool support, the completion for ng is switched on transparently, as soon as the shell is started and gives control back to the user.

You do not need to run this command constantly, unless you develop the completion functionality in angular/cli.

In fact, `ng completion` should only be callable _outside_ of an ng app folder, for that matter.

**Comment by loganmzz** [comment]
I consider it a bug as:
* messages must be passed as stderr when you are supposed to generate interpretable content
* no output must be sent on stdout
* command must ends with an exit code different from 0

**Comment by catull** [comment]
The user who wants to generate NG completion **inside** of an ng app folder has to face the consequences.
That includes surprises of discontinued options/commands or changed options etc.

PR #7246 corrects the behaviour, whereby the warning on version mismatch is written as a shell comment to stdout.

This almost satisfies your first concern.

The problem is that both `console.log('Message')` and `console.warn ('Message')` write to stdout, only `console.error('Message')` writes to stderror.
Which means, it would have to be an error to warrant writing to stderror.
@hansl @filipesilva @Brocco 
The ng CLI core team decides whether console.error is preferable here.

I disagree with your second point.
An older version of the completion is producing correct output for that specific version.
A warning is not an error, the completion shell output is fine.

The third point would be a small change.
@hansl @filipesilva @Brocco 
However, the ng CLI core team decide whether this is acceptable.

**Comment by loganmzz** [comment]
I will speak from my personal experience.

For a CLI tool, completion is not a nice-to-have but must-to-have.

Having different versions of CLI isn't an exceptional case to me. You're working on different project and CLI is installed globally (to be able to use `new`) and locally (automatically done by `ng new` and I found it nice to be consistent during project development).
As you wish to be keep uptodate for new projects, you don't want to update your project each time angular team provides new releases (for framework, CLI or any other). Otherwise you will spend time to make integration, not development.

`completion` command is specific and message in the case, that output **must** be interpreted. Tools that provide interpretable content assume that they will be piped/redirected. It is a basic in system programming and one of *nix foundation. You can take a look at how `grep` or `ls` commands handle their warnings.
Interfaces for machine can't act as those for humans. In Web development, they are some practise to use `Content-Type` or URL to have specific rendering (`application/html` VS `application/xml` or `/api/***` VS `/view/**`). `completion` command is one case of specific rendering for machine interface.

**Comment by catull** [comment]
@loganmzz 
Created a new PR #7366 much more along your line of thinking.
