### ISSUE TITLE
vss-web-extension-sdk doesn't work with typings

### ISSUE THREAD

**Issue by DrMueller** [angular/angular-cli#6356]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.1
node: 6.9.1
os: win32 x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.2

### Repro steps.

1. - Get the Repo https://github.com/DrMueller/vss-sdk-test
2. - Try to run ng build

### Desired functionality.
I'd like to add the typings for the mentioned sdk in order to use Intellisense. According to the CLI ReadMe and this issue: https://github.com/angular/angular-cli/issues/4249 all, I'd need to do is to add the package to the typings.d.ts and import it. Unfortunately, the CLI can't resolve the exported Module.
I've tried all sorts of combinations, but I didn't get any feedback on Stackoverflow and didn't find any information regarding that topic or Imports generally.

**Comment by Brocco** [comment]
You were correct to go to stack overflow first with this issue, as this repo is not the ideal spot for support questions. Because of that I am going to close this issue.

That being said I looked at your repo you created a typings file in the root of your project instead of adding it to this file: https://github.com/DrMueller/vss-sdk-test/blob/master/src/typings.d.ts so please try updating that file. If that does not work, please post a link to the stack overflow question here as I try to keep an eye on those as well.

**Comment by DrMueller** [comment]
Hi Brocco, thanks for the feedback. I agree I shouldn't ask here for Support, but as you can see from my SO request here: https://stackoverflow.com/questions/43945422/angular-cli-specific-typings-folder ,nobody seems to know how the magic on the CLI works. I also didn't find any reasonable sources regarding that topic, so therefore it might be bit underdocumented? Probably it's also painfully obvious...
