### ISSUE TITLE
Angular cli fails to resolve capital letter classes on Linux

### ISSUE THREAD

**Issue by qwert789** [angular/angular-cli#6409]
This issue happens on Linux only:

When you trying to import class using capital letters it fails:

`Import User from './../../../shared/models/User'`
Throwing  failed to resolve module exception!

However changing it to:
`Import User from './../../../shared/models/user`' works fine.

Please note: under Windows and Mac the first declaration works perfectly fine.

**Comment by robwormald** [comment]
what's the actual file name?

**Comment by qwert789** [comment]
The actual file name is user.ts, path was automatically imported by vscode.

**Comment by Brocco** [comment]
This seems like an issue for the VS Code repo, the 2nd import is the correct one and VS Code should generate the correct import automatically.

**Comment by qwert789** [comment]
@brocco You can't close it like this , this causes inconsistency - why does it works in MAC OS/ Windows, for such things people drop using angular in general.

**Comment by filipesilva** [comment]
@qwert789 I just want to add that VS Code generated an invalid import for you - OSX and Windows support case insensitive paths but not Linux.

This isn't something we could allow in the CLI either, because in Linux you **can** have both `./shared/models/User.ts` and `shared/models/user.ts` files, and these are different things.

**Comment by Brocco** [comment]
@qwert789 I'm sorry you feel that way. As @filipesilva explained this is an OS-level issue caused by code that VS Code generated and is therefore something we can't fix via the CLI.

We do generate some imports automatically and try to keep the casing of those consistent to not cause any bugs. I hope you're able to find a solution with the VS Code team for this issue.

**Comment by qwert789** [comment]
thanks for the explanation in general I agree , but why can't we force cli try to resolve it using both cases I mean if user.ts not found why can't it try resolve User.ts. Please agree with me  that even if Linux allows 2 files coexist it isn't realistic scenario for app to have it.
