### ISSUE TITLE
base href conflict

### ISSUE THREAD

**Issue by fdhadzh** [angular/angular-cli#646]
Please, create base href replacement optionally.

**Comment by cmiagssh** [comment]
Solution:

Replace
<base href="/">
with 
<script>document.write('<base href="' + document.location + '" />');</script>
in
angular-cli\addon\ng2\blueprints\ng2\files\__path__\index.html

**Comment by fdhadzh** [comment]
Thanks. I solved this problem by:
```javascript
import {APP_BASE_HREF} from '@angular/common';

bootstrap(AppComponent, [
  ROUTER_PROVIDERS, 
  provide(APP_BASE_HREF, {useValue : '/' });
]); 
```

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/1064, which is more explicit.

**Comment by niklas-dahl** [comment]
@fdhadzh I tried your solution but it only works for routes like this: `localhost:4200/xxx`.
The moment the route is one "layer" deeper it doenst work: `localhost:4200/xxx/yyy` or just `localhost:4200/xxx/` (second slash).

This is because without a `base` tag the generated `script` tags no longer refer relative to `/`:
```
<script type="text/javascript" src="inline.bundle.js"></script>
<script type="text/javascript" src="styles.bundle.js"></script>
<script type="text/javascript" src="scripts.bundle.js"></script>
<script type="text/javascript" src="vendor.bundle.js"></script>
<script type="text/javascript" src="main.bundle.js"></script>
```
I want to use svg markers that require relative `FuncIRI`s.

@filipesilva Is this currently solvable with the current webpack setup?

Thanks.

Problem described here:
https://stacksandfoundations.com/2016/06/22/svgs-funciri-angular2-and-the-base-tag/
