### ISSUE TITLE
feat(environment): add build time and version to environment

### ISSUE THREAD

**Issue by frederikschubert** [angular/angular-cli#650]
We would like to show the current version and build time in our apps. This makes giving feedback easier during QA and one can assert, that the right version is deployed and loaded.

**Comment by phillipgreenii** [comment]
Just so I understand this, do you mean some kind of dynamically generated class that contains build information?

**Comment by frederikschubert** [comment]
Yes. That would be really helpful. Maybe it is even possible to add the information to environment.ts?

**Comment by filipesilva** [comment]
I understand the usecase as I had projects that needed this, but think this is mostly a user-feature to be honest.

Since this is the sort of stuff that gets deployed, you'll need to make it part of the application. I agree that `environment.ts` is the right place for it as well. Then you can import that information onto your app and display it somewhere.
