### ISSUE TITLE
Angular CLI server not starting

### ISSUE THREAD

**Issue by Rambj** [angular/angular-cli#6524]
i am unable to start the Angular CLI server in Eclipse workspace angular. I have downloaded the plugin Angular for eclipse neon. I have created the new project with angular, but unable to start the Angular CLI server. Below  is the link i am following.
[https://www.genuitec.com/first-angular-2-app/](url)

Regards,
Ram

**Comment by Rambj** [comment]
Pls Explain the folder structure for Angular2 and the dependencies to download

**Comment by sumitarora** [comment]
@Rambj Seems like the post is outdated you can follow the wiki to create and run CLI project. Should be three commands.
- `ng new hello-world`
- `cd hello-world`
- `ng serve`

After that opening `http://localhost:4200/` in the browser, you should see sample app.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
