### ISSUE TITLE
Site is not auto reloading if "ng serve" is running.

### ISSUE THREAD

**Issue by DurgaAbhist** [angular/angular-cli#6561]
Hi Sir, Madam,

I'm Durga Abhist and I recently started working with Angular/CLI tool, I'm facing a problem while executing the file, that is when I run "ng serve " command then this command helps us in auto reloading the site when any changes are made in the source file but in my system it is not happening (i.e. site is not auto reloading and when I forcely reload the site then also it is not getting updated as per changes made in the source file).

The site is getting updated only when I terminate the "ng serve" command and again run the same command("ng serve") then only my site is getting updated.

So it becomes hard for me to terminate the server and connect the server, when ever the changes are made, so I request you Sir/Madam help me out in this issue.

**Comment by filipesilva** [comment]
Heya, there are a few reports of live reloading not working properly but they are heavily dependent on the system and setup. My advice is to have a look at the existing issue on this topic (https://github.com/angular/angular-cli/issues/1610), perhaps some of the fixes suggested there apply to your case.

**Comment by kartikchauhan** [comment]
Restarting my system helped in fixing the issue.

**Comment by simeyla** [comment]
PS. Doesn't seem like it's related to auto reloading because you say 

> when I forcely reload the site then also it is not getting update

I just had the same problem:

* I am using a ASPNET Core application with a development proxy to pass through to port 4200
* I noticed that when accessing 4200 directly in the browser then the reloading logic worked just fine
* So I assumed it was something in the proxy caching it, but restarting the ASPNET Core server did nothing
* Then I remembered I'd been playing with benchmarking and using `--aot` command which builds into the `dist` folder
* I deleted the contents of `ClientBin\dist` and re-ran my `npm start` command (which runs `ng serve`) and then everything was back to normal again :-)

So it may be as simple as **delete ClientBin\dist**
