### ISSUE TITLE
A lot of test cases have undefined names, licence test failing as well

### ISSUE THREAD

**Issue by gioragutt** [angular/angular-cli#6569]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

master

### Repro steps.

`clone the repository`  
`npm install`  
`npm run test`  
you can see that a lot of test cases (`describe`, not `it`) are `undefined`

### The log given by the failure.

```
undefined
    √ ng generate guard ..\my-guard from root dir will fail
undefined
    √ should error out when given an incorrect module path
    should import and add to provider list
      √ when given a root level module with module.ts suffix (339ms)
      √ when given a root level module with missing module.ts suffix (341ms)
      √ when given a submodule with module.ts suffix (669ms)
```

as for the licence test

```
You cannot use the new command inside an Angular CLI project.
Invalid package licences found:
jschardet@1.4.2 (D:/Repositories/angular-cli/node_modules/jschardet): LGPL-2.1+
```

### Desired functionality.

all tests should have valid names and there should be no licence tests failing

**Comment by clydin** [comment]
The `undefined` lines are actually caused by [this line](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/ember-cli/lib/cli/cli.js#L161) and not anything to do with test case names.  This only occurs in ember-cli testing mode.

The license failure seems to be due something odd happening with yarn in combination with the e2e tests and/or build.  That package isn't actually used by the CLI.  It is a transitive dependency of yarn though.

**Comment by gioragutt** [comment]
Thanks for clearing that out.
