### ISSUE TITLE
DatePipe error when using `navigator.language` as LOCALE_ID with aot

### ISSUE THREAD

**Issue by robindijkhof** [angular/angular-cli#6618]
### Bug Report
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0-beta.1
node: 6.10.2
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.2.0-beta.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

Windows 10
Chrome 58.0.3029.110 (64-bit)
FireFox 53.0.3

### Repro steps.
I'm providing this LOCALE_ID in my appAppModule `{provide: LOCALE_ID, useValue: navigator.language}`

Install this project https://github.com/robindijkhof/localeTest
run with `ng serve --aot`

### The log given by the failure.
```
ERROR TypeError: Cannot convert undefined or null to object
    at new DateTimeFormat (native)
    at intlDateFormat (http://localhost:4200/vendor.bundle.js:14481:12)
    at http://localhost:4200/vendor.bundle.js:14542:45
    at dateFormatter (http://localhost:4200/vendor.bundle.js:14554:16)
    at Function.webpackJsonp.../../../common/@angular/common.es5.js.DateFormatter.format (http://localhost:4200/vendor.bundle.js:14597:16)
    at DatePipe.webpackJsonp.../../../common/@angular/common.es5.js.DatePipe.transform (http://localhost:4200/vendor.bundle.js:14960:30)
    at checkAndUpdatePureExpressionInline (http://localhost:4200/vendor.bundle.js:26971:38)
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:27868:17)
    at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:27801:16)
    at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:28504:59)
```

### Desired functionality.
It shouldn't crash

**Comment by ocombe** [comment]
Hello, the problem is double:
`LOCALE_ID` needs to be defined at bootstrap for the compiler, it won't work if you define it in a module later on. For JIT you would change your main.ts file like this:
```ts
platformBrowserDynamic().bootstrapModule(AppModule, {provide: LOCALE_ID, useValue: navigator.language});
```

But for AOT you have to use the cli parameter `--locale` when you serve / build. In your case it would be for example:
```sh
ng serve --aot --locale fr-FR
```
The reason for that is that the compiler will compile the files "offline", and the compiler part will be dropped from the angular bundle (it is no longer available at runtime). But since `LOCALE_ID` is used by the compiler for i18n, it needs to be defined manually.
This means that you cannot define the locale for AOT with the value from navigator.language, since this is not available in your cli (obviously).

**Comment by robindijkhof** [comment]
@ocombe are you sure? 

> Argument of type '{ provide: InjectionToken<string>; useValue: string; }' is not assignable to parameter of type 'CompilerOptions | CompilerOptions[]'

**Comment by ocombe** [comment]
Sorry, it should be:
```ts
platformBrowserDynamic().bootstrapModule(AppModule, {providers: [{provide: LOCALE_ID, useValue: navigator.language}]});
```

You can take a look at my demo project that supports JIT and AOT (with server side detection of the browser locale for AOT): https://github.com/ocombe/i18n-demo

**Comment by robindijkhof** [comment]
Thanks!
