### ISSUE TITLE
add --config option to ng lint

### ISSUE THREAD

**Issue by philippart-s** [angular/angular-cli#6664]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Versions.

@angular/cli: 1.0.1
node: 6.10.2
os: win32 x64 (Windows 7)

### Repro steps.

launch command `ng lint --config /foo/tslint.json`

### The log given by the failure.

The option '--config' is not registered with the lint command. Run `ng lint --help` for a list of supported options.

### Desired functionality.

Is it possible to implement the ability to pass the path of the eslint config file. 
The aim is to centralize le config and that the config cannot be modifiable.

**Comment by billfranklin** [comment]
we would really appreciate this change.

**Comment by sam-s4s** [comment]
Ah, I just spent a good 5 minutes playing around with different combinations of setting the config file, only to find out ng lint didn't implement it LOL

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

Kindly see: https://angular.io/cli/lint there is a option named `tslintConfig`

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
