### ISSUE TITLE
Problem with Angular Cli, Build and Routes

### ISSUE THREAD

**Issue by lennonalvesdias** [angular/angular-cli#6665]
I have a problem with an Angular application, someone help me?
When running 'ng serve', everything flowed normally, but when performing 'ng build' and execute to the server, when I refresh the page the application loses the route by returning the following message: 'The requested URL was not found in this Server. '.

When I build the command 'ng build --prod' or 'ng build --prod --aot' some errors appear, such as:

'ERROR in Child compilation failed:
Module not found: Error: Can't resolve './.' in '[...]\src\app\admin':
Error: Can't resolve './.' in '[...]\src\app\admin'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '[...]\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts'

Despite some similar situations, I have not found any resolution on the internet so far. Thank you for your attention. Hugs.

**Comment by Brocco** [comment]
You will need to configure the web server you're deploying to to redirect requests that can't be handled (404's) to `index.html` and allow the client application handle routing.

**Comment by zohar1000** [comment]
hi @lennonalvesdias , I found out eventually what the problem was.
it was a definition in the css, there was an empty url for a background image, something like:
   background-image: url('') 
the background image was filled during run time by the .ts script.

It wasn't my code, I was given the task to compile it for aot after the programmer who wrote it
and his team leader gave up on trying to find out what the problem was. I found out a bunch of
other errors that the aot compiler produces that the jit compiler doesn't, can't understand why they
both don't share the same compilation code, but I guess there are reasons..  at least for some errors the angular compiler messages can be improved, that would save us a lot of time on problems like this one (:

on any case thanks for and the help and the willingness :)
