### ISSUE TITLE
e2e tests do not run after ejecting

### ISSUE THREAD

**Issue by Chuvisco88** [angular/angular-cli#6678]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.1.1 (e)
node: 7.4.0
os: darwin x64
@angular/animations: 4.2.2
@angular/common: 4.2.2
@angular/compiler: 4.2.2
@angular/core: 4.2.2
@angular/forms: 4.2.2
@angular/http: 4.2.2
@angular/platform-browser: 4.2.2
@angular/platform-browser-dynamic: 4.2.2
@angular/router: 4.2.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.2.2
@angular/language-service: 4.2.2
```

### Repro steps.

```
ng new project --style=scss --routing --prefix=prefi
cd project
npm run e2e
ng eject
npm install
npm run e2e
```

### The log given by the failure.

```
**************************************************
*                    Failures                    *
**************************************************

1) project App should display welcome message
  - Failed: Angular could not be found on the page http://localhost:4200/.If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see 
                            https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load

```
The dev server is not started before the tests are run

### Desired functionality.

The server is starting before running the e2e tests (same behaviour as before the eject was done)

**Comment by emilio-martinez** [comment]
I think once you eject you have to manually run `npm start` to kickstart the server and then in a separate process run the e2e. It's inconvenient, but you could also write a script to exec the sequence of operations.

**Comment by zebslc** [comment]
What goes into that custom script when in a CI environment (in my case VSO but this probably applies to all of them)?  

My CI test for e2e is now broken because of this.  Ejecting should create the necessary script to carry on testing as before or have clear instructions about what to do to fix the issue - running a second terminal would only be of use if you were running locally.  

I have added a question on stack overflow & would really appreciate if anyone knows how to  fix :

Thanks 😄 

https://stackoverflow.com/questions/49655014/angular-continuous-integration-e2e-test-broken-on-visualstudioonline-after-eject

My ejected seed project using it
https://github.com/zebslc/angular5mat

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
