### ISSUE TITLE
Feature request: Also use kjhtml reporter when code-coverage is enabled.

### ISSUE THREAD

**Issue by robindijkhof** [angular/angular-cli#6732]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
Currently when enabling code-coverage on the unittest `kjhtml` reporter is not used. I can't think of any reason why. I think it would be usefull if it was enabled again.

`reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],`

**Comment by delasteve** [comment]
The Karma file has been updated back in May to no longer use this logic. You can find the updated blueprint here:

https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/karma.conf.js

Make sure to upgrade your CLI to the latest version because there were other changes done that are necessary for this to work properly.

**Comment by Brocco** [comment]
Thanks @delasteve... closing this issue as resolved.
