### ISSUE TITLE
Generate index.ts file for component generations

### ISSUE THREAD

**Issue by gioragutt** [angular/angular-cli#6743]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality.

`ng g c my-comp --index`
`my-comp/index.ts` would be generated
`import { MyCompComp } from './my-comp';` would work

flag name subject to change

### Mention any other details that might be useful.

I think that this is something that might spare some time for people, as doing `./my-comp/my-comp.component` can be quite long to write for every component.

It will make people have to write less code eventually and make them think less exactly which file needs to be imported, because the index makes you think only about the name of the component, without having to explicitly use the component ts file path.

**Comment by TheDonDope** [comment]
Index-, or barrel-files as they were called were around for some time to achieve those shortcuts you described. They were even suggested for use by the [official Styleguide](https://angular.io/guide/styleguide).

However, with the introduction of `NgModule`s they became obsolete. Barrel-files always posed the risk of circular dependencies which can be nifty to figure out, since order of `import` statements is of the essence.

Since the barrel rule was removed from the styleguide, my 2 cents are to not re-introduce this error-prone functionality and instead stickt to full-qualifified `import` statements. Yes they are a tad more code to write, alas they make dependencies full on visible.

**Comment by gioragutt** [comment]
@TheDonDope condering they're still pretty useful for exporting public api's (much like the packages in `@angular`), but I do agree they can cause some trouble.

Having to do full qualified `import` statements can also be a bit error prone (webpack occasionally fails with a silent error, which turns out to be an import that is no longer valid but is not reported in the code editor), and really tedious to write when you have a lot of imports. There has to be some middle ground regarding export organizing, otherwise importing will be a bitch.

**Comment by filipesilva** [comment]
@TheDonDope's comment accurately reflects why they were removed. There are no plans to add them back currently.
