### ISSUE TITLE
Ending a i18n app - translation 'target' element with question mart crashes an application.

### ISSUE THREAD

**Issue by KrystianRos** [angular/angular-cli#6849]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.1.0
node: 6.11.0
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.0
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Repro steps.

Define a translation file (xlf v 1.2) with the following translation (a sample i18n app could be found here https://medium.com/@feloy/deploying-an-i18n-angular-app-with-angular-cli-fc788f17e358):
`<target>Gut Bier?</target>`
and build app with command:
ng build --output-path=dist/de --aot -prod --bh /de/ --i18n-file=src/i18n/messages.de.xlf --i18n-format=xlf --locale=de

### The log given by the failure.

> inline.5ac3c6f….bundle.js:1 Uncaught SyntaxError: Unexpected token {
> polyfills.60e21c0….bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
>     at polyfills.60e21c0….bundle.js:1
> (anonymous) @ polyfills.60e21c0….bundle.js:1
> vendor.449ec25….bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
>     at vendor.449ec25….bundle.js:1
> (anonymous) @ vendor.449ec25….bundle.js:1
> main.23c05b7….bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined
>     at main.23c05b7….bundle.js:1

Adding a blank space after question mark (or removing it) could solve a problem, but is not a solution.

### Desired functionality.

This should not cause a error.

**Comment by ocombe** [comment]
Hello, I've cloned the app linked in the medium article, it's an ejected cli app, which means that you cannot run `ng build --output-path=dist/de --aot -prod --bh /de/ --i18n-file=src/i18n/messages.de.xlf --i18n-format=xlf --locale=de`, you have to use a webpack config file.
I cloned the webpack.fr.config to make one for "de", and I cloned the xlf french file as well to make a german one with a translation containing "Gut Bier?". The build worked fine.

You probably have a problem with your webpack config, but I don't think that it has anything to do with angular-cli or angular. If you still think that this is the case, then please provide us with your own project since the one that you linked works fine.

**Comment by ocombe** [comment]
Closing this since there was no reply for a while.
