### ISSUE TITLE
--no-extract-css in prod should not create another bundle

### ISSUE THREAD

**Issue by mernen** [angular/angular-cli#6957]
I have an application with a very small bit of global CSS. I figured I could inline it into my JS bundles with `--no-extract-css` and save a request, but instead it just got replaced by an equivalent JS bundle!

### Bug Report or Feature Request
- [ ] bug report
- [x] feature request

### Versions.

    @angular/cli: 1.2.1
    node: 8.1.4
    os: darwin x64
    @angular/core: 4.2.6

### Repro steps.

This can be demonstrated with a blank CLI project:

```
ng new foo
cd foo
yarn install
ng build --prod --no-extract-css
```

(of course, the blank project is somewhat silly here since the input CSS is empty, but the idea still applies)

### Desired functionality.

Expected: no styles bundle, and a slightly larger main bundle.

Actual: “styles” CSS bundle is gone, but a new JS bundle appears in its place — which is necessarily larger.

**Comment by filipesilva** [comment]
`--extract-css` refers to having a `.css` bundle instead of a `.js` bundle for global styles. The `.js` bundle is just a development optimization for faster rebuilds, due to the way that Webpack works. 

We're not looking at adding CSS inlining capabilities overall though. It offers no benefits for apps, it's just bigger and slower to process by the browser.
