### ISSUE TITLE
Empty string as base href argument

### ISSUE THREAD

**Issue by williamAlhant** [angular/angular-cli#7044]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.0.3
(I checked the change log for newer versions but there is no reference to this particular issue, as far as I can see)

### Repro steps.
When using the --base-href argument, it does not seem to be possible to use an empty string, as it keeps the old base href (the one set in index.html) instead of overriding it with empty string.

I am using the following command :
`ng build --watch --output-hashing=none --base-href='' --output-path=[...]`
but the base-href is not working as intended.

**Comment by filipesilva** [comment]
This is a bug in https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/lib/base-href-webpack/base-href-webpack-plugin.ts#L10.

We do `if (!this.options.baseHref) {` and since `!''` is also evaluated to false, the plugin does nothing.

Would you be interested in making a PR that fixes this behaviour?

**Comment by sendilkumarn** [comment]
@filipesilva is this up for grab?

**Comment by filipesilva** [comment]
Sure is!
