### ISSUE TITLE
Importing promises in Angular 4

### ISSUE THREAD

**Issue by yvessabourin** [angular/angular-cli#7067]
Bug Report

Output from: `ng 4.3.0`.`node 3.10.9` and `npm 6.9.2`. macOS (Sierra)

I have developed a service to pick up a list of invoices from RabbitMQ using amqplib and bluebird.

When I use pure Javascript, that part works fine. I then migrated to Typescript with an ES5 target and got the invoice recuperation part to work alright, but the objective is to import the result into a component to display the information (or use dependency injection eventually). The import however is always showing the promise as undefined.

After noticing that bluebird was ignored by the compiler, I decided to remove bluebird in view of some conflicts with zone.js and use native promises instead, but the result was the same.

Using Gulp to target ES5 I have managed to make things work as expected with pure Javascript, but bringing the code back into Angular I always run into the same wall. I suspect a problem with either Angular-CLI (1.0.0-beta-28.3) and/or Webpack v=configuration.

**Comment by clydin** [comment]
The latest stable version of the CLI is 1.2.1.  Your version is quite outdated.  I'd suggest upgrading both the CLI and the project's dependencies.

Also, in the future please use the issue template.

**Comment by yvessabourin** [comment]
A little while ago I tried to upgrade to 1.0.3, it was a disaster and I had to revert back to the one I already had. I will start with that. I did use the template, but thought I would make things a little more synthetic. I will abide by it next time.

**Comment by clydin** [comment]
There's a migration guide (https://github.com/angular/angular-cli/wiki/stories-1.0-update ) that may be helpful.  Also, depending on your project, it may be easier to create a new project with the latest version and manually move over the app specific code.

**Comment by filipesilva** [comment]
As @clydin mentioned you are using quite an old version, and a lot has changed since then. We don't really support that version anymore so there is very little we can do to help.

Regarding the webpack build config, I don't believe there is anything inherently wrong. If I had to bet, the promise library you are using isn't compatible with the promise implementation in TypeScript or the ones expected by Angular itself. 

I'm closing this issue as I feel the core questions have been addressed and there doesn't seem to be anything actionable. If you still have problems with promises please do open a new issue and include a small repro of how the build breaks.
