### ISSUE TITLE
Latest cli fails to install

### ISSUE THREAD

**Issue by MrVibe** [angular/angular-cli#7167]
Type to update to latest CLI but consistently fails on Mac. 

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> found several links but none of them works.
- [ ] feature request
```

### Versions.
angular-cli: 1.0.0-beta.28.3 ( Trying to update it )
node: 7.2.1
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10

### Repro steps.
npm cache clean 
npm install -g @angular/cli@latest

Stuck at : fetchMetadata: verb afterAdd /Users/xxxx/.npm/yallist/2.1.2/package/package.json written ( 30 minutes and then times out )

### The log given by the failure.
Operation timed out. 

### Desired functionality.
Should install without operation timeout.

### Mention any other details that might be useful.
Tried on Windows and Mac at the same time, while it installed correctly on Windows, it failed to install on mac.

**Comment by ampgular** [comment]
Hi @MrVibe. Have you tried  as descrid in the repo

If you're using **Angular CLI 1.0.0-beta.28 or less(which is your case)** , you need to uninstall angular-cli package. It should be done due to changing of package's name and scope from angular-cli to @angular/cli:

npm uninstall -g angular-cli
npm uninstall --save-dev angular-cli

To update Angular CLI to a new version, you must update both the global package and your project's local package.

Global package:

npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
Local project package:

rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
npm install --save-dev @angular/cli@latest
npm install

HOPE it helps

**Comment by MrVibe** [comment]
Thanks, this resolved the issue.

**Comment by bellalDjam** [comment]
Hi ,

Im on Windows7 64x, tried to  install Angular/cli I followed this step but
npm install --save-dev @angular/cli@latest

the consol block in this step
..............] | fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 .

Thanks.
