### ISSUE TITLE
A issue will occur when I operate the ng~

### ISSUE THREAD

**Issue by Huang9495** [angular/angular-cli#7174]
A issue will occur when I operate the instructions of ng new PROJECT-NAME or others 

Before it ,when I seem to install a package about ng but I have forgot it's what.So who meet it as I said
Who can tell me how to resolve it ?
my environment: Ubuntu:14.04;nodejs:6.11;npm:3.10
when I type to  ng new PROJECT-NAME in the terminal I come into the interface such as the picure:
![screenshot from 2017-07-28 00 14 41](https://user-images.githubusercontent.com/26674689/28681133-0862192c-732b-11e7-8c0a-0c4c6581c3cf.png)

**Comment by filipesilva** [comment]
Your machine seems to have another binary called `ng` that seems to be a text editor, and when you run `ng new PROJECT-NAME` you run that instead of Angular CLI.

You can do `which ng` to figure out what you're actually running. Also ensure you have your environment correctly configured with the path to `npm` global modules (this article often helps due to permissions in Ubuntu https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory).
