### ISSUE TITLE
Not showing webpack compilation warnings

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#7213]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.3.0-rc.3
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/compiler: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/platform-browser-dynamic: 4.3.1
@angular/platform-server: 4.3.1
@angular/router: 4.3.1
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.3.0-rc.3
@angular/compiler-cli: 4.3.1
```

### Repro steps.
After upgrading to 1.3.0-rc.3 and doing some bad things, `ng serve` outputs:
```
webpack: Compiling...
webpack: Compiled with warnings.
```
But no warnings are printed 😞 

(I encountered the issue with [there changes][1], but any changes creating warnings should do.)

### The log given by the failure.
N/A

[1]: https://github.com/gkalpak/angular/commit/51f6dda138c9f1bba49b651e576f620d68b6a623

**Comment by gkalpak** [comment]
cc @filipesilva

**Comment by gkalpak** [comment]
(Hm...or maybe there are no warnings and the message is wrong. Not sure how to find out.)

**Comment by filipesilva** [comment]
There are errors. Might be just a circular dependency error, but it exists. I had similar trouble last week.

**Comment by gkalpak** [comment]
Yeah, they were circular dependency warnings. If there are errors too, the warnings are shown along with the errors. But if there are only warnings, nothing is shown.

**Comment by Matmo10** [comment]
@filipesilva @hansl  Could this be made configurable at all? 

I have lots of the fake errors stemming from https://github.com/angular/angular-cli/issues/2034, and I actually enjoyed having the warning output rather limited.

Not only did you guys bring back the first line of the warnings (how it use to be), but you also added the whole stack traces as well. So now I have a giant wall of stack traces every time I make a change.

**Comment by Vandivier** [comment]
Bump. I realize we don't want to expose webpack until 2.0, but silencing the warnings can be done without exposing webpack.

Also, what is the timeline for 2.0?

Lastly, this has some technical merit in addition to being a convenience: Right now I'm trying to debug an issue during init [which throws so many warnings](https://github.com/typeorm/typeorm/pull/1143) it pushes the error above the scrollable range for my CLI. The solution would be to use a logger, but because the err is happening in init I'm not currently able to use my logger. Totally my issue to work out but this feature would assist.
