### ISSUE TITLE
Generated javascript files make debugging difficult

### ISSUE THREAD

**Issue by diminutivesloop** [angular/angular-cli#7229]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/platform-server: 4.2.5
@angular/router: 4.2.5
@angular/upgrade: 4.2.5
@angular/cli: 1.2.0
@angular/language-service: 4.2.5
@ngtools/webpack: 1.5.0

### Repro steps.
1. Run app via `ng serve`.
2. Open Chrome dev tools.
3. Open **Go to source** panel (ctrl+p).
4. Try searching for an angular component.
=> Results are cluttered with various generated javascript files that are not usually relevant for debugging purposes. This makes fuzzy search for source files significantly less usable.
![aot-generated-files-devtools](https://user-images.githubusercontent.com/667716/28837266-1e7f2744-76ba-11e7-8e0f-ef71d2270fe5.PNG)

### Desired functionality.
Generated files should not be exposed when running the development server.

### Mention any other details that might be useful.
This issue appears to have been introduced in our project when we upgraded angular-cli from 1.0.0-beta.26 to 1.2.0.

**Comment by filipesilva** [comment]
So yeah, this happens. It happens because all those things really do exist and have sourcemaps.

I'm not sure how the situation can be improved though. Hiding some of the sourcemaps isn't a good idea IMHO. 

In your case it also does not have that you really do have a couple of different components that will match that fuzzy search, but even in simple app the situation is similar:
![image](https://user-images.githubusercontent.com/4172079/28868454-6f106c74-7771-11e7-9313-296dd88a6a8f.png)

I don't know if there is a solution for this. But will keep it open as a discussion.

**Comment by mgechev** [comment]
Do we have any ideas around this? The behavior looks correct to me, it'll also get less confusing when we introduce ivy (no ngfactories).

**Comment by filipesilva** [comment]
Yeah I think the real answer is that using Ivy (as is the default in CLI 9) makes this a non-issue.
