### ISSUE TITLE
add user defined barrels to system-config.ts 

### ISSUE THREAD

**Issue by spboyer** [angular/angular-cli#723]
In system-config.ts the barrel configuration is component specific and projects as if it is controlled only or could be altered by the cli pursuant the the comment in the file.
```
////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
```

As with the option for the user to define relative paths and packages above this line, we should be able to define custom barrels.

such as:

```
const mybarrels : string[] : ['app/materialdesign'];
```

and then have these merged in 

```
const cliSystemConfigPackages: any = {};
barrels.concat(mybarrels).forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});
```

alternatively add command to cli `ng barrel materialdesign` which adds the folder name to the `barrels[]`

@Brocco @johnpapa

**Comment by Brocco** [comment]
I agree it can be confusing, just not certain which approach would make the most sense. There's an internal module in the CLI which handles registering barrels, so implementing `ng barrel` would be relatively painless, but not sure how common the use case will be.

**Comment by hboylan** [comment]
+1

Just ran into this issue. Had to edit 2 files to add material design components:

Both ```angular-cli.json```
```json
  "packages": ["@angular2-material/core", "@angular2-material/button"],
```

And ```src/system-config.ts```
```typescript
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  '@angular2-material': 'vendor/@angular2-material'
};

/** User packages configuration. */
const packages: any = {
  '@angular2-material/core': { main: 'core' },
  '@angular2-material/button': { main: 'button' }
};
```

**Comment by hboylan** [comment]
Also ```angular-cli-build.js```
```javascript
      '@angular2-material/**/*.js'
```

**Comment by hansl** [comment]
The `angular-cli.json` does not have `packages` support right now. That part doesn't end up being used.

**Comment by yahyaKacem** [comment]
Hi, first thanks for this tool.
What about making generating components by default with barrels, unless a --no-barrels flag was provided?
this way we have two pattern of generating components/routes/pipes... with or without barrels, maybe later it could be added as a param in the .ember-cli file or angular-cli.json this will make adding barrels to the `system-config.ts` file automated by the cli no need for user defined barrels at least not for all new generated component, maybe for some cases.

**Comment by johnpapa** [comment]
why would you *not* want a barrel? its a convenience.

**Comment by yahyaKacem** [comment]
@johnpapa , I do want them, but I thought this tool doesn't generate barrels all the time, this is related to this issues #513 #585 #586.
My case is when I created created a custom class under the shared folder I didn't get barrels, like this:

    ng g class shared/helpers/url helper

I run that command after I had to create the shared/helpers folder manually I got under it only the 2 url.herlper.ts & url.herlper.spec.ts no index.ts file & in the shared/index.ts the url.helper.ts file was exported instead of the shared folder, so related to this issue I thought if the barrels generation became a convention for all generated folders (after adding the ability to make folders too) this would make it easier to manage the cli addition of barrels into the `system-config.ts` file and also remove the burden of adding them into a user defined barrels not that it is a bad idea to have user defined barrels variable in the `system-config.ts` file but I think it should not be used so much for adding barrels that could be inserted by the cli, what you think?

**Comment by filipesilva** [comment]
Made obsolete by #1455.
