### ISSUE TITLE
EPERM: operation not permitted, lstat 'C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\dist'

### ISSUE THREAD

**Issue by enochfonky** [angular/angular-cli#7272]
I reporting this, everything was working perfectly all of a sudden. I have this error when I run the ng serve.I am using Angular IDE

EPERM: operation not permitted, lstat 'C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\dist'
Error: EPERM: operation not permitted, lstat 'C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\dist'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at Object.lstatSync (C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.rimrafSync (C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\node_modules\fs-extra\lib\remove\rimraf.js:237:18)
    at Class.run (C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\node_modules\@angular\cli\tasks\serve.js:31:16)
    at check_port_1.checkPort.then.port (C:\Users\Enoch\Workspaces\Angular IDE 2017 CI\myangular\node_modules\@angular\cli\commands\serve.js:110:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by rajbdilip** [comment]
I have the exact same case. All of a sudden I started getting this error since yesterday. I have the following setup.

 - Node v6.9.1
 - NPM v3.10.8
 - Angular CLI v1.2.6

I'm using Angular IDE on Windows 7. However, I get the same error if I use NodeJS prompt too. This is probably not relevant but I don't' have admin rights.

**Comment by Brocco** [comment]
Seems like either permissions issue or dependencies issues.

- Delete `dist` folder and `node_modules`
- Run `npm install`
- retry `ng serve`

**Comment by itsSandeepNandey** [comment]
**Solution:**

To fix this issue I have to restart the machine.

I know , this is not the correct way but till we have not correct solution ,this will fix the issue.

**Comment by itsSandeepNandey** [comment]
**Possible Root Cause & Solution**:

While I was debugging the application in browser & tried to rebuild the solution , I received the same error.
Then I closed all the browser & folder ( dist ) and tried to rebuilt the solution.
And did not face the issue this time.
Possibly , when we try to build the solution while debugging or with app. opened in browser (Post debugging), files were not able to delete as it is being used by browser.

So, I would suggest to follow the above approach and give it a try.

**Comment by elshan** [comment]
Just do a system restart. But I know it's not the correct solution... for me it works

**Comment by mgechev** [comment]
Can you still reproduce the issue?

**Comment by mgechev** [comment]
Closing the issue due to inactivity. If the problem still exists in the latest version of the CLI, please open a new issue following the template and providing a minimal demo where we can reproduce it. Thanks! :-)
