### ISSUE TITLE
feat: support adding 'crossorigin' attribute

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#7301]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
@angular/cli: 1.3.0-rc.5
node: 6.11.0
os: win32 x64

### Desired functionality.
Add a build/serve option that adds `crossorigin="anonymous"` to generated script and style tags.
Adding this attribute will make the request without cookies which are probably an unnecessary overhead on these requests.

This feature can be used if there's no option to use a cookie-less domain.

**Comment by axelboc** [comment]
My app's assets are hosted on a CDN. I pass the CDN's URL with the `--deploy-url` option.

I think the lack of attribute `crossorigin` on the generated `script` tags means that I get a `ScriptError` any time an error is thrown in one of the bundles.

https://scotch.io/bar-talk/what-the-heck-is-script-error

**Comment by alan-agius4** [comment]
Hi, for this you can use the `subresource-integrity` flag which also enables the use of subresource integrity validation.

https://angular.io/cli/build

**Comment by axelboc** [comment]
Not sure how this relates to `subresource-integrity`.

**Comment by clydin** [comment]
The `crossorigin` attributes are added to scripts when the SRI option is enabled.  This allows for useful error messaging within the browser console.  The attribute controls the presence of error information for "classic" scripts (i.e., not `type="module"`).  No credentials should be sent if the attribute is not present ([spec reference](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attribute)) since the "missing default value" is no CORS which would cause a credential mode of "omit".
