### ISSUE TITLE
Improve docs/story for universal builds

### ISSUE THREAD

**Issue by BioPhoton** [angular/angular-cli#7388]
### Bug Report or Feature Request
```
- [X] documentation thing
```

### Versions.
@angular/cli: 1.3.0
node: 6.11.1
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4
@angular/platform-server: 4.3.4

### Repro steps.
I followed the Story about [universal rendering](https://github.com/angular/angular-cli/wiki/stories-universal-rendering).
It was all clear but i guess the last step [testing the whole thing](https://github.com/angular/angular-cli/wiki/stories-universal-rendering#testing-the-bundle) is not really good explained. 

Where to place the code, how to serve this and so on. I think this information would make it more complete and helpful.

### The log given by the failure.
Nothing

### Desired functionality.
Documentation on how to test it. => I want to see the rendered page (html)

### Mention any other details that might be useful.
No

**Comment by maxisam** [comment]
Also, is there any chance to add some documents for how to make universal to work with asp.net core?

**Comment by dockleryxk** [comment]
@maxisam does [this](https://github.com/angular/universal/tree/master/modules/ng-aspnetcore-engine) help at all? I know jack squat about asp.net, but I saw this earlier. Hopefully it helps!

**Comment by BioPhoton** [comment]
I guess i tiny script to run it with node ./universal-test.js would be enough to test it.

**Comment by maxisam** [comment]
@dockleryxk  thanks. 

However, I got error like 

Exception: Call to Node module failed with error: Prerendering timed out after 30000ms because the boot function in 'D:\Users\saml\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal/ClientApp/dist-server/main.bundle' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.

I kinda use https://github.com/MarkPieszak/aspnetcore-angular2-universal as a guide as well.

But I can't make it work. I wonder if anyone successfully makes CLI+universal+asp.net work.

**Comment by maxisam** [comment]
For future reference: Here is the repo https://github.com/maxisam/DotNetCoreNgCli/tree/master/dotNetCoreNgCli

**Comment by dockleryxk** [comment]
Would it be fitting to write a lazy loading section that references [this package](https://github.com/angular/universal/tree/master/modules/ng-module-map-ngfactory-loader) on Universal? I could definitely handle that.

**Comment by RicardoVaranda** [comment]
Hi @alxhub , I've submitted a PR to match your specifications, let me know if you have any suggestions on how to further improve it #7534

**Comment by CaerusKaru** [comment]
Should be closed by #7803

**Comment by tiaguinho** [comment]
@alxhub like @CaerusKaru says I think this should be closed.

**Comment by BioPhoton** [comment]
It's in the cli now... :-)
