### ISSUE TITLE
[Enhancement] --output-hashing=chunk

### ISSUE THREAD

**Issue by xouqoa** [angular/angular-cli#7431]
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions.
@angular/cli: 1.2.6
node: 7.7.1
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.2.6
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Desired functionality.

Due to the way our server side code is set up, we are unable to use the dist/index.html file generated during the build process. We use it locally for development purposes only. Consequently, we have output hashing turned off since trying to keep all the file names straight with an external file would be a nightmare.

We have recently run into an issue with browsers caching the chunk files, since they don't have the hash appended to them. Our normal JS files are loaded with a url parameter to keep them fresh, but we aren't able to do that with the chunk files (lazy loaded modules) as they are loaded via inline.bundle.js.

I ejected the webpack config file, and it looks like it would be possible to add an additional argument value (--output-hashing=chunk) so that it only applies the hash value to those files. I'm not sure what difficulties this would create outside of the webpack.config. There may be technical reasons this hasn't been done already, but I thought I'd ask just in case.  

I'm also open to other suggestions we could implement to prevent the browsers from being able to cache the chunk files.

**Comment by hansl** [comment]
We already support the `--output-hashing=bundles`. Doesn't that work for you?

**Comment by xouqoa** [comment]
No, unfortunately. We're using ColdFusion/Railo with an MVC framework, so we have to include the javascript files in that view manually. If we build the bundle files with the hashing, we have to update the view every time which is less than desirable. (Admittedly possible, but just a pain to make sure it is right.) There may be some way to script that update, but I haven't looked into that yet.

Since the chunks are loaded from inside the Angular app, we wouldn't have to worry about updating the view if they had the hash added.

Is there any way to override the function Angular is using to load the chunks? I was thinking maybe we could do something with an interceptor where we change the cache control settings on those files or something, but I haven't looked into it yet.

Maybe there's some other way I haven't thought of. This just came up today. :)

**Comment by kevinphelps** [comment]
Can your MVC views read the filesystem to determine the hashed filename? I have done this similar with .NET MVC Framework.

**Comment by IndianaHorrscht** [comment]
+1

**Comment by pnuzhdin** [comment]
We need it badly

**Comment by kjbetz** [comment]
Found this issue/request after searching and running into the same issue as @xouqoa describes.

It would be ideal to have just the chunks hashed.

@kevinphelps Do you have a sample I could look at?

**Comment by kjbetz** [comment]
I still think this would be a worthwhile enhancement.

But for ASP.NET Core users... here's the rather simple solution.

`<link rel="stylesheet" asp-href-include="~/dist/apps/yourapp/path/styles.*.css">`

`<script type="text/javascript" asp-src-include="~/dist/apps/yourapp/path/runtime.*.js">`
`<script type="text/javascript" asp-src-include="~/dist/apps/yourapp/path/polyfills.*.js">`
`<script type="text/javascript" asp-src-include="~/dist/apps/yourapp/path/main.*.js">`

http://michaco.net/blog/Angular4GettingHashedWebpackBundlesWorkingInASPNETCoreMVC

https://www.davepaquette.com/archive/2015/05/06/link-and-script-tag-helpers-in-mvc6.aspx

**Comment by pravesh364** [comment]
Is there any updated on it. I having the same problem.

**Comment by EvtK** [comment]
same here, I want to have my lazy loaded chunks to be hashed for cache busting, but not the main bundles, since they are addressed directly from an MVC rendering.

**Comment by LucasMenchi** [comment]
Same here!

**Comment by damsorian** [comment]
+1

**Comment by mark-tabit** [comment]
Anything new?

**Comment by dgp1130** [comment]
Discussed this within the tooling team today. It seems like the core desire is to use a custom `index.html` page without impacting the application's caching strategy.

Our take is that Angular generates a default index page which includes hashes for you. If you want to skip that and generate your own index page, you certainly can, however it necessarily requires solving the same problem and figuring out how to serve these files in a cacheable manner. The proper solution here will likely vary based on your exact use case and the server framework you're working within.

One approach is to turn off hashes altogether, another is to make your custom index page read the filesystem to find the hashes (see https://github.com/angular/angular-cli/issues/7431#issuecomment-400040277), and there are any number of other solutions in between.

The specific FR in this issue is for some option to express "Add hashes to lazy loaded chunks, but not the entry points because I need a hard coded reference to them." This is fairly nuanced and hard to communicate or document in a clear manner. It complicates caching further as well, since the entry points cannot be immutably cached but all lazy loaded chunks can, this likely necessitates treating the two sets of files with different caching strategies (or not immutably caching chunks, which means they really don't need hashes at all then). This approach is also just one possible solution to the real problem of using a custom index page without breaking caching. As a result, we don't think this is the ideal solution here.

Angular also isn't particularly unique here, adding hashes to filenames is a common pattern, and we do support dropping the hashes altogether if your use case is benefited by it. We feel that these approaches should give reasonable choices for server frameworks and other tools to work with, and if not, a FR to them would likely give a more intuitive and maintainable solution for everyone.
