### ISSUE TITLE
proxy config breaks debugging

### ISSUE THREAD

**Issue by quanterion** [angular/angular-cli#7465]
If I serve my app with proxy config like this:
ng serve --proxy-config my.proxy.json
```
{
  "/": {
    "target": "https://www.example.com/",
    "secure": false
  }
}
```

It works perfectly however debugging is not working anymore. I can't put breakpoints in VS Code. And I can't find my original TypeScript files if I search with Ctrl+P in Chrome Dev Tools.

I suspect that the proxy middleware should intercept all paths to code bundles, index.html and source maps requests, but fails to intercept the last ones and sends source maps requests to example.com instead.

PS: Angular=5.0.0-beta.3 ng-cli=1.3.0

**Comment by alexej-strelzow** [comment]
Interesting theory. I've noticed, that debugging in cli 1.2.4 is still working (I can find all the typescript files of my app with Ctrl + P) in chrome (V 59). But once I upgraded the cli to anything > 1.2.4 I cannot find those files anymore. I never thought that the proxy-config could be the trigger for that issue. I also tried to map the local file system to chrome (under settings - in chrome), but it did not change anything. This issue is actually a blocker for us (our company project) to upgrade to cli > 1.2.4. If I cannot debug properly, a newer version is no use. Please look into it!

**Comment by filipesilva** [comment]
Can you give me detailed instructions on how to see this? e.g. setup, everything. I'm on a windows machine and use chrome.

**Comment by quanterion** [comment]
I workaround the issue by using separate entries for each path instead of "/". Now with 1.5.0 it works perfectly.

**Comment by popica14** [comment]
Hi guys, is there a solution for the problem described in this thread? I am facing the same issue.
