### ISSUE TITLE
Can't import Quill editor

### ISSUE THREAD

**Issue by kuzyas** [angular/angular-cli#7526]
I'm trying to import quill and register additional module, but it imports undefined

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.0-rc.3
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.0-rc.3
@angular/compiler-cli: 4.3.4
@angular/language-service: 4.3.4

### Repro steps.

Add 
 "quill": "^1.3.1",
 "quill-image-resize-module": "^3.0.0",
 "ngx-quill": "^1.4.0".

.angular-cli
  "styles": [
        "styles.scss",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/quill/dist/quill.core.css",
        "../node_modules/quill/dist/quill.snow.css"
      ],
      "scripts": [
        "../node_modules/quill/dist/quill.js"
      ],

```typescript
import { ImageResize } from 'quill-image-resize-module';
import * as Quill from 'quill';
Quill.register('modules/imageResize', ImageResize);
```
### The log given by the failure.
![image](https://user-images.githubusercontent.com/17053017/29779984-e22a5a66-8c1c-11e7-886d-3f8213b00fc8.png)

### Desired functionality.
It should work like described on page
https://github.com/angular/angular-cli/wiki/stories-global-scripts

**Comment by J2D2Development** [comment]
We were having the same issue- got it working today by loading both scripts (base quill and quill-image-resize-module) in the angular-cli.json scripts array:

```
"scripts": [
        "../node_modules/quill/dist/quill.min.js",
        "../node_modules/quill-image-resize-module/image-resize.min.js"
 ],
```

Then in the component using Quill, don't import it as a module, just declare Quill as a global (so Typescript doesn't complain):

`declare const Quill: any;`

And you should be able to create  your instance of Quill with the Image Resize module.  One thing to note: there's a typo in the documentation for the image resize module: make sure it's camel case when you declare it in your options (otherwise, it won't be recognized):

```
modules: {
    toolbar: toolbarOptions,
    imageResize: {}
},
```

**Comment by filipesilva** [comment]
Thanks for sharing your solution @J2D2Development. There's a note about this behaviour in https://github.com/angular/angular-cli/wiki/stories-global-scripts#using-global-libraries-inside-your-app.
