### ISSUE TITLE
IE 10 throw unable to get property 'addEventListener' of undefined or null reference

### ISSUE THREAD

**Issue by pavinthan** [angular/angular-cli#7542]
I'm submitting a ...

bug report
Unable to get property 'addEventListener' of undefined or null reference

ag-grid-angular version: 12.0.0
Angular version: 4.3.6
Browser: [ IE 10 ]
Language: [all | TypeScript X.X | ES6/7 | ES5]

[Screenshot](https://ibb.co/nqj4XQ)

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by MatthewHerbst** [comment]
For anyone who finds this, here is a related issue and the fix (at least for myself and a few others): https://github.com/ag-grid/ag-grid/issues/1971
