### ISSUE TITLE
Adding angular-cli to existing project? On using ng init

### ISSUE THREAD

**Issue by jmb-mage** [angular/angular-cli#755]
_> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)_
  
Windows 10

_2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here._
angular-cli: 0.1.0
node: 4.2.1
os: win32 x64

_3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc._
Create an Angular 2 project without angular-cli, for example:
`git clone https://github.com/angular/quickstart.git quickstart`
`cd quickstart`
`npm install`
`npm install angular-cli`
`ng **????  -- how to add angular-cli to project at this point?**`

To make that project use angular-cli for commands like:
`ng generate route magazines`

_4. The log given by the failure. Normally this include a stack trace and some
   more information._

You have to be inside an angular-cli project in order to use the generate command.

_5. Mention any other details that might be useful._

Apologies if this is a duplicate, looking for answers in doc and SO.

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by pkamdem** [comment]
@jmb-mage 

```ng init ``` inside root folder and following instructions will do.

**Comment by jmb-mage** [comment]
In this particular case, there was a `/app` folder with the components, code in it.

After I run `ng init` there is a `/src/app` folder that does not have the same components in it as `/app`  Is this intentional?

**Comment by jmb-mage** [comment]
And `ng init` is missing from readme.md on this page: https://github.com/angular/angular-cli

**Comment by pkamdem** [comment]
@jmb-mage 

When running ``ng init`` you have the option to provide the source directory as ``ng init --source-dir [my_source_directory]``. Default is set to ``src``. 

This will create App components following Style guide conventions

Note that there may be some configuration to be done depending of the current project setup

**Comment by jmb-mage** [comment]
Following these steps, brand new:
git clone https://github.com/angular/quickstart.git test
cd test
npm install
npm start
npm install angular-cli --save
ng init --source-dir "app"

It made a /app/app folder for the angular-cli files.

And then I get this error:
Installing packages for tooling via npmmodule.js:339
    throw err;
    ^

Error: Cannot find module 'C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\lib/build.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.defineProperty.get (C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\lib\npm.js:196:15)
    at C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\lib\install.js:1163:17
    at asyncMap (C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\node_modules\slide\lib\async-map.js:27:18)
    at andBuildResolvedTree (C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\lib\install.js:761:9)
    at C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\lib\install.js:715:9
    at asyncMap (C:\dev\angular\test\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\node_modules\slide\lib\async-map.js:27:18)

---

In my other project, where I did `ng init` without the `--source-dir`, I had to run this:
`npm install ember-cli --save`
And now I am getting errors related to ember-cli when I try and run `ng-serve`

**Comment by pkamdem** [comment]
@jmb-mage 

Just complete these steps, and everything went ok.

``git clone https://github.com/angular/quickstart.git test``
``cd test``
``npm install``
``ng init --source-dir app`` _(Make sure to accept overwriting files and tweak after if need be. This will also install angular-cli as your dev dependencies)_
``npm start``

**Comment by jmb-mage** [comment]
thanks @pkamdem it seems there may have been a network error getting all the packages or something.  I did `npm uninstall angular-cli` and `npm install angular-cli` and it started working again.

**Comment by hansl** [comment]
Considering this fixed per last message from @jmb-mage

**Comment by Sri276286** [comment]
@pkamdem

Doing what you told , in app folder it's again creating one more app folder with same files as we have in quick-start project. How to fix this

**Comment by dvidsilva** [comment]
Also, if the current project has already some progress it will overwrite all that, is there a way to get the steps needed to get it to run in an existing project without overwriting the code I already have? I'm mostly interested because of the github pages deploy capabilities.

**Comment by rmcsharry** [comment]
@dvidsilva I wanted that too (easy github pages deploy) but I could not successfully add angular-cli to an existing project, too many config and file version changes.

However, to deploy to github pages I found a workaround without needing the cli:

1. create a new repository for your 'github pages deployment' - eg. <githubusername>.github.io
NOTE - it must start with your username followed by github.io
[this is because of assets like images that must be loaded from relative paths]
2. clone that repo in local folder myapp-prod (OUTSIDE of your existing app repo folder) - ensure this folder has the origin set to your repo created in (1)
3. build your project locally as prod (ie: ng build -prod)
4. copy the resulting DIST folder from (3) into (2)
5. cd into (2) and commit the changes (ie. the dist folder you just copied there)
6. then run: `git subtree push --prefix dist origin master`
7. on github, goto settings tab for the repo and in the github pages section, set source to master branch
8. browse to <githubusername>.github.io - your prod app is running there

Each time now, just run your prod build, copy the dist folder, commit it, push the subtree (steps 3-6 basically)

**Comment by phil123456** [comment]
D:\WORK\ANGULAR\catalog\backend>ng build
The package "angular-cli" has been renamed to "@angular/cli". The old package will be deprecated soon.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

You have to be inside an Angular CLI project in order to use the build command.

D:\WORK\ANGULAR\catalog\backend>ng init
The package "angular-cli" has been renamed to "@angular/cli". The old package will be deprecated soon.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

The specified command init is invalid. For available options, see `ng help`.

**Comment by nbora98** [comment]
Hi ,
Try the below solution may be it could help.
Step 1. Run this command on root folder [npm install -g angular -cli]
Step 2. Create new folder for your project [ng new project_folder_name]
Step 3. Enter inside that folder [cd project_folder_name]
Step 4. Run the project by this command [ng serve]
(Note: Now on localhost:4200, the demo project will run)
Step 5. Copy the '/src' folder of your existing project and replace with the '/src' of your newly created project from Project's root folder only.

Do let me know if you have any confusion.

**Comment by lagofvc** [comment]
@nbora98 , thanx for that tip!  That helped me out.   I had just gotten done updating an old project to @angular 4.0.1 and wanted to use `ng generate` commands.   I did as your steps indicate except for step 5.   Instead I did a diff on the top level files in both projects and then brought those changes from `new_project_name` and boiled down to these files : 

`angular-cli.json
 karma.conf.js
 package.json
 protractor.conf.js
 tslint.json`

**Comment by tanzeelrana** [comment]
When I run `ng init src` I get the following : 

![image](https://cloud.githubusercontent.com/assets/2520028/24575769/d770636a-167c-11e7-9737-994e67c713fa.png)

I am new to angular, can someone guide me how to deploy my app to an apache ?

**Comment by tanzeelrana** [comment]
`ng build -prod`

gives me : 

![image](https://cloud.githubusercontent.com/assets/2520028/24575795/2b5ea536-167d-11e7-82d3-58b05b71033e.png)

**Comment by daton89** [comment]
i've this problem...

➜  create git:(master) ✗ ng init
The specified command init is invalid. For available options, see `ng help`.
➜  create git:(master) ✗ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.3
node: 7.10.0
os: darwin x64
@angular/cli: 1.0.3

**Comment by y2ls02** [comment]
I have same issue as @daton89 

$ ng init
The specified command init is invalid. For available options, see `ng help`.
$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.3
node: 6.9.4
os: darwin x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/cli: 1.0.3
@angular/compiler-cli: error
@angular/platform-browser-dynamic: error
@angular/platform-server: error
@angular/router: error

**Comment by kevcodes** [comment]
@y2ls02  and @daton89 
Those commands no longer exiss.
see https://github.com/asnowwolf/angular-cli/blob/master/docs/documentation/stories/moving-into-the-cli.md

**Comment by shyamalm88** [comment]
Working with master

git clone https://github.com/angular/angular-cli.git
cd angular-cli
npm link
npm link is very similar to npm install -g except that instead of downloading the package from the repo, the just cloned angular-cli/ folder becomes the global package. Additionally, this repository publishes several packages and we use special logic to load all of them on development setups.

Any changes to the files in the angular-cli/ folder will immediately affect the global @angular/cli package, allowing you to quickly test any changes you make to the cli project.

Now you can use @angular/cli via the command line:

ng new foo
cd foo
npm link @angular/cli
ng serve
npm link @angular/cli is needed because by default the globally installed @angular/cli just loads the local @angular/cli from the project which was fetched remotely from npm. npm link @angular/cli symlinks the global @angular/cli package to the local @angular/cli package. Now the angular-cli you cloned before is in three places: The folder you cloned it into, npm's folder where it stores global packages and the Angular CLI project you just created.

You can also use ng new foo --link-cli to automatically link the @angular/cli package.

Please read the official npm-link documentation and the npm-link cheatsheet for more information.

To run the Angular CLI test suite use the node tests/run_e2e.js command. It can also receive a filename to only run that test (e.g. node tests/run_e2e.js tests/e2e/tests/build/dev-build.ts).

As part of the test procedure, all packages will be built and linked. You will need to re-run npm link to re-link the development Angular CLI environment after tests finish.

**Comment by FlameStriker** [comment]
hey can you please tell me how to add angular 2 component into existing java web application project.

**Comment by ORESoftware** [comment]
`ng init` no longer works

here is the solution

https://github.com/angular/angular-cli/issues/5431

**Comment by rawat-naresh** [comment]
you can use yarn package manager to install angular-cli or other dependencies to the existing project.

**Comment by brahimdev** [comment]
please i need help i have to run exiting angular cli project with client server so i'm stacking how to do that i test some command but i still don't have solution

**Comment by muneebshafiq** [comment]
For me `npm install` did the thing.

**Comment by Priyanka1234512345** [comment]
i m making a dist folder but inside dist folder one more folder is build by own which is present in my system how  to remove this.....?????

**Comment by Balarama888** [comment]
@nbora98 
Can you please explain the src folder I have "project>fuse>e2e-node_module-src-browserlistrc-editorconfig...."
How to open the existing project has enclosed in the given above folder.
Thanks for posting the solution to existing  project.

Step 5. Copy the '/src' folder of your existing project and replace with the '/src' of your newly created project from Project's root folder only.
