### ISSUE TITLE
Recommended package versions for current version?

### ISSUE THREAD

**Issue by BOb511** [angular/angular-cli#7652]
Ever since I started using Angular Cli I had the problem of figuring out what package versions are recommended.
For 1.0 there was documentation for it:
https://github.com/angular/angular-cli/wiki/stories-1.0-update#packagejson

After that (1.1., 1.2., 1.3.) I picked it from `packages/@angular/cli/blueprints`, which is now gone from 1.4., apparently because it was merely an old ember-cli thing:
https://github.com/angular/angular-cli/commit/4b58204b3b8b8d3d04fc57ac237cbf07d9a68d21#diff-f521eb20afff8ecf591da1d9a117cab8

What's the or even is there a proper way of keeping up-to-date with recommended package versions?

Thanks.

**Comment by grizzm0** [comment]
The schematics now lives under https://github.com/angular/devkit/tree/master/packages/schematics/angular

**Comment by Ploppy3** [comment]
Since the release of the CLI I have the same problem. I'm still looking for a proper way to update the dependencies.

Though, if you want to know what are the latest ones, considering your global CLI is up to date:
`ng new test-cli --skip-install` 
The _--skip-install_ parameter skips the installatoion of the node modules, therefore it's almost instantaneous, as well as deleting the test project once your done with its package.json.

**Comment by daniele-zurico** [comment]
Hey guys I've the same problem. All the time that a new version is relaease I need to generate a new project and copy paste what is changed.
I know that the update project has been removed because it was creating issues but could be appreciated if there's a sort of update file that describe what to change

**Comment by grizzm0** [comment]
There's really nothing to update. Your project is a working project. You control the versions in package.json yourself. The CLI itself works outside of your package.json with it's own versions.

**Comment by BOb511** [comment]
As mentioned in my initial post, for 1.0 there were recommended changes:  
https://github.com/angular/angular-cli/wiki/stories-1.0-update#packagejson

Since I rarely actually _need_ to update the packages I'd prefer to update the packages to the _recommended_ versions to keep them somewhat up-to-date.

Since I couldn't figure it out so far: where does `ng new` generate its package.json from?

**Comment by grizzm0** [comment]
@BOb511 I linked to that about 4 comments up.

**Comment by Ploppy3** [comment]
@grizzm0 Where do you see the versions of package.json in the page you linked ???

**Comment by grizzm0** [comment]
@Ploppy3 https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/package.json

**Comment by Ploppy3** [comment]
Why not give this url right away then?

**Comment by grizzm0** [comment]
Becuase I linked to the new location of the schematics. Including all generated files such as components, services, modules, guards, pipes etc.

**Comment by BOb511** [comment]
Sorry, I totally missed that.
Thanks!
