### ISSUE TITLE
[1.4.x] service path differs if generated with alias or not

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#7679]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.1
node: 8.4.0
os: darwin x64
@angular/animations: 5.0.0-beta.3
@angular/common: 5.0.0-beta.3
@angular/compiler: 5.0.0-beta.3
@angular/core: 5.0.0-beta.3
@angular/forms: 5.0.0-beta.3
@angular/platform-browser: 5.0.0-beta.3
@angular/platform-browser-dynamic: 5.0.0-beta.3
@angular/router: 5.0.0-beta.3
@angular/cli: 1.4.1
@angular/compiler-cli: 5.0.0-beta.3
@angular/language-service: 5.0.0-beta.3
typescript: 2.4.2

### Repro steps.
```
> ng g service race
create src/app/race.service.spec.ts (368 bytes)
create src/app/race.service.ts (111 bytes)
```
works as it used too, whereas using the alias:
```
> ng g s race
create src/app/race/race.service.spec.ts (368 bytes)
create src/app/race/race.service.ts (111 bytes)
```
generates the service inside a new directory.

### Desired functionality.
Both commands should have the same result

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
