### ISSUE TITLE
@ngtools/webpack doesn't work with providers coming from a preprocess-loader'ed file

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular-cli#7691]
This is a follow-up on #6701

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

`"@ngtools/webpack": "1.7.1"`

### Repro steps.

I've created a commit against `test-app-weird` showing the behavior:
https://github.com/Tragetaschen/angular-cli/commit/1cb1aeba117b65e4013c1a8c9c42386f6190fd15

Upon running webpack of the test app when `"DEBUG": false`, there are warnings:
```
WARNING in ./not/so/source/app/generated/app/app.component.ngfactory.ts
40:28-43 "export 'DebugService' (imported as 'i4') was not found in '../../app.services'

WARNING in ./not/so/source/app/generated/app/app.component.ngfactory.ts
40:45-60 "export 'DebugService' (imported as 'i4') was not found in '../../app.services'
```
The `View_AppComponent_Host_0` function references the service, while the actual `app.services` module doesn't have it.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
