### ISSUE TITLE
Use environment variables in index.html

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#7704]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Desired functionality.

Have the possibility to use environment variables in the index.html file

Currently I have google analytics code in the environment files to be able to have different id´s.
This results in some warnings:

"A Parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google-analytics.com/analytics.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details."

**Comment by x1c0** [comment]
I would also love to have this for configuring CSP meta-tag info depending on the environment, since angular does not work without 'unsafe-eval' in normal dev mode.

**Comment by bravik** [comment]
How about setting a html language tag `html lang="xx"` dynamicly basing on some variable.... Cause you have to build angular app as many times as a number of locales you support...

**Comment by alan-agius4** [comment]
Hi @mackelito, do you envision this to be something during runtime or build time?

**Comment by SchnWalter** [comment]
We use such a feature in some of our projects where we have the ability to change the environment variables after build, to do this, we have a `my-app-global.d.ts` definition file that defines a type which is available in both JS and TS files:
```ts
declare namespace MyApp {
  interface IEnvironmentConfiguration {
    apiUrl: string;
    // ...
  }
}

/**
 * NOTE: The global configuration variable should be consumed at runtime using:
 * <code>
 *   import { ENVIRONMENT } from `~app/config`;
 * </code>
 */
declare var MY_APP_ENVIRONMENT_CONFIGURATION: Readonly<MyApp.IEnvironmentConfiguration>;
```

And then we provide a default `src/environment/config.js` which is included in the build:
```js
// @ts-check
/** @type { Readonly<MyApp.IEnvironmentConfiguration> } */
window.MY_APP_ENVIRONMENT_CONFIGURATION = {
  apiUrl: 'https://example.com/api/v1'
  // ...
};
```
And we also have a script to generate a new `config.js` file after the build, using bash environment variables. And this file is included in the head tag of `index.html` like so:
```html
<script src="environment/config.js"></script>
```

And to avoid confusion, we renamed the old `environment*.ts` files to `build-flags*.ts`. And also renamed the `production` flag from the old `environment.prod.ts` to `devMode` since it's not directly related to the "production" configuration from `angular.json`, and after these changes our `main.ts` will look like this:
```
import { BUILD_FLAGS } from '~app/config';
if (!BUILD_FLAGS.devMode) {
  enableProdMode();
}
```

**Comment by alan-agius4** [comment]
Sounds to me that what you want is runtime configuration which in that case probably this is the same as https://github.com/angular/angular-cli/issues/7506 and partially related to https://github.com/angular/angular-cli/issues/3855

**Comment by alan-agius4** [comment]
lets keep tracking this in #3855
