### ISSUE TITLE
continued support for --no-aot flag with ng serve and ng build

### ISSUE THREAD

**Issue by jaa1982** [angular/angular-cli#7726]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Versions.
@angular/cli: 1.5.0 and beyond

### Desired functionality.

For reasons described in #5275, dynamic compilation of components is possible in JIT mode but not in AOT. In order to support dynamic compilation, per comment in link below, I have been using the --no-aot flag to JIT build for production. 

https://github.com/angular/angular-cli/issues/5275#issuecomment-287489334

With the upcoming plans for --aot by default in cli v.1.5.0 and beyond, I'd like to request/confirm continued support for the --no-aot flag for ng serve / ng build

### Mention any other details that might be useful.

Use case - for a commercial enterprise app scenario, where bandwidth is cheap and development resources hard to come by, dynamic component compilation allows non-developers to build pages that are more complex than a typical "dashboard" but without requirement for a full-on development environment or permissions to push a new build. Dynamic component templates and class definitions would instead be stored in a database and loaded as needed, without risk of breaking the build. Typical case might be 90% AOT (the "built-in components") and 10% JIT compiled ("custom components")

**Comment by hansl** [comment]
Hello @jaa1982,

AOT will not be by default in 1.x (1.5, 1.6 or beyond).  This is considered a major version change. Also note that there's no plan to remove the flag itself. So in 2.x (2.0, 2.1, 2.2 and above) you will still be able to build with `--aot=false`.

When we revisit this option to completely remove the `--aot` flag, there should be a way for you to dynamically compile components. As well, it will be at the very least in the CLI 3.0, since removing a flag is also a major version change.

Hope this clarifies the situation. Thanks!

Closing this as answered.
