### ISSUE TITLE
ng g c component-name Error: sourceDir option is required

### ISSUE THREAD

**Issue by jkbreunig** [angular/angular-cli#7765]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.4.2

### Repro steps.

ng g c component-name
or
ng g c component-name --source-dir source-dir
or 
ng g c component-name --app app

### The log given by the failure.

Error: sourceDir option is required.
sourceDir option is required.

### Desired functionality.

generate component

**Comment by Queatz** [comment]
Getting this as well.

**Comment by tazmanrising** [comment]
Getting this too

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
