### ISSUE TITLE
ngu-sw-manifest not populating the Routes

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular-cli#7806]
I am uisng this command in the following shell script to generate the manifest file.
```
#!/bin/bash
PATH=$PATH:$(npm bin)
set -x
# Production build
ng build --prod
# merge ngsw-manifest and copy to dist
./node_modules/.bin/ngu-sw-manifest --module src/app/app.routing.ts \
--out dist/ngsw-manifest.json
# Serve
cd dist
http-server
``` 
But My Generated manifest file is missing the routing configuration , is there any flag i need to append to it ?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
