### ISSUE TITLE
node-sass is in package.json Dependencies (in addition to optionalDependencies)

### ISSUE THREAD

**Issue by asafMasa** [angular/angular-cli#7813]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report

### Versions.
**1.4.3**

### Repro steps.
npm install with no sass environment (local sinopea storage)

### The log given by the failure.
install fail's

### Desired functionality.
cli installed

### Mention any other details that might be useful.

                                "webpack-merge": "^4.1.0",
				"zone.js": "^0.8.14",
				**"node-sass": "^4.3.0"**  --> why?
			},
			"optionalDependencies": {
				"node-sass": "^4.3.0"
			},

**Comment by clydin** [comment]
Neither the [latest stable release (1.4.3)](https://github.com/angular/angular-cli/blob/66faea66fd401ec2939152a40da95175c90a7896/packages/%40angular/cli/package.json) nor [master](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/package.json) have `node-sass` as a non-optional dependency.  Can you provide a link to the `package.json` you are referencing?

**Comment by asafMasa** [comment]
I don't know how, but i've just re-installed latest CLI and in my pakage.json the node-sass is inside "dependencies" section (after npm cache clean/clear), i'm also trying to solve this mystery...

**Comment by asafMasa** [comment]
ok ithink it's in the NPM package.json but not in the cli-1.4.3.tgz file.... thats weird

**Comment by filipesilva** [comment]
This might be something with your proxy perhaps? Looking over https://unpkg.com/@angular/cli@1.4.3/package.json there is no `node-sass` in dependencies there. 

It might also be some rewriting that `npm` itself does after install, since the `package.json` you show has a bunch of fields starting with underscore, which I know npm adds itself. 

Either way, you can force the optional dependency to not be installed via the `--no-optional` flag on npm install.
