### ISSUE TITLE
add option to parameterize LicenseWebpackPlugin

### ISSUE THREAD

**Issue by tahubu** [angular/angular-cli#7819]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
I think, it would be nice to set the `pattern` attribute of the LicenseWebpackPlugin plugin in the .angular-cli.json file. Here is an example:
```json
{
  "defaults": {
    "build": {
      "license": {
        "pattern":  "^(.*)$",
        "unacceptablePattern": "^(GPL.*)$",
        "abortOnUnacceptableLicense": true,
        "includePackagesWithoutLicense": true
      }
    }
  }
}
```
With this option we do not limit our to show only the `(MIT|ISC|BSD.*)` licenses and packages in the 3rdpartylicenses.txt file.

**Comment by filipesilva** [comment]
I don't think exposing the license regex is the best way to approach this issue. The plugin we use might change for instance, and those options no longer work. It would be better to just automatically extract all licenses IMHO.

**Comment by tamascsaba** [comment]
I think license export is not the most important functionality, the most used (for me) is unacceptablePattern. In enterprise environment we can not use GPL license (GPL require same license in your product).

**Comment by tamascsaba** [comment]
hi @filipesilva @Brocco, What do you think about GPL license ignore feature?
It is important for us :)

**Comment by tamascsaba** [comment]
@filipesilva, @Brocco would you like merge this pull request?

**Comment by filipesilva** [comment]
@tamascsaba I think what you need is something difference... You can't use some licenses in your organization, right?

But the way you're trying to detect licenses if through the license comments included in the output bundles. You only get licenses there that included license strings in the source code. 

That means that some packages, that don't include license comments in the source code, can have invalid licenses for you.

Instead you should check the licenses in the packages themselves to determine whether or not they are valid. We need to do that for the CLI itself. There's a script to check licenses here: https://github.com/angular/angular-cli/blob/master/scripts/test-licenses.js.

My advice for you is to adapt this script to your project. In your case you probably don't want to check all dependencies though, since you care about the licenses used in packages in the build but not in the tooling.

**Comment by alan-agius4** [comment]
@tamascsaba, thanks for this feature request, but it's outside of the scope of the Angular CLI. 

If you need to customize a Webpack plugin, you can do so by using [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus). While, we do allow customizing your build pipeline via 3rd party builders, we don't support this.
