### ISSUE TITLE
[Feature] Add a new application inside existing one

### ISSUE THREAD

**Issue by kevinvavelin** [angular/angular-cli#7839]
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
```

### Versions.
@angular/cli: 1.4.3
node: 8.1.4
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.
Run ng new inside an existing project

### The log given by the failure.
You cannot use the new command inside an Angular CLI project.

### Desired functionality.
Having the possibility to create another application inside an existing one. Maybe create a ng add function which will add necessary json config to .angular-cli.json

**Comment by lacolaco** [comment]
I also want something like `ng generate app ssr --platform server` to add multiple apps.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

See: https://angular.io/cli/generate
