### ISSUE TITLE
how can u use it right

### ISSUE THREAD

**Issue by Maybrittnelson** [angular/angular-cli#7864]
i can't use it right 
![image](https://user-images.githubusercontent.com/20365012/30946559-58bdd180-a437-11e7-81e3-77ed31dddbd2.png)

but u can do this right
https://github.com/angular/angular-cli/blob/master/tools/publish/src/changelog.ts#L12

so how can u do this right

**Comment by textbook** [comment]
This is **not** an Angular CLI problem. You can see how *"u use it right"* exactly where you've linked to.

**Comment by Maybrittnelson** [comment]
@textbook sry i can't find it, fs is part of node, right. also i want to know how import fs like angular-cli

**Comment by filipesilva** [comment]
Like @textbook said, this isn't a Angular CLI question at all so I'm closing it.

When you're writing node applications in typescript, you can import `fs` by doing `import * as fs from 'fs';` (note the `* as fs` bit). 

This will not work inside Angular applications however, because Angular applications run on the browser and not on node. `fs` is not available on the browser.
