### ISSUE TITLE
Move package.json to /dist 

### ISSUE THREAD

**Issue by gretschann** [angular/angular-cli#7881]
Extended .angular-cli.json by 

```"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico",
        "../package.json"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ]
```

and then run `ng build` the expected behaviour that the package.json is moving to /dist directory

what is wrong?

@angular/cli: 1.4.3

**Comment by Brocco** [comment]
What is your use case in wanting to move a configuration file into the build output directory?

**Comment by mspe044** [comment]
This would be nice when building AOT feature modules. I currently copy my package.json of my feature module into the aot output directory of my feature module so that the package.json of my main angular app can use  "file:../featureModule/dist/aot" to depend on just the aot output of that feature module rather than "file:../featureModule" which is a whole can of worms due to the feature modules node_modules sub directory.

**Comment by gretschann** [comment]
> What is your use case in wanting to move a configuration file into the build output directory?

Our deploy script from git to server needed package.json. So I got our backend developers to change their scripts
