### ISSUE TITLE
build optimizer flag only reduces app size 0.1% max

### ISSUE THREAD

**Issue by m4mbart** [angular/angular-cli#7914]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting (though not sure it is a bug)
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.4
node: 6.10.3
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.4.4
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
typescript: 2.3.4

### Repro steps.
I ran these commands and compared the output:
ng build --prod --build-optimizer --aot false --env=dev-nl --sm false --base-href="/app/"
ng build --prod --aot false --env=dev-nl --sm false --base-href="/app/"

### Command outputs:
![optimized](https://user-images.githubusercontent.com/11663618/31120764-f79056d2-a835-11e7-83a4-c37f741acec5.png)
![not-optimized](https://user-images.githubusercontent.com/11663618/31120767-fbccb498-a835-11e7-80d8-b7e11a792507.png)

### Desired functionality.
angular.io apparantly reduced there output size by 50%. I do not expect results anywhere near that size. But I would have thought to gain a little more then 0.1%.
What do you think about this?

**Comment by m4mbart** [comment]
Oh my.. noticing --aot false just now, as I am first testing this functionality on the Dev environment. Will be back with new results soon...

**Comment by m4mbart** [comment]
Ok, with AOT the new results.

### Commands
ng build --prod --env=dev-nl --sm false --base-href="/app/"
ng build --prod --build-optimizer --env=dev-nl --sm false --base-href="/app/"

### Outputs
![not-optimized](https://user-images.githubusercontent.com/11663618/31123224-4bb5b8ca-a83f-11e7-819f-9197005f021b.png)
![optimized](https://user-images.githubusercontent.com/11663618/31123230-4f9508ce-a83f-11e7-9759-94c7447e720d.png)

**Comment by clydin** [comment]
The build optimizer is designed to remove unused code with the primary target being vendor libraries (angular, etc.).  However, the more of the vendor libraries the application uses the less the build optimizer can do.  Also, as an application grows larger the ratio of vendor code to application code moves toward application code; making the potential savings percentage decrease as the ratio shifts toward the application.

In general, rather than the total size of the application, the more important metric is the size of the files on the critical path.  These affect the first render time of the application and in this case they would be `inline`, `polyfills`, `main`, and `styles`.  A decrease here will lower the wait time a user will experience before using the application.  This is in contrast to the lazy loaded bundles which can be prefetched in the background while the user is interacting with the application.

**Comment by m4mbart** [comment]
Ah thanks for the explanation., I was not aware that the build-optimizer was mainly intended for libraries and not actual application code. Although it makes sense, because all code we write should be in use and not stripped away like library code. I Guess the application/library ratio of our codebase is the reason for the small gain.
