### ISSUE TITLE
Add possibility to exclude "config file" of the application

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#7970]
### Type of issue
 [ x] feature request

### Desired functionality.
Possibility to exclude application "config" from package - make it standalone - requested before the start of the application. 

When you build your application for several environments and you want to make it from the same codebase, you HAVE to build ALL packages in the same time - because of "genial" NPM semantic versioning, you cannot risk the build of the same version in 2 different times (because of not the same External NPM modules).

It would be nice to have a possiblity to exclude "config.js" file from the package and generate it as a standalone CONFIG file - so you can only change for example URLs to your servers and so on in only 1 file and you dont have to rebuild entire solution. 

### Mention any other details that might be useful.
Similar functionality like Web.config in ASP .NET applications.
Ofc you can have "static" json file, with configuration and load it before start of the application, but it should be more systematic...

**Comment by tomastrajan** [comment]
Do I understand correctly that this means that you want to preserve `environment.<env>.ts` as a standalone file (what you call `config.js`) so that you can adjust values independently of build?

Thoughts:
* what about cache busting, file content is hashed initially for prod build but when you manually change it later you would have to rehash it yourself or employ different versioning scheme so that you prevent issues with browser caching 
* used with new `ng build` flag, something like `--external-env` or `--extract-env`

**Comment by montella1507** [comment]
@tomastrajan  the main purpose of this functionality is because you want EXACTLY the same build for several environments - dev, test, preprod, prod,..  Every build takes in average project 10-20mins so it takes like 2 hours only to build 6 packages, which are definitely the same except 3 variables (apiURL, redirectURL etc.)

So it is littlebit nonsense for me to build 6x 20mins the same package only with different URLs.

So your "what about cache busting,..." case doesn't take a place here in most often scenario.

And of course.. If you want your devops to change variable in your config file, he would be able to change hash in html too.

**Comment by filipesilva** [comment]
I'm pretty sure what you're asking is the same as https://github.com/angular/angular-cli/issues/3855. Please let me know if that's not the case.
