### ISSUE TITLE
Not working sourcemap + karma

### ISSUE THREAD

**Issue by acopalipsis** [angular/angular-cli#7987]
If you write in the project `console.log('...')`, the browser shows `... context.js:0`
Why sourcemap not working? Karma exist karma-sourcemap-loader, why are You not using it?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by acopalipsis** [comment]
@filipesilva Are you kidding me? If the creators of cli have never written tests with its application, then I will not use this shit and I will not advise others. Information is scarce ... NPM TEST and write a test with output to the console. Or do you want something I describe + its solution? Is it too difficult for you to do it?

**Comment by filipesilva** [comment]
Heya, it seems that the answer I gave has upset you. I'm sorry about that. But it really is important to fill in the issue template. The link in my response explains why.

> We want to fix all the issues as soon as possible, but before fixing a bug we need to reproduce and confirm it. In order to reproduce bugs we will systematically ask you to provide a minimal reproduction scenario using ng new repro-app. Having a reproducible scenario gives us wealth of important information without going back & forth to you with additional questions like:
> 
> version of Angular CLI used
> .angular-cli.json configuration
> 3rd-party libraries and their versions
> and most importantly - a use-case that fails

I understand the problem you are describing and it's something that I've worked on a lot in Angular CLI. But if you don't provide important details like the CLI version you're using, and how you're getting that result, I won't be able to zone in on the problem.

For instance, it's not the first time we've had problems with sourcemaps on karma. This has happened in the past with older versions. Maybe you're using an older version of the CLI where that problem was known, and it's enough to update to fix it. Or maybe the command you're using includes `--sm=false` - that disables the sourcemaps. Have you tried pressing the debug button on karma? Often that gives you much better logs. Maybe you're not using chrome but instead phantomjs, which has known issues. Maybe the problem you are experiencing is known and there's an issue opened for it already. It's hard to tell because you ignored the issue template, so I have to guess all these things. 

So without that information I'd have to spend a lot of hours trying out all combinations of these things to try and get to the problem you're having. but it would have been really fast if you had taken a few minutes to fill in the issue template.

Regarding `karma-sourcemap-loader`, we can't use it because of custom bundle loading we have in our custom karma plugin (https://github.com/angular/angular-cli/pull/6160), which improvement the rebuild speed dramatically. We're talking about very significant rebuild speed improvements, 15x to 30x faster, so it was worth it to make a custom setup. Instead we use https://github.com/tschaub/karma-source-map-support.
