### ISSUE TITLE
Server compiles just by right clicking a file in Windows Explorer

### ISSUE THREAD

**Issue by gaurawerma** [angular/angular-cli#8009]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.5
node: 6.11.3
os: win32 x64

### Repro steps.
I can reproduce this everytime by launching the skeleton app or any existing app by running the following commands

ng new my-first-app
cd my-first-app
ng serve --open

Now when the browser is loaded and the application is up and showing in the UI, I just go to the src folder of the app in windows explorer and just right click any file OR open the file in notepad.

The compiler starts buiding the project in loop (sometimes forever) and the UI keeps reloading

### The log given by the failure.
This is the command prompt log
[log.txt](https://github.com/angular/angular-cli/files/1375965/log.txt)

### Desired functionality.
The compiler should not trigger just by opening the file or right clicking the file in windows explorer

**Comment by gaurawerma** [comment]
I realized this behavior is only when the source code is on a network path (mapped network drive)

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
