### ISSUE TITLE
Unable load local json files using http get service with new angular-cli 1.4.5 version  ?

### ISSUE THREAD

**Issue by soumya-synaptech** [angular/angular-cli#8019]
with angular cli -1.0.0 there is no issue to load local json files
Yesturday i updated my cli version 1.4.5 , with that it's unabled to load local json files
getting 404 err0r in console

I tried many ways, even i put the json files in to assets, put the folder path into cli assets array 
even it's not working for me

**Comment by filipesilva** [comment]
Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
