### ISSUE TITLE
1.5.0's new --bundle-dependencies=all causes build warnings out of the box

### ISSUE THREAD

**Issue by SteveSandersonMS** [angular/angular-cli#8035]
Firstly, thanks again to @hansl for implementing `--bundle-dependencies`.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.5.0-rc.0

### Repro steps.

* `npm install -g @angular/cli@1.5.0-rc.0`
* `ng new MyApp`
* `cd MyApp`
* Open your code editor, and modify `.angular-cli.json` to add `"platform": "server"` to the config for the app.
* `ng build --prod --bundle-dependencies=all`

Expected: Build completes without warnings/errors

Actual:

```
WARNING in ./node_modules/@angular/core/bundles/core.umd.js
5691:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (dir\MyApp\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (dir\MyApp\node_modules\webpack\lib\Compilation.js:701:24)
```

... plus many more lines of warnings.

### Desired functionality.

Builds without errors/warnings in the default case for `platform: server` and `--bundle-dependencies=all`.

### Mention any other details that might be useful.

In `@angular/cli` 1.4.x, it was possible to make fully-bundled server builds work without errors by modifying the `node_modules/@angular/cli/models/webpack-configs/` files in two ways:

1. By changing `server.js` to set `externals` to an empty array
2. By changing `production.js` so that `UglifyJsPlugin` was not added to the plugins array for server builds.

However, in 1.5.0-rc.0, the `Critical dependency: the request of a dependency is an expression` warnings still happen regardless of `UglifyJsPlugin`. So something else must have changed in 1.5.0 to trigger these additional warnings.

**Comment by irowbin** [comment]
I am also getting this warning as well after I updated to `Angular v5`.  No warning when I downgrade `Angular v4xx` but, After v5 I am seeing this warning.

**Comment by muradm** [comment]
+1

**Comment by chamikasandamal** [comment]
Getting this issue in `@angular/cli@1.6.0` as well

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by speige** [comment]
+1

**Comment by lankaapura** [comment]
🔔

**Comment by speige** [comment]
In my case I get the same "Critical dependency: the request of a dependency is an expression". However, I simply ignore it & everything seems to work fine. I haven't noticed any bugs/issues caused by it in production.

I have --bundle-dependencies=all turned on, latest build of angular 5, & I use serverSideRendering/universal (using a .net core backend) in my app without copying node_modules to my production server.

**Comment by mikila85** [comment]
+1

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
