### ISSUE TITLE
be able to configure url-loader limit

### ISSUE THREAD

**Issue by jon301** [angular/angular-cli#8088]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.

@angular/cli: 1.4.3 (e)
node: 7.7.1
os: linux x64
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.5
@angular/animations: 4.4.5
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/router: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4

### Desired functionality.

The default behavior of url-loader in the Angular CLI is to inline files as data url if file size is greater than 10000 bytes

It would be nice if this value could be configured (without ejecting webpack config)

**Comment by clydin** [comment]
The current value is an extremely common value for the option.  Also the value is the upper threshold and only files with a size less than the value will be inlined not greater.

If there is any information or research suggesting a different value would be more optimal than the current setting could potentially be changed.

Also, in regards to providing full configurability of the value, could you provide an example of what you’re attempting or a general usecase that would necessitate the additional capability?

**Comment by jon301** [comment]
Basically I have some CSS selectors with background images :

```
.thing-red {
    background-image: url('/assets/thing-red.png');
}
.thing-blue {
    background-image: url('/assets/thing-blue.png');
}
```

When toggling class names from `.thing-red` to `thing-blue`, there is a loading time which is not very good for our user experience, and I'd prefer not have to use a PNG sprite.

Thanks for your help.

**Comment by clydin** [comment]
Inlining large assets will essentially just move the bad user experience rather than eliminate it; albeit in this case with a somewhat less bad user experience (longer loading vs visual degradation).  The images, if not already, should be optimized (imagemin for instance) and using several different image resolutions based on chosen breakpoints is typically effective.  And more generally, make sure that the resolution of the image fits its intended purpose (e.g., background image for the entire window vs a button).

Something else to consider is to add pre-fetch hints in `index.html` for the assets if they are used early/frequently.  This will allow the browser to be aware of them sooner and fetch/cache them once critical assets are available.  For a more comprehensive background asset caching capability (as well as other features), angular's service worker may be of interest as well.

**Comment by jon301** [comment]
Thanks @clydin for your help
I went for custom preloading strategy coupled with a service worker, worked like a charm :)

I'm closing this.
