### ISSUE TITLE
Root Component prefix and other Component prefixes should be consistent and pass ng lint

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#824]
We need to think how this should work. Consistency is key, IMO

When I generate a new app and create components, the prefixes are not consistent and therefore `ng lint` barks that we have inconsistent prefixes.

```
ng new force
cd force
ng g c foo
ng g c bar
```

We now have 
- `ForceAppComponent` with a selector of `force-app`
- `FooComponent` with a selector of `app-foo`
- `BarComponent` with a selector of `app-bar`

Then we add an ng lint rule in `tslint.json` like this (so we can follow the guide)

```
    "component-selector-prefix": [
      true,
      "app"
    ],
```

If we run `ng lint` we hear

```
$ ng lint
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

> force@0.0.0 lint /Users/john/_play/tmp/force
> tslint "src/**/*.ts"

src/app/bar/bar.component.spec.ts[38, 13]: The selector of the component "BarComponentTestController" should have prefix "app", however its value is "test".
src/app/foo/foo.component.spec.ts[38, 13]: The selector of the component "FooComponentTestController" should have prefix "app", however its value is "test".
src/app/force.component.ts[5, 13]: The selector of the component "ForceAppComponent" should have prefix "app", however its value is "force-app".
```

cc @mgechev @Brocco  @wardbell

**Comment by PascalPrecht** [comment]
cc @cburgdorf

**Comment by Brocco** [comment]
This conversation has already been started and the current solutions being proposed are:

1. Change the app component's selector to use a prefix of `app` instead of a suffix. So the root/app component would end up being `app-force` in based upon the above example

1. Slight variation of prefixing a discrete value of `app` would be to use the optional `--prefix` argument's value to prepend to the root component's selector

1. Leave the suffix of `app` as is and also prefix with the configured `--prefix` value (`app` by default). The resulting app component's selector could end up being `app-force-app`.

1. Modify [codelyzer](https://github.com/mgechev/codelyzer) to ignore/not check the root component's selector. In this case the selector for the app component could remain `force-app`

**Comment by filipesilva** [comment]
Obsolete issue, implemented as of now.

**Comment by mgechev** [comment]
FYI codelyzer now supports multiple prefixes https://github.com/mgechev/codelyzer/commit/91c952225c496e0ec3c6a0d4043be1fc99dd203a.

**Comment by filipesilva** [comment]
@mgechev sweet! Could you make a PR adding the prefix rule?

**Comment by mgechev** [comment]
@filipesilva I'll do that as soon as I get a chance.
