### ISSUE TITLE
Angular cli 1.5  ng serve, ng build command not working and is Fustrating can't  we build angular 5 apps with out the cli? and just config webpac?

### ISSUE THREAD

**Issue by alfredobialo** [angular/angular-cli#8293]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by baruchvlz** [comment]
What errors are you getting?

**Comment by bmayen** [comment]
Angular 5 has no dependency on the CLI. You are free to set up your own Webpack (or SystemJS or whatever) configs.

**Comment by deebloo** [comment]
@alfredobialo if you fill out the issue template with the issue we are getting perhaps we can help your rectify the issue or identify if there is a bug in the cli itself

**Comment by filipesilva** [comment]
Like @bmayen said you can use whatever build system you want. It really is up to you. Using the CLI is frequently easier and that's why we made it. 

I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening. That way you'll at least give a chance to help you.
