### ISSUE TITLE
Error while installing angular material 2

### ISSUE THREAD

**Issue by paramsinghvc** [angular/angular-cli#832]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.4
node: 6.0.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Nothing

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`Param-Singh:Youtube param$ npm install --save @angular2-material/core @angular2-material/checkbox
(node:26890) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
npm WARN @angular2-material/checkbox@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-messages@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-mocks@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-route@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-sanitize@>=1.3 <1.6 but none was installed.`

5. Mention any other details that might be useful.

I'm trying to use ng 2 material with a project created with angular cli but it complains about some versions of angular issue. how can I use it??
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by JonCubed** [comment]
they are all peer dependency warnings, you can safely ignore them

**Comment by paramsinghvc** [comment]
It can't be ignored, it doesn't install material 2 in my app.

**Comment by JonCubed** [comment]
If that is the only error, I think it will be installing you should check your node_modules folder for @angular2-material folder.

If it is there but your not seeing it in your vendor folder then make sure you update angular-cli-build.js to include it
```
'@angular2-material/**/*.js',
```

**Comment by filipesilva** [comment]
This issue is obsolete now, I believe. If this is not the case tell me so I can reopen it.

**Comment by dguthrie10** [comment]
I don't understand why this would be closed....someone out there has to be seeing what I am seeing. It is August 21, 2016 - Referring to https://github.com/angular/material2/blob/master/GETTING_STARTED.md

 I installed the angular-cli as directed:
 npm install -g angular-cli

I saw some of the same warnings, but it seemed to install anyway.
Created the project as directed:

ng new my-project

Created project just fine.

Attempted to git the material files:

npm install --save @angular2-material/core @angular2-material/button @angular2-material/card

Went completely to pieces at that point.....I have pasted the results below.

Why does this have to be such a chore? Been trying to get Angular2/Typescript/VS2015/SPA/WebApi/Material configured to JUST DO SOMETHING for months now and (primarily due to Microsoft finally getting their stuff sort of together) finally got all but Angular2 Material working. But can't get past this to save my life. After 30 years developing software am I really that stupid? I hope so. Can somebody please enlighten me??? Thanks.

For brevity, this starts about 3/4 of the way through the cli installation....

├── tmp@0.0.28
├── mkdirp@0.5.1
├── har-validator@2.0.6
├── optionator@0.8.1 (wordwrap@1.0.0)
├── findup@0.1.5 (commander@2.1.0)
├── lodash.clonedeep@3.0.2 (lodash._baseclone@3.3.0)
├── hawk@3.1.3
├── socket.io-parser@2.2.6 (json3@3.3.2)
├── babylon@5.8.38
├── touch@1.0.0 (nopt@1.0.10)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── optimist@0.6.1
├── iconv-lite@0.4.13
├── istextorbinary@2.1.0
├── argparse@1.0.7
├── es6-map@0.1.4
├── conventional-changelog-writer@1.4.1
├── engine.io-parser@1.2.4 (has-binary@0.1.6)
├── chalk@1.1.3 (has-ansi@2.0.0, ansi-styles@2.2.1, supports-color@2.0.0, ansi-r
egex@2.0.0, strip-ansi@3.0.1)
├── diff@2.2.3
├── cli-usage@0.1.2 (minimist@0.2.0)
├── meow@3.7.0 (minimist@1.2.0)
├── any-promise@1.3.0
├── fileset@0.2.1 (minimatch@2.0.10, glob@5.0.15)
├── json-schema@0.2.2
├── broccoli@1.0.0-beta.7
├── rewire@2.5.2
├── agent-base@2.0.1 (semver@5.0.3)
├── JSONStream@1.1.3
├── fs-extra@0.30.0
├── engine.io@1.6.11 (accepts@1.1.4, mime-types@2.0.14, mime-db@1.12.0, negotiat
or@0.4.9)
├── detective@4.3.1
├── cli-table@0.3.1 (colors@1.0.3)
├── inquirer@0.12.0 (readline2@1.0.1, strip-ansi@3.0.1, ansi-regex@2.0.0)
├── rsvp@3.2.1
├── normalize-package-data@2.3.5
├── temp@0.8.3 (rimraf@2.2.8)
├── es6-set@0.1.4
├── socket.io-adapter@0.4.0 (socket.io-parser@2.2.2)
├── babel-template@6.9.0 (babylon@6.8.4)
├── esniff@1.0.0
├── express@4.14.0 (finalhandler@0.5.0)
├── commoner@0.10.4 (glob@5.0.15)
├── shelljs@0.7.0
├── regexpu@1.3.0 (esprima@2.7.2)
├── quick-temp@0.1.5 (rimraf@2.2.8, underscore.string@2.3.3)
├── yam@0.0.18 (lodash.isplainobject@3.2.0, lodash.keysin@3.0.8, lodash.merge@3.
3.2, graceful-fs@3.0.8, fs-extra@0.16.5)
├── is-my-json-valid@2.13.1
├── sshpk@1.8.3 (assert-plus@1.0.0)
├── acorn@1.2.2
├── cardinal@0.5.0
├── bluebird@2.10.2
├── broccoli-concat@2.2.1
├── engine.io-client@1.6.11 (ws@1.0.1)
├── are-we-there-yet@1.1.2 (isarray@1.0.0, readable-stream@2.1.4)
├── escope@3.6.0
├── tiny-lr@0.2.1 (qs@5.1.0)
├── through2@2.0.1 (isarray@1.0.0, readable-stream@2.0.6)
├── redeyed@0.5.0 (esprima-fb@12001.1.0-dev-harmony-fb)
├── detect-indent@3.0.1 (minimist@1.2.0)
├── js-yaml@3.6.1 (esprima@2.7.2)
├── recast@0.10.33 (source-map@0.5.6)
├── when@3.7.7
├── rollup@0.30.0 (source-map-support@0.4.1, source-map@0.1.32)
├── body-parser@1.14.2 (http-errors@1.3.1, bytes@2.2.0, qs@5.2.0)
├── acorn-jsx@3.0.1 (acorn@3.2.0)
├── ember-cli-broccoli@0.16.9 (broccoli-slow-trees@1.1.0, glob@5.0.15, broccoli-
kitchen-sink-helpers@0.2.9)
├── consolidate@0.14.1 (bluebird@3.4.1)
├── broccoli-filter@0.1.14 (walk-sync@0.1.3, mkdirp@0.3.5, glob@5.0.15, broccoli
-kitchen-sink-helpers@0.2.9)
├── markdown-it@4.3.0
├── broccoli-kitchen-sink-helpers@0.3.1 (glob@5.0.15)
├── bl@1.1.2 (isarray@1.0.0, readable-stream@2.0.6)
├── babel-traverse@6.10.4 (globals@8.18.0, babylon@6.8.4)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── resolve@1.1.7
├── fast-sourcemap-concat@1.0.0 (chalk@0.5.1)
├── hash-for-dep@1.0.2 (broccoli-kitchen-sink-helpers@0.2.9, glob@5.0.15)
├── popsicle@5.0.1 (form-data@0.2.0, combined-stream@0.0.7, mime-types@2.0.14, m
ime-db@1.12.0, async@0.9.2, delayed-stream@0.0.5)
├── concat-stream@1.5.1 (readable-stream@2.0.6, isarray@1.0.0)
├── sane@1.4.0 (minimist@1.2.0)
├── babel-generator@6.11.3 (source-map@0.5.6)
├── git-repo-info@1.1.4
├── underscore.string@3.3.4
├── broccoli-config-replace@1.1.2 (fs-extra@0.24.0, broccoli-plugin@1.2.1)
├── markdown-it-terminal@0.0.3 (ansi-styles@2.2.1, lodash.merge@3.3.2, lodash.is
plainobject@3.2.0, lodash.keysin@3.0.8, markdown-it@4.4.0)
├── broccoli-caching-writer@2.2.1 (broccoli-kitchen-sink-helpers@0.2.9, glob@5.0
.15)
├── clean-css@3.4.18 (commander@2.8.1)
├── doctrine@1.2.2 (esutils@1.1.6, isarray@1.0.0)
├── got@5.6.0 (isarray@1.0.0, readable-stream@2.1.4)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── typings-core@0.3.1 (repeating@2.0.1, detect-indent@4.0.0)
├── tap-parser@1.2.2 (readable-stream@2.1.4, isarray@1.0.0)
├── broccoli-uglify-js@0.1.3 (async@0.2.10, yargs@3.5.4, wordwrap@0.0.2, uglify-
js@2.4.24, source-map@0.1.34)
├── inline-source-map-comment@1.0.5 (minimist@1.2.0)
├── uglify-js@2.7.0 (async@0.2.10, source-map@0.5.6)
├── duplexer2@0.1.4 (readable-stream@2.1.4, isarray@1.0.0)
├── espree@3.1.6 (acorn@3.2.0)
├── read-all-stream@3.1.0 (isarray@1.0.0, readable-stream@2.1.4)
├── typescript@1.8.10
├── defs@1.1.1 (window-size@0.1.4, yargs@3.27.0)
├── handlebars@4.0.5
├── typings@0.8.1 (wordwrap@1.0.0, bluebird@3.4.1, minimist@1.2.0)
├── ember-router-generator@1.2.1 (esprima@2.7.2, recast@0.11.10, ast-types@0.8.1
7, source-map@0.5.6)
├── json5@0.4.0
├── rc@1.1.6 (minimist@1.2.0)
├── node-notifier@4.6.0 (minimist@1.2.0)
├── testem@1.9.1 (bluebird@3.4.1)
├── table@3.7.8 (ansi-regex@2.0.0, strip-ansi@3.0.1, bluebird@3.4.1)
├── systemjs-builder@0.15.20 (source-map@0.5.6, babel-core@6.10.4, babylon@6.8.4
, bluebird@3.4.1)
├── babel-plugin-proto-to-assign@1.0.4 (lodash@3.10.1)
├── mout@1.0.0
├── lodash-node@2.4.1
├── traceur@0.0.105 (glob@5.0.15, semver@4.3.6)
├── es5-ext@0.10.12
├── core-js@1.2.6
├── ember-cli-preprocess-registry@2.0.0 (lodash@3.10.1)
├── babel-core@5.8.38 (minimatch@2.0.10, source-map@0.5.6, lodash@3.10.1)
├── lodash@4.13.1
├── babel-register@6.9.0 (source-map@0.5.6, babel-core@6.10.4, babylon@6.8.4, co
re-js@2.4.0)
├── babel-runtime@6.9.2 (core-js@2.4.0)
├── npm@3.10.2
├── bower@1.7.9
└── ember-cli@2.5.0 (glob@7.0.3, fs-tree-diff@0.4.4, fs-extra@0.26.7, broccoli-p
lugin@1.2.1, npm@2.14.21)

C:\windows\system32>ng new my-project
(node:14976) fs: re-evaluating native module sources is not supported. If you ar
e using the graceful-fs module, please update it to a more recent version.
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\environment.ts
  create src\app\index.ts
  create src\app\shared\index.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\system-config.ts
  create src\tsconfig.json
  create src\typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config\environment.dev.ts
  create config\environment.js
  create config\environment.prod.ts
  create config\karma-test-shim.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
| Installing packages for tooling via npm
├── es6-shim (global)
├── angular-protractor (global dev)
├── jasmine (global dev)
└── selenium-webdriver (global dev)

Installed packages for tooling via npm.

C:\windows\system32>npm install --save @angular2-material/core @angular2-materia
l/button @angular2-material/card
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/angular2-material/core)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/angular2-material/card)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/angular2-material/button)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:angular2-material/card)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:angular2-material/core)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:angular2-material/button)
npm ERR! git clone git@github.com:angular2-material/card Cloning into bare repos
itory 'C:\Users\dennisg.FMSI.COM\AppData\Roaming\npm-cache\_git-remotes\git-gith
ub-com-angular2-material-card-6510cd18'...
npm ERR! git clone git@github.com:angular2-material/card Host key verification f
ailed.
npm ERR! git clone git@github.com:angular2-material/card fatal: Could not read f
rom remote repository.
npm ERR! git clone git@github.com:angular2-material/card
npm ERR! git clone git@github.com:angular2-material/card Please make sure you ha
ve the correct access rights
npm ERR! git clone git@github.com:angular2-material/card and the repository exis
ts.
npm ERR! git clone git@github.com:angular2-material/button Cloning into bare rep
ository 'C:\Users\dennisg.FMSI.COM\AppData\Roaming\npm-cache\_git-remotes\git-gi
thub-com-angular2-material-button-cabe3f74'...
npm ERR! git clone git@github.com:angular2-material/button Host key verification
 failed.
npm ERR! git clone git@github.com:angular2-material/button fatal: Could not read
 from remote repository.
npm ERR! git clone git@github.com:angular2-material/button
npm ERR! git clone git@github.com:angular2-material/button Please make sure you
have the correct access rights
npm ERR! git clone git@github.com:angular2-material/button and the repository ex
ists.
npm ERR! addLocal Could not install angular2-material/card
npm ERR! Error: ENOENT: no such file or directory, stat 'C:\windows\system32\ang
ular2-material\card'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocola
tey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@a
ngular2-material/core" "@angular2-material/button" "@angular2-material/card"
npm ERR! cwd C:\windows\system32
npm ERR! node -v v6.3.1
npm ERR! npm -v 1.4.9
npm ERR! path C:\windows\system32\angular2-material\card
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! addLocal Could not install angular2-material/button
npm ERR! git clone git@github.com:angular2-material/core Cloning into bare repos
itory 'C:\Users\dennisg.FMSI.COM\AppData\Roaming\npm-cache\_git-remotes\git-gith
ub-com-angular2-material-core-bf428d36'...
npm ERR! git clone git@github.com:angular2-material/core Host key verification f
ailed.
npm ERR! git clone git@github.com:angular2-material/core fatal: Could not read f
rom remote repository.
npm ERR! git clone git@github.com:angular2-material/core
npm ERR! git clone git@github.com:angular2-material/core Please make sure you ha
ve the correct access rights
npm ERR! git clone git@github.com:angular2-material/core and the repository exis
ts.
npm ERR! addLocal Could not install angular2-material/core
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\windows\system32\npm-debug.log
npm ERR! not ok code 0

C:\windows\system32>npm install --save @angular2-material/core
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/angular2-material/core)
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:angular2-material/core)
npm ERR! git clone git@github.com:angular2-material/core Cloning into bare repos
itory 'C:\Users\dennisg.FMSI.COM\AppData\Roaming\npm-cache\_git-remotes\git-gith
ub-com-angular2-material-core-bf428d36'...
npm ERR! git clone git@github.com:angular2-material/core Host key verification f
ailed.
npm ERR! git clone git@github.com:angular2-material/core fatal: Could not read f
rom remote repository.
npm ERR! git clone git@github.com:angular2-material/core
npm ERR! git clone git@github.com:angular2-material/core Please make sure you ha
ve the correct access rights
npm ERR! git clone git@github.com:angular2-material/core and the repository exis
ts.
npm ERR! addLocal Could not install angular2-material/core
npm ERR! Error: ENOENT: no such file or directory, stat 'C:\windows\system32\ang
ular2-material\core'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocola
tey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@a
ngular2-material/core"
npm ERR! cwd C:\windows\system32
npm ERR! node -v v6.3.1
npm ERR! npm -v 1.4.9
npm ERR! path C:\windows\system32\angular2-material\core
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\windows\system32\npm-debug.log
npm ERR! not ok code 0

C:\windows\system32>
