### ISSUE TITLE
Cannot find module '../lib/config/schema'.

### ISSUE THREAD

**Issue by Mani2693** [angular/angular-cli#8365]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

![image](https://user-images.githubusercontent.com/11607412/32434368-eb8a9166-c303-11e7-8cd2-9f037b06d23d.png)

### Repro steps.

With the below package.json , I perform "npm start" -> ng serve 
![image](https://user-images.githubusercontent.com/11607412/32434478-3b544ce6-c304-11e7-844f-4e9064603fc4.png)

### The log given by the failure.

Build gets to 92% and gives below error 
![image](https://user-images.githubusercontent.com/11607412/32435080-f9a2636c-c305-11e7-8528-81c175c6a5f3.png)

### Desired functionality.

I am using below project and facing the issue :  https://github.com/microsoftgraph/angular-connect-rest-sample

**Comment by filipesilva** [comment]
Heya, can you try using the latest version of the CLI in the project instead? Right now that is `1.2.7`, and you are using `1.2.7`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
