### ISSUE TITLE
Adding a route doesn't add imports to app component

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#840]
On the latest master, and on Windows machines, adding a route doesn't add imports to the App Component.

Repro steps on a windows machine:
```
ng new foo
cd foo
ng build
ng g r my-route
ng build # this will fail compilation
```

At this point, `foo.component.ts` looks like this (note the missing imports):

```
import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'foo-app',
  templateUrl: 'foo.component.html',
  styleUrls: ['foo.component.css']
,
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
export class FooAppComponent {
  title = 'foo works!';
}
```

**Comment by gdboling** [comment]
Seems to add them correctly on OSX.

**Comment by filipesilva** [comment]
@Brocco also tried on OSX, and reported it was fine. Not sure why it happens on my windows machine though.

**Comment by st-clair-clarke** [comment]
I logged this issue almost at week ago and no one cared to comment at [https://github.com/angular/angular-cli/issues/830](https://github.com/angular/angular-cli/issues/830)

I am happy that someone else logged the issue because I have been stucked since waiting for some resolution.

I note that @gdboling and @Brocco tried it on OSX and it worked, but some of us do use Windows on which it does NOT work. All other commands worked as expected, but not the route command. I hope that authors will look into this issue sooner rather than later.

Cheers

**Comment by filipesilva** [comment]
@st-clair-clarke apologies, going over the issue backlog has been a slow process and only now am I getting this far. I'll close your issue in favor of this one, just because it has more feedback in it.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/911
