### ISSUE TITLE
Stuck at download via NPM

### ISSUE THREAD

**Issue by bidipeppercrap** [angular/angular-cli#8453]
Always stuck download the CLI at this webpack, I've waited for 1 day still no progress!!!.
What to do? Tried 5 times still didn't work, what a waste of my time.
I need help!

[CLICK HERE FOR IMAGE](https://pbs.twimg.com/media/DOW4W2iUQAAC4td.jpg:large)

**Comment by JinsPeter** [comment]
Are you connected to internet. ? It doesnt take 1 day. Your issue is not at all clear.
Do u use nodejs source code installer. If not use [https://nodejs.org/en/download/](from here).
Use command
npm install -g @angular/cli.
Make sure you are connected to internet. Otherwise, these things does not work.
if you wait 1 whole day and is not getting this thing done. Rest assured that, its not NPM or CLI problem, its your internet or package manager problem.

**Comment by Brocco** [comment]
I agree that this is not a CLI issue.

Please consult npm (or yarn) documentation to ensure your environment is set up correctly. Good luck.

**Comment by bidipeppercrap** [comment]
I'm connected.
It's 5.5.1 as well. Wierd.
I'll try with disabling AntiVirus.

**Comment by bidipeppercrap** [comment]
Is there any way to install angular without npm? or you can say git clone?
