### ISSUE TITLE
validate enum values in templates 

### ISSUE THREAD

**Issue by amineparis** [angular/angular-cli#8468]
When using bad value for enum type in component class I get :
` Property 'BadValue' does not exist on type 'typeof ActionState'.` This is a greate feature ! Why we don't have the same when using enums on templates. the current behaiviour is that the error occurs silently.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
