### ISSUE TITLE
Wiki Story Universal Rendering: missing ModuleMapLoaderModule  

### ISSUE THREAD

**Issue by feloy** [angular/angular-cli#8550]
In the "Angular Universal Integration" wiki page (https://github.com/angular/angular-cli/wiki/stories-universal-rendering), I think that the inclusion of ModuleMapLoaderModule in the AppServerModule is missing:
```
import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
+import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

import {AppModule} from './app.module';
import {AppComponent} from './app.component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  imports: [
    // The AppServerModule should import your AppModule followed
    // by the ServerModule from @angular/platform-server.
    AppModule,
    ServerModule,
+    ModuleMapLoaderModule
  ],
  // Since the bootstrapped component is not inherited from your
  // imported AppModule, it needs to be repeated here.
  bootstrap: [AppComponent],
})
export class AppServerModule {}
```

**Comment by mgol** [comment]
This also affect what `ng generate universal <name>` generates.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
