### ISSUE TITLE
No vendor chunk when Wiki says vendor chunk is true by default - CLI 1.5.3

### ISSUE THREAD

**Issue by Swellenator** [angular/angular-cli#8586]
### Versions
```
Angular CLI: 1.5.3
Node: 8.4.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.3
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.5
typescript: 2.6.1
webpack: 3.8.1
```

### Repro steps
```
ng build --prod
Hash: 6089f98c9d995de864aa
Time: 176725ms
chunk {0} main.34c2fb4b05da249393db.bundle.js (main) 3.97 MB [initial] [rendered]
chunk {1} styles.f1b5f293ba4b13abcdbb.bundle.css (styles) 618 kB [initial] [rendered]
chunk {2} inline.48dff7d85670862c6bca.bundle.js (inline) 1.43 kB [entry] [rendered]
```

### Desired behavior
The wiki says 

> vendor-chunk
> --vendor-chunk (aliases: -vc) default value: true
> Use a separate bundle containing only vendor libraries.

Yet there is no vendor bundle. Did this change? Is the documentation out of date? Why did it change? Is there some guidance one way or another as to why we should have a vendor chunk or not?

I can see that it would be useful for caching (assuming it gets the same hash if the content doesn't change)?  Is there any benefit in splitting and having two parallel requests?

**Comment by devoto13** [comment]
Yes, it was changed by [this commit](https://github.com/angular/angular-cli/commit/0eb25be6ffa68efc3e8a7b628e35f7ab67739e44). Essentially vendor chunk is disabled, when build optimizer is enabled as this improves results of tree shaking. And since build optimizer is enabled by default for --prod builds the vendor chunk is disabled.

I think it should be added to this section of documentation: https://github.com/angular/angular-cli/wiki/build#--dev-vs---prod-builds.

Because of tree shaking and minification you will often get different bundle hash even when changing application code only, so it is less useful for production builds now. In development it is still very useful to improve rebuild speed as there is no tree-shaking involved, hash stays the same and there is no need to rebuild vendor files, when something in the application is changed.

**Comment by Swellenator** [comment]
Yes, definitely should be updated in the documentation where you say as a side effect of `--prod`. It would also be good to document the reasons why it is not enabled by default as you outline.

**Comment by filipesilva** [comment]
I thought we had actually added this to the docs but it looks like we haven't. Thanks for making an issue for it!

**Comment by trsh** [comment]
@filipesilva

And why exactly build-optimizer and vendor-chunk can not co-exist?
