### ISSUE TITLE
Unable to create angular 4 application

### ISSUE THREAD

**Issue by devcer** [angular/angular-cli#8587]
### Versions
```
Angular CLI: 1.5.3
Node: 8.4.0
OS: linux x64
Angular: 
```

### Repro steps
* was creating new app using `ng new app-name --ng4`
* gives error ng4 is not defined

### Observed behavior
```
It should create a angular 4 application
```

### Desired behavior
any other alternative to create a angular 4 application using angular cli?

**Comment by mkamranhamid** [comment]
i guess thats something possible with old cli cos i'm getting this
 `The option '--ng4' is not registered with the new command. Run `ng new --help` for a list of supported options.` 
when i run `ng new app-name --ng4` yoi

**Comment by filipesilva** [comment]
The `--ng4` flag existed briefly on older CLI versions right after Angular 4 was released, and we've since removed it.

You can change the generated app to use Angular 4 instead by editing the generated `package.json` and changing the versions. 

We encourage you to use the lates Angular version though. There isn't much benefit to using older Angular versions.

**Comment by guify** [comment]
Thanks for the package.json help. No thanks, I think I'll skip Angular 5 through 22. I might pick up Angular 23. It's all open source, right?
