### ISSUE TITLE
Crash if Route's Resolve name is constant

### ISSUE THREAD

**Issue by jhcao23** [angular/angular-cli#8636]
## Route[] and `constant`
We usually specify a `RoutingModule` or similar thing to provide `Route[]`.
sometimes we provide `resolve` for the `Route & Component`, for example, `{path: COURSE, component: CourseComponent, resolve: {'course': CourseResolve } }`; however, if replace the resolve name to a constant such as `{path: COURSE, component: CourseComponent, resolve: { [COURSE]: CourseResolve } }` the APP will crash when we do `ng build` or `ng serve`.
I just simply made this simple change to a template project generated by `ng new`.

Please look at my public repo: [https://github.com/jhcao23/angular-cli-crash-constant-route-resolve-name.git](https://github.com/jhcao23/angular-cli-crash-constant-route-resolve-name.git).

### Versions
```
Angular CLI: 1.5.4
Node: 8.9.1
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps
Please open file `routes.module.ts` and please read my comment:
- if no `export` before `const routes: Routes = [...]`, it works fine if running `ng serve -open`.
- in all other cases, it crashes!

### Observed behavior
Possible crash reports (`ng serve`):
 - `ng serve`:
```
ERROR in TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (/template/node_modules/@angular/compiler/bundles/compiler.umd.js:28600:21)
    at listLazyRoutes (/template/node_modules/@angular/compiler/bundles/compiler.umd.js:28575:49)
    at visitLazyRoute (/template/node_modules/@angular/compiler/bundles/compiler.umd.js:29995:47)
    at AotCompiler.listLazyRoutes (/template/node_modules/@angular/compiler/bundles/compiler.umd.js:29963:20)
    at AngularCompilerProgram.listLazyRoutes (/template/node_modules/@angular/compiler-cli/src/transformers/program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/template/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/template/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (/template/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:538:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
- `ng serve -aot`:
```
ERROR in Error: Error encountered resolving symbol values statically. 
Expression form not supported (position 9:57 in the original .ts file), 
resolving symbol routes in /template/src/app/routes/routes.module.ts, 
resolving symbol RoutesModule in /template/src/app/routes/routes.module.ts, 
resolving symbol RoutesModule in /template/src/app/routes/routes.module.ts, 
resolving symbol RoutesModule in /template/src/app/routes/routes.module.ts
```

**Comment by filipesilva** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://angular.io/guide/metadata
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.
