### ISSUE TITLE
Angularcli 1.5.4 webpack uses const. Phantomjs gets error

### ISSUE THREAD

**Issue by markqian** [angular/angular-cli#8642]
1. install angularcli 1.5.4 using npm install
2. create a sample repo
3. run ng serve
4. install phantomjs
5. run phantomjs on the webpage with any script

Errors I got was "invalid token const..." in vendor.js, outputted by phantomjs.
My tsconfig.json file is:

{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es6",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

It was working for version 1.3.0, but since i upgrade to angular 5 and cli version 1.5.4. I been getting this error.

tested on chrome version 62 and windows 10.

**Comment by filipesilva** [comment]
Webpack overall is moving to use `let` and `const`, dropping support for over browsers (`phantomjs` uses its own browser).

This isn't something that we're going to work around since we've never really recommended using `phantomjs` and it hasn't been updated in a very long time. My suggestion is that you use a test runner that is more up to date. Most test runners today have support for Chrome in headless mode for instance.
