### ISSUE TITLE
ng command not found on archlinux

### ISSUE THREAD

**Issue by ubgen** [angular/angular-cli#8663]
Hello, 
I am trying to start a MEAN project with Angular Cli, the problem is that bash does not find ng command.

N.B.
I installed @angular/cli locally, not globally. Here is my npm list --depth=0 output:

[ubarch@ubarch_725_g2 ~]$ npm list --depth=0
ubarch@1.0.0 /home/ubarch
├── @angular/cli@1.5.4
├── express@4.16.2
├── node@8.9.1
├── npm@5.5.1
├── rxjs@5.5.2
└── webpack@3.8.1

![npm_list](https://user-images.githubusercontent.com/28753134/33421974-41af6072-d5b4-11e7-8b7e-e2b9af538fd7.png)

I found ng into the path **~/node_modules/@angular/cli/bin** and I can execute it if I call using ./ng, the output is in the following screeshot.

![ng_version](https://user-images.githubusercontent.com/28753134/33421981-46f49b7e-d5b4-11e7-8543-3926f870a1ec.png)

What have I do to make ng usable without invoking it with ./ ?

**Comment by filipesilva** [comment]
Angular CLI can either be install globally (`npm i -g @angular/cli`) or locally on a project (same command but without `-g`).

In your case you're installing it locally but not on a project. You're just installing it in your user directory. That won't work because your user directory is not really a CLI project.

I recommend that you either do a global install or create a real project to install Angular CLI in. Then you can add a npm script to your `package.json` that calls it (e.g. `"ng": "ng",`) and call commands with `npm run ng -- args --flags`).

That way you get a fully local CLI. But the half local half global approach you're trying is not supported.

**Comment by ubgen** [comment]
Thank you very much for the advice, I didn't know.
