### ISSUE TITLE
locale flag is ignored by 'ng serve/build' in JIT mode

### ISSUE THREAD

**Issue by nikklassen** [angular/angular-cli#8682]
### Versions
```
Angular CLI: 1.5.4
Node: 8.9.0
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

* Start with a clean "ng new" repo
* Add `@Inject(LOCALE_ID) locale` to the constructor of app.component.ts
* `ng serve --locale 'fr'`

### Observed behavior

The injected value of `LOCALE_ID` in app.component.ts is 'en-US'

### Desired behavior

The injected value of `LOCALE_ID` is 'fr'

### Mention any other details that might be useful (optional)

Running `ng serve --aot --locale fr` gives the expected behaviour.

**Comment by filipesilva** [comment]
@ocombe can you have a look please?

**Comment by ocombe** [comment]
The --locale parameter only works for AOT (because the aot compiler is called programatically by the CLI when we build the application, and we can pass the locale parameter).
For the JIT compiler you have to define the providers yourself at runtime.
See the documentation here: https://angular.io/guide/i18n#setting-up-the-locale-of-your-app

**Comment by nikklassen** [comment]
Thanks for the quick response. Sorry about that, that document has changed since I last looked at it.

**Comment by ocombe** [comment]
No problem, it was updated for Angular v5.
