### ISSUE TITLE
Request to sockjs-node/info does not use port specified in .angular-cli.json but port in browser url

### ISSUE THREAD

**Issue by joerideg** [angular/angular-cli#8705]
### Versions
```
Angular CLI: 1.5.5
Node: 6.12.0
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.5
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1
```
```
node --version: v6.12.0
npm --version: 4.6.1
```

### Repro steps
We have a webapplication that is run on port 9080 which contains iframes with angular apps and rules to forward any requests to a specific url to an angular cli dev server on a different port. Example: a request is made to angular/hippo-projects to the webapplication running on port 9080, which it forwards to the angular cli dev server running on port 9092. 

### Observed behavior
The request to sockjs-node/info is done to port 9080 and *not* the specified port in the .angular-cli.json serve port property. Resulting in
```
GET http://127.0.0.1:9080/sockjs-node/info?t=1512123674532 404 ()
[WDS] Disconnected!
```

### Desired behavior
The request to /sockjs-node/info should use the same port as specified in .angular-cli.json

### Mention any other details that might be useful (optional)
The WDS Disconnect does not happen when opening the angular app directly in a browser tab (so not via the iframe in the webapplication on port 9080), because then the url port is the same as the web-dev-server port and the request to /sockjs-node/info succeeds.
Also tried @angular/cli 1.6.0-rc.1, which has the same results as @angular/cli 1.5.5

**Comment by clydin** [comment]
This is intentional behavior.  The public facing address and port are the only reliable connection information the live reload client can use.  If there is a difference between the dev server's bound address and the address used to connect to the web application, then the typical scenario is that the dev server is _internal_ and not accessible to the web browser (e.g., proxy setup, docker container, etc.).  The address/port that the live reload client uses can be manually configured using the `ng serve` command's `--public-host` option if a more atypical use case is presented.

If this does not solve the problem, please re-open the issue.

**Comment by joerideg** [comment]
Thanks! I missed that option in the wiki. This solved my problem.
