### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Class constructor Lh cannot be invoked without 'new'

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular-cli#8910]
I get this error, and it happens only if I use es6 and production.

```
main.16ed0bb01156b27f659a.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: Class constructor Lh cannot be invoked without 'new'
TypeError: Class constructor Lh cannot be invoked without 'new'
```

So the same code base is fine if run with es5 dev/prod or es6 dev only.

### Versions
```
Angular CLI: 1.6.0
Node: 8.4.0
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/schematics: 0.0.10
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps

- Clone this repo: https://github.com/ShinDarth/angular-test-app
- npm install
- ng serve --prod
- open the app with the browser

you will see the error in the browser console

### Observed behavior

The app is broken and there is that error in the console. Happens only if es6 AND production.

### Desired behavior

It should always run fine, no matter of es5/es6 or prod/dev.

**Comment by IlyaSurmay** [comment]
this was originally created here https://github.com/valor-software/ngx-bootstrap/issues/3252 
It happens when you build project with es6 & AOT. So non-prod build with AOT has this error as well.
I figured out that the main reason in rxjs version. If you downgrade it to 5.4.3, everything works as expected, but 5.5+ seems to break the app. So I think this is more related to rxjs, not angular CLI. I'll create an issue in rxjs repo as well.

Does someone have any idea about why it's happening this way? I don't see any breaking changes notes in rxjs changelog

**Comment by IlyaSurmay** [comment]
Also want to notice that in the stack trace I see a link to the es5 file but our lib has es2015 bundle. Seems like it's ignored

**Comment by ShinDarth** [comment]
Bug still present in:

```
Bug still present in:

```
Angular CLI: 1.6.4
Node: 8.9.1
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.37
@angular-devkit/core: 0.0.24
@angular-devkit/schematics: 0.0.45
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.12
typescript: 2.6.2
webpack: 3.10.0
```

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
