### ISSUE TITLE
Angular CLI 1.6.1 Requires NPM Install after ng generate universal

### ISSUE THREAD

**Issue by Vandivier** [angular/angular-cli#8915]
feel free to close as I'm not providing the boilerplate info, but here's the issue and solution:

Issue:
1. install angular-cli 1.6.1 (and all peer deps)
1. `ng new <name>`
1. `cd <name>`
1. [As instructed](https://blog.angular.io/angular-5-1-more-now-available-27d372f5eb4e): `ng generate universal <name>`
1. `ng serve`
1. Get err that http isn't there
1. Install http
1. `ng serve`
1. issue persists

![image](https://user-images.githubusercontent.com/5559355/34090484-4e863de6-e385-11e7-8bbe-14bde96b031e.png)

Solution:
within the generated project folder `./<name>`, run `npm install`
now `ng serve` works

![image](https://user-images.githubusercontent.com/5559355/34090547-dcbd0de2-e385-11e7-9cb3-6aad4f59dd98.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
