### ISSUE TITLE
Generate component to ClientApp/app/components in ASP. NET Core with Angular Application

### ISSUE THREAD

**Issue by phuongthuan** [angular/angular-cli#8970]
Hi you guys,

I have stuck when I'm trying to generate a component to ClientApp/app/components. 
In this ClientApp project ASP NET core. It has three modules are: 
**app.browser.module.ts,**  **app.server.module.ts** and  **app.shared.module.ts**.

Now when I type: 

`ng g c product --module app.shared.module.ts`
An issue occurred:
`Error: obs.pipe is not a function
obs.pipe is not a function`

Can you tell me what's going on or where I'm doing wrong?

**Comment by homapm** [comment]
Hi
In my case, the angular.json file was missing in the project. 
I had created the project using 
**dotnet new angular my-proejct-name**

I created another project using **"ng new project-name"** and copied the **angular.json** project in root of  the project - and set ClientApp in the root property:

`"root": "ClientApp"`

**Angular CLI : 8.3.4
Angular : 4.2.5
Node: 10.16.3**

```

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "hello-world": {
      "projectType": "application",
      "schematics": {},
      "root": "ClientApp",
      ....
```

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
