### ISSUE TITLE
Angular-cli installation issue on windows 8.1

### ISSUE THREAD

**Issue by praveenbommali** [angular/angular-cli#8985]
### node 8.6.0
npm 5.3.0
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows 8.1
-->
```

### Repro steps
Angular-cli installation  was struck  at  following  scenario,  after that even waiting for hours , its  not progressed further. 

> >npm install -g -f @angular/cli   
> npm WARN using --force I sure hope you know what you are doing.   [ ...............] \ fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 checking installable status

### Observed behavior
```
 Installation  struck  at  chokidar  package downloading  
```

### Desired behavior
instillation should be complete and ng  should  be recognised 

### Mention any other details that might be useful (optional)
I followed the  to installation  in  two ways  
1)Using  cmd  as admin 
2) Using  git bash shell  
and followed steps are  : 

> npm uninstall -g @angular/cli 
> npm cache clean   
> npm cache verify   
> npm install -g @angular/cli
> --

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

If I had to bet, it is either related to a NPM proxy or to your use of the `-f` flag. There isn't much we can do here to help because you never run Angular CLI, it's `npm` that isn't installing it.
