### ISSUE TITLE
ng generate component is not working 

### ISSUE THREAD

**Issue by Mian007** [angular/angular-cli#9001]
when i try to generate the component via ng generate component . it gives this error
![screenshot_4](https://user-images.githubusercontent.com/26344379/34357945-35d0e5dc-ea6d-11e7-8974-2419a6f58c62.png)

**Comment by NagarajRaju** [comment]
ng generate component pages/about --module=app.module

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
