### ISSUE TITLE
[bug] ng lint --fix 

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular-cli#9017]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular/tsc-wrapped: 4.4.6
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Observed behavior

This `{{ htmlContent}}` on running `ng lint --fix` changes to `{{ htmlConten }}}`

### Desired behavior

Should only fix the whitespace

### Mention any other details that might be useful (optional)

OS: Windows 10

**Comment by filipesilva** [comment]
Heya, this seems to be a bug on `codelyzer` (https://github.com/mgechev/codelyzer/issues/469) that was fixed in `4.0.2` (https://github.com/mgechev/codelyzer/releases/tag/4.0.2). Updating `codelyzer` should fix it.

If it doesn't please open a new issue on the `codelyzer` issue tracker. That is the library that lints Angular templates.
