### ISSUE TITLE
ng serve --aot Reference to a non-exported function

### ISSUE THREAD

**Issue by anjmao** [angular/angular-cli#9027]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.1
OS: darwin x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
When I run `ng serve --aot` I'm getting error what slideToLeftTransition and slideToLeft are not exported even if they are used just in this file.

```ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';
import { trigger, state, animate, style, transition } from '@angular/core';

function slideToLeft() {
    return trigger('slideToLeftTransition', [
        state('void', style({ position: 'absolute', width: '80%' })),
        state('*', style({ position: 'absolute', width: '80%' })),
        transition(':enter', [
            style({ transform: 'translateX(100%)' }),
            animate('0.2s ease-in-out', style({ transform: 'translateX(0%)' }))
        ]),
        transition(':leave', [
            style({ transform: 'translateX(0%)' }),
            animate('0.2s ease-in-out', style({ transform: 'translateX(100%)' }))
        ])
    ]);
}

function slideToLeftTransition() {
    return slideToLeft();
}

@Component({
    selector: 'app-details-view',
    templateUrl: './details-view.component.html',
    styleUrls: ['./details-view.component.scss'],
    animations: [slideToLeftTransition()],
    host: {
        '[@slideToLeftTransition]': ''
    }
})
export class DetailsViewComponent implements OnInit {

    @Input() loading: boolean;
    @Output() close = new EventEmitter();

    constructor() { }

    ngOnInit() {
    }

    closeDetails($e) {
        this.close.emit($e);
    }
}
```

### Observed behavior
```
ERROR in src/app/admin/shared/details-view/details-view.component.ts(19,10): Error during template compile of 'DetailsViewComponent'
  Reference to a non-exported function.
```

### Desired behavior

I should not get these kind of errors if my typescript is actual valid source code and I should not need to export private functions to work just for specific angular aot compiler.

**Comment by filipesilva** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://angular.io/guide/metadata
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.
