### ISSUE TITLE
Unable to run the command 'npm install angular-in-memory-web-api --save'

### ISSUE THREAD

**Issue by salilsingh2008** [angular/angular-cli#9046]
I am unable to run the command - npm install angular-in-memory-web-api --save
Node version  - 8.9.3
NPM version - 5.5.1

Please see attached file for details.
[2017-12-31T06_15_01_379Z-debug.log](https://github.com/angular/angular-cli/files/1595019/2017-12-31T06_15_01_379Z-debug.log)

Can you please help me resolve this issue.

Thanks,
Salil

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

Looking at the log it seems like https://github.com/npm/npm/issues/17671, which is fixed in npm 5.6.0.

**Comment by Crikick** [comment]
I am unable to run the command - npm install angular-in-memory-web-api --save
see the attach file
[Uploading 2019-05-18T19_29_46_677Z-debug.log…]()
