### ISSUE TITLE
Default dev builds to -vc=false

### ISSUE THREAD

**Issue by BustyLoli-Chan** [angular/angular-cli#9082]
### Versions
```
Angular CLI: 1.6.0
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack-angular-externals: 1.0.2
webpack-rxjs-externals: 1.1.0
webpack: 3.10.0
```

### Desired behavior
When hosting angular in index pages not built by the cli we have a statically defined list of includes. 
As production builds no longer create `vendor.bundle.js` we have removed this include from our list; however, now when dev builds are done we get an `Uncaught TypeError: Cannot read property 'call' of undefined`, presumably because whatever functions these are trying to access are wrapped in the vendor bundle that's not included in the page. 

It would be nice if dev builds would also default to `ng build -vc=false` so that lazy people like me can just type `ng build` without our dev builds blowing up. 

This command can be aliased by npm in package.json, but I still have to type `npm run build-dev` or something to do that. Alternatively, it would be nice if there was a way to configure custom default compiler flags for the repo so people could still be lazy and set up the project however they wanted. (I don't know if there is already a way to do this, but if there is, please let me know how)

**Comment by clydin** [comment]
The vendor chunk is on by default for the development target because it greatly improves rebuild time; both with serve and build watch.  Using an npm script allows for customizing the command line options, as mentioned.  The script could be shortened to `bd` if character count is a prime concern.
More comprehensive application option configuration is planned.   This will allow the project to be configured without the need for a variety of command line switches.  For now, the npm script is most likely the best option.

**Comment by fedorl** [comment]
Building a large app with vc=false even with --prod makes little sense to me. In my opinion, It trades minor size optimization for effective download time, especially on app updates. Not sure why the default was changed...
