### ISSUE TITLE
warning "@schematics/schematics@0.0.11" has unmet peer dependency "@angular-devkit/core@0.0.22".

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#9147]
### Versions
```
$ ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.3
Node: 8.5.0
OS: darwin x64
Angular: 
...

```

### Repro steps
yarn global add @angular/cli
ng new my-app 

### Observed behavior
App scaffolds fine but I get this warning from the npm install.

### Desired behavior
No warnings from the npm install

**Comment by riccardopietropala** [comment]
Here the scaffolding gives me `Error: Cannot find module '@angular-devkit/core'`.
Current workaround I install manually the dependency:
I run `yarn add @angular-devkit/core` in `~/.config/yarn/global` and then in the project folder too, after I created it obviously .

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
