### ISSUE TITLE
Incorrect path of ng generate with the custom root path in .angular-cli.json

### ISSUE THREAD

**Issue by NiKlimenko** [angular/angular-cli#9198]
### Versions
```
Angular CLI: 1.6.4
Windows 10.
```

### Repro steps
* Create a simple Angular project via Angular CLI with the changed ```root``` directory in the .angular-cli.json
* Try to generate something via ```ng generate```

### Observed behavior
```
My root path looks like: "root": "./src/demo-app/src"
After execution ng generate module test:
create src/demo-app/src/src/demo-app/src/app/test/test.module.ts (188 bytes)
```

### Desired behavior
Should generate the correct path (not duplicated)

**Comment by Nangal** [comment]
i have also experiencing same issue

**Comment by mikehallishere** [comment]
I can reproduce too. But it works fine when taking off `./`

**Comment by evxn** [comment]
reproduced with `1.6.6`
works fine with `1.6.3`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
