### ISSUE TITLE
Setup Windows CI 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#92]
We should setup appveyor or something similar to run an e2e test on windows. Travis does not support windows VMs.

http://www.appveyor.com/docs/lang/nodejs-iojs

Once setup we should use it to run end-to-end test suite: #90

**Comment by jkuri** [comment]
I successfully configured the Windows CI. 
I must say that appveyor works fine, the only problem is that builds are not running concurrently and the build time exceeds 20min as I configured x86 and amd64 arch for both node versions. Otherwise appveyor really is a Travis CI for Windows environment as they are saying on their webpage. If we use their plan then 2 concurrent jobs are guaranteed, I think, and then build time will be similar to the one we now have in Travis CI. 
[Here](https://ci.appveyor.com/project/jkuri/angular-cli/history) is the history of my test builds and [here](https://raw.githubusercontent.com/jkuri/angular-cli/appveyor/appveyor.yml) is the configuration I used.

/cc @hansl

**Comment by hansl** [comment]
Good job! It's really nice to see this.

Look at the results, there's absolute no reason why we should run both x86b and x64 versions of the CLI tests. Also, we could be more severe with Windows and not run the tests on Node 4, telling people they need node 5 or above for better support.


Let's chat on Slack for the next steps with this (ie. submitting it to the repo and making it required for PRs to get green).

**Comment by hansl** [comment]
I can close this now. This was done with PR #275.  Thanks jkuri!
