### ISSUE TITLE
Adding app-shell breaks down lazy loading on server-side

### ISSUE THREAD

**Issue by krivochenko** [angular/angular-cli#9202]
### Versions
```
Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* git clone git@github.com:krivochenko/lazy.git
* npm install
* build:ssr
* serve:ssr - on this step everything works fine. Including server-side rendering with lazy loading. There isn't errors  in console of server.
* ng generate app-shell --universal-app universal
* build:ssr
* serve:ssr

### Observed behavior
Server-side rendering doesn't work (in source code of page I see only router-outlet). In console of server I get error: 
```
Cannot find module 'app/pages/contacts/contacts.module.ngfactory'
```

### Desired behavior
I expect server-side rendering work without errors.

### Mention any other details that might be useful (optional)
I created simple repo for reproduction of issue by following steps:
* ng new lazy --service-worker --routing
* adding HomeComponent and ContactsComponent for checking lazy loading
* adding universal followed with [guide](https://github.com/angular/angular-cli/wiki/stories-universal-rendering)

Thanks for help

**Comment by krivochenko** [comment]
As I understand, using App Shell have a meaning only if I don't use server-side rendering. If I use Universal-app for server-side rendering, my web-server returns not blank page, so using App Shell is redundant.

But I need some kind of App Shell for PWA, so I have to provide some URL with App Shell by myself without using `ng generate app-shell ...`

Please correct me, if I missed something.

**Comment by FrozenPandaz** [comment]
Hi,

I have investigated this issue to a degree. I also cannot find any way of using app-shells with Universal...

Sorry i wrote a novel, feel free to skip down to the solutions

Conflict:
* Prerendering the app shell is done with the app server module
* The ModuleMapLoaderModule requires a module map, without it the app shell wont render
* It seems extraProviders during bootstrap are the bottom layer of providers
  * Providing a dummy module map or the app shell rendering will fix that but break lazy loaded routes on the server as mentioned by @krivochenko 

# Solutions:
* Yes, you can have a normal server app with an app shell route and have the ngsw-config point to the route with the app shell instead of index.html
  * When someone installs a version of the PWA, it will go to the server rendered route and you will have your app shell
  * You can do this today but it's a little wasteful to have the server generate it at request time
  * It _should_ be possible to prerender the app shell at build time AND server render
* You can write your own post process script to render the app shell but this is what the CLI intends to do for you
* These are possible solutions for the CLI
  * When rendering the app shell, it provides a dummy module map.
    * This should be the simplest/ easiest solution but it adds a (Angular team controlled) dependency to the CLI
  * The ModuleMapNgFactoryLoader is modified to have the module map be optional so that DI doesn't break
    * I had some trouble with this having a null module map even though one was provide in extraproviders in the server executable
    * This also isn't exactly kosher because the module map is pretty much require for the provider to work

@krivochenko Your solution should work, if you need an example, let me know

@hansl @Brocco Should we pursue providing a dummy moule map [here](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/render-universal.ts#L30)?

It would look like

```ts
    const html = await renderModuleFactory(AppServerModuleNgFactory, {
        url: options.url,
        document: index,
        extraProviders: [
            provideModuleMap({})
        ]
    });
```

**Comment by playground** [comment]
@Brocco you mentioned that app shell feature in CLI is not documented when we spoke in ng-atl.  Can you tell me what is the process to get that documented?  Thanks.

**Comment by evanjmg** [comment]
Any update on this? So lazy load caching doesn't work with service workers?

**Comment by alan-agius4** [comment]
I looked into this and the problem is that when using the `RouterModule.forRoot()` in `app.server.module.ts` `NgModuleFactoryLoader` is not being provided as `ModuleMapNgFactoryLoader` from `@nguniversal/module-map-ngfactory-loader` but rather `NgModuleFactoryLoader` from `@angular/core` as the `RouterModule` is bootstrapped in prior to `ModuleMapLoaderModule`

To fix this one need to add the following in `AppServerModule` so that the provider is updated across the board;

```ts
  providers: [{
    provide: NgModuleFactoryLoader,
    useClass: ModuleMapNgFactoryLoader
  }],
``` 

That said, this only works with the latest packages of the dependencies.

Created an example repo here: https://github.com/alan-agius4/universal-lazy-loading-app-shell

**Comment by vikerman** [comment]
@alan-agius4 - The provider should be used at the platform providers level and not the ServerAppModule

https://github.com/angular/universal-starter/blob/master/server.ts#L28

**Comment by alan-agius4** [comment]
@vikerman that does work as well. Thanks for your input

**Comment by csbenjamin** [comment]
@alan-agius4 your solution does not work for me. I keep getting the error: Cannot find module 'app/pages/contacts/contacts.module.ngfactory'

**Comment by csbenjamin** [comment]
I solve my problem doing the following:

``` bash
ng run my-app:app-shell:production
sed -i -e "s/RouterModule.forRoot/\\/\\/ RouterModule.forRoot/g" path/to/app.server.module.ts
ng run my-app:server
sed -i -e "s/\\/\\/ RouterModule.forRoot/RouterModule.forRoot/g" path/to/app.server.module.ts
```

**Comment by alan-agius4** [comment]
Hi @csbenjamin, please note that this issue is closed.

If this issue is still happening even with changes stated in the documentation, please open a new issue with a minimal reproduction and a step by step guide. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by csbenjamin** [comment]
@alan-agius4 Thanks for the reply. Here is the new issue
https://github.com/angular/angular-cli/issues/12921
There I put a repo as you ask
https://github.com/csbenjamin/app-shell-plus-univeral-plus-lazy-routing
