### ISSUE TITLE
Name class with ng genarate component

### ISSUE THREAD

**Issue by pasquelin** [angular/angular-cli#9269]
Hello,

If I run this command line: 

`ng generate component level1/level2/level3`

How can I have a :

class name : Level1Level2Level3Component
selector : app-level1-level2-level3

because i have a conflit if : 

`ng generate component test1/level1/level2/level3`
`ng generate component test2/level1/level2/level3`

Thx

excuse for my english i'am french lol.

**Comment by jburtondev** [comment]
Hey, I assume you are referring to the duplication of the following class: `Level3Component` 
`export class Level3Component implements OnInit {}
`
I have had a look through the source code and I don't think this use case is addressed (unless someone can show otherwise). For now, I would suggest renaming the classes manually.

**Comment by hansl** [comment]
```ng generate component --name=Level1Level2Level3Component --path=test1/level1/level2/level3```

**Comment by srihari1988** [comment]
I get the below warnings when trying to use the parameters 'path' and 'name' with ng generate.
Example: 
ng g module --path modules/sppeoplepicker --name SPPeoplePicker  
(or) 
ng g module --path=modules/sppeoplepicker --name=SPPeoplePicker

The option '--path' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
The option '--path' is not registered with the generate command. Run `ng generate --help` for a list of supported options.
