### ISSUE TITLE
Provide options to enable/disable the removal of decorators and replacement of resources in a prod build with AOT

### ISSUE THREAD

**Issue by Paladinium** [angular/angular-cli#9306]
This is a feature request referring to the prod build with AOT using the CLI. A more general title would be "Provide options to make the applied transformations configurable". For my use case, it is sufficient to just consider the two specific options described below - but other developers might have other use-cases.

### Requirements
It would be very helpful to me and many other developers if the compiler options would provide means to control the removal of decorators in a prod build with AOT. There are two ways that could make it happen. Either in tsconfig.json as a parameter to angularCompilerOptions, e.g.:

```
  "angularCompilerOptions": {
    "aotRemoveDecorators": false
  }
```
Or as a switch to the ng-command, e.g.

`ng build --prod --aotRemoveDecorators=false`

The wording of such an option is yet to be discussed. I personally would favor to distinguish options that are only valid for either AOT or JIT by having a prefix/suffix in the option's name as indicated.

#### Additional Requirement
For the use-case described below, it is also important to replace style and template URLs by their content. This is what is done in JIT mode just a few lines above the referenced code (see link below). Now either the proposed option implies this behavior (which I don't like since it is not obvious) or another option gives the developer control for that behavior, too, e.g.

`ng build --prod --aotRemoveDecorators=false --aotReplaceResources=true`

### Use-Case
There are Angular apps that use standard Angular means. To make those applications run fast, it makes sense to use AOT. However, many of those applications also have a need to build Angular components dynamically and invoke the JIT compiler. I am aware that it seems unusual to use JIT and AOT in one app, but it is also a reality that many applications have this need (just do a search for AOT and JIT in the angular github issues). It has also been shown that it is indeed possible to make AOT and JIT work together (e.g. see https://github.com/angular/angular/issues/15510). However, since the CLI removes the decorators in a prod build, the JIT compiler cannot compile the components and is emitting errors like "Please add a @NgModule annotation".

To make it work nowadays, it requires to hand-craft the build yourself using webpack or another bundler, but it is much more complex. Instead, it would be **much** more convenient to rely on the Angular CLI and use the powerful ecosystem that the CLI provides. The cost of adding such an option seems to me negligible compared to the pain many developers have. And I would highly appreciate if the CLI team would consider it.

### The code responsible for the removal
The code responsible for the removal is located here: https://github.com/angular/angular-cli/blob/5f73a75193bc1217cbfb7f2240355679517cc8d0/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L682

### Workarounds
I don't know any workaround and I would be very happy to hear some. For example, I was wondering if it is possible to override the function "removeDecorators" to just do nothing? Any other ideas?

**Comment by Paladinium** [comment]
For the sake of completeness, I reference some of the issues I found that are related to this feature request (either because the decorators are removed or because developers have issues with AOT and JIT):

https://github.com/angular/angular-cli/issues/6866
https://github.com/angular/angular/issues/15510
https://github.com/angular/angular/issues/20875
https://github.com/angular/angular/issues/20864
https://github.com/angular/angular-cli/issues/5359

**Comment by ocombe** [comment]
@hansl would you accept a pull request for that? If so, in what form: config parameter, cli parameter, something else?

**Comment by Paladinium** [comment]
Thanks a lot, @ocombe , for providing help for this issue!

**Comment by Alekcei** [comment]
Yes, it flag very need

**Comment by pawelkondraciuk** [comment]
I think code you are referring is only removing decorators from `@angular/core`
https://github.com/angular/angular-cli/blob/a47f024b37858a93f022a5060411a41c2fb36414/packages/%40ngtools/webpack/src/transformers/remove_decorators.ts#L33-L37

I agree with you but there should be a better way to decide which decorators should be preserving than preserving all of them. For example, I only need decorated modules from a specific directory.

**Comment by pawelkondraciuk** [comment]
Put `import { NgModule } from './ngmodule.decorator';` in desired file where you want to preserve decorator

**Comment by Paladinium** [comment]
Thanks, @p3x-robot . It's funny, we do the same workaround as you but with Gradle (which is our main build invoking the CLI - not going into details why) just after npm install. It is renaming removeDecorators by replaceResources in angular_compiler_plugin.js. One could also think of applying such a hack as part of the postinstall hook in packages.json if not using gradle. However, this is very unstable meaning that it can break anytime the CLI changes.

This is why I hope that @ocombe , besides being busy with many other tasks, can eventually help to solve this issue. In my view, he understands the pain and the use-cases described in this feature request. 

@p3x-robot : with our help, others should now be able to figure out what to do. I highly appreciate that you shared it here! If you ask me, we should let the Angular guys do their job and avoid adding further comments.

**Comment by benjaminlefevre** [comment]
Could the commit of marcelamsler be merged on angular-cli? I need also to skip removal of decorators in aot mode :(

**Comment by Paladinium** [comment]
In my view, the commit is only 50% correct. For JIT to work, the resources must also be replaced which is the IF condition just above where @marcelamsler made his change where function 'replaceResources' is called. Therefore, instead of having a narrow argument like 'skipRemoveDecorators', maybe a more general like 'enableJitInAot' might provide a higher level of abstraction.

**Comment by benjaminlefevre** [comment]
Yep

I also noticed the build-optimizer option of angular-cli AOT compilation (default: true since Angular 5), is stripping the decorators as well :( so workaround for me, is to apply the hack above, and also to set build-optimizer to false. Definitively too much.....

**Comment by marcelamsler** [comment]
I am sorry my pull-request for this commit was a mistake. I just tried if it could work but it did not. I am planning to do it, but I don't have time at the moment. 

My current work-around is to disable build-optimizer (ng-build --aot --build-optimizer=false) and to re-export the needed decorators

`
import { Component, NgModule } from '@angular/core';

export { NgModule, Component };`

And this is the component I wrote to make dynamic templates possible

`import { Compiler, Input, OnInit, ViewChild, ViewContainerRef } from '@angular/core';
import { Component, NgModule } from '@app/aot.decorators';

/*
 This Component allows you to compile a template at runtime. Just pass in the template, the needed modules and a context. Make sure that
 context is not a complete component, but an object with attributes. Because you would overwrite internal attributes.
 e.g. <cu-dynamic [template]="details.html" [context]="{task: task}"></cu-dynamic>
 With the example above you could use a template like this <div>{{task.id}}</div>
 */
@Component({
    selector: 'cu-dynamic',
    template: '<ng-container #vc></ng-container>'
})
export class DynamicComponent implements OnInit {
    @ViewChild('vc', {read: ViewContainerRef}) viewContainer: ViewContainerRef;

    @Input() public template: string;
    @Input() public modules: any[];
    @Input() public context: any;

    constructor(private compiler: Compiler) {
    }

    public static createComponent(compiler: Compiler, template: string, modules?: any[]): any {
        @Component({template})
        class TemplateComponent {
        }

        @NgModule({
            declarations: [TemplateComponent],
            imports: modules
        })
        class TemplateModule {
        }

        const mod = compiler.compileModuleAndAllComponentsSync(TemplateModule);
        const factory = mod.componentFactories.find((comp: any) =>
            comp.componentType === TemplateComponent
        );

        return factory;
    }

    ngOnInit() {
        const component = DynamicComponent.createComponent(this.compiler, this.template, this.modules);

        const container = this.viewContainer.createComponent(component);
        Object.assign(container.instance, this.context);
        container.changeDetectorRef.detectChanges();
    }
}`

**Comment by marcelamsler** [comment]
That is really all you have to do. It worked for us and we also use forms and ngModel and even the two way binding works. But I hope that we can fix it soon with a compiler-option so, this hack won't be necessary anymore and we can use build-optimizer again. Btw it is also awesome because we don't have to eject the webpack config.

**Comment by Alekcei** [comment]
@marcelamsler from the factories you can get VievDef and renderType. After giving them to the JitCompiler

**Comment by marcelamsler** [comment]
@Alekcei sorry I don't get the context/intention of your comment. Why would I do/need that?

**Comment by Alekcei** [comment]
For ```Some additional info, I also tried to use ngsummary files and pass them to the compiler, like the testcompiler does, it but I was not able to get them.```

**Comment by marcelamsler** [comment]
@p3x-robot how should it be possible to use aot if you don't know the template at compile-time?

**Comment by robwormald** [comment]
We are not going to make any changes to how this works in the short term. The new Ivy view engine (slated to land in 7.0) will allow you to dynamically compose views (note that this is *not* the same thing as  JIT/ $compile does - allowing full compilation is a security risk, and requires a HUGE amount of slow code to be shipped to browsers).

In short, the *output* of the compiler will be a public API, so that you could handwrite (or generate at runtime based on whatever) the same thing the compiler spits out. How you arrive at that point will be up to you. See https://github.com/angular/angular/blob/master/packages/core/test/render3/component_spec.ts#L28-L33 for an example of what that looks like. We will not provide you an API to take a string template and compile it at runtime.

See also https://github.com/angular/angular/blob/master/packages/core/src/reflection/reflection_capabilities.ts#L135 - rather than using a decorator, you could use the longhand syntax (this is what the decorator actually does):
```
import { Component } from '@angular/core';

export class AppComponent  {
  name = 'Angular 5';
}

AppComponent['decorators'] = [{
  type: Component, 
  args: [{
    selector: 'my-app',
    template: 'hello'
  }]
}]
```

This is a private API, is likely to blow up in your face if you rely on it, and is subject to change without warning or mercy, and we will immediately close any issues complaining about it with "I told you so" - again, shipping the JIT compiler to your users is a Bad Idea, and its an *especially* bad idea to take arbitrary, non-trusted input (eg, "I have random people write templates and drop them into a database, and then fetch them at runtime") and run it through the compiler. You have been warned. JIT is for development ONLY. Please do not rely on this behavior for production applications.

**Comment by Paladinium** [comment]
Thanks, @robwormald for taking your time to explain the thoughts of the Angular team on that subject. I do acknowledge many of your points (security, bundle size, performance, ...).

On the other side, I would be very happy if the Angular team could start to honor the need for more dynamic applications. The changes you mentioned for Angular 7 seem to go into that direction. But I am convinced that for web apps with an adaptive UI (e.g. allowing its customers for configuration), a very dynamic solution is required. This could also be a significant differentiator to other web frameworks.

**Comment by marcelamsler** [comment]
@robwormald

Thank you for your explanation. I think it is a mistake to remove template compilation at runtime. I am with you that everybody should be very careful when they decide to use it, because it has some disadvantages (security, performance). But sometimes you just need it. And to assume that everyone who uses it, is just a noob who knows nothing about security, performance or a proper application architecture, is just wrong. ("I have random people write templates and drop them into a database, and then fetch them at runtime")

In our case we are wrapping an other application, which provides forms, we have to display. So it is just not possible to know the html at compile time. Also we have html content that can be defined and shown whenever the customer wants it. And there we need a lot of html features, which we can not avoid by using structured data from server. But these templates are designed by our own staff and we are also running a security check(whitelist) and optimizations on it, on the server side. 

So please consider valid used cases for runtime compilation before removing it from Angular completely.

**Comment by rodrigoEclipsa** [comment]
@Paladinium you have an example of how we could use a module compiled with angular cli, in another application created with angular cli, taking into account that they are not known at compile time

**Comment by laynelin** [comment]
Is there any update of this feature request?
I really wish this feature can be implemented.

**Comment by rodrigoEclipsa** [comment]
I found a viable solution to this problem. can create an angular element
Here is an example:
https://github.com/nrwl/playbook-angular-v6-elements-example

Then insert the script main.js and inline.js at run time and go!

you can create and compile components that can be loaded at run time, this technique does not need the application to know the components at compile time and benefits from the compiler

**Comment by psamusev** [comment]
guys, any updates on it? I faced with this problem during usage of custom decorator. WIth `buildOptimizer: true` I'm getting all my classes without decorators

**Comment by marcelamsler** [comment]
No there is no update...

just set buildOptimizer to "false" and reexport the core decorators if you
need them at runtime. Your own decorator should not be removed by normal
build because it is not a core decorator...

As far as I understand the build optimizer, it does not affect size or
performance in a way that would it make really necessary for a normal sized
app.

**Comment by theknet** [comment]
@marcelamsler From your example above, do I need to know about the @app/aot.decorators?

At the moment during my runtime I'm getting a StaticInjectError:
`Uncaught (in promise): Error: StaticInjectorError[n -> n]: StaticInjectorError(Platform: core)[n -> n]: NullInjectorError: No provider for n! `

Could this be my DI for the Compiler from @angular/platform-browser-dynamic?

**Comment by marcelamsler** [comment]
No, I also use the compiler from core directly. Make sure that all Modules for all components, pipes are passed in in "modules"-input. Also make sure, that your custom components you want to use (and their dependencies are using the re-exported decorators. Here is my current code for the exports:

`import { Component, Directive, HostListener, Input, NgModule, Pipe } from '@angular/core';

export { Component, Directive, HostListener, Input, NgModule, Pipe };`

**Comment by lefoulkrod** [comment]
@robwormald As others have expressed, there are companies (like mine) that want to use Angular but have use cases which would be very well served by being able to dynamically compile an html template into a component at runtime, knowing the risks and performance implications.  You may want to reconsider this as a valid use case.

**Comment by lefoulkrod** [comment]
@marcelamsler I'm able to make this work without re-exporting the decorators.  I only have to set build-optimizer=false.  Of course this increases my output main.js file size by 40%.

**Comment by rodrigoEclipsa** [comment]
@lefoulkrod why not use angular element?

**Comment by dmitry-kostin** [comment]
where is my angular 1.x ...

**Comment by PascalGit1** [comment]
Is there an update or work around for this issue yet?

**Comment by ayerix** [comment]
Here are some of my observations relative to this problem (all 3 ways implies aot compilation enabled and combination of lib with custom decorators and project importing it)

1) the problem is not observed when project imports the lib (with custom decorators) directly (not from node_modules, but from inner folder) and than runs under nginx (not via ng serve --prod, but after it has built with ng build --prod).
2) the problem is not observed when importing project (importing the lib with custom decorators) disables optimization even if it is started with ng serve --prod
3) the problem is not observed when importing project compiles to 'es5' target with ng serve --prod
The problem is raised only when these factors meet together: optimization enabled (by default), es2015 target (by default) and webpack server (also by default). 

Please can somebody tell me whether solutions 1 and 3 are stables workarounds? Can we rely on this not awaiting the knife in our back? What is the preferable way and why 1 and 3 actually works?

Still very waiting this flag (preserving custom annotations)! Angular team, please pay attention to this, your users are unhappy without it! It's actually a kind of trap: you writing custom decorators and all works well until you develop all the stuff. Next you go live of your project and everyghing wraps into a singularity because angular decides you don't need them as well as they don't and "optimizing" it without any care or choose. 
Just have a look at this instruction how to achive this functionality here: https://blog.angularindepth.com/converting-typescript-decorators-into-static-code-using-tsquery-tstemplate-and-transforms-8c65d606a517 It's a kind of Fifty Shades of Grey. Do you think it's normal to rewrite AST tree in 2019 to bring this to project?

**Comment by agrinko** [comment]
I have similar use-case: I need an Angular module which is compiled and stored on a remote server, and loaded into the main app in the runtime. Having in-browser compiler in the AOT build of the main app would solve the issue.

But since there is no solution for this yet, I ended up with a different approach: compiling my remote module as an AOT bundle, using a custom builder script for that. And that is where this great article came handy: https://blog.angularindepth.com/building-extensible-dynamic-pluggable-enterprise-application-with-angular-aed8979faba5

**Comment by dgp1130** [comment]
This came up in a CLI meeting recently. [@robwormald's previous comment](https://github.com/angular/angular-cli/issues/9306#issuecomment-378081686) is still a pretty accurate description of our feelings on the matter. Using JIT in a prod application causes a lot of performance and security issues. JIT is intended for development use only, and we don't expect that to change anytime soon.

**Comment by agrinko** [comment]
Here's a link to a relevant discussion, if anybody still needs AOT-compilation of a separate module which is then included to the main application in the runtime via HTTP request: https://github.com/angular/angular/issues/20875#issuecomment-634818485
