### ISSUE TITLE
ng serve stops loading when it reaches 70% in Ubuntu

### ISSUE THREAD

**Issue by RafaelFronteira** [angular/angular-cli#9318]
Angular CLI: 1.6.5
Node: 8.9.4
OS: linux x64

Hey guys

I'm trying to run my angular 2 application, but when I run 'ng serve' it loads only up to 70%.

On the console is this message that appears:
"70% building modules 748/748 modules 0 active"

I already did the npm uninstall of angular/cli, I installed again and it continues with the same problem.

**Comment by hansl** [comment]
Without a reproduction (a git repo for example), this issue is very hard to investigate. I just verified on a Ubuntu machine and it works with a simple project (angular.io).

I'm closing this, and if you can provide a project where this issue happens and that we can clone locally, please do so and we'll be happy to look at the problem.
