### ISSUE TITLE
Error in 0.js from UglifyJs Unexpected character '`' 

### ISSUE THREAD

**Issue by RkReddy88** [angular/angular-cli#9319]
![webpack](https://user-images.githubusercontent.com/25411057/35236414-3f265ac8-ff75-11e7-9094-5d7274b2206c.PNG)
I am facing publish issue in my Dotnet core angular app with ERROR MSB3073,
![image](https://user-images.githubusercontent.com/25411057/35236144-3f2221fc-ff74-11e7-8c42-1911938b44b6.png)
 which is due to error in 0.js from UglifyJs 
![image](https://user-images.githubusercontent.com/25411057/35236181-5c91cb48-ff74-11e7-9fc5-c94f2e3a8281.png) 

ie.,
![image](https://user-images.githubusercontent.com/25411057/35236259-afa15010-ff74-11e7-8309-1991b1c3ddc1.png)

the function readTag is in the dicom-parser which I am using as a part of rendering dicom images in the browser through cornerstone component(dicom viewer).

the following are my package.json and webpack.json

![packageuglify](https://user-images.githubusercontent.com/25411057/35236407-39c599ea-ff75-11e7-93a9-ec290008fbb0.PNG)

### Versions
Node version v9.4.0
NPM version v5.6.0

please provide some thoughts in fixing this issue.
Thank you in advance

**Comment by tymiao1220** [comment]
I got the same error

**Comment by RkReddy88** [comment]
I am able to publish it after removing the dicom-parser component.,but that's not the fix, are you using the same component.@tymiao1220

**Comment by hansl** [comment]
@RkReddy88 It seems `dicom-parser` distributed code that is not compatible with older browsers. It contains a new feature only available in more recent browsers. If they have a different distribution that's meant to be used in browser you should use that. Otherwise, you should file an issue with them to publish browser compatible bundles.

Closing this as there's nothing we can do in the Webpack plugin.
