### ISSUE TITLE
docker + aspnetcore2 + angular5

### ISSUE THREAD

**Issue by Drewster727** [angular/angular-cli#9390]
All,

I'm running into a very frustrating issue. I'm not sure if it's an npm, angular-cli, or webpack issue.

I'm attempting to run an angular5/aspnetcore2 app inside of a docker container. I've got a dockerfile specified (see below). I am having a tough time figuring out why my dependencies are not loading fully inside the container. When my app goes to run dotnet publish, it bombs out saying I need angular-cli. Even though I'm installing it globally AND running npm install to prep everything inside node_modules.

Keep in mind this app works great locally, outside the docker container.

### Versions

Running ng --version inside my container (after it failed to build)
```
Angular CLI: 1.6.3
Node: 6.12.3
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.0.2
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript-string-operations: 1.1.5
typescript: 2.6.2
webpack-dev-server: 2.11.1
webpack-hot-middleware: 2.21.0
webpack-merge: 4.1.1
webpack: 3.10.0
```
```
root@8895d7d6094b:/app# node -v
v8.9.4
root@8895d7d6094b:/app# npm -v
5.6.0
```

### Repro steps
Dockerfile
```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
USER root

# Copy csproj and restore as distinct layers
COPY *.csproj package.json ./

RUN npm cache clean -f \
	&& npm install -g n \
	&& n lts \
	&& npm install -g @angular/cli@1.6.3 webpack@3.10.0 --unsafe \
        && npm install

WORKDIR /app
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "SMG.HealthCheck.Web.dll"]
```

### Observed behavior
```
   Version: webpack 3.10.0
  Child
      Hash: e4c26685a25d2f5b9478
      Time: 9883ms
                                     Asset    Size  Chunks                    Chunk Names
      89889688147bd7575d6327160d64e760.svg  109 kB          [emitted]
                                 vendor.js  192 kB       0  [emitted]         vendor
                                vendor.css  334 kB       0  [emitted]  [big]  vendor
      Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/bootstrap/dist/css/bootstrap.css:
           1 asset
  Child
      Hash: 3dc1f3d1309fa86f58d0
      Time: 9894ms
                                     Asset     Size  Chunks                    Chunk Names
      89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                                 vendor.js  5.93 MB       0  [emitted]  [big]  vendor
  Hash: 3ffdfd3dc4a66cad1049bfe612d7d9f53ebad322
  Version: webpack 3.10.0
  Child
      Hash: 3ffdfd3dc4a66cad1049
      Time: 4560ms
               Asset    Size  Chunks                    Chunk Names
      main-client.js  284 kB       0  [emitted]  [big]  main-client

      ERROR in ./ClientApp/boot.browser.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.browser.module.ngfactory' in '/app/ClientApp' [/app/SMG.HealthCheck.Web.csproj]
       @ ./ClientApp/boot.browser.ts 5:0-95

EXEC : ERROR in error : Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+ [/app/SMG.HealthCheck.Web.csproj]
          at throwNotSupportedError (/app/packages/compiler-cli/src/ngtools_api.ts:132:9)
          at Function.NgTools_InternalApi_NG_2.codeGen (/app/packages/compiler-cli/src/ngtools_api.ts:80:11)
          at _donePromise.Promise.resolve.then (/app/node_modules/@ngtools/webpack/src/plugin.js:430:58)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Function.Module.runMain (module.js:686:11)
          at startup (bootstrap_node.js:187:16)
          at bootstrap_node.js:608:3
  Child
      Hash: bfe612d7d9f53ebad322
      Time: 4893ms
               Asset     Size  Chunks                    Chunk Names
      main-server.js  2.99 MB       0  [emitted]  [big]  main-server

      ERROR in ./ClientApp/boot.server.ts
Module not found : error : Can't resolve './../$$_gendir/ClientApp/app/app.server.module.ngfactory' in '/app/ClientApp' [/app/SMG.HealthCheck.Web.csproj]
       @ ./ClientApp/boot.server.ts 8:0-94

EXEC : ERROR in error : Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+ [/app/SMG.HealthCheck.Web.csproj]
          at throwNotSupportedError (/app/packages/compiler-cli/src/ngtools_api.ts:132:9)
          at Function.NgTools_InternalApi_NG_2.codeGen (/app/packages/compiler-cli/src/ngtools_api.ts:80:11)
          at _donePromise.Promise.resolve.then (/app/node_modules/@ngtools/webpack/src/plugin.js:430:58)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
          at Function.Module.runMain (module.js:686:11)
          at startup (bootstrap_node.js:187:16)
          at bootstrap_node.js:608:3
/app/SMG.HealthCheck.Web.csproj(108,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.
The command '/bin/sh -c dotnet publish -c Release -o out' returned a non-zero code: 1
```

### Desired behavior
The container builds just fine...

### Mention any other details that might be useful (optional)
I'm really struggling here. Any suggestions would be very much appreciated.

**Comment by filipesilva** [comment]
I'd really like to help you but at the end of the day this is a support request with a huge amount of required setup... It's not something I can test quickly to just give you some insight. For that reason I have to give you the saved reply below that explains why we mostly don't answer support requests.

What I can tell you from the logs you show is:
- You seem to be globally installing `webpack@3.10.0` which I think is odd. I hope that's not happening locally because you'll end up with several different versions of webpack and that will break your app.
- I have no idea what aspnetcore2 is doing with Angular CLI, but I can say that Angular CLI itself works and is tested. Maybe the aspnetcore2 folks know more about what's happening.
- The `Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+` error happens when the old webpack plugin (`AoTPlugin`) is used with Angular v5+ (see https://github.com/angular/angular-cli/blob/master/packages/@ngtools/webpack/README.md). Since the CLI itself switches this over seamlessly, it never happens with Angular CLI. But if a custom setup is not using the right plugin you can get this error. 
- If I had to bet, the aspnetcore2 setup has a custom webpack setup (further evidenced by the console output, which isn't the same as Angular CLI) and it isn't using the new plugin for Angular v5. If this is the case, going down to Angular v4 should sort your problems. But the author of that build setup needs to update the plugins for Angular v5 eventually.

Sorry I can't be more help.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
