### ISSUE TITLE
install latest cli error

### ISSUE THREAD

**Issue by lomo1** [angular/angular-cli#9432]
### Versions
Angular CLI: 1.6.6
npm version：5.6.0
node version: v8.2.1

MacOSX - 10.12
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
uninstall 1.2.0 version: sudo npm uninstall -g @angular/cli
* Step 2
npm cache clean --force
* Step 3
sudo npm install -g @angular/cli@latest

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
anyway, it installed success（after finished install i tried `ng version`, seems ok） but get lots of error in console, like below:
```bash
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/build'
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.6.6
added 1213 packages and updated 1 package in 95.405s
```

### Desired behavior

i am not very sure it's ok or maybe has some potiential influence?

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

I think your specific problem is the permissions one, since using `sudo npm` is known to cause a lot of problems.

**Comment by lomo1** [comment]
@filipesilva  thx ~
