### ISSUE TITLE
Test coverage output color not deactivatable

### ISSUE THREAD

**Issue by lukengda** [angular/angular-cli#9526]
### Versions
```
Angular CLI: 1.6.7
Node: 8.9.4
OS: linux x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Generate new Angular project
* Add coverage text reporters to `karma.conf.js`:
  ```diff
     coverageIstanbulReporter: {
  -      reports: [ 'html', 'lcovonly' ],
  +      reports: [ 'html', 'lcovonly', 'text', 'text-summary' ],
       fixWebpackSourcePaths: true
  ```
* Execute tests with coverage and without colors:
  ```bash
  ng test --code-coverage --colors=false
  ```

### Observed behavior

Both the detailed coverage report listing all files and the coverage report summary in terminal do use colored output.

### Desired behavior

Angular CLI should instruct karma to disable istanbul color output if i set the `--colors=false` option

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
