### ISSUE TITLE
Production build service problem

### ISSUE THREAD

**Issue by petoknm** [angular/angular-cli#953]
I am trying to use a generated service in the main component. When I try to use a generated service in dev environment everything is fine. But when I switch to production is cannot find the service => `GET http://localhost:4200/app/flights.service.js 404 (Not Found)`. The service is not present in the dist folder. Am I doing something wrong? Build is successful but for some reason the service is not there. If it is being bundled into index.js then it should not be requested from flights.service.js, right?

OS: Linux x64, Fedora 23
ng-cli : 1.0.0-beta.5
node: 5.11.1

Reproduction Steps:
Generate a new app using `ng new ng-app`
Generate a new service using `ng g service flights`
Then use the service in the app by adding it to the bootstrap list of dependencies and injecting it into the main component.
Serve it in production mode `ng serve -prod`
Load the app in the browser => `GET http://localhost:4200/app/flights.service.js 404 (Not Found)`

The app that shows the problem: https://github.com/petoknm/angular2-cli-issue
![screenshot from 2016-05-29 10-40-52](https://cloud.githubusercontent.com/assets/5087675/15632169/0261ad66-258a-11e6-9508-cde891e21b2c.png)
![screenshot from 2016-05-29 10-41-45](https://cloud.githubusercontent.com/assets/5087675/15632170/0262e708-258a-11e6-92b6-7cdba662ab2f.png)

Thank you :smile:

**Comment by butters16** [comment]
I can confirm that I've seen the same problem. None of my angular-cli generated services or pipes end up in the dist/app folder when using the -prod option. These files show up as expected using the default (nothing explicitly specified, so defaults to dev) or explicitly specifying -dev. I am using angular-cli@0.0.39. Since @petoknm says this issue still exists in the current version 1.0.0-beta.5, I have not tried upgrading.

**Comment by riblee** [comment]
I can confirm the problem still exists in 1.0.0-beta.5.

**Comment by borntodesign** [comment]
I have just battled against this issue, I added all my files to the index.ts file for applicable sections ("articles/index.ts", "users/index.ts") and updates all the imports. Also for the main app bootstrapping when declaring global services I exported them from the main index file "app/index.ts". This fixed most things although I personally forgot to then order my files based on how things export and the order in which they do so. Now I am trying to figure out why the cli removes my js files from my public folder and where it puts them lol

**Comment by filipesilva** [comment]
@borntodesign is right - the issue was that the services should not be added to `main.ts` but instead to your main component. `main.ts` serves only to bootstrap the app.

Most app files shouldn't appear on `dist/` after `ng build -prod` though, since prod builds are bundled up.

@borntodesign can you open a new issue for the js files in vendor? I think they should be copied over.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1028 was merged in and should be included in beta.6. It should reduce alleviate the scenarios where bundling is broken between `main.ts` and subpackages of `app`.
