### ISSUE TITLE
AngularCompilerPlugin doesn't take input from previous loaders

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular-cli#9559]
### Versions
```
"@ngtools/webpack": "^1.9.8"
```

### Repro steps

* Have multiple loaders in `webpack.config` that are executed before `@ngtools/webpack`. e.g.
```
{
   test: /\.ts$/,
   loader: ['@ngtools/webpack', 'ts-nameof-loader']
}
```
* Use `AngularCompilerPlugin`.
```
new AngularCompilerPlugin({
     tsConfigPath: 'app/tsconfig.json',
     mainPath: helpers.root('app/main.ts'),
     skipCodeGeneration: false
})
```
* Run webpack

### Observed behavior
The loaders before `@ngtools/webpack` are executed, but sinse `AngularCompilerPlugin` ignores the `source` parameter that was passed in, and instead loads the content directly from the file, any preprocessing done by previous loaders is ignored. The `AotPlugin` has some special handling for this case.

### Desired behavior
Input from loaders that are executed before `@ngtools/webpack` is considered.

### Mention any other details that might be useful (optional)
Maybe I'm missing something, and this scenario is not supposed to supported. But it worked before and we have some code depending on this. If that's the case, please let me know if there any supported way to have this working.

**Comment by filipesilva** [comment]
This is indeed something we don't support right now. This is similar, but not the same, as https://github.com/angular/angular-cli/issues/9089. There's some background on that issue about why this is hard.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
