### ISSUE TITLE
Service Worker - Ng Prod in Watch Mode - Future Request

### ISSUE THREAD

**Issue by Max-Lev** [angular/angular-cli#9631]
Hi, is it possible to make service-worker available/generated in a Watch Mode?

At this moment, in case of "ng build --prod -w"  service worked not generated.

**Comment by cyraid** [comment]
I agree this would be a great future so you can test your service workers locally for push notifications.

**Comment by idenisovs** [comment]
@cyraid Any progress on this?

**Comment by cyraid** [comment]
Oh I was just commenting it'd be nice haha .. Though it does look like it's still relevant. Right now I'm sure people would have to rig up copying files through the serve/watch process (to copy your service worker config file) through the angular.json assets config (using globs if necessary), and making sure you're serving on https and your local security certificate has been accepted in the browser (or in the systems cert chains).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
