### ISSUE TITLE
command: ng xi18n gives Environment "dev" does not exist.

### ISSUE THREAD

**Issue by ringodotnl** [angular/angular-cli#9701]
### Versions
Angular CLI: 1.6.8
Node: 8.7.0
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0

### Repro steps
- Create a new NG project
- Remove environment 'dev' from the file angular-cli.json
- cmd: `ng xi18n`

### Observed behavior
Environment "dev" does not exist.

### Desired behavior
No error when you don't have environment dev. 
Optional solution: be able to give it another environment  name then 'dev'

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since there we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
