### ISSUE TITLE
DevDependencies

### ISSUE THREAD

**Issue by Santhamani** [angular/angular-cli#9711]
How to install devDependencies.

What is the difference between dependencies and devDependencies. Which are packages are used while deploying

**Comment by andyg8180** [comment]
this question should be asked on stackoverflow since it is a straight npm/yarn question. But for a kick start, here you go

for [npm ](https://docs.npmjs.com/cli/install)its `npm install your-package-name --save-dev`
for [yarn ](https://yarnpkg.com/lang/en/docs/managing-dependencies/)its `yarn add your-package-name --dev`

**Comment by Santhamani** [comment]
Thank you for the reply.
I have used same command but the packages are not installed in devDependencies.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
