### ISSUE TITLE
Translating PR in to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [angular/angular-cli#9732]
HI! I would like to contribute with this project by offering a translation in to Spanish (my native language) I can translate any PR you want. I work for Utopian-io as translator. Let me know if interested!

**Comment by StephenFluin** [comment]
@LuigiBaute This is awesome that you want to contribute!

I think long term we'd love to have help translating (and maintaining) translations and localization for our sites and documentation, but it's hard to translate our sites right now because we don't currently have the infrastructure to maintain these effectively. The closest thing we have is a branch of angular.io maintained by some Chinese contributors.  (https://github.com/angular/angular-cn)

Are you specifically referring to something in the CLI you are looking to translate, or some piece of our documentation?

**Comment by LuigiBaute** [comment]
I'd like to start translating the README file. see if you guys like it and we can see from there! what do you think?

**Comment by StephenFluin** [comment]
Thank you so much for your interest! We'd love to have your help, but we wouldn't be able to accept your contribution in the main repo yet. This is on our roadmap, but the best way to be involved today would be to make your changes on a branch you maintain, or just wait for us to be more ready to support these sorts of contributions in in a scalable, maintainable way.
