### ISSUE TITLE
Add preprocess script section in angular-cli.json

### ISSUE THREAD

**Issue by claygifford** [angular/angular-cli#9749]
I want to concat css into a single file.
I have to run a separate gulp process.

Thanks for adding it

**Comment by filipesilva** [comment]
Hi @claygifford, this is functionality we already have. Have a look at https://github.com/angular/angular-cli/wiki/stories-global-styles for details.

Bear in mind that in development builds we will make a JS file instead of a CSS file for rebuild speed. But on production builds (`ng build --prod`) you will have the CSS file.

**Comment by claygifford** [comment]
Thanks for the quick reply, that is something different.

I am asking for a 

"styles": ["../css-bundles/**"],

Your answer to that almost 2 years ago was no.

Instead simply allow a pre processing script something like....

function requireAll(r) { r.keys().forEach(r); }
requireAll(require.context('../client', true, /\.css$/));

Or 
gulp-concat-css

**Comment by claygifford** [comment]
https://github.com/angular/angular-cli/issues/3069

Here is your response 2 years ago.

**Comment by filipesilva** [comment]
I understand what you were talking about better now, thank you. Yeah I think the stance our stance still the same though, for the same reasons (https://github.com/angular/angular-cli/issues/3069#issuecomment-261941189):

> We're not looking at adding glob support to `styles`, because loading order is relevant. Instead, just make a single file that imports everything in the order you want and put that in the `styles` array.
