### ISSUE TITLE
[Feature Request] Create components with module flag inside that module folder

### ISSUE THREAD

**Issue by michaeljota** [angular/angular-cli#9815]
### Versions

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Create a new module
```
ng g module feature
```
* Create a new component for that module
```
ng g component some-component -m feature
```

### Observed behavior
The component is created in the `app` folder.

### Desired behavior
The component should be created in the module (`feature`) folder.

### Mention any other details that might be useful (optional)
Currently you can do
```
ng g component feature/some-component -m feature
```
But you are repeating yourself when specify the module route and the module name. Ideally, Angular should now where this module is located, and create the component there.

**Comment by clydin** [comment]
Alternatively, you could do the following:
```
ng g module feature
cd feature
ng g component some-component
ng g component other-component
ng g component third-component
```

**Comment by michaeljota** [comment]
@clydin Thanks. I did not knew that. However, you usually work with `ng` in the root of the application, so your change directory would be like `cd src/app/feature`. Other than that, you suggestion works.

I still believe it should generate the component inside the module specified by the flag, but thanks for the workaround.

**Comment by clydin** [comment]
The most of the CLI commands take the current working directory into account and many of the generate commands were optimized (i.e., simplified command option usage) for use in this manner.

The module option is intended to be a helper option to affect the module rather than the component itself.  And the option is generally only needed when the standard file structure of a component within a module directory is not used.
Also, the standard module discovery logic will walk the directory hierarchy and use the closest module found so components can be nested several levels deep within a module directory and still be automatically added to the module.

**Comment by alan-agius4** [comment]
Hi @michaeljota, thanks for this feature request. However, currently this is not part of the Angular CLI roadmap.

Let's close it for now, and revisit in the future if we see that this is needed.
