### ISSUE TITLE
Vendor Bundle size is huge when i build with angular cli 1.7.1

### ISSUE THREAD

**Issue by arunprasathv** [angular/angular-cli#9818]
I'm having an issue with bundle size. I see the size of vendor bundle is 6.33 MB. 

I'm using below-mentioned version. 

**Command**
ng build prod 

**Versions**

Angular CLI: 1.7.1
Node: 8.9.1
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack-bundle-analyzer: 2.11.0
webpack: 3.11.0

### Repro steps
Command
ng build prod 

Observed behavior
Bundle size is 6.3 MB 
 
Desired behavior
bundle size should in KBs.

**Comment by deebloo** [comment]
the command is `ng build --prod`

**Comment by tosehee75** [comment]
My vendor bundle is 18.5MB and I am using ng build --prod...

**Comment by clydin** [comment]
`ng build --prod` does not generate a vendor bundle by default.

**Comment by arunprasathv** [comment]
@deebloo 
using **ng build --prod,** I could see the size of main bundle reduced to 3.27 MB. I can reduce it more by lazy loading.

**Comment by arunprasathv** [comment]
@deebloo @hansl 

Is there a way to run ng build specifying a project path where package.json exists ?  instead of C:\Projects\Angular, i want to run ng build on c:\Projects

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
