### ISSUE TITLE
How to disable chunk generation?

### ISSUE THREAD

**Issue by gubenkovalik** [angular/angular-cli#9836]
I very want angular to generate just one big js file instead of lots of chunks, it is slowing down navigation
How to disable chunking?

**Comment by Heurazio** [comment]
The build process will generate one chunk for each "lazy loaded" module. If you don't want chunks you should eager load every module. This will result in only a few generated bundle files (main, inline, scripts, polyfills).

Be aware that will drastically delay your first meaningful paint because one "heavy" bundle need to be loaded.

**Comment by clydin** [comment]
Closing as answered by @Heurazio (thank you).
