### ISSUE TITLE
Service Worker, 6.0.0-beta.4, ngsw.json doesn't include js and css bundles

### ISSUE THREAD

**Issue by htdt** [angular/angular-cli#9846]
### Versions
```
Angular CLI: 6.0.0-beta.4
Node: 8.9.4
OS: linux x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 6.0.0-beta.4
@angular-devkit/build-optimizer: 0.4.3
@angular-devkit/core: 0.4.3
@angular-devkit/schematics: 0.4.3
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.4
@schematics/angular: 0.4.3
@schematics/package-update: 0.4.3
typescript: 2.5.3
webpack: 4.0.1
```

### Repro steps

* Create new project `ng new test --service-worker`;
* Build `ng build --prod`.

### Observed behavior
* `css` and `js` bundles in `dist` don't match `src/ngsw-config.json` and are not included in `dist/ngsw.json`;
* Published project is not caching, doesn't support offline mode.

### Desired behavior
`dist/ngsw.json` should include `css` and `js` bundles and publised project should be cached.

**Comment by mackelito** [comment]
Any updates on this?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
