### ISSUE TITLE
[Feature] Ability to include separate "pre-app" bundle

### ISSUE THREAD

**Issue by samherrmann** [angular/angular-cli#9856]
# Feature Request
Is it feasible to add the ability to the CLI to have it build a separate bundle from TypeScript and apply the same build pipeline (lint, test, minify, etc) as for the rest of the app and include it in `index.html` before any of the current script bundles?

# Use Case
I have a requirement to show a message in an Angular app to users who are using an unsupported browser. The app is an internal corporate app where we are spoiled with only needing to support Chrome. We do not want to enable the various [polyfills](https://angular.io/guide/browser-support#polyfills) to support IE since we will not spend resources to test the app in IE. We do however need to notify the user when they are using an unsupported browser. 

# Analysis
When a user uses an unsupported browser, any of the JavaScript bundles generated by the CLI (`inline`, `polyfills`, and `main` located at the bottom of the `body` in `index.html`) may fail due to dependence on features that are not supported in those browsers. That means that the "browser check" code needs to run BEFORE any of the those bundles.

When reviewing [index.html of angular.io](https://github.com/angular/angular/blob/master/aio/src/index.html) for inspiration, I have noticed that they have inline `script`s in the `head` for things like Google Analytics (which is another use case). I can for sure follow the same approach and add my "browser check" code inline in `index.html`. That solution meets the requirement of executing before any of the Angular app bundles. However, when adding scripts inline in `index.html`, we are both polluting the `index.html` source file, and we are also not getting the benefits of TypeScript, linting, testing, minifaction, etc provided out of the box by the CLI for the app.

**Comment by alan-agius4** [comment]
Hi @samherrmann,

Thanks for this feature request. However, at the moment it is not in the roadmap to add this feature as part of the Angular CLI.

In most cases unsupported browsers pages are create in plain HTML+CSS and served via a reverse proxy such as NGINX instead of the actual application when visiting the application with an unsupported user-agent.

Alternatively there are 3rd party services that offer this functionality and can be used by injected a small script in the index file. Ex: http://browser-update.org/

Thanks,
Alan
