### ISSUE TITLE
Not loading assets in 1.6.5 and later versions

### ISSUE THREAD

**Issue by ashahimian** [angular/angular-cli#9865]
I had angular/cli 1.6.3 and loading all files in assets and upgrading later version (1.6.5 and 1.7.1) but not loading them there is a problem in 1.6.5 and later. Please help me for this issue.

![not-loading](https://user-images.githubusercontent.com/31849386/36968414-ae2dbd58-2077-11e8-98b1-58abbae5f7cf.png)
Thanks

**Comment by rahulbhooteshwar** [comment]
@ashahimian can you please provide the details in the required format. That will help in understanding the issue with clarity.

Versions (output of ng -v)
Repro steps
Observed Behavior
Desired Behavior

**Comment by ashahimian** [comment]
Versions (output of ng -v): 1.7.1

Repro steps: angular cli version was 1.6.3 then everything was OK but I updated it to 1.6.5 and higher (1.7.1) the problem happened.

Observed Behavior: During ng serve and ng build angular cli will not at assets then all images and other assets miss

Desired Behavior: angular cli should load assets

Best regards

**Comment by yannickbattail** [comment]
I had the same problem because my project was in "program files (x86)".
Workaroud: copy your project in a folder where the path does not contain space or "("

**Comment by yannickbattail** [comment]
I had the same problem because my project was in "program files (x86)".
Workaround: copy your project in a folder where the path does not contain space or "("

**Comment by ashahimian** [comment]
This solution is good but what other way to not change path?

**Comment by lehtiniemi** [comment]
I can confirm - moving my project to my Dropbox folder (for constant cloud backup) broke the assets folder. (Dropbox folder naming can't be changed, it's "Dropbox (My company)" so it contains parenthesis. It would be great if this would work properly. It's impossible to user the project within any folder that contains ( or ) because it breaks the assets-linking.

I also tried to build the project - the assets-folder isn't bundled in the finished build at all.

I tried to create a symbolic link for the whole Dropbox-folder, but when running ng serve in this linked folder, "ng serve" gave the following errors (sorry for inconsistent / and \, it's because I replaced some pathnames manually):

```
ERROR in c:/Users/My name/Dropbox (My Company)/Koodaus/nordic-sounds/src/main.ts
Module build failed: Error: c:/Users/My name/Dropbox (My Company)/\Koodaus\nordic-sounds\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (c:/Users/My name/Dropbox (My Company)\Koodaus\nordic-sounds\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (c:/Users/My name/Dropbox (My Company)/\Koodaus\nordic-sounds\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
ERROR in c:/Users/My name/Dropbox (My Company)/Koodaus/nordic-sounds/src/polyfills.ts
Module build failed: Error: c:/Users/My name/Dropbox (My Company)\Koodaus\nordic-sounds\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (c:/Users/My name/Dropbox (My Company)\Koodaus\nordic-sounds\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (c:/Users/My name/Dropbox (My Company)/Koodaus\nordic-sounds\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
