### ISSUE TITLE
providing --build-optimizer option with --prod seems to cause the process to hang

### ISSUE THREAD

**Issue by lewmpk** [angular/angular-cli#9974]
### Versions
```
<!--
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.0
Node: 8.8.1
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.7.0
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.3.4
webpack: 3.11.0
-->
```

### Repro steps
* ng build --prod --build-optimizer

### Observed behavior
It seems that it causes the process to hang. I've waited up to 30mins.

### Desired behavior
From what I understand, angular/cli enables the build-optimizer flag if --prod is set. So the expected behaviour should be that providing '--build-optimizer' should have no additional affect

**Comment by WandererInVoids** [comment]
related to this https://github.com/angular/angular-cli/issues/5618

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
